  package com.cloudframe.app.process;
  /* Java code generated by CloudFrame on 2025-04-21 at 12:00. */
  
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.mc154.dto.*;
  import com.cloudframe.app.mc154.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("mc154")
  
  public class Mc154 extends CommonProcess {
  
  Logger logger = LoggerFactory.getLogger(Mc154.class);
  
  private Work work = new Work() ;
  
  
  
  
  
  
  
  
  
      /**
      * process 
      * Input  :  

      * - cnst9999300                    COBOL Name: 300-CNST-9999
      * - cnst1300                       COBOL Name: 300-CNST-1
      * - cnst4300                       COBOL Name: 300-CNST-4
      *
      * Output :  

      * - sys009CntlKey                  COBOL Name: SYS009-CNTL-KEY
      * - cnst9999300                    COBOL Name: 300-CNST-9999
      *
      * @throws CFException
      */
      @Override
      public int process() throws Exception {
       initVars();
			// Declare local variables used in the method
			char[] sys009CntlKey = null;
			short cnst9999300 = 0;
			// End of variable declaration

       try {
       setCodePage("1047");
          // MOVE SPACES TO SYS009-CNTL-KEY
          work.setSys009CntlKey(CONSTANTS.SPACE_10);
          // MOVE 300-CNST-9999 TO SYS009-CNTL-KEY
          work.setSys009CntlKey(work.getCnst9999300ActualString());
//  DISPLAY 'SYS009-CNTL-KEY = ' SYS009-CNTL-KEY
          logger.info("SYS009-CNTL-KEY = {}", new String(work.getSys009CntlKey())); 
          cnst9999300 = work.getCnst9999300();
          sys009CntlKey = work.getSys009CntlKey();
//  IF SYS009-CNTL-KEY ( 300-CNST-1 : 300-CNST-4 ) IS EQUAL TO 300-CNST-9999
          if (compareChars(substring(sys009CntlKey,(work.getCnst1300()-1), (work.getCnst4300() + (work.getCnst1300() - 1)) ),work.getCnst9999300ActualString()) == 0) { 
//  DISPLAY '*IF SYS009-CNTL-KEY = 9999 * SUCCESS *'
              logger.info("*IF SYS009-CNTL-KEY = 9999 * SUCCESS *"); 
          }
  
//  ELSE
          else { 
//  DISPLAY '*IF SYS009-CNTL-KEY = 9999 * FAILURE *'
              logger.info("*IF SYS009-CNTL-KEY = 9999 * FAILURE *"); 
          }
//  MOVE -9999 TO 300-CNST-9999
          work.setCnst9999300(-9999);
          // MOVE SPACES TO SYS009-CNTL-KEY
          work.setSys009CntlKey(CONSTANTS.SPACE_10);
          // MOVE 300-CNST-9999 TO SYS009-CNTL-KEY
          work.setSys009CntlKey(work.getCnst9999300ActualString());
//  DISPLAY 'SYS009-CNTL-KEY = ' SYS009-CNTL-KEY
          logger.info("SYS009-CNTL-KEY = {}", new String(work.getSys009CntlKey())); 
          cnst9999300 = work.getCnst9999300();
          sys009CntlKey = work.getSys009CntlKey();
//  IF SYS009-CNTL-KEY ( 300-CNST-1 : 300-CNST-4 ) IS EQUAL TO 300-CNST-9999
          if (compareChars(substring(sys009CntlKey,(work.getCnst1300()-1), (work.getCnst4300() + (work.getCnst1300() - 1)) ),work.getCnst9999300ActualString()) == 0) { 
//  DISPLAY '*IF SYS009-CNTL-KEY = 9999 * SUCCESS *'
              logger.info("*IF SYS009-CNTL-KEY = 9999 * SUCCESS *"); 
          }
  
//  ELSE
          else { 
//  DISPLAY '*IF SYS009-CNTL-KEY = 9999 * FAILURE *'
              logger.info("*IF SYS009-CNTL-KEY = 9999 * FAILURE *"); 
          }
//  STOP RUN
          throw Terminate.TERMINATE;
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
      // end of process method
      }
  
  
      /**
* This method pre-initializes variables consistent with
* what a mainframe program would have done at the start of a program
*/
      @Override
      public void initVars() throws CFException {
      setProgramEnded(false);
          if(!isInitDone()) {
          	this.setRc(0);
          	setInitDone(true);
          }
        CFUtil.resetDecimalAsComma();
       }
  
  
  
  
  
  
  }
