#STEP:PRIP7001_STEP030| PGM:SORT| DD:SORTIN
SortzdcompPrip7001_step030SortIn=MCI.IP.P2BX.TABLE130.UNLOAD.MPS
SortzdcompPrip7001_step030SortIn.DISP=SHR,KEEP,KEEP
SortzdcompPrip7001_step030SortInRecordType=FB
SortzdcompPrip7001_step030SortInRecordLen=85
#STEP:PRIP7001_STEP030| PGM:SORT| DD:SORTOUT
SortzdcompPrip7001_step030SortOut=MCI.IP.P2BX.TABLE130.SORTED.MPS
SortzdcompPrip7001_step030SortOut.DISP=NEW,CATLG,DELETE
SortzdcompPrip7001_step030SortOutRecordType=FB
SortzdcompPrip7001_step030SortOutRecordLen=85
