<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="BookReqArea" cobol:name="BOOK-REQ-AREA" cobol:offset="0" cobol:length="534" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="BreqBookId" type="xs:int" maxOccurs="1"  cobol:name="BREQ-BOOK-ID" cobol:offset="0" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BreqIsbn" type="xs:int" maxOccurs="1"  cobol:name="BREQ-ISBN" cobol:offset="4" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
<xs:element name="BreqPublishedDate" maxOccurs="1" cobol:name="BREQ-PUBLISHED-DATE" cobol:offset="8" cobol:length="257" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="BreqPublisherId" type="xs:int" maxOccurs="1"  cobol:name="BREQ-PUBLISHER-ID" cobol:offset="265" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BreqRating" type="xs:int" maxOccurs="1"  cobol:name="BREQ-RATING" cobol:offset="269" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
<xs:element name="BreqTitleGrp" maxOccurs="1" cobol:name="BREQ-TITLE-GRP" cobol:offset="273" cobol:length="257" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="BreqTotalPages" type="xs:int" maxOccurs="1"  cobol:name="BREQ-TOTAL-PAGES" cobol:offset="530" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
