<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Work" cobol:name="work" cobol:offset="0" cobol:length="0" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="W300EvalChar" maxOccurs="1"  cobol:name="W-300-EVAL-CHAR" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 evalChar300 VALUE [["A"], ["B"], ["C"], ["D"], ["E"], ["F"], ["G"], ["H"], ["I"], ["J"], ["K"], ["L"], ["M"], ["N"], ["O"], ["P"], ["Q"], ["R"], ["S"], ["T"], ["U"], ["V"], ["W"], ["X"], ["Y"], ["Z"], ["0"], ["1"], ["2"], ["3"], ["4"], ["5"], ["6"], ["7"], ["8"], ["9"], ["-"], ["."], [","], ["/"], ["\\"]].
                        88 evalCharLetter300 VALUE [[["A"],["Z"]]].
                        88 evalCharA300 VALUE [["A"]].
                        88 evalCharB300 VALUE [["B"]].
                        88 evalCharC300 VALUE [["C"]].
                        88 evalCharD300 VALUE [["D"]].
                        88 evalCharE300 VALUE [["E"]].
                        88 evalCharF300 VALUE [["F"]].
                        88 evalCharG300 VALUE [["G"]].
                        88 evalCharH300 VALUE [["H"]].
                        88 evalCharI300 VALUE [["I"]].
                        88 evalCharJ300 VALUE [["J"]].
                        88 evalCharK300 VALUE [["K"]].
                        88 evalCharL300 VALUE [["L"]].
                        88 evalCharM300 VALUE [["M"]].
                        88 evalCharN300 VALUE [["N"]].
                        88 evalCharO300 VALUE [["O"]].
                        88 evalCharP300 VALUE [["P"]].
                        88 evalCharQ300 VALUE [["Q"]].
                        88 evalCharR300 VALUE [["R"]].
                        88 evalCharS300 VALUE [["S"]].
                        88 evalCharT300 VALUE [["T"]].
                        88 evalCharU300 VALUE [["U"]].
                        88 evalCharV300 VALUE [["V"]].
                        88 evalCharW300 VALUE [["W"]].
                        88 evalCharX300 VALUE [["X"]].
                        88 evalCharY300 VALUE [["Y"]].
                        88 evalCharZ300 VALUE [["Z"]].
                        88 evalChar0300 VALUE [["0"]].
                        88 evalChar1300 VALUE [["1"]].
                        88 evalChar2300 VALUE [["3"]].
                        88 evalChar3300 VALUE [["3"]].
                        88 evalChar4300 VALUE [["4"]].
                        88 evalChar5300 VALUE [["5"]].
                        88 evalChar6300 VALUE [["6"]].
                        88 evalChar7300 VALUE [["7"]].
                        88 evalChar8300 VALUE [["8"]].
                        88 evalChar9300 VALUE [["9"]].
                        88 evalCharPeriod300 VALUE [["."]].
                        88 evalCharComma300 VALUE [[","]].
                        88 evalCharHyphen300 VALUE [["-"]].
                        88 evalCharSlashF300 VALUE [["/"]].
                        88 evalCharSlashB300 VALUE [["\\"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
