<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Db85102dWorkFields" cobol:name="DB85102D-WORK-FIELDS" cobol:offset="0" cobol:length="93" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Db85102dConnectStatusMap" maxOccurs="1"  cobol:name="DB85102D-CONNECT-STATUS-MAP" cobol:offset="0" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Db85102dCurrCollId" maxOccurs="1"  cobol:name="DB85102D-CURR-COLL-ID" cobol:offset="5" cobol:length="18" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Db85102dTempCollId" maxOccurs="1"  cobol:name="DB85102D-TEMP-COLL-ID" cobol:offset="23" cobol:length="18" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Db85102dPrevCollId" maxOccurs="1"  cobol:name="DB85102D-PREV-COLL-ID" cobol:offset="41" cobol:length="18" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Db85102dDb2CurrServer" maxOccurs="1"  cobol:name="DB85102D-DB2-CURR-SERVER" cobol:offset="59" cobol:length="16" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="16" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Db85102dDb2User" maxOccurs="1"  cobol:name="DB85102D-DB2-USER" cobol:offset="75" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Db85102dDb2CurrSqlid" maxOccurs="1"  cobol:name="DB85102D-DB2-CURR-SQLID" cobol:offset="83" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Db85102dDb2cloneStatus" maxOccurs="1"  cobol:name="DB85102D-DB2CLONE-STATUS" cobol:offset="91" cobol:length="2" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_100" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 db85102dDb2cloneIoGood88 VALUE [["00"]].
                        88 db85102dDb2cloneEof88 VALUE [["10"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="2" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
