# Program CALLVP77 | DD : INFILE | RecordFormat : FixedLength | RecordLength : 74
CALLVP77.ddname.INFILE=InputFile
CALLVP77.InputFile=InputFile
CALLVP77.InputFileCharSet=cp1047
CALLVP77.InputFileCRLFflag=no
# Program CALLVP77 | DD : OUTFILE | RecordFormat : FixedLength | RecordLength : 132
CALLVP77.ddname.OUTFILE=OutputFile
CALLVP77.OutputFile=OutputFile
CALLVP77.OutputFileCharSet=cp1047
CALLVP77.OutputFileCRLFflag=no
# 
# End of CALLVP77
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
inputValue1=''
inputValue2=''
inputValue3=''
# End of VP776A00
