
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
#uncomment and update the inputValue below, that has to be passed to the application if running as a stand alone
#inputValue=
MC083.ddname.FBFILE=FbFile
MC083.FbFile=FbFile
MC083.FbFileCharSet=cp1047
MC083.FbFileCRLFflag=no
