#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
MC071.ddname.OUTFILE=OutputFile
MC071.OutputFile=OutputFile
MC071.OutputFileCharSet=cp1047
MC071.OutputFileCRLFflag=no
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
