# Program MC071 | DD : OUTFILE | RecordFormat : FixedLength | RecordLength : 80
MC071.ddname.OUTFILE=OutputFile
MC071.OutputFile=OutputFile
MC071.OutputFileCharSet=cp1047
MC071.OutputFileCRLFflag=no
# 
# End of MC071
