#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
#
# End of CICS0012
GLOBAL.ddname.VSSECU01=CLFQA_BASELINE_VSDEMSEC
GLOBAL.ddname.VSSECU00=CLFQA_BASELINE_VSDEMSEC
GLOBAL.ddname.VSSECU02=CLFQA_BASELINE_VSDEMSEC
GLOBAL.ddname.VSSECU03=CLFQA_BASELINE_VSDEMSEC
GLOBAL.ddname.VSSECU04=CLFQA_BASELINE_VSDEMSEC