#STEP:STEP010| PGM:SORT| DD:SORTIN
Sort038Step010SortIn=CLOUDFRM.MC.GCMS.SORT.IN0381
Sort038Step010SortIn.DISP=SHR,KEEP,KEEP
Sort038Step010SortInRecordType=FB
Sort038Step010SortInRecordLen=19
#STEP:STEP010| PGM:SORT| DD:SORTOUT
Sort038Step010SortOut=CLOUDFRM.MC.GCMS.SORT.OUT0381
Sort038Step010SortOut.DISP=NEW,KEEP,KEEP
Sort038Step010SortOutRecordType=FB
Sort038Step010SortOutRecordLen=17
#STEP:STEP020| PGM:SORT| DD:SORTIN
Sort038Step020SortIn=CLOUDFRM.MC.GCMS.SORT.IN0382
Sort038Step020SortIn.DISP=SHR,KEEP,KEEP
Sort038Step020SortInRecordType=FB
Sort038Step020SortInRecordLen=19
#STEP:STEP020| PGM:SORT| DD:SORTOUT
Sort038Step020SortOut=CLOUDFRM.MC.GCMS.SORT.OUT0382
Sort038Step020SortOut.DISP=NEW,KEEP,KEEP
Sort038Step020SortOutRecordType=FB
Sort038Step020SortOutRecordLen=17
