<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip66601UserTagId" cobol:name="IP66601-USER-TAG-ID" cobol:offset="2" cobol:length="8" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="Ip66601UserElementId" maxOccurs="1" cobol:name="IP66601-USER-ELEMENT-ID" cobol:offset="0" cobol:length="4" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="Ip66601UserTagOccurrence" type="xs:short" maxOccurs="1"  cobol:name="IP66601-USER-TAG-OCCURRENCE" cobol:offset="4" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip66601UserTagSubfldNo" type="xs:short" maxOccurs="1"  cobol:name="IP66601-USER-TAG-SUBFLD-NO" cobol:offset="6" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
