# Program CFSORT02 | DD : FILEIN | RecordFormat : FixedLength | RecordLength : 30
CFSORT02.ddname.FILEIN=FileIn
CFSORT02.FileIn=FileIn
CFSORT02.FileInCharSet=cp1047
CFSORT02.FileInCRLFflag=no
# Program CFSORT02 | DD : FILEOUT | RecordFormat : FixedLength | RecordLength : 30
CFSORT02.ddname.FILEOUT=FileOut
CFSORT02.FileOut=FileOut
CFSORT02.FileOutCharSet=cp1047
CFSORT02.FileOutCRLFflag=no
# 
# End of CFSORT02
