<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip00404MpePeRecData" cobol:name="IP00404-MPE-PE-REC-DATA" cobol:offset="42" cobol:length="25" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip00404AccountRangeId" type="xs:long" maxOccurs="1"  cobol:name="IP00404-ACCOUNT-RANGE-ID" cobol:offset="0" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M"/>
    <xs:element name="Ip00404Ab" maxOccurs="1"  cobol:name="IP00404-AB" cobol:offset="6" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ip00404PriorityCode" type="xs:int" maxOccurs="1"  cobol:name="IP00404-PRIORITY-CODE" cobol:offset="9" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="Ip00404PrfxIca" type="xs:long" maxOccurs="1"  cobol:name="IP00404-PRFX-ICA" cobol:offset="11" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
    <xs:element name="Ip00404ProdId" maxOccurs="1"  cobol:name="IP00404-PROD-ID" cobol:offset="22" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
