<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip33701CurrConvOutput" cobol:name="IP33701-CURR-CONV-OUTPUT" cobol:offset="39" cobol:length="91" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Ip33701ConvType" maxOccurs="1"  cobol:name="IP33701-CONV-TYPE" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip33701CrossRate88 VALUE [["F"]].
                        88 ip33701MarketRateConv88 VALUE [["M"]].
                        88 ip33701NoConversion88 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip33701RateSrcToTrg" maxOccurs="1"  cobol:name="IP33701-RATE-SRC-TO-TRG" cobol:offset="1" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_1P" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip33701SrcToTrgSame88 VALUE [[1]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="7" />                       
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip33701SrcAmt6Decimals" maxOccurs="1"  cobol:name="IP33701-SRC-AMT-6-DECIMALS" cobol:offset="16" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="18" />
                  <xs:fractionDigits value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ip33701TargetAmount" type="xs:long" maxOccurs="1"  cobol:name="IP33701-TARGET-AMOUNT" cobol:offset="34" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
    <xs:element name="Ip33701TargetAmount1" maxOccurs="1"  cobol:name="IP33701-TARGET-AMOUNT-1" cobol:offset="34" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="18" />
                  <xs:fractionDigits value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip33701TargetAmount2" maxOccurs="1"  cobol:name="IP33701-TARGET-AMOUNT-2" cobol:offset="34" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="18" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip33701TargetAmount3" maxOccurs="1"  cobol:name="IP33701-TARGET-AMOUNT-3" cobol:offset="34" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="18" />
                  <xs:fractionDigits value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip33701TargetAmount4" maxOccurs="1"  cobol:name="IP33701-TARGET-AMOUNT-4" cobol:offset="34" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="18" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip33701TargetAmount5" maxOccurs="1"  cobol:name="IP33701-TARGET-AMOUNT-5" cobol:offset="34" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="18" />
                  <xs:fractionDigits value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip33701TargetAmount6" maxOccurs="1"  cobol:name="IP33701-TARGET-AMOUNT-6" cobol:offset="34" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="18" />
                  <xs:fractionDigits value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip33701TrgAmt6Decimals" maxOccurs="1"  cobol:name="IP33701-TRG-AMT-6-DECIMALS" cobol:offset="52" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="18" />
                  <xs:fractionDigits value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip33701TargetAmount7" maxOccurs="1"  cobol:name="IP33701-TARGET-AMOUNT-7" cobol:offset="70" cobol:length="19" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="19" />
                  <xs:fractionDigits value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip33701ReturnCode" maxOccurs="1"  cobol:name="IP33701-RETURN-CODE" cobol:offset="89" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="Long.MAX_VALUE" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip33701CurNotNumeric88 VALUE [[2]].
                        88 ip33701AmtNotNumeric88 VALUE [[3]].
                        88 ip33701InvalidCurExp88 VALUE [[4]].
                        88 ip33701CurCdZeroes88 VALUE [[8]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:short">
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
