  package com.cloudframe.app.process;
  /* Java code generated by CloudFrame on 2025-04-29 at 08:42. */
  
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.beans.factory.annotation.Qualifier;
  import com.cloudframe.app.asaprnt.file.*;
  import com.cloudframe.app.data.Field;
  import com.cloudframe.app.utility.CFUtil;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.asaprnt.dto.*;
  import com.cloudframe.app.asaprnt.dto.Header2a700;
  import com.cloudframe.app.asaprnt.dto.Trailer1700;
  import com.cloudframe.app.asaprnt.file.records.Reprec;
  import com.cloudframe.app.asaprnt.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  
  @Component("asaprnt")
  
  public class Asaprnt extends CommonProcess {
  
  Logger logger = LoggerFactory.getLogger(Asaprnt.class);
  
  private Header2a700 header2a700 = new Header2a700() ;
  private Trailer1700 trailer1700 = new Trailer1700() ;
  private Reprec reprec = new Reprec() ;
  private Work work = new Work() ;
  
  
  
  @Autowired 
  @Qualifier("asaprnt_repout")
  Repout repout;
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output :  

      * - reprec                         COBOL Name: REPREC
      *
      * @throws CFException
      */
      @Override
      public int process() throws Exception {
       initVars();
       try {
       setCodePage("1047");

// * When only write after advancing syntax is used, z/os keeps all
// * datasets in fba format. this is much more simple to handle
// * and will be supported by cf
// *
// *****************************************************************
// ****
// **** move 'before advancing page'
// ****   to reprec
// **** write reprec
// ****       before advancing page
// ****
// **** move 'before advancing 1 line'
// ****   to reprec
// **** write reprec
// ****       before advancing 1 line
// ****
// **** move 'before advancing 2 lines'
// ****   to reprec
// **** write reprec
// ****       before advancing 2 lines
// ****
// **** move 'before advancing 3 lines'
// ****   to reprec
// **** write reprec
// ****       before advancing 3
// ****
// **** move 'before advancing 4 lines'
// ****   to reprec
// **** write reprec
// ****       before 4
// ****
// **** move 'before advancing 5 lines'
// ****   to reprec
// **** write reprec
// ****       before 5 lines
// ****
// **** move 'before advancing 6 lines'
// ****   to reprec
// **** write reprec
// ****       before 6 line
// *

// *
// * Normal line
// *
//  OPEN OUTPUT REPOUT
          repout.open(new String(CONSTANTS.MODE_WRITE_ONLY_36397),repout.getFileName(),repout.getRepoutCharSet(),repout.getRepoutCrlfFlag());
          // MOVE 'WRITE REPREC (NORMAL LINE)' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_481463768);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC
          repout.writeWithAttribute(reprec.toCharArray());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
// ***************************************************
// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 0 LINE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_151822019);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 0 LINE
          repout.writeAfter(reprec.toCharArray(),0);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 0 LINES' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_144601986);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 0 LINES
          repout.writeAfter(reprec.toCharArray(),0);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 0 LINE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_1183756956);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 0 LINE
          repout.writeAfter(reprec.toCharArray(),0);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 0 LINES' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_1691326721);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 0 LINES
          repout.writeAfter(reprec.toCharArray(),0);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 0 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_676794423);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 0
          repout.writeAfter(reprec.toCharArray(),0);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 0 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_676794423);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 0
          repout.writeAfter(reprec.toCharArray(),0);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 0 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_148256600);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 0
          repout.writeAfter(reprec.toCharArray(),0);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 0 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_148256600);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 0
          repout.writeAfter(reprec.toCharArray(),0);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
// ***************************************************
// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 1 LINE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_140505892);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 1 LINE
          repout.writeAfter(reprec.toCharArray(),1);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 1 LINES' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_206197951);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 1 LINES
          repout.writeAfter(reprec.toCharArray(),1);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 1 LINE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_1195073083);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 1 LINE
          repout.writeAfter(reprec.toCharArray(),1);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 1 LINES' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_1340526784);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 1 LINES
          repout.writeAfter(reprec.toCharArray(),1);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 1 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_645774616);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 1
          repout.writeAfter(reprec.toCharArray(),1);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 1 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_645774616);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 1
          repout.writeAfter(reprec.toCharArray(),1);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 1 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_117236793);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 1
          repout.writeAfter(reprec.toCharArray(),1);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 1 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_117236793);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  PERFORM PROCESS-1
          process1();/*PROCESS-1*/
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
        finally {
      		if(repout.hasOpened() && !repout.isReadOnly()) { 
      			repout.flush(); 
      		}
      }
      
       return getRc(); // Exit with return code
      // end of process method
      }
      /**
      * process1 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-1 COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      private void process1() throws Exception {
//  PERFORM PROCESS-1-SPLIT3
          process1Split3();/*PROCESS-1-SPLIT3*/
//  PERFORM PROCESS-1-SPLIT4
          process1Split4();/*PROCESS-1-SPLIT4*/
      
      }
      /**
      * process1Split3 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-1-SPLIT3 COBOL Cyclomatic complexity - 1
      * Input  :  

      * - reprec                         COBOL Name: REPREC
      *
      * Output :  

      * - reprec                         COBOL Name: REPREC
      *
      * @throws CFException
      */
      private void process1Split3() throws Exception {
//  WRITE REPREC AFTER 1
          repout.writeAfter(reprec.toCharArray(),1);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
// ***************************************************
// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 2 LINE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_129189765);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 2 LINE
          repout.writeAfter(reprec.toCharArray(),2);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 2 LINES' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_556997888);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 2 LINES
          repout.writeAfter(reprec.toCharArray(),2);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 2 LINE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_1206389210);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 2 LINE
          repout.writeAfter(reprec.toCharArray(),2);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 2 LINES' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_989726847);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 2 LINES
          repout.writeAfter(reprec.toCharArray(),2);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 2 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_614754809);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 2
          repout.writeAfter(reprec.toCharArray(),2);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 2 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_614754809);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 2
          repout.writeAfter(reprec.toCharArray(),2);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 2 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_86216986);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 2
          repout.writeAfter(reprec.toCharArray(),2);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 2 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_86216986);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 2
          repout.writeAfter(reprec.toCharArray(),2);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
// ***************************************************
// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 3 LINE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_117873638);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 3 LINE
          repout.writeAfter(reprec.toCharArray(),3);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 3 LINES' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_907797825);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 3 LINES
          repout.writeAfter(reprec.toCharArray(),3);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 3 LINE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_1217705337);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 3 LINE
          repout.writeAfter(reprec.toCharArray(),3);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 3 LINES' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_638926910);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 3 LINES
          repout.writeAfter(reprec.toCharArray(),3);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 3 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_583735002);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 3
          repout.writeAfter(reprec.toCharArray(),3);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 3 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_583735002);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 3
          repout.writeAfter(reprec.toCharArray(),3);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 3 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_55197179);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 3
          repout.writeAfter(reprec.toCharArray(),3);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 3 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_55197179);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 3
          repout.writeAfter(reprec.toCharArray(),3);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
// ***************************************************
// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 4 LINE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_106557511);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
      
      }
      /**
      * process1Split4 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-1-SPLIT4 COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      private void process1Split4() throws Exception {
//  PERFORM PROCESS-2
          process2();/*PROCESS-2*/
      
      }
      /**
      * process2 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-2 COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      private void process2() throws Exception {
//  PERFORM PROCESS-2-SPLIT5
          process2Split5();/*PROCESS-2-SPLIT5*/
//  PERFORM PROCESS-2-SPLIT6
          process2Split6();/*PROCESS-2-SPLIT6*/
      
      }
      /**
      * process2Split5 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-2-SPLIT5 COBOL Cyclomatic complexity - 1
      * Input  :  

      * - reprec                         COBOL Name: REPREC
      *
      * Output :  

      * - reprec                         COBOL Name: REPREC
      * - lineSpace                      COBOL Name: LINE-SPACE
      *
      * @throws CFException
      */
      private void process2Split5() throws Exception {
//  WRITE REPREC AFTER ADVANCING 4 LINE
          repout.writeAfter(reprec.toCharArray(),4);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 4 LINES' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_1258597762);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 4 LINES
          repout.writeAfter(reprec.toCharArray(),4);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 4 LINE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_1229021464);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 4 LINE
          repout.writeAfter(reprec.toCharArray(),4);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 4 LINES' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_288126973);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 4 LINES
          repout.writeAfter(reprec.toCharArray(),4);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 4 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_552715195);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 4
          repout.writeAfter(reprec.toCharArray(),4);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING 4 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_552715195);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING 4
          repout.writeAfter(reprec.toCharArray(),4);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 4 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_24177372);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 4
          repout.writeAfter(reprec.toCharArray(),4);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER 4 ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_24177372);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER 4
          repout.writeAfter(reprec.toCharArray(),4);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
// ***************************************************
// *

// *
          // MOVE 1 TO LINE-SPACE
          work.setLineSpace((short)1);
          // MOVE 'WRITE REPREC AFTER ADVANCING LINE-SPACE LINE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_1049052406);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING LINE-SPACE LINE
          repout.writeAfter(reprec.toCharArray(),work.getLineSpace());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING LINE-SPACE LINES' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_1572200475);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING LINE-SPACE LINES
          repout.writeAfter(reprec.toCharArray(),work.getLineSpace());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER LINE-SPACE LINE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_827854455);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER LINE-SPACE LINE
          repout.writeAfter(reprec.toCharArray(),work.getLineSpace());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER LINE-SPACE LINES' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_160597636);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER LINE-SPACE LINES
          repout.writeAfter(reprec.toCharArray(),work.getLineSpace());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING LINE-SPACE ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_22177790);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING LINE-SPACE
          repout.writeAfter(reprec.toCharArray(),work.getLineSpace());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER ADVANCING LINE-SPACE ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_22177790);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING LINE-SPACE
          repout.writeAfter(reprec.toCharArray(),work.getLineSpace());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER LINE-SPACE ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_312035843);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER LINE-SPACE
          repout.writeAfter(reprec.toCharArray(),work.getLineSpace());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER LINE-SPACE ' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_312035843);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER LINE-SPACE
          repout.writeAfter(reprec.toCharArray(),work.getLineSpace());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
// ***************************************************
// *
          // MOVE 'WRITE REPREC AFTER ADVANCING PAGE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_1157308888);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING PAGE
          repout.writeWithPageBreakAfter(reprec.toCharArray());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER PAGE' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_38601913);
      
      }
      /**
      * process2Split6 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-2-SPLIT6 COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      private void process2Split6() throws Exception {
//  PERFORM PROCESS-3
          process3();/*PROCESS-3*/
      
      }
      /**
      * process3 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-3 COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output :  

      * - reprec                         COBOL Name: REPREC
      * - h2aTimeRun700                  COBOL Name: 700-H2A-TIME-RUN
      * - t1TotLen700                    COBOL Name: 700-T1-TOT-LEN
      *
      * @throws CFException
      */
      private void process3() throws Exception {
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER PAGE
          repout.writeWithPageBreakAfter(reprec.toCharArray());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
// ***************************************************
// *
// * C01 - c12 are special environment names supported by cobol
// *
// * c01 through c12   : skip to channel 1 through channel 12
// *                     respectively
// *
// * c01 is equivalent of advancing page. we will just support this
// *
// * write advancing support mnemonic names that map to above
// * special envornment variables
// *
// *
// * special envoronment variables like c01 can be defined with a
// * mnemonic name via special-names under configuration section
// *
// * in this program we have defined page-top mapping to c01
// *
          // MOVE 'WRITE REPREC AFTER ADVANCING PAGE-TOP' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_788824560);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER ADVANCING PAGE-TOP
          repout.writeWithPageBreakAfter(reprec.toCharArray());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
          // MOVE 'WRITE REPREC AFTER PAGE-TOP' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_1492651089);
          // MOVE '123' TO REPREC (130 : 3)
          //  LITERAL_123 = '123'
          reprec.replace(CONSTANTS.LITERAL_123,0,3/* length */,129,3 /* replace,sourceIndex,sourceLen,targetIndex,targetLen */);
//  WRITE REPREC AFTER PAGE-TOP
          repout.writeWithPageBreakAfter(reprec.toCharArray());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
// * Mc ip072010
// *
//  MOVE '10.11.12' TO 700-H2A-TIME-RUN
//  LITERAL_618066464 = '10.11.12'
          header2a700.setH2aTimeRun700(CONSTANTS.LITERAL_618066464);
//  WRITE REPREC FROM 700-HEADER2A AFTER ADVANCING PAGE
          repout.writeWithPageBreakAfter(header2a700.toCharArray());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
//  MOVE 123 TO 700-T1-TOT-LEN
//  LITERAL_123 = 123, FORMAT_1801178557 = "ZZZ,ZZ9"
          trailer1700.setT1TotLen700(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1801178557,CONSTANTS.LITERAL_123));
//  WRITE REPREC FROM 700-TRAILER1
          repout.writeWithAttribute(trailer1700.toCharArray());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
//  MOVE '11.12.13' TO 700-H2A-TIME-RUN
//  LITERAL_1933166945 = '11.12.13'
          header2a700.setH2aTimeRun700(CONSTANTS.LITERAL_1933166945);
//  WRITE REPREC FROM 700-HEADER2A AFTER ADVANCING PAGE
          repout.writeWithPageBreakAfter(header2a700.toCharArray());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
//  MOVE 456 TO 700-T1-TOT-LEN
//  LITERAL_456 = 456, FORMAT_1801178557 = "ZZZ,ZZ9"
          trailer1700.setT1TotLen700(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1801178557,CONSTANTS.LITERAL_456));
//  WRITE REPREC FROM 700-TRAILER1 AFTER ADVANCING 2 LINES
          repout.writeAfter(trailer1700.toCharArray(),2);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
//  MOVE '12.13.14' TO 700-H2A-TIME-RUN
//  LITERAL_189433058 = '12.13.14'
          header2a700.setH2aTimeRun700(CONSTANTS.LITERAL_189433058);
//  WRITE REPREC FROM 700-HEADER2A AFTER ADVANCING PAGE
          repout.writeWithPageBreakAfter(header2a700.toCharArray());
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
//  MOVE 789 TO 700-T1-TOT-LEN
//  LITERAL_789 = 789, FORMAT_1801178557 = "ZZZ,ZZ9"
          trailer1700.setT1TotLen700(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1801178557,CONSTANTS.LITERAL_789));
//  WRITE REPREC FROM 700-TRAILER1 AFTER 4
          repout.writeAfter(trailer1700.toCharArray(),4);
          reprec.setString(CONSTANTS.LOW_VALUE_215751987);

// *
//  CLOSE REPOUT
          repout.close(); 
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          this.setProgramEnded(true);
          return ;
      
      }
  
  
      /**
* This method pre-initializes variables consistent with
* what a mainframe program would have done at the start of a program
*/
      @Override
      public void initVars() throws CFException {
      setProgramEnded(false);
          if(!isInitDone()) {
          	this.setRc(0);
          	setInitDone(true);
          }
        CFUtil.resetDecimalAsComma();
       }
  
  
  
  
  
  
  }
