DROP TABLE CLOUDDEV.ALLDTYP;
COMMIT WORK;
CREATE TABLE CLOUDDEV.ALLDTYP(DTYP_ID INTEGER not null, DTYP_SMALLINT SMALLINT,DTYP_INT INTEGER,DTYP_BIGINT BIGINT, DTYP_CHAR CHAR(8),DTYP_DATE DATE,DTYP_TIME TIME, DTYP_TMSTMP TIMESTAMP(6),DTYP_DECIMAL DECIMAL(10, 2), DTYP_VARCHAR VARCHAR(255)) IN DBCLOUD.TSCLDDEV;
