STEP010.DSNTEP2.Sysprint=STEP010.DSNTEP2.SYSPRINT.SYSOUT
STEP010.DSNTEP2.Systsprt=STEP010.DSNTEP2.SYSTSPRT.SYSOUT
#start sqlutil report/raw format properties
unload.sqlutil.format=REPORT
#end sqlutil report/raw format properties

#database specific properties
spring.database.enabled=true
spring.datasource.jdbc-url=jdbc:db2://sysh.cloudframe.com:5040/DALLASC:currentSchema=CLOUDDEV;
spring.datasource.driverClassName=com.ibm.db2.jcc.DB2Driver
spring.datasource.username=QAUSER
spring.datasource.password=CLOUD04
spring.datasource.initialization-mode=embedded
spring.jpa.hibernate.ddl-auto=update
spring.jdbc.template.fetch-size=5000
#end of database properties
CLP_DSNUPROC.DSNUTILB.Sysrec00=CLOUDFRM.ALLDTYP.DATA
CLP_DSNUPROC.DSNUTILB.Sysrec00.Charset=utf-8
CLP_DSNUPROC.DSNUTILB.Sysrec00.CRLFflag=yes
CLP_DSNUPROC.DSNUTILB.Sysdisc=USWB.TBXMLLOG.SYSDISC
load.sqlutil.seperator=|
STEP011.DSNTEP2.Sysprint=STEP011.DSNTEP2.SYSPRINT.SYSOUT
STEP011.DSNTEP2.Systsprt=STEP011.DSNTEP2.SYSTSPRT.SYSOUT
