#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
# 
# End of BBHSR002
inputValue1=
D5427HPC.dbQualifier=
# End of D5427HPC
# End of C5427HPC
DPHPCTSQ.dbQualifier=
# End of DPHPCTSQ
inputValue2=
inputValue3=
inputValue4=
inputValue5=
inputValue6=
inputValue7=
inputValue8=
inputValue9=
inputValue10=
inputValue11=
inputValue12=
D5427POL.dbQualifier=
# End of D5427POL
D5427BHI.dbQualifier=
# End of D5427BHI
# End of C5427BHI
D5427SCN.dbQualifier=
# End of D5427SCN
D5427TLI.dbQualifier=
# End of D5427TLI
