
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
MCFILE1.ddname.OUTPDD=FlOutputFile
MCFILE1.FlOutputFile=FlOutputFile
MCFILE1.FlOutputFileCharSet=cp1047
MCFILE1.FlOutputFileCRLFflag=no
MCFILE2.ddname.OUTPDD=FlOutputFile
MCFILE2.FlOutputFile=FlOutputFile
MCFILE2.FlOutputFileCharSet=cp1047
MCFILE2.FlOutputFileCRLFflag=no
