# Program MCFILE1 | DD : OUTPDD | RecordFormat : FixedLength | RecordLength : 31
MCFILE1.ddname.OUTPDD=FlOutputFile
MCFILE1.FlOutputFile=FlOutputFile
MCFILE1.FlOutputFileCharSet=cp1047
MCFILE1.FlOutputFileCRLFflag=no
# 
# End of MCFILE1
# Program MCFILE2 | DD : OUTPDD | RecordFormat : FixedLength | RecordLength : 31
MCFILE2.ddname.OUTPDD=FlOutputFile
MCFILE2.FlOutputFile=FlOutputFile
MCFILE2.FlOutputFileCharSet=cp1047
MCFILE2.FlOutputFileCRLFflag=no
# End of MCFILE2
