<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="MiscData" cobol:name="WS-MISC-DATA" cobol:offset="0" cobol:length="293" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="I" type="xs:short" maxOccurs="1"  cobol:name="I" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="CmdCaHomeSidBidCode" maxOccurs="1"  cobol:name="CMD-CA-HOME-SID-BID-CODE" cobol:offset="2" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Tbls" maxOccurs="1"  cobol:name="WS-TBLS" cobol:offset="7" cobol:length="286" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="286" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="TblsRedefined" maxOccurs="26" cobol:name="WS-TBLS-REDEFINED" cobol:offset="7" cobol:length="11" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
