#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
spring.main.allow-circular-references=true
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=0
inputValue1=0
inputValue2=0
#logging.level.com.cloudframe=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
# 
# End of SEARCH0
