#common-test-properties
spring.main.log-startup-info=OFF
logging.pattern.file=%msg%n
logging.file.name=QA271.log
logging.logback.rollingpolicy.clean-history-on-start=true
logging.level.com.zaxxer=OFF
logging.level.com.cloudframe.app.dao.CFDataSourceConfiguration=OFF
logging.level.com.cloudframe.app.vsam.VSAMClusterUtil=OFF
logging.level.com.cloudframe.app.utility.CFConfiguration=OFF
#test-specific-properties
# compare.files[0]=ExpSys201ZLogFile,Sys201ZLogFile
#compare.files[1]=ExpQA271.log,QA271.log
#project-specific-properties
#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
timeZoneId=Etc/GMT
SF326010.ddname.SYS001=SYS001
SF326010.Sys001MipLogFile=SYS001
SF326010.Sys001MipLogFileCharSet=cp1047
SF326010.Sys001MipLogFileCRLFflag=no
SF326010.ddname.SYS201=Sys201ZLogFile
SF326010.Sys201ZLogFile=Sys201ZLogFile
SF326010.Sys201ZLogFileCharSet=cp1047
SF326010.Sys201ZLogFileCRLFflag=no
#logging.level.com.cloudframe=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
# 
# End of SF326010
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=X
# End of SF305120
