timeZoneId=Etc/GMT
# Program SF326010 | DD : SYS001 | RecordFormat : VariableLength | MaxRecordLength : 32752
SF326010.ddname.SYS001=Sys001MipLogFile
SF326010.Sys001MipLogFile=Sys001MipLogFile
SF326010.Sys001MipLogFileCharSet=cp1047
SF326010.Sys001MipLogFileCRLFflag=no
# Program SF326010 | DD : SYS201 | RecordFormat : FixedLength | RecordLength : 75
SF326010.ddname.SYS201=Sys201ZLogFile
SF326010.Sys201ZLogFile=Sys201ZLogFile
SF326010.Sys201ZLogFileCharSet=cp1047
SF326010.Sys201ZLogFileCRLFflag=no
# 
# End of SF326010
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
# End of SF305120
