  package com.cloudframe.app.process;
  /* Java code generated by CloudFrame on 2025-04-21 at 10:54. */
  
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.beans.factory.annotation.Qualifier;
  import com.cloudframe.app.vsammon7.file.*;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.vsammon7.file.Scanner;
  import com.cloudframe.app.data.Field;
  import com.cloudframe.app.vsammon7.dto.Input;
  import com.cloudframe.app.exception.Terminate;
  import java.util.ArrayList;
  import java.util.Map;
  import java.util.HashMap;
  import com.cloudframe.app.vsammon7.dto.KeyreadData;
  import com.cloudframe.app.utility.CFUtil;
  import com.cloudframe.app.vsammon7.dto.ProgramData;
  import com.cloudframe.app.vsammon7.file.records.MonPriKey;
  import com.cloudframe.app.utility.CFConstants;
  import com.cloudframe.app.vsammon7.dto.*;
  import com.cloudframe.app.vsammon7.file.records.Reprec;
  import com.cloudframe.app.vsammon7.dto.MonitorFileStatus;
  import com.cloudframe.app.vsammon7.file.records.MonitorRecord;
  import com.cloudframe.app.vsammon7.dto.AcceptInputGroup;
  import com.cloudframe.app.vsammon7.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  
  @Component("vsammon7")
  
  public class Vsammon7 extends CommonProcess {
  
  Logger logger = LoggerFactory.getLogger(Vsammon7.class);
  
  private Reprec reprec = new Reprec() ;
  private MonitorFileStatus monitorFileStatus = new MonitorFileStatus() ;
  private MonitorRecord monitorRecord = new MonitorRecord() ;
  private AcceptInputGroup acceptInputGroup = new AcceptInputGroup() ;
  private Work work = new Work() ;
  
  
  
  @Autowired 
  @Qualifier("vsammon7_monitor")
  Monitor monitor;
  @Autowired 
  @Qualifier("vsammon7_repout")
  Repout repout;
  
  
  private boolean doNotSkipCloseFiles = true;
  private boolean doNotSkipKeyreadBasedReport = true;
  private boolean doNotSkipReadnxt = true;
  private boolean doNotSkipRn9999 = true;
  private boolean doNotSkipProgram = true;
  private boolean doNotSkipStartp = true;
  private boolean doNotSkipStarta = true;
  
  
    @Autowired
    @Qualifier("vsammon7_scanner")
    Scanner scanner;
  
  
  
      /**
      * process 
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      @Override
      public int process() throws Exception {
       initVars();
       try {
       setCodePage("1047");
          ;
//  PERFORM 0000-MAINLINE
          mainline();/*0000-MAINLINE*/
          if (this.isProgramEnded()) {
              return getRc();
          }
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
        finally {
      		if(monitor.hasOpened() && !monitor.isReadOnly()) { 
      			monitor.flush(); 
      		}
      		if(repout.hasOpened() && !repout.isReadOnly()) { 
      			repout.flush(); 
      		}
      		if(scanner.hasOpened()) { 
      			scanner.close();
      		}
      }
      
       return getRc(); // Exit with return code
      // end of process method
      }
      /**
      * mainline 
      *   This method is derived from 
  *   COBOL Paragraph - 0000-MAINLINE COBOL Cyclomatic complexity - 11
      * Input  :  

      * - i                              COBOL Name: WS-I
      *
      * Output :  

      * - input                          COBOL Name: WS-INPUT
      * - inputCommand                   COBOL Name: WS-INPUT-COMMAND
      * - acceptInput                    COBOL Name: WS-ACCEPT-INPUT
      * - i                              COBOL Name: WS-I
      * - q                              COBOL Name: Q
      * - r                              COBOL Name: R
      *
      * @throws CFException
      */
      private void mainline() throws Exception {
			// Declare local variables used in the method
			char[] consoleInput = null;
			short r = 0;
			Input input = acceptInputGroup.getInput();
			// End of variable declaration

//  PERFORM 0010-OPEN-FILES THRU 0010-EXIT
          openFiles();/*0010-OPEN-FILES*/
          if (this.isProgramEnded()) {
              return ;
          }
//  MOVE SPACES TO WS-INPUT
          acceptInputGroup.setInput(CONSTANTS.SPACE_80);
//  PERFORM UNTIL C-TERMINATE
          while ((!(acceptInputGroup.getInput().isCTerminate()) )) {
//  ACCEPT WS-ACCEPT-INPUT
              consoleInput = scanner.nextLine();
              if (!scanner.hasEnded()) {
                 acceptInputGroup.setAcceptInput(consoleInput);  // read from console and assign
              }
//  ADD 1 TO WS-I
              work.setI(work.getI()+(long)1);
//  DIVIDE WS-I BY 1000 GIVING Q REMAINDER R
              work.setQ( (short) (work.getI()/1000));
              work.setR( (short) (work.getI()%1000));
              r = work.getR();
//  IF R = 0 THEN
//  LITERAL_0 = 0
              if (	( r == 0 ) ) { 
//  DISPLAY '** ' WS-I
                  logger.info("** {}", String.valueOf(work.getI())); 
              }
  
              input = acceptInputGroup.getInput();
//  EVALUATE TRUE
              if  ( input.isCKeyread()  ) { 
//  PERFORM 4000-KEYREAD-BASED-REPORT THRU 4000-EXIT
                  keyreadBasedReport();/*4000-KEYREAD-BASED-REPORT*/
                  if (this.isProgramEnded()) {
                      return ;
                  }
              }
              else if  ( input.isCReadnxt()  ) { 
//  PERFORM 5000-READNXT THRU 5000-EXIT
                  readnxt();/*5000-READNXT*/
                  if (this.isProgramEnded()) {
                      return ;
                  }
              }
              else if  (Field.compareChar(input.getInputCommand() , CONSTANTS.LITERAL_RN , ( 0 /*start*/ ), 2 /*left len*/ , 2 /*right len*/)) { 
//  PERFORM 6000-RN9999 THRU 6000-EXIT
                  rn9999();/*6000-RN9999*/
                  if (this.isProgramEnded()) {
                      return ;
                  }
              }
              else if  ( input.isCProgram()  ) { 
//  PERFORM 7000-PROGRAM THRU 7000-EXIT
                  program();/*7000-PROGRAM*/
                  if (this.isProgramEnded()) {
                      return ;
                  }
              }
              else if  ( input.isCStartp()  ) { 
//  PERFORM 8000-STARTP THRU 8000-EXIT
                  startp();/*8000-STARTP*/
                  if (this.isProgramEnded()) {
                      return ;
                  }
              }
              else if  ( input.isCStarta()  ) { 
//  PERFORM 9000-STARTA THRU 9000-EXIT
                  starta();/*9000-STARTA*/
                  if (this.isProgramEnded()) {
                      return ;
                  }
              }
              else   { 
                  ;
              }
  
          }
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          this.setProgramEnded(true);
          return ;
      
      }
      /**
      * openFiles 
      *   This method is derived from 
  *   COBOL Paragraph - 0010-OPEN-FILES COBOL Cyclomatic complexity - 3
      * Input  : None 

      * Output :  

      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      * - reprec                         COBOL Name: REPREC
      *
      * @throws CFException
      */
      private void openFiles() throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			Map<String,Object> updated = null;
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
//  OPEN OUTPUT REPOUT
          repout.open(new String(CONSTANTS.MODE_WRITE_ONLY_36397),repout.getFileName(),repout.getRepoutCharSet(),repout.getRepoutCrlfFlag());
//  OPEN I-O MONITOR
          	monitor.setVsamCluster("VSAMMON7" /*program name*/);
          monitor.open("rw"); 
          monitorFileStatus.setString(monitor.getStatusString() );
//  IF MONITOR-FILE-STATUS NOT = '00'
//  LITERAL_00 = '00'
          if (		compareChars(monitorFileStatus,CONSTANTS.LITERAL_00) != 0 ) { 
//  MOVE SPACES TO REPREC
              reprec.setString(CONSTANTS.SPACE_300);
//  STRING 'Error opening Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B3_openingMonitor_CL_);
                 charArray.add(monitorFileStatus.toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(reprec.toCharArray() ,joinCharArray);
              reprec.setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(reprec.toCharArray()); 
              reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 9999-EXIT-PROGRAM
exitProgram();
 return ;
//cobolCodeEnds::GO TO 9999-EXIT-PROGRAM
          }
          ;
      
      }
      /**
      * closeFiles 
      *   This method is derived from 
  *   COBOL Paragraph - 0020-CLOSE-FILES COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      private void closeFiles() throws Exception {
      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
//  CLOSE MONITOR
          monitor.close(); 
          monitorFileStatus.setString(monitor.getStatusString() );
//  CLOSE REPOUT
          repout.close(); 
          ;
      
      }
      /**
      * keyreadBasedReport 
      *   This method is derived from 
  *   COBOL Paragraph - 4000-KEYREAD-BASED-REPORT COBOL Cyclomatic complexity - 4
      * Input  :  

      * - iKeyread                       COBOL Name: WS-I-KEYREAD
      *
      * Output :  

      * - reprec                         COBOL Name: REPREC
      * - eofSw                          COBOL Name: WS-EOF-SW
      * - monPriKey                      COBOL Name: MON-PRI-KEY
      * - iKeyread                       COBOL Name: WS-I-KEYREAD
      * - monitorRecord                  COBOL Name: MONITOR-RECORD
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      * - staInStat1                     COBOL Name: STA-IN-STAT1
      *
      * @throws CFException
      */
      private void keyreadBasedReport() throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			char[] staInStat1 = null;
			Map<String,Object> updated = null;
			KeyreadData keyreadData = acceptInputGroup.getInput().getKeyreadData();
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
          // MOVE '**********' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          reprec.setString(CONSTANTS.SPACE_300);
//  STRING 'Direct Read of Monitor row  matching KEY = ' WS-I-KEYREAD DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_1103497819);
             charArray.add(keyreadData.getIKeyread());
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
          updated = updateString(reprec.toCharArray() ,joinCharArray);
          reprec.setString(  (char[])updated.get("string"));
  
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO WS-EOF-SW
          work.setEofSw(CONSTANTS.SPACE);
//  MOVE WS-I-KEYREAD TO MON-PRI-KEY
          monitorRecord.getMonPriKey().setString(keyreadData.getIKeyread());
  
//  READ MONITOR END-READ
          	monitor.readDirect(monitorRecord.getMonPriKey().toCharArray(),monitor.getKeyInfo().getMonPriKey());
          monitorFileStatus.setString(monitor.getStatusString() );
          if (!monitor.hasEnded()) {
          	monitorRecord.setString(monitor.getRecord());
          }
          staInStat1 = monitorFileStatus.getStaInStat1();
//  IF STA-IN-STAT1 > '1'
//  LITERAL_1 = '1'
          if (		compareChars(staInStat1,CONSTANTS.LITERAL_1) > 0 ) { 
//  MOVE SPACES TO REPREC
              reprec.setString(CONSTANTS.SPACE_300);
//  STRING 'Error reading Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B3_readingMonitor_CL_);
                 charArray.add(monitorFileStatus.toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(reprec.toCharArray() ,joinCharArray);
              reprec.setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(reprec.toCharArray()); 
              reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 4000-EXIT
return ;
//cobolCodeEnds::GO TO 4000-EXIT
          }
  
          // MOVE MONITOR-RECORD TO REPREC
          reprec.setString(monitorRecord.getCharArray());
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
          ;
      
      }
      /**
      * readnxt 
      *   This method is derived from 
  *   COBOL Paragraph - 5000-READNXT COBOL Cyclomatic complexity - 3
      * Input  : None 

      * Output :  

      * - reprec                         COBOL Name: REPREC
      * - eofSw                          COBOL Name: WS-EOF-SW
      * - monitorRecord                  COBOL Name: MONITOR-RECORD
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      * - monPriKey                      COBOL Name: MON-PRI-KEY
      * - staInStat1                     COBOL Name: STA-IN-STAT1
      *
      * @throws CFException
      */
      private void readnxt() throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			char[] staInStat1 = null;
			Map<String,Object> updated = null;
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
          // MOVE '**********' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE 'READ NEXT done after Direct READ/START' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_10037858);
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO WS-EOF-SW
          work.setEofSw(CONSTANTS.SPACE);
//  READ MONITOR NEXT END-READ
          monitor.readNext();
          monitorFileStatus.setString(monitor.getStatusString() );
          if (!monitor.hasEnded()) {
          	monitorRecord.setString(monitor.getRecord());
          }
          staInStat1 = monitorFileStatus.getStaInStat1();
//  IF STA-IN-STAT1 > '0'
//  LITERAL_0 = '0'
          if (		compareChars(staInStat1,CONSTANTS.LITERAL_0) > 0 ) { 
//  MOVE SPACES TO REPREC
              reprec.setString(CONSTANTS.SPACE_300);
//  STRING 'Error reading Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B3_readingMonitor_CL_);
                 charArray.add(monitorFileStatus.toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(reprec.toCharArray() ,joinCharArray);
              reprec.setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(reprec.toCharArray()); 
              reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 5000-EXIT
return ;
//cobolCodeEnds::GO TO 5000-EXIT
          }
  
          // MOVE MONITOR-RECORD TO REPREC
          reprec.setString(monitorRecord.getCharArray());
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
          ;
      
      }
      /**
      * rn9999 
      *   This method is derived from 
  *   COBOL Paragraph - 6000-RN9999 COBOL Cyclomatic complexity - 6
      * Input  :  

      * - acceptInput                    COBOL Name: WS-ACCEPT-INPUT
      * - j                              COBOL Name: WS-J
      *
      * Output :  

      * - reprec                         COBOL Name: REPREC
      * - rnCnt                          COBOL Name: WS-RN-CNT
      * - acceptInput                    COBOL Name: WS-ACCEPT-INPUT
      * - j                              COBOL Name: WS-J
      * - monitorRecord                  COBOL Name: MONITOR-RECORD
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      * - monPriKey                      COBOL Name: MON-PRI-KEY
      * - staInStat1                     COBOL Name: STA-IN-STAT1
      *
      * @throws CFException
      */
      private void rn9999() throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			char[] staInStat1 = null;
			Map<String,Object> updated = null;
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
          // MOVE '**********' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          reprec.setString(CONSTANTS.SPACE_300);
//  MOVE WS-ACCEPT-INPUT (3 : 4) TO WS-RN-CNT
          work.setRnCnt(CFUtil.getInt(substring(acceptInputGroup.getAcceptInput(),2,6)));
//  STRING 'READ NEXT of ' WS-RN-CNT ' records done after Direct READ' DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_READ_B3_NEXTof);
             charArray.add(String.valueOf(work.getRnCntString()).toCharArray());
             charArray.add(CONSTANTS.LITERAL_B5_recordsdoneafterDirectREAD);
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1),charArray.get(2));
          updated = updateString(reprec.toCharArray() ,joinCharArray);
          reprec.setString(  (char[])updated.get("string"));
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//  PERFORM VARYING WS-J FROM 1 BY 1 UNTIL WS-J > WS-RN-CNT
          for (work.setJ(1); (	( work.getJ() <= work.getRnCnt() ) ) ; work.setJ(work.getJ() + 1) ) {
//  READ MONITOR NEXT END-READ
              monitor.readNext();
              monitorFileStatus.setString(monitor.getStatusString() );
              if (!monitor.hasEnded()) {
              	monitorRecord.setString(monitor.getRecord());
              }
              staInStat1 = monitorFileStatus.getStaInStat1();
//  IF STA-IN-STAT1 > '0'
//  LITERAL_0 = '0'
              if (		compareChars(staInStat1,CONSTANTS.LITERAL_0) > 0 ) { 
//  MOVE SPACES TO REPREC
                  reprec.setString(CONSTANTS.SPACE_300);
//  STRING 'Error reading Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
                  charArray = new ArrayList<char[]>();
                     charArray.add(CONSTANTS.LITERAL_Error_B3_readingMonitor_CL_);
                     charArray.add(monitorFileStatus.toCharArray());
                  joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
                  updated = updateString(reprec.toCharArray() ,joinCharArray);
                  reprec.setString(  (char[])updated.get("string"));
//  WRITE REPREC
                  repout.write(reprec.toCharArray()); 
                  reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 6000-EXIT
return ;
//cobolCodeEnds::GO TO 6000-EXIT
              }
  
              // MOVE MONITOR-RECORD TO REPREC
              reprec.setString(monitorRecord.getCharArray());
//  WRITE REPREC
              repout.write(reprec.toCharArray()); 
              reprec.setString(CONSTANTS.LOW_VALUE_215695350);
          }
          ;
      
      }
      /**
      * program 
      *   This method is derived from 
  *   COBOL Paragraph - 7000-PROGRAM COBOL Cyclomatic complexity - 5
      * Input  :  

      * - iProgram                       COBOL Name: WS-I-PROGRAM
      *
      * Output :  

      * - reprec                         COBOL Name: REPREC
      * - eofSw                          COBOL Name: WS-EOF-SW
      * - monXcdtProgNm                  COBOL Name: MON-XCDT-PROG-NM
      * - iProgram                       COBOL Name: WS-I-PROGRAM
      * - monitorRecord                  COBOL Name: MONITOR-RECORD
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      * - monPriKey                      COBOL Name: MON-PRI-KEY
      * - staInStat1                     COBOL Name: STA-IN-STAT1
      *
      * @throws CFException
      */
      private void program() throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			char[] staInStat1 = null;
			Map<String,Object> updated = null;
			ProgramData programData = acceptInputGroup.getInput().getProgramData();
			MonPriKey monPriKey = monitorRecord.getMonPriKey();
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
          // MOVE '**********' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          reprec.setString(CONSTANTS.SPACE_300);
//  STRING 'Direct Read of Monitor row  matching AIX Prog = ' WS-I-PROGRAM DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_660112468);
             charArray.add(programData.getIProgram());
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
          updated = updateString(reprec.toCharArray() ,joinCharArray);
          reprec.setString(  (char[])updated.get("string"));
  
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO WS-EOF-SW
          work.setEofSw(CONSTANTS.SPACE);
//  MOVE WS-I-PROGRAM TO MON-XCDT-PROG-NM
          monPriKey.setMonXcdtProgNm(programData.getIProgram());
  
//  READ MONITOR KEY IS MON-XCDT-PROG-NM END-READ
          	monitor.readDirect(monPriKey.getMonXcdtProgNm(),monitor.getKeyInfo().getMonXcdtProgNm());
          monitorFileStatus.setString(monitor.getStatusString() );
          if (!monitor.hasEnded()) {
          	monitorRecord.setString(monitor.getRecord());
          }
  
          staInStat1 = monitorFileStatus.getStaInStat1();
//  IF STA-IN-STAT1 > '1'
//  LITERAL_1 = '1'
          if (		compareChars(staInStat1,CONSTANTS.LITERAL_1) > 0 ) { 
//  MOVE SPACES TO REPREC
              reprec.setString(CONSTANTS.SPACE_300);
//  STRING 'Error reading Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B3_readingMonitor_CL_);
                 charArray.add(monitorFileStatus.toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(reprec.toCharArray() ,joinCharArray);
              reprec.setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(reprec.toCharArray()); 
              reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 7000-EXIT
return ;
//cobolCodeEnds::GO TO 7000-EXIT
          }
  
          // MOVE MONITOR-RECORD TO REPREC
          reprec.setString(monitorRecord.getCharArray());
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          reprec.setString(CONSTANTS.SPACE_300);
//  STRING '|--> MONITOR-FILE-STATUS = ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_1711277613);
             charArray.add(monitorFileStatus.toCharArray());
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
          updated = updateString(reprec.toCharArray() ,joinCharArray);
          reprec.setString(  (char[])updated.get("string"));
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
          ;
      
      }
      /**
      * startp 
      *   This method is derived from 
  *   COBOL Paragraph - 8000-STARTP COBOL Cyclomatic complexity - 4
      * Input  :  

      * - iKeyread                       COBOL Name: WS-I-KEYREAD
      * - staInStat1                     COBOL Name: STA-IN-STAT1
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      *
      * Output :  

      * - reprec                         COBOL Name: REPREC
      * - eofSw                          COBOL Name: WS-EOF-SW
      * - monPriKey                      COBOL Name: MON-PRI-KEY
      * - iKeyread                       COBOL Name: WS-I-KEYREAD
      *
      * @throws CFException
      */
      private void startp() throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			char[] staInStat1 = null;
			Map<String,Object> updated = null;
			KeyreadData keyreadData = acceptInputGroup.getInput().getKeyreadData();
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
          // MOVE '**********' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          reprec.setString(CONSTANTS.SPACE_300);
//  STRING 'START > = PRIMARY KEY :  ' WS-I-KEYREAD DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_1718420788);
             charArray.add(keyreadData.getIKeyread());
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
          updated = updateString(reprec.toCharArray() ,joinCharArray);
          reprec.setString(  (char[])updated.get("string"));
  
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO WS-EOF-SW
          work.setEofSw(CONSTANTS.SPACE);
//  MOVE WS-I-KEYREAD TO MON-PRI-KEY
          monitorRecord.getMonPriKey().setString(keyreadData.getIKeyread());
  
//  START MONITOR KEY = MON-PRI-KEY END-START
          monitor.seek(monitorRecord.toCharArray(),CFConstants.CONDITION_EQUAL,monitor.getKeyInfo().getMonPriKey()); 
          monitorFileStatus.setString(monitor.getStatusString() );
          staInStat1 = monitorFileStatus.getStaInStat1();
//  IF STA-IN-STAT1 > '0'
//  LITERAL_0 = '0'
          if (		compareChars(staInStat1,CONSTANTS.LITERAL_0) > 0 ) { 
//  MOVE SPACES TO REPREC
              reprec.setString(CONSTANTS.SPACE_300);
//  STRING 'Error reading Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B3_readingMonitor_CL_);
                 charArray.add(monitorFileStatus.toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(reprec.toCharArray() ,joinCharArray);
              reprec.setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(reprec.toCharArray()); 
              reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 8000-EXIT
return ;
//cobolCodeEnds::GO TO 8000-EXIT
          }
  
          ;
      
      }
      /**
      * starta 
      *   This method is derived from 
  *   COBOL Paragraph - 9000-STARTA COBOL Cyclomatic complexity - 4
      * Input  :  

      * - iProgram                       COBOL Name: WS-I-PROGRAM
      * - staInStat1                     COBOL Name: STA-IN-STAT1
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      *
      * Output :  

      * - reprec                         COBOL Name: REPREC
      * - eofSw                          COBOL Name: WS-EOF-SW
      * - monXcdtProgNm                  COBOL Name: MON-XCDT-PROG-NM
      * - iProgram                       COBOL Name: WS-I-PROGRAM
      *
      * @throws CFException
      */
      private void starta() throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			char[] staInStat1 = null;
			Map<String,Object> updated = null;
			ProgramData programData = acceptInputGroup.getInput().getProgramData();
			MonPriKey monPriKey = monitorRecord.getMonPriKey();
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
          // MOVE '**********' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          reprec.setString(CONSTANTS.SPACE_300);
//  STRING 'START > = ALTERNATE KEY :  ' WS-I-PROGRAM DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_899168748);
             charArray.add(programData.getIProgram());
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
          updated = updateString(reprec.toCharArray() ,joinCharArray);
          reprec.setString(  (char[])updated.get("string"));
  
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          reprec.setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(reprec.toCharArray()); 
          reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO WS-EOF-SW
          work.setEofSw(CONSTANTS.SPACE);
//  MOVE WS-I-PROGRAM TO MON-XCDT-PROG-NM
          monPriKey.setMonXcdtProgNm(programData.getIProgram());
  
//  START MONITOR KEY IS EQUAL TO MON-XCDT-PROG-NM END-START
          monitor.seek(monitorRecord.toCharArray(),CFConstants.CONDITION_EQUAL,monitor.getKeyInfo().getMonXcdtProgNm()); 
          monitorFileStatus.setString(monitor.getStatusString() );
  
          staInStat1 = monitorFileStatus.getStaInStat1();
//  IF STA-IN-STAT1 > '0'
//  LITERAL_0 = '0'
          if (		compareChars(staInStat1,CONSTANTS.LITERAL_0) > 0 ) { 
//  MOVE SPACES TO REPREC
              reprec.setString(CONSTANTS.SPACE_300);
//  STRING 'Error reading Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B3_readingMonitor_CL_);
                 charArray.add(monitorFileStatus.toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(reprec.toCharArray() ,joinCharArray);
              reprec.setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(reprec.toCharArray()); 
              reprec.setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 9000-EXIT
return ;
//cobolCodeEnds::GO TO 9000-EXIT
          }
  
          ;
      
      }
      /**
      * exitProgram 
      *   This method is derived from 
  *   COBOL Paragraph - 9999-EXIT-PROGRAM COBOL Cyclomatic complexity - 2
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      private void exitProgram() throws Exception {
      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          this.setProgramEnded(true);
          return ;
      
      }
  
  
      /**
* This method pre-initializes variables consistent with
* what a mainframe program would have done at the start of a program
*/
      @Override
      public void initVars() throws CFException {
      setProgramEnded(false);
       doNotSkipCloseFiles = true;
       doNotSkipKeyreadBasedReport = true;
       doNotSkipReadnxt = true;
       doNotSkipRn9999 = true;
       doNotSkipProgram = true;
       doNotSkipStartp = true;
       doNotSkipStarta = true;
          if(!isInitDone()) {
          	this.setRc(0);
          	setInitDone(true);
          }
        CFUtil.resetDecimalAsComma();
       }
  
  
  
  
  
  
  }
