#
#STEP:VSAMINIT| PGM:IDCAMS| DD:INDD
VSAMINIT.IDCAMS.Indd=CLOUDFRM.IDCAMS.PRINT.VSAMKSDS.INPUT
VSAMINIT.IDCAMS.Indd.DISP=SHR,KEEP,KEEP
VSAMINIT.IDCAMS.Indd.RecordType=FB
VSAMINIT.IDCAMS.Indd.RecordLen=281
#
#
#STEP:VSAMINIT| PGM:IDCAMS| DD:OUTDD
VSAMINIT.IDCAMS.Outdd=CLOUDFRM_IDCAMS_PRINT_VSAMKSDS
#
#STEP:PRINT01| PGM:IDCAMS| DD:INPUT
PRINT01.IDCAMS.Input=CLOUDFRM_IDCAMS_PRINT_VSAMKSDS
#
#STEP:PRINT01| PGM:IDCAMS| DD:SYSPRINT
PRINT01.IDCAMS.Sysprint=PRINT01.IDCAMS.SYSPRINT.SYSOUT
#
