#common-test-properties
spring.main.log-startup-info=OFF
logging.pattern.file=%msg%n
logging.file.name=QA273.log
logging.logback.rollingpolicy.clean-history-on-start=true
logging.level.com.zaxxer=OFF
logging.level.com.cloudframe.app.dao.CFDataSourceConfiguration=OFF
logging.level.com.cloudframe.app.vsam.VSAMClusterUtil=OFF
logging.level.com.cloudframe.app.utility.CFConfiguration=OFF
#test-specific-properties
#compare.files[4]=Exp_QA000273.CLF.SYSOUT.MF,QA273.log
#project-specific-properties
#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
# spring.main.lazy-initialization=true
timeZoneId=Etc/GMT
SF320010.ddname.SYS001=SYS001
SF320010.GeneralLogFileIn=SYS001
SF320010.GeneralLogFileInCharSet=cp1047
SF320010.GeneralLogFileInCRLFflag=no
SF320010.ddname.SYS301=SYS301TempWorkFile
SF320010.TempWorkFile=SYS301TempWorkFile
SF320010.TempWorkFileCharSet=cp1047
SF320010.TempWorkFileCRLFflag=no
SF320010.ddname.SYS201=sys201ReportFileOut
SF320010.ReportFileOut=sys201ReportFileOut
SF320010.ReportFileOutCharSet=cp1047
SF320010.ReportFileOutCRLFflag=no
SF320010.ddname.SYS202=sys202InfoSecFileOut
SF320010.InfoSecFileOut=sys202InfoSecFileOut
SF320010.InfoSecFileOutCharSet=cp1047
SF320010.InfoSecFileOutCRLFflag=no
SF320010.ddname.SYS203=Sys203EmailFileOut
SF320010.Sys203EmailFileOut=Sys203EmailFileOut
SF320010.Sys203EmailFileOutCharSet=cp1047
SF320010.Sys203EmailFileOutCRLFflag=no
#logging.level.com.cloudframe=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
cf.sort.useTempFile=no
cf.has.sort=true
HIGH_VALUE=Z
# 
# End of SF320010
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=X
inputValue1=X
# End of MCWIN
# End of MCABEND
