<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="SortworkRecord" cobol:name="SORTWORK-RECORD" cobol:offset="0" cobol:length="59" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="SortworkKeyZoneDec" type="xs:long" maxOccurs="1"  cobol:name="SORTWORK-KEY-ZONE-DEC" cobol:offset="0" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="SortworkKeyComp3" type="xs:long" maxOccurs="1"  cobol:name="SORTWORK-KEY-COMP-3" cobol:offset="21" cobol:length="10" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="SortworkKeyBinary" type="xs:int" maxOccurs="1"  cobol:name="SORTWORK-KEY-BINARY" cobol:offset="34" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SortworkKeyComp" type="xs:int" maxOccurs="1"  cobol:name="SORTWORK-KEY-COMP" cobol:offset="41" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SortworkKeyComp4" type="xs:int" maxOccurs="1"  cobol:name="SORTWORK-KEY-COMP-4" cobol:offset="48" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SortworkKeyComp5" type="xs:int" maxOccurs="1"  cobol:name="SORTWORK-KEY-COMP-5" cobol:offset="55" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
