  package com.cloudframe.app.process.impl;
  /* Java code generated by CloudFrame on 2025-04-28 at 07:55. */
  
  import com.cloudframe.app.init2.Init2Ctx.*;
  import com.cloudframe.app.init2.Init2Ctx;
  import com.cloudframe.app.process.Init2;
  import com.cloudframe.app.process.BaseProcess;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.dto.GlobalExecutorCtx;
  import com.cloudframe.app.exception.Terminate;
  import java.math.BigDecimal;
  import com.cloudframe.app.utility.CFUtil;
  import com.cloudframe.app.init2.dto.*;
  import com.cloudframe.app.init2.dto.L6560ParmInfo;
  import com.cloudframe.app.init2.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  
  @Component("init2")
  
  public class Init2Impl extends CommonProcess implements Init2 {
  
  Logger logger = LoggerFactory.getLogger(Init2Impl.class);
  
  
  
  
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      public int process(Init2Ctx programCtx) throws Exception {
       try {
       setCodePage("1047");
            // Reset program ended flag
           programCtx.setProgramEnded(false);
//  PERFORM 0000-INITIALIZE THRU 0000-EXIT
          initialize(programCtx);/*0000-INITIALIZE*/
          if (programCtx.isProgramEnded()) {
              return programCtx.getRc();
          }

// *

// *

// *
//  STOP RUN
          throw Terminate.TERMINATE;
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
      // end of process method
      }
      /**
      * initialize 
      *   This method is derived from 
  *   COBOL Paragraph - 0000-INITIALIZE COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output :  

      * - l6560SurrSaleLoadAmt           COBOL Name: L6560-SURR-SALE-LOAD-AMT
      * - l6560InputParmInfo             COBOL Name: L6560-INPUT-PARM-INFO
      * - l6560RqstCd                    COBOL Name: L6560-RQST-CD
      * - l6560EffDt                     COBOL Name: L6560-EFF-DT
      * - l6560Cvg                       COBOL Name: L6560-CVG
      * - l6560SurrAmt                   COBOL Name: L6560-SURR-AMT
      * - l6560SurrChrgTypCd             COBOL Name: L6560-SURR-CHRG-TYP-CD
      * - l6560PolAcumValuAmt            COBOL Name: L6560-POL-ACUM-VALU-AMT
      * - l6560CvgAcumValuAmt            COBOL Name: L6560-CVG-ACUM-VALU-AMT
      * - l6560MthvAdjAmt                COBOL Name: L6560-MTHV-ADJ-AMT
      * - l6560MktvalAdjPct              COBOL Name: L6560-MKTVAL-ADJ-PCT
      * - l6560CalcIfTerminatedSw        COBOL Name: L6560-CALC-IF-TERMINATED-SW
      * - l6560FreeWthAppliedInd         COBOL Name: L6560-FREE-WTH-APPLIED-IND
      * - l6560DbscInfo                  COBOL Name: L6560-DBSC-INFO
      * - l6560DbscApplicableInd         COBOL Name: L6560-DBSC-APPLICABLE-IND
      * - l6560DbscTotSurrAmt            COBOL Name: L6560-DBSC-TOT-SURR-AMT
      * - l6560DbscTotChrgAmt            COBOL Name: L6560-DBSC-TOT-CHRG-AMT
      * - l6560DbscTotFreeAmt            COBOL Name: L6560-DBSC-TOT-FREE-AMT
      * - l6560DbscAssSurrAmt            COBOL Name: L6560-DBSC-ASS-SURR-AMT
      * - l6560DbscAssChrgAmt            COBOL Name: L6560-DBSC-ASS-CHRG-AMT
      * - l6560DbscAssFreeAmt            COBOL Name: L6560-DBSC-ASS-FREE-AMT
      * - l6560PlanFndTypCd              COBOL Name: L6560-PLAN-FND-TYP-CD
      * - l6560SurrChrgOvridInd          COBOL Name: L6560-SURR-CHRG-OVRID-IND
      * - l6560IoParmInfo                COBOL Name: L6560-IO-PARM-INFO
      * - l6560RetrnCd                   COBOL Name: L6560-RETRN-CD
      * - l6560SurrChrgAmt               COBOL Name: L6560-SURR-CHRG-AMT
      * - l6560SurrChrgFlatAmt           COBOL Name: L6560-SURR-CHRG-FLAT-AMT
      * - l6560SurrChrgPct               COBOL Name: L6560-SURR-CHRG-PCT
      * - l6560MktvalAdjAmt              COBOL Name: L6560-MKTVAL-ADJ-AMT
      * - l6560OutputParmInfo            COBOL Name: L6560-OUTPUT-PARM-INFO
      * - l6560FreeWthdrwAmt             COBOL Name: L6560-FREE-WTHDRW-AMT
      *
      * @throws CFException
      */
      @Override
      public InitializeOutCtx initialize(Init2Ctx programCtx) throws Exception {
InitializeOutCtx methodOut = programCtx.getInitializeOutCtx();
//  MOVE 100 TO L6560-SURR-SALE-LOAD-AMT (1) L6560-SURR-SALE-LOAD-AMT (2) L6560-SURR-SALE-LOAD-AMT (5) L6560-SURR-SALE-LOAD-AMT (7) L6560-SURR-SALE-LOAD-AMT (9) L6560-SURR-SALE-LOAD-AMT (11)
          methodOut.setL6560SurrSaleLoadAmt(0,BigDecimal.valueOf(100));
          methodOut.setL6560SurrSaleLoadAmt(1,BigDecimal.valueOf(100));
          methodOut.setL6560SurrSaleLoadAmt(4,BigDecimal.valueOf(100));
          methodOut.setL6560SurrSaleLoadAmt(6,BigDecimal.valueOf(100));
          methodOut.setL6560SurrSaleLoadAmt(8,BigDecimal.valueOf(100));
          methodOut.setL6560SurrSaleLoadAmt(10,BigDecimal.valueOf(100));

// *
//  INITIALIZE L6560-INPUT-PARM-INFO L6560-RQST-CD L6560-EFF-DT L6560-CVG L6560-SURR-AMT L6560-SURR-CHRG-TYP-CD L6560-POL-ACUM-VALU-AMT L6560-CVG-ACUM-VALU-AMT L6560-MTHV-ADJ-AMT L6560-MKTVAL-ADJ-PCT L6560-CALC-IF-TERMINATED-SW L6560-FREE-WTH-APPLIED-IND L6560-DBSC-INFO L6560-DBSC-APPLICABLE-IND L6560-DBSC-TOT-SURR-AMT L6560-DBSC-TOT-CHRG-AMT L6560-DBSC-TOT-FREE-AMT L6560-DBSC-ASS-SURR-AMT L6560-DBSC-ASS-CHRG-AMT L6560-DBSC-ASS-FREE-AMT L6560-PLAN-FND-TYP-CD L6560-SURR-CHRG-OVRID-IND L6560-IO-PARM-INFO L6560-RETRN-CD L6560-SURR-CHRG-AMT L6560-SURR-CHRG-FLAT-AMT L6560-SURR-CHRG-PCT L6560-MKTVAL-ADJ-AMT
          methodOut.getL6560InputParmInfo().initialize();
          methodOut.setL6560RqstCd(CONSTANTS.SPACE_2 /* Fill 2 Spaces*/);
          methodOut.setL6560EffDt(CONSTANTS.SPACE_10 /* Fill 10 Spaces*/);
          methodOut.setL6560Cvg((short)0);
          methodOut.setL6560SurrAmt(BigDecimal.ZERO);
          methodOut.setL6560SurrChrgTypCd(CONSTANTS.SPACE /* Fill 1 Spaces*/);
          methodOut.setL6560PolAcumValuAmt(BigDecimal.ZERO);
          methodOut.setL6560CvgAcumValuAmt(BigDecimal.ZERO);
          methodOut.setL6560MthvAdjAmt(BigDecimal.ZERO);
          methodOut.setL6560MktvalAdjPct(BigDecimal.ZERO);
          methodOut.setL6560CalcIfTerminatedSw(CONSTANTS.SPACE /* Fill 1 Spaces*/);
          methodOut.setL6560FreeWthAppliedInd(CONSTANTS.SPACE /* Fill 1 Spaces*/);
          methodOut.getL6560DbscInfo().initialize();
          methodOut.setL6560DbscApplicableInd(CONSTANTS.SPACE /* Fill 1 Spaces*/);
          methodOut.setL6560DbscTotSurrAmt(BigDecimal.ZERO);
          methodOut.setL6560DbscTotChrgAmt(BigDecimal.ZERO);
          methodOut.setL6560DbscTotFreeAmt(BigDecimal.ZERO);
          methodOut.setL6560DbscAssSurrAmt(BigDecimal.ZERO);
          methodOut.setL6560DbscAssChrgAmt(BigDecimal.ZERO);
          methodOut.setL6560DbscAssFreeAmt(BigDecimal.ZERO);
          methodOut.setL6560PlanFndTypCd(CONSTANTS.SPACE /* Fill 1 Spaces*/);
          methodOut.setL6560SurrChrgOvridInd(CONSTANTS.SPACE /* Fill 1 Spaces*/);
          methodOut.setL6560IoParmInfo(CONSTANTS.SPACE_25 /* Fill 25 Spaces*/);
          methodOut.setL6560RetrnCd((short)0);
          methodOut.setL6560SurrChrgAmt(BigDecimal.ZERO);
          methodOut.setL6560SurrChrgFlatAmt(BigDecimal.ZERO);
          methodOut.setL6560SurrChrgPct(BigDecimal.ZERO);
          methodOut.setL6560MktvalAdjAmt(BigDecimal.ZERO);
//  INITIALIZE L6560-OUTPUT-PARM-INFO
          methodOut.getL6560OutputParmInfo().initialize();
//  DISPLAY 'L6560-SURR-SALE-LOAD-AMT (25) = ' L6560-SURR-SALE-LOAD-AMT (25)
          logger.info("L6560-SURR-SALE-LOAD-AMT (25) = {}", String.valueOf(methodOut.getL6560SurrSaleLoadAmt(24).movePointRight(2))); 

// *
//  DISPLAY 'L6560-FREE-WTHDRW-AMT         = ' L6560-FREE-WTHDRW-AMT
          logger.info("L6560-FREE-WTHDRW-AMT         = {}", String.valueOf(methodOut.getL6560FreeWthdrwAmt().movePointRight(2))); 
          ;
      
      return methodOut;
      }
  
  
  
  
  
  
  
  
  }
