  package com.cloudframe.app.process.impl;
  /* Java code generated by CloudFrame on 2025-04-24 at 16:43. */
  
  import com.cloudframe.app.addrchk.AddrchkCtx.*;
  import com.cloudframe.app.addrchk.AddrchkCtx;
  import com.cloudframe.app.process.Addrchk;
  import com.cloudframe.app.process.BaseProcess;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.dto.GlobalExecutorCtx;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.addrchk.dto.*;
  import com.cloudframe.app.addrchk.dto.Groupvar1;
  import com.cloudframe.app.addrchk.dto.Groupvar2;
  import com.cloudframe.app.addrchk.dto.Var3;
  import com.cloudframe.app.addrchk.dto.Var1;
  import com.cloudframe.app.addrchk.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("addrchk")
  
  public class AddrchkImpl extends CommonProcess implements Addrchk {
  
  Logger logger = LoggerFactory.getLogger(AddrchkImpl.class);
  
  
  
  
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      public int process(AddrchkCtx programCtx) throws Exception {
       try {
       setCodePage("1047");
            // Reset program ended flag
           programCtx.setProgramEnded(false);
          ;
//  PERFORM 0000-MAINLINE
          mainline(programCtx.getMainlineInCtx());/*0000-MAINLINE*/
          if (programCtx.isProgramEnded()) {
              return programCtx.getRc();
          }
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
       return programCtx.getRc(); // Exit with return code
      // end of process method
      }
      /**
      * mainline 
      *   This method is derived from 
  *   COBOL Paragraph - 0000-MAINLINE COBOL Cyclomatic complexity - 4
      * Input  :  

      * - groupvar1                      COBOL Name: GROUPVAR1
      * - groupvar2                      COBOL Name: GROUPVAR2
      *
      * Output :  

      * - primvar1                       COBOL Name: PRIMVAR1
      * - primvar2                       COBOL Name: PRIMVAR2
      * - primvar3                       COBOL Name: PRIMVAR3
      * - var1                           COBOL Name: LK-VAR1
      * - var3                           COBOL Name: LK-VAR3
      *
      * @throws CFException
      */
      @Override
      public MainlineOutCtx mainline(MainlineInCtx methodIn) throws Exception {
AddrchkCtx programCtx = methodIn.getAddrchkCtx();
MainlineOutCtx methodOut = methodIn.getMainlineOutCtx();
//  SET PRIMVAR1 TO ADDRESS OF GROUPVAR1
          methodOut.setPrimvar1(setObject(methodIn.getGroupvar1())); 
          
//  SET PRIMVAR2 TO ADDRESS OF GROUPVAR2
          methodOut.setPrimvar2(setObject(methodIn.getGroupvar2())); 
          
//  SET PRIMVAR3 TO ADDRESS OF GROUPVAR1
          methodOut.setPrimvar3(setObject(methodIn.getGroupvar1())); 
          
//  IF PRIMVAR1 IS EQUAL TO PRIMVAR3 THEN
          if (	( methodOut.getPrimvar1() == methodOut.getPrimvar3() )) { 
//  DISPLAY 'PASS: ADDRESS POINTER IS SAME'
              logger.info("PASS: ADDRESS POINTER IS SAME"); 
          }
//  ELSE
          else { 
//  DISPLAY 'FAIL: ADDRESS POINTER IS DIFFERENT'
              logger.info("FAIL: ADDRESS POINTER IS DIFFERENT"); 
          }
//  SET ADDRESS OF LK-VAR1 TO PRIMVAR1
          methodOut.getVar1().set(getObject(methodOut.getPrimvar1())); 
          
//  SET ADDRESS OF LK-VAR3 TO PRIMVAR3
          methodOut.getVar3().set(getObject(methodOut.getPrimvar3())); 
          
//  IF LK-VAR1 (1 : 10) = LK-VAR3 (1 : 10)
          if (		compareChars(substring(methodOut.getVar1().getCharArray(),0,10),substring(methodOut.getVar3().getCharArray(),0,10)) == 0 ) { 
//  DISPLAY 'PASS: ADDRESS CONTENT IS SAME'
              logger.info("PASS: ADDRESS CONTENT IS SAME"); 
          }
//  ELSE
          else { 
//  DISPLAY 'FAIL: ADDRESS CONTENT IS DIFFERENT'
              logger.info("FAIL: ADDRESS CONTENT IS DIFFERENT"); 
          }
//  EXIT PROGRAM
          setNotLogged(false); // no need to log, it is a normal termination
          programCtx.setProgramEnded(true);
          return methodOut;
      
      }
  
  
  
  
  
  
  
  
  }
