# Program MCSORT01 | DD : SORTIN | RecordFormat : VariableLength | MaxRecordLength : 32752
MCSORT01.ddname.SORTIN=SortIn
MCSORT01.SortIn=SortIn
MCSORT01.SortInCharSet=cp1047
MCSORT01.SortInCRLFflag=no
# Program MCSORT01 | DD : SORTOUT | RecordFormat : VariableLength | MaxRecordLength : 32752
MCSORT01.ddname.SORTOUT=SortOut
MCSORT01.SortOut=SortOut
MCSORT01.SortOutCharSet=cp1047
MCSORT01.SortOutCRLFflag=no
# 
# End of MCSORT01
