#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
# 
# End of IP282210
# Program IP343900 | DD : SYS067 | RecordFormat : FixedLength | RecordLength : 80
IP343900.ddname.SYS067=Sys067EnvrmentFile
IP343900.Sys067EnvrmentFile=Sys067EnvrmentFile
IP343900.Sys067EnvrmentFileCharSet=cp1047
IP343900.Sys067EnvrmentFileCRLFflag=no
# Program IP343900 | DD : SYS001 | RecordFormat : FixedLength | RecordLength : 94
IP343900.ddname.SYS001=Sys001PmmFixUnloadFile
IP343900.Sys001PmmFixUnloadFile=Sys001PmmFixUnloadFile
IP343900.Sys001PmmFixUnloadFileCharSet=cp1047
IP343900.Sys001PmmFixUnloadFileCRLFflag=no
# End of IP343900
