#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
#logging.level.com.cloudframe=DEBUG
logging.file.name=console-IDCPRN01.log
logging.pattern.file=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
PRINT01.IDCAMS.Input=CLOUDFRM.IDCAMS.PRINT.FB.FILE1
PRINT01.IDCAMS.Input.DISP=SHR,KEEP,KEEP
PRINT01.IDCAMS.Input.RecordType=FB
PRINT01.IDCAMS.Input.RecordLen=80
#End of INPUT DD, PRINT01 step for IDCAMS
PRINT01.IDCAMS.Sysprint=PRINT01.IDCAMS.SYSPRINT.SYSOUT
#End of SYSPRINT DD, PRINT01 step for IDCAMS
# Missing PARM inputValues
