package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.utility.CFUtil;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] SPACE_10 = CFUtil.fillSpaces(10);
public static final char[] LITERAL_AAAAAAAAAA = "AAAAAAAAAA".toCharArray();
public static final char[] LITERAL_BBBBBBBBBB = "BBBBBBBBBB".toCharArray();
public static final char[] LITERAL_CCCCCCCCCC = "CCCCCCCCCC".toCharArray();
public static final char[] LITERAL_DDDDDDDDDD = "DDDDDDDDDD".toCharArray();
public static final char[] LITERAL_EEEEEEEEEE = "EEEEEEEEEE".toCharArray();
 
}
