version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/cics-usecases/CF03SECU/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/cics-usecases/CICS0009/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/cics-usecases/CICS0012/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/cics-usecases/Uhgpocusecase_1/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/cics-usecases/Uhgpocusecase_2/"
    schedule:
      interval: "daily"