<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip65504DeNamesLargeGroup3" cobol:name="IP65504-DE-NAMES-LARGE-GROUP-3" cobol:offset="492" cobol:length="248" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip65504D63TrxCycS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D63-TRX-CYC-S" cobol:offset="4" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D63TrxCycL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D63-TRX-CYC-L" cobol:offset="6" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller63" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="8" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D64MacCodS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D64-MAC-COD-S" cobol:offset="12" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D64MacCodL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D64-MAC-COD-L" cobol:offset="14" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller64" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="16" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D65ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D65-RESERVD-S" cobol:offset="20" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D65ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D65-RESERVD-L" cobol:offset="22" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller65" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="24" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D66AmtFeeS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D66-AMT-FEE-S" cobol:offset="28" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D66AmtFeeL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D66-AMT-FEE-L" cobol:offset="30" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller66" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="32" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D67ExtPayS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D67-EXT-PAY-S" cobol:offset="36" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D67ExtPayL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D67-EXT-PAY-L" cobol:offset="38" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller67" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="40" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D68RecvCcS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D68-RECV-CC-S" cobol:offset="44" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D68RecvCcL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D68-RECV-CC-L" cobol:offset="46" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller68" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="48" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D69SetlCcS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D69-SETL-CC-S" cobol:offset="52" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D69SetlCcL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D69-SETL-CC-L" cobol:offset="54" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller69" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="56" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D70AuthCcS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D70-AUTH-CC-S" cobol:offset="60" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D70AuthCcL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D70-AUTH-CC-L" cobol:offset="62" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller70" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="64" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D71MsgNbrS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D71-MSG-NBR-S" cobol:offset="68" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D71MsgNbrL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D71-MSG-NBR-L" cobol:offset="70" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller71" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="72" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D72DataRdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D72-DATA-RD-S" cobol:offset="76" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D72DataRdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D72-DATA-RD-L" cobol:offset="78" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller72" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="80" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D73ActDteS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D73-ACT-DTE-S" cobol:offset="84" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D73ActDteL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D73-ACT-DTE-L" cobol:offset="86" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller73" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="88" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D74CrNmbrS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D74-CR-NMBR-S" cobol:offset="92" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D74CrNmbrL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D74-CR-NMBR-L" cobol:offset="94" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller74" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="96" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D75CrRevnS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D75-CR-REVN-S" cobol:offset="100" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D75CrRevnL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D75-CR-REVN-L" cobol:offset="102" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller75" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="104" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D76DbNmbrS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D76-DB-NMBR-S" cobol:offset="108" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D76DbNmbrL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D76-DB-NMBR-L" cobol:offset="110" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller76" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="112" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D77DbRevnS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D77-DB-REVN-S" cobol:offset="116" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D77DbRevnL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D77-DB-REVN-L" cobol:offset="118" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller77" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="120" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D78TferNoS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D78-TFER-NO-S" cobol:offset="124" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D78TferNoL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D78-TFER-NO-L" cobol:offset="126" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller78" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="128" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D79TferRvS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D79-TFER-RV-S" cobol:offset="132" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D79TferRcL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D79-TFER-RC-L" cobol:offset="134" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller79" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="136" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D80InqNbrS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D80-INQ-NBR-S" cobol:offset="140" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D80InqNbrL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D80-INQ-NBR-L" cobol:offset="142" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller80" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="144" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D81AuthNoS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D81-AUTH-NO-S" cobol:offset="148" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D81AuthNoL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D81-AUTH-NO-L" cobol:offset="150" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller81" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="152" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D82InqRevS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D82-INQ-REV-S" cobol:offset="156" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D82InqRevL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D82-INQ-REV-L" cobol:offset="158" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller82" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="160" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D83PymtNoS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D83-PYMT-NO-S" cobol:offset="164" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D83PymtNoL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D83-PYMT-NO-L" cobol:offset="166" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller83" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="168" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D84PymtRvS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D84-PYMT-RV-S" cobol:offset="172" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D84PymtRvL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D84-PYMT-RV-L" cobol:offset="174" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller84" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="176" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D85FeeColS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D85-FEE-COL-S" cobol:offset="180" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D85FeeColL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D85-FEE-COL-L" cobol:offset="182" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller85" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="184" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D86CrAmtsS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D86-CR-AMTS-S" cobol:offset="188" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D86CrAmtsL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D86-CR-AMTS-L" cobol:offset="190" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller86" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="192" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D87CrRevrS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D87-CR-REVR-S" cobol:offset="196" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D87CrRevrL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D87-CR-REVR-L" cobol:offset="198" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller87" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="200" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D88DbAmtsS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D88-DB-AMTS-S" cobol:offset="204" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D88DbAmtsL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D88-DB-AMTS-L" cobol:offset="206" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller88" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="208" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D89DbRevrS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D89-DB-REVR-S" cobol:offset="212" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D89DbRevrL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D89-DB-REVR-L" cobol:offset="214" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller89" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="216" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D90AuthRvS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D90-AUTH-RV-S" cobol:offset="220" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D90AuthRvL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D90-AUTH-RV-L" cobol:offset="222" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller90" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="224" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D91TrxDccS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D91-TRX-DCC-S" cobol:offset="228" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D91TrxDccL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D91-TRX-DCC-L" cobol:offset="230" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller91" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="232" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D92TrxOccS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D92-TRX-OCC-S" cobol:offset="236" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D92TrxOccL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D92-TRX-OCC-L" cobol:offset="238" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller92" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="240" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D93TrxDidS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D93-TRX-DID-S" cobol:offset="244" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504D93TrxDidL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-D93-TRX-DID-L" cobol:offset="246" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504DeMapGroupFiller93" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="248" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
