  package com.cloudframe.app.process;
  /* Java code generated by CloudFrame on 2025-04-21 at 11:05. */
  
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.beans.factory.annotation.Qualifier;
  import com.cloudframe.app.oldnew.file.*;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.data.Field;
  import com.cloudframe.app.oldnew.dto.*;
  import com.cloudframe.app.oldnew.file.records.FsRecord;
  import com.cloudframe.app.oldnew.file.records.FsOutrec;
  import com.cloudframe.app.oldnew.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("oldnew")
  
  public class Oldnew extends CommonProcess {
  
  Logger logger = LoggerFactory.getLogger(Oldnew.class);
  
  private FsRecord fsRecord = new FsRecord() ;
  private FsOutrec fsOutrec = new FsOutrec() ;
  private Work work = new Work() ;
  
  
  
  @Autowired 
  @Qualifier("oldnew_sys001MipSpecrtOld")
  Sys001MipSpecrtOld sys001MipSpecrtOld;
  @Autowired 
  @Qualifier("oldnew_sys002MipSpecrtNew")
  Sys002MipSpecrtNew sys002MipSpecrtNew;
  
  
  
  
  
  
      /**
      * process 
      * Input  :  

      * - eof                            COBOL Name: WS-EOF
      *
      * Output :  

      * - fsRecord                       COBOL Name: FS-RECORD
      * - eof                            COBOL Name: WS-EOF
      *
      * @throws CFException
      */
      @Override
      public int process() throws Exception {
       initVars();
       try {
       setCodePage("1047");
//  OPEN INPUT SYS001-MIP-SPECRT-OLD
          sys001MipSpecrtOld.open(new String(CONSTANTS.MODE_READ_ONLY_36242),sys001MipSpecrtOld.getFileName(),sys001MipSpecrtOld.getSys001MipSpecrtOldCharSet(),sys001MipSpecrtOld.getSys001MipSpecrtOldCrlfFlag());
//  OPEN OUTPUT SYS002-MIP-SPECRT-NEW
          sys002MipSpecrtNew.open(new String(CONSTANTS.MODE_WRITE_ONLY_36397),sys002MipSpecrtNew.getFileName(),sys002MipSpecrtNew.getSys002MipSpecrtNewCharSet(),sys002MipSpecrtNew.getSys002MipSpecrtNewCrlfFlag());
//  PERFORM UNTIL WS-EOF = 'Y'
          while ((work.getEof()[0] != 'Y')) {
//  READ SYS001-MIP-SPECRT-OLD INTO WS-RECORD
              	sys001MipSpecrtOld.read();
              if (!sys001MipSpecrtOld.hasEnded()) {
                 fsRecord.setString(sys001MipSpecrtOld.getRecord());
                 work.setRecordWs(fsRecord.toCharArray());
              }
//  AT END
              if (sys001MipSpecrtOld.hasEnded()) {  
                  // MOVE 'Y' TO WS-EOF
                  //  LITERAL_Y = 'Y'
                  work.setEof(CONSTANTS.LITERAL_Y);
                }
//  NOT AT END
              else  {
//  PERFORM 1000-WRITE-PARA
                  writePara();/*1000-WRITE-PARA*/
                  if (this.isProgramEnded()) {
                      return getRc();
                  }
                }
          }
//  CLOSE SYS001-MIP-SPECRT-OLD
          sys001MipSpecrtOld.close(); 
//  CLOSE SYS002-MIP-SPECRT-NEW
          sys002MipSpecrtNew.close(); 
//  STOP RUN
          throw Terminate.TERMINATE;
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
        finally {
      		if(sys001MipSpecrtOld.hasOpened() && !sys001MipSpecrtOld.isReadOnly()) { 
      			sys001MipSpecrtOld.flush(); 
      		}
      		if(sys002MipSpecrtNew.hasOpened() && !sys002MipSpecrtNew.isReadOnly()) { 
      			sys002MipSpecrtNew.flush(); 
      		}
      }
      
      // end of process method
      }
      /**
      * writePara 
      *   This method is derived from 
  *   COBOL Paragraph - 1000-WRITE-PARA COBOL Cyclomatic complexity - 1
      * Input  :  

      * - recordWs                       COBOL Name: WS-RECORD
      *
      * Output :  

      * - fsOutrec                       COBOL Name: FS-OUTREC
      * - recordWs                       COBOL Name: WS-RECORD
      *
      * @throws CFException
      */
      private void writePara() throws Exception {
//  MOVE WS-RECORD TO FS-OUTREC
          fsOutrec.setString(work.getRecordWs());
//  WRITE FS-OUTREC END-WRITE
          sys002MipSpecrtNew.write(fsOutrec.toCharArray()); 
          fsOutrec.setString(CONSTANTS.LOW_VALUE_1253879107);
      
      }
  
  
      /**
* This method pre-initializes variables consistent with
* what a mainframe program would have done at the start of a program
*/
      @Override
      public void initVars() throws CFException {
      setProgramEnded(false);
          if(!isInitDone()) {
          	this.setRc(0);
          	setInitDone(true);
          }
        CFUtil.resetDecimalAsComma();
       }
  
  
  
  
  
  
  }
