<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip0040TableDataFields" cobol:name="IP0040-TABLE-DATA-FIELDS" cobol:offset="41" cobol:length="151" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Ip0040AccRangeH" maxOccurs="1"  cobol:name="IP0040-ACC-RANGE-H" cobol:offset="0" cobol:length="19" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="19" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040Ab" maxOccurs="1"  cobol:name="IP0040-AB" cobol:offset="19" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ip0040PriorityCode" type="xs:int" maxOccurs="1"  cobol:name="IP0040-PRIORITY-CODE" cobol:offset="22" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="Ip0040PrfxIca" type="xs:long" maxOccurs="1"  cobol:name="IP0040-PRFX-ICA" cobol:offset="24" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
    <xs:element name="Ip0040ProductType" maxOccurs="1"  cobol:name="IP0040-PRODUCT-TYPE" cobol:offset="35" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ip0040Endpoint" type="xs:long" maxOccurs="1"  cobol:name="IP0040-ENDPOINT" cobol:offset="36" cobol:length="7" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
    <xs:element name="Ip0040Country" maxOccurs="1"  cobol:name="IP0040-COUNTRY" cobol:offset="43" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ip0040CountryNum" type="xs:int" maxOccurs="1"  cobol:name="IP0040-COUNTRY-NUM" cobol:offset="46" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
<xs:element name="Ip0040RegionSubreg" maxOccurs="1" cobol:name="IP0040-REGION-SUBREG" cobol:offset="49" cobol:length="1" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Ip0040ProductClass" maxOccurs="1"  cobol:name="IP0040-PRODUCT-CLASS" cobol:offset="50" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040TranRoutingInd" maxOccurs="1"  cobol:name="IP0040-TRAN-ROUTING-IND" cobol:offset="53" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040PrsProdReassgnSw" maxOccurs="1"  cobol:name="IP0040-PRS-PROD-REASSGN-SW" cobol:offset="54" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip0040PrsPdReasgn88 VALUE [["Y"]].
                        88 ip0040PrsPdNotReasgn88 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip0040ProdReassignmentSw" maxOccurs="1"  cobol:name="IP0040-PROD-REASSIGNMENT-SW" cobol:offset="55" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip0040PdReassigned88 VALUE [["Y"]].
                        88 ip0040PdNotReassigned88 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip0040OptInFlag" maxOccurs="1"  cobol:name="IP0040-OPT-IN-FLAG" cobol:offset="56" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040LicensedProdId" maxOccurs="1"  cobol:name="IP0040-LICENSED-PROD-ID" cobol:offset="57" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040VirtFundPanInd" maxOccurs="1"  cobol:name="IP0040-VIRT-FUND-PAN-IND" cobol:offset="60" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040AcctCatgPartSw" maxOccurs="1"  cobol:name="IP0040-ACCT-CATG-PART-SW" cobol:offset="61" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ip0040AcctCatgActvnDate" type="xs:long" maxOccurs="1"  cobol:name="IP0040-ACCT-CATG-ACTVN-DATE" cobol:offset="62" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M"/>
<xs:element name="Ip0040CardHldrBlngCur" maxOccurs="1" cobol:name="IP0040-CARD-HLDR-BLNG-CUR" cobol:offset="68" cobol:length="32" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Ip0040ChipConversionSw" maxOccurs="1"  cobol:name="IP0040-CHIP-CONVERSION-SW" cobol:offset="100" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="Ip0040FloorExpiryDate" maxOccurs="1" cobol:name="IP0040-FLOOR-EXPIRY-DATE" cobol:offset="101" cobol:length="6" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Ip0040CoBrandSw" maxOccurs="1"  cobol:name="IP0040-CO-BRAND-SW" cobol:offset="107" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040SpendControlRcnSw" maxOccurs="1"  cobol:name="IP0040-SPEND-CONTROL-RCN-SW" cobol:offset="108" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040MerchCleanServPart" maxOccurs="1"  cobol:name="IP0040-MERCH-CLEAN-SERV-PART" cobol:offset="109" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ip0040MerchCleanActvDate" type="xs:long" maxOccurs="1"  cobol:name="IP0040-MERCH-CLEAN-ACTV-DATE" cobol:offset="112" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M"/>
    <xs:element name="Ip0040PaypassEnabledInd" maxOccurs="1"  cobol:name="IP0040-PAYPASS-ENABLED-IND" cobol:offset="118" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040RateTypeIndicator" maxOccurs="1"  cobol:name="IP0040-RATE-TYPE-INDICATOR" cobol:offset="119" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040RoutePsnIndicator" maxOccurs="1"  cobol:name="IP0040-ROUTE-PSN-INDICATOR" cobol:offset="120" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040CbwpIndicator" maxOccurs="1"  cobol:name="IP0040-CBWP-INDICATOR" cobol:offset="121" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip0040CbwpIndY88 VALUE [["Y"]].
                        88 ip0040CbwpIndN88 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip0040FlexParticipInd" maxOccurs="1"  cobol:name="IP0040-FLEX-PARTICIP-IND" cobol:offset="122" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip0040ParticipInd088 VALUE [["0"]].
                        88 ip0040ParticipInd188 VALUE [["1"]].
                        88 ip0040ParticipInd288 VALUE [["2"]].
                        88 ip0040ParticipInd388 VALUE [["3"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip0040RepwrRldInd" maxOccurs="1"  cobol:name="IP0040-REPWR-RLD-IND" cobol:offset="123" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040MoneySendInd" maxOccurs="1"  cobol:name="IP0040-MONEY-SEND-IND" cobol:offset="124" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip0040MoneySendDomCrs88 VALUE [["Y"]].
                        88 ip0040MoneySendDom88 VALUE [["D"]].
                        88 ip0040MoneySendNo88 VALUE [["N"]].
                        88 ip0040MoneySendUnknown88 VALUE [["U"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip0040RegulatedRateIndSw" maxOccurs="1"  cobol:name="IP0040-REGULATED-RATE-IND-SW" cobol:offset="125" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip0040RegRateIndSw88 VALUE [["Y"]].
                        88 ip0040NonRegIndSw88 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip0040CashAccessSw" maxOccurs="1"  cobol:name="IP0040-CASH-ACCESS-SW" cobol:offset="126" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ip0040PersonPresentInd" type="xs:int" maxOccurs="1"  cobol:name="IP0040-PERSON-PRESENT-IND" cobol:offset="127" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
    <xs:element name="Ip0040CrossBdrException" maxOccurs="1"  cobol:name="IP0040-CROSS-BDR-EXCEPTION" cobol:offset="128" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040IssTargetMarketInd" maxOccurs="1"  cobol:name="IP0040-ISS-TARGET-MARKET-IND" cobol:offset="129" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040PostDateServSw" maxOccurs="1"  cobol:name="IP0040-POST-DATE-SERV-SW" cobol:offset="130" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip0040PostDteServSwY88 VALUE [["Y"]].
                        88 ip0040PostDteServSwN88 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip0040MealVoucherInd" maxOccurs="1"  cobol:name="IP0040-MEAL-VOUCHER-IND" cobol:offset="131" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip0040MealVoucherIndY88 VALUE [["Y"]].
                        88 ip0040MealVoucherIndN88 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip0040NonRldblPrpdSw" maxOccurs="1"  cobol:name="IP0040-NON-RLDBL-PRPD-SW" cobol:offset="132" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040FasterFundsInd" maxOccurs="1"  cobol:name="IP0040-FASTER-FUNDS-IND" cobol:offset="134" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip0040FasterFundsNo88 VALUE [["N"]].
                        88 ip0040FasterFundsDom88 VALUE [["D"]].
                        88 ip0040FstrFndDomCrs88 VALUE [["Y"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip0040AnonPrepaidInd" maxOccurs="1"  cobol:name="IP0040-ANON-PREPAID-IND" cobol:offset="135" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip0040AnonPrepaidIndN88 VALUE [["N"]].
                        88 ip0040AnonPrepaidIndE88 VALUE [["E"]].
                        88 ip0040AnonPrepaidIndA88 VALUE [["A"]].
                        88 ip0040AnonPrepaidIndU88 VALUE [["U"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip0040DccStatusInd" maxOccurs="1"  cobol:name="IP0040-DCC-STATUS-IND" cobol:offset="136" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip0040MemberFiller" maxOccurs="1"  cobol:name="IP0040-MEMBER-FILLER" cobol:offset="137" cobol:length="14" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="14" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
