<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip00901BsArMaster" cobol:name="IP00901-BS-AR-MASTER" cobol:offset="0" cobol:length="80" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Ip00901EffectiveDate" maxOccurs="1"  cobol:name="IP00901-EFFECTIVE-DATE" cobol:offset="0" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip00901ActiveInactive" maxOccurs="1"  cobol:name="IP00901-ACTIVE-INACTIVE" cobol:offset="10" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="Ip00901ParameterMasterData" maxOccurs="1" cobol:name="IP00901-PARAMETER-MASTER-DATA" cobol:offset="11" cobol:length="8" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Ip00901TableData" maxOccurs="1" cobol:name="IP00901-TABLE-DATA" cobol:offset="19" cobol:length="61" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
