#STEP:S030_P080| PGM:SORT| DD:SORTIN
Y91dext2S030_p080SortIn=Y910.P.ATM.BACKUP.TLFDUP1(+0)
Y91dext2S030_p080SortIn.DISP=SHR,KEEP,KEEP
Y91dext2S030_p080SortInRecordType=FB
Y91dext2S030_p080SortInRecordLen=123
#STEP:S030_P080| PGM:SORT| DD:SORTOUT
Y91dext2S030_p080SortOut=Y910.P.ATM.TEMP.TLFDUP1
Y91dext2S030_p080SortOut.DISP=NEW,CATLG,DELETE
Y91dext2S030_p080SortOutRecordType=FB
Y91dext2S030_p080SortOutRecordLen=132
