<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="CheckCloseQueueGroup100" cobol:name="100-CHECK-CLOSE-QUEUE-GROUP" cobol:offset="0" cobol:length="1" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="CheckCloseQueue100" maxOccurs="1"  cobol:name="100-CHECK-CLOSE-QUEUE" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 closePmaAms88100 VALUE [["0"]].
                        88 closePmiAms88100 VALUE [["1"]].
                        88 closePimAms88100 VALUE [["2"]].
                        88 closePma88100 VALUE [["3"]].
                        88 closePmi88100 VALUE [["4"]].
                        88 closePim88100 VALUE [["5"]].
                        88 closePmt88100 VALUE [["6"]].
                        88 closeCaq88100 VALUE [["7"]].
                        88 closeCemreqMq88100 VALUE [["8"]].
                        88 closeCemresMq188100 VALUE [["9"]].
                        88 closeFaaFac88100 VALUE [["A"]].
                        88 closeCemresMq288100 VALUE [["B"]].
                        88 closeCemresMq388100 VALUE [["C"]].
                        88 closeFpq88100 VALUE [["D"]].
                        88 closeMpAch88100 VALUE [["E"]].
                        88 closeNmq88100 VALUE [["F"]].
                        88 closeQrRefunds88100 VALUE [["G"]].
                        88 closeInstq88100 VALUE [["H"]].
                        88 closeAlmqPre88100 VALUE [["I"]].
                        88 closeAlmqCha88100 VALUE [["J"]].
                        88 closeAlmqRsp88100 VALUE [["K"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
