<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip00404Table" cobol:name="IP00404-TABLE" cobol:offset="0" cobol:length="22416" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip00404EntriesFoundCount" type="xs:int" maxOccurs="1"  cobol:name="IP00404-ENTRIES-FOUND-COUNT" cobol:offset="0" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
<xs:element name="Ip00404ArRangeGrp" maxOccurs="1" cobol:name="IP00404-AR-RANGE-GRP" cobol:offset="4" cobol:length="38" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Ip00404ArRangeEntries" maxOccurs="1" cobol:name="IP00404-AR-RANGE-ENTRIES" cobol:offset="42" cobol:length="22374" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
