<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip0040iPrimaryCrncyTbl" cobol:name="IP0040I-PRIMARY-CRNCY-TBL" cobol:offset="62" cobol:length="7" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip0040iCardPrimeTxnCur" type="xs:int" maxOccurs="1"  cobol:name="IP0040I-CARD-PRIME-TXN-CUR" cobol:offset="0" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="Ip0040iCardPrimeBlngCur" type="xs:int" maxOccurs="1"  cobol:name="IP0040I-CARD-PRIME-BLNG-CUR" cobol:offset="3" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="Ip0040iCardPrimeBlngExp" type="xs:int" maxOccurs="1"  cobol:name="IP0040I-CARD-PRIME-BLNG-EXP" cobol:offset="6" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
