<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip30781TipaccdTable" cobol:name="IP30781-TIPACCD-TABLE" cobol:offset="0" cobol:length="74" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip30781ClrCyclId" type="xs:short" maxOccurs="1"  cobol:name="IP30781-CLR-CYCL-ID" cobol:offset="0" cobol:length="2" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
    <xs:element name="Ip30781EffTs" maxOccurs="1"  cobol:name="IP30781-EFF-TS" cobol:offset="2" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip30781ClrCyclDt" maxOccurs="1"  cobol:name="IP30781-CLR-CYCL-DT" cobol:offset="28" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip30781ClrCyclTm" maxOccurs="1"  cobol:name="IP30781-CLR-CYCL-TM" cobol:offset="38" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip30781RecStatCd" maxOccurs="1"  cobol:name="IP30781-REC-STAT-CD" cobol:offset="46" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip30781UtcDt" maxOccurs="1"  cobol:name="IP30781-UTC-DT" cobol:offset="47" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip30781UtcTm" maxOccurs="1"  cobol:name="IP30781-UTC-TM" cobol:offset="57" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip30781ClrCyclRpmSw" maxOccurs="1"  cobol:name="IP30781-CLR-CYCL-RPM-SW" cobol:offset="65" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ip30781ClrCyclRpmNum" type="xs:int" maxOccurs="1"  cobol:name="IP30781-CLR-CYCL-RPM-NUM" cobol:offset="66" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
    <xs:element name="Ip30781DfltDlvryCyclSw" maxOccurs="1"  cobol:name="IP30781-DFLT-DLVRY-CYCL-SW" cobol:offset="71" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip30781MqRespCd" maxOccurs="1"  cobol:name="IP30781-MQ-RESP-CD" cobol:offset="72" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip30781OvrdeTmoutSw" maxOccurs="1"  cobol:name="IP30781-OVRDE-TMOUT-SW" cobol:offset="73" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
