<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip32101CbhfChkKey" cobol:name="IP32101-CBHF-CHK-KEY" cobol:offset="28" cobol:length="50" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Ip32101CbhfGftDasetNam" maxOccurs="1"  cobol:name="IP32101-CBHF-GFT-DASET-NAM" cobol:offset="0" cobol:length="44" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ip32101CbhfFileSeqNum" type="xs:long" maxOccurs="1"  cobol:name="IP32101-CBHF-FILE-SEQ-NUM" cobol:offset="44" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
    <xs:element name="Ip32101CbhfIndCd" maxOccurs="1"  cobol:name="IP32101-CBHF-IND-CD" cobol:offset="49" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
