<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip32101ChkPtDataCbhf" cobol:name="IP32101-CHK-PT-DATA-CBHF" cobol:offset="17" cobol:length="125" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip32101CbhfDataLen" type="xs:short" maxOccurs="1"  cobol:name="IP32101-CBHF-DATA-LEN" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip32101CbhfFreq" type="xs:long" maxOccurs="1"  cobol:name="IP32101-CBHF-FREQ" cobol:offset="2" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
<xs:element name="Ip32101CbhfChkKey" maxOccurs="1" cobol:name="IP32101-CBHF-CHK-KEY" cobol:offset="11" cobol:length="50" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="Ip32101CbhfChkCnt" type="xs:long" maxOccurs="1"  cobol:name="IP32101-CBHF-CHK-CNT" cobol:offset="61" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Ip32101CbhfCycInd" type="xs:short" maxOccurs="1"  cobol:name="IP32101-CBHF-CYC-IND" cobol:offset="70" cobol:length="2" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="Ip32101CbhfCsIpmRecCnt" type="xs:int" maxOccurs="1"  cobol:name="IP32101-CBHF-CS-IPM-REC-CNT" cobol:offset="72" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
    <xs:element name="Ip32101CbhfBulkId" maxOccurs="1"  cobol:name="IP32101-CBHF-BULK-ID" cobol:offset="77" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip32101CbhfEdcDasetNam" maxOccurs="1"  cobol:name="IP32101-CBHF-EDC-DASET-NAM" cobol:offset="81" cobol:length="44" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
