<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip33701CurrConvInterface" cobol:name="IP33701-CURR-CONV-INTERFACE" cobol:offset="0" cobol:length="130" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="Ip33701CurrConvInput" maxOccurs="1" cobol:name="IP33701-CURR-CONV-INPUT" cobol:offset="0" cobol:length="39" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Ip33701CurrConvOutput" maxOccurs="1" cobol:name="IP33701-CURR-CONV-OUTPUT" cobol:offset="39" cobol:length="91" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
