<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip38201McidynamParms" cobol:name="IP38201-MCIDYNAM-PARMS" cobol:offset="0" cobol:length="164" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Ip38201Function" maxOccurs="1"  cobol:name="IP38201-FUNCTION" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip38201Allocate88 VALUE [["A"]].
                        88 ip38201Unallocate88 VALUE [["U"]].
                        88 ip38201FinalUnallocate88 VALUE [["F"]].
                        88 ip38201Delete88 VALUE [["D"]].
                        88 ip38201Info88 VALUE [["I"]].
                        88 ip38201End88 VALUE [["E"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip38201Dd" maxOccurs="1"  cobol:name="IP38201-DD" cobol:offset="1" cobol:length="8" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_100M" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip38201DdBlank88 VALUE [["        "]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="8" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip38201Dsn" maxOccurs="1"  cobol:name="IP38201-DSN" cobol:offset="9" cobol:length="44" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="Long.MAX_VALUE" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip38201DsnBlank88 VALUE [["                                            "]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="44" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
<xs:element name="Ip38201Disposition" maxOccurs="1" cobol:name="IP38201-DISPOSITION" cobol:offset="53" cobol:length="3" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Ip38201AllocateParms" maxOccurs="1" cobol:name="IP38201-ALLOCATE-PARMS" cobol:offset="56" cobol:length="79" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Ip38201ReturnCode" maxOccurs="1"  cobol:name="IP38201-RETURN-CODE" cobol:offset="135" cobol:length="4" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10K" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip38201ReturnCode000588 VALUE [["0005"]].
                        88 ip38201ReturnCode000688 VALUE [["0006"]].
                        88 ip38201ReturnCode000788 VALUE [["0007"]].
                        88 ip38201ReturnCode000888 VALUE [["0008"]].
                        88 ip38201ReturnCode000988 VALUE [["0009"]].
                        88 ip38201ReturnCode001088 VALUE [["0010"]].
                        88 ip38201ReturnCode001188 VALUE [["0011"]].
                        88 ip38201ReturnCode001288 VALUE [["0012"]].
                        88 ip38201ReturnCode001388 VALUE [["0013"]].
                        88 ip38201ReturnCode001488 VALUE [["0014"]].
                        88 ip38201ReturnCode001588 VALUE [["0015"]].
                        88 ip38201ReturnCode001688 VALUE [["0016"]].
                        88 ip38201ReturnCode001788 VALUE [["0017"]].
                        88 ip38201ReturnCode001888 VALUE [["0018"]].
                        88 ip38201ReturnCode001988 VALUE [["0019"]].
                        88 ip38201ReturnCode002088 VALUE [["0020"]].
                        88 ip38201ReturnCode002188 VALUE [["0021"]].
                        88 ip38201ReturnCode002288 VALUE [["0022"]].
                        88 ip38201ReturnCode002388 VALUE [["0023"]].
                        88 ip38201ReturnCode002488 VALUE [["0024"]].
                        88 ip38201ReturnCode002588 VALUE [["0025"]].
                        88 ip38201ReturnCode002688 VALUE [["0026"]].
                        88 ip38201ReturnCode002788 VALUE [["0027"]].
                        88 ip38201ReturnCode002888 VALUE [["0028"]].
                        88 ip38201ReturnCode002988 VALUE [["0029"]].
                        88 ip38201ReturnCode003088 VALUE [["0030"]].
                        88 ip38201ReturnCode003188 VALUE [["0031"]].
                        88 ip38201ReturnCode003288 VALUE [["0032"]].
                        88 ip38201ReturnCode003388 VALUE [["0033"]].
                        88 ip38201ReturnCode003488 VALUE [["0034"]].
                        88 ip38201ReturnCode003588 VALUE [["0035"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="4" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip38201Filler" maxOccurs="1"  cobol:name="IP38201-FILLER" cobol:offset="139" cobol:length="25" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
