<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip50201ClosedDate" cobol:name="IP50201-CLOSED-DATE" cobol:offset="26" cobol:length="10" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Ip50201ClosedCcyy" maxOccurs="1"  cobol:name="IP50201-CLOSED-CCYY" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip50201Filler1" maxOccurs="1"  cobol:name="IP50201-FILLER1" cobol:offset="4" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip50201ClosedMm" maxOccurs="1"  cobol:name="IP50201-CLOSED-MM" cobol:offset="5" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip50201Filler2" maxOccurs="1"  cobol:name="IP50201-FILLER2" cobol:offset="7" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip50201ClosedDd" maxOccurs="1"  cobol:name="IP50201-CLOSED-DD" cobol:offset="8" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
