<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip65504PdsNamesLargeGroup84" cobol:name="IP65504-PDS-NAMES-LARGE-GROUP-84" cobol:offset="20580" cobol:length="248" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip65504P2574S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2574-S" cobol:offset="4" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2574L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2574-L" cobol:offset="6" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2574" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="8" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2575S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2575-S" cobol:offset="12" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2575L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2575-L" cobol:offset="14" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2575" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="16" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2576S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2576-S" cobol:offset="20" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2576L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2576-L" cobol:offset="22" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2576" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="24" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2577S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2577-S" cobol:offset="28" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2577L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2577-L" cobol:offset="30" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2577" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="32" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2578S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2578-S" cobol:offset="36" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2578L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2578-L" cobol:offset="38" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2578" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="40" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2579S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2579-S" cobol:offset="44" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2579L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2579-L" cobol:offset="46" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2579" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="48" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2580S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2580-S" cobol:offset="52" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2580L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2580-L" cobol:offset="54" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2580" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="56" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2581S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2581-S" cobol:offset="60" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2581L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2581-L" cobol:offset="62" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2581" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="64" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2582S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2582-S" cobol:offset="68" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2582L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2582-L" cobol:offset="70" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2582" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="72" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2583S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2583-S" cobol:offset="76" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2583L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2583-L" cobol:offset="78" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2583" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="80" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2584S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2584-S" cobol:offset="84" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2584L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2584-L" cobol:offset="86" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2584" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="88" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2585S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2585-S" cobol:offset="92" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2585L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2585-L" cobol:offset="94" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2585" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="96" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2586S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2586-S" cobol:offset="100" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2586L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2586-L" cobol:offset="102" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2586" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="104" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2587S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2587-S" cobol:offset="108" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2587L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2587-L" cobol:offset="110" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2587" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="112" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2588S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2588-S" cobol:offset="116" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2588L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2588-L" cobol:offset="118" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2588" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="120" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2589S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2589-S" cobol:offset="124" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2589L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2589-L" cobol:offset="126" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2589" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="128" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2590S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2590-S" cobol:offset="132" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2590L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2590-L" cobol:offset="134" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2590" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="136" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2591S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2591-S" cobol:offset="140" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2591L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2591-L" cobol:offset="142" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2591" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="144" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2592S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2592-S" cobol:offset="148" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2592L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2592-L" cobol:offset="150" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2592" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="152" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2593S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2593-S" cobol:offset="156" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2593L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2593-L" cobol:offset="158" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2593" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="160" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2594S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2594-S" cobol:offset="164" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2594L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2594-L" cobol:offset="166" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2594" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="168" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2595S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2595-S" cobol:offset="172" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2595L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2595-L" cobol:offset="174" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2595" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="176" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2596S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2596-S" cobol:offset="180" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2596L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2596-L" cobol:offset="182" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2596" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="184" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2597S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2597-S" cobol:offset="188" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2597L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2597-L" cobol:offset="190" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2597" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="192" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2598S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2598-S" cobol:offset="196" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2598L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2598-L" cobol:offset="198" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2598" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="200" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2599S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2599-S" cobol:offset="204" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2599L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2599-L" cobol:offset="206" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2599" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="208" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2600S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2600-S" cobol:offset="212" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2600L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2600-L" cobol:offset="214" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2600" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="216" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2601S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2601-S" cobol:offset="220" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2601L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2601-L" cobol:offset="222" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2601" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="224" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2602S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2602-S" cobol:offset="228" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2602L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2602-L" cobol:offset="230" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2602" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="232" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2603S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2603-S" cobol:offset="236" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2603L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2603-L" cobol:offset="238" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2603" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="240" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2604S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2604-S" cobol:offset="244" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P2604L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P2604-L" cobol:offset="246" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller2604" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="248" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
