<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip70301PmaRusMqSrvActiveGroup" cobol:name="IP70301-PMA-RUS-MQ-SRV-ACTIVE-GROUP" cobol:offset="0" cobol:length="1" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Ip70301PmaRusMqSrvActive" maxOccurs="1"  cobol:name="IP70301-PMA-RUS-MQ-SRV-ACTIVE" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip70301PmaRusMqActveY88 VALUE [["Y"]].
                        88 ip70301PmaRusMqActveN88 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
