<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip70711ResponseData" cobol:name="IP70711-RESPONSE-DATA" cobol:offset="57" cobol:length="2047" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Ip70711MqRespCd" maxOccurs="1"  cobol:name="IP70711-MQ-RESP-CD" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip70711ResRespN VALUE [["N"]].
                        88 ip70711ResRespR VALUE [["R"]].
                        88 ip70711ResRespC VALUE [["C"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip70711StrtJobNum" maxOccurs="1"  cobol:name="IP70711-STRT-JOB-NUM" cobol:offset="1" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip70711StrtTs" maxOccurs="1"  cobol:name="IP70711-STRT-TS" cobol:offset="9" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip70711StatCd" maxOccurs="1"  cobol:name="IP70711-STAT-CD" cobol:offset="35" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip70711ResComplete VALUE [["C"]].
                        88 ip70711ResTimeout VALUE [["T"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip70711JobGrpId" maxOccurs="1"  cobol:name="IP70711-JOB-GRP-ID" cobol:offset="36" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ip70711JobGrpNum" type="xs:int" maxOccurs="1"  cobol:name="IP70711-JOB-GRP-NUM" cobol:offset="42" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="Ip70711RespDataTxtLen" type="xs:short" maxOccurs="1"  cobol:name="IP70711-RESP-DATA-TXT-LEN" cobol:offset="44" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="Ip70711RespDataTxt" maxOccurs="1"  cobol:name="IP70711-RESP-DATA-TXT" cobol:offset="46" cobol:length="2000" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2000" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip70711RejStatCd" maxOccurs="1"  cobol:name="IP70711-REJ-STAT-CD" cobol:offset="2046" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
