  package com.cloudframe.app.process;
  /* Java code generated by CloudFrame on 2025-04-29 at 05:40. */
  
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.utility.CFUtil;
  import com.cloudframe.app.data.Field;
  import java.util.ArrayList;
  import java.util.Map;
  import java.util.HashMap;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.inspct1.dto.*;
  import com.cloudframe.app.inspct1.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  
  @Component("inspct1")
  
  public class Inspct1 extends CommonProcess {
  
  Logger logger = LoggerFactory.getLogger(Inspct1.class);
  
  private Work work = new Work() ;
  
  
  
  
  
  private int tallyCount = 0;
  
  
  
  
      /**
      * process 
      * Input  :  

      * - replacPredicate                COBOL Name: WS-REPLAC-PREDICATE
      * - searchPredicate                COBOL Name: WS-SEARCH-PREDICATE
      * - convrtPredicate                COBOL Name: WS-CONVRT-PREDICATE
      * - sub3                           COBOL Name: WS-SUB3
      *
      * Output :  

      * - subEdt                         COBOL Name: WS-SUB-EDT
      * - sub3                           COBOL Name: WS-SUB3
      *
      * @throws CFException
      */
      @Override
      public int process() throws Exception {
       initVars();
       try {
       setCodePage("1047");
//  DISPLAY 'WS-REPLAC-PREDICATE ' WS-REPLAC-PREDICATE
          logger.info("WS-REPLAC-PREDICATE {}", new String(work.getReplacPredicate())); 
//  DISPLAY 'WS-SEARCH-PREDICATE ' WS-SEARCH-PREDICATE
          logger.info("WS-SEARCH-PREDICATE {}", new String(work.getSearchPredicate())); 
//  DISPLAY 'WS-CONVRT-PREDICATE ' WS-CONVRT-PREDICATE
          logger.info("WS-CONVRT-PREDICATE {}", new String(work.getConvrtPredicate())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR CHARACTERS
          tallyCount = work.getSearchPredicate().length;
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'CFM008A 1- CHARACTERS ' WS-SUB-EDT
          logger.info("CFM008A 1- CHARACTERS {}", new String(work.getSubEdt())); 
//  INSPECT WS-CONVRT-PREDICATE CONVERTING '1346' TO 'ABCD' BEFORE INITIAL '8'
          		work.setConvrtPredicate( convertBefore(work.getConvrtPredicate(),CONSTANTS.LITERAL_1346,CONSTANTS.LITERAL_ABCD,CONSTANTS.LITERAL_8) ) ; 
//  DISPLAY 'INSPCT1 (2) - ' WS-CONVRT-PREDICATE (1 : 121)
          logger.info("INSPCT1 (2) - {}", new String(substring(work.getConvrtPredicate(),0,121))); 
//  INSPECT WS-CONVRT-PREDICATE CONVERTING '1346' TO 'ABCD' AFTER INITIAL '9'
          	work.setConvrtPredicate( convertAfter(work.getConvrtPredicate(),CONSTANTS.LITERAL_1346,CONSTANTS.LITERAL_ABCD,CONSTANTS.LITERAL_9) ) ; 
//  DISPLAY 'INSPCT1 (3) - ' WS-CONVRT-PREDICATE (1 : 121)
          logger.info("INSPCT1 (3) - {}", new String(substring(work.getConvrtPredicate(),0,121))); 
//  INSPECT WS-CONVRT-PREDICATE CONVERTING 'ABCD' TO '1346' BEFORE INITIAL '8' AFTER INITIAL '9'
          	work.setConvrtPredicate( convertBeforeAfter(work.getConvrtPredicate(),CONSTANTS.LITERAL_ABCD,CONSTANTS.LITERAL_1346,CONSTANTS.LITERAL_8,CONSTANTS.LITERAL_9) ) ; 
//  DISPLAY 'INSPCT1 (4) - ' WS-CONVRT-PREDICATE (1 : 121)
          logger.info("INSPCT1 (4) - {}", new String(substring(work.getConvrtPredicate(),0,121))); 
//  INSPECT WS-CONVRT-PREDICATE CONVERTING '1346' TO 'ABCD'
          	work.setConvrtPredicate( convert(work.getConvrtPredicate(),CONSTANTS.LITERAL_1346,CONSTANTS.LITERAL_ABCD) ) ;
//  DISPLAY 'INSPCT1 (5) - ' WS-CONVRT-PREDICATE (1 : 121)
          logger.info("INSPCT1 (5) - {}", new String(substring(work.getConvrtPredicate(),0,121))); 
//  INSPECT WS-CONVRT-PREDICATE CONVERTING 'ABCD' TO '1346'
          	work.setConvrtPredicate( convert(work.getConvrtPredicate(),CONSTANTS.LITERAL_ABCD,CONSTANTS.LITERAL_1346) ) ;
//  DISPLAY 'INSPCT1 (6) - ' WS-CONVRT-PREDICATE (1 : 121)
          logger.info("INSPCT1 (6) - {}", new String(substring(work.getConvrtPredicate(),0,121))); 
//  INSPECT WS-REPLAC-PREDICATE REPLACING FIRST '%' BY '@' AFTER INITIAL '9'
          work.setReplacPredicate(  replaceFirstAfter(work.getReplacPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_AT_,CONSTANTS.LITERAL_9) ) ; 
//  DISPLAY 'INSPCT1 (7) - ' WS-REPLAC-PREDICATE (1 : 121)
          logger.info("INSPCT1 (7) - {}", new String(substring(work.getReplacPredicate(),0,121))); 
//  INSPECT WS-REPLAC-PREDICATE REPLACING LEADING '%' BY '@' AFTER INITIAL '9'
          work.setReplacPredicate(  replaceLeadingAfter(work.getReplacPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_AT_,CONSTANTS.LITERAL_9) ) ; 
//  DISPLAY 'INSPCT1 (8) - ' WS-REPLAC-PREDICATE (1 : 121)
          logger.info("INSPCT1 (8) - {}", new String(substring(work.getReplacPredicate(),0,121))); 
//  INSPECT WS-REPLAC-PREDICATE REPLACING ALL '%' BY '@' AFTER INITIAL '9'
          work.setReplacPredicate(  replaceAllAfter(work.getReplacPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_AT_,CONSTANTS.LITERAL_9) ) ; 
//  DISPLAY 'INSPCT1 (9) -' WS-REPLAC-PREDICATE (1 : 130)
          logger.info("INSPCT1 (9) -{}", new String(substring(work.getReplacPredicate(),0,130))); 
//  INSPECT WS-REPLAC-PREDICATE REPLACING FIRST '@' BY '%'
          work.setReplacPredicate(  replaceFirst(work.getReplacPredicate(),CONSTANTS.LITERAL_AT_,CONSTANTS.LITERAL_PR_)  );
//  DISPLAY 'INSPCT1 (10) - ' WS-REPLAC-PREDICATE (1 : 121)
          logger.info("INSPCT1 (10) - {}", new String(substring(work.getReplacPredicate(),0,121))); 
//  INSPECT WS-REPLAC-PREDICATE REPLACING FIRST '@' BY '%' BEFORE INITIAL '8'
          work.setReplacPredicate(  replaceFirstBefore(work.getReplacPredicate(),CONSTANTS.LITERAL_AT_,CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_8) ) ; 
//  DISPLAY 'INSPCT1 (11) -' WS-REPLAC-PREDICATE (1 : 121)
          logger.info("INSPCT1 (11) -{}", new String(substring(work.getReplacPredicate(),0,121))); 
//  INSPECT WS-REPLAC-PREDICATE REPLACING FIRST '%' BY '@' BEFORE INITIAL '8' AFTER INITIAL '9'
          work.setReplacPredicate(  replaceFirstBeforeAfter(work.getReplacPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_AT_,CONSTANTS.LITERAL_8,CONSTANTS.LITERAL_9) ) ; 
//  DISPLAY 'INSPCT1 (12) - ' WS-REPLAC-PREDICATE (1 : 121)
          logger.info("INSPCT1 (12) - {}", new String(substring(work.getReplacPredicate(),0,121))); 
//  INSPECT WS-REPLAC-PREDICATE REPLACING ALL '%' BY '@'
          work.setReplacPredicate(  replaceAll(work.getReplacPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_AT_)  );
//  DISPLAY 'INSPCT1 (13)- ' WS-REPLAC-PREDICATE (1 : 121)
          logger.info("INSPCT1 (13)- {}", new String(substring(work.getReplacPredicate(),0,121))); 
//  INSPECT WS-REPLAC-PREDICATE REPLACING ALL '@' BY '%' BEFORE INITIAL '8'
          work.setReplacPredicate(  replaceAllBefore(work.getReplacPredicate(),CONSTANTS.LITERAL_AT_,CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_8) ) ; 
//  DISPLAY 'INSPCT1 (14)- ' WS-REPLAC-PREDICATE (1 : 121)
          logger.info("INSPCT1 (14)- {}", new String(substring(work.getReplacPredicate(),0,121))); 
//  INSPECT WS-REPLAC-PREDICATE REPLACING ALL '%' BY '@' BEFORE INITIAL '8' AFTER INITIAL '9'
          work.setReplacPredicate(  replaceAllBeforeAfter(work.getReplacPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_AT_,CONSTANTS.LITERAL_8,CONSTANTS.LITERAL_9) ) ; 
//  DISPLAY 'INSPCT1 (15)- ' WS-REPLAC-PREDICATE (1 : 130)
          logger.info("INSPCT1 (15)- {}", new String(substring(work.getReplacPredicate(),0,130))); 
//  INSPECT WS-REPLAC-PREDICATE REPLACING LEADING '%' BY '@'
          work.setReplacPredicate(  replaceLeading(work.getReplacPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_AT_) );
//  DISPLAY 'INSPCT1 (16)- ' WS-REPLAC-PREDICATE (1 : 121)
          logger.info("INSPCT1 (16)- {}", new String(substring(work.getReplacPredicate(),0,121))); 
//  INSPECT WS-REPLAC-PREDICATE REPLACING LEADING '%' BY '@' BEFORE INITIAL '8'
          work.setReplacPredicate(  replaceLeadingBefore(work.getReplacPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_AT_,CONSTANTS.LITERAL_8) ) ; 
//  DISPLAY 'INSPCT1 (17) -' WS-REPLAC-PREDICATE (1 : 121)
          logger.info("INSPCT1 (17) -{}", new String(substring(work.getReplacPredicate(),0,121))); 
//  INSPECT WS-REPLAC-PREDICATE REPLACING LEADING '%' BY '@' BEFORE INITIAL '8' AFTER INITIAL '9'
          work.setReplacPredicate(  replaceLeadingBeforeAfter(work.getReplacPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_AT_,CONSTANTS.LITERAL_8,CONSTANTS.LITERAL_9) ) ; 
//  DISPLAY 'INSPCT1 (18)- ' WS-REPLAC-PREDICATE (1 : 121)
          logger.info("INSPCT1 (18)- {}", new String(substring(work.getReplacPredicate(),0,121))); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR ALL '%'
          tallyCount = tallyAll(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (19) ALL     ' WS-SUB-EDT
          logger.info("INSPCT1 (19) ALL     {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR ALL '%' BEFORE INITIAL '8'
          tallyCount = tallyAllBefore(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_8);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (20) - ALL BFORE INITIAL ' WS-SUB-EDT
          logger.info("INSPCT1 (20) - ALL BFORE INITIAL {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR ALL '%' AFTER INITIAL '9'
          tallyCount = tallyAllAfter(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_9);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (21)- ALL AFTR  INITIAL ' WS-SUB-EDT
          logger.info("INSPCT1 (21)- ALL AFTR  INITIAL {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR ALL '%' BEFORE INITIAL '8' AFTER INITIAL '9'
          tallyCount = tallyAllBeforeAfter(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_8,CONSTANTS.LITERAL_9);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  PERFORM PROCESS-1
          process1();/*PROCESS-1*/
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
       return getRc(); // Exit with return code
      // end of process method
      }
      /**
      * process1 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-1 COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      private void process1() throws Exception {
//  PERFORM PROCESS-1-SPLIT3
          process1Split3();/*PROCESS-1-SPLIT3*/
//  PERFORM PROCESS-1-SPLIT4
          process1Split4();/*PROCESS-1-SPLIT4*/
      
      }
      /**
      * process1Split3 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-1-SPLIT3 COBOL Cyclomatic complexity - 1
      * Input  :  

      * - subEdt                         COBOL Name: WS-SUB-EDT
      * - sub3                           COBOL Name: WS-SUB3
      * - searchPredicate                COBOL Name: WS-SEARCH-PREDICATE
      *
      * Output :  

      * - subEdt                         COBOL Name: WS-SUB-EDT
      * - sub3                           COBOL Name: WS-SUB3
      * - parm                           COBOL Name: WS-PARM
      *
      * @throws CFException
      */
      private void process1Split3() throws Exception {
//  DISPLAY 'INSPCT1 (22) - ALL BFORE AFTER  ' WS-SUB-EDT
          logger.info("INSPCT1 (22) - ALL BFORE AFTER  {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR LEADING '%'
          tallyCount = tallyLeading(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (23) LEADING             ' WS-SUB-EDT
          logger.info("INSPCT1 (23) LEADING             {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR LEADING '%' BEFORE INITIAL '8'
          tallyCount = tallyLeadingBefore(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_8);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (24)- LEADING BFORE INITIAL ' WS-SUB-EDT
          logger.info("INSPCT1 (24)- LEADING BFORE INITIAL {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR LEADING '%' AFTER INITIAL '9'
          tallyCount = tallyLeadingAfter(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_9);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (25) - LEADING AFTR  INITIAL ' WS-SUB-EDT
          logger.info("INSPCT1 (25) - LEADING AFTR  INITIAL {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR LEADING '%' BEFORE INITIAL '8' AFTER INITIAL '9'
          tallyCount = tallyLeadingBeforeAfter(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_8,CONSTANTS.LITERAL_9);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (25)- LEADING BFORE AFTER  ' WS-SUB-EDT
          logger.info("INSPCT1 (25)- LEADING BFORE AFTER  {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR ALL '%'
          tallyCount = tallyAll(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (26)- ALL   ' WS-SUB-EDT
          logger.info("INSPCT1 (26)- ALL   {}", new String(work.getSubEdt())); 
//  MOVE ZERO TO WS-SUB3
          work.setSub3(0);
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR LEADING '%'
          tallyCount = tallyLeading(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (27) ' WS-SUB-EDT
          logger.info("INSPCT1 (27) {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR CHARACTERS BEFORE INITIAL '8'
          tallyCount = tallyCharBefore(work.getSearchPredicate(),CONSTANTS.LITERAL_8);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (28)- LEAD  ' WS-SUB-EDT
          logger.info("INSPCT1 (28)- LEAD  {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR CHARACTERS AFTER INITIAL '9'
          tallyCount = tallyCharAfter(work.getSearchPredicate(),CONSTANTS.LITERAL_9);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (29)- AFTER INITIAL ' WS-SUB-EDT
          logger.info("INSPCT1 (29)- AFTER INITIAL {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR LEADING '%' CHARACTERS BEFORE INITIAL '8'
          tallyCount = tallyLeading(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_);
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyCharBefore(work.getSearchPredicate(),CONSTANTS.LITERAL_8);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (30)- LEAD BEFORE INTIAL ' WS-SUB-EDT
          logger.info("INSPCT1 (30)- LEAD BEFORE INTIAL {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR LEADING '%' CHARACTERS AFTER INITIAL '9'
          tallyCount = tallyLeading(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_);
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyCharAfter(work.getSearchPredicate(),CONSTANTS.LITERAL_9);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (31)- LEAD AFTER INTIAL ' WS-SUB-EDT
          logger.info("INSPCT1 (31)- LEAD AFTER INTIAL {}", new String(work.getSubEdt())); 
//  DISPLAY 'WS-SEARCH-PREDICATE (1) ' WS-SEARCH-PREDICATE
          logger.info("WS-SEARCH-PREDICATE (1) {}", new String(work.getSearchPredicate())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR ALL '%' CHARACTERS BEFORE INITIAL '8'
          tallyCount = tallyAllAfter(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_8);
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyCharBefore(work.getSearchPredicate(),CONSTANTS.LITERAL_8);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (32)- ALL BEFORE INITIAL ' WS-SUB-EDT
          logger.info("INSPCT1 (32)- ALL BEFORE INITIAL {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR ALL '%' CHARACTERS AFTER INITIAL '9'
          tallyCount = tallyAllBefore(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_9);
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyCharAfter(work.getSearchPredicate(),CONSTANTS.LITERAL_9);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (33) - ALL AFTER  INITIAL ' WS-SUB-EDT
          logger.info("INSPCT1 (33) - ALL AFTER  INITIAL {}", new String(work.getSubEdt())); 
//  INSPECT WS-SEARCH-PREDICATE TALLYING WS-SUB3 FOR ALL '%' CHARACTERS BEFORE INITIAL '8' AFTER INITIAL '9'
          tallyCount = tallyAllAfter(work.getSearchPredicate(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_8);
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyCharBeforeAfter(work.getSearchPredicate(),CONSTANTS.LITERAL_8,CONSTANTS.LITERAL_9);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (34) - ALL BEFORE AFTER  ' WS-SUB-EDT
          logger.info("INSPCT1 (34) - ALL BEFORE AFTER  {}", new String(work.getSubEdt())); 

// *
//  MOVE 0 TO WS-SUB3
          work.setSub3(0);
//  INSPECT WS-SEARCH-PREDICATE2 TALLYING WS-SUB3 FOR ALL '%' CHARACTERS AFTER INITIAL '9'
          tallyCount = tallyAllBefore(work.getSearchPredicate2(),CONSTANTS.LITERAL_PR_,CONSTANTS.LITERAL_9);
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyCharAfter(work.getSearchPredicate2(),CONSTANTS.LITERAL_9);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'INSPCT1 (35) - ALL AFTER  INITIAL ' WS-SUB-EDT
          logger.info("INSPCT1 (35) - ALL AFTER  INITIAL {}", new String(work.getSubEdt())); 
          // MOVE LOW-VALUES TO WS-PARM
          work.setParm(CONSTANTS.LOW_VALUE_1253883912);

// *
//  DISPLAY 'WS-PARM ' WS-PARM
          logger.info("WS-PARM {}", new String(work.getParm())); 
//  MOVE '0000000000 NAT CA VER ' TO WS-PARM (1 : 22)
//  LITERAL_0000000000_B4_NATCAVER = '0000000000 NAT CA VER '
          work.setParm(replace(work.getParm(),CONSTANTS.LITERAL_0000000000_B4_NATCAVER,0,22));
//  DISPLAY 'WS-PARM (1) ' WS-PARM
          logger.info("WS-PARM (1) {}", new String(work.getParm())); 
//  INSPECT WS-PARM TALLYING WS-SUB3 FOR CHARACTERS BEFORE '  '
          tallyCount = tallyCharBefore(work.getParm(),CONSTANTS.SPACE_2);
          work.setSub3(    work.getSub3() + tallyCount );
      
      }
      /**
      * process1Split4 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-1-SPLIT4 COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      private void process1Split4() throws Exception {
//  PERFORM PROCESS-2
          process2();/*PROCESS-2*/
      
      }
      /**
      * process2 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-2 COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      private void process2() throws Exception {
//  PERFORM PROCESS-2-SPLIT5
          process2Split5();/*PROCESS-2-SPLIT5*/
//  PERFORM PROCESS-2-SPLIT6
          process2Split6();/*PROCESS-2-SPLIT6*/
      
      }
      /**
      * process2Split5 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-2-SPLIT5 COBOL Cyclomatic complexity - 1
      * Input  :  

      * - sub3                           COBOL Name: WS-SUB3
      *
      * Output :  

      * - subEdt                         COBOL Name: WS-SUB-EDT
      * - sub3                           COBOL Name: WS-SUB3
      * - counterLine                    COBOL Name: COUNTER-LINE
      * - xmlSegment                     COBOL Name: XML-SEGMENT
      * - ltCount                        COBOL Name: WS-LT-COUNT
      * - htmlMLength                    COBOL Name: WS-HTML-M-LENGTH
      * - floatPlusCount                 COBOL Name: FLOAT-PLUS-COUNT
      * - floatMinusCount                COBOL Name: FLOAT-MINUS-COUNT
      * - floatDollarCount               COBOL Name: FLOAT-DOLLAR-COUNT
      * - sub1                           COBOL Name: WS-SUB1
      * - sub2                           COBOL Name: WS-SUB2
      *
      * @throws CFException
      */
      private void process2Split5() throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			Map<String,Object> updated = null;
			// End of variable declaration

//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY 'CFM008A- CHAR BEFORE SPACES  ' WS-SUB-EDT
          logger.info("CFM008A- CHAR BEFORE SPACES  {}", new String(work.getSubEdt())); 

// *
// * Ml inspects
// *
          // MOVE SPACES TO COUNTER-LINE
          work.setCounterLine(CONSTANTS.SPACE_80);
//  STRING 'ABCD1234' X'00010203' '@#$%' DELIMITED BY SIZE INTO COUNTER-LINE END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_ABCD1234);
             charArray.add(CONSTANTS.HEX_00010203);
             charArray.add(CONSTANTS.LITERAL_1033574940);
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1),charArray.get(2));
          updated = updateString(work.getCounterLine() ,joinCharArray);
          work.setCounterLine(  (char[])updated.get("string"));
//  DISPLAY '* ML 1 * COUNTER-LINE = ' COUNTER-LINE
          logger.info("* ML 1 * COUNTER-LINE = {}", new String(work.getCounterLine())); 
//  INSPECT COUNTER-LINE REPLACING CHARACTERS BY '.'
          work.setCounterLine(  replaceAllChar(work.getCounterLine(),CONSTANTS.LITERAL_34134)  );
//  DISPLAY '* ML 2 * COUNTER-LINE = ' COUNTER-LINE
          logger.info("* ML 2 * COUNTER-LINE = {}", new String(work.getCounterLine())); 

// *
//  MOVE ZERO TO WS-SUB3
          work.setSub3(0);
//  INSPECT COUNTER-LINE TALLYING WS-SUB3 FOR CHARACTERS
          tallyCount = work.getCounterLine().length;
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY '* ML 3 * # OF CHARS   = ' WS-SUB-EDT
          logger.info("* ML 3 * # OF CHARS   = {}", new String(work.getSubEdt())); 

// *
//  MOVE ZERO TO WS-SUB3
          work.setSub3(0);
          // MOVE '<htag>Header</htag>' TO XML-SEGMENT
          work.setXmlSegment(CONSTANTS.LITERAL_954407368);
//  INSPECT XML-SEGMENT (7 : ) TALLYING WS-SUB3 FOR CHARACTERS BEFORE INITIAL '</ht'
          tallyCount = tallyCharBefore(substring(work.getXmlSegment(),6,86),CONSTANTS.LITERAL_1030306145);
          work.setSub3(    work.getSub3() + tallyCount );
//  DISPLAY '* ML 4 * XML-SEGMENT  = ' XML-SEGMENT
          logger.info("* ML 4 * XML-SEGMENT  = {}", new String(work.getXmlSegment())); 
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY '* ML 4 * # OF CHARS   = ' WS-SUB-EDT
          logger.info("* ML 4 * # OF CHARS   = {}", new String(work.getSubEdt())); 

// *
//  MOVE ZERO TO WS-SUB3
          work.setSub3(0);
          // MOVE 7 TO WS-LT-COUNT
          work.setLtCount((short)7);
          // MOVE 80 TO WS-HTML-M-LENGTH
          work.setHtmlMLength((short)80);
//  INSPECT XML-SEGMENT ( WS-LT-COUNT : WS-HTML-M-LENGTH - WS-LT-COUNT ) TALLYING WS-SUB3 FOR CHARACTERS BEFORE INITIAL '</ht'
          tallyCount = tallyCharBefore(substring(work.getXmlSegment(),(work.getLtCount()-1), (work.getHtmlMLength() - work.getLtCount() + (work.getLtCount() - 1)) ),CONSTANTS.LITERAL_1030306145);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY '* ML 5 * # OF CHARS   = ' WS-SUB-EDT
          logger.info("* ML 5 * # OF CHARS   = {}", new String(work.getSubEdt())); 

// *
//  MOVE ZERO TO WS-SUB3
          work.setSub3(0);
          // MOVE 7 TO WS-LT-COUNT
          work.setLtCount((short)7);
          // MOVE 80 TO WS-HTML-M-LENGTH
          work.setHtmlMLength((short)80);
//  INSPECT XML-SEGMENT ( WS-LT-COUNT : WS-HTML-M-LENGTH - WS-LT-COUNT ) TALLYING WS-SUB3 FOR CHARACTERS BEFORE INITIAL '</HT'
          tallyCount = tallyCharBefore(substring(work.getXmlSegment(),(work.getLtCount()-1), (work.getHtmlMLength() - work.getLtCount() + (work.getLtCount() - 1)) ),CONSTANTS.LITERAL_1030274401);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY '* ML 6 * # OF CHARS   = ' WS-SUB-EDT
          logger.info("* ML 6 * # OF CHARS   = {}", new String(work.getSubEdt())); 

// *
//  MOVE ZERO TO WS-SUB3
          work.setSub3(0);
          // MOVE SPACES TO COUNTER-LINE
          work.setCounterLine(CONSTANTS.SPACE_80);
          // MOVE ALL '*' TO COUNTER-LINE
          work.setCounterLine(CONSTANTS.LITERAL_1170718772);
          // MOVE ALL ' ' TO COUNTER-LINE (1 : 7)
          work.setCounterLine(replace(work.getCounterLine(), CONSTANTS.SPACE_7, 0,7));
//  DISPLAY '* ML 7 * COUNTER-LINE = ' COUNTER-LINE
          logger.info("* ML 7 * COUNTER-LINE = {}", new String(work.getCounterLine())); 
//  INSPECT COUNTER-LINE TALLYING WS-SUB3 FOR LEADING SPACES
          tallyCount = tallyLeading(work.getCounterLine(),CONSTANTS.SPACE);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY '* ML 8 * WS-SUB3      = ' WS-SUB-EDT
          logger.info("* ML 8 * WS-SUB3      = {}", new String(work.getSubEdt())); 
//  INSPECT COUNTER-LINE REPLACING CHARACTERS BY '*'
          work.setCounterLine(  replaceAllChar(work.getCounterLine(),CONSTANTS.LITERAL_STR_)  );
//  DISPLAY '* ML 9 * COUNTER-LINE = ' COUNTER-LINE
          logger.info("* ML 9 * COUNTER-LINE = {}", new String(work.getCounterLine())); 
//  MOVE 0 TO WS-SUB3
          work.setSub3(0);
//  INSPECT COUNTER-LINE TALLYING WS-SUB3 FOR ALL '*'
          tallyCount = tallyAll(work.getCounterLine(),CONSTANTS.LITERAL_STR_);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY '* ML10 * WS-SUB3      = ' WS-SUB-EDT
          logger.info("* ML10 * WS-SUB3      = {}", new String(work.getSubEdt())); 
//  INSPECT COUNTER-LINE REPLACING ALL '*' BY SPACE
          work.setCounterLine(  replaceAll(work.getCounterLine(),CONSTANTS.LITERAL_STR_,CONSTANTS.SPACE)  );
//  DISPLAY '* ML11 * COUNTER-LINE = ' COUNTER-LINE
          logger.info("* ML11 * COUNTER-LINE = {}", new String(work.getCounterLine())); 

// *
          // MOVE '$+9-9$+-123+$$' TO COUNTER-LINE
          work.setCounterLine(CONSTANTS.LITERAL_959977949);
//  MOVE ZEROS TO FLOAT-PLUS-COUNT FLOAT-MINUS-COUNT FLOAT-DOLLAR-COUNT WS-SUB1 WS-SUB2 WS-SUB3
          work.setFloatPlusCount((short) 0);
          work.setFloatMinusCount((short) 0);
          work.setFloatDollarCount((short) 0);
          work.setSub1((short) 0);
          work.setSub2((short) 0);
          work.setSub3(0);
//  INSPECT COUNTER-LINE TALLYING FLOAT-PLUS-COUNT FOR ALL '+' FLOAT-MINUS-COUNT FOR ALL '-' FLOAT-DOLLAR-COUNT FOR ALL '$'
          tallyCount = tallyAll(work.getCounterLine(),CONSTANTS.LITERAL_PL_);
          work.setFloatPlusCount(  (short) ( work.getFloatPlusCount() + tallyCount ));
          tallyCount = tallyAll(work.getCounterLine(),CONSTANTS.LITERAL_MN_);
          work.setFloatMinusCount(  (short) ( work.getFloatMinusCount() + tallyCount ));
          tallyCount = tallyAll(work.getCounterLine(),CONSTANTS.LITERAL_33824);
          work.setFloatDollarCount(  (short) ( work.getFloatDollarCount() + tallyCount ));
//  DISPLAY '* ML12 * FLOAT-PLUS-COUNT  = ' FLOAT-PLUS-COUNT ' FLOAT-MINUS-COUNT = ' FLOAT-MINUS-COUNT ' FLOAT-DOLLAR-COUNT = ' FLOAT-DOLLAR-COUNT
          logger.info("* ML12 * FLOAT-PLUS-COUNT  = {} FLOAT-MINUS-COUNT = {} FLOAT-DOLLAR-COUNT = {}", String.valueOf(work.getFloatPlusCount()), String.valueOf(work.getFloatMinusCount()), String.valueOf(work.getFloatDollarCount())); 
//  INSPECT COUNTER-LINE (1 : 14) TALLYING WS-SUB1 FOR CHARACTERS BEFORE INITIAL '-' WS-SUB2 FOR CHARACTERS AFTER INITIAL '+'
          tallyCount = tallyCharBefore(substring(work.getCounterLine(),0,14),CONSTANTS.LITERAL_MN_);
          work.setSub1(  (short) ( work.getSub1() + tallyCount ));
          tallyCount = tallyCharAfter(substring(work.getCounterLine(),0,14),CONSTANTS.LITERAL_PL_);
          work.setSub2(  (short) ( work.getSub2() + tallyCount ));
//  MOVE WS-SUB1 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub1()).toCharArray()));
      
      }
      /**
      * process2Split6 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-2-SPLIT6 COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      private void process2Split6() throws Exception {
//  PERFORM PROCESS-3
          process3();/*PROCESS-3*/
      
      }
      /**
      * process3 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-3 COBOL Cyclomatic complexity - 1
      * Input  :  

      * - subEdt                         COBOL Name: WS-SUB-EDT
      * - sub2                           COBOL Name: WS-SUB2
      * - sub3                           COBOL Name: WS-SUB3
      *
      * Output :  

      * - subEdt                         COBOL Name: WS-SUB-EDT
      * - sub2                           COBOL Name: WS-SUB2
      * - sub3                           COBOL Name: WS-SUB3
      * - sub1                           COBOL Name: WS-SUB1
      * - counterLine                    COBOL Name: COUNTER-LINE
      * - htmlMLength                    COBOL Name: WS-HTML-M-LENGTH
      *
      * @throws CFException
      */
      private void process3() throws Exception {
//  DISPLAY '* ML13 * CHARS BEFORE INITIAL ''-'' = ' WS-SUB-EDT
          logger.info("* ML13 * CHARS BEFORE INITIAL \'-\' = {}", new String(work.getSubEdt())); 
//  MOVE WS-SUB2 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub2()).toCharArray()));
//  DISPLAY '* ML14 * CHARS AFTER  INITIAL  +   = ' WS-SUB-EDT
          logger.info("* ML14 * CHARS AFTER  INITIAL  +   = {}", new String(work.getSubEdt())); 
//  INSPECT COUNTER-LINE (1 : 14) TALLYING WS-SUB3 FOR CHARACTERS BEFORE '1'
          tallyCount = tallyCharBefore(substring(work.getCounterLine(),0,14),CONSTANTS.LITERAL_1);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY '* ML15 * CHARS BEFORE ''1'' = ' WS-SUB-EDT
          logger.info("* ML15 * CHARS BEFORE \'1\' = {}", new String(work.getSubEdt())); 

// *
          // MOVE 0 TO WS-SUB1 WS-SUB2
          work.setSub1((short)0);
          work.setSub2((short)0);
//  INSPECT COUNTER-LINE (1 : 20) TALLYING WS-SUB1 FOR CHARACTERS BEFORE INITIAL '-' WS-SUB2 FOR CHARACTERS AFTER INITIAL '-'
          tallyCount = tallyCharBefore(substring(work.getCounterLine(),0,20),CONSTANTS.LITERAL_MN_);
          work.setSub1(  (short) ( work.getSub1() + tallyCount ));
          tallyCount = tallyCharAfter(substring(work.getCounterLine(),0,20),CONSTANTS.LITERAL_MN_);
          work.setSub2(  (short) ( work.getSub2() + tallyCount ));
//  MOVE WS-SUB1 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub1()).toCharArray()));
//  DISPLAY '* ML16 * CHARS BEFORE INITIAL ''-'' = ' WS-SUB-EDT
          logger.info("* ML16 * CHARS BEFORE INITIAL \'-\' = {}", new String(work.getSubEdt())); 
//  MOVE WS-SUB2 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub2()).toCharArray()));
//  DISPLAY '* ML17 * CHARS AFTER  INITIAL ''-'' = ' WS-SUB-EDT
          logger.info("* ML17 * CHARS AFTER  INITIAL \'-\' = {}", new String(work.getSubEdt())); 

// *
          // MOVE LOW-VALUES TO COUNTER-LINE
          work.setCounterLine(CONSTANTS.LOW_VALUE_1253879107);
//  DISPLAY '* ML18 * COUNTER-LINE (Before Inspect) ' COUNTER-LINE
          logger.info("* ML18 * COUNTER-LINE (Before Inspect) {}", new String(work.getCounterLine())); 
//  INSPECT COUNTER-LINE REPLACING ALL LOW-VALUE BY SPACE
          work.setCounterLine(  replaceAll(work.getCounterLine(),CONSTANTS.LOW_VALUE_STRING,CONSTANTS.SPACE)  );
//  DISPLAY '* ML19 * COUNTER-LINE (After  Inspect) ' COUNTER-LINE
          logger.info("* ML19 * COUNTER-LINE (After  Inspect) {}", new String(work.getCounterLine())); 
          // MOVE HIGH-VALUES TO COUNTER-LINE
          work.setCounterLine(CONSTANTS.HIGH_VALUE_1455163297);
//  DISPLAY '* ML20 * COUNTER-LINE (Before Inspect) ' COUNTER-LINE
          logger.info("* ML20 * COUNTER-LINE (Before Inspect) {}", new String(work.getCounterLine())); 
//  INSPECT COUNTER-LINE REPLACING ALL HIGH-VALUE BY '$'
          work.setCounterLine(  replaceAll(work.getCounterLine(),CONSTANTS.HIGH_VALUE_STRING,CONSTANTS.LITERAL_33824)  );
//  DISPLAY '* ML21 * COUNTER-LINE (After  Inspect) ' COUNTER-LINE
          logger.info("* ML21 * COUNTER-LINE (After  Inspect) {}", new String(work.getCounterLine())); 

// *
          // MOVE '&<''"">123&<''"">&<&<''"">''>''>""' TO COUNTER-LINE
          work.setCounterLine(CONSTANTS.LITERAL_534421107);
          // MOVE 50 TO WS-HTML-M-LENGTH
          work.setHtmlMLength((short)50);
//  MOVE 0 TO WS-SUB3
          work.setSub3(0);
//  INSPECT COUNTER-LINE (1 : WS-HTML-M-LENGTH ) TALLYING WS-SUB3 FOR ALL "&" "<" ">" "'" """"
          tallyCount = tallyAll(substring(work.getCounterLine(),0,work.getHtmlMLength()),CONSTANTS.LITERAL_NP_);
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyAll(substring(work.getCounterLine(),0,work.getHtmlMLength()),CONSTANTS.LITERAL_34568);
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyAll(substring(work.getCounterLine(),0,work.getHtmlMLength()),CONSTANTS.LITERAL_34630);
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyAll(substring(work.getCounterLine(),0,work.getHtmlMLength()),CONSTANTS.LITERAL_BS_QT_);
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyAll(substring(work.getCounterLine(),0,work.getHtmlMLength()),CONSTANTS.LITERAL_BS_);
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY '* ML22 * SPECIAL CHAR COUNT = ' WS-SUB-EDT
          logger.info("* ML22 * SPECIAL CHAR COUNT = {}", new String(work.getSubEdt())); 
//  MOVE 0 TO WS-SUB3
          work.setSub3(0);
//  INSPECT COUNTER-LINE (1 : WS-HTML-M-LENGTH ) TALLYING WS-SUB3 FOR ALL AMPERSAND LESSTHAN GREATERTHAN APOSTROPHE DOUBLQUOTE
          tallyCount = tallyAll(substring(work.getCounterLine(),0,work.getHtmlMLength()),work.getAmpersand());
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyAll(substring(work.getCounterLine(),0,work.getHtmlMLength()),work.getLessthan());
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyAll(substring(work.getCounterLine(),0,work.getHtmlMLength()),work.getGreaterthan());
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyAll(substring(work.getCounterLine(),0,work.getHtmlMLength()),work.getApostrophe());
          work.setSub3(    work.getSub3() + tallyCount );
          tallyCount = tallyAll(substring(work.getCounterLine(),0,work.getHtmlMLength()),work.getDoublquote());
          work.setSub3(    work.getSub3() + tallyCount );
//  MOVE WS-SUB3 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub3()).toCharArray()));
//  DISPLAY '* ML23 * SPECIAL CHAR COUNT = ' WS-SUB-EDT
          logger.info("* ML23 * SPECIAL CHAR COUNT = {}", new String(work.getSubEdt())); 
          // MOVE '$+9-9$+-123+$$' TO COUNTER-LINE
          work.setCounterLine(CONSTANTS.LITERAL_959977949);
          // MOVE 0 TO WS-SUB1
          work.setSub1((short)0);
//  INSPECT COUNTER-LINE (1 : 14) TALLYING WS-SUB1 FOR CHARACTERS AFTER INITIAL '+'
          tallyCount = tallyCharAfter(substring(work.getCounterLine(),0,14),CONSTANTS.LITERAL_PL_);
          work.setSub1(  (short) ( work.getSub1() + tallyCount ));
//  MOVE WS-SUB1 TO WS-SUB-EDT
//  FORMAT_2062691925 = "ZZZZZZZZ9"
          work.setSubEdt(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2062691925,String.valueOf(work.getSub1()).toCharArray()));
//  DISPLAY '* ML24 * CHARS AFTER  INITIAL ''+'' = ' WS-SUB-EDT
          logger.info("* ML24 * CHARS AFTER  INITIAL \'+\' = {}", new String(work.getSubEdt())); 

// *
// *    Move
// *
//  STOP RUN
          throw Terminate.TERMINATE;
      
      }
  
  
      /**
* This method pre-initializes variables consistent with
* what a mainframe program would have done at the start of a program
*/
      @Override
      public void initVars() throws CFException {
      setProgramEnded(false);
          if(!isInitDone()) {
          	this.setRc(0);
          	setInitDone(true);
          }
        CFUtil.resetDecimalAsComma();
       }
  
  
  
  
  
  
  }
