package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.utility.CFUtil;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] SPACE_3 = CFUtil.fillSpaces(3);
public static final char[] SPACE_7 = CFUtil.fillSpaces(7);
public static final char[] SPACE_8 = CFUtil.fillSpaces(8);
public static final char[] SPACE_4 = CFUtil.fillSpaces(4);
public static final char[] SPACE_50 = CFUtil.fillSpaces(50);
public static final char[] SPACE_9 = CFUtil.fillSpaces(9);
public static final char[] SPACE_17 = CFUtil.fillSpaces(17);
public static final char[] ZERO_8 = CFUtil.fill(8,"0");
public static final char[] SPACE_57 = CFUtil.fillSpaces(57);
public static final char[] SPACE_2 = CFUtil.fillSpaces(2);
public static final char[] SPACE_32762 = CFUtil.fillSpaces(32762);
public static final char[] FORMAT1311677340 = "X(08)BX(08)".toCharArray();
public static final char[] FORMAT_1027795424 = "99BB".toCharArray();
public static final char[] FORMAT_33154069 = "99/".toCharArray();
public static final char[] FORMAT_33154658 = "99B".toCharArray();
public static final char[] LITERAL_1482901889 = "12/28/2121.42.37".toCharArray();
public static final char[] LITERAL_1484748993 = "12/28/2121.44.39".toCharArray();
public static final char[] LOW_VALUE_STRING = new String(new byte[]{0}).toCharArray();
 
}
