#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
# Program CFSORT09 | DD : OUTFILE | RecordFormat : FixedLength | RecordLength : 133
CFSORT09.ddname.OUTFILE=DisplayFile
CFSORT09.DisplayFile=DisplayFile
CFSORT09.DisplayFileCharSet=cp1047
CFSORT09.DisplayFileCRLFflag=no
# Program CFSORT09 | DD : TESTDATA | RecordFormat : FixedLength | RecordLength : 59
CFSORT09.ddname.TESTDATA=TestdataFile
CFSORT09.TestdataFile=TestdataFile
CFSORT09.TestdataFileCharSet=cp1047
CFSORT09.TestdataFileCRLFflag=no
# 
# End of CFSORT09
