<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="QueryFilterSvcSql" cobol:name="QUERY-FILTER-SVC-SQL" cobol:offset="0" cobol:length="375" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="QueryFilterSvcSqlFiller1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="8" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller3" maxOccurs="1"  cobol:name="FILLER" cobol:offset="18" cobol:length="24" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="24" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller4" maxOccurs="1"  cobol:name="FILLER" cobol:offset="42" cobol:length="35" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="35" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller5" maxOccurs="1"  cobol:name="FILLER" cobol:offset="77" cobol:length="35" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="35" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller6" maxOccurs="1"  cobol:name="FILLER" cobol:offset="112" cobol:length="41" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="41" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller7" maxOccurs="1"  cobol:name="FILLER" cobol:offset="153" cobol:length="39" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="39" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller8" maxOccurs="1"  cobol:name="FILLER" cobol:offset="192" cobol:length="31" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="31" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller9" maxOccurs="1"  cobol:name="FILLER" cobol:offset="223" cobol:length="31" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="31" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller10" maxOccurs="1"  cobol:name="FILLER" cobol:offset="254" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller11" maxOccurs="1"  cobol:name="FILLER" cobol:offset="280" cobol:length="25" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller12" maxOccurs="1"  cobol:name="FILLER" cobol:offset="305" cobol:length="44" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller13" maxOccurs="1"  cobol:name="FILLER" cobol:offset="349" cobol:length="24" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="24" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller14" maxOccurs="1"  cobol:name="FILLER" cobol:offset="373" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="QueryFilterSvcSqlFiller15" maxOccurs="1"  cobol:name="FILLER" cobol:offset="374" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
