<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Sqlda" cobol:name="SQLDA" cobol:offset="0" cobol:length="33016" cobol:datatype="Grp-VarLen" cobol:hasParent="false" cobol:dependingArrayLen="44" cobol:offsetToVariableArray="16"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Sqldaid" maxOccurs="1"  cobol:name="SQLDAID" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Sqldabc" type="xs:int" maxOccurs="1"  cobol:name="SQLDABC" cobol:offset="8" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Sqln" type="xs:short" maxOccurs="1"  cobol:name="SQLN" cobol:offset="12" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Sqld" type="xs:short" maxOccurs="1"  cobol:name="SQLD" cobol:offset="14" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
<xs:element name="Sqlvar" maxOccurs="750" cobol:name="SQLVAR" cobol:offset="16" cobol:length="44" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
