# Program CFSORT10 | DD : FILEIN | RecordFormat : FixedLength | RecordLength : 80
CFSORT10.ddname.FILEIN=FileIn
CFSORT10.FileIn=FileIn
CFSORT10.FileInCharSet=cp1047
CFSORT10.FileInCRLFflag=no
# Program CFSORT10 | DD : FILEOUT | RecordFormat : FixedLength | RecordLength : 80
CFSORT10.ddname.FILEOUT=FileOut
CFSORT10.FileOut=FileOut
CFSORT10.FileOutCharSet=cp1047
CFSORT10.FileOutCRLFflag=no
# 
# End of CFSORT10
