# Program QSAMRW01 | DD : SYS103 | RecordFormat : FixedLength | RecordLength : 1020
QSAMRW01.ddname.SYS103=QA.QA000258.CLF.SYS103.CF
QSAMRW01.Sys103FileIdHistoryFile=QA.QA000258.CLF.SYS103.CF
STEP01.QSAMRW01.Sys103FileIdHistoryFile=QA.QA000258.CLF.SYS103.CF
STEP01.QSAMRW01.Sys103FileIdHistoryFile.DISP=SHR,KEEP,KEEP
STEP02.QSAMRW01.Sys103FileIdHistoryFile=QA.QA000258.CLF.SYS103.CF
STEP02.QSAMRW01.Sys103FileIdHistoryFile.DISP=SHR,KEEP,KEEP
QSAMRW01.Sys103FileIdHistoryFileCharSet=cp1047
QSAMRW01.Sys103FileIdHistoryFileCRLFflag=no
# 
# End of QSAMRW01
