#STEP:DELETE| PGM:IEFBR14| DD:SYS103
DELETE.IEFBR14.Sys103=QA.QA000258.CLF.SYS103.CF
DELETE.IEFBR14.Sys103.DISP=MOD,DELETE,DELETE
#
#STEP:DELETE| PGM:IEFBR14| DD:SYSOUT
DELETE.IEFBR14.Sysout=QA.QA000258.CLF.STEP01.SYSOUT.CF
DELETE.IEFBR14.Sysout.DISP=MOD,DELETE,DELETE
#
#STEP:ALLOC| PGM:IEFBR14| DD:SYS103
ALLOC.IEFBR14.Sys103=QA.QA000258.CLF.SYS103.CF
ALLOC.IEFBR14.Sys103.DISP=MOD,CATLG,DELETE
#
#STEP:ALLOC| PGM:IEFBR14| DD:SYSOUT
ALLOC.IEFBR14.Sysout=QA.QA000258.CLF.STEP01.SYSOUT.CF
ALLOC.IEFBR14.Sysout.DISP=MOD,CATLG,DELETE
#
