<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip02014lTableDataFields" cobol:name="IP02014L-TABLE-DATA-FIELDS" cobol:offset="11" cobol:length="921" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Ip02014lGeoScopeCode" maxOccurs="1"  cobol:name="IP02014L-GEO-SCOPE-CODE" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip02014lPaGlobal88 VALUE [["G"]].
                        88 ip02014lPaLocal88 VALUE [["L"]].
                        88 ip02014lPaRegional88 VALUE [["R"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip02014lHostInd" maxOccurs="1"  cobol:name="IP02014L-HOST-IND" cobol:offset="1" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip02014lPaIsHost88 VALUE [["Y"]].
                        88 ip02014lNotTheHost88 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
<xs:element name="Ip02014lImpBulkId" maxOccurs="1" cobol:name="IP02014L-IMP-BULK-ID" cobol:offset="2" cobol:length="4" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="Ip02014lNumCurrCd" type="xs:int" maxOccurs="1"  cobol:name="IP02014L-NUM-CURR-CD" cobol:offset="6" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
    <xs:element name="Ip02014lOfsoilDataTypCd" maxOccurs="1"  cobol:name="IP02014L-OFSOIL-DATA-TYP-CD" cobol:offset="9" cobol:length="3" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_1000" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip02014lPaTransLevel88 VALUE [["TXL"]].
                        88 ip02014lPaTransLevelObs88 VALUE [["TXO"]].
                        88 ip02014lPaSummaryLevel88 VALUE [["SUM"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="3" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip02014lMrchntSplitCd" maxOccurs="1"  cobol:name="IP02014L-MRCHNT-SPLIT-CD" cobol:offset="12" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip02014lIncMrchtSpltY88 VALUE [["Y"]].
                        88 ip02014lIncMrchtSpltN88 VALUE [["N"]].
                        88 ip02014lIncMrchntSpltC88 VALUE [["C"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip02014lCurrSplitCd" maxOccurs="1"  cobol:name="IP02014L-CURR-SPLIT-CD" cobol:offset="13" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip02014lCurrSplitYes88 VALUE [["Y"]].
                        88 ip02014lCurrSpitNo88 VALUE [["N"]].
                        88 ip02014lCurrSplitCond88 VALUE [["C"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip02014lAcquirerSplitCd" maxOccurs="1"  cobol:name="IP02014L-ACQUIRER-SPLIT-CD" cobol:offset="14" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip02014lAcquirerSplitYes88 VALUE [["Y"]].
                        88 ip02014lAcquirerSplitNo88 VALUE [["N"]].
                        88 ip02014lAcquirerSplitCon88 VALUE [["C"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip02014lDomCollOnlyCd" maxOccurs="1"  cobol:name="IP02014L-DOM-COLL-ONLY-CD" cobol:offset="15" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip02014lDomCollOnlySplt88 VALUE [["S"]].
                        88 ip02014lDomCollOnlyHost88 VALUE [["H"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip02014lOnsoilDataShrSw" maxOccurs="1"  cobol:name="IP02014L-ONSOIL-DATA-SHR-SW" cobol:offset="16" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip02014lDataShrAllowed88 VALUE [["Y"]].
                        88 ip02014lDataShrNotAllow88 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
         <xs:element name="Ip02014lClrCycleNum" type="xs:int" maxOccurs="1"  cobol:name="IP02014L-CLR-CYCLE-NUM" cobol:offset="17" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="Ip02014lDtaWrhsOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-DTA-WRHS-ONSOIL-SW" cobol:offset="19" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lBllngOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-BLLNG-ONSOIL-SW" cobol:offset="20" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lSetlOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-SETL-ONSOIL-SW" cobol:offset="21" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lClrOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-CLR-ONSOIL-SW" cobol:offset="22" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lAmsOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-AMS-ONSOIL-SW" cobol:offset="23" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lMcomOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-MCOM-ONSOIL-SW" cobol:offset="24" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lMdsOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-MDS-ONSOIL-SW" cobol:offset="25" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lStndInOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-STND-IN-ONSOIL-SW" cobol:offset="26" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lAuthOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-AUTH-ONSOIL-SW" cobol:offset="27" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lPushOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-PUSH-ONSOIL-SW" cobol:offset="28" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lIncontrolOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-INCONTROL-ONSOIL-SW" cobol:offset="29" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lEsrvcOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-ESRVC-ONSOIL-SW" cobol:offset="30" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lGftOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-GFT-ONSOIL-SW" cobol:offset="31" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lBnknetOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-BNKNET-ONSOIL-SW" cobol:offset="32" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lMdesOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-MDES-ONSOIL-SW" cobol:offset="33" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lZappOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-ZAPP-ONSOIL-SW" cobol:offset="34" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lCemOnsoilSw" maxOccurs="1"  cobol:name="IP02014L-CEM-ONSOIL-SW" cobol:offset="35" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lRptHdrName" maxOccurs="1"  cobol:name="IP02014L-RPT-HDR-NAME" cobol:offset="36" cobol:length="80" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="80" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lClrPrcssCd" maxOccurs="1"  cobol:name="IP02014L-CLR-PRCSS-CD" cobol:offset="116" cobol:length="4" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10K" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 ip02014lGlobalPrcssCd88 VALUE [["GCMS"]].
                        88 ip02014lLocalPrcssCd88 VALUE [["LCMS"]].
                        88 ip02014lRedactPrcssCd88 VALUE [["RCMS"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="4" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Ip02014lOnUsPrcssAgrmtId" maxOccurs="1"  cobol:name="IP02014L-ON-US-PRCSS-AGRMT-ID" cobol:offset="120" cobol:length="11" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lOperSysId" maxOccurs="1"  cobol:name="IP02014L-OPER-SYS-ID" cobol:offset="131" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lDbId" maxOccurs="1"  cobol:name="IP02014L-DB-ID" cobol:offset="151" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip02014lFiller" maxOccurs="1"  cobol:name="IP02014L-FILLER" cobol:offset="171" cobol:length="750" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="750" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
