package com.cloudframe.app.mcsort02.file.records;
import com.cloudframe.app.sort.model.SortKeyObject;
/* Java Code Generated by CloudFrame */

import com.cloudframe.app.data.Field;
import java.util.Comparator;

public class SortTableIdKeys extends SortKeyObject{

	private  long sortRecPos = 0;
	private  int sortRecLen = 0;
	private  int fileIndx = 0;
    private byte[] sortTableId;
    private byte[] sortTableEffDate;
    private byte[] sortTableKeyData;
    private byte[] sort4TableId;
    private byte[] sort4Key;
    private byte[] sort4TableEffDate;
    private byte[] sort5TableId;
    private byte[] sort5Key;
    private byte[] sort5TableEffDate;
	
	public long getSortRecPos() {
		return sortRecPos;
	}

	public void setSortRecPos(long sortRecPos) {
		this.sortRecPos = sortRecPos;
	}

	public int getSortRecLen() {
		return sortRecLen;
	}

	public void setSortRecLen(int sortRecLen) {
		this.sortRecLen = sortRecLen;
	}
	
	public int getFileIndx() {
		return fileIndx;
	}

	public void setFileIndx(int indx) {
		this.fileIndx = indx;
	}
	
    /* Display - String - sortTableId */
	public byte[] getSortTableId() {
		return sortTableId;
	}

	public void setSortTableId(byte[] val) {
		this.sortTableId = val; 
	}
    /* Display - String - sortTableEffDate */
	public byte[] getSortTableEffDate() {
		return sortTableEffDate;
	}

	public void setSortTableEffDate(byte[] val) {
		this.sortTableEffDate = val; 
	}
    /* Display - String - sortTableKeyData */
	public byte[] getSortTableKeyData() {
		return sortTableKeyData;
	}

	public void setSortTableKeyData(byte[] val) {
		this.sortTableKeyData = val; 
	}
    /* Display - String - sort4TableId */
	public byte[] getSort4TableId() {
		return sort4TableId;
	}

	public void setSort4TableId(byte[] val) {
		this.sort4TableId = val; 
	}
    /* Display - String - sort4Key */
	public byte[] getSort4Key() {
		return sort4Key;
	}

	public void setSort4Key(byte[] val) {
		this.sort4Key = val; 
	}
    /* Display - String - sort4TableEffDate */
	public byte[] getSort4TableEffDate() {
		return sort4TableEffDate;
	}

	public void setSort4TableEffDate(byte[] val) {
		this.sort4TableEffDate = val; 
	}
    /* Display - String - sort5TableId */
	public byte[] getSort5TableId() {
		return sort5TableId;
	}

	public void setSort5TableId(byte[] val) {
		this.sort5TableId = val; 
	}
    /* Display - String - sort5Key */
	public byte[] getSort5Key() {
		return sort5Key;
	}

	public void setSort5Key(byte[] val) {
		this.sort5Key = val; 
	}
    /* Display - String - sort5TableEffDate */
	public byte[] getSort5TableEffDate() {
		return sort5TableEffDate;
	}

	public void setSort5TableEffDate(byte[] val) {
		this.sort5TableEffDate = val; 
	}

	public static Comparator<SortTableIdKeys> getSortTableIdComparator(boolean isAsc) {
		return isAsc ? (o1, o2) -> Field.compareBytes(o1.getSortTableId(), o2.getSortTableId())
				: (o1, o2) -> Field.compareBytes(o2.getSortTableId(), o1.getSortTableId());
	}
	
	public static Comparator<SortTableIdKeys> getSortTableEffDateComparator(boolean isAsc) {
		return isAsc ? (o1, o2) -> Field.compareBytes(o1.getSortTableEffDate(), o2.getSortTableEffDate())
				: (o1, o2) -> Field.compareBytes(o2.getSortTableEffDate(), o1.getSortTableEffDate());
	}
	
	public static Comparator<SortTableIdKeys> getSortTableKeyDataComparator(boolean isAsc) {
		return isAsc ? (o1, o2) -> Field.compareBytes(o1.getSortTableKeyData(), o2.getSortTableKeyData())
				: (o1, o2) -> Field.compareBytes(o2.getSortTableKeyData(), o1.getSortTableKeyData());
	}
	
	public static Comparator<SortTableIdKeys> getSort4TableIdComparator(boolean isAsc) {
		return isAsc ? (o1, o2) -> Field.compareBytes(o1.getSort4TableId(), o2.getSort4TableId())
				: (o1, o2) -> Field.compareBytes(o2.getSort4TableId(), o1.getSort4TableId());
	}
	
	public static Comparator<SortTableIdKeys> getSort4KeyComparator(boolean isAsc) {
		return isAsc ? (o1, o2) -> Field.compareBytes(o1.getSort4Key(), o2.getSort4Key())
				: (o1, o2) -> Field.compareBytes(o2.getSort4Key(), o1.getSort4Key());
	}
	
	public static Comparator<SortTableIdKeys> getSort4TableEffDateComparator(boolean isAsc) {
		return isAsc ? (o1, o2) -> Field.compareBytes(o1.getSort4TableEffDate(), o2.getSort4TableEffDate())
				: (o1, o2) -> Field.compareBytes(o2.getSort4TableEffDate(), o1.getSort4TableEffDate());
	}
	
	public static Comparator<SortTableIdKeys> getSort5TableIdComparator(boolean isAsc) {
		return isAsc ? (o1, o2) -> Field.compareBytes(o1.getSort5TableId(), o2.getSort5TableId())
				: (o1, o2) -> Field.compareBytes(o2.getSort5TableId(), o1.getSort5TableId());
	}
	
	public static Comparator<SortTableIdKeys> getSort5KeyComparator(boolean isAsc) {
		return isAsc ? (o1, o2) -> Field.compareBytes(o1.getSort5Key(), o2.getSort5Key())
				: (o1, o2) -> Field.compareBytes(o2.getSort5Key(), o1.getSort5Key());
	}
	
	public static Comparator<SortTableIdKeys> getSort5TableEffDateComparator(boolean isAsc) {
		return isAsc ? (o1, o2) -> Field.compareBytes(o1.getSort5TableEffDate(), o2.getSort5TableEffDate())
				: (o1, o2) -> Field.compareBytes(o2.getSort5TableEffDate(), o1.getSort5TableEffDate());
	}
	
}
