#STEP:STEP002| PGM:IEBGENER| DD:SYSUT1
STEP002.IEBGENER.Sysut1=CLOUDFRM.IEBGENER.DATA1
STEP002.IEBGENER.Sysut1.DISP=SHR,KEEP,KEEP
STEP002.IEBGENER.Sysut1.RecordType=FB
STEP002.IEBGENER.Sysut1.RecordLen=<recordLen>
#
#STEP:STEP002| PGM:IEBGENER| DD:SYSUT2
STEP002.IEBGENER.Sysut2=STEP002.IEBGENER.SYSUT2.SYSOUT
#
