#common-test-properties
spring.main.log-startup-info=OFF
logging.pattern.file=%msg%n
logging.file.name=READ0003-JunitTest.log
logging.logback.rollingpolicy.clean-history-on-start=true
logging.level.com.zaxxer=OFF
logging.level.com.cloudframe.app.dao.CFDataSourceConfiguration=OFF
logging.level.com.cloudframe.app.vsam.VSAMClusterUtil=OFF
logging.level.com.cloudframe.app.utility.CFConfiguration=OFF
#test-specific-properties
# compare.files[0]=ExpectedREAD0003.MF,READ0003-JunitTest.log
#compare.files[1]=ExpectedOutPutFile,GeneratedOutputFile
#project-specific-properties
#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
# spring.main.lazy-initialization=true
GLOBAL.ddname.SYS003=IpmFile
GLOBAL.IpmFile=SYS003
GLOBAL.IpmFileCharSet=cp1047
GLOBAL.IpmFileCRLFflag=no
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
