# Program ASAPRNT | DD : REPOUT | RecordFormat : FixedLength | RecordLength : 132
ASAPRNT.ddname.REPOUT=Repout
ASAPRNT.Repout=Repout
ASAPRNT.RepoutCharSet=cp1047
ASAPRNT.RepoutCRLFflag=no
# 
# End of ASAPRNT
