#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
spring.main.allow-circular-references=true
cf.jcl.batch=true
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=BINARY    
# Program CFSORT09 | DD : OUTFILE | RecordFormat : FixedLength | RecordLength : 133
CFSORT09.ddname.OUTFILE=DisplayFile
CFSORT09.DisplayFile=DisplayFile
CFSORT09.DisplayFileCharSet=cp1047
CFSORT09.DisplayFileCRLFflag=no
# Program CFSORT09 | DD : TESTDATA | RecordFormat : FixedLength | RecordLength : 59
CFSORT09.ddname.TESTDATA=TestdataFile
CFSORT09.TestdataFile=TestdataFile
CFSORT09.TestdataFileCharSet=cp1047
CFSORT09.TestdataFileCRLFflag=no
#logging.level.com.cloudframe=DEBUG
logging.file.name=console-CFSORT09.log
logging.pattern.file=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
cf.has.sort=true
cf.sort.useTempFile=no
cf.sort.using.file.strategy=yes
cf_sort_limit_memory_of_heap_percentage=60
cf_sort_inmemorykey_use_sync=true
cf_sort_force_inmemory_strategy=false
cf_sort_force_inmemory_key_strategy=false
cf_sort_force_tempfile_with_record_strategy=false
cf_sort_force_tempfile_strategy=false
HIGH_VALUE=Z
# 
# End of CFSORT09
