  package com.cloudframe.app.process.impl;
  /* Java code generated by CloudFrame on 2025-04-28 at 08:00. */
  
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.beans.factory.annotation.Qualifier;
  import com.cloudframe.app.mc155.file.*;
  import com.cloudframe.app.mc155.Mc155Ctx.*;
  import com.cloudframe.app.mc155.Mc155Ctx;
  import com.cloudframe.app.process.Mc155;
  import com.cloudframe.app.process.BaseProcess;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.dto.GlobalExecutorCtx;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.data.Field;
  import com.cloudframe.app.utility.CFConstants;
  import com.cloudframe.app.mc155.dto.*;
  import com.cloudframe.app.mc155.file.records.Sys109UniqueFileIdRecGroup;
  import com.cloudframe.app.mc155.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("mc155")
  
  public class Mc155Impl extends CommonProcess implements Mc155 {
  
  Logger logger = LoggerFactory.getLogger(Mc155Impl.class);
  
  
  
  
  @Autowired 
  @Qualifier("mc155_sys109UniqueFileIdFile")
  Sys109UniqueFileIdFile sys109UniqueFileIdFile;
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      public int process(Mc155Ctx programCtx) throws Exception {
       try {
       setCodePage("1047");
            // Reset program ended flag
           programCtx.setProgramEnded(false);
          ;
//  PERFORM MAINLINE-PARA
          mainlinePara(programCtx);/*MAINLINE-PARA*/
          if (programCtx.isProgramEnded()) {
              return programCtx.getRc();
          }
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
        finally {
      		if(sys109UniqueFileIdFile.hasOpened() && !sys109UniqueFileIdFile.isReadOnly()) { 
      			sys109UniqueFileIdFile.flush(); 
      		}
      }
      
       return programCtx.getRc(); // Exit with return code
      // end of process method
      }
      /**
      * mainlinePara 
      *   This method is derived from 
  *   COBOL Paragraph - MAINLINE-PARA COBOL Cyclomatic complexity - 2
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      @Override
      public void mainlinePara(Mc155Ctx programCtx) throws Exception {
//  PERFORM 1200-OPEN-SYS109
          openSys109(programCtx.getOpenSys109InCtx());/*1200-OPEN-SYS109*/
          if (programCtx.isProgramEnded()) {
              return ;
          }
//  PERFORM 1400-LOAD-ALTERNATE-TABLE
          loadAlternateTable(programCtx.getLoadAlternateTableInCtx());/*1400-LOAD-ALTERNATE-TABLE*/
          if (programCtx.isProgramEnded()) {
              return ;
          }
//  PERFORM 1500-CLOSE-SYS109
          closeSys109(programCtx.getCloseSys109InCtx());/*1500-CLOSE-SYS109*/
          if (programCtx.isProgramEnded()) {
              return ;
          }
//  STOP RUN
          throw Terminate.TERMINATE;
      
      }
      /**
      * openSys109 
      *   This method is derived from 
  *   COBOL Paragraph - 1200-OPEN-SYS109 COBOL Cyclomatic complexity - 4
      * Input  : None 

      * Output :  

      * - uniqueFileIdFileStatus200      COBOL Name: 200-UNIQUE-FILE-ID-FILE-STATUS
      *
      * @throws CFException
      */
      @Override
      public OpenSys109OutCtx openSys109(OpenSys109InCtx methodIn) throws Exception {
Mc155Ctx programCtx = methodIn.getMc155Ctx();
OpenSys109OutCtx methodOut = methodIn.getOpenSys109OutCtx();
//  OPEN INPUT SYS109-UNIQUE-FILE-ID-FILE
          	sys109UniqueFileIdFile.setVsamCluster("MC155" /*program name*/);
          sys109UniqueFileIdFile.open("r"); 
          methodOut.setUniqueFileIdFileStatus200(sys109UniqueFileIdFile.getStatusString() );
//  IF 88-200-SYS109-STATUS-GOOD OR 88-200-SYS109-STATUS-97
//  ELSE
          if (!(methodOut.isSys109StatusGood88200())  && !(methodOut.isSys109Status9788200()) ) { 
//  DISPLAY 'OPEN SYS109 FAILE : STATUS CODE = ' 200-UNIQUE-FILE-ID-FILE-STATUS
              logger.info("OPEN SYS109 FAILE : STATUS CODE = {}", new String(methodOut.getUniqueFileIdFileStatus200())); 
//  GOBACK
              setNotLogged(false); // no need to log, it is a normal termination
              programCtx.setProgramEnded(true);
              return methodOut;
          }
      
      return methodOut;
      }
      /**
      * loadAlternateTable 
      *   This method is derived from 
  *   COBOL Paragraph - 1400-LOAD-ALTERNATE-TABLE COBOL Cyclomatic complexity - 9
      * Input  :  

      * - uniqueFileIdFileStatus200      COBOL Name: 200-UNIQUE-FILE-ID-FILE-STATUS
      *
      * Output :  

      * - sys109ProcessSeqnoKey          COBOL Name: SYS109-PROCESS-SEQNO-KEY
      * - sys109UniqueFileIdRec          COBOL Name: SYS109-UNIQUE-FILE-ID-REC
      * - uniqueFileIdFileStatus200      COBOL Name: 200-UNIQUE-FILE-ID-FILE-STATUS
      * - sys109FileIdKey                COBOL Name: SYS109-FILE-ID-KEY
      *
      * @throws CFException
      */
      @Override
      public LoadAlternateTableOutCtx loadAlternateTable(LoadAlternateTableInCtx methodIn) throws Exception {
Mc155Ctx programCtx = methodIn.getMc155Ctx();
LoadAlternateTableOutCtx methodOut = methodIn.getLoadAlternateTableOutCtx();
//  MOVE LOW-VALUES TO SYS109-PROCESS-SEQNO-KEY
          methodOut.setSys109ProcessSeqnoKey(CONSTANTS.LOW_VALUE_1253885741);
//  START SYS109-UNIQUE-FILE-ID-FILE KEY IS GREATER THAN SYS109-PROCESS-SEQNO-KEY END-START
          sys109UniqueFileIdFile.seek(methodOut.getSys109UniqueFileIdRec().toCharArray(),CFConstants.CONDITION_GREATER_THAN,sys109UniqueFileIdFile.getKeyInfo().getSys109ProcessSeqnoKey()); 
          methodOut.setUniqueFileIdFileStatus200(sys109UniqueFileIdFile.getStatusString() );
//  IF 88-200-SYS109-STATUS-GOOD
//  ELSE
          if (!(methodIn.isSys109StatusGood88200()) ) { 
//  DISPLAY 'START SYS109 FAILE : STATUS CODE = ' 200-UNIQUE-FILE-ID-FILE-STATUS
              logger.info("START SYS109 FAILE : STATUS CODE = {}", new String(methodOut.getUniqueFileIdFileStatus200())); 
//  GOBACK
              setNotLogged(false); // no need to log, it is a normal termination
              programCtx.setProgramEnded(true);
              return methodOut;
          }
//  PERFORM UNTIL 200-UNIQUE-FILE-ID-FILE-STATUS NOT EQUAL ZEROS
          while ((( allZeros(methodOut.getUniqueFileIdFileStatus200()) ) /*  ==  zeros*/)) {
//  READ SYS109-UNIQUE-FILE-ID-FILE END-READ
              sys109UniqueFileIdFile.readNext();
              methodOut.setUniqueFileIdFileStatus200(sys109UniqueFileIdFile.getStatusString() );
              if (!sys109UniqueFileIdFile.hasEnded()) {
              	methodOut.getSys109UniqueFileIdRec().setString(sys109UniqueFileIdFile.getRecord());
              }
//  EVALUATE TRUE
              if  ( methodIn.isSys109StatusGood88200()  ) { 
//  DISPLAY 'SYS109-UNIQUE-FILE-ID-REC = ' SYS109-UNIQUE-FILE-ID-REC
                  logger.info("SYS109-UNIQUE-FILE-ID-REC = {}", methodOut.getSys109UniqueFileIdRec().toString()); 
              }
              else if  ( methodOut.isSys109EndOfFile88200()  ) { 
                  ;
              }
              else if  ( methodOut.isSys109NoRecord88200()  ) { 
                  ;
              }
              else   { 
//  DISPLAY 'READ  SYS109 FAILE : STATUS CODE = ' 200-UNIQUE-FILE-ID-FILE-STATUS
                  logger.info("READ  SYS109 FAILE : STATUS CODE = {}", new String(methodOut.getUniqueFileIdFileStatus200())); 
//  GOBACK
                  setNotLogged(false); // no need to log, it is a normal termination
                  programCtx.setProgramEnded(true);
                  return methodOut;
              }
          }
      
      return methodOut;
      }
      /**
      * closeSys109 
      *   This method is derived from 
  *   COBOL Paragraph - 1500-CLOSE-SYS109 COBOL Cyclomatic complexity - 3
      * Input  :  

      * - uniqueFileIdFileStatus200      COBOL Name: 200-UNIQUE-FILE-ID-FILE-STATUS
      *
      * Output : None 

      * @throws CFException
      */
      @Override
      public CloseSys109OutCtx closeSys109(CloseSys109InCtx methodIn) throws Exception {
Mc155Ctx programCtx = methodIn.getMc155Ctx();
CloseSys109OutCtx methodOut = methodIn.getCloseSys109OutCtx();
//  CLOSE SYS109-UNIQUE-FILE-ID-FILE
          sys109UniqueFileIdFile.close(); 
          methodOut.setUniqueFileIdFileStatus200(sys109UniqueFileIdFile.getStatusString() );
//  IF 88-200-SYS109-STATUS-GOOD
//  ELSE
          if (!(methodIn.isSys109StatusGood88200()) ) { 
//  DISPLAY 'CLOSE SYS109 FAILE : STATUS CODE = ' 200-UNIQUE-FILE-ID-FILE-STATUS
              logger.info("CLOSE SYS109 FAILE : STATUS CODE = {}", new String(methodOut.getUniqueFileIdFileStatus200())); 
//  GOBACK
              setNotLogged(false); // no need to log, it is a normal termination
              programCtx.setProgramEnded(true);
              return methodOut;
          }
      
      return methodOut;
      }
  
  
  
  
  
  
  
  
  }
