#
#Common db properties
pring.datasource.initialization-mode=embedded
pring.jpa.hibernate.ddl-auto=update
pring.jdbc.template.fetch-size=1000
pring.datasource.maximum-pool-size=1
#
#VSAM specific db properties (h2)
spring.cf.db.enabled=true
spring.cf.db.jdbc-url=jdbc:h2:file:./cf-vsam-db;DEFRAG_ALWAYS=true;
spring.cf.db.driverClassName=org.h2.Driver
spring.cf.db.username=sa
spring.cf.db.password=
#spring.cf.db.fetch-size=1000
#uncomment below property to disable in-memory load of VSAM
#cf.vsam.load.inmemory=false
#end of h2
#
