#STEP:QSAM2VSAM| PGM:SORT| DD:SORTIN
SortvsamQsam2vsamSortIn=CLOUDFRM.IDCAMS.MONITOR.INPUT
SortvsamQsam2vsamSortIn.DISP=SHR,KEEP,KEEP
SortvsamQsam2vsamSortInRecordType=FB
SortvsamQsam2vsamSortInRecordLen=281
#STEP:QSAM2VSAM| PGM:SORT| DD:SORTOUT
SortvsamQsam2vsamSortOut=CLOUDFRM_IDCAMS_MONITOR
SortvsamQsam2vsamSortOut.DISP=OLD,KEEP,KEEP
SortvsamQsam2vsamSortOutRecordType=VSAM
SortvsamQsam2vsamSortOutRecordLen=281
#STEP:VSAM2QSAM| PGM:SORT| DD:SORTIN
SortvsamVsam2qsamSortIn=CLOUDFRM_IDCAMS_MONITOR
SortvsamVsam2qsamSortIn.DISP=OLD,KEEP,KEEP
SortvsamVsam2qsamSortInRecordType=VSAM
SortvsamVsam2qsamSortInRecordLen=281
#STEP:VSAM2QSAM| PGM:SORT| DD:SORTOUT
SortvsamVsam2qsamSortOut=CLOUDFRM.SORT.MONITOR.OUTPUT
SortvsamVsam2qsamSortOut.DISP=DISP=(NEW,KEEP,KEEP
SortvsamVsam2qsamSortOutRecordType=FB
SortvsamVsam2qsamSortOutRecordLen=281
#
#STEP:IDCAMSOUT| PGM:IDCAMS| DD:INDD
IDCAMSOUT.IDCAMS.Indd=CLOUDFRM_IDCAMS_MONITOR
#
#
#STEP:IDCAMSOUT| PGM:IDCAMS| DD:OUTDD
IDCAMSOUT.IDCAMS.Outdd=CLOUDFRM.IDCAMS.MONITOR.OUTPUT
IDCAMSOUT.IDCAMS.Outdd.DISP=DISP=(NEW,KEEP,KEEP
IDCAMSOUT.IDCAMS.Outdd.RecordType=FB
IDCAMSOUT.IDCAMS.Outdd.RecordLen=281
#
