#
#STEP:P050_01| PGM:ICETOOL| DD:SORTIN
Ice003P050_01SortIn=Y900.P.TM.WRK.EXTRACT(+0)
Ice003P050_01SortIn.DISP=SHR,KEEP,KEEP
Ice003P050_01SortInRecordType=VB
Ice003P050_01SortInRecordLen=4000
#
#
#STEP:P050_01| PGM:ICETOOL| DD:SORTIN2
Ice003P050_01SortOut=Y900.P.TM.WRK.SORT2(+1)
Ice003P050_01SortOut.DISP=NEW,CATLG,DELETE
Ice003P050_01SortOutRecordType=VB
Ice003P050_01SortOutRecordLen=4000
#
#
#STEP:P050_02| PGM:ICETOOL| DD:SORTIN2
Ice003P050_02SortIn=Y900.P.TM.WRK.SORT2(+1)
Ice003P050_02SortIn.DISP=SHR,CATLG,DELETE
Ice003P050_02SortInRecordType=VB
Ice003P050_02SortInRecordLen=4000
#
#
#STEP:P050_02| PGM:ICETOOL| DD:SORTOUT
Ice003P050_02SortOut=Y900.P.TM.WRK.PBALSRT(+1)
Ice003P050_02SortOut.DISP=NEW,CATLG,DELETE
Ice003P050_02SortOutRecordType=VB
Ice003P050_02SortOutRecordLen=4000
#
