
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
timeZoneId=Etc/GMT
IP661020.ddname.SYS003=IpmFile
IP661020.IpmFile=QA.QA000139.SYS003
IP661020.IpmFileCharSet=cp1047
IP661020.IpmFileCRLFflag=no
IP650010.ddname.SYS007=MC_VSAM_KSDS
#Common db properties
spring.datasource.initialization-mode=embedded
spring.jpa.hibernate.ddl-auto=update
spring.jdbc.template.fetch-size=1000
#spring.datasource.autocommit=false
#Vsam specific db properties (h2)
spring.cf.db.enabled=true
spring.cf.db.jdbc-url=jdbc:h2:file:./cf-139-db;DEFRAG_ALWAYS=true;
spring.cf.db.driverClassName=org.h2.Driver
spring.cf.db.username=sa
spring.cf.db.password=
#spring.cf.fetch-size=500
#end of h2
