  package com.cloudframe.app.process.impl;
  /* Java code generated by CloudFrame on 2025-04-24 at 16:39. */
  
  import com.cloudframe.app.wm001.Wm001Ctx.*;
  import com.cloudframe.app.wm001.Wm001Ctx;
  import com.cloudframe.app.process.Wm001;
  import com.cloudframe.app.process.BaseProcess;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.dto.GlobalExecutorCtx;
  import com.cloudframe.app.process.Wm002;
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.beans.factory.annotation.Qualifier;
  import com.cloudframe.app.process.*;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.wm001.dto.*;
  import com.cloudframe.app.wm001.dto.Hdr;
  import com.cloudframe.app.wm001.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("wm001")
  
  public class Wm001Impl extends CommonProcess implements Wm001 {
  
  Logger logger = LoggerFactory.getLogger(Wm001Impl.class);
  
  
  
  
  @Autowired 
  @Qualifier("wm002")
  Wm002 wm002;
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      public int process(Wm001Ctx programCtx) throws Exception {
       try {
       setCodePage("1047");
            // Reset program ended flag
           programCtx.setProgramEnded(false);
          ;
//  PERFORM 000-START-PGM
          startPgm(programCtx.getStartPgmInCtx());/*000-START-PGM*/
          if (programCtx.isProgramEnded()) {
              return programCtx.getRc();
          }
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
       return programCtx.getRc(); // Exit with return code
      // end of process method
      }
      /**
      * startPgm 
      *   This method is derived from 
  *   COBOL Paragraph - 000-START-PGM COBOL Cyclomatic complexity - 4
      * Input  :  

      * - hdrCnt                         COBOL Name: WS-HDR-CNT
      * - hdr                            COBOL Name: WS-HDR
      *
      * Output :  

      * - hdrL2                          COBOL Name: WS-HDR-L2
      * - hdrL3                          COBOL Name: WS-HDR-L3
      * - hdrCnt                         COBOL Name: WS-HDR-CNT
      * - rc                             COBOL Name: RETURN-CODE
      *
      * @throws CFException
      */
      @Override
      public StartPgmOutCtx startPgm(StartPgmInCtx methodIn) throws Exception {
Wm001Ctx programCtx = methodIn.getWm001Ctx();
StartPgmOutCtx methodOut = methodIn.getStartPgmOutCtx();
//  MOVE ALL '-' TO WS-HDR-L2 WS-HDR-L3
          methodOut.setHdrL2(CONSTANTS.LITERAL_969266263);
          methodOut.setHdrL3(CONSTANTS.LITERAL_969266263);
//  PERFORM VARYING WS-HDR-CNT FROM 1 BY 1 UNTIL WS-HDR-CNT > 10
          for (methodOut.setHdrCnt(1); (	( methodOut.getHdrCnt() <= 10 )) ; methodOut.setHdrCnt(methodOut.getHdrCnt() + 1) ) {
//  DISPLAY WS-HDR
              logger.info(methodIn.getHdr().toString()); 
//  CALL WS-CALL-PROG
              // CALL WS-CALL-PROG
              	programCtx.setRc( wm002.process(programCtx.getGlobalCtx().getContext("WM002")));
//  DISPLAY ' '
              logger.info(" "); 
          }
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          programCtx.setProgramEnded(true);
          return methodOut;
      
      }
  
  
  
  
  
  
  
  
  }
