<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="WvExposureResultsTable" cobol:name="WV-EXPOSURE-RESULTS-TABLE" cobol:offset="0" cobol:length="16635008" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="WvAccounts" maxOccurs="15000" cobol:name="WV-ACCOUNTS" cobol:offset="0" cobol:length="1109" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="WvAcctIndex" type="xs:short" maxOccurs="1"  cobol:name="WV-ACCT-INDEX" cobol:offset="16635000" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="WvWeightIndex" type="xs:int" maxOccurs="1"  cobol:name="WV-WEIGHT-INDEX" cobol:offset="16635002" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="WvMonthIndex" type="xs:short" maxOccurs="1"  cobol:name="WV-MONTH-INDEX" cobol:offset="16635006" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
