#STEP:SORT001| PGM:SORT| DD:SORTJNF1
TranSort001SortIn[0]=CLOUDFRM.MC.MDS.BATCH.SORT.IN0011
TranSort001SortIn[0].DISP=SHR,KEEP,KEEP
TranSort001SortIn0RecordType=FB
TranSort001SortIn0RecordLen=102
#STEP:SORT001| PGM:SORT| DD:SORTJNF2
TranSort001SortIn[1]=CLOUDFRM.MC.MDS.BATCH.SORT.IN0012
TranSort001SortIn[1].DISP=SHR,KEEP,KEEP
TranSort001SortIn1RecordType=FB
TranSort001SortIn1RecordLen=95
#STEP:SORT001| PGM:SORT| DD:SORTOUT
TranSort001SortOut=CLOUDFRM.MC.MDS.BATCH.SORT.OUT01
TranSort001SortOut.DISP=NEW,KEEP,KEEP
TranSort001SortOutRecordType=FB
TranSort001SortOutRecordLen=136
#STEP:SORT002| PGM:SORT| DD:SORTIN
TranSort002SortIn=CLOUDFRM.MC.MDS.BATCH.SORT.IN02
TranSort002SortIn.DISP=SHR,KEEP,KEEP
TranSort002SortInRecordType=FB
TranSort002SortInRecordLen=50
#STEP:SORT002| PGM:SORT| DD:SORTOUT
TranSort002SortOut=CLOUDFRM.MC.MDS.BATCH.SORT.OUT02
TranSort002SortOut.DISP=NEW,KEEP,KEEP
TranSort002SortOutRecordType=FB
TranSort002SortOutRecordLen=50
#STEP:SORT003| PGM:SORT| DD:SORTIN
TranSort003SortIn=CLOUDFRM.MC.MDS.BATCH.SORT.IN02
TranSort003SortIn.DISP=SHR,KEEP,KEEP
TranSort003SortInRecordType=FB
TranSort003SortInRecordLen=50
#STEP:SORT003| PGM:SORT| DD:SORTOUT
TranSort003SortOut=CLOUDFRM.MC.MDS.BATCH.SORT.OUT03
TranSort003SortOut.DISP=NEW,KEEP,KEEP
TranSort003SortOutRecordType=FB
TranSort003SortOutRecordLen=50
#STEP:SORT004| PGM:SORT| DD:SORTIN
TranSort004SortIn=CLOUDFRM.MC.MDS.BATCH.SORT.IN02
TranSort004SortIn.DISP=SHR,KEEP,KEEP
TranSort004SortInRecordType=FB
TranSort004SortInRecordLen=50
#STEP:SORT004| PGM:SORT| DD:SORTOUT
TranSort004SortOut=CLOUDFRM.MC.MDS.BATCH.SORT.OUT04
TranSort004SortOut.DISP=NEW,KEEP,KEEP
TranSort004SortOutRecordType=FB
TranSort004SortOutRecordLen=50
#STEP:SORT005| PGM:SORT| DD:SORTIN
TranSort005SortIn=CLOUDFRM.MC.MDS.BATCH.SORT.IN02
TranSort005SortIn.DISP=SHR,KEEP,KEEP
TranSort005SortInRecordType=FB
TranSort005SortInRecordLen=50
#STEP:SORT005| PGM:SORT| DD:SORTOUT
TranSort005SortOut=CLOUDFRM.MC.MDS.BATCH.SORT.OUT05
TranSort005SortOut.DISP=NEW,KEEP,KEEP
TranSort005SortOutRecordType=FB
TranSort005SortOutRecordLen=50
#STEP:SORT006| PGM:SORT| DD:SORTIN
TranSort006SortIn=CLOUDFRM.MC.MDS.BATCH.SORT.IN02
TranSort006SortIn.DISP=SHR,KEEP,KEEP
TranSort006SortInRecordType=FB
TranSort006SortInRecordLen=50
#STEP:SORT006| PGM:SORT| DD:SORTOUT
TranSort006SortOut=CLOUDFRM.MC.MDS.BATCH.SORT.OUT06
TranSort006SortOut.DISP=NEW,KEEP,KEEP
TranSort006SortOutRecordType=FB
TranSort006SortOutRecordLen=50
#STEP:SORT007| PGM:SORT| DD:SORTIN
TranSort007SortIn=CLOUDFRM.MC.MDS.BATCH.SORT.IN02
TranSort007SortIn.DISP=SHR,KEEP,KEEP
TranSort007SortInRecordType=FB
TranSort007SortInRecordLen=50
#STEP:SORT007| PGM:SORT| DD:SORTOUT
TranSort007SortOut=CLOUDFRM.MC.MDS.BATCH.SORT.OUT07
TranSort007SortOut.DISP=NEW,KEEP,KEEP
TranSort007SortOutRecordType=FB
TranSort007SortOutRecordLen=50
