<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Work" cobol:name="work" cobol:offset="0" cobol:length="158" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="AaW1Comp94" type="xs:int" maxOccurs="1"  cobol:name="AA-W1-COMP-9-4" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="AaW1CompS94" type="xs:short" maxOccurs="1"  cobol:name="AA-W1-COMP-S9-4" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="AaW1Comp98" type="xs:long" maxOccurs="1"  cobol:name="AA-W1-COMP-9-8" cobol:offset="0" cobol:length="4" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="AaW1CompS98" type="xs:int" maxOccurs="1"  cobol:name="AA-W1-COMP-S9-8" cobol:offset="0" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="AaW1Comp912" type="xs:long" maxOccurs="1"  cobol:name="AA-W1-COMP-9-12" cobol:offset="0" cobol:length="8" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="AaW1CompS912" type="xs:long" maxOccurs="1"  cobol:name="AA-W1-COMP-S9-12" cobol:offset="0" cobol:length="8" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="AaW1Bin94" type="xs:int" maxOccurs="1"  cobol:name="AA-W1-BIN-9-4" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="AaW1BinS94" type="xs:short" maxOccurs="1"  cobol:name="AA-W1-BIN-S9-4" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="AaW1Bin98" type="xs:long" maxOccurs="1"  cobol:name="AA-W1-BIN-9-8" cobol:offset="0" cobol:length="4" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="AaW1BinS98" type="xs:int" maxOccurs="1"  cobol:name="AA-W1-BIN-S9-8" cobol:offset="0" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="AaW1Bin912" type="xs:long" maxOccurs="1"  cobol:name="AA-W1-BIN-9-12" cobol:offset="0" cobol:length="8" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="AaW1BinS912" type="xs:long" maxOccurs="1"  cobol:name="AA-W1-BIN-S9-12" cobol:offset="0" cobol:length="8" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="AaW1Edit94" maxOccurs="1"  cobol:name="AA-W1-EDIT-9-4" cobol:offset="0" cobol:length="4" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Edit94Nb" maxOccurs="1"  cobol:name="AA-W1-EDIT-9-4-NB" cobol:offset="4" cobol:length="4" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="true" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="AaW1Disp94" type="xs:int" maxOccurs="1"  cobol:name="AA-W1-DISP-9-4" cobol:offset="8" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
         <xs:element name="AaW1DispS94" type="xs:short" maxOccurs="1"  cobol:name="AA-W1-DISP-S9-4" cobol:offset="12" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
         <xs:element name="AaW1Disp98" type="xs:long" maxOccurs="1"  cobol:name="AA-W1-DISP-9-8" cobol:offset="16" cobol:length="8" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
         <xs:element name="AaW1DispS98" type="xs:int" maxOccurs="1"  cobol:name="AA-W1-DISP-S9-8" cobol:offset="24" cobol:length="8" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
         <xs:element name="AaW1Disp912" type="xs:long" maxOccurs="1"  cobol:name="AA-W1-DISP-9-12" cobol:offset="32" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T"/>
         <xs:element name="AaW1DispS912" type="xs:long" maxOccurs="1"  cobol:name="AA-W1-DISP-S9-12" cobol:offset="44" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T"/>
         <xs:element name="AaW1Comp394" type="xs:int" maxOccurs="1"  cobol:name="AA-W1-COMP-3-9-4" cobol:offset="56" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
         <xs:element name="AaW1Comp3S94" type="xs:short" maxOccurs="1"  cobol:name="AA-W1-COMP-3-S9-4" cobol:offset="59" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
         <xs:element name="AaW1Comp398" type="xs:long" maxOccurs="1"  cobol:name="AA-W1-COMP-3-9-8" cobol:offset="62" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
         <xs:element name="AaW1Comp3S98" type="xs:int" maxOccurs="1"  cobol:name="AA-W1-COMP-3-S9-8" cobol:offset="67" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
         <xs:element name="AaW1Comp3912" type="xs:long" maxOccurs="1"  cobol:name="AA-W1-COMP-3-9-12" cobol:offset="72" cobol:length="7" cobol:datatype="Packed-Dec" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T"/>
         <xs:element name="AaW1Comp3S912" type="xs:long" maxOccurs="1"  cobol:name="AA-W1-COMP-3-S9-12" cobol:offset="79" cobol:length="7" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T"/>
    <xs:element name="AaW1Comp3944" maxOccurs="1"  cobol:name="AA-W1-COMP-3-9-44" cobol:offset="86" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="4" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Comp3S944" maxOccurs="1"  cobol:name="AA-W1-COMP-3-S9-44" cobol:offset="89" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="4" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Comp3984" maxOccurs="1"  cobol:name="AA-W1-COMP-3-9-84" cobol:offset="92" cobol:length="4" cobol:datatype="Packed-Dec" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="6" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Comp3S984" maxOccurs="1"  cobol:name="AA-W1-COMP-3-S9-84" cobol:offset="96" cobol:length="4" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="6" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Comp39124" maxOccurs="1"  cobol:name="AA-W1-COMP-3-9-124" cobol:offset="100" cobol:length="7" cobol:datatype="Packed-Dec" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Comp3S9124" maxOccurs="1"  cobol:name="AA-W1-COMP-3-S9-124" cobol:offset="107" cobol:length="7" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Comp944" maxOccurs="1"  cobol:name="AA-W1-COMP-9-44" cobol:offset="114" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="4" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1CompS944" maxOccurs="1"  cobol:name="AA-W1-COMP-S9-44" cobol:offset="114" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="4" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Comp984" maxOccurs="1"  cobol:name="AA-W1-COMP-9-84" cobol:offset="114" cobol:length="4" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="6" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1CompS984" maxOccurs="1"  cobol:name="AA-W1-COMP-S9-84" cobol:offset="114" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="6" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Comp9124" maxOccurs="1"  cobol:name="AA-W1-COMP-9-124" cobol:offset="114" cobol:length="8" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1CompS9124" maxOccurs="1"  cobol:name="AA-W1-COMP-S9-124" cobol:offset="114" cobol:length="8" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Disp944" maxOccurs="1"  cobol:name="AA-W1-DISP-9-44" cobol:offset="114" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="4" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1DispS944" maxOccurs="1"  cobol:name="AA-W1-DISP-S9-44" cobol:offset="118" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="4" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Disp984" maxOccurs="1"  cobol:name="AA-W1-DISP-9-84" cobol:offset="122" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="6" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1DispS984" maxOccurs="1"  cobol:name="AA-W1-DISP-S9-84" cobol:offset="128" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="6" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Disp9124" maxOccurs="1"  cobol:name="AA-W1-DISP-9-124" cobol:offset="134" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1DispS9124" maxOccurs="1"  cobol:name="AA-W1-DISP-S9-124" cobol:offset="146" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Bin944" maxOccurs="1"  cobol:name="AA-W1-BIN-9-44" cobol:offset="158" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="4" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1BinS944" maxOccurs="1"  cobol:name="AA-W1-BIN-S9-44" cobol:offset="158" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="4" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Bin984" maxOccurs="1"  cobol:name="AA-W1-BIN-9-84" cobol:offset="158" cobol:length="4" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="6" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1BinS984" maxOccurs="1"  cobol:name="AA-W1-BIN-S9-84" cobol:offset="158" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="6" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1Bin9124" maxOccurs="1"  cobol:name="AA-W1-BIN-9-124" cobol:offset="158" cobol:length="8" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1BinS9124" maxOccurs="1"  cobol:name="AA-W1-BIN-S9-124" cobol:offset="158" cobol:length="8" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1X1" maxOccurs="1"  cobol:name="AA-W1-X1" cobol:offset="158" cobol:length="12" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="12" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1X2" maxOccurs="1"  cobol:name="AA-W1-X2" cobol:offset="158" cobol:length="12" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="true" >
                  <xs:length value="12" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1X3" maxOccurs="1"  cobol:name="AA-W1-X3" cobol:offset="158" cobol:length="12" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="true" >
                  <xs:length value="12" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1X4" maxOccurs="1"  cobol:name="AA-W1-X4" cobol:offset="158" cobol:length="12" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="12" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AaW1X5" maxOccurs="1"  cobol:name="AA-W1-X5" cobol:offset="158" cobol:length="12" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="12" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
