<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="SmmRec" cobol:name="SMM-REC" cobol:offset="0" cobol:length="822" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="SmmKey" maxOccurs="1" cobol:name="SMM-KEY" cobol:offset="0" cobol:length="100" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="SmmSsDdrKey" maxOccurs="1"  cobol:name="SMM-SS-DDR-KEY" cobol:offset="100" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmMatchStatus" maxOccurs="1"  cobol:name="SMM-MATCH-STATUS" cobol:offset="110" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmClassification" maxOccurs="1"  cobol:name="SMM-CLASSIFICATION" cobol:offset="112" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmField2" maxOccurs="1"  cobol:name="SMM-FIELD2" cobol:offset="114" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmField4" maxOccurs="1"  cobol:name="SMM-FIELD4" cobol:offset="144" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmField5" maxOccurs="1"  cobol:name="SMM-FIELD5" cobol:offset="174" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmField6" maxOccurs="1"  cobol:name="SMM-FIELD6" cobol:offset="204" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmField7" maxOccurs="1"  cobol:name="SMM-FIELD7" cobol:offset="234" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmField8" maxOccurs="1"  cobol:name="SMM-FIELD8" cobol:offset="264" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmField9" maxOccurs="1"  cobol:name="SMM-FIELD9" cobol:offset="294" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmField10" maxOccurs="1"  cobol:name="SMM-FIELD10" cobol:offset="324" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmField11" maxOccurs="1"  cobol:name="SMM-FIELD11" cobol:offset="354" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmField12" maxOccurs="1"  cobol:name="SMM-FIELD12" cobol:offset="384" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmField13" maxOccurs="1"  cobol:name="SMM-FIELD13" cobol:offset="414" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmField14" maxOccurs="1"  cobol:name="SMM-FIELD14" cobol:offset="444" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmField15" maxOccurs="1"  cobol:name="SMM-FIELD15" cobol:offset="474" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmBranch" maxOccurs="1"  cobol:name="SMM-BRANCH" cobol:offset="504" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmTeller" maxOccurs="1"  cobol:name="SMM-TELLER" cobol:offset="514" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmHash" maxOccurs="1"  cobol:name="SMM-HASH" cobol:offset="524" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmType" maxOccurs="1"  cobol:name="SMM-TYPE" cobol:offset="554" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmAppTypePsetNum" maxOccurs="1"  cobol:name="SMM-APP-TYPE-PSET-NUM" cobol:offset="564" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmPostingDate" maxOccurs="1"  cobol:name="SMM-POSTING-DATE" cobol:offset="567" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmTransTime" maxOccurs="1"  cobol:name="SMM-TRANS-TIME" cobol:offset="577" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmRefText1" maxOccurs="1"  cobol:name="SMM-REF-TEXT1" cobol:offset="585" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmRefText2" maxOccurs="1"  cobol:name="SMM-REF-TEXT2" cobol:offset="615" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmRefText3" maxOccurs="1"  cobol:name="SMM-REF-TEXT3" cobol:offset="645" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmRefText4" maxOccurs="1"  cobol:name="SMM-REF-TEXT4" cobol:offset="675" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmRefText5" maxOccurs="1"  cobol:name="SMM-REF-TEXT5" cobol:offset="705" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmRefNum1" maxOccurs="1"  cobol:name="SMM-REF-NUM1" cobol:offset="735" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmRefNum2" maxOccurs="1"  cobol:name="SMM-REF-NUM2" cobol:offset="765" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmSubclass" maxOccurs="1"  cobol:name="SMM-SUBCLASS" cobol:offset="795" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmFlags" maxOccurs="1"  cobol:name="SMM-FLAGS" cobol:offset="805" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmCycleNo" maxOccurs="1"  cobol:name="SMM-CYCLE-NO" cobol:offset="810" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmCycleDate" maxOccurs="1"  cobol:name="SMM-CYCLE-DATE" cobol:offset="811" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SmmEnd" maxOccurs="1"  cobol:name="SMM-END" cobol:offset="819" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
