timeZoneId=Etc/GMT
# Program USBAEEXT | DD : TMFILEIN | RecordFormat : VariableLength | MaxRecordLength : 3996
USBAEEXT.ddname.TMFILEIN=TmFile
USBAEEXT.TmFile=TmFile
USBAEEXT.TmFileCharSet=cp1047
USBAEEXT.TmFileCRLFflag=no
# Program USBAEEXT | DD : ADJTBL | RecordFormat : FixedLength | RecordLength : 80
USBAEEXT.ddname.ADJTBL=AdjTable
USBAEEXT.AdjTable=AdjTable
USBAEEXT.AdjTableCharSet=cp1047
USBAEEXT.AdjTableCRLFflag=no
# Program USBAEEXT | DD : AEOUTPUT | RecordFormat : FixedLength | RecordLength : 525
USBAEEXT.ddname.AEOUTPUT=AeOutputFile
USBAEEXT.AeOutputFile=AeOutputFile
USBAEEXT.AeOutputFileCharSet=cp1047
USBAEEXT.AeOutputFileCRLFflag=no
# 
# End of USBAEEXT
