# Program  : VSAMMON1 | DD : SYSIN | RecordFormat : FixedLength | RecordLength : 80
VSAMMON1.Scanner=SYSIN.bin
VSAMMON1.ScannerCharSet=cp1047
VSAMMON1.ScannerCRLFflag=no
# Program VSAMMON1 | DD : MONITOR | VSAM KSDS
VSAMMON1.ddname.MONITOR=Monitor
# Program VSAMMON1 | DD : REPOUT | RecordFormat : FixedLength | RecordLength : 300
VSAMMON1.ddname.REPOUT=Repout
VSAMMON1.Repout=Repout
VSAMMON1.RepoutCharSet=cp1047
VSAMMON1.RepoutCRLFflag=no
# 
# End of VSAMMON1
