# Program ASAPRNT4 | DD : REPOUT | RecordFormat : FixedLength | RecordLength : 287
ASAPRNT4.ddname.REPOUT=Repout
ASAPRNT4.Repout=Repout
ASAPRNT4.RepoutCharSet=cp1047
ASAPRNT4.RepoutCRLFflag=no
# 
# End of ASAPRNT4
