<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Work" cobol:name="work" cobol:offset="0" cobol:length="16" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="LitAbrir" maxOccurs="1"  cobol:name="LIT-ABRIR" cobol:offset="0" cobol:length="5" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="LitWrite" maxOccurs="1"  cobol:name="LIT-WRITE" cobol:offset="0" cobol:length="5" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="LitCerrar" maxOccurs="1"  cobol:name="LIT-CERRAR" cobol:offset="0" cobol:length="6" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="LitGe0001w" maxOccurs="1"  cobol:name="LIT-GE0001W" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="LitPrograma" maxOccurs="1"  cobol:name="LIT-PROGRAMA" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Acceso" maxOccurs="1"  cobol:name="WS-ACCESO" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Fichero" maxOccurs="1"  cobol:name="WS-FICHERO" cobol:offset="0" cobol:length="7" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FileStatus" maxOccurs="1"  cobol:name="FILE-STATUS" cobol:offset="0" cobol:length="2" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FsGe0001w" maxOccurs="1"  cobol:name="FS-GE0001W" cobol:offset="0" cobol:length="2" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sqlcode_Ws" maxOccurs="1"  cobol:name="WS-SQLCODE" cobol:offset="0" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="Long.MAX_VALUE" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 db2NotFound VALUE [[100]].
                        88 db2StatusOk VALUE [[0ALL]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:int">
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="WkErrorDb2" maxOccurs="1"  cobol:name="WK-ERROR-DB2" cobol:offset="0" cobol:length="2" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SwFinCurGe18" maxOccurs="1"  cobol:name="SW-FIN-CUR-GE18" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 swFinCurGe18Si VALUE [["S"]].
                        88 swFinCurGe18No VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="SwInfoSalida" maxOccurs="1"  cobol:name="SW-INFO-SALIDA" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 swSiInfoSalida VALUE [["S"]].
                        88 swNoInfoSalida VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="SwFinCursorRowset" maxOccurs="1"  cobol:name="SW-FIN-CURSOR-ROWSET" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 swSiFinCurRowset VALUE [["S"]].
                        88 swNoFinCurRowset VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
         <xs:element name="PosRow" type="xs:int" maxOccurs="1"  cobol:name="POS-ROW" cobol:offset="0" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="RegsRecupRowset" type="xs:int" maxOccurs="1"  cobol:name="REGS-RECUP-ROWSET" cobol:offset="0" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="AbendLinea1" maxOccurs="1"  cobol:name="ABEND-LINEA1" cobol:offset="0" cobol:length="80" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="80" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendLinea2" maxOccurs="1"  cobol:name="ABEND-LINEA2" cobol:offset="0" cobol:length="80" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="80" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendLinea3" maxOccurs="1"  cobol:name="ABEND-LINEA3" cobol:offset="0" cobol:length="80" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="80" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendLinea5" maxOccurs="1"  cobol:name="ABEND-LINEA5" cobol:offset="0" cobol:length="80" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="80" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendLinea8" maxOccurs="1"  cobol:name="ABEND-LINEA8" cobol:offset="0" cobol:length="80" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="80" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendLinea9" maxOccurs="1"  cobol:name="ABEND-LINEA9" cobol:offset="0" cobol:length="80" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="80" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendLinea10" maxOccurs="1"  cobol:name="ABEND-LINEA10" cobol:offset="0" cobol:length="80" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="80" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendLinea11" maxOccurs="1"  cobol:name="ABEND-LINEA11" cobol:offset="0" cobol:length="80" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="80" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ge1801Codentid" maxOccurs="1"  cobol:name="GE1801-CODENTID" cobol:offset="0" cobol:length="2" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ge1801Tipproduct" maxOccurs="1"  cobol:name="GE1801-TIPPRODUCT" cobol:offset="0" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ge1801Codcontrat" type="xs:long" maxOccurs="1"  cobol:name="GE1801-CODCONTRAT" cobol:offset="0" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Ge1801Ofigestora" type="xs:short" maxOccurs="1"  cobol:name="GE1801-OFIGESTORA" cobol:offset="8" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
    <xs:element name="Ge1801Idepsig" maxOccurs="1"  cobol:name="GE1801-IDEPSIG" cobol:offset="11" cobol:length="12" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="12" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ge1801Numpersona" type="xs:int" maxOccurs="1"  cobol:name="GE1801-NUMPERSONA" cobol:offset="11" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ge1801Numcartera" type="xs:int" maxOccurs="1"  cobol:name="GE1801-NUMCARTERA" cobol:offset="11" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
    <xs:element name="Ge1801Codcartera" maxOccurs="1"  cobol:name="GE1801-CODCARTERA" cobol:offset="16" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ge1801Fechaalta" maxOccurs="1"  cobol:name="GE1801-FECHAALTA" cobol:offset="16" cobol:length="10" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ge1801Fechabaja" maxOccurs="1"  cobol:name="GE1801-FECHABAJA" cobol:offset="16" cobol:length="10" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ge1801Codnodo" maxOccurs="1"  cobol:name="GE1801-CODNODO" cobol:offset="16" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ge1801Resambito" maxOccurs="1"  cobol:name="GE1801-RESAMBITO" cobol:offset="16" cobol:length="12" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="12" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ge1801Numresamb" type="xs:int" maxOccurs="1"  cobol:name="GE1801-NUMRESAMB" cobol:offset="16" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ge1801Numpresamb" type="xs:int" maxOccurs="1"  cobol:name="GE1801-NUMPRESAMB" cobol:offset="16" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="Ge1801Cengescapt" maxOccurs="1"  cobol:name="GE1801-CENGESCAPT" cobol:offset="16" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ge1801Numgescap" type="xs:int" maxOccurs="1"  cobol:name="GE1801-NUMGESCAP" cobol:offset="16" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ge1801Numpgescap" type="xs:int" maxOccurs="1"  cobol:name="GE1801-NUMPGESCAP" cobol:offset="16" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ge1801Numpesprie" type="xs:int" maxOccurs="1"  cobol:name="GE1801-NUMPESPRIE" cobol:offset="16" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="Ge1801Codcarrie" maxOccurs="1"  cobol:name="GE1801-CODCARRIE" cobol:offset="16" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ge1801Fecciecurso" maxOccurs="1"  cobol:name="GE1801-FECCIECURSO" cobol:offset="16" cobol:length="10" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Dsnnrows" type="xs:int" maxOccurs="1"  cobol:name="DSNNROWS" cobol:offset="16" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
