#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
#logging.level.com.cloudframe=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
     
Icet050MergeSortIn[0]=CLOUDFRM.MC.SORT.IN0201
Icet050MergeSortIn[0].DISP=SHR,KEEP,KEEP
Icet050MergeSortIn[1]=CLOUDFRM.MC.SORT.IN0202
Icet050MergeSortIn[1].DISP=SHR,KEEP,KEEP
Icet050MergeSortInRecordType=FB
Icet050MergeSortInRecordLen=133
#End of [INABC, INDEF] DD, MERGE step for ICETOOL

#Icet050MergeSortOut[0]=CLOUDFRM.MC.SORT.OUT050A
#Icet050MergeSortOut[1]:CLOUDFRM.MC.SORT.OUT050B
#Icet050MergeSortOutRecordType=FB
#Icet050MergeSortOutRecordLen=133
#End of [OUTACE, OUTBDF] DD, MERGE step for ICETOOL