#
#STEP:MERGE| PGM:ICETOOL| DD:INABC, INDEF
Icet050MergeSortIn[0]=CLOUDFRM.MC.SORT.IN0201
Icet050MergeSortIn[0].DISP=SHR,KEEP,KEEP
Icet050MergeSortIn[1]=CLOUDFRM.MC.SORT.IN0202
Icet050MergeSortIn[1].DISP=SHR,KEEP,KEEP
Icet050MergeSortInRecordType=FB
Icet050MergeSortInRecordLen=<recordLen>
#
