#STEP:P010| PGM:IEFBR14| DD:SYSUT2
P010.IEFBR14.Sysut2=Y900.P.TM.Y90DCABR.SORTALL
P010.IEFBR14.Sysut2.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:SYSUT3
P010.IEFBR14.Sysut3=Y900.P.TM.Y90DCABR.SORTAK1
P010.IEFBR14.Sysut3.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:SYSUT4
P010.IEFBR14.Sysut4=Y900.P.TM.Y90DCABR.SORTBA1
P010.IEFBR14.Sysut4.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:SYSUT5
P010.IEFBR14.Sysut5=Y900.P.TM.Y90DCABR.SORTBA2
P010.IEFBR14.Sysut5.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:SYSUT6
P010.IEFBR14.Sysut6=Y900.P.TM.Y90DCABR.SORTCLC
P010.IEFBR14.Sysut6.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:SYSUT7
P010.IEFBR14.Sysut7=Y900.P.TM.Y90DCABR.SBRTSALL
P010.IEFBR14.Sysut7.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:SYSUT8
P010.IEFBR14.Sysut8=Y900.P.TM.Y90DCABR.SUMALL
P010.IEFBR14.Sysut8.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:SYSUT9
P010.IEFBR14.Sysut9=Y900.P.TM.Y90DCABR.SUMWORK
P010.IEFBR14.Sysut9.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:SYSUT10
P010.IEFBR14.Sysut10=Y900.P.TM.Y90DCABR.SORTBA3
P010.IEFBR14.Sysut10.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:SYSUT11
P010.IEFBR14.Sysut11=Y900.P.TM.Y90DCABR.SORTBA4
P010.IEFBR14.Sysut11.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:SYSUT12
P010.IEFBR14.Sysut12=Y900.P.TM.Y90DCABR.SORTITM
P010.IEFBR14.Sysut12.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:SYSUT13
P010.IEFBR14.Sysut13=Y900.P.TM.Y90DCABR.SORTBAW
P010.IEFBR14.Sysut13.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:SYSUT14
P010.IEFBR14.Sysut14=Y900.P.TM.ITEMSUMM.X350
P010.IEFBR14.Sysut14.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:SYSUT15
P010.IEFBR14.Sysut15=Y900.P.TM.ITEMSUMM.TMS
P010.IEFBR14.Sysut15.DISP=MOD,DELETE,DELETE
#
#STEP:P020| PGM:IEBGENER| DD:SYSUT1
P020.IEBGENER.Sysut1=DUMMY
#
#STEP:P020| PGM:IEBGENER| DD:SYSUT2
P020.IEBGENER.Sysut2=Y900.P.TM.Y90DCABR.SORTALL
P020.IEBGENER.Sysut2.DISP=NEW,CATLG,DELETE
P020.IEBGENER.Sysut2.RecordType=FB
P020.IEBGENER.Sysut2.RecordLen=80
#
#STEP:P020| PGM:IEBGENER| DD:SYSUT3
P020.IEBGENER.Sysut3=Y900.P.TM.Y90DCABR.SORTAK1
P020.IEBGENER.Sysut3.DISP=NEW,CATLG,DELETE
P020.IEBGENER.Sysut3.RecordType=FB
P020.IEBGENER.Sysut3.RecordLen=80
#
#STEP:P020| PGM:IEBGENER| DD:SYSUT4
P020.IEBGENER.Sysut4=Y900.P.TM.Y90DCABR.SORTBA1
P020.IEBGENER.Sysut4.DISP=NEW,CATLG,DELETE
P020.IEBGENER.Sysut4.RecordType=FB
P020.IEBGENER.Sysut4.RecordLen=80
#
#STEP:P020| PGM:IEBGENER| DD:SYSUT5
P020.IEBGENER.Sysut5=Y900.P.TM.Y90DCABR.SORTBA2
P020.IEBGENER.Sysut5.DISP=NEW,CATLG,DELETE
P020.IEBGENER.Sysut5.RecordType=FB
P020.IEBGENER.Sysut5.RecordLen=80
#
#STEP:P020| PGM:IEBGENER| DD:SYSUT6
P020.IEBGENER.Sysut6=Y900.P.TM.Y90DCABR.SORTCLC
P020.IEBGENER.Sysut6.DISP=NEW,CATLG,DELETE
P020.IEBGENER.Sysut6.RecordType=FB
P020.IEBGENER.Sysut6.RecordLen=80
#
#STEP:P020| PGM:IEBGENER| DD:SYSUT7
P020.IEBGENER.Sysut7=Y900.P.TM.Y90DCABR.SBRTSALL
P020.IEBGENER.Sysut7.DISP=NEW,CATLG,DELETE
P020.IEBGENER.Sysut7.RecordType=FB
P020.IEBGENER.Sysut7.RecordLen=80
#
#STEP:P020| PGM:IEBGENER| DD:SYSUT8
P020.IEBGENER.Sysut8=Y900.P.TM.Y90DCABR.SUMALL
P020.IEBGENER.Sysut8.DISP=NEW,CATLG,DELETE
P020.IEBGENER.Sysut8.RecordType=FB
P020.IEBGENER.Sysut8.RecordLen=80
#
#STEP:P020| PGM:IEBGENER| DD:SYSUT9
P020.IEBGENER.Sysut9=Y900.P.TM.Y90DCABR.SUMWORK
P020.IEBGENER.Sysut9.DISP=NEW,CATLG,DELETE
P020.IEBGENER.Sysut9.RecordType=FB
P020.IEBGENER.Sysut9.RecordLen=80
#
#STEP:P020| PGM:IEBGENER| DD:SYSUT10
P020.IEBGENER.Sysut10=Y900.P.TM.Y90DCABR.SORTBA3
P020.IEBGENER.Sysut10.DISP=NEW,CATLG,DELETE
P020.IEBGENER.Sysut10.RecordType=FB
P020.IEBGENER.Sysut10.RecordLen=80
#
#STEP:P020| PGM:IEBGENER| DD:SYSUT11
P020.IEBGENER.Sysut11=Y900.P.TM.Y90DCABR.SORTBA4
P020.IEBGENER.Sysut11.DISP=NEW,CATLG,DELETE
P020.IEBGENER.Sysut11.RecordType=FB
P020.IEBGENER.Sysut11.RecordLen=80
#
#STEP:P020| PGM:IEBGENER| DD:SYSUT12
P020.IEBGENER.Sysut12=Y900.P.TM.Y90DCABR.SORTITM
P020.IEBGENER.Sysut12.DISP=NEW,CATLG,DELETE
P020.IEBGENER.Sysut12.RecordType=FB
P020.IEBGENER.Sysut12.RecordLen=80
#
#STEP:P020| PGM:IEBGENER| DD:SYSUT13
P020.IEBGENER.Sysut13=Y900.P.TM.Y90DCABR.SORTBAW
P020.IEBGENER.Sysut13.DISP=NEW,CATLG,DELETE
P020.IEBGENER.Sysut13.RecordType=FB
P020.IEBGENER.Sysut13.RecordLen=80
#
#
#STEP:P030_01| PGM:ICETOOL| DD:FILESIN
Ice002P030_01SortIn=Y900.P.TM.USBTBITM.FILEOUT(+0)
Ice002P030_01SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_01SortIn.RecordType=FB
Ice002P030_01SortIn.RecordLen=80
#
#
#STEP:P030_01| PGM:ICETOOL| DD:FILEAK1
Ice002P030_01SortOut=Y900.P.TM.Y90DCABR.SORTAK1
Ice002P030_01SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_01SortOut.RecordType=FB
Ice002P030_01SortOut.RecordLen=80
#
#
#STEP:P030_02| PGM:ICETOOL| DD:FILESIN
Ice002P030_02SortIn=Y900.P.TM.USBTBITM.FILEOUT(+0)
Ice002P030_02SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_02SortIn.RecordType=FB
Ice002P030_02SortIn.RecordLen=80
#
#
#STEP:P030_02| PGM:ICETOOL| DD:FILECLC
Ice002P030_02SortOut=Y900.P.TM.Y90DCABR.SORTCLC
Ice002P030_02SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_02SortOut.RecordType=FB
Ice002P030_02SortOut.RecordLen=80
#
#
#STEP:P030_03| PGM:ICETOOL| DD:FILESIN
Ice002P030_03SortIn=Y900.P.TM.USBTBITM.FILEOUT(+0)
Ice002P030_03SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_03SortIn.RecordType=FB
Ice002P030_03SortIn.RecordLen=80
#
#
#STEP:P030_03| PGM:ICETOOL| DD:FILEBA1
Ice002P030_03SortOut=Y900.P.TM.Y90DCABR.SORTBA1
Ice002P030_03SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_03SortOut.RecordType=FB
Ice002P030_03SortOut.RecordLen=80
#
#
#STEP:P030_04| PGM:ICETOOL| DD:FILESIN
Ice002P030_04SortIn=Y900.P.TM.USBTBITM.FILEOUT(+0)
Ice002P030_04SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_04SortIn.RecordType=FB
Ice002P030_04SortIn.RecordLen=80
#
#
#STEP:P030_04| PGM:ICETOOL| DD:FILEBA2
Ice002P030_04SortOut=Y900.P.TM.Y90DCABR.SORTBA2
Ice002P030_04SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_04SortOut.RecordType=FB
Ice002P030_04SortOut.RecordLen=80
#
#
#STEP:P030_05| PGM:ICETOOL| DD:FILESIN
Ice002P030_05SortIn=Y900.P.TM.USBTBITM.FILEOUT(+0)
Ice002P030_05SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_05SortIn.RecordType=FB
Ice002P030_05SortIn.RecordLen=80
#
#
#STEP:P030_05| PGM:ICETOOL| DD:FILEBAW
Ice002P030_05SortOut=Y900.P.TM.Y90DCABR.SORTBAW
Ice002P030_05SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_05SortOut.RecordType=FB
Ice002P030_05SortOut.RecordLen=80
#
#
#STEP:P030_06| PGM:ICETOOL| DD:FILEBAW
Ice002P030_06SortIn=Y900.P.TM.Y90DCABR.SORTBAW
Ice002P030_06SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_06SortIn.RecordType=FB
Ice002P030_06SortIn.RecordLen=80
#
#
#STEP:P030_06| PGM:ICETOOL| DD:FILEBA3
Ice002P030_06SortOut=Y900.P.TM.Y90DCABR.SORTBA3
Ice002P030_06SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_06SortOut.RecordType=FB
Ice002P030_06SortOut.RecordLen=80
#
#
#STEP:P030_07| PGM:ICETOOL| DD:FILESIN
Ice002P030_07SortIn=Y900.P.TM.USBTBITM.FILEOUT(+0)
Ice002P030_07SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_07SortIn.RecordType=FB
Ice002P030_07SortIn.RecordLen=80
#
#
#STEP:P030_07| PGM:ICETOOL| DD:FILEBA4
Ice002P030_07SortOut=Y900.P.TM.Y90DCABR.SORTBA4
Ice002P030_07SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_07SortOut.RecordType=FB
Ice002P030_07SortOut.RecordLen=80
#
#
#STEP:P030_08| PGM:ICETOOL| DD:FILESIN
Ice002P030_08SortIn=Y900.P.TM.USBTBITM.FILEOUT(+0)
Ice002P030_08SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_08SortIn.RecordType=FB
Ice002P030_08SortIn.RecordLen=80
#
#
#STEP:P030_08| PGM:ICETOOL| DD:FILEITM
Ice002P030_08SortOut=Y900.P.TM.Y90DCABR.SORTITM
Ice002P030_08SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_08SortOut.RecordType=FB
Ice002P030_08SortOut.RecordLen=80
#
#
#STEP:P030_09| PGM:ICETOOL| DD:FILEAK1
Ice002P030_09SortIn=Y900.P.TM.Y90DCABR.SORTAK1
Ice002P030_09SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_09SortIn.RecordType=FB
Ice002P030_09SortIn.RecordLen=80
#
#
#STEP:P030_09| PGM:ICETOOL| DD:SUMWORK
Ice002P030_09SortOut=Y900.P.TM.Y90DCABR.SUMWORK
Ice002P030_09SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_09SortOut.RecordType=FB
Ice002P030_09SortOut.RecordLen=80
#
#
#STEP:P030_10| PGM:ICETOOL| DD:FILECLC
Ice002P030_10SortIn=Y900.P.TM.Y90DCABR.SORTCLC
Ice002P030_10SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_10SortIn.RecordType=FB
Ice002P030_10SortIn.RecordLen=80
#
#
#STEP:P030_10| PGM:ICETOOL| DD:SUMWORK
Ice002P030_10SortOut=Y900.P.TM.Y90DCABR.SUMWORK
Ice002P030_10SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_10SortOut.RecordType=FB
Ice002P030_10SortOut.RecordLen=80
#
#
#STEP:P030_11| PGM:ICETOOL| DD:FILEBA1
Ice002P030_11SortIn=Y900.P.TM.Y90DCABR.SORTBA1
Ice002P030_11SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_11SortIn.RecordType=FB
Ice002P030_11SortIn.RecordLen=80
#
#
#STEP:P030_11| PGM:ICETOOL| DD:SUMWORK
Ice002P030_11SortOut=Y900.P.TM.Y90DCABR.SUMWORK
Ice002P030_11SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_11SortOut.RecordType=FB
Ice002P030_11SortOut.RecordLen=80
#
#
#STEP:P030_12| PGM:ICETOOL| DD:FILEBA2
Ice002P030_12SortIn=Y900.P.TM.Y90DCABR.SORTBA2
Ice002P030_12SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_12SortIn.RecordType=FB
Ice002P030_12SortIn.RecordLen=80
#
#
#STEP:P030_12| PGM:ICETOOL| DD:SUMWORK
Ice002P030_12SortOut=Y900.P.TM.Y90DCABR.SUMWORK
Ice002P030_12SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_12SortOut.RecordType=FB
Ice002P030_12SortOut.RecordLen=80
#
#
#STEP:P030_13| PGM:ICETOOL| DD:FILEBA3
Ice002P030_13SortIn=Y900.P.TM.Y90DCABR.SORTBA3
Ice002P030_13SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_13SortIn.RecordType=FB
Ice002P030_13SortIn.RecordLen=80
#
#
#STEP:P030_13| PGM:ICETOOL| DD:SUMWORK
Ice002P030_13SortOut=Y900.P.TM.Y90DCABR.SUMWORK
Ice002P030_13SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_13SortOut.RecordType=FB
Ice002P030_13SortOut.RecordLen=80
#
#
#STEP:P030_14| PGM:ICETOOL| DD:FILEBA4
Ice002P030_14SortIn=Y900.P.TM.Y90DCABR.SORTBA4
Ice002P030_14SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_14SortIn.RecordType=FB
Ice002P030_14SortIn.RecordLen=80
#
#
#STEP:P030_14| PGM:ICETOOL| DD:SUMWORK
Ice002P030_14SortOut=Y900.P.TM.Y90DCABR.SUMWORK
Ice002P030_14SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_14SortOut.RecordType=FB
Ice002P030_14SortOut.RecordLen=80
#
#
#STEP:P030_15| PGM:ICETOOL| DD:FILEITM
Ice002P030_15SortIn=Y900.P.TM.Y90DCABR.SORTITM
Ice002P030_15SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_15SortIn.RecordType=FB
Ice002P030_15SortIn.RecordLen=80
#
#
#STEP:P030_15| PGM:ICETOOL| DD:SUMWORK
Ice002P030_15SortOut=Y900.P.TM.Y90DCABR.SUMWORK
Ice002P030_15SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_15SortOut.RecordType=FB
Ice002P030_15SortOut.RecordLen=80
#
#
#STEP:P030_16| PGM:ICETOOL| DD:SUMWORK
Ice002P030_16SortIn=Y900.P.TM.Y90DCABR.SUMWORK
Ice002P030_16SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_16SortIn.RecordType=FB
Ice002P030_16SortIn.RecordLen=80
#
#
#STEP:P030_16| PGM:ICETOOL| DD:SUMALL
Ice002P030_16SortOut=Y900.P.TM.Y90DCABR.SUMALL
Ice002P030_16SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_16SortOut.RecordType=FB
Ice002P030_16SortOut.RecordLen=80
#
#
#STEP:P030_17| PGM:ICETOOL| DD:FILEAK1
Ice002P030_17SortIn=Y900.P.TM.Y90DCABR.SORTAK1
Ice002P030_17SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_17SortIn.RecordType=FB
Ice002P030_17SortIn.RecordLen=80
#
#
#STEP:P030_17| PGM:ICETOOL| DD:ENDRESLT
Ice002P030_17SortOut=Y900.P.TM.Y90DCABR.SBRTSALL
Ice002P030_17SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_17SortOut.RecordType=FB
Ice002P030_17SortOut.RecordLen=80
#
#
#STEP:P030_18| PGM:ICETOOL| DD:FILECLC
Ice002P030_18SortIn=Y900.P.TM.Y90DCABR.SORTCLC
Ice002P030_18SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_18SortIn.RecordType=FB
Ice002P030_18SortIn.RecordLen=80
#
#
#STEP:P030_18| PGM:ICETOOL| DD:ENDRESLT
Ice002P030_18SortOut=Y900.P.TM.Y90DCABR.SBRTSALL
Ice002P030_18SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_18SortOut.RecordType=FB
Ice002P030_18SortOut.RecordLen=80
#
#
#STEP:P030_19| PGM:ICETOOL| DD:FILEBA1
Ice002P030_19SortIn=Y900.P.TM.Y90DCABR.SORTBA1
Ice002P030_19SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_19SortIn.RecordType=FB
Ice002P030_19SortIn.RecordLen=80
#
#
#STEP:P030_19| PGM:ICETOOL| DD:ENDRESLT
Ice002P030_19SortOut=Y900.P.TM.Y90DCABR.SBRTSALL
Ice002P030_19SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_19SortOut.RecordType=FB
Ice002P030_19SortOut.RecordLen=80
#
#
#STEP:P030_20| PGM:ICETOOL| DD:FILEBA2
Ice002P030_20SortIn=Y900.P.TM.Y90DCABR.SORTBA2
Ice002P030_20SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_20SortIn.RecordType=FB
Ice002P030_20SortIn.RecordLen=80
#
#
#STEP:P030_20| PGM:ICETOOL| DD:ENDRESLT
Ice002P030_20SortOut=Y900.P.TM.Y90DCABR.SBRTSALL
Ice002P030_20SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_20SortOut.RecordType=FB
Ice002P030_20SortOut.RecordLen=80
#
#
#STEP:P030_21| PGM:ICETOOL| DD:FILEBA3
Ice002P030_21SortIn=Y900.P.TM.Y90DCABR.SORTBA3
Ice002P030_21SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_21SortIn.RecordType=FB
Ice002P030_21SortIn.RecordLen=80
#
#
#STEP:P030_21| PGM:ICETOOL| DD:ENDRESLT
Ice002P030_21SortOut=Y900.P.TM.Y90DCABR.SBRTSALL
Ice002P030_21SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_21SortOut.RecordType=FB
Ice002P030_21SortOut.RecordLen=80
#
#
#STEP:P030_22| PGM:ICETOOL| DD:FILEBA4
Ice002P030_22SortIn=Y900.P.TM.Y90DCABR.SORTBA4
Ice002P030_22SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_22SortIn.RecordType=FB
Ice002P030_22SortIn.RecordLen=80
#
#
#STEP:P030_22| PGM:ICETOOL| DD:ENDRESLT
Ice002P030_22SortOut=Y900.P.TM.Y90DCABR.SBRTSALL
Ice002P030_22SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_22SortOut.RecordType=FB
Ice002P030_22SortOut.RecordLen=80
#
#
#STEP:P030_23| PGM:ICETOOL| DD:FILEITM
Ice002P030_23SortIn=Y900.P.TM.Y90DCABR.SORTITM
Ice002P030_23SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_23SortIn.RecordType=FB
Ice002P030_23SortIn.RecordLen=80
#
#
#STEP:P030_23| PGM:ICETOOL| DD:ENDRESLT
Ice002P030_23SortOut=Y900.P.TM.Y90DCABR.SBRTSALL
Ice002P030_23SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_23SortOut.RecordType=FB
Ice002P030_23SortOut.RecordLen=80
#
#
#STEP:P030_24| PGM:ICETOOL| DD:SUMALL
Ice002P030_24SortIn=Y900.P.TM.Y90DCABR.SUMALL
Ice002P030_24SortIn.DISP=SHR,KEEP,KEEP
Ice002P030_24SortIn.RecordType=FB
Ice002P030_24SortIn.RecordLen=80
#
#
#STEP:P030_24| PGM:ICETOOL| DD:ENDRESLT
Ice002P030_24SortOut=Y900.P.TM.Y90DCABR.SBRTSALL
Ice002P030_24SortOut.DISP=MOD,KEEP,KEEP
Ice002P030_24SortOut.RecordType=FB
Ice002P030_24SortOut.RecordLen=80
#
#STEP:P050| PGM:IEBGENER| DD:SYSUT1
P050.IEBGENER.Sysut1=Y900.P.TM.Y90DCABR.SBRTSALL
P050.IEBGENER.Sysut1.DISP=SHR,KEEP,KEEP
P050.IEBGENER.Sysut1.RecordType=FB
P050.IEBGENER.Sysut1.RecordLen=80
#
#STEP:P050| PGM:IEBGENER| DD:SYSUT2
P050.IEBGENER.Sysut2=Y900.P.TM.ITEMSUMM.X350
P050.IEBGENER.Sysut2.DISP=NEW,CATLG,DELETE
P050.IEBGENER.Sysut2.RecordType=FB
P050.IEBGENER.Sysut2.RecordLen=80
#
#STEP:P060| PGM:SORT| DD:SORTIN
Ice002P060SortIn=Y900.P.TM.ITEMSUMM.X350
Ice002P060SortIn.DISP=SHR,KEEP,KEEP
Ice002P060SortInRecordType=FB
Ice002P060SortInRecordLen=80
#STEP:P060| PGM:SORT| DD:SORTOUT
Ice002P060SortOut=Y900.P.TM.ITEMSUMM.TMS
Ice002P060SortOut.DISP=NEW,CATLG,DELETE
Ice002P060SortOutRecordType=FB
Ice002P060SortOutRecordLen=80
