  package com.cloudframe.app.process.impl;
  /* Java code generated by CloudFrame on 2025-04-24 at 16:43. */
  
  import com.cloudframe.app.edit1.Edit1Ctx.*;
  import com.cloudframe.app.edit1.Edit1Ctx;
  import com.cloudframe.app.process.Edit1;
  import com.cloudframe.app.process.BaseProcess;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.dto.GlobalExecutorCtx;
  import com.cloudframe.app.utility.CFUtil;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.edit1.dto.*;
  import com.cloudframe.app.edit1.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  
  @Component("edit1")
  
  public class Edit1Impl extends CommonProcess implements Edit1 {
  
  Logger logger = LoggerFactory.getLogger(Edit1Impl.class);
  
  
  
  
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output :  

      * - wS1                            COBOL Name: WS-1
      * - wS2                            COBOL Name: WS-2
      * - wS3                            COBOL Name: WS-3
      * - wS4                            COBOL Name: WS-4
      * - wS5                            COBOL Name: WS-5
      * - wS6                            COBOL Name: WS-6
      * - wS07                           COBOL Name: WS-07
      * - wS08                           COBOL Name: WS-08
      * - wS09                           COBOL Name: WS-09
      * - wS10                           COBOL Name: WS-10
      * - wS11                           COBOL Name: WS-11
      * - wS12                           COBOL Name: WS-12
      * - wS13                           COBOL Name: WS-13
      * - wS14                           COBOL Name: WS-14
      * - wS15                           COBOL Name: WS-15
      * - wS16                           COBOL Name: WS-16
      * - wS17                           COBOL Name: WS-17
      * - wS18                           COBOL Name: WS-18
      * - wS19                           COBOL Name: WS-19
      * - wS20                           COBOL Name: WS-20
      * - wS21                           COBOL Name: WS-21
      * - wS22                           COBOL Name: WS-22
      * - wS23                           COBOL Name: WS-23
      * - wS24                           COBOL Name: WS-24
      * - wS25                           COBOL Name: WS-25
      * - wS26                           COBOL Name: WS-26
      *
      * @throws CFException
      */
      public int process(Edit1Ctx programCtx) throws Exception {
       try {
       setCodePage("1047");
            // Reset program ended flag
           programCtx.setProgramEnded(false);
ProcessOutCtx methodOut = programCtx.getProcessOutCtx();
//  MOVE -1234567.56 TO WS-1
//  LITERAL_873148860 = -1234567.56, FORMAT_117107259 = "$,$$$,999.99"
          methodOut.setWS1(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_117107259,CONSTANTS.LITERAL_873148860));
//  DISPLAY '  1.' '$,$$$,999.99   -1234567.56 ACTUAL >' WS-1 '<'
          logger.info("  1.$,$$$,999.99   -1234567.56 ACTUAL >{}<", new String(methodOut.getWS1())); 
//  MOVE -1234567.789 TO WS-2
//  LITERAL_1297873135 = -1234567.789, FORMAT_1521621993 = "+,+++,999.99"
          methodOut.setWS2(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1521621993,CONSTANTS.LITERAL_1297873135));
//  DISPLAY '  2.' '+,+++,999.99   -1234567.789 ACTUAL >' WS-2 '<'
          logger.info("  2.+,+++,999.99   -1234567.789 ACTUAL >{}<", new String(methodOut.getWS2())); 
//  MOVE -1234.45 TO WS-3
//  LITERAL_315839328 = -1234.45, FORMAT_1496183807 = "*,***.**+"
          methodOut.setWS3(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1496183807,CONSTANTS.LITERAL_315839328));
//  DISPLAY '  3.' '*,***.**+      -1234.45 ACTUAL >' WS-3 '<'
          logger.info("  3.*,***.**+      -1234.45 ACTUAL >{}<", new String(methodOut.getWS3())); 
//  MOVE -1234.45 TO WS-4
//  LITERAL_315839328 = -1234.45, FORMAT_1752851303 = "*,***.*+"
          methodOut.setWS4(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1752851303,CONSTANTS.LITERAL_315839328));
//  DISPLAY '  4.' '*,***.*+       -1234.45 ACTUAL >' WS-4 '<'
          logger.info("  4.*,***.*+       -1234.45 ACTUAL >{}<", new String(methodOut.getWS4())); 
//  MOVE -234.56 TO WS-5
//  LITERAL_1566779237 = -234.56, FORMAT_1905112861 = "--,9.99"
          methodOut.setWS5(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1905112861,CONSTANTS.LITERAL_1566779237));
//  DISPLAY '  5.' '--,-9.99       -234.56 ACTUAL >' WS-5 '<'
          logger.info("  5.--,-9.99       -234.56 ACTUAL >{}<", new String(methodOut.getWS5())); 
//  MOVE -234.56 TO WS-6
//  LITERAL_1566779237 = -234.56, FORMAT_1530979905 = "-,-9.99"
          methodOut.setWS6(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1530979905,CONSTANTS.LITERAL_1566779237));
//  DISPLAY '  6.' '-,-9.99        -234.56 ACTUAL >' WS-6 '<'
          logger.info("  6.-,-9.99        -234.56 ACTUAL >{}<", new String(methodOut.getWS6())); 
//  MOVE 1.234 TO WS-07
//  LITERAL_1557204654 = 1.234, FORMAT_139959221 = "999.99"
          methodOut.setWS07(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_139959221,CONSTANTS.LITERAL_1557204654));
//  DISPLAY '  7.' '"999.99" "1.234"             "' WS-07 '" '
          logger.info("  7.\"999.99\" \"1.234\"             \"{}\" ", new String(methodOut.getWS07())); 
//  MOVE 12.34 TO WS-08
//  LITERAL_1560779574 = 12.34, FORMAT_139959221 = "999.99"
          methodOut.setWS08(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_139959221,CONSTANTS.LITERAL_1560779574));
//  DISPLAY '  8.' '"999.99" "12.34"             "' WS-08 '" '
          logger.info("  8.\"999.99\" \"12.34\"             \"{}\" ", new String(methodOut.getWS08())); 
//  MOVE 123.45 TO WS-09
//  LITERAL_1143995811 = 123.45, FORMAT_139959221 = "999.99"
          methodOut.setWS09(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_139959221,CONSTANTS.LITERAL_1143995811));
//  DISPLAY '  9.' '"999.99" "123.45"            "' WS-09 '" '
          logger.info("  9.\"999.99\" \"123.45\"            \"{}\" ", new String(methodOut.getWS09())); 
//  MOVE 1234.5 TO WS-10
//  LITERAL_1144168791 = 1234.5, FORMAT_139959221 = "999.99"
          methodOut.setWS10(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_139959221,CONSTANTS.LITERAL_1144168791));
//  DISPLAY ' 10.' '"999.99" "1234.5"            "' WS-10 '" '
          logger.info(" 10.\"999.99\" \"1234.5\"            \"{}\" ", new String(methodOut.getWS10())); 
//  MOVE 12345 TO WS-11
//  LITERAL_12345 = 12345, FORMAT_1570673630 = "+999.99E+99"
          methodOut.setWS11(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1570673630,CONSTANTS.LITERAL_12345));
//  DISPLAY ' 11.' '"+999.99E+99" "12345"      "' WS-11 '" '
          logger.info(" 11.\"+999.99E+99\" \"12345\"      \"{}\" ", new String(methodOut.getWS11())); 
//  MOVE +6555.556 TO WS-12
//  LITERAL_411062766 = +6555.556, FORMAT_43768242 = "999.99+"
          methodOut.setWS12(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_43768242,CONSTANTS.LITERAL_411062766));
//  DISPLAY ' 12.' '"999.99+" "+6555.556"        "' WS-12 '" '
          logger.info(" 12.\"999.99+\" \"+6555.556\"        \"{}\" ", new String(methodOut.getWS12())); 
//  MOVE -6555.555 TO WS-13
//  LITERAL_804089807 = -6555.555, FORMAT_1507649635 = "+9999.99"
          methodOut.setWS13(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1507649635,CONSTANTS.LITERAL_804089807));
//  DISPLAY ' 13.' '"+9999.99" "-6555.555"       "' WS-13 '" '
          logger.info(" 13.\"+9999.99\" \"-6555.555\"       \"{}\" ", new String(methodOut.getWS13())); 
//  MOVE +1234.56 TO WS-14
//  LITERAL_364218050 = +1234.56, FORMAT_33936778 = "9999.99"
          methodOut.setWS14(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_33936778,CONSTANTS.LITERAL_364218050));
//  DISPLAY ' 14.' '"9999.99" "+1234.56"         "' WS-14 '" '
          logger.info(" 14.\"9999.99\" \"+1234.56\"         \"{}\" ", new String(methodOut.getWS14())); 
//  MOVE -123.45 TO WS-15
//  LITERAL_1811130714 = -123.45, FORMAT_2021751851 = "$999.99"
          methodOut.setWS15(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_2021751851,CONSTANTS.LITERAL_1811130714));
//  DISPLAY ' 15.' '"$999.99" "-123.45"          "' WS-15 '" '
          logger.info(" 15.\"$999.99\" \"-123.45\"          \"{}\" ", new String(methodOut.getWS15())); 
//  MOVE -123.456 TO WS-16
//  LITERAL_310477940 = -123.456, FORMAT_1228097364 = "-$999.99"
          methodOut.setWS16(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1228097364,CONSTANTS.LITERAL_310477940));
//  DISPLAY ' 16.' '"-$999.99" "-123.456"        "' WS-16 '" '
          logger.info(" 16.\"-$999.99\" \"-123.456\"        \"{}\" ", new String(methodOut.getWS16())); 
//  MOVE +123.456 TO WS-17
//  LITERAL_369580430 = +123.456, FORMAT_1228097364 = "-$999.99"
          methodOut.setWS17(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1228097364,CONSTANTS.LITERAL_369580430));
//  DISPLAY ' 17.' '"-$999.99" "+123.456"        "' WS-17 '" '
          logger.info(" 17.\"-$999.99\" \"+123.456\"        \"{}\" ", new String(methodOut.getWS17())); 
//  MOVE +123.45 TO WS-18
//  LITERAL_1674489956 = +123.45, FORMAT_1753528569 = "$9999.99CR"
          methodOut.setWS18(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1753528569,CONSTANTS.LITERAL_1674489956));
//  DISPLAY ' 18.' '"$9999.99CR" "+123.45"       "' WS-18 '" '
          logger.info(" 18.\"$9999.99CR\" \"+123.45\"       \"{}\" ", new String(methodOut.getWS18())); 
//  MOVE -123.45 TO WS-19
//  LITERAL_1811130714 = -123.45, FORMAT_1753528569 = "$9999.99CR"
          methodOut.setWS19(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1753528569,CONSTANTS.LITERAL_1811130714));
//  DISPLAY ' 19.' '"$9999.99CR" "-123.45"       "' WS-19 '" '
          logger.info(" 19.\"$9999.99CR\" \"-123.45\"       \"{}\" ", new String(methodOut.getWS19())); 
//  MOVE .123 TO WS-20
//  LITERAL_1017382524 = .123, FORMAT_56562378 = "$$$$.99"
          methodOut.setWS20(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_56562378,CONSTANTS.LITERAL_1017382524));
//  DISPLAY ' 20.' '"$$$$.99 .123"                "' WS-20 '" '
          logger.info(" 20.\"$$$$.99 .123\"                \"{}\" ", new String(methodOut.getWS20())); 
//  MOVE .12 TO WS-21
//  LITERAL_32818773 = .12, FORMAT_37168437 = "$$$9.99"
          methodOut.setWS21(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_37168437,CONSTANTS.LITERAL_32818773));
//  DISPLAY ' 21.' '"$$$9.99 .12"                 "' WS-21 '" '
          logger.info(" 21.\"$$$9.99 .12\"                 \"{}\" ", new String(methodOut.getWS21())); 
//  MOVE -1234.56 TO WS-22
//  LITERAL_315840320 = -1234.56, FORMAT_117107259 = "$,$$$,999.99"
          methodOut.setWS22(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_117107259,CONSTANTS.LITERAL_315840320));
//  DISPLAY ' 22.' '"$,$$$,999.99 -1234.56"       "' WS-22 '" '
          logger.info(" 22.\"$,$$$,999.99 -1234.56\"       \"{}\" ", new String(methodOut.getWS22())); 
//  MOVE -123456.789 TO WS-23
//  LITERAL_865108266 = -123456.789, FORMAT_1521621993 = "+,+++,999.99"
          methodOut.setWS23(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1521621993,CONSTANTS.LITERAL_865108266));
//  DISPLAY ' 23.' '"+,+++,999.99 -123456.789"    "' WS-23 '" '
          logger.info(" 23.\"+,+++,999.99 -123456.789\"    \"{}\" ", new String(methodOut.getWS23())); 
//  MOVE -1234567 TO WS-24
//  LITERAL_MN_1234567 = -1234567, FORMAT_1482399849 = "$$,$$$,$$$.99CR"
          methodOut.setWS24(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1482399849,CONSTANTS.LITERAL_MN_1234567));
//  DISPLAY ' 24.' '"$$,$$$,$$$.99CR" "-1234567"   "' WS-24 '"'
          logger.info(" 24.\"$$,$$$,$$$.99CR\" \"-1234567\"   \"{}\"", new String(methodOut.getWS24())); 
//  MOVE 0000.00 TO WS-25
//  LITERAL_1797057878 = 0000.00, FORMAT_1859484197 = "++,+++,+++.+++"
          methodOut.setWS25(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1859484197,CONSTANTS.LITERAL_1797057878));
//  DISPLAY ' 25.' '"++,+++,+++.+++" "000.00"      "' WS-25 '"'
          logger.info(" 25.\"++,+++,+++.+++\" \"000.00\"      \"{}\"", new String(methodOut.getWS25())); 
//  MOVE 0000.00 TO WS-26
//  LITERAL_1797057878 = 0000.00, FORMAT_1277246314 = "****.**"
          methodOut.setWS26(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1277246314,CONSTANTS.LITERAL_1797057878));
//  PERFORM PROCESS-1
          process1(programCtx.getProcess1InCtx());/*PROCESS-1*/
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
       return programCtx.getRc(); // Exit with return code
      // end of process method
      }
      /**
      * process1 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-1 COBOL Cyclomatic complexity - 1
      * Input  :  

      * - wS26                           COBOL Name: WS-26
      *
      * Output :  

      * - wS27                           COBOL Name: WS-27
      * - wS28                           COBOL Name: WS-28
      * - wS29                           COBOL Name: WS-29
      * - wS30                           COBOL Name: WS-30
      * - wS31                           COBOL Name: WS-31
      * - wS32                           COBOL Name: WS-32
      * - wS33                           COBOL Name: WS-33
      * - wS34                           COBOL Name: WS-34
      * - wS35                           COBOL Name: WS-35
      * - wS36                           COBOL Name: WS-36
      * - wS37                           COBOL Name: WS-37
      * - wS38                           COBOL Name: WS-38
      * - wS39                           COBOL Name: WS-39
      * - wS40                           COBOL Name: WS-40
      * - wS42                           COBOL Name: WS-42
      * - wS46                           COBOL Name: WS-46
      *
      * @throws CFException
      */
      @Override
      public Process1OutCtx process1(Process1InCtx methodIn) throws Exception {
Edit1Ctx programCtx = methodIn.getEdit1Ctx();
Process1OutCtx methodOut = methodIn.getProcess1OutCtx();
//  DISPLAY ' 26.' '"****.**" "0000.00"            "' WS-26 '"'
          logger.info(" 26.\"****.**\" \"0000.00\"            \"{}\"", new String(methodIn.getWS26())); 
//  MOVE 0000.00 TO WS-27
//  LITERAL_1797057878 = 0000.00, FORMAT_1842350742 = "ZZZZ.ZZ"
          methodOut.setWS27(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1842350742,CONSTANTS.LITERAL_1797057878));
//  DISPLAY ' 27.' '"ZZZZ.ZZ" "0000.00"            "' WS-27 '"'
          logger.info(" 27.\"ZZZZ.ZZ\" \"0000.00\"            \"{}\"", new String(methodOut.getWS27())); 
//  MOVE 0000.00 TO WS-28
//  LITERAL_1797057878 = 0000.00, FORMAT_1842318006 = "ZZZZ.99"
          methodOut.setWS28(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1842318006,CONSTANTS.LITERAL_1797057878));
//  DISPLAY ' 28.' '"ZZZZ.99" "0000.00"            "' WS-28 '"'
          logger.info(" 28.\"ZZZZ.99\" \"0000.00\"            \"{}\"", new String(methodOut.getWS28())); 
//  MOVE 0000.00 TO WS-29
//  LITERAL_1797057878 = 0000.00, FORMAT_1277231434 = "****.99"
          methodOut.setWS29(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1277231434,CONSTANTS.LITERAL_1797057878));
//  DISPLAY ' 29.' '"****.99" "0000.00"            "' WS-29 '"'
          logger.info(" 29.\"****.99\" \"0000.00\"            \"{}\"", new String(methodOut.getWS29())); 
//  MOVE 0000.00 TO WS-30
//  LITERAL_1797057878 = 0000.00, FORMAT_867079830 = "ZZ99.99"
          methodOut.setWS30(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_867079830,CONSTANTS.LITERAL_1797057878));
//  DISPLAY ' 30.' '"ZZ99.99" "0000.00"            "' WS-30 '"'
          logger.info(" 30.\"ZZ99.99\" \"0000.00\"            \"{}\"", new String(methodOut.getWS30())); 
//  MOVE +123.456 TO WS-31
//  LITERAL_369580430 = +123.456, FORMAT_564800609 = "Z,ZZZ.ZZ+"
          methodOut.setWS31(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_564800609,CONSTANTS.LITERAL_369580430));
//  DISPLAY ' 31.' '"Z,ZZZ.ZZ+" "+123.456"         "' WS-31 '"'
          logger.info(" 31.\"Z,ZZZ.ZZ+\" \"+123.456\"         \"{}\"", new String(methodOut.getWS31())); 
//  MOVE -123.45 TO WS-32
//  LITERAL_1811130714 = -123.45, FORMAT_1496183807 = "*,***.**+"
          methodOut.setWS32(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1496183807,CONSTANTS.LITERAL_1811130714));
//  DISPLAY ' 32.' '"*,***.**+" "-123.45"          "' WS-32 '"'
          logger.info(" 32.\"*,***.**+\" \"-123.45\"          \"{}\"", new String(methodOut.getWS32())); 
//  MOVE +12345678.9 TO WS-33
//  LITERAL_615274698 = +12345678.9, FORMAT_62899239 = "**,***,***.**+"
          methodOut.setWS33(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_62899239,CONSTANTS.LITERAL_615274698));
//  DISPLAY ' 33.' '"**,***,***.**+" "+12345678.9"  "' WS-33 '"'
          logger.info(" 33.\"**,***,***.**+\" \"+12345678.9\"  \"{}\"", new String(methodOut.getWS33())); 
//  MOVE +12345.67 TO WS-34
//  LITERAL_1600399133 = +12345.67, FORMAT_1302734873 = "$Z,ZZZ,ZZZ.ZZCR"
          methodOut.setWS34(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1302734873,CONSTANTS.LITERAL_1600399133));
//  DISPLAY ' 34.' '"$Z,ZZZ,ZZZ.ZZCR" "+12345.67"   "' WS-34 '"'
          logger.info(" 34.\"$Z,ZZZ,ZZZ.ZZCR\" \"+12345.67\"   \"{}\"", new String(methodOut.getWS34())); 
//  MOVE -12345.67 TO WS-35
//  LITERAL_1207372123 = -12345.67, FORMAT_383751516 = "$B*,***,***.**BBDB"
          methodOut.setWS35(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_383751516,CONSTANTS.LITERAL_1207372123));
//  DISPLAY ' 35.' '"$B*,***,***.**BBDB" "-12345.67""' WS-35 '"'
          logger.info(" 35.\"$B*,***,***.**BBDB\" \"-12345.67\"\"{}\"", new String(methodOut.getWS35())); 
//  MOVE 4917.842600000001 TO WS-36
//  LITERAL_616730720 = 4917.842600000001, FORMAT_505319870 = "ZZZZZ9.99-"
          methodOut.setWS36(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_505319870,CONSTANTS.LITERAL_616730720));
//  DISPLAY ' 36.' '"ZZZZZ9.99-" "4917.842600000001" "' WS-36 '"'
          logger.info(" 36.\"ZZZZZ9.99-\" \"4917.842600000001\" \"{}\"", new String(methodOut.getWS36())); 
//  MOVE 4917.842600000001 TO WS-37
//  LITERAL_616730720 = 4917.842600000001, FORMAT_1033206804 = "ZZ,ZZ9.99-"
          methodOut.setWS37(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1033206804,CONSTANTS.LITERAL_616730720));
//  DISPLAY ' 37.' '"ZZ,ZZ9.99-" "4917.842600000001" "' WS-37 '"'
          logger.info(" 37.\"ZZ,ZZ9.99-\" \"4917.842600000001\" \"{}\"", new String(methodOut.getWS37())); 
//  MOVE -888.88 TO WS-38
//  LITERAL_389881663 = -888.88, FORMAT_226624864 = "--------------9.99999"
          methodOut.setWS38(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_226624864,CONSTANTS.LITERAL_389881663));
//  DISPLAY ' 38.' '"--------------9.99999" "-888.88" "' WS-38 '"'
          logger.info(" 38.\"--------------9.99999\" \"-888.88\" \"{}\"", new String(methodOut.getWS38())); 
//  MOVE -98765432101234 TO WS-39
//  LITERAL_MN_98765432101234 = -98765432101234, FORMAT_226624864 = "--------------9.99999"
          methodOut.setWS39(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_226624864,CONSTANTS.LITERAL_MN_98765432101234));
//  DISPLAY ' 39.' '"--------------9.99999" "-98765432101234" ' '"' WS-39 '"'
          logger.info(" 39.\"--------------9.99999\" \"-98765432101234\" \"{}\"", new String(methodOut.getWS39())); 
//  MOVE -9.8765432101234E13 TO WS-40
//  LITERAL_2092897743 = -9.8765432101234E13, FORMAT_226624864 = "--------------9.99999"
          methodOut.setWS40(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_226624864,CONSTANTS.LITERAL_2092897743));
//  DISPLAY ' 40.' '"--------------9.99999" "-9.8765432101234E13"' '"' WS-40 '"'
          logger.info(" 40.\"--------------9.99999\" \"-9.8765432101234E13\"\"{}\"", new String(methodOut.getWS40())); 

// *        Move -12345.67 to ws-41
//  DISPLAY ' 41.' '"+$9,99.99E+99" "-12345.67" ** INVALID ** '
          logger.info(" 41.\"+$9,99.99E+99\" \"-12345.67\" ** INVALID ** "); 
//  MOVE .1234567 TO WS-42
//  LITERAL_1491404614 = .1234567, FORMAT_1570673630 = "+999.99E+99"
          methodOut.setWS42(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1570673630,CONSTANTS.LITERAL_1491404614));
//  DISPLAY ' 42.' '"+999.99E+99" ".1234567"       "' WS-42 '"'
          logger.info(" 42.\"+999.99E+99\" \".1234567\"       \"{}\"", new String(methodOut.getWS42())); 

// *        Move .1234567 to ws-43
//  DISPLAY ' 43.' '"+999.99E+9999" ".1234567"  ** INVALID ** '
          logger.info(" 43.\"+999.99E+9999\" \".1234567\"  ** INVALID ** "); 

// *        Move .123 to ws-44
//  DISPLAY ' 44.' '"+999E+99" ".123"789        ** INVALID **'
          logger.info(" 44.\"+999E+99\" \".123\"789        ** INVALID **"); 

// *        Move .123 to ws-45
//  DISPLAY ' 45.' '"+***E+99" ".123"789        ** INVALID **'
          logger.info(" 45.\"+***E+99\" \".123\"789        ** INVALID **"); 
//  MOVE +12.67 TO WS-46
//  LITERAL_84390333 = +12.67, FORMAT_1302734873 = "$Z,ZZZ,ZZZ.ZZCR"
          methodOut.setWS46(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT_1302734873,CONSTANTS.LITERAL_84390333));
//  DISPLAY ' 46.' '"$Z,ZZZ,ZZZ.ZZCR" "+12.67"     "' WS-46 '"'
          logger.info(" 46.\"$Z,ZZZ,ZZZ.ZZCR\" \"+12.67\"     \"{}\"", new String(methodOut.getWS46())); 

// *
//  STOP RUN
          throw Terminate.TERMINATE;
      
      }
  
  
  
  
  
  
  
  
  }
