# Program TSTCDPAG | DD : INFILE | RecordFormat : FixedLength | RecordLength : 1
TSTCDPAG.ddname.INFILE=CLOUDFRM.EBCDIC.BYTESIN
TSTCDPAG.InputFile=CLOUDFRM.EBCDIC.BYTESIN
TSTCDPAG.InputFile.DISP=SHR,KEEP,KEEP
TSTCDPAG.InputFileCharSet=cp1047
TSTCDPAG.InputFileCRLFflag=no
# Program TSTCDPAG | DD : OUTFILE | RecordFormat : FixedLength | RecordLength : 80
TSTCDPAG.ddname.OUTFILE=CLOUDFRM.EBCDIC.BYTESOUT.CF
TSTCDPAG.OutputFile=CLOUDFRM.EBCDIC.BYTESOUT.CF
TSTCDPAG.OutputFile.DISP=NEW,KEEP,KEEP
TSTCDPAG.OutputFileCharSet=cp1047
TSTCDPAG.OutputFileCRLFflag=no
# 
# End of TSTCDPAG