#STEP:SORT1| PGM:ICEMAN| DD:SORTIN
IcemanSort1SortIn=CLOUDFRM.JPM.SORT.INPUT1
IcemanSort1SortIn.DISP=SHR,KEEP,KEEP
IcemanSort1SortInRecordType=FB
IcemanSort1SortInRecordLen=200
#STEP:SORT1| PGM:ICEMAN| DD:SORTOUT
IcemanSort1SortOut=CLOUDFRM.JPM.SORT.OUTPUT1
IcemanSort1SortOut.DISP=NEW,KEEP,KEEP
IcemanSort1SortOutRecordType=FB
IcemanSort1SortOutRecordLen=200
#STEP:SORT2| PGM:ICEMAN| DD:SORTIN
IcemanSort2SortIn=CLOUDFRM.JPM.SORT.INPUT2
IcemanSort2SortIn.DISP=SHR,KEEP,KEEP
IcemanSort2SortInRecordType=FB
IcemanSort2SortInRecordLen=200
#STEP:SORT2| PGM:ICEMAN| DD:SORTOUT
IcemanSort2SortOut=CLOUDFRM.JPM.SORT.OUTPUT2
IcemanSort2SortOut.DISP=NEW,KEEP,KEEP
IcemanSort2SortOutRecordType=FB
IcemanSort2SortOutRecordLen=200
#STEP:SORT3| PGM:ICEMAN| DD:SORTIN
IcemanSort3SortIn=CLOUDFRM.JPM.SORT.INPUT
IcemanSort3SortIn.DISP=SHR,KEEP,KEEP
IcemanSort3SortInRecordType=FB
IcemanSort3SortInRecordLen=200
#STEP:SORT3| PGM:ICEMAN| DD:SORTOUT
IcemanSort3SortOut=CLOUDFRM.JPM.SORT.OUTPUT3
IcemanSort3SortOut.DISP=NEW,KEEP,KEEP
IcemanSort3SortOutRecordType=FB
IcemanSort3SortOutRecordLen=200
#STEP:SORT4| PGM:ICEMAN| DD:SORTIN
IcemanSort4SortIn=CLOUDFRM.JPM.SORT.INPUT
IcemanSort4SortIn.DISP=SHR,KEEP,KEEP
IcemanSort4SortInRecordType=FB
IcemanSort4SortInRecordLen=200
#STEP:SORT4| PGM:ICEMAN| DD:SORTOUT
IcemanSort4SortOut=CLOUDFRM.JPM.SORT.OUTPUT4
IcemanSort4SortOut.DISP=NEW,KEEP,KEEP
IcemanSort4SortOutRecordType=FB
IcemanSort4SortOutRecordLen=200
#STEP:SORT5| PGM:ICEMAN| DD:SORTIN
IcemanSort5SortIn=CLOUDFRM.JPM.SORT.INPUT
IcemanSort5SortIn.DISP=SHR,KEEP,KEEP
IcemanSort5SortInRecordType=FB
IcemanSort5SortInRecordLen=200
#STEP:SORT5| PGM:ICEMAN| DD:SORTOUT
IcemanSort5SortOut=CLOUDFRM.JPM.SORT.OUTPUT5
IcemanSort5SortOut.DISP=NEW,KEEP,KEEP
IcemanSort5SortOutRecordType=FB
IcemanSort5SortOutRecordLen=200
#STEP:SORT6| PGM:ICEMAN| DD:SORTIN
IcemanSort6SortIn=CLOUDFRM.JPM.SORT.INPUT
IcemanSort6SortIn.DISP=SHR,KEEP,KEEP
IcemanSort6SortInRecordType=FB
IcemanSort6SortInRecordLen=200
#STEP:SORT6| PGM:ICEMAN| DD:SORTOUT
IcemanSort6SortOut=CLOUDFRM.JPM.SORT.OUTPUT6
IcemanSort6SortOut.DISP=NEW,KEEP,KEEP
IcemanSort6SortOutRecordType=FB
IcemanSort6SortOutRecordLen=9
#STEP:SORT7| PGM:ICEMAN| DD:SORTIN
IcemanSort7SortIn=CLOUDFRM.JPM.SORT.INPUT
IcemanSort7SortIn.DISP=SHR,KEEP,KEEP
IcemanSort7SortInRecordType=FB
IcemanSort7SortInRecordLen=200
#STEP:SORT7| PGM:ICEMAN| DD:SORTOUT
IcemanSort7SortOut=CLOUDFRM.JPM.SORT.OUTPUT7
IcemanSort7SortOut.DISP=NEW,KEEP,KEEP
IcemanSort7SortOutRecordType=FB
IcemanSort7SortOutRecordLen=200
#STEP:SORT8| PGM:ICEMAN| DD:SORTIN
IcemanSort8SortIn=CLOUDFRM.JPM.SORT.INPUT
IcemanSort8SortIn.DISP=SHR,KEEP,KEEP
IcemanSort8SortInRecordType=FB
IcemanSort8SortInRecordLen=200
#STEP:SORT8| PGM:ICEMAN| DD:SORTOUT
IcemanSort8SortOut=CLOUDFRM.JPM.SORT.OUTPUT8
IcemanSort8SortOut.DISP=NEW,KEEP,KEEP
IcemanSort8SortOutRecordType=FB
IcemanSort8SortOutRecordLen=12
#STEP:SORT9| PGM:ICEMAN| DD:SORTIN
IcemanSort9SortIn=CLOUDFRM.JPM.SORT.INPUT9
IcemanSort9SortIn.DISP=SHR,KEEP,KEEP
IcemanSort9SortInRecordType=FB
IcemanSort9SortInRecordLen=52
#STEP:SORT9| PGM:ICEMAN| DD:SORTOUT
IcemanSort9SortOut=CLOUDFRM.JPM.SORT.OUTPUT9
IcemanSort9SortOut.DISP=NEW,KEEP,KEEP
IcemanSort9SortOutRecordType=FB
IcemanSort9SortOutRecordLen=8
#STEP:SORT10| PGM:ICEMAN| DD:SORTIN
IcemanSort10SortIn=CLOUDFRM.JPM.SORT.INPUT10
IcemanSort10SortIn.DISP=SHR,KEEP,KEEP
IcemanSort10SortInRecordType=FB
IcemanSort10SortInRecordLen=52
#STEP:SORT10| PGM:ICEMAN| DD:SORTOUT
IcemanSort10SortOut=CLOUDFRM.JPM.SORT.OUTPUT10
IcemanSort10SortOut.DISP=NEW,KEEP,KEEP
IcemanSort10SortOutRecordType=FB
IcemanSort10SortOutRecordLen=52
#STEP:SORT11| PGM:ICEMAN| DD:SORTIN
IcemanSort11SortIn=CLOUDFRM.JPM.SORT.INPUT11
IcemanSort11SortIn.DISP=SHR,KEEP,KEEP
IcemanSort11SortInRecordType=FB
IcemanSort11SortInRecordLen=52
#STEP:SORT11| PGM:ICEMAN| DD:SORTOUT
IcemanSort11SortOut=CLOUDFRM.JPM.SORT.OUTPUT11
IcemanSort11SortOut.DISP=NEW,KEEP,KEEP
IcemanSort11SortOutRecordType=FB
IcemanSort11SortOutRecordLen=11
#STEP:SORT12| PGM:ICEMAN| DD:SORTIN
IcemanSort12SortIn=CLOUDFRM.JPM.SORT.INPUT12
IcemanSort12SortIn.DISP=SHR,KEEP,KEEP
IcemanSort12SortInRecordType=FB
IcemanSort12SortInRecordLen=52
#STEP:SORT12| PGM:ICEMAN| DD:SORTOUT
IcemanSort12SortOut=CLOUDFRM.JPM.SORT.OUTPUT12
IcemanSort12SortOut.DISP=NEW,KEEP,KEEP
IcemanSort12SortOutRecordType=FB
IcemanSort12SortOutRecordLen=52
#STEP:SORT13| PGM:ICEMAN| DD:SORTIN
IcemanSort13SortIn=CLOUDFRM.JPM.SORT.INPUT13
IcemanSort13SortIn.DISP=SHR,KEEP,KEEP
IcemanSort13SortInRecordType=FB
IcemanSort13SortInRecordLen=52
#STEP:SORT13| PGM:ICEMAN| DD:SORTOUT
IcemanSort13SortOut=CLOUDFRM.JPM.SORT.OUTPUT13
IcemanSort13SortOut.DISP=NEW,KEEP,KEEP
IcemanSort13SortOutRecordType=FB
IcemanSort13SortOutRecordLen=52
#STEP:SORT14| PGM:ICEMAN| DD:SORTIN
IcemanSort14SortIn=CLOUDFRM.JPM.SORT.INPUT
IcemanSort14SortIn.DISP=SHR,KEEP,KEEP
IcemanSort14SortInRecordType=FB
IcemanSort14SortInRecordLen=200
#STEP:SORT14| PGM:ICEMAN| DD:SORTOUT
IcemanSort14SortOut=CLOUDFRM.JPM.SORT.OUTPUT14
IcemanSort14SortOut.DISP=NEW,KEEP,KEEP
IcemanSort14SortOutRecordType=FB
IcemanSort14SortOutRecordLen=200
#STEP:SORT15| PGM:ICEMAN| DD:SORTIN
IcemanSort15SortIn[0]=CLOUDFRM.JPM.SORT.INPUT151
IcemanSort15SortIn[0].DISP=SHR,KEEP,KEEP
IcemanSort15SortIn0RecordType=FB
IcemanSort15SortIn0RecordLen=200
#STEP:SORT15| PGM:ICEMAN| DD:SORTIN
IcemanSort15SortIn[1]=CLOUDFRM.JPM.SORT.INPUT152
IcemanSort15SortIn[1].DISP=SHR,KEEP,KEEP
IcemanSort15SortIn1RecordType=FB
IcemanSort15SortIn1RecordLen=200
#STEP:SORT15| PGM:ICEMAN| DD:SORTOUT
IcemanSort15SortOut=CLOUDFRM.JPM.SORT.OUTPUT15
IcemanSort15SortOut.DISP=NEW,KEEP,KEEP
IcemanSort15SortOutRecordType=FB
IcemanSort15SortOutRecordLen=200
#STEP:SORT16| PGM:ICEMAN| DD:SORTIN
IcemanSort16SortIn[0]=CLOUDFRM.JPM.SORT.INPUT161
IcemanSort16SortIn[0].DISP=SHR,KEEP,KEEP
IcemanSort16SortIn0RecordType=FB
IcemanSort16SortIn0RecordLen=200
#STEP:SORT16| PGM:ICEMAN| DD:SORTIN
IcemanSort16SortIn[1]=CLOUDFRM.JPM.SORT.INPUT162
IcemanSort16SortIn[1].DISP=SHR,KEEP,KEEP
IcemanSort16SortIn1RecordType=FB
IcemanSort16SortIn1RecordLen=200
#STEP:SORT16| PGM:ICEMAN| DD:SORTIN
IcemanSort16SortIn[2]=CLOUDFRM.JPM.SORT.INPUT163
IcemanSort16SortIn[2].DISP=SHR,KEEP,KEEP
IcemanSort16SortIn2RecordType=FB
IcemanSort16SortIn2RecordLen=200
#STEP:SORT16| PGM:ICEMAN| DD:SORTOUT
IcemanSort16SortOut=CLOUDFRM.JPM.SORT.OUTPUT16
IcemanSort16SortOut.DISP=NEW,KEEP,KEEP
IcemanSort16SortOutRecordType=FB
IcemanSort16SortOutRecordLen=200
#STEP:SORT18| PGM:ICEMAN| DD:SORTIN
IcemanSort18SortIn=CLOUDFRM.JPM.SORT.INPUT18
IcemanSort18SortIn.DISP=SHR,KEEP,KEEP
IcemanSort18SortInRecordType=FB
IcemanSort18SortInRecordLen=52
#STEP:SORT18| PGM:ICEMAN| DD:SORTOUT
IcemanSort18SortOut=CLOUDFRM.JPM.SORT.OUTPUT18
IcemanSort18SortOut.DISP=NEW,KEEP,KEEP
IcemanSort18SortOutRecordType=FB
IcemanSort18SortOutRecordLen=40
#STEP:SORT19| PGM:ICEMAN| DD:SORTIN
IcemanSort19SortIn=CLOUDFRM.JPM.SORT.INPUT19
IcemanSort19SortIn.DISP=SHR,KEEP,KEEP
IcemanSort19SortInRecordType=FB
IcemanSort19SortInRecordLen=200
#STEP:SORT19| PGM:ICEMAN| DD:SORTOUT
IcemanSort19SortOut=CLOUDFRM.JPM.SORT.OUTPUT19
IcemanSort19SortOut.DISP=NEW,KEEP,KEEP
IcemanSort19SortOutRecordType=FB
IcemanSort19SortOutRecordLen=300
#STEP:SORT20| PGM:ICEMAN| DD:SORTIN
IcemanSort20SortIn=CLOUDFRM.JPM.SORT.INPUT20
IcemanSort20SortIn.DISP=SHR,KEEP,KEEP
IcemanSort20SortInRecordType=FB
IcemanSort20SortInRecordLen=52
#STEP:SORT20| PGM:ICEMAN| DD:SORTOUT
IcemanSort20SortOut=CLOUDFRM.JPM.SORT.OUTPUT20
IcemanSort20SortOut.DISP=NEW,KEEP,KEEP
IcemanSort20SortOutRecordType=FB
IcemanSort20SortOutRecordLen=9
