timeZoneId=Etc/GMT
# Program SF320010 | DD : SYS001 | RecordFormat : VariableLength | MaxRecordLength : 32752
SF320010.ddname.SYS001=GeneralLogFileIn
SF320010.GeneralLogFileIn=GeneralLogFileIn
SF320010.GeneralLogFileInCharSet=cp1047
SF320010.GeneralLogFileInCRLFflag=no
# Program SF320010 | DD : SYS301 | RecordFormat : FixedLength | RecordLength : 397
SF320010.ddname.SYS301=TempWorkFile
SF320010.TempWorkFile=TempWorkFile
SF320010.TempWorkFileCharSet=cp1047
SF320010.TempWorkFileCRLFflag=no
# Program SF320010 | DD : SYS201 | RecordFormat : FixedLength | RecordLength : 145
SF320010.ddname.SYS201=ReportFileOut
SF320010.ReportFileOut=ReportFileOut
SF320010.ReportFileOutCharSet=cp1047
SF320010.ReportFileOutCRLFflag=no
# Program SF320010 | DD : SYS202 | RecordFormat : FixedLength | RecordLength : 80
SF320010.ddname.SYS202=InfoSecFileOut
SF320010.InfoSecFileOut=InfoSecFileOut
SF320010.InfoSecFileOutCharSet=cp1047
SF320010.InfoSecFileOutCRLFflag=no
# Program SF320010 | DD : SYS203 | RecordFormat : FixedLength | RecordLength : 145
SF320010.ddname.SYS203=Sys203EmailFileOut
SF320010.Sys203EmailFileOut=Sys203EmailFileOut
SF320010.Sys203EmailFileOutCharSet=cp1047
SF320010.Sys203EmailFileOutCRLFflag=no
# 
# End of SF320010
