  package com.cloudframe.app.process.impl;
  /* Java code generated by CloudFrame on 2025-04-28 at 08:08. */
  
  import com.cloudframe.app.dbrowset.DbrowsetCtx.*;
  import com.cloudframe.app.dbrowset.DbrowsetCtx;
  import com.cloudframe.app.process.Dbrowset;
  import com.cloudframe.app.process.BaseProcess;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.dto.GlobalExecutorCtx;
  import com.cloudframe.app.exception.Terminate;
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.beans.factory.annotation.Qualifier;
  import com.cloudframe.app.repository.DbrowsetRepository;
  import com.cloudframe.app.utility.CFUtil;
  import com.cloudframe.app.dbrowset.dto.*;
  import com.cloudframe.app.dbrowset.dto.Sqlca;
  import com.cloudframe.app.dbrowset.dto.Misc;
  import com.cloudframe.app.dbrowset.dto.SecTable;
  import com.cloudframe.app.dbrowset.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.common.SQLS;
  import org.springframework.beans.factory.annotation.Value;
  import com.cloudframe.app.dao.Db2Base;
  import java.sql.SQLException;
  
  @Component("dbrowset")
  
  public class DbrowsetImpl extends CommonProcess implements Dbrowset {
  
  Logger logger = LoggerFactory.getLogger(DbrowsetImpl.class);
  
  
  @Value("${DBROWSET.dbQualifier:}")
  private String dbQualifier;
  
  
  @Autowired 
  @Qualifier("db2Base")
  Db2Base db2Base;
  @Autowired 
  @Qualifier("dbrowsetRepository")
  DbrowsetRepository dbrowsetRepository;
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      public int process(DbrowsetCtx programCtx) throws Exception {
       try {
       setCodePage("1047");
            // Reset program ended flag
           programCtx.setProgramEnded(false);
      	db2Base.reset("DBROWSET" ,dbQualifier, true/*use Dynamic SQL*/);
          ;
//  PERFORM START-OF-PROGRAM
          startOfProgram(programCtx);/*START-OF-PROGRAM*/
          if (programCtx.isProgramEnded()) {
              return programCtx.getRc();
          }
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
        finally {
		handleDbAtEnd(db2Base); 
		clearVars(); 
      

      }
      
       return programCtx.getRc(); // Exit with return code
      // end of process method
      }
      /**
      * startOfProgram 
      *   This method is derived from 
  *   COBOL Paragraph - START-OF-PROGRAM COBOL Cyclomatic complexity - 2
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      @Override
      public void startOfProgram(DbrowsetCtx programCtx) throws Exception {
//  PERFORM 0000-INITIALIZE THRU 0000-EXIT
          initialize(programCtx);/*0000-INITIALIZE*/
          if (programCtx.isProgramEnded()) {
              return ;
          }
//  PERFORM 1000-FETCH-ROWS THRU 1000-EXIT
          fetchRows(programCtx.getFetchRowsInCtx());/*1000-FETCH-ROWS*/
          if (programCtx.isProgramEnded()) {
              return ;
          }
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          programCtx.setProgramEnded(true);
          return ;
      
      }
      /**
      * initialize 
      *   This method is derived from 
  *   COBOL Paragraph - 0000-INITIALIZE COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output :  

      * - maxRows                        COBOL Name: WS-MAX-ROWS
      *
      * @throws CFException
      */
      @Override
      public InitializeOutCtx initialize(DbrowsetCtx programCtx) throws Exception {
InitializeOutCtx methodOut = programCtx.getInitializeOutCtx();

// *

// *
          // MOVE 20 TO WS-MAX-ROWS
          methodOut.setMaxRows(20);
          ;
      
      return methodOut;
      }
      /**
      * fetchRows 
      *   This method is derived from 
  *   COBOL Paragraph - 1000-FETCH-ROWS COBOL Cyclomatic complexity - 13
      * Input  :  

      * - sqlcode                        COBOL Name: SQLCODE
      * - ix                             COBOL Name: IX
      * - maxRows                        COBOL Name: WS-MAX-ROWS
      * - isin                           COBOL Name: WS-ISIN
      * - sedol                          COBOL Name: WS-SEDOL
      * - ric                            COBOL Name: WS-RIC
      *
      * Output :  

      * - sqlcode_Ws                     COBOL Name: WS-SQLCODE
      * - sqlcode                        COBOL Name: SQLCODE
      * - ix                             COBOL Name: IX
      *
      * @throws CFException
      */
      @Override
      public FetchRowsOutCtx fetchRows(FetchRowsInCtx methodIn) throws Exception {
DbrowsetCtx programCtx = methodIn.getDbrowsetCtx();
FetchRowsOutCtx methodOut = methodIn.getFetchRowsOutCtx();
//  SELECT ISIN , SEDOL , RIC FROM TBDEMSEC ORDER BY ISIN ASC
          programCtx.setSecCursorResultSet(dbrowsetRepository.openSecCursorDbrowset(programCtx.getSqlca()));
//  IF SQLCODE = 0 THEN
//  ELSE
          if (	( methodOut.getSqlcode() != 0 )) { 
              // MOVE SQLCODE TO WS-SQLCODE
              //  FORMAT1016704244 = "-999"
              methodOut.setSqlcode_Ws(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT1016704244,String.valueOf(methodOut.getSqlcode()).toCharArray()));
//  DISPLAY 'OPEN SEC_CURSOR FAILED : SQLCODE = ' WS-SQLCODE
              logger.info("OPEN SEC_CURSOR FAILED : SQLCODE = {}", new String(methodOut.getSqlcode_Ws())); 
//  GOBACK
              setNotLogged(false); // no need to log, it is a normal termination
              programCtx.setProgramEnded(true);
              return methodOut;
          }

// *
//  PERFORM 3 TIMES
          for (int index0 = 0; index0 < 3;index0++) {
//  FETCH NEXT ROWSET FROM SEC_CURSOR FOR ? ROWS INTO ? , ? , ?
              dbrowsetRepository.fetchSecCursorDbrowset(programCtx.getSecCursorResultSet(),programCtx.getSqlca(),methodOut.getSecTable(),methodIn.getMisc());
//  IF SQLCODE = 0 THEN
              if (	( methodOut.getSqlcode() == 0 )) { 
//  PERFORM VARYING IX FROM 1 BY 1 UNTIL IX > WS-MAX-ROWS
                  for (methodOut.setIx(1); (	( methodOut.getIx() <= methodIn.getMaxRows() ) ) ; methodOut.setIx(methodOut.getIx() + 1) ) {
//  DISPLAY WS-ISIN (IX) ' ** ' WS-SEDOL (IX) ' ** ' WS-RIC (IX)
                      logger.info("{} ** {} ** {}", new String(methodIn.getIsin(methodOut.getIx() - 1)), new String(methodIn.getSedol(methodOut.getIx() - 1)), new String(methodIn.getRic(methodOut.getIx() - 1))); 
                  }
              }
//  ELSE
              else { 
                  // MOVE SQLCODE TO WS-SQLCODE
                  //  FORMAT1016704244 = "-999"
                  methodOut.setSqlcode_Ws(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT1016704244,String.valueOf(methodOut.getSqlcode()).toCharArray()));
//  DISPLAY 'FETCH SEC_CURSOR FAILED : SQLCODE = ' WS-SQLCODE
                  logger.info("FETCH SEC_CURSOR FAILED : SQLCODE = {}", new String(methodOut.getSqlcode_Ws())); 
//  GOBACK
                  setNotLogged(false); // no need to log, it is a normal termination
                  programCtx.setProgramEnded(true);
                  return methodOut;
              }
          }
//  CLOSE SEC_CURSOR
          dbrowsetRepository.closeSecCursorDbrowset(programCtx.getSecCursorResultSet(),programCtx.getSqlca());
//  IF SQLCODE = 0 THEN
//  ELSE
          if (	( methodOut.getSqlcode() != 0 )) { 
              // MOVE SQLCODE TO WS-SQLCODE
              //  FORMAT1016704244 = "-999"
              methodOut.setSqlcode_Ws(CFUtil.cobolNumberFormatter(CONSTANTS.FORMAT1016704244,String.valueOf(methodOut.getSqlcode()).toCharArray()));
//  DISPLAY 'OPEN SEC_CURSOR FAILED : SQLCODE = ' WS-SQLCODE
              logger.info("OPEN SEC_CURSOR FAILED : SQLCODE = {}", new String(methodOut.getSqlcode_Ws())); 
//  GOBACK
              setNotLogged(false); // no need to log, it is a normal termination
              programCtx.setProgramEnded(true);
              return methodOut;
          }
          ;
      
      return methodOut;
      }
  
  
  
  
  
  
  
  
  }
