#Common db properties
spring.datasource.initialization-mode=embedded
spring.jpa.hibernate.ddl-auto=update
spring.jdbc.template.fetch-size=1000
spring.datasource.maximum-pool-size=50
#spring.datasource.autocommit=false
#database specific properties
spring.database.enabled=true
spring.datasource.jdbc-url=jdbc:db2://sysh.cloudframe.com:5040/DALLASC:currentSchema=UHG;dateFormat=1;timeFormat=1;timestampFormat=1;timestampPrecisionReporting=2;
spring.datasource.driverClassName=com.ibm.db2.jcc.DB2Driver
spring.datasource.username=qauser
spring.datasource.password=cloud04
cf.sqlMetaDataLookup.enabled=false
#end of database properties
