<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.7</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.cloudframe</groupId>
	<artifactId>IDCPRN06</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>IDCPRN06</name>
	<description>CloudFrame Spring batch generated Code</description>
	
	<properties>
		<java.version>17</java.version>
		<project.build.sourceEncoding>Cp1252</project.build.sourceEncoding>
		<skipJavaDoc>true</skipJavaDoc>
		<skipJunitTests>true</skipJunitTests>
       <log4j2.version>2.24.1</log4j2.version>
	</properties>
	
	<dependencies>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-batch</artifactId>
		</dependency>
		
		<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
		<dependency>
            <groupId>com.cloudframe</groupId>
            <artifactId>dcio</artifactId>
            <version>5.0.0.21</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/cf-lib/CFDataConnectIO.jar</systemPath>
        </dependency>
<dependency>
	<groupId>com.cloudframe</groupId>
	<artifactId>dcio.plus</artifactId>
	<version>dummy-ioversion</version>
	<scope>system</scope>
	<systemPath>${project.basedir}/cf-lib/CFDataConnectIOPlus.jar</systemPath>
</dependency>
	</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
				       <includeSystemScope>true</includeSystemScope>
				</configuration>
			</plugin>
		</plugins>
	</build>
	
</project>
