# Program VSAMMON9 | DD : MONITOR | VSAM KSDS
VSAMMON9.ddname.MONITOR=Monitor
# Program VSAMMON9 | DD : REPOUT | RecordFormat : FixedLength | RecordLength : 300
VSAMMON9.ddname.REPOUT=Repout
VSAMMON9.Repout=Repout
VSAMMON9.RepoutCharSet=cp1047
VSAMMON9.RepoutCRLFflag=no
# 
# End of VSAMMON9
