<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="AdditionalSyntaxChecksGroup100" cobol:name="100-ADDITIONAL-SYNTAX-CHECKS-GROUP" cobol:offset="0" cobol:length="1" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="AdditionalSyntaxChecks100" maxOccurs="1"  cobol:name="100-ADDITIONAL-SYNTAX-CHECKS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 noAdditionalChecks88100 VALUE [["0"], ["1"], ["M"]].
                        88 leftJustifyNotSpace88100 VALUE [["2"]].
                        88 notLowHighValue88100 VALUE [["3"]].
                        88 numericNotZero88100 VALUE [["4"]].
                        88 allZeroes88100 VALUE [["5"]].
                        88 notSpacesZerosAlpha88100 VALUE [["6"]].
                        88 notAllSpaces88100 VALUE [["7"]].
                        88 dateOrDayZeros88100 VALUE [["8"]].
                        88 julianDateYddd88100 VALUE [["9"]].
                        88 validHhMm88100 VALUE [["A"]].
                        88 validHh88100 VALUE [["B"]].
                        88 validMmss88100 VALUE [["C"]].
                        88 notSpacesZerosNine88100 VALUE [["D"]].
                        88 notSpacesOrZeros88100 VALUE [["E"]].
                        88 validYymm88100 VALUE [["F"]].
                        88 alphnumSpaceDash88100 VALUE [["G"]].
                        88 maxLengthDivisible88100 VALUE [["H"]].
                        88 leftJustifyCanSpace88100 VALUE [["I"]].
                        88 noLhBasicPresence88100 VALUE [["J"]].
                        88 noZeroBasicPresence88100 VALUE [["K"]].
                        88 leftJustifyNoBasic88100 VALUE [["L"]].
                        88 alpnumDasNtAlSpc88100 VALUE [["M"]].
                        88 alpnumNotSpaceZero88100 VALUE [["N"]].
                        88 leftJustifyNoSpcZer88100 VALUE [["O"]].
                        88 alphanumericSpace88100 VALUE [["P"]].
                        88 mustBeAllSpaces88100 VALUE [["Q"]].
                        88 mustBeAllZeroes88100 VALUE [["R"]].
                        88 leftJustNoSpcNum88100 VALUE [["S"]].
                        88 numericAllSpace88100 VALUE [["T"]].
                        88 leadSpaceLjAllZeros88100 VALUE [["U"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
