<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip65504PdsNamesLargeGroup36" cobol:name="IP65504-PDS-NAMES-LARGE-GROUP-36" cobol:offset="8676" cobol:length="248" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip65504P1086MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1086-MEMDATA-S" cobol:offset="4" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1086MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1086-MEMDATA-L" cobol:offset="6" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1086" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="8" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1087MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1087-MEMDATA-S" cobol:offset="12" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1087MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1087-MEMDATA-L" cobol:offset="14" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1087" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="16" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1088MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1088-MEMDATA-S" cobol:offset="20" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1088MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1088-MEMDATA-L" cobol:offset="22" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1088" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="24" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1089MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1089-MEMDATA-S" cobol:offset="28" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1089MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1089-MEMDATA-L" cobol:offset="30" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1089" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="32" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1090MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1090-MEMDATA-S" cobol:offset="36" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1090MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1090-MEMDATA-L" cobol:offset="38" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1090" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="40" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1091MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1091-MEMDATA-S" cobol:offset="44" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1091MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1091-MEMDATA-L" cobol:offset="46" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1091" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="48" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1092MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1092-MEMDATA-S" cobol:offset="52" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1092MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1092-MEMDATA-L" cobol:offset="54" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1092" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="56" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1093MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1093-MEMDATA-S" cobol:offset="60" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1093MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1093-MEMDATA-L" cobol:offset="62" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1093" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="64" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1094MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1094-MEMDATA-S" cobol:offset="68" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1094MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1094-MEMDATA-L" cobol:offset="70" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1094" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="72" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1095MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1095-MEMDATA-S" cobol:offset="76" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1095MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1095-MEMDATA-L" cobol:offset="78" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1095" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="80" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1096MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1096-MEMDATA-S" cobol:offset="84" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1096MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1096-MEMDATA-L" cobol:offset="86" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1096" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="88" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1097MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1097-MEMDATA-S" cobol:offset="92" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1097MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1097-MEMDATA-L" cobol:offset="94" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1097" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="96" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1098MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1098-MEMDATA-S" cobol:offset="100" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1098MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1098-MEMDATA-L" cobol:offset="102" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1098" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="104" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1099MemdataS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1099-MEMDATA-S" cobol:offset="108" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1099MemdataL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1099-MEMDATA-L" cobol:offset="110" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1099" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="112" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1100S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1100-S" cobol:offset="116" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1100L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1100-L" cobol:offset="118" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1100" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="120" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1101S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1101-S" cobol:offset="124" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1101L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1101-L" cobol:offset="126" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1101" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="128" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1102S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1102-S" cobol:offset="132" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1102L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1102-L" cobol:offset="134" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1102" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="136" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1103S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1103-S" cobol:offset="140" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1103L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1103-L" cobol:offset="142" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1103" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="144" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1104S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1104-S" cobol:offset="148" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1104L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1104-L" cobol:offset="150" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1104" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="152" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1105S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1105-S" cobol:offset="156" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1105L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1105-L" cobol:offset="158" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1105" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="160" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1106S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1106-S" cobol:offset="164" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1106L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1106-L" cobol:offset="166" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1106" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="168" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1107S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1107-S" cobol:offset="172" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1107L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1107-L" cobol:offset="174" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1107" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="176" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1108S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1108-S" cobol:offset="180" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1108L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1108-L" cobol:offset="182" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1108" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="184" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1109S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1109-S" cobol:offset="188" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1109L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1109-L" cobol:offset="190" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1109" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="192" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1110S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1110-S" cobol:offset="196" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1110L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1110-L" cobol:offset="198" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1110" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="200" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1111S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1111-S" cobol:offset="204" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1111L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1111-L" cobol:offset="206" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1111" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="208" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1112S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1112-S" cobol:offset="212" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1112L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1112-L" cobol:offset="214" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1112" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="216" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1113S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1113-S" cobol:offset="220" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1113L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1113-L" cobol:offset="222" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1113" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="224" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1114S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1114-S" cobol:offset="228" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1114L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1114-L" cobol:offset="230" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1114" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="232" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1115S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1115-S" cobol:offset="236" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1115L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1115-L" cobol:offset="238" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1115" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="240" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1116S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1116-S" cobol:offset="244" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P1116L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P1116-L" cobol:offset="246" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller1116" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="248" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
