<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip65504PdsNamesLargeGroup23" cobol:name="IP65504-PDS-NAMES-LARGE-GROUP-23" cobol:offset="5452" cobol:length="248" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip65504P683TaxAmount4S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P683-TAX-AMOUNT4-S" cobol:offset="4" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P683TaxAmount4L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P683-TAX-AMOUNT4-L" cobol:offset="6" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller683" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="8" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P684TaxAmount5S" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P684-TAX-AMOUNT5-S" cobol:offset="12" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P684TaxAmount5L" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P684-TAX-AMOUNT5-L" cobol:offset="14" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller684" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="16" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P685TypeOfSupplyS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P685-TYPE-OF-SUPPLY-S" cobol:offset="20" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P685TypeOfSupplyL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P685-TYPE-OF-SUPPLY-L" cobol:offset="22" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller685" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="24" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P686TaxExmptIndS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P686-TAX-EXMPT-IND-S" cobol:offset="28" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P686TaxExmptIndL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P686-TAX-EXMPT-IND-L" cobol:offset="30" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller686" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="32" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P687UnqvatInvrfnoS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P687-UNQVAT-INVRFNO-S" cobol:offset="36" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P687UnqvatInvrfnoL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P687-UNQVAT-INVRFNO-L" cobol:offset="38" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller687" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="40" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P688ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P688-RESERVD-S" cobol:offset="44" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P688ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P688-RESERVD-L" cobol:offset="46" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller688" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="48" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P689CorpIdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P689-CORP-ID-S" cobol:offset="52" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P689CorpIdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P689-CORP-ID-L" cobol:offset="54" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller689" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="56" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P690NoShowIndS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P690-NO-SHOW-IND-S" cobol:offset="60" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P690NoShowIndL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P690-NO-SHOW-IND-L" cobol:offset="62" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller690" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="64" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P691DaysRentedS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P691-DAYS-RENTED-S" cobol:offset="68" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P691DaysRentedL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P691-DAYS-RENTED-L" cobol:offset="70" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller691" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="72" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P692WeekRentAmtS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P692-WEEK-RENT-AMT-S" cobol:offset="76" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P692WeekRentAmtL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P692-WEEK-RENT-AMT-L" cobol:offset="78" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller692" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="80" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P693TotAuthAmtS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P693-TOT-AUTH-AMT-S" cobol:offset="84" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P693TotAuthAmtL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P693-TOT-AUTH-AMT-L" cobol:offset="86" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller693" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="88" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P6941waydropChrgeS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P694-1WAYDROP-CHRGE-S" cobol:offset="92" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P6941waydropChrgeL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P694-1WAYDROP-CHRGE-L" cobol:offset="94" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller694" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="96" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P695RegMileChrgeS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P695-REG-MILE-CHRGE-S" cobol:offset="100" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P695RegMileChrgeL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P695-REG-MILE-CHRGE-L" cobol:offset="102" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller695" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="104" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P696ExtMileChrgeS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P696-EXT-MILE-CHRGE-S" cobol:offset="108" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P696ExtMileChrgeL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P696-EXT-MILE-CHRGE-L" cobol:offset="110" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller696" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="112" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P697LateChrgeS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P697-LATE-CHRGE-S" cobol:offset="116" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P697LateChrgeL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P697-LATE-CHRGE-L" cobol:offset="118" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller697" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="120" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P698FuelChrgeS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P698-FUEL-CHRGE-S" cobol:offset="124" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P698FuelChrgeL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P698-FUEL-CHRGE-L" cobol:offset="126" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller698" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="128" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P699TotTaxAmtS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P699-TOT-TAX-AMT-S" cobol:offset="132" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P699TotTaxAmtL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P699-TOT-TAX-AMT-L" cobol:offset="134" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller699" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="136" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P700TowingChrgeS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P700-TOWING-CHRGE-S" cobol:offset="140" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P700TowingChrgeL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P700-TOWING-CHRGE-L" cobol:offset="142" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller700" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="144" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P701ExtraChrgeS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P701-EXTRA-CHRGE-S" cobol:offset="148" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P701ExtraChrgeL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P701-EXTRA-CHRGE-L" cobol:offset="150" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller701" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="152" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P702OtherChrgeS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P702-OTHER-CHRGE-S" cobol:offset="156" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P702OtherChrgeL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P702-OTHER-CHRGE-L" cobol:offset="158" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller702" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="160" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P703TotRoomNightS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P703-TOT-ROOM-NIGHT-S" cobol:offset="164" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P703TotRoomNightL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P703-TOT-ROOM-NIGHT-L" cobol:offset="166" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller703" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="168" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P704PrepaidExpnseS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P704-PREPAID-EXPNSE-S" cobol:offset="172" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P704PrepaidExpnseL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P704-PREPAID-EXPNSE-L" cobol:offset="174" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller704" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="176" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P705TotroomTaxamtS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P705-TOTROOM-TAXAMT-S" cobol:offset="180" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P705TotroomTaxamtL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P705-TOTROOM-TAXAMT-L" cobol:offset="182" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller705" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="184" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P706CashAdvanceS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P706-CASH-ADVANCE-S" cobol:offset="188" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P706CashAdvanceL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P706-CASH-ADVANCE-L" cobol:offset="190" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller706" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="192" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P707ValetChrgeS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P707-VALET-CHRGE-S" cobol:offset="196" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P707ValetChrgeL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P707-VALET-CHRGE-L" cobol:offset="198" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller707" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="200" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P708MovieChrgeS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P708-MOVIE-CHRGE-S" cobol:offset="204" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P708MovieChrgeL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P708-MOVIE-CHRGE-L" cobol:offset="206" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller708" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="208" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P709BsnsCntrChrgS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P709-BSNS-CNTR-CHRG-S" cobol:offset="212" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P709BsnsCntrChrgL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P709-BSNS-CNTR-CHRG-L" cobol:offset="214" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller709" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="216" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P710HelthclubChrgS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P710-HELTHCLUB-CHRG-S" cobol:offset="220" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P710HelthclubChrgL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P710-HELTHCLUB-CHRG-L" cobol:offset="222" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller710" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="224" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P711FireSfactIndS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P711-FIRE-SFACT-IND-S" cobol:offset="228" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P711FireSfactIndL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P711-FIRE-SFACT-IND-L" cobol:offset="230" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller711" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="232" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P712NetFuelPriceS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P712-NET-FUEL-PRICE-S" cobol:offset="236" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P712NetFuelPriceL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P712-NET-FUEL-PRICE-L" cobol:offset="238" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller712" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="240" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P713RestrctTktindS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P713-RESTRCT-TKTIND-S" cobol:offset="244" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P713RestrctTktindL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P713-RESTRCT-TKTIND-L" cobol:offset="246" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller713" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="248" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
