<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip65504PdsNamesLargeGroup5" cobol:name="IP65504-PDS-NAMES-LARGE-GROUP-5" cobol:offset="988" cobol:length="248" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip65504P125ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P125-RESERVD-S" cobol:offset="4" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P125ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P125-RESERVD-L" cobol:offset="6" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller125" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="8" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P126ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P126-RESERVD-S" cobol:offset="12" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P126ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P126-RESERVD-L" cobol:offset="14" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller126" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="16" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P127ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P127-RESERVD-S" cobol:offset="20" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P127ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P127-RESERVD-L" cobol:offset="22" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller127" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="24" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P128ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P128-RESERVD-S" cobol:offset="28" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P128ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P128-RESERVD-L" cobol:offset="30" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller128" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="32" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P129ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P129-RESERVD-S" cobol:offset="36" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P129ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P129-RESERVD-L" cobol:offset="38" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller129" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="40" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P130ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P130-RESERVD-S" cobol:offset="44" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P130ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P130-RESERVD-L" cobol:offset="46" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller130" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="48" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P131ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P131-RESERVD-S" cobol:offset="52" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P131ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P131-RESERVD-L" cobol:offset="54" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller131" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="56" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P132ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P132-RESERVD-S" cobol:offset="60" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P132ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P132-RESERVD-L" cobol:offset="62" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller132" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="64" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P133ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P133-RESERVD-S" cobol:offset="68" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P133ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P133-RESERVD-L" cobol:offset="70" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller133" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="72" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P134ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P134-RESERVD-S" cobol:offset="76" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P134ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P134-RESERVD-L" cobol:offset="78" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller134" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="80" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P135FlrejreS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P135-FLREJRE-S" cobol:offset="84" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P135FlrejreL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P135-FLREJRE-L" cobol:offset="86" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller135" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="88" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P136ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P136-RESERVD-S" cobol:offset="92" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P136ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P136-RESERVD-L" cobol:offset="94" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller136" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="96" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P137FeeCtlS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P137-FEE-CTL-S" cobol:offset="100" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P137FeeCtlL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P137-FEE-CTL-L" cobol:offset="102" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller137" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="104" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P138SrcMsgS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P138-SRC-MSG-S" cobol:offset="108" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P138SrcMsgL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P138-SRC-MSG-L" cobol:offset="110" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller138" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="112" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P139ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P139-RESERVD-S" cobol:offset="116" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P139ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P139-RESERVD-L" cobol:offset="118" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller139" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="120" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P140ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P140-RESERVD-S" cobol:offset="124" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P140ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P140-RESERVD-L" cobol:offset="126" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller140" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="128" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P141ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P141-RESERVD-S" cobol:offset="132" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P141ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P141-RESERVD-L" cobol:offset="134" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller141" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="136" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P142ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P142-RESERVD-S" cobol:offset="140" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P142ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P142-RESERVD-L" cobol:offset="142" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller142" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="144" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P143ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P143-RESERVD-S" cobol:offset="148" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P143ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P143-RESERVD-L" cobol:offset="150" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller143" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="152" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P144ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P144-RESERVD-S" cobol:offset="156" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P144ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P144-RESERVD-L" cobol:offset="158" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller144" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="160" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P145ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P145-RESERVD-S" cobol:offset="164" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P145ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P145-RESERVD-L" cobol:offset="166" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller145" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="168" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P146TrxAmtS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P146-TRX-AMT-S" cobol:offset="172" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P146TrxAmtL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P146-TRX-AMT-L" cobol:offset="174" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller146" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="176" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P147OrgAmtS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P147-ORG-AMT-S" cobol:offset="180" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P147OrgAmtL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P147-ORG-AMT-L" cobol:offset="182" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller147" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="184" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P148CurExpS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P148-CUR-EXP-S" cobol:offset="188" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P148CurExpL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P148-CUR-EXP-L" cobol:offset="190" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller148" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="192" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P149CurCdsS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P149-CUR-CDS-S" cobol:offset="196" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P149CurCdsL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P149-CUR-CDS-L" cobol:offset="198" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller149" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="200" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P150ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P150-RESERVD-S" cobol:offset="204" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P150ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P150-RESERVD-L" cobol:offset="206" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller150" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="208" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P151ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P151-RESERVD-S" cobol:offset="212" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P151ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P151-RESERVD-L" cobol:offset="214" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller151" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="216" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P152ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P152-RESERVD-S" cobol:offset="220" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P152ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P152-RESERVD-L" cobol:offset="222" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller152" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="224" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P153ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P153-RESERVD-S" cobol:offset="228" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P153ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P153-RESERVD-L" cobol:offset="230" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller153" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="232" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P154ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P154-RESERVD-S" cobol:offset="236" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P154ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P154-RESERVD-L" cobol:offset="238" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller154" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="240" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P155ReservdS" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P155-RESERVD-S" cobol:offset="244" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504P155ReservdL" type="xs:short" maxOccurs="1"  cobol:name="IP65504-P155-RESERVD-L" cobol:offset="246" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ip65504PdsMapGroupFiller155" type="xs:int" maxOccurs="1"  cobol:name="FILLER" cobol:offset="248" cobol:length="4" cobol:datatype="Index" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
