<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip90134TableEntry" cobol:name="IP90134-TABLE-ENTRY" cobol:offset="0" cobol:length="21" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="Ip90134EditGroupKey" maxOccurs="1" cobol:name="IP90134-EDIT-GROUP-KEY" cobol:offset="0" cobol:length="15" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="Ip90134PositionStart" type="xs:int" maxOccurs="1"  cobol:name="IP90134-POSITION-START" cobol:offset="15" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="Ip90134PositionEnd" type="xs:int" maxOccurs="1"  cobol:name="IP90134-POSITION-END" cobol:offset="18" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
