  package com.cloudframe.app.process.impl;
  /* Java code generated by CloudFrame on 2025-04-24 at 16:34. */
  
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.beans.factory.annotation.Qualifier;
  import com.cloudframe.app.vsammon1.file.*;
  import com.cloudframe.app.vsammon1.Vsammon1Ctx.*;
  import com.cloudframe.app.vsammon1.Vsammon1Ctx;
  import com.cloudframe.app.process.Vsammon1;
  import com.cloudframe.app.process.BaseProcess;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.dto.GlobalExecutorCtx;
  import com.cloudframe.app.vsammon1.file.Scanner;
  import com.cloudframe.app.exception.Terminate;
  import java.util.ArrayList;
  import com.cloudframe.app.data.Field;
  import java.util.Map;
  import java.util.HashMap;
  import com.cloudframe.app.utility.CFConstants;
  import com.cloudframe.app.vsammon1.dto.*;
  import com.cloudframe.app.vsammon1.dto.MonitorFileStatus;
  import com.cloudframe.app.vsammon1.file.records.MonitorRecord;
  import com.cloudframe.app.vsammon1.file.records.Reprec;
  import com.cloudframe.app.vsammon1.dto.AcceptInputGroup;
  import com.cloudframe.app.vsammon1.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("vsammon1")
  
  public class Vsammon1Impl extends CommonProcess implements Vsammon1 {
  
  Logger logger = LoggerFactory.getLogger(Vsammon1Impl.class);
  
  
  
  
  @Autowired 
  @Qualifier("vsammon1_monitor")
  Monitor monitor;
  @Autowired 
  @Qualifier("vsammon1_repout")
  Repout repout;
  
  
  
  
    @Autowired
    @Qualifier("vsammon1_scanner")
    Scanner scanner;
  
  
  
      /**
      * process 
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      public int process(Vsammon1Ctx programCtx) throws Exception {
       try {
       setCodePage("1047");
            // Reset program ended flag
           programCtx.setProgramEnded(false);
          ;
//  PERFORM 0000-MAINLINE
          mainline(programCtx);/*0000-MAINLINE*/
          if (programCtx.isProgramEnded()) {
              return programCtx.getRc();
          }
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
        finally {
      		if(monitor.hasOpened() && !monitor.isReadOnly()) { 
      			monitor.flush(); 
      		}
      		if(repout.hasOpened() && !repout.isReadOnly()) { 
      			repout.flush(); 
      		}
      		if(scanner.hasOpened()) { 
      			scanner.close();
      		}
      }
      
       return programCtx.getRc(); // Exit with return code
      // end of process method
      }
      /**
      * mainline 
      *   This method is derived from 
  *   COBOL Paragraph - 0000-MAINLINE COBOL Cyclomatic complexity - 12
      * Input  : None 

      * Output :  

      * - input                          COBOL Name: WS-INPUT
      * - inputCommand                   COBOL Name: WS-INPUT-COMMAND
      * - acceptInput                    COBOL Name: WS-ACCEPT-INPUT
      *
      * @throws CFException
      */
      @Override
      public MainlineOutCtx mainline(Vsammon1Ctx programCtx) throws Exception {
			// Declare local variables used in the method
			char[] consoleInput = null;
			// End of variable declaration

MainlineOutCtx methodOut = programCtx.getMainlineOutCtx();
//  PERFORM 0010-OPEN-FILES THRU 0010-EXIT
          openFiles(programCtx.getOpenFilesInCtx());/*0010-OPEN-FILES*/
          if (programCtx.isProgramEnded()) {
              return methodOut;
          }
//  MOVE SPACES TO WS-INPUT
          methodOut.setInput(CONSTANTS.SPACE_80);
//  PERFORM UNTIL C-TERMINATE
          while ((!(methodOut.isCTerminate()) )) {
//  ACCEPT WS-ACCEPT-INPUT
              consoleInput = scanner.nextLine();
              if (!scanner.hasEnded()) {
                 methodOut.setAcceptInput(consoleInput);  // read from console and assign
              }
//  EVALUATE TRUE
              if  ( methodOut.isCMethod()  ) { 
//  PERFORM 1000-METHOD-BASED-REPORT THRU 1000-EXIT
                  methodBasedReport(programCtx.getMethodBasedReportInCtx());/*1000-METHOD-BASED-REPORT*/
                  if (programCtx.isProgramEnded()) {
                      return methodOut;
                  }
              }
              else if  ( methodOut.isCProgram()  ) { 
//  PERFORM 2000-PROGRAM-BASED-REPORT THRU 2000-EXIT
                  programBasedReport(programCtx.getProgramBasedReportInCtx());/*2000-PROGRAM-BASED-REPORT*/
                  if (programCtx.isProgramEnded()) {
                      return methodOut;
                  }
              }
              else if  ( methodOut.isCProgram1()  ) { 
//  PERFORM 2001-PROGRAM-BASED-REPORT THRU 2001-EXIT
                  programBasedReport2001(programCtx.getProgramBasedReport2001InCtx());/*2001-PROGRAM-BASED-REPORT*/
                  if (programCtx.isProgramEnded()) {
                      return methodOut;
                  }
              }
              else if  ( methodOut.isCIpaddr()  ) { 
//  PERFORM 3000-IPADDR-BASED-REPORT THRU 3000-EXIT
                  ipaddrBasedReport(programCtx.getIpaddrBasedReportInCtx());/*3000-IPADDR-BASED-REPORT*/
                  if (programCtx.isProgramEnded()) {
                      return methodOut;
                  }
              }
              else if  ( methodOut.isCKeyread()  ) { 
//  PERFORM 4000-KEYREAD-BASED-REPORT THRU 4000-EXIT
                  keyreadBasedReport(programCtx.getKeyreadBasedReportInCtx());/*4000-KEYREAD-BASED-REPORT*/
                  if (programCtx.isProgramEnded()) {
                      return methodOut;
                  }
              }
              else if  ( methodOut.isCKeyreadn()  ) { 
//  PERFORM 4001-KEYREADN-BASED-REPORT THRU 4001-EXIT
                  keyreadnBasedReport(programCtx.getKeyreadnBasedReportInCtx());/*4001-KEYREADN-BASED-REPORT*/
                  if (programCtx.isProgramEnded()) {
                      return methodOut;
                  }
              }
              else if  ( methodOut.isCInsert()  ) { 
//  PERFORM 5000-INSERT-BASED-REPORT THRU 5000-EXIT
                  insertBasedReport(programCtx.getInsertBasedReportInCtx());/*5000-INSERT-BASED-REPORT*/
                  if (programCtx.isProgramEnded()) {
                      return methodOut;
                  }
              }
              else if  ( methodOut.isCDelete()  ) { 
//  PERFORM 6000-DELETE-BASED-REPORT THRU 6000-EXIT
                  deleteBasedReport(programCtx.getDeleteBasedReportInCtx());/*6000-DELETE-BASED-REPORT*/
                  if (programCtx.isProgramEnded()) {
                      return methodOut;
                  }
              }
              else   { 
                  ;
              }
          }
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          programCtx.setProgramEnded(true);
          return methodOut;
      
      }
      /**
      * openFiles 
      *   This method is derived from 
  *   COBOL Paragraph - 0010-OPEN-FILES COBOL Cyclomatic complexity - 3
      * Input  : None 

      * Output :  

      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      * - reprec                         COBOL Name: REPREC
      *
      * @throws CFException
      */
      @Override
      public OpenFilesOutCtx openFiles(OpenFilesInCtx methodIn) throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			Map<String,Object> updated = null;
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
Vsammon1Ctx programCtx = methodIn.getVsammon1Ctx();
OpenFilesOutCtx methodOut = methodIn.getOpenFilesOutCtx();
//  OPEN OUTPUT REPOUT
          repout.open(new String(CONSTANTS.MODE_WRITE_ONLY_36397),repout.getFileName(),repout.getRepoutCharSet(),repout.getRepoutCrlfFlag());
//  OPEN I-O MONITOR
          	monitor.setVsamCluster("VSAMMON1" /*program name*/);
          monitor.open("rw"); 
          methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
//  IF MONITOR-FILE-STATUS NOT = '00'
//  LITERAL_00 = '00'
          if (		compareChars(methodOut.getMonitorFileStatus(),CONSTANTS.LITERAL_00) != 0 ) { 
//  MOVE SPACES TO REPREC
              methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Error opening Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B3_openingMonitor_CL_);
                 charArray.add(methodOut.getMonitorFileStatus().toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
              methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 9999-EXIT-PROGRAM
exitProgram(programCtx);
 return methodOut;
//cobolCodeEnds::GO TO 9999-EXIT-PROGRAM
          }
          ;
      
      return methodOut;
      }
      /**
      * closeFiles 
      *   This method is derived from 
  *   COBOL Paragraph - 0020-CLOSE-FILES COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      @Override
      public CloseFilesOutCtx closeFiles(Vsammon1Ctx programCtx) throws Exception {
      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
CloseFilesOutCtx methodOut = programCtx.getCloseFilesOutCtx();
//  CLOSE MONITOR
          monitor.close(); 
          methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
//  CLOSE REPOUT
          repout.close(); 
          ;
      
      return methodOut;
      }
      /**
      * methodBasedReport 
      *   This method is derived from 
  *   COBOL Paragraph - 1000-METHOD-BASED-REPORT COBOL Cyclomatic complexity - 8
      * Input  :  

      * - iMethod                        COBOL Name: WS-I-METHOD
      * - staInStat1                     COBOL Name: STA-IN-STAT1
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      *
      * Output :  

      * - eofSw                          COBOL Name: WS-EOF-SW
      * - reprec                         COBOL Name: REPREC
      * - monXcdtMthdNm                  COBOL Name: MON-XCDT-MTHD-NM
      * - iMethod                        COBOL Name: WS-I-METHOD
      * - monitorRecord                  COBOL Name: MONITOR-RECORD
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      * - monPriKey                      COBOL Name: MON-PRI-KEY
      *
      * @throws CFException
      */
      @Override
      public MethodBasedReportOutCtx methodBasedReport(MethodBasedReportInCtx methodIn) throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			Map<String,Object> updated = null;
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
Vsammon1Ctx programCtx = methodIn.getVsammon1Ctx();
MethodBasedReportOutCtx methodOut = methodIn.getMethodBasedReportOutCtx();
//  MOVE SPACES TO WS-EOF-SW
          methodOut.setEofSw(CONSTANTS.SPACE);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Extracting all Monitor rows matching Method Name = ' WS-I-METHOD DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_1076917621);
             charArray.add(methodOut.getIMethod());
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
          updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
          methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE WS-I-METHOD TO MON-XCDT-MTHD-NM
          methodOut.setMonXcdtMthdNm(methodOut.getIMethod());
//  START MONITOR KEY IS EQUAL TO MON-XCDT-MTHD-NM
          monitor.seek(methodOut.getMonitorRecord().toCharArray(),CFConstants.CONDITION_EQUAL,monitor.getKeyInfo().getMonXcdtMthdNm()); 
          methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
//  IF STA-IN-STAT1 > '1'
//  LITERAL_1 = '1'
          if (		compareChars(methodIn.getStaInStat1(),CONSTANTS.LITERAL_1) > 0 ) { 
//  MOVE SPACES TO REPREC
              methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Error strting Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B3_strtingMonitor_CL_);
                 charArray.add(methodOut.getMonitorFileStatus().toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
              methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 1000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 1000-EXIT
          }
//  PERFORM UNTIL END-OF-MONITOR
          while ((!(methodOut.isEndOfMonitor()) )) {
//  READ MONITOR NEXT
              monitor.readNext();
              methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
              if (!monitor.hasEnded()) {
              	methodOut.getMonitorRecord().setString(monitor.getRecord());
              }
//  AT END
              if (monitor.hasEnded()) {  
//  SET END-OF-MONITOR TO TRUE
                  methodOut.setEndOfMonitorTrue(); 
                  
//cobolCode::GO TO 1000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 1000-EXIT
                }
//  IF MON-XCDT-MTHD-NM = WS-I-METHOD THEN
//  ELSE
              if (		compareChars(methodOut.getMonXcdtMthdNm(),methodOut.getIMethod()) != 0 ) { 
//cobolCode::GO TO 1000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 1000-EXIT
              }
              // MOVE MONITOR-RECORD TO REPREC
              methodOut.getReprec().setString(methodOut.getMonitorRecord().getCharArray());
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  IF STA-IN-STAT1 > '1'
//  LITERAL_1 = '1'
              if (		compareChars(methodIn.getStaInStat1(),CONSTANTS.LITERAL_1) > 0 ) { 
//  MOVE SPACES TO REPREC
                  methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Error reading Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
                  charArray = new ArrayList<char[]>();
                     charArray.add(CONSTANTS.LITERAL_Error_B3_readingMonitor_CL_);
                     charArray.add(methodOut.getMonitorFileStatus().toCharArray());
                  joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
                  updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
                  methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
                  repout.write(methodOut.getReprec().toCharArray()); 
                  methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 1000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 1000-EXIT
              }
          }
          ;
      
      return methodOut;
      }
      /**
      * programBasedReport 
      *   This method is derived from 
  *   COBOL Paragraph - 2000-PROGRAM-BASED-REPORT COBOL Cyclomatic complexity - 8
      * Input  :  

      * - iProgram                       COBOL Name: WS-I-PROGRAM
      * - staInStat1                     COBOL Name: STA-IN-STAT1
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      *
      * Output :  

      * - eofSw                          COBOL Name: WS-EOF-SW
      * - reprec                         COBOL Name: REPREC
      * - monXcdtProgNm                  COBOL Name: MON-XCDT-PROG-NM
      * - iProgram                       COBOL Name: WS-I-PROGRAM
      * - monitorRecord                  COBOL Name: MONITOR-RECORD
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      * - monPriKey                      COBOL Name: MON-PRI-KEY
      *
      * @throws CFException
      */
      @Override
      public ProgramBasedReportOutCtx programBasedReport(ProgramBasedReportInCtx methodIn) throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			Map<String,Object> updated = null;
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
Vsammon1Ctx programCtx = methodIn.getVsammon1Ctx();
ProgramBasedReportOutCtx methodOut = methodIn.getProgramBasedReportOutCtx();
//  MOVE SPACES TO WS-EOF-SW
          methodOut.setEofSw(CONSTANTS.SPACE);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Extracting all Monitor rows matching Program Name = ' WS-I-PROGRAM DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_641398852);
             charArray.add(methodOut.getIProgram());
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
          updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
          methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE WS-I-PROGRAM TO MON-XCDT-PROG-NM
          methodOut.setMonXcdtProgNm(methodOut.getIProgram());
//  START MONITOR KEY IS EQUAL TO MON-XCDT-PROG-NM
          monitor.seek(methodOut.getMonitorRecord().toCharArray(),CFConstants.CONDITION_EQUAL,monitor.getKeyInfo().getMonXcdtProgNm()); 
          methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
//  IF STA-IN-STAT1 > '1'
//  LITERAL_1 = '1'
          if (		compareChars(methodIn.getStaInStat1(),CONSTANTS.LITERAL_1) > 0 ) { 
//  MOVE SPACES TO REPREC
              methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Error strting Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B3_strtingMonitor_CL_);
                 charArray.add(methodOut.getMonitorFileStatus().toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
              methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 2000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 2000-EXIT
          }
//  PERFORM UNTIL END-OF-MONITOR
          while ((!(methodOut.isEndOfMonitor()) )) {
//  READ MONITOR NEXT
              monitor.readNext();
              methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
              if (!monitor.hasEnded()) {
              	methodOut.getMonitorRecord().setString(monitor.getRecord());
              }
//  AT END
              if (monitor.hasEnded()) {  
//  SET END-OF-MONITOR TO TRUE
                  methodOut.setEndOfMonitorTrue(); 
                  
//cobolCode::GO TO 2000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 2000-EXIT
                }
//  IF MON-XCDT-PROG-NM = WS-I-PROGRAM THEN
//  ELSE
              if (		compareChars(methodOut.getMonXcdtProgNm(),methodOut.getIProgram()) != 0 ) { 
//cobolCode::GO TO 2000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 2000-EXIT
              }
              // MOVE MONITOR-RECORD TO REPREC
              methodOut.getReprec().setString(methodOut.getMonitorRecord().getCharArray());
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  IF STA-IN-STAT1 > '1'
//  LITERAL_1 = '1'
              if (		compareChars(methodIn.getStaInStat1(),CONSTANTS.LITERAL_1) > 0 ) { 
//  MOVE SPACES TO REPREC
                  methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Error reading Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
                  charArray = new ArrayList<char[]>();
                     charArray.add(CONSTANTS.LITERAL_Error_B3_readingMonitor_CL_);
                     charArray.add(methodOut.getMonitorFileStatus().toCharArray());
                  joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
                  updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
                  methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
                  repout.write(methodOut.getReprec().toCharArray()); 
                  methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 2000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 2000-EXIT
              }
          }
          ;
      
      return methodOut;
      }
      /**
      * programBasedReport2001 
      *   This method is derived from 
  *   COBOL Paragraph - 2001-PROGRAM-BASED-REPORT COBOL Cyclomatic complexity - 12
      * Input  :  

      * - iProgram                       COBOL Name: WS-I-PROGRAM
      *
      * Output :  

      * - eofSw                          COBOL Name: WS-EOF-SW
      * - reprec                         COBOL Name: REPREC
      * - monXcdtProgNm                  COBOL Name: MON-XCDT-PROG-NM
      * - iProgram                       COBOL Name: WS-I-PROGRAM
      * - monitorRecord                  COBOL Name: MONITOR-RECORD
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      * - monPriKey                      COBOL Name: MON-PRI-KEY
      * - staInStat1                     COBOL Name: STA-IN-STAT1
      *
      * @throws CFException
      */
      @Override
      public ProgramBasedReport2001OutCtx programBasedReport2001(ProgramBasedReport2001InCtx methodIn) throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			Map<String,Object> updated = null;
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
Vsammon1Ctx programCtx = methodIn.getVsammon1Ctx();
ProgramBasedReport2001OutCtx methodOut = methodIn.getProgramBasedReport2001OutCtx();
//  MOVE SPACES TO WS-EOF-SW
          methodOut.setEofSw(CONSTANTS.SPACE);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Extracting all Monitor rows matching Program Name ' WS-I-PROGRAM ' using Direct Read via AIX ' DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_1301224615);
             charArray.add(methodOut.getIProgram());
             charArray.add(CONSTANTS.LITERAL_B6_usingDirectReadviaAIX);
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1),charArray.get(2));
          updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
          methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE WS-I-PROGRAM TO MON-XCDT-PROG-NM
          methodOut.setMonXcdtProgNm(methodOut.getIProgram());
//  READ MONITOR KEY IS MON-XCDT-PROG-NM
          	monitor.readDirect(methodOut.getMonXcdtProgNm(),monitor.getKeyInfo().getMonXcdtProgNm());
          methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
          if (!monitor.hasEnded()) {
          	methodOut.getMonitorRecord().setString(monitor.getRecord());
          }
//  IF MONITOR-FILE-STATUS = '00' OR '02' THEN
//  LITERAL_02 = '02'
//  ELSE
          if (		compareChars(methodOut.getMonitorFileStatus(),CONSTANTS.LITERAL_00) != 0  && 		compareChars(methodOut.getMonitorFileStatus(),CONSTANTS.LITERAL_02) != 0 ) { 
//  MOVE SPACES TO REPREC
              methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Error reading Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B3_readingMonitor_CL_);
                 charArray.add(methodOut.getMonitorFileStatus().toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
              methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 2001-EXIT
return methodOut;
//cobolCodeEnds::GO TO 2001-EXIT
          }
//  PERFORM UNTIL END-OF-MONITOR
          while ((!(methodOut.isEndOfMonitor()) )) {
//  MOVE SPACES TO REPREC
              methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'MONITOR FILE-STATUS = ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_1852263558);
                 charArray.add(methodOut.getMonitorFileStatus().toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
              methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
              // MOVE MONITOR-RECORD TO REPREC
              methodOut.getReprec().setString(methodOut.getMonitorRecord().getCharArray());
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  READ MONITOR NEXT
              monitor.readNext();
              methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
              if (!monitor.hasEnded()) {
              	methodOut.getMonitorRecord().setString(monitor.getRecord());
              }
//  AT END
              if (monitor.hasEnded()) {  
//  SET END-OF-MONITOR TO TRUE
                  methodOut.setEndOfMonitorTrue(); 
                  
//  MOVE SPACES TO REPREC
                  methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'END-OF-FILE condition set' DELIMITED BY SIZE INTO REPREC END-STRING
                  charArray = new ArrayList<char[]>();
                     charArray.add(CONSTANTS.LITERAL_END_MN2_OFFILE_B2_conditionset);
                  joinCharArray = Field.mergeArrays(charArray.get(0));
                  updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
                  methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
                  repout.write(methodOut.getReprec().toCharArray()); 
                  methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 2001-EXIT
return methodOut;
//cobolCodeEnds::GO TO 2001-EXIT
                }
//  IF STA-IN-STAT1 > '1'
//  LITERAL_1 = '1'
              if (		compareChars(methodOut.getStaInStat1(),CONSTANTS.LITERAL_1) > 0 ) { 
//  MOVE SPACES TO REPREC
                  methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Error reading Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
                  charArray = new ArrayList<char[]>();
                     charArray.add(CONSTANTS.LITERAL_Error_B3_readingMonitor_CL_);
                     charArray.add(methodOut.getMonitorFileStatus().toCharArray());
                  joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
                  updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
                  methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
                  repout.write(methodOut.getReprec().toCharArray()); 
                  methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 2001-EXIT
return methodOut;
//cobolCodeEnds::GO TO 2001-EXIT
              }
//  IF MON-XCDT-PROG-NM = WS-I-PROGRAM THEN
//  ELSE
              if (		compareChars(methodOut.getMonXcdtProgNm(),methodOut.getIProgram()) != 0 ) { 
//  MOVE SPACES TO REPREC
                  methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Next Record Prog key = ' MON-XCDT-PROG-NM ' doesnot match ' WS-I-PROGRAM DELIMITED BY SIZE INTO REPREC END-STRING
                  charArray = new ArrayList<char[]>();
                     charArray.add(CONSTANTS.LITERAL_442000900);
                     charArray.add(methodOut.getMonXcdtProgNm());
                     charArray.add(CONSTANTS.LITERAL_B3_doesnotmatch);
                     charArray.add(methodOut.getIProgram());
                  joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1),charArray.get(2),charArray.get(3));
                  updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
                  methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
                  repout.write(methodOut.getReprec().toCharArray()); 
                  methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 2001-EXIT
return methodOut;
//cobolCodeEnds::GO TO 2001-EXIT
              }
          }
          ;
      
      return methodOut;
      }
      /**
      * ipaddrBasedReport 
      *   This method is derived from 
  *   COBOL Paragraph - 3000-IPADDR-BASED-REPORT COBOL Cyclomatic complexity - 8
      * Input  :  

      * - iIpaddr                        COBOL Name: WS-I-IPADDR
      * - staInStat1                     COBOL Name: STA-IN-STAT1
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      *
      * Output :  

      * - eofSw                          COBOL Name: WS-EOF-SW
      * - reprec                         COBOL Name: REPREC
      * - monXcdtReqrIpAd                COBOL Name: MON-XCDT-REQR-IP-AD
      * - iIpaddr                        COBOL Name: WS-I-IPADDR
      * - monitorRecord                  COBOL Name: MONITOR-RECORD
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      * - monPriKey                      COBOL Name: MON-PRI-KEY
      *
      * @throws CFException
      */
      @Override
      public IpaddrBasedReportOutCtx ipaddrBasedReport(IpaddrBasedReportInCtx methodIn) throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			Map<String,Object> updated = null;
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
Vsammon1Ctx programCtx = methodIn.getVsammon1Ctx();
IpaddrBasedReportOutCtx methodOut = methodIn.getIpaddrBasedReportOutCtx();
//  MOVE SPACES TO WS-EOF-SW
          methodOut.setEofSw(CONSTANTS.SPACE);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Extracting all Monitor rows matching IP Address = ' WS-I-IPADDR DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_477265736);
             charArray.add(methodOut.getIIpaddr());
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
          updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
          methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE WS-I-IPADDR TO MON-XCDT-REQR-IP-AD
          methodOut.setMonXcdtReqrIpAd(methodOut.getIIpaddr());
//  START MONITOR KEY IS EQUAL TO MON-XCDT-REQR-IP-AD
          monitor.seek(methodOut.getMonitorRecord().toCharArray(),CFConstants.CONDITION_EQUAL,monitor.getKeyInfo().getMonXcdtReqrIpAd()); 
          methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
//  IF STA-IN-STAT1 > '1'
//  LITERAL_1 = '1'
          if (		compareChars(methodIn.getStaInStat1(),CONSTANTS.LITERAL_1) > 0 ) { 
//  MOVE SPACES TO REPREC
              methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Error strting Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B3_strtingMonitor_CL_);
                 charArray.add(methodOut.getMonitorFileStatus().toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
              methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 3000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 3000-EXIT
          }
//  PERFORM UNTIL END-OF-MONITOR
          while ((!(methodOut.isEndOfMonitor()) )) {
//  READ MONITOR NEXT
              monitor.readNext();
              methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
              if (!monitor.hasEnded()) {
              	methodOut.getMonitorRecord().setString(monitor.getRecord());
              }
//  AT END
              if (monitor.hasEnded()) {  
//  SET END-OF-MONITOR TO TRUE
                  methodOut.setEndOfMonitorTrue(); 
                  
//cobolCode::GO TO 3000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 3000-EXIT
                }
//  IF MON-XCDT-REQR-IP-AD = WS-I-IPADDR THEN
//  ELSE
              if (		compareChars(methodOut.getMonXcdtReqrIpAd(),methodOut.getIIpaddr()) != 0 ) { 
//cobolCode::GO TO 3000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 3000-EXIT
              }
              // MOVE MONITOR-RECORD TO REPREC
              methodOut.getReprec().setString(methodOut.getMonitorRecord().getCharArray());
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  IF STA-IN-STAT1 > '1'
//  LITERAL_1 = '1'
              if (		compareChars(methodIn.getStaInStat1(),CONSTANTS.LITERAL_1) > 0 ) { 
//  MOVE SPACES TO REPREC
                  methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Error reading Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
                  charArray = new ArrayList<char[]>();
                     charArray.add(CONSTANTS.LITERAL_Error_B3_readingMonitor_CL_);
                     charArray.add(methodOut.getMonitorFileStatus().toCharArray());
                  joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
                  updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
                  methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
                  repout.write(methodOut.getReprec().toCharArray()); 
                  methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 3000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 3000-EXIT
              }
          }
          ;
      
      return methodOut;
      }
      /**
      * keyreadBasedReport 
      *   This method is derived from 
  *   COBOL Paragraph - 4000-KEYREAD-BASED-REPORT COBOL Cyclomatic complexity - 4
      * Input  :  

      * - iKeyread                       COBOL Name: WS-I-KEYREAD
      *
      * Output :  

      * - eofSw                          COBOL Name: WS-EOF-SW
      * - reprec                         COBOL Name: REPREC
      * - monPriKey                      COBOL Name: MON-PRI-KEY
      * - iKeyread                       COBOL Name: WS-I-KEYREAD
      * - monitorRecord                  COBOL Name: MONITOR-RECORD
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      * - staInStat1                     COBOL Name: STA-IN-STAT1
      *
      * @throws CFException
      */
      @Override
      public KeyreadBasedReportOutCtx keyreadBasedReport(KeyreadBasedReportInCtx methodIn) throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			Map<String,Object> updated = null;
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
Vsammon1Ctx programCtx = methodIn.getVsammon1Ctx();
KeyreadBasedReportOutCtx methodOut = methodIn.getKeyreadBasedReportOutCtx();
//  MOVE SPACES TO WS-EOF-SW
          methodOut.setEofSw(CONSTANTS.SPACE);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Direct Read of Monitor row  matching KEY = ' WS-I-KEYREAD DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_1103497819);
             charArray.add(methodOut.getIKeyread());
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
          updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
          methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE WS-I-KEYREAD TO MON-PRI-KEY
          methodOut.getMonPriKey().setString(methodOut.getIKeyread());
//  READ MONITOR END-READ
          	monitor.readDirect(methodOut.getMonPriKey().toCharArray(),monitor.getKeyInfo().getMonPriKey());
          methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
          if (!monitor.hasEnded()) {
          	methodOut.getMonitorRecord().setString(monitor.getRecord());
          }
//  IF STA-IN-STAT1 > '1'
//  LITERAL_1 = '1'
          if (		compareChars(methodOut.getStaInStat1(),CONSTANTS.LITERAL_1) > 0 ) { 
//  MOVE SPACES TO REPREC
              methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Error reading Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B3_readingMonitor_CL_);
                 charArray.add(methodOut.getMonitorFileStatus().toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
              methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 4000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 4000-EXIT
          }
          // MOVE MONITOR-RECORD TO REPREC
          methodOut.getReprec().setString(methodOut.getMonitorRecord().getCharArray());
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
          ;
      
      return methodOut;
      }
      /**
      * keyreadnBasedReport 
      *   This method is derived from 
  *   COBOL Paragraph - 4001-KEYREADN-BASED-REPORT COBOL Cyclomatic complexity - 6
      * Input  :  

      * - iKeyread                       COBOL Name: WS-I-KEYREAD
      *
      * Output :  

      * - eofSw                          COBOL Name: WS-EOF-SW
      * - reprec                         COBOL Name: REPREC
      * - monPriKey                      COBOL Name: MON-PRI-KEY
      * - iKeyread                       COBOL Name: WS-I-KEYREAD
      * - monitorRecord                  COBOL Name: MONITOR-RECORD
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      * - staInStat1                     COBOL Name: STA-IN-STAT1
      *
      * @throws CFException
      */
      @Override
      public KeyreadnBasedReportOutCtx keyreadnBasedReport(KeyreadnBasedReportInCtx methodIn) throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			Map<String,Object> updated = null;
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
Vsammon1Ctx programCtx = methodIn.getVsammon1Ctx();
KeyreadnBasedReportOutCtx methodOut = methodIn.getKeyreadnBasedReportOutCtx();
//  MOVE SPACES TO WS-EOF-SW
          methodOut.setEofSw(CONSTANTS.SPACE);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Direct Read of Monitor row  matching KEY = ' WS-I-KEYREAD DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_1103497819);
             charArray.add(methodOut.getIKeyread());
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
          updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
          methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE WS-I-KEYREAD TO MON-PRI-KEY
          methodOut.getMonPriKey().setString(methodOut.getIKeyread());
//  READ MONITOR KEY IS MON-PRI-KEY END-READ
          	monitor.readDirect(methodOut.getMonPriKey().toCharArray(),monitor.getKeyInfo().getMonPriKey());
          methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
          if (!monitor.hasEnded()) {
          	methodOut.getMonitorRecord().setString(monitor.getRecord());
          }
//  IF STA-IN-STAT1 > '1'
//  LITERAL_1 = '1'
          if (		compareChars(methodOut.getStaInStat1(),CONSTANTS.LITERAL_1) > 0 ) { 
//  MOVE SPACES TO REPREC
              methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Error reading Monitor: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B3_readingMonitor_CL_);
                 charArray.add(methodOut.getMonitorFileStatus().toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
              methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
          }
//  ELSE
          else { 
              // MOVE MONITOR-RECORD TO REPREC
              methodOut.getReprec().setString(methodOut.getMonitorRecord().getCharArray());
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
          }

// * Now do read next
          // MOVE 'READ NEXT done after Direct READ' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_190291563);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  READ MONITOR NEXT
          monitor.readNext();
          methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
          if (!monitor.hasEnded()) {
          	methodOut.getMonitorRecord().setString(monitor.getRecord());
          }
//  AT END
          if (monitor.hasEnded()) {  
//  SET END-OF-MONITOR TO TRUE
              methodOut.setEndOfMonitorTrue(); 
              
//  MOVE SPACES TO REPREC
              methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'END-OF-FILE condition set' DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_END_MN2_OFFILE_B2_conditionset);
              joinCharArray = Field.mergeArrays(charArray.get(0));
              updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
              methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 4001-EXIT
return methodOut;
//cobolCodeEnds::GO TO 4001-EXIT
            }
//  MOVE SPACES TO REPREC
          methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'MONITOR FILE-STATUS = ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_1852263558);
             charArray.add(methodOut.getMonitorFileStatus().toCharArray());
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
          updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
          methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);

// *
          // MOVE MONITOR-RECORD TO REPREC
          methodOut.getReprec().setString(methodOut.getMonitorRecord().getCharArray());
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
          ;
      
      return methodOut;
      }
      /**
      * insertBasedReport 
      *   This method is derived from 
  *   COBOL Paragraph - 5000-INSERT-BASED-REPORT COBOL Cyclomatic complexity - 4
      * Input  :  

      * - iInsertKey                     COBOL Name: WS-I-INSERT-KEY
      *
      * Output :  

      * - eofSw                          COBOL Name: WS-EOF-SW
      * - reprec                         COBOL Name: REPREC
      * - monitorRecord                  COBOL Name: MONITOR-RECORD
      * - monXcdtReqrIpAd                COBOL Name: MON-XCDT-REQR-IP-AD
      * - monPriKey                      COBOL Name: MON-PRI-KEY
      * - iInsertKey                     COBOL Name: WS-I-INSERT-KEY
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      *
      * @throws CFException
      */
      @Override
      public InsertBasedReportOutCtx insertBasedReport(InsertBasedReportInCtx methodIn) throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			Map<String,Object> updated = null;
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
Vsammon1Ctx programCtx = methodIn.getVsammon1Ctx();
InsertBasedReportOutCtx methodOut = methodIn.getInsertBasedReportOutCtx();
//  MOVE SPACES TO WS-EOF-SW
          methodOut.setEofSw(CONSTANTS.SPACE);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'WRITE Monitor Record with KEY = ' WS-I-INSERT-KEY DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_1442017046);
             charArray.add(methodOut.getIInsertKey());
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
          updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
          methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  INITIALIZE MONITOR-RECORD
          methodOut.getMonitorRecord().initialize();

// *    Add 1 to ws-ip-node
// *    string
// *       ws-ip-node '.'
// *       ws-ip-node '.'
// *       ws-ip-node '.'
// *       ws-ip-node delimited by size
// *      into mon-xcdt-reqr-ip-ad
// *    end-string
//  MOVE '1.1.1.1' TO MON-XCDT-REQR-IP-AD
          methodOut.setMonXcdtReqrIpAd(CONSTANTS.LITERAL_1979067146);
//  MOVE WS-I-INSERT-KEY TO MON-PRI-KEY
          methodOut.getMonPriKey().setString(methodOut.getIInsertKey());
//  WRITE MONITOR-RECORD
          monitor.write(methodOut.getMonitorRecord().toCharArray()); 
          methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
//  IF MONITOR-FILE-STATUS = '00'
//  LITERAL_00 = '00'
//  ELSE
          if (		compareChars(methodOut.getMonitorFileStatus(),CONSTANTS.LITERAL_00) != 0 ) { 
//  MOVE SPACES TO REPREC
              methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Error Writing Monitor Record: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B4_WritingMonitorRecord_CL_);
                 charArray.add(methodOut.getMonitorFileStatus().toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
              methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 5000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 5000-EXIT
          }
          ;
      
      return methodOut;
      }
      /**
      * deleteBasedReport 
      *   This method is derived from 
  *   COBOL Paragraph - 6000-DELETE-BASED-REPORT COBOL Cyclomatic complexity - 4
      * Input  :  

      * - iDeleteKey                     COBOL Name: WS-I-DELETE-KEY
      * - monitorFileStatus              COBOL Name: MONITOR-FILE-STATUS
      *
      * Output :  

      * - eofSw                          COBOL Name: WS-EOF-SW
      * - reprec                         COBOL Name: REPREC
      * - monitorRecord                  COBOL Name: MONITOR-RECORD
      * - monPriKey                      COBOL Name: MON-PRI-KEY
      * - iDeleteKey                     COBOL Name: WS-I-DELETE-KEY
      *
      * @throws CFException
      */
      @Override
      public DeleteBasedReportOutCtx deleteBasedReport(DeleteBasedReportInCtx methodIn) throws Exception {
			// Declare local variables used in the method
			ArrayList<char[]> charArray = new ArrayList<char[]>();
			char[] joinCharArray = null;
			Map<String,Object> updated = null;
			// End of variable declaration

      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
Vsammon1Ctx programCtx = methodIn.getVsammon1Ctx();
DeleteBasedReportOutCtx methodOut = methodIn.getDeleteBasedReportOutCtx();
//  MOVE SPACES TO WS-EOF-SW
          methodOut.setEofSw(CONSTANTS.SPACE);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  MOVE SPACES TO REPREC
          methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'DELETE Monitor Record with KEY = ' WS-I-DELETE-KEY DELIMITED BY SIZE INTO REPREC END-STRING
          charArray = new ArrayList<char[]>();
             charArray.add(CONSTANTS.LITERAL_320748634);
             charArray.add(methodOut.getIDeleteKey());
          joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
          updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
          methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
          // MOVE '**********' TO REPREC
          methodOut.getReprec().setString(CONSTANTS.LITERAL_2015391037);
//  WRITE REPREC
          repout.write(methodOut.getReprec().toCharArray()); 
          methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//  INITIALIZE MONITOR-RECORD
          methodOut.getMonitorRecord().initialize();
//  MOVE WS-I-DELETE-KEY TO MON-PRI-KEY
          methodOut.getMonPriKey().setString(methodOut.getIDeleteKey());
//  DELETE MONITOR
          monitor.delete(methodOut.getMonPriKey().toCharArray());
          methodOut.getMonitorFileStatus().setString(monitor.getStatusString() );
//  IF MONITOR-FILE-STATUS NOT = '00'
//  LITERAL_00 = '00'
          if (		compareChars(methodOut.getMonitorFileStatus(),CONSTANTS.LITERAL_00) != 0 ) { 
//  MOVE SPACES TO REPREC
              methodOut.getReprec().setString(CONSTANTS.SPACE_300);
//  STRING 'Error Deleting Monitor Record: ' MONITOR-FILE-STATUS DELIMITED BY SIZE INTO REPREC END-STRING
              charArray = new ArrayList<char[]>();
                 charArray.add(CONSTANTS.LITERAL_Error_B4_DeletingMonitorRecord_CL_);
                 charArray.add(methodOut.getMonitorFileStatus().toCharArray());
              joinCharArray = Field.mergeArrays(charArray.get(0),charArray.get(1));
              updated = updateString(methodOut.getReprec().toCharArray() ,joinCharArray);
              methodOut.getReprec().setString(  (char[])updated.get("string"));
//  WRITE REPREC
              repout.write(methodOut.getReprec().toCharArray()); 
              methodOut.getReprec().setString(CONSTANTS.LOW_VALUE_215695350);
//cobolCode::GO TO 6000-EXIT
return methodOut;
//cobolCodeEnds::GO TO 6000-EXIT
          }
          ;
      
      return methodOut;
      }
      /**
      * exitProgram 
      *   This method is derived from 
  *   COBOL Paragraph - 9999-EXIT-PROGRAM COBOL Cyclomatic complexity - 2
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      @Override
      public void exitProgram(Vsammon1Ctx programCtx) throws Exception {
      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          programCtx.setProgramEnded(true);
          return ;
      
      }
  
  
  
  
  
  
  
  
  }
