# Program  : DB2FUNC | DD : SYSIN | RecordFormat : FixedLength | RecordLength : 80
DB2FUNC.Scanner=SYSIN.bin
DB2FUNC.ScannerCharSet=cp1047
DB2FUNC.ScannerCRLFflag=no
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
DB2FUNC.dbQualifier=
# 
# End of DB2FUNC
