# Program CFSORT05 | DD : FILEIN | RecordFormat : FixedLength | RecordLength : 30
CFSORT05.ddname.FILEIN=FileIn
CFSORT05.FileIn=FileIn
CFSORT05.FileInCharSet=cp1047
CFSORT05.FileInCRLFflag=no
# Program CFSORT05 | DD : FILEOUT | RecordFormat : FixedLength | RecordLength : 30
CFSORT05.ddname.FILEOUT=FileOut
CFSORT05.FileOut=FileOut
CFSORT05.FileOutCharSet=cp1047
CFSORT05.FileOutCRLFflag=no
# 
# End of CFSORT05
