  package com.cloudframe.app.process;
  /* Java code generated by CloudFrame on 2025-04-28 at 06:52. */
  
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.utility.CFUtil;
  import java.math.BigDecimal;
  import com.cloudframe.app.init1.dto.ProgramCounters;
  import com.cloudframe.app.init1.dto.RlcbmBillMessageRec;
  import com.cloudframe.app.init1.dto.WvExtrLdgBblX;
  import com.cloudframe.app.init1.dto.WvExtrActDensityX;
  import com.cloudframe.app.init1.dto.WvExtrLdgM3AmbX;
  import com.cloudframe.app.init1.dto.WvExtrDetails;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.init1.dto.*;
  import com.cloudframe.app.init1.dto.FillerBeginEndMid1;
  import com.cloudframe.app.init1.dto.CmnAcmn009pParms;
  import com.cloudframe.app.init1.dto.TV20Table;
  import com.cloudframe.app.init1.dto.Bilrlu5f;
  import com.cloudframe.app.init1.dto.SaveInfoArea;
  import com.cloudframe.app.init1.dto.Rlm2tPromoCustMtnRec;
  import com.cloudframe.app.init1.dto.FillerBeginEnd;
  import com.cloudframe.app.init1.dto.DclWipBlCycPhaseAudit;
  import com.cloudframe.app.init1.dto.DclBlAcctSvcProd;
  import com.cloudframe.app.init1.dto.CycleInfo;
  import com.cloudframe.app.init1.dto.FillerBeginEnd1;
  import com.cloudframe.app.init1.dto.InputRec;
  import com.cloudframe.app.init1.dto.WsrevRevoStatRecord;
  import com.cloudframe.app.init1.dto.FillerBeginEndMid;
  import com.cloudframe.app.init1.dto.IypData6;
  import com.cloudframe.app.init1.dto.Counters;
  import com.cloudframe.app.init1.dto.Test1;
  import com.cloudframe.app.init1.dto.WvExtrRecord;
  import com.cloudframe.app.init1.dto.RlcbmBillMsgDtlGroup;
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.beans.factory.annotation.Qualifier;
  import com.cloudframe.app.global.sharedvar.ReturnJobNameGroup;
  import com.cloudframe.app.init1.dto.Rl001CycleInputData;
  import com.cloudframe.app.init1.dto.RlduuInEocUsgBlData;
  import com.cloudframe.app.init1.dto.RlhzaRcCycleData;
  import com.cloudframe.app.init1.dto.FlguuInEocUsgBlData;
  import com.cloudframe.app.init1.dto.BmdCdrInfo;
  import com.cloudframe.app.init1.dto.CycdateInfo;
  import com.cloudframe.app.init1.dto.TCpduTableInit;
  import com.cloudframe.app.init1.dto.TLnshrgrpTableInit;
  import com.cloudframe.app.init1.dto.LCpduTableInit;
  import com.cloudframe.app.init1.dto.TDataAlpTableInit;
  import com.cloudframe.app.init1.dto.TDataSfoTableInit;
  import com.cloudframe.app.init1.dto.TSpoAlwTableInit;
  import com.cloudframe.app.init1.dto.TSvcProdTableInit;
  import com.cloudframe.app.init1.dto.TSpoProdTableInit;
  import com.cloudframe.app.init1.dto.TGlbProdTableInit;
  import com.cloudframe.app.init1.dto.TM2mPromoTableInit;
  import com.cloudframe.app.init1.dto.TMtnStatTableInit;
  import com.cloudframe.app.init1.dto.TRevoTableInit;
  import com.cloudframe.app.init1.dto.RcCycleDateInit;
  import com.cloudframe.app.init1.dto.CmnErrorMessages;
  import com.cloudframe.app.init1.dto.WscdlCalDate;
  import com.cloudframe.app.init1.dto.Sqlca;
  import com.cloudframe.app.init1.dto.NoFiller;
  import com.cloudframe.app.init1.dto.Xcprs01;
  import com.cloudframe.app.init1.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  
  @Component("init1")
  
  public class Init1 extends CommonProcess {
  
  Logger logger = LoggerFactory.getLogger(Init1.class);
  
  private FillerBeginEndMid1 fillerBeginEndMid1 = new FillerBeginEndMid1() ;
  private CmnAcmn009pParms cmnAcmn009pParms = new CmnAcmn009pParms() ;
  private TV20Table tV20Table = new TV20Table() ;
  private Bilrlu5f bilrlu5f = new Bilrlu5f() ;
  private SaveInfoArea saveInfoArea = new SaveInfoArea() ;
  private Rlm2tPromoCustMtnRec rlm2tPromoCustMtnRec = new Rlm2tPromoCustMtnRec() ;
  private FillerBeginEnd fillerBeginEnd = new FillerBeginEnd() ;
  private DclWipBlCycPhaseAudit dclWipBlCycPhaseAudit = new DclWipBlCycPhaseAudit() ;
  private DclBlAcctSvcProd dclBlAcctSvcProd = new DclBlAcctSvcProd() ;
  private CycleInfo cycleInfo = new CycleInfo() ;
  private FillerBeginEnd1 fillerBeginEnd1 = new FillerBeginEnd1() ;
  private InputRec inputRec = new InputRec() ;
  private WsrevRevoStatRecord wsrevRevoStatRecord = new WsrevRevoStatRecord() ;
  private FillerBeginEndMid fillerBeginEndMid = new FillerBeginEndMid() ;
  private IypData6 iypData6 = new IypData6() ;
  private Counters counters = new Counters() ;
  private Test1 test1 = new Test1() ;
  private WvExtrRecord wvExtrRecord = new WvExtrRecord() ;
  private RlcbmBillMsgDtlGroup rlcbmBillMsgDtlGroup = new RlcbmBillMsgDtlGroup() ;
  private Rl001CycleInputData rl001CycleInputData = new Rl001CycleInputData() ;
  private RlduuInEocUsgBlData rlduuInEocUsgBlData = new RlduuInEocUsgBlData() ;
  private RlhzaRcCycleData rlhzaRcCycleData = new RlhzaRcCycleData() ;
  private FlguuInEocUsgBlData flguuInEocUsgBlData = new FlguuInEocUsgBlData() ;
  private BmdCdrInfo bmdCdrInfo = new BmdCdrInfo() ;
  private CycdateInfo cycdateInfo = new CycdateInfo() ;
  private TCpduTableInit tCpduTableInit = new TCpduTableInit() ;
  private TLnshrgrpTableInit tLnshrgrpTableInit = new TLnshrgrpTableInit() ;
  private LCpduTableInit lCpduTableInit = new LCpduTableInit() ;
  private TDataAlpTableInit tDataAlpTableInit = new TDataAlpTableInit() ;
  private TDataSfoTableInit tDataSfoTableInit = new TDataSfoTableInit() ;
  private TSpoAlwTableInit tSpoAlwTableInit = new TSpoAlwTableInit() ;
  private TSvcProdTableInit tSvcProdTableInit = new TSvcProdTableInit() ;
  private TSpoProdTableInit tSpoProdTableInit = new TSpoProdTableInit() ;
  private TGlbProdTableInit tGlbProdTableInit = new TGlbProdTableInit() ;
  private TM2mPromoTableInit tM2mPromoTableInit = new TM2mPromoTableInit() ;
  private TMtnStatTableInit tMtnStatTableInit = new TMtnStatTableInit() ;
  private TRevoTableInit tRevoTableInit = new TRevoTableInit() ;
  private RcCycleDateInit rcCycleDateInit = new RcCycleDateInit() ;
  private CmnErrorMessages cmnErrorMessages = new CmnErrorMessages() ;
  private WscdlCalDate wscdlCalDate = new WscdlCalDate() ;
  private Sqlca sqlca = new Sqlca() ;
  private NoFiller noFiller = new NoFiller() ;
  private Xcprs01 xcprs01 = new Xcprs01() ;
  private Work work = new Work() ;
  
  
  
  @Autowired 
  @Qualifier("global_returnJobNameGroup")
  ReturnJobNameGroup returnJobNameGroup;
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output :  

      * - cmnAcmn009pParms               COBOL Name: CMN-ACMN009P-PARMS
      * - counters                       COBOL Name: WS-COUNTERS
      * - saveInfoArea                   COBOL Name: WS-SAVE-INFO-AREA
      * - wsrevRevoStatRecord            COBOL Name: WSREV-REVO-STAT-RECORD
      * - keyUsgPrev                     COBOL Name: WS-KEY-USG-PREV
      * - returnJobName                  COBOL Name: WS-RETURN-JOB-NAME
      * - cDisplayJobnme                 COBOL Name: C-DISPLAY-JOBNME
      * - tV20Table                      COBOL Name: T-V20-TABLE
      * - dclBlAcctSvcProd               COBOL Name: DCL-BL-ACCT-SVC-PROD
      * - delayedCpduInd                 COBOL Name: WS-DELAYED-CPDU-IND
      * - rejectCd                       COBOL Name: WS-REJECT-CD
      * - rlm2tPromoCustMtnRec           COBOL Name: RLM2T-PROMO-CUST-MTN-REC
      * - bypassAcctFlag                 COBOL Name: WS-BYPASS-ACCT-FLAG
      * - errRejFlag                     COBOL Name: WS-ERR-REJ-FLAG
      * - custFlgUsgCtr                  COBOL Name: WS-CUST-FLG-USG-CTR
      * - custUsgCtr                     COBOL Name: WS-CUST-USG-CTR
      * - cycleInfo                      COBOL Name: WS-CYCLE-INFO
      * - wcdloDateTable                 COBOL Name: WCDLO-DATE-TABLE
      * - wcdloDateChar                  COBOL Name: WCDLO-DATE-CHAR
      * - wcdloStartDateIso              COBOL Name: WCDLO-START-DATE-ISO
      * - wcdloEndDateIso                COBOL Name: WCDLO-END-DATE-ISO
      * - wcdloCycStartDt                COBOL Name: WCDLO-CYC-START-DT
      * - wcdloCycEndDt                  COBOL Name: WCDLO-CYC-END-DT
      * - billPeriodDates                COBOL Name: WS-BILL-PERIOD-DATES
      * - dclWipBlCycPhaseAudit          COBOL Name: DCL-WIP-BL-CYC-PHASE-AUDIT
      * - errAcctRecord                  COBOL Name: WS-ERR-ACCT-RECORD
      *
      * @throws CFException
      */
      @Override
      public int process() throws Exception {
       initVars();
			// Declare local variables used in the method
			ProgramCounters programCounters = counters.getProgramCounters();
			// End of variable declaration

       try {
       setCodePage("1047");

// *
//  MOVE ALL 'A' TO CMN-ACMN009P-PARMS WS-COUNTERS WS-SAVE-INFO-AREA WSREV-REVO-STAT-RECORD
          cmnAcmn009pParms.setString(CONSTANTS.LITERAL_489482004);
          counters.setString(CONSTANTS.LITERAL_1224993241);
          saveInfoArea.setString(CONSTANTS.LITERAL_1884079407);
          wsrevRevoStatRecord.setString(CONSTANTS.LITERAL_1270257749);
//  INITIALIZE CMN-ACMN009P-PARMS WS-COUNTERS WS-SAVE-INFO-AREA WSREV-REVO-STAT-RECORD
          cmnAcmn009pParms.initialize();
          counters.initialize();
          saveInfoArea.initialize();
          wsrevRevoStatRecord.initialize();
//  DISPLAY '1 -CMN-ACMN009P-PARMS ' CMN-ACMN009P-PARMS ' WS-COUNTERS ' WS-COUNTERS ' WS-SAVE-INFO-AREA ' WS-SAVE-INFO-AREA ' WSREV-REVO-STAT-RECORD ' WSREV-REVO-STAT-RECORD
          logger.info("1 -CMN-ACMN009P-PARMS {} WS-COUNTERS {} WS-SAVE-INFO-AREA {} WSREV-REVO-STAT-RECORD {}", cmnAcmn009pParms.toString(), counters.toString(), saveInfoArea.toString(), wsrevRevoStatRecord.toString()); 

// *
//  MOVE ALL 'A' TO WS-KEY-USG-PREV
          saveInfoArea.getKeyUsgPrev().setString(CONSTANTS.LITERAL_1791367435);
//  INITIALIZE WS-KEY-USG-PREV
          saveInfoArea.getKeyUsgPrev().initialize();

// *
//  MOVE ALL 'A' TO WS-RETURN-JOB-NAME C-DISPLAY-JOBNME
          returnJobNameGroup.setReturnJobName(CONSTANTS.LITERAL_AAAAAAAA);
          work.setCDisplayJobnme(CONSTANTS.LITERAL_AAAAAAAA);
//  INITIALIZE WS-RETURN-JOB-NAME C-DISPLAY-JOBNME
          returnJobNameGroup.setReturnJobName(CONSTANTS.SPACE_8 /* Fill 8 Spaces*/);
          work.setCDisplayJobnme(CONSTANTS.SPACE_8 /* Fill 8 Spaces*/);
//  DISPLAY '2 ' WS-RETURN-JOB-NAME C-DISPLAY-JOBNME
          logger.info("2 {}{}", new String(returnJobNameGroup.getReturnJobName()), new String(work.getCDisplayJobnme())); 

// *
//  MOVE ALL 'A' TO T-V20-TABLE
          tV20Table.setString(CONSTANTS.LITERAL_834541873);
//  INITIALIZE T-V20-TABLE
          tV20Table.initialize();
//  DISPLAY '3 ' T-V20-TABLE
          logger.info("3 {}", tV20Table.toString()); 
//  MOVE ALL 'A' TO DCL-BL-ACCT-SVC-PROD
          dclBlAcctSvcProd.setString(CONSTANTS.LITERAL_620166200);
//  INITIALIZE DCL-BL-ACCT-SVC-PROD
          dclBlAcctSvcProd.initialize();
//  DISPLAY '4 ' DCL-BL-ACCT-SVC-PROD
          logger.info("4 {}", dclBlAcctSvcProd.toString()); 

// *
//  MOVE ALL 'A' TO WS-DELAYED-CPDU-IND WS-REJECT-CD
          work.setDelayedCpduInd(CONSTANTS.LITERAL_A);
          work.setRejectCd(CONSTANTS.LITERAL_AAA);
//  INITIALIZE WS-DELAYED-CPDU-IND WS-REJECT-CD
          work.setDelayedCpduInd(CONSTANTS.SPACE /* Fill 1 Spaces*/);
          work.setRejectCd(CONSTANTS.SPACE_3 /* Fill 3 Spaces*/);
//  DISPLAY '5 ' WS-DELAYED-CPDU-IND WS-REJECT-CD
          logger.info("5 {}{}", new String(work.getDelayedCpduInd()), new String(work.getRejectCd())); 

// *
          // MOVE ALL 'A' TO WS-REJECT-CD
          work.setRejectCd(CONSTANTS.LITERAL_AAA);
//  INITIALIZE WS-REJECT-CD
          work.setRejectCd(CONSTANTS.SPACE_3 /* Fill 3 Spaces*/);
//  DISPLAY '6 ' WS-REJECT-CD
          logger.info("6 {}", new String(work.getRejectCd())); 

// *
//  MOVE ALL 'A' TO RLM2T-PROMO-CUST-MTN-REC
          rlm2tPromoCustMtnRec.setString(CONSTANTS.LITERAL_642798454);
//  INITIALIZE RLM2T-PROMO-CUST-MTN-REC
          rlm2tPromoCustMtnRec.initialize();
//  DISPLAY '7 ' RLM2T-PROMO-CUST-MTN-REC
          logger.info("7 {}", rlm2tPromoCustMtnRec.toString()); 

// *
//  MOVE ALL 'A' TO WS-BYPASS-ACCT-FLAG WS-ERR-REJ-FLAG
          work.setBypassAcctFlag(CONSTANTS.LITERAL_A);
          work.setErrRejFlag(CONSTANTS.LITERAL_A);
//  INITIALIZE WS-CUST-FLG-USG-CTR WS-CUST-USG-CTR WS-BYPASS-ACCT-FLAG WS-ERR-REJ-FLAG
          programCounters.setCustFlgUsgCtr(BigDecimal.ZERO);
          programCounters.setCustUsgCtr(BigDecimal.ZERO);
          work.setBypassAcctFlag(CONSTANTS.SPACE /* Fill 1 Spaces*/);
          work.setErrRejFlag(CONSTANTS.SPACE /* Fill 1 Spaces*/);
  
//  DISPLAY '8 ' WS-CUST-FLG-USG-CTR WS-CUST-USG-CTR WS-BYPASS-ACCT-FLAG WS-ERR-REJ-FLAG
          logger.info("8 {}{}{}{}", String.valueOf(programCounters.getCustFlgUsgCtr().movePointRight(2)), String.valueOf(programCounters.getCustUsgCtr().movePointRight(2)), new String(work.getBypassAcctFlag()), new String(work.getErrRejFlag())); 
  

// *
//  MOVE ALL 'A' TO WS-CYCLE-INFO
          cycleInfo.setString(CONSTANTS.LITERAL_551705848);
//  INITIALIZE WS-CYCLE-INFO
          cycleInfo.initialize();
//  INITIALIZE WCDLO-DATE-TABLE
          wscdlCalDate.getWcdloDateTable().initialize();

// *
//  MOVE ALL 'A' TO WCDLO-DATE-CHAR
          wscdlCalDate.getWcdloDateChar().setString(CONSTANTS.LITERAL_AAAAAAAA);
//  INITIALIZE WCDLO-DATE-CHAR
          wscdlCalDate.getWcdloDateChar().initialize();
//  DISPLAY '9 ' WCDLO-DATE-CHAR
          logger.info("9 {}", wscdlCalDate.getWcdloDateChar().toString()); 

// *
          // MOVE 01012018 TO WCDLO-START-DATE-ISO WCDLO-END-DATE-ISO
          wscdlCalDate.setWcdloStartDateIso((long)1012018);
          wscdlCalDate.setWcdloEndDateIso((long)1012018);

// *
//  MOVE ALL 'A' TO WCDLO-CYC-START-DT WCDLO-CYC-END-DT
          wscdlCalDate.getWcdloCycStartDt().setString(CONSTANTS.LITERAL_AAAAAAAAAA);
          wscdlCalDate.getWcdloCycEndDt().setString(CONSTANTS.LITERAL_AAAAAAAAAA);
//  INITIALIZE WCDLO-CYC-START-DT WCDLO-CYC-END-DT WCDLO-START-DATE-ISO WCDLO-END-DATE-ISO
          wscdlCalDate.getWcdloCycStartDt().initialize();
          wscdlCalDate.getWcdloCycEndDt().initialize();
          wscdlCalDate.setWcdloStartDateIso(0);
          wscdlCalDate.setWcdloEndDateIso(0);
//  DISPLAY '10 ' WCDLO-CYC-START-DT WCDLO-CYC-END-DT WCDLO-START-DATE-ISO WCDLO-END-DATE-ISO
          logger.info("10 {}{}{}{}", wscdlCalDate.getWcdloCycStartDt().toString(), wscdlCalDate.getWcdloCycEndDt().toString(), String.valueOf(wscdlCalDate.getWcdloStartDateIso()), String.valueOf(wscdlCalDate.getWcdloEndDateIso())); 

// *
          // MOVE 01012018 TO WCDLO-START-DATE-ISO WCDLO-END-DATE-ISO
          wscdlCalDate.setWcdloStartDateIso((long)1012018);
          wscdlCalDate.setWcdloEndDateIso((long)1012018);
//  MOVE ALL 'A' TO WCDLO-CYC-START-DT WCDLO-CYC-END-DT
          wscdlCalDate.getWcdloCycStartDt().setString(CONSTANTS.LITERAL_AAAAAAAAAA);
          wscdlCalDate.getWcdloCycEndDt().setString(CONSTANTS.LITERAL_AAAAAAAAAA);
//  INITIALIZE WCDLO-CYC-START-DT WCDLO-CYC-END-DT WCDLO-START-DATE-ISO WCDLO-END-DATE-ISO
          wscdlCalDate.getWcdloCycStartDt().initialize();
          wscdlCalDate.getWcdloCycEndDt().initialize();
          wscdlCalDate.setWcdloStartDateIso(0);
          wscdlCalDate.setWcdloEndDateIso(0);
//  DISPLAY '11 ' WCDLO-CYC-START-DT WCDLO-CYC-END-DT WCDLO-START-DATE-ISO WCDLO-END-DATE-ISO
          logger.info("11 {}{}{}{}", wscdlCalDate.getWcdloCycStartDt().toString(), wscdlCalDate.getWcdloCycEndDt().toString(), String.valueOf(wscdlCalDate.getWcdloStartDateIso()), String.valueOf(wscdlCalDate.getWcdloEndDateIso())); 

// *
//  MOVE ALL 'A' TO WS-BILL-PERIOD-DATES
          cycdateInfo.getBillPeriodDates().setString(CONSTANTS.LITERAL_517757467);
//  INITIALIZE WS-BILL-PERIOD-DATES
          cycdateInfo.getBillPeriodDates().initialize();
//  DISPLAY '12 ' WS-BILL-PERIOD-DATES
          logger.info("12 {}", cycdateInfo.getBillPeriodDates().toString()); 

// *
//  MOVE ALL 'A' TO DCL-WIP-BL-CYC-PHASE-AUDIT
          dclWipBlCycPhaseAudit.setString(CONSTANTS.LITERAL_446927024);
//  INITIALIZE DCL-WIP-BL-CYC-PHASE-AUDIT
          dclWipBlCycPhaseAudit.initialize();
//  DISPLAY '13 ' DCL-WIP-BL-CYC-PHASE-AUDIT
          logger.info("13 {}", dclWipBlCycPhaseAudit.toString()); 

// *
//  MOVE ALL 'A' TO DCL-WIP-BL-CYC-PHASE-AUDIT
          dclWipBlCycPhaseAudit.setString(CONSTANTS.LITERAL_446927024);
//  INITIALIZE DCL-WIP-BL-CYC-PHASE-AUDIT
          dclWipBlCycPhaseAudit.initialize();
//  DISPLAY '14 ' DCL-WIP-BL-CYC-PHASE-AUDIT
          logger.info("14 {}", dclWipBlCycPhaseAudit.toString()); 

// *
//  MOVE ALL 'A' TO WS-ERR-ACCT-RECORD
          saveInfoArea.getErrAcctRecord().setString(CONSTANTS.LITERAL_1621061940);
//  INITIALIZE WS-ERR-ACCT-RECORD
          saveInfoArea.getErrAcctRecord().initialize();
//  PERFORM PROCESS-1
          process1();/*PROCESS-1*/
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
       return getRc(); // Exit with return code
      // end of process method
      }
      /**
      * process1 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-1 COBOL Cyclomatic complexity - 1
      * Input  :  

      * - errAcctRecord                  COBOL Name: WS-ERR-ACCT-RECORD
      * - i1                             COBOL Name: I1
      * - messageMaxCnt                  COBOL Name: MESSAGE-MAX-CNT
      *
      * Output :  

      * - rlcbmInvoiceNo                 COBOL Name: RLCBM-INVOICE-NO
      * - rlcbmEcpdProfileId             COBOL Name: RLCBM-ECPD-PROFILE-ID
      * - rlcbmActiveMtnsQty             COBOL Name: RLCBM-ACTIVE-MTNS-QTY
      * - rlcbmCustTypCd                 COBOL Name: RLCBM-CUST-TYP-CD
      * - custFlgUsgCtr                  COBOL Name: WS-CUST-FLG-USG-CTR
      * - custUsgCtr                     COBOL Name: WS-CUST-USG-CTR
      * - bypassAcctFlag                 COBOL Name: WS-BYPASS-ACCT-FLAG
      * - errRejFlag                     COBOL Name: WS-ERR-REJ-FLAG
      * - bilrlu5f                       COBOL Name: BILRLU5F
      * - test1                          COBOL Name: WS-TEST1
      * - iypData6                       COBOL Name: WS-6IYP-DATA
      * - fillerBeginEnd                 COBOL Name: FILLER-BEGIN-END
      * - fillerBeginEndMid              COBOL Name: FILLER-BEGIN-END-MID
      * - fillerBeginEnd1                COBOL Name: FILLER-BEGIN-END1
      * - fillerBeginEndMid1             COBOL Name: FILLER-BEGIN-END-MID1
      * - i1                             COBOL Name: I1
      * - messages                       COBOL Name: MESSAGES
      * - messageSeverity                COBOL Name: MESSAGE-SEVERITY
      * - messageDescriptionLen          COBOL Name: MESSAGE-DESCRIPTION-LEN
      * - wvExtrRecord                   COBOL Name: WV-EXTR-RECORD
      * - wvExtrDetails                  COBOL Name: WV-EXTR-DETAILS
      * - wvExtrLdgBbl                   COBOL Name: WV-EXTR-LDG-BBL
      * - wvExtrActDensity               COBOL Name: WV-EXTR-ACT-DENSITY
      * - wvExtrLdgM3Amb                 COBOL Name: WV-EXTR-LDG-M3-AMB
      * - wvExtrFrmlVers                 COBOL Name: WV-EXTR-FRML-VERS
      * - inputRec                       COBOL Name: WS-INPUT-REC
      * - inputDeductions                COBOL Name: WS-INPUT-DEDUCTIONS
      *
      * @throws CFException
      */
      private void process1() throws Exception {
			// Declare local variables used in the method
			RlcbmBillMessageRec rlcbmBillMessageRec = rlcbmBillMsgDtlGroup.getRlcbmBillMsgDtl().getRlcbmBillMessageRec();
			ProgramCounters programCounters = counters.getProgramCounters();
			WvExtrLdgBblX wvExtrLdgBblX = wvExtrRecord.getWvExtrDetails().getWvExtrLdgBblX();
			WvExtrActDensityX wvExtrActDensityX = wvExtrRecord.getWvExtrDetails().getWvExtrActDensityX();
			WvExtrLdgM3AmbX wvExtrLdgM3AmbX = wvExtrRecord.getWvExtrDetails().getWvExtrLdgM3AmbX();
			WvExtrDetails wvExtrDetails = wvExtrRecord.getWvExtrDetails();
			// End of variable declaration

//  DISPLAY '15 ' WS-ERR-ACCT-RECORD
          logger.info("15 {}", saveInfoArea.getErrAcctRecord().toString()); 

// *
//  MOVE 999 TO RLCBM-INVOICE-NO RLCBM-ECPD-PROFILE-ID RLCBM-ACTIVE-MTNS-QTY
          rlcbmBillMessageRec.setRlcbmInvoiceNo((long)999);
          rlcbmBillMessageRec.setRlcbmEcpdProfileId(999);
          rlcbmBillMessageRec.setRlcbmActiveMtnsQty(999);
  
//  MOVE ALL 'A' TO RLCBM-CUST-TYP-CD
          rlcbmBillMessageRec.setRlcbmCustTypCd(CONSTANTS.LITERAL_AA);
  
//  INITIALIZE RLCBM-INVOICE-NO RLCBM-CUST-TYP-CD RLCBM-ECPD-PROFILE-ID RLCBM-ACTIVE-MTNS-QTY
          rlcbmBillMessageRec.setRlcbmInvoiceNo(0);
          rlcbmBillMessageRec.setRlcbmCustTypCd(CONSTANTS.SPACE_2 /* Fill 2 Spaces*/);
          rlcbmBillMessageRec.setRlcbmEcpdProfileId(0);
          rlcbmBillMessageRec.setRlcbmActiveMtnsQty(0);
  
//  DISPLAY '16 ' RLCBM-INVOICE-NO RLCBM-CUST-TYP-CD RLCBM-ECPD-PROFILE-ID RLCBM-ACTIVE-MTNS-QTY
          logger.info("16 {}{}{}{}", String.valueOf(rlcbmBillMessageRec.getRlcbmInvoiceNo()), new String(rlcbmBillMessageRec.getRlcbmCustTypCd()), String.valueOf(rlcbmBillMessageRec.getRlcbmEcpdProfileId()), String.valueOf(rlcbmBillMessageRec.getRlcbmActiveMtnsQty())); 
  

// *
//  MOVE 999 TO WS-CUST-FLG-USG-CTR WS-CUST-USG-CTR
          programCounters.setCustFlgUsgCtr(BigDecimal.valueOf(999));
          programCounters.setCustUsgCtr(BigDecimal.valueOf(999));
  
//  MOVE ALL 'A' TO WS-BYPASS-ACCT-FLAG WS-ERR-REJ-FLAG
          work.setBypassAcctFlag(CONSTANTS.LITERAL_A);
          work.setErrRejFlag(CONSTANTS.LITERAL_A);
//  INITIALIZE WS-CUST-FLG-USG-CTR WS-CUST-USG-CTR WS-BYPASS-ACCT-FLAG WS-ERR-REJ-FLAG
          programCounters.setCustFlgUsgCtr(BigDecimal.ZERO);
          programCounters.setCustUsgCtr(BigDecimal.ZERO);
          work.setBypassAcctFlag(CONSTANTS.SPACE /* Fill 1 Spaces*/);
          work.setErrRejFlag(CONSTANTS.SPACE /* Fill 1 Spaces*/);
  
//  DISPLAY '17 ' WS-CUST-FLG-USG-CTR WS-CUST-USG-CTR WS-BYPASS-ACCT-FLAG WS-ERR-REJ-FLAG
          logger.info("17 {}{}{}{}", String.valueOf(programCounters.getCustFlgUsgCtr().movePointRight(2)), String.valueOf(programCounters.getCustUsgCtr().movePointRight(2)), new String(work.getBypassAcctFlag()), new String(work.getErrRejFlag())); 
  
//  INITIALIZE BILRLU5F
          bilrlu5f.initialize();
//  DISPLAY '18 ' BILRLU5F
          logger.info("18 {}", bilrlu5f.toString()); 
//  MOVE ALL '9' TO WS-TEST1
          test1.setString(CONSTANTS.LITERAL_99999999999999999999999999);
//  INITIALIZE WS-TEST1
          test1.initialize();
//  DISPLAY '19 WS-TEST1 ' WS-TEST1
          logger.info("19 WS-TEST1 {}", test1.toString()); 
//  MOVE ALL '8' TO WS-TEST1
          test1.setString(CONSTANTS.LITERAL_88888888888888888888888888);
//  INITIALIZE WS-TEST1
          test1.initialize();
//  DISPLAY '20 WS-TEST1 ' WS-TEST1
          logger.info("20 WS-TEST1 {}", test1.toString()); 
//  INITIALIZE WS-6IYP-DATA
          iypData6.initialize();
//  DISPLAY '21 WS-6IYP-DATA ' WS-6IYP-DATA
          logger.info("21 WS-6IYP-DATA {}", iypData6.toString()); 
//  INITIALIZE FILLER-BEGIN-END
          fillerBeginEnd.initialize();
//  DISPLAY '22 FILLER-BEGIN-END ' FILLER-BEGIN-END
          logger.info("22 FILLER-BEGIN-END {}", fillerBeginEnd.toString()); 
//  INITIALIZE FILLER-BEGIN-END-MID
          fillerBeginEndMid.initialize();
//  DISPLAY '23 FILLER-BEGIN-END-MID ' FILLER-BEGIN-END-MID
          logger.info("23 FILLER-BEGIN-END-MID {}", fillerBeginEndMid.toString()); 
//  INITIALIZE FILLER-BEGIN-END1
          fillerBeginEnd1.initialize();
//  DISPLAY '24 FILLER-BEGIN-END1 ' FILLER-BEGIN-END1
          logger.info("24 FILLER-BEGIN-END1 {}", fillerBeginEnd1.toString()); 
//  INITIALIZE FILLER-BEGIN-END-MID1
          fillerBeginEndMid1.initialize();
//  DISPLAY '25 FILLER-BEGIN-END-MID1 ' FILLER-BEGIN-END-MID1
          logger.info("25 FILLER-BEGIN-END-MID1 {}", fillerBeginEndMid1.toString()); 

// *
// *
//  PERFORM WITH TEST BEFORE VARYING I1 FROM 1 BY 1 UNTIL I1 > MESSAGE-MAX-CNT
          for (work.setI1(1); (	( work.getI1() <= work.getMessageMaxCnt() ) ) ; work.setI1(work.getI1() + 1) ) {
//  INITIALIZE MESSAGES OF XCPRS01 (I1)
              xcprs01.getMessagesX().getMessages(work.getI1() - 1).initialize();
          }
//  DISPLAY '26 MESSAGE-SEVERITY(3) = ' MESSAGE-SEVERITY (3)
          logger.info("26 MESSAGE-SEVERITY(3) = {}", new String(xcprs01.getMessagesX().getMessages(2).getMessageSeverity())); 
//  DISPLAY '27 MESSAGE-DESCRIPTION-LEN(4) = ' MESSAGE-DESCRIPTION-LEN (4)
          logger.info("27 MESSAGE-DESCRIPTION-LEN(4) = {}", String.valueOf(xcprs01.getMessagesX().getMessages(3).getMessageDescription().getMessageDescriptionLen())); 

// *
//  INITIALIZE WV-EXTR-RECORD
          wvExtrRecord.initialize();
//  DISPLAY '29 WV-EXTR-DETAILS = '
          logger.info("29 WV-EXTR-DETAILS = "); 
//  DISPLAY '    (' WV-EXTR-DETAILS (1 : 100) ')'
          logger.info("    ({})", new String(substring(wvExtrRecord.getWvExtrDetails().toCharArray(),0,100))); 
//  DISPLAY '    (' WV-EXTR-DETAILS (101 : 100) ')'
          logger.info("    ({})", new String(substring(wvExtrRecord.getWvExtrDetails().toCharArray(),100,200))); 
//  DISPLAY '    (' WV-EXTR-DETAILS (201 : 100) ')'
          logger.info("    ({})", new String(substring(wvExtrRecord.getWvExtrDetails().toCharArray(),200,300))); 
//  DISPLAY '    (' WV-EXTR-DETAILS (301 : 100) ')'
          logger.info("    ({})", new String(substring(wvExtrRecord.getWvExtrDetails().toCharArray(),300,400))); 
//  DISPLAY '    (' WV-EXTR-DETAILS (401 : 100) ')'
          logger.info("    ({})", new String(substring(wvExtrRecord.getWvExtrDetails().toCharArray(),400,500))); 
//  DISPLAY '    (' WV-EXTR-DETAILS (501 : 100) ')'
          logger.info("    ({})", new String(substring(wvExtrRecord.getWvExtrDetails().toCharArray(),500,600))); 
//  DISPLAY '    (' WV-EXTR-DETAILS (601 : ) ')'
          logger.info("    ({})", new String(substring(wvExtrRecord.getWvExtrDetails().toCharArray(),600,1224))); 

// *
//  DISPLAY '30 WV-EXTR-LDG-BBL = (' WV-EXTR-LDG-BBL ')'
          logger.info("30 WV-EXTR-LDG-BBL = ({})", new String(wvExtrLdgBblX.getWvExtrLdgBbl())); 
  
//  DISPLAY '31 WV-EXTR-ACT-DENSITY = (' WV-EXTR-ACT-DENSITY ')'
          logger.info("31 WV-EXTR-ACT-DENSITY = ({})", new String(wvExtrActDensityX.getWvExtrActDensity())); 
  
//  DISPLAY '32 WV-EXTR-LDG-M3-AMB  = (' WV-EXTR-LDG-M3-AMB ')'
          logger.info("32 WV-EXTR-LDG-M3-AMB  = ({})", new String(wvExtrLdgM3AmbX.getWvExtrLdgM3Amb())); 
  
//  DISPLAY '33  WV-EXTR-FRML-VERS  = (' WV-EXTR-FRML-VERS ')'
          logger.info("33  WV-EXTR-FRML-VERS  = ({})", new String(wvExtrDetails.getWvExtrFrmlVers())); 
  

// *
//  INITIALIZE WS-INPUT-REC
          inputRec.initialize();
//  DISPLAY '34  WS-INPUT-DEDUCTIONS(1) = ' WS-INPUT-DEDUCTIONS (1)
          logger.info("34  WS-INPUT-DEDUCTIONS(1) = {}", String.valueOf(inputRec.getInputDeductions(0).movePointRight(2))); 

// *
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          this.setProgramEnded(true);
          return ;
      
      }
  
  
      /**
* This method pre-initializes variables consistent with
* what a mainframe program would have done at the start of a program
*/
      @Override
      public void initVars() throws CFException {
      setProgramEnded(false);
          if(!isInitDone()) {
          	this.setRc(0);
          	setInitDone(true);
          }
        CFUtil.resetDecimalAsComma();
       }
  
  
  
  
  
  
  }
