DB2VARCH.dbQualifier=
# 
# End of DB2VARCH
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
inputValue1=
inputValue2=
DB2VARCL.dbQualifier=
# End of DB2VARCL
