<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="SmallParent" cobol:name="WS-SMALL-PARENT" cobol:offset="0" cobol:length="21" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Parent11" maxOccurs="1"  cobol:name="WS-PARENT-11" cobol:offset="0" cobol:length="10" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="Parent21" maxOccurs="1" cobol:name="WS-PARENT-21" cobol:offset="10" cobol:length="1" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Parent31" maxOccurs="1"  cobol:name="WS-PARENT-31" cobol:offset="11" cobol:length="10" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
