# Program OLDNEW | DD : SYS001 | RecordFormat : FixedLength | RecordLength : 80
OLDNEW.ddname.SYS001=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(+0)
OLDNEW.Sys001MipSpecrtOld=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(+0)
OLDNEW.Sys001MipSpecrtOld.DISP=SHR,KEEP,KEEP
OLDNEW.Sys001MipSpecrtOldCharSet=cp1047
OLDNEW.Sys001MipSpecrtOldCRLFflag=no
# Program OLDNEW | DD : SYS002 | RecordFormat : FixedLength | RecordLength : 80
OLDNEW.ddname.SYS002=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(+1)
OLDNEW.Sys002MipSpecrtNew=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(+1)
OLDNEW.Sys002MipSpecrtNew.DISP=SHR,KEEP,KEEP
OLDNEW.Sys002MipSpecrtNewCharSet=cp1047
OLDNEW.Sys002MipSpecrtNewCRLFflag=no
# 
# End of OLDNEW
