<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="ErrorMsg6003002" cobol:name="600-3002-ERROR-MSG" cobol:offset="0" cobol:length="49" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="ErrorMsg6003002Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="0" cobol:length="25" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FileDd6003002" maxOccurs="1"  cobol:name="600-3002-FILE-DD" cobol:offset="25" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ErrorMsg6003002Filler2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="31" cobol:length="16" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="16" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FileStat6003002" maxOccurs="1"  cobol:name="600-3002-FILE-STAT" cobol:offset="47" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
