  package com.cloudframe.app.sort.file;
  /* Java Code Generated by CloudFrame */
  
  import org.springframework.stereotype.Component;
  import com.cloudframe.app.utility.CFFile;
  import org.springframework.beans.factory.annotation.Value;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import org.springframework.batch.core.configuration.annotation.JobScope;
  
  @Component("Sgp7344dPrgp4511_step11aSortIn1")
  @JobScope
  public class Sgp7344dPrgp4511_step11aSortIn1 extends CFFile {
  	@Value("${Sgp7344dPrgp4511_step11aSortIn[1]:DTF.GP.P2BX.TGPAUKD.AKF.LOAD}")
  	private String fileName;
  
  	/**
  	 * This function is not required in this subclass for your program to work as intended. 
  	 * CloudFrame generated this function to provide you hints for the code you must write 
  	 * to change the implementation and remove runtime and license dependency on CloudFrame. 
  	 * Consult CloudFrame's customer wiki for additional information. https://wiki.cloudframe.com
  	 **/
  	public String getFileName() {
  		return fileName;
  	}
  	
  	/**
  	 * This function is not required in this subclass for your program to work as intended. 
  	 * CloudFrame generated this function to provide you hints for the code you must write 
  	 * to change the implementation and remove runtime and license dependency on CloudFrame. 
  	 * Consult CloudFrame's customer wiki for additional information. https://wiki.cloudframe.com
  	 **/	
  	@Override
  	public  void setFileName(String fileName) {
  		this.fileName = fileName;
  	}	
  
  	@Value("#{'${Sgp7344dPrgp4511_step11aSortIn1RecordType:${Sgp7344dPrgp4511_step11aSortInRecordType:FB}}'}")
  	private String recordType;
  
  	@Value("#{'${Sgp7344dPrgp4511_step11aSortIn1RecordLen:${Sgp7344dPrgp4511_step11aSortInRecordLen:80}}'}")
  	private int recordLen;
  	
  	public boolean isFBRec() {
    		return (recordType.startsWith("F")); //F/FB/FBA
    	}
  
    
  	public int getRecordLen() {
  		return recordLen;
  	}
  	
    
  	
  	public String getStatusString() {
  		if (status == 0) return "00";
  		else if (status == 10) return "10";
  		return String.format("%1$2s", status+"").replace(' ', '0');
  	}
  }
