<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="DrstEditErrorValueTxt" cobol:name="DRST-EDIT-ERROR-VALUE-TXT" cobol:offset="322" cobol:length="17" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="DrstEditErrorValueInt" maxOccurs="1"  cobol:name="DRST-EDIT-ERROR-VALUE-INT" cobol:offset="0" cobol:length="15" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="15" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DrstEditErrorValueDec" maxOccurs="1"  cobol:name="DRST-EDIT-ERROR-VALUE-DEC" cobol:offset="0" cobol:length="15" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="15" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
