<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="FesaKey1" cobol:name="FESA-KEY1" cobol:offset="0" cobol:length="25" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="FesaPolicy1" maxOccurs="1"  cobol:name="FESA-POLICY1" cobol:offset="0" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="FesaPlanVar1" type="xs:int" maxOccurs="1"  cobol:name="FESA-PLAN-VAR1" cobol:offset="6" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
         <xs:element name="FesaEffDate1" type="xs:int" maxOccurs="1"  cobol:name="FESA-EFF-DATE1" cobol:offset="11" cobol:length="7" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
         <xs:element name="FesaSpiNbr1" type="xs:int" maxOccurs="1"  cobol:name="FESA-SPI-NBR1" cobol:offset="18" cobol:length="7" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
