<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="FesaDateTimestamp" cobol:name="FESA-DATE-TIMESTAMP" cobol:offset="17" cobol:length="9" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="FesaDatestamp" type="xs:int" maxOccurs="1"  cobol:name="FESA-DATESTAMP" cobol:offset="0" cobol:length="4" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
         <xs:element name="FesaTimestamp" type="xs:int" maxOccurs="1"  cobol:name="FESA-TIMESTAMP" cobol:offset="4" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
