<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="FeSpiAltPlanRecord" cobol:name="FE-SPI-ALT-PLAN-RECORD" cobol:offset="0" cobol:length="31" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="FesaKey" maxOccurs="1" cobol:name="FESA-KEY" cobol:offset="0" cobol:length="17" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="FesaDateTimestamp" maxOccurs="1" cobol:name="FESA-DATE-TIMESTAMP" cobol:offset="17" cobol:length="9" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="FesaCanDt" type="xs:int" maxOccurs="1"  cobol:name="FESA-CAN-DT" cobol:offset="26" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
