<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="HdVariableDetailData" cobol:name="HD-VARIABLE-DETAIL-DATA" cobol:offset="31" cobol:length="1383" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="HdPmtiProvX" maxOccurs="1" cobol:name="HD-PMTI-PROV-X" cobol:offset="28" cobol:length="15" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="HdPmtiTin" type="xs:long" maxOccurs="1"  cobol:name="HD-PMTI-TIN" cobol:offset="28" cobol:length="13" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10T"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
