<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ioi02bReserveArea" cobol:name="IOI-02B-RESERVE-AREA" cobol:offset="350" cobol:length="120" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ioi02bWorkAreaAddr" type="xs:int" maxOccurs="1"  cobol:name="IOI-02B-WORK-AREA-ADDR" cobol:offset="0" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ioi02bWorkAreaPtr" type="xs:int" maxOccurs="1"  cobol:name="IOI-02B-WORK-AREA-PTR" cobol:offset="0" cobol:length="4" cobol:datatype="Pointer" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
         <xs:element name="Ioi02bInterfaceAddr" type="xs:int" maxOccurs="1"  cobol:name="IOI-02B-INTERFACE-ADDR" cobol:offset="4" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ioi02bInterfacePtr" type="xs:int" maxOccurs="1"  cobol:name="IOI-02B-INTERFACE-PTR" cobol:offset="4" cobol:length="4" cobol:datatype="Pointer" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
         <xs:element name="Ioi02bJournalAddr" type="xs:int" maxOccurs="1"  cobol:name="IOI-02B-JOURNAL-ADDR" cobol:offset="8" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Ioi02bJournalPtr" type="xs:int" maxOccurs="1"  cobol:name="IOI-02B-JOURNAL-PTR" cobol:offset="8" cobol:length="4" cobol:datatype="Pointer" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
