<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="M51uLinkage" cobol:name="M51U-LINKAGE" cobol:offset="2595" cobol:length="9345" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="UIcn51" maxOccurs="1"  cobol:name="LK-51U-ICN" cobol:offset="0" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="UIoRequest51" maxOccurs="1"  cobol:name="LK-51U-IO-REQUEST" cobol:offset="10" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="UCauseCd51" maxOccurs="1"  cobol:name="LK-51U-CAUSE-CD" cobol:offset="11" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="UProvType51" maxOccurs="1"  cobol:name="LK-51U-PROV-TYPE" cobol:offset="12" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="UPlanVar51" type="xs:short" maxOccurs="1"  cobol:name="LK-51U-PLAN-VAR" cobol:offset="14" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="UPolicyNo51" maxOccurs="1"  cobol:name="LK-51U-POLICY-NO" cobol:offset="16" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="UDiagnosisCode51" maxOccurs="25"  cobol:name="LK-51U-DIAGNOSIS-CODE" cobol:offset="22" cobol:length="7" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="UIcdVerNbr51" maxOccurs="1"  cobol:name="LK-51U-ICD-VER-NBR" cobol:offset="197" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="UMedicalClaim51" maxOccurs="1"  cobol:name="LK-51U-MEDICAL-CLAIM" cobol:offset="198" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="USourceInd51" maxOccurs="1"  cobol:name="LK-51U-SOURCE-IND" cobol:offset="199" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="UEarliestDos51" type="xs:long" maxOccurs="1"  cobol:name="LK-51U-EARLIEST-DOS" cobol:offset="200" cobol:length="8" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
         <xs:element name="UNbrOfLines51" type="xs:short" maxOccurs="1"  cobol:name="LK-51U-NBR-OF-LINES" cobol:offset="208" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
<xs:element name="ULineData51" maxOccurs="120" cobol:name="LK-51U-LINE-DATA" cobol:offset="211" cobol:length="36" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="UCpeDescCd51" maxOccurs="1"  cobol:name="LK-51U-CPE-DESC-CD" cobol:offset="4531" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="UOutLineData51" maxOccurs="120" cobol:name="LK-51U-OUT-LINE-DATA" cobol:offset="4535" cobol:length="40" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="UStopAutoSw51" maxOccurs="1"  cobol:name="LK-51U-STOP-AUTO-SW" cobol:offset="9335" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="UOutCauseCd51" maxOccurs="1"  cobol:name="LK-51U-OUT-CAUSE-CD" cobol:offset="9336" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="USlotPlanVar51" type="xs:short" maxOccurs="1"  cobol:name="LK-51U-SLOT-PLAN-VAR" cobol:offset="9337" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="USlotPolicyNo51" maxOccurs="1"  cobol:name="LK-51U-SLOT-POLICY-NO" cobol:offset="9339" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
