package com.cloudframe.app.ar640010.dto;

/**
*  The class ErrorTableGroup590 is used to handle fields declared in it
*  @author CloudFrame Inc.
*  created on 2025-04-28 at 07:11. using version 5.0.0.256
**/


import com.cloudframe.app.ar640010.dto.serialize.*;
import com.cloudframe.app.exception.CFException;
import com.cloudframe.app.data.Field;


public class ErrorTableGroup590 extends ErrorTableGroup590Serialized {
   

						private char[] errorTable590 = new char[18684];
					private ErrorTable590Redefined errorTable590Redefined = new ErrorTable590Redefined();
	
	/**
	* Constructor for ErrorTableGroup590
	**/
    public ErrorTableGroup590() {
		super();
		/*  set the parent of each child as this which are a group variable */
	       			errorTable590Redefined.setParent(this,getStartOffset() + 0);
	   	/*  end of offset */
								setErrorTable590("0100APPLICATION FILE-ALLOCATE ERROR (MCDYNAM)         0101APPLICATION FILE-OPEN ERROR (MCSEQIO)             0102APPLICATION FILE-READ ERROR (MCSEQIO)             0103APPLICATION FILE-CLOSE ERROR (MCSEQIO)            0104APPLICATION FILE-UNALLOCATE ERROR (MCDYNAM)       0105APPLICATION FILE-DELETE|ALLOCATION ERROR (MCDYNAM)0106APPLICATION FILE-DELETE|OPEN ERROR (MCSEQIO)      0107APPLICATION FILE-DELETE|CLOSE ERROR (MCSEQIO)     0108APPLICATION FILE-IN USE BY OTHER JOB/USER(MCDYNAM)0109APPLICATION FILE AND GFT FILE COUNTS DO NOT MATCH 0110GFT FILE-ALLOCATE ERROR (MCDYNAM)                 0111GFT FILE-OPEN ERROR (MCSEQIO)                     0112GFT FILE-WRITE ERROR (MCSEQIO)                    0113GFT FILE-CLOSE ERROR (MCSEQIO)                    0114GFT FILE-UNALLOCATE ERROR (MCDYNAM)               0115GFT FILE - DELETE|ALLOCATE ERROR (MCDYNAM)        0116GFT FILE - DELETE|OPEN ERROR (MCSEQIO)            0117GFT FILE - DELETE|CLOSE ERROR (MCSEQIO)           0118GFT FILE-IN USE BY OTHER JOB/USER (MCDYNAM)       0119GFT UNIQUE ROTORIZED DATASET NAMES ARE UNAVAILABLE0120TRANSFER STATUS-SQL INSERT ERROR (FXS)            0121ENDPOINT FILE PROFILE-SQL SELECT NOT FOUND (EFP)  0122ENDPOINT FILE PROFILE-SQL SELECT ERROR (EFP)      0200APPLICATION FILE-ALLOCATE ERROR (MCDYNAM)         0201APPLICATION FILE-OPEN ERROR (MCSEQIO)             0202APPLICATION FILE-READ ERROR (MCSEQIO)             0203APPLICATION FILE-CLOSE ERROR (MCSEQIO)            0204APPLICATION FILE-UNALLOCATE ERROR (MCDYNAM)       0205APPLICATION FILE-DELETE|ALLOCATION ERROR (MCDYNAM)0206APPLICATION FILE-DELETE|OPEN ERROR (MCSEQIO)      0207APPLICATION FILE-DELETE|CLOSE ERROR (MCSEQIO)     0208APPLICATION FILE-IN USE BY OTHER JOB/USER(MCDYNAM)0209APPLICATION FILE AND GFT FILE COUNTS DO NOT MATCH 0210GFT FILE-ALLOCATE ERROR (MCDYNAM)                 0211GFT FILE-OPEN ERROR (MCSEQIO)                     0212GFT FILE-WRITE ERROR (MCSEQIO)                    0213GFT FILE-CLOSE ERROR (MCSEQIO)                    0214GFT FILE-UNALLOCATE ERROR (MCDYNAM)               0215GFT FILE - DELETE|ALLOCATE ERROR (MCDYNAM)        0216GFT FILE - DELETE|OPEN ERROR (MCSEQIO)            0217GFT FILE - DELETE|CLOSE ERROR (MCSEQIO)           0218GFT FILE-IN USE BY OTHER JOB/USER (MCDYNAM)       0219GFT UNIQUE ROTORIZED DATASET NAMES ARE UNAVAILABLE0220TRANSFER STATUS-SQL INSERT ERROR (FXS)            0221ENDPOINT FILE PROFILE-SQL OPEN ERROR (EFP)        0222ENDPOINT FILE PROFILE-SQL FETCH ERROR (EFP)       0223ENDPOINT FILE PROFILE-SQL CLOSE ERROR (EFP)       0224ENDPOINT FILE PROFILE-SQL SELECT ERROR (EFP)      0225ENDPOINT PROFILE-SQL SELECT ERROR (EPT)           0226ENDPOINT FILE PROFILE-SQL SELECT ERR (B/U EFP)    0227ENDPOINT PROFILE-SQL SELECT ERROR (B/U EPT)       0228BROADCAST RESULT DD FILE-OPEN ERROR (MCSEQIO)     0229BROADCAST RESULT DD FILE-WRITE ERROR (MCSEQIO)    0230BROADCAST RESULT DD FILE-CLOSE ERROR (MCSEQIO)    0231BROADCAST BDIO DUPE CHECK-SELECT ERROR (FXS)      0232BROADCAST BDIO DUPE CHECK-SELECT ERROR (FXA)      0301TRANSFER STATUS-SQL COUNT|SELECT ERROR (FXS)      0302BULK ID TYPE IS OUTBOUND (WILL COUNT ONLY INBOUND)0400APPLICATION FILE-ALLOCATE ERROR (MCDYNAM)         0401APPLICATION FILE-OPEN ERROR (MCSEQIO)             0402APPLICATION FILE-READ ERROR (MCSEQIO)             0403APPLICATION FILE-CLOSE ERROR (MCSEQIO)            0404APPLICATION FILE-UNALLOCATE ERROR (MCDYNAM)       0405APPLICATION FILE-DELETE|ALLOCATION ERROR (MCDYNAM)0406APPLICATION FILE-DELETE|OPEN ERROR (MCSEQIO)      0407APPLICATION FILE-DELETE|CLOSE ERROR (MCSEQIO)     0408APPLICATION FILE-IN USE BY OTHER JOB/USER(MCDYNAM)0409APPLICATION FILE AND GFT FILE COUNTS DO NOT MATCH 0410GFT FILE-ALLOCATE ERROR (MCDYNAM)                 0411GFT FILE-OPEN ERROR (MCSEQIO)                     0412GFT FILE-WRITE ERROR (MCSEQIO)                    0413GFT FILE-CLOSE ERROR (MCSEQIO)                    0414GFT FILE-UNALLOCATE ERROR (MCDYNAM)               0415GFT FILE-DELETE|ALLOCATE ERROR (MCDYNAM)          0416GFT FILE-DELETE|OPEN ERROR (MCSEQIO)              0417GFT FILE-DELETE|CLOSE ERROR (MCSEQIO)             0418GFT FILE-IN USE BY OTHER JOB/USER (MCDYNAM)       0419GFT UNIQUE ROTORIZED DATASET NAMES ARE UNAVAILABLE0420TRANSFER STATUS-SQL INSERT ERROR (FXS)            0421ENDPOINT FILE PROFILE-SQL SELECT ERROR (EFP)      0422ENDPOINT PROFILE-SQL SELECT ERROR (EPT)           0423ENDPOINT FILE PROFILE-SQL SELECT ERR (B/U EFP)    0424ENDPOINT PROFILE-SQL SELECT ERROR (B/U EPT)       0425BROADCAST LISTDD-OPEN ERROR (MCSEQIO)             0426BROADCAST LISTDD-READ ERROR (MCSEQIO)             0427BROADCAST LISTDD-CLOSE ERROR (MCSEQIO)            0428BROADCAST RESULT DD FILE-OPEN ERROR (MCSEQIO)     0429BROADCAST RESULT DD FILE-WRITE ERROR (MCSEQIO)    0430BROADCAST RESULT DD FILE-CLOSE ERROR (MCSEQIO)    0431BROADCAST BDIO DUPE CHECK-SELECT ERROR (FXS)      0432BROADCAST BDIO DUPE CHECK-SELECT ERROR (FXA)      0500APPLICATION FILE-ALLOCATE ERROR (MCDYNAM)         0501APPLICATION FILE-OPEN ERROR (MCSEQIO)             0502APPLICATION FILE-WRITE ERROR (MCSEQIO)            0503APPLICATION FILE-CLOSE ERROR (MCSEQIO)            0504APPLICATION FILE-UNALLOCATE ERROR (MCDYNAM)       0505APPLICATION FILE-DELETE|ALLOCATION ERROR (MCDYNAM)0506APPLICATION FILE-DELETE|OPEN ERROR (MCSEQIO)      0507APPLICATION FILE-DELETE|CLOSE ERROR (MCSEQIO)     0508APPLICATION FILE-IN USE BY OTHER JOB/USER(MCDYNAM)0509APPLICATION FILE-ALREADY EXISTS (DSN IN CATALOG)  0510GFT FILE-ALLOCATE ERROR (MCDYNAM)                 0511GFT FILE-OPEN ERROR (MCSEQIO)                     0512GFT FILE-READ ERROR (MCSEQIO)                     0513GFT FILE-CLOSE ERROR (MCSEQIO)                    0514GFT FILE-UNALLOCATE ERROR (MCDYNAM)               0518GFT FILE-IN USE BY OTHER JOB/USER (MCDYNAM)       0519APPLICATION FILE AND GFT FILE COUNTS DO NOT MATCH 0520TRANSFER STATUS-FILE NOT READY TO BE RETRIEVED    0521TRANSFER STATUS-SQL SELECT NOT FOUND (FXS)        0522TRANSFER STATUS-SQL OPEN ERROR (FXS)              0523TRANSFER STATUS-SQL FETCH ERROR (FXS)             0524TRANSFER STATUS-SQL CLOSE ERROR (FXS)             0525TRANSFER STATUS-SQL SELECT ERROR (FXS)            0526ENDPOINT FILE PROFILE-SQL SELECT NOT FOUND (EFP)  0527ENDPOINT FILE PROFILE-SQL SELECT ERROR (EFP)      0528ENDPOINT PROFILE-SQL SELECT NOT FOUND (EPT)       0529ENDPOINT PROFILE-SQL SELECT ERROR (EPT)           0530TRANSFER STATUS-SQL UPLOAD|SELECT NOT FOUND (FXS) 0531TRANSFER STATUS-SQL UPLOAD|UPDATE ERROR (FXS)     0532TRANSFER STATUS-SQL UPLOAD|COMMIT ERROR (FXS)     0533TRANSFER STATUS-SQL COMPLETE|SELECT NOT FOUND(FXS)0534TRANSFER STATUS-SQL COMPLETE|SELECT ERR (FXS)     0535TRANSFER STATUS-SQL COMPLETE|COMMIT ERR (FXS)     0536TRANSFER STATUS-SQL PENDING|SELECT NOT FOUND (FXS)0537TRANSFER STATUS-SQL PENDING|UPDATE ERROR (FXS)    0538TRANSFER STATUS-SQL PENDING|COMMIT ERROR (FXS)    0600APPLICATION FILE-ALLOCATE ERROR (MCDYNAM)         0601APPLICATION FILE-OPEN ERROR (MCSEQIO)             0602APPLICATION FILE-READ ERROR (MCSEQIO)             0603APPLICATION FILE-CLOSE ERROR (MCSEQIO)            0604APPLICATION FILE-UNALLOCATE ERROR (MCDYNAM)       0605APPLICATION FILE-DELETE|ALLOCATION ERROR (MCDYNAM)0606APPLICATION FILE-DELETE|OPEN ERROR (MCSEQIO)      0607APPLICATION FILE-DELETE|CLOSE ERROR (MCSEQIO)     0608APPLICATION FILE-IN USE BY OTHER JOB/USER(MCDYNAM)0609APPLICATION FILE AND GFT FILE COUNTS DO NOT MATCH 0610GFT FILE-ALLOCATE ERROR (MCDYNAM)                 0611GFT FILE-OPEN ERROR (MCSEQIO)                     0612GFT FILE-WRITE ERROR (MCSEQIO)                    0613GFT FILE-CLOSE ERROR (MCSEQIO)                    0614GFT FILE-UNALLOCATE ERROR (MCDYNAM)               0615GFT FILE - DELETE|ALLOCATE ERROR (MCDYNAM)        0616GFT FILE - DELETE|OPEN ERROR (MCSEQIO)            0617GFT FILE - DELETE|CLOSE ERROR (MCSEQIO)           0618GFT FILE-IN USE BY OTHER JOB/USER (MCDYNAM)       0619GFT UNIQUE ROTORIZED DATASET NAMES ARE UNAVAILABLE0620TRANSFER STATUS-SQL INSERT ERROR (FXS)            0621ENDPOINT FILE PROFILE-SQL SELECT ERROR (EFP)      0622ENDPOINT PROFILE-SQL SELECT ERROR (EPT)           0623ENDPOINT FILE PROFILE-SQL SELECT ERROR (B/U EFP)  0624ENDPOINT PROFILE-SQL SELECT ERROR (B/U EPT)       0625ENDPOINT PROFILE-ENDPT (EPT) B/U CHAIN BROKEN     0626ENDPOINT PROFILE-ENDPT(EPT) B/U CHAIN LOOPS       0701TRANSFER STATUS-SQL SELECT NOT FOUND (FXS/FXA)    0702TRANSFER STATUS-SQL OPEN ERROR (FXA)              0703TRANSFER STATUS-SQL FETCH ERROR (FXA)             0704TRANSFER STATUS-SQL CLOSE ERROR (FXA)             0705TRANSFER STATUS-SQL SELECT ERROR (FXS/FXA)        0706TRANSFER STATUS NOT APPLCABLE FOR \"RESET\" FUNCTION0707TRANSFER STATUS-SQL INSERT ERROR (FXS)            0708ENDPOINT FILE PROFILE-SQL SELECT NOT FOUND (EFP)  0709ENDPOINT FILE PROFILE-SQL SELECT ERROR (EFP)      0710TRANSFER STATUS-SQL UPDATE|SELECT NOT FOUND (FXS) 0711TRANSFER STATUS-SQL UPDATE|UPDATE ERROR (FXS)     0712TRANSFER STATUS-SQL UPDATE|COMMIT ERROR (FXS)     0800APPLICATION FILE-ALLOCATE ERROR (MCDYNAM)         0801APPLICATION FILE-OPEN ERROR (MCSEQIO)             0802APPLICATION FILE-READ ERROR (MCSEQIO)             0803APPLICATION FILE-CLOSE ERROR (MCSEQIO)            0804APPLICATION FILE-UNALLOCATE ERROR (MCDYNAM)       0805APPLICATION FILE-DELETE|ALLOCATION ERROR (MCDYNAM)0806APPLICATION FILE-DELETE|OPEN ERROR (MCSEQIO)      0807APPLICATION FILE-DELETE|CLOSE ERROR (MCSEQIO)     0808APPLICATION FILE-IN USE BY OTHER JOB/USER(MCDYNAM)0809APPLICATION FILE AND GFT FILE COUNTS DO NOT MATCH 0810GFT FILE-ALLOCATE ERROR (MCDYNAM)                 0811GFT FILE-OPEN ERROR (MCSEQIO)                     0812GFT FILE-WRITE ERROR (MCSEQIO)                    0813GFT FILE-CLOSE ERROR (MCSEQIO)                    0814GFT FILE-UNALLOCATE ERROR (MCDYNAM)               0815GFT FILE - DELETE|ALLOCATE ERROR (MCDYNAM)        0816GFT FILE - DELETE|OPEN ERROR (MCSEQIO)            0817GFT FILE - DELETE|CLOSE ERROR (MCSEQIO)           0818GFT FILE-IN USE BY OTHER JOB/USER (MCDYNAM)       0819GFT POST-APPL EXIT DSN EXISTS IN TARAFXS/SYS CATAL0820TRANSFER STATUS-SQL INSERT ERROR (FXS)            0821TRANSFER STATUS-SQL OPEN ERROR (FXS)              0822TRANSFER STATUS-SQL FETCH ERROR (FXS)             0823TRANSFER STATUS-SQL CLOSE ERROR (FXS)             0824TRANSFER STATUS-SQL SELECT NOT FOUND (FXS)        0825TRANSFER STATUS-SQL SELECT ERROR (FXS)            0826ENDPOINT PROFILE-SQL SELECT ERROR (EPT)           0827TRANSFER STATUS-SQL COMPLETE|SELECT NOT FOUND(FXS)0828TRANSFER STATUS-SQL COMPLETE|UPDATE ERR (FXS)     0829TRANSFER STATUS-SQL EXIT|FETCH EMPTY (FXS)        0830TRANSFER STATUS GFT FILE ROW HAS NO EXIT NAME INFO0831TRANSFER STATUS GFT FILE ROW STATUS CODE NOT = \"X\"0832INSTALL RESULT DD FILE-OPEN ERROR (MCSEQIO)       0833INSTALL RESULT DD FILE-WRITE ERROR (MCSEQIO)      0834INSTALL RESULT DD FILE-CLOSE ERROR (MCSEQIO)      0835MULTIPLE ENDPNT FILE PROF-SQL SELECT NOTFND (EFP) 0836MULTIPLE ENDPNT FILE PROF-SQL SELECT ERROR (EFP)  0837STANDARD ENDPNT FILE PROF-SQL SELECT NOTFND (EFP) 0838STANDARD ENDPNT FILE PROF-SQL SELECT ERROR (EFP)  0839TRANSFER STATUS-SQL SELECT CHECK/ERROR (FXS)      9000REQUEST/FUNCTION (CODE) IS INVALID (OR UNKNOWN)   9011FILE PROFILE-RECORD FORMAT SPEC VALUE UNACCEPTABLE9012FILE PROFILE-RECORD LENGTH SPEC VALUE UNACCEPTABLE9013FILE PROFILE-BLOCK SIZE SPEC VALUE UNACCEPTABLE   9014FILE PROFILE-SYSTEM ID = GFT - RETRIEVE IMPOSSIBLE9021APPLICATION FILE-RECORD FORMAT UNACCEPTABLE       9022APPLICATION FILE-RECORD LENGTH UNACCEPTABLE       9023APPLICATION FILE-BLOCK SIZE UNACCEPTABLE          9024APPLICATION FILE-ALLOCATION UNIT TYPE UNACCEPTABLE9031GFT FILE-RECORD FORMAT UNACCEPTABLE               9032GFT FILE-RECORD LENGTH UNACCEPTABLE               9033GFT FILE-BLOCK SIZE UNACCEPTABLE                  9034GFT FILE-ALLOCATION UNIT TYPE UNACCEPTABLE        9045APPL EXIT ROUTINE TARAEFP COLUMN FORMAT IS INVALID9101CONTROL FILE PARAMETER-DATABASE IDENTIFIER INVALID9102CONTROL FILE PARAMETER-DATABASE PACKAGESET INVALID9103CONTROL FILE PARAMETER-DSN HILVL QUALIFIER INVALID9200CONNECTIVITY-USER DATABASE SQL STORE|SET ERROR    9201CONNECTIVITY-USER PACKAGESET SQL STORE|SET ERROR  9202CONNECTIVITY-USER PACKAGESET SQL RESTORE|SET ERROR9203CONNECTIVITY-USER DATABASE SQL RESTORE|SET ERROR  9212CONNECTIVITY-GFT DATABASE SQL SET ERROR           9213CONNECTIVITY-GFT PACKAGESET SQL SET ERROR         9214CONNECTIVITY-GFT DATABASE SQL RELEASE ERROR       9218CONNECTIVITY-GFT DATABASE SQL ROLLBACK ERROR      9219CONNECTIVITY-GFT DATABASE SQL COMMIT ERROR        9300DYNAMIC ALLOCATION-LINK FOR \"INIT\" ERROR (MCDYNAM)9309DYNAMIC ALLOCATION-LINK FOR \"END\" ERROR (MCDYNAM) 9310LISTDSI-LINKAGE PARAMETER ERROR (AR642010)        9311LISTDSI-TSOE ENVIR (IKJTSOEV) CALL ERR (AR642010) 9312LISTDSI-REXX EXEC (IRXEXEC) CALL ERROR (AR642010) 9313LISTDSI-REXX EXEC FUNCTION/RETURN ERROR (AR642010)9314LISTDSI-REXX \"RETURNED PARAMETER\" ERROR (AR642010)9315LISTDSI-RELATIVE GDG NOT FOUND (AR642010)         9316LISTDSI-PDS MEMBER NOT FOUND (AR642010)           9317LISTDSI-PDS IS \"PROTECTED\" (AR642010)             9318LISTDSI-PDS IS \"NOT AVAILABLE\" (AR642010)         9319LISTDSI-RETURN CODE (AR642010) UNKNOWN TO API MGR 9320ACTION CODE (IN LINKAGE AREA) IS IN ERROR         9321ACTION WAS NOT IN LOGICAL ORDER (OPEN/WRITE/CLOSE)9322SYSLST COBOL I/O ERROR (SEE THE AR648010 MESSAGES)9323AR648010 RE-ENTERED AFTER SYSLST COBOL I/O ERROR  9329AR648010 RETURN CODE UNKNOWN TO API MANAGER       9331RENAME-TSOE ENVIR (IKJTSOEV) CALL ERR (AR647010)  9332RENAME-REXX EXEC (IRXEXEC) CALL ERROR (AR647010)  9333RENAME-REXX EXEC FUNCTION/RETURN ERROR (AR647010) 9334RENAME-NEW DSN ALREADY EXISTS IN CATAL (AR647010) 9335RENAME-APPL FILE IN USE BY OTHER JOB/USR(AR647010)9336RENAME-APPL FILE IS NOT CATALOGUED (AR647010)     9337RENAME-APPL DATA SET NAME IS INVALID (AR647010)   9338RENAME-GFT DATA SET NAME IS INVALID (AR647010)    9339AR647010 RETURN CODE UNKNOWN TO API MANAGER       9340AR649010 CONFIGURATION UTILITY ENCOUNTERED ERROR  9341MCINFO ENCOUNTERED AN ERROR CONDITION             9400COPYBOOK PROGRAM ID ERROR - NOTIFY GFT SYSTEMS    9401COPYBOOK DATE ERROR - NOTIFY GFT SYSTEMS          9402COPYBOOK MODIFICATION ERROR - NOTIFY GFT SYSTEMS  9410BULK ID PARM-NOT FOUND ON FILE PROFILE (FPL)      9411FILE PROFILE-SQL SELECT ERROR (FPL)               9412BULK ID PARM-REQUEST -VS- BULK DIRECTION CONFLICTS9419BULK ID PARM-REQUIRED BUT MISSING                 9420ENDPT ID PARM-NOT FOUND ON ENDPT PROFILE (EPT)    9421ENDPOINT PROFILE-SQL SELECT ERROR (EPT)           9429ENDPT ID PARM-REQUIRED BUT MISSING                9430DELETE INDICATOR PARM-VALUE INVALID               9439DELETE INDICATOR PARM-REQUIRED BUT MISSING        9440CYCLE NUMBER PARM-VALUE NOT NUMERIC               9441FTSS SEQUENCE NUMBER-VALUE UNACCEPTABLE OR INVALID9449CYCLE NUMBER PARM-REQUIRED BUT MISSING            9450BROADCAST LISTDD FILE-INVALID SPECIFICATION       9451BROADCAST LISTDD FILE-DATASET NOT CATALOGUED      9452BROADCAST LISTDD FILE-DD NAME NOT IN JCL          9453BROADCAST LISTDD FILE-VSAM FILE UNACCEPTABLE      9454BROADCAST LISTDD FILE-TYPE (DSORG) NOT PROCESSED  9455BROADCAST LISTDD FILE-DD NAME INVALID             9456BROADCAST LISTDD FILE-PDS MEMBER NOT FOUND        9459BROADCAST LISTDD PARM-REQUIRED BUT MISSING        9460APPLICATION DSN FILE-INVALID SPECIFICATION        9461APPLICATION DSN FILE-NOT CATALOGUED               9462APPLICATION DSN FILE-DD NAME NOT IN JCL           9463APPLICATION DSN FILE-VSAM FILE UNACCEPTABLE       9464APPLICATION DSN FILE-TYPE (DSORG) NOT PROCESSED   9465APPLICATION DSN FILE-DD NAME INVALID              9466APPLICATION DSN FILE-PDS MEMBER NOT FOUND         9467APPLICATION DSN FILE-RELATIVE GDG NOT FOUND       9469APPLICATION DSN PARAMETER-REQUIRED BUT MISSING    9470GFT DSN FILE-INVALID SPECIFICATION                9471GFT DSN FILE-NOT CATALOGUED                       9472GFT DSN FILE-DD NAME NOT IN JCL                   9473GFT DSN FILE-VSAM FILE UNACCEPTABLE               9474GFT DSN FILE-TYPE (DSORG) NOT PROCESSED           9475GFT DSN FILE-DD NAME INVALID                      9479GFT DSN PARAMETER-REQUIRED BUT MISSING            9480BROADCAST RESULT DD FILE-INVALID SPECIFICATION    9481BROADCAST RESULT DD FILE-NOT CATALOGUED           9482BROADCAST RESULT DD FILE-DD NAME NOT IN JCL       9483BROADCAST RESULT DD FILE-VSAM FILE UNACCEPTABLE   9484BROADCAST RESULT DD FILE-TYPE(DSORG) NOT PROCESSED9485BROADCAST RESULT DD FILE-DD NAME INVALID          9486BROADCAST RESULT DD PARM-OPTION/DDNAME INVALID    9489BROADCAST RESULT DD PARM-REQUIRED BUT MISSING     9490PROCESS DATE - FORMAT INVALID (VALID: YYYY-MM-DD) 9491PROCESS DATE - YEAR VALUE INVALID OR UNACCEPTABLE 9492PROCESS DATE - MONTH VALUE INVALID                9493PROCESS DATE - DAY VALUE INVALID                  9494PROCESS DATE - DAY NOT VALID FOR MONTH SPECIFIED  9512CONFLICT-CONTROL DD NAME -VS- APPLICATION DD NAME 9513CONFLICT-CONTROL DD NAME -VS- GFT DD NAME         9514CONFLICT-CONTROL DD NAME -VS- LISTDD DD NAME      9515CONFLICT-CONTROL DD NAME -VS- RESULT DD NAME      9523CONFLICT-APPLICATION DD NAME -VS- GFT DD NAME     9524CONFLICT-APPLICATION DD NAME -VS- LISTDD DD NAME  9525CONFLICT-APPLICATION DD NAME -VS- RESULT DD NAME  9534CONFLICT-GFT DD NAME -VS- LISTDD DD NAME          9535CONFLICT-GFT DD NAME -VS- RESULT DD NAME          9545CONFLICT-LISTDD DD NAME -VS- RESULT DD NAME       9612CONFLICT-CONTROL DSN -VS- APPLICATION DSN         9613CONFLICT-CONTROL DSN -VS- GFT DSN                 9614CONFLICT-CONTROL DSN -VS- LISTDD DSN              9615CONFLICT-CONTROL DSN -VS- RESULT DSN              9623CONFLICT-APPLICATION DSN -VS- GFT DSN             9624CONFLICT-APPLICATION DSN -VS- LISTDD DSN          9625CONFLICT-APPLICATION DSN -VS- RESULT DSN          9634CONFLICT-GFT DSN -VS- LISTDD DSN                  9635CONFLICT-GFT DSN -VS- RESULT DSN                  9645CONFLICT-LISTDD DSN -VS- RESULT DSN               9900CONTROL FILE-OPEN ERROR (MCSEQIO)                 9901CONTROL FILE-READ ERROR (MCSEQIO)                 9902CONTROL FILE-CLOSE ERROR (MCSEQIO)                9903CONTROL FILE-DD NAME NOT IN JCL                   9904CONTROL FILE-TYPE (DSORG) NOT PROCESSED           9905CONTROL FILE-RECORD FORMAT UNACCEPTABLE           9906CONTROL FILE-DATASET IS EMPTY (NO RECORDS)        9915CONTROL FILE-RECORD LENGTH INVALID                9925BROADCAST RESULT DD-RECORD LENGTH INVALID         9927BROADCAST RESULT DD-RECORD FORMAT UNACCEPTABLE    9930FPL APP_ENDPT_ID COLUMN-SQL SELECT ERROR (EPT)    9940TARASTS STAT REF ID SELECT DB2 ERROR              9990API LOGIC ERROR-STATUS CDE ASSIGNMENT UNDETERMINED....**** UNDOCUMENTED ERROR -- NOTIFY GFT SYSTEMS ****".toCharArray());
    }


 

	/**
	 *	Returns the value of errorTable590
	 *	@return errorTable590
	 */
   public char[] getErrorTable590() throws CFException{
     if (isErrorTable590Modified()) { 
        errorTable590 = refreshErrorTable590();
     }
   		return errorTable590;
   }

  
	/**
	*  set variable errorTable590
	*  Corresponding COBOL Variable is 590-ERROR-TABLE
	*  @param value
	**/
   public void setErrorTable590(char[] value) {
      errorTable590 = checkErrorTable590Constraints(value);
      serializeErrorTable590(errorTable590);
   } 

     /**
	 * 	Update ErrorTable590 
	 *     with a char[] from an offset and length             
	 *	@param value
	 */
   public void setErrorTable590(char[] source, int sourceIndex) {
       replace(source,sourceIndex,source.length,beginErrorTable590,errorTable590.length);
   	
   }
   
   public void setErrorTable590(char[] source, int sourceIndex , int sourceLen) {
       replace(source,sourceIndex,sourceLen,beginErrorTable590,errorTable590.length);
   	
   }
   
     /**
	 * 	Update ErrorTable590 
	 *     with a char[] from an offset and length  
	 *                     to  an offset and length         
	 *	@param value
	 */
   public void setErrorTable590(char[] source, int sourceIndex,int sourceLen, int targetIndex,int targetLen) {
       replace(source,sourceIndex,sourceLen,beginErrorTable590+targetIndex,targetLen);
   
   }
   
    /**
	 * 	Update ErrorTable590 with another Field
	 *	@param value
	 */
   public void setErrorTable590(Field source) {
       replace(source,0,source.length(),beginErrorTable590,ERROR_TABLE_590_LEN);
   	
   }  
   
     /**
	 * 	Update ErrorTable590 
	 *     with another Field from an offset and length          
	 *	@param value
	 */
   public void setErrorTable590(Field source, int sourceIndex,int sourceLen) {
        replace(source,sourceIndex,sourceLen,beginErrorTable590,ERROR_TABLE_590_LEN);
   	
   }
   
     /**
	 * 	Update ErrorTable590 
	 *     with another Field from an offset and length  
	 *                         to  an offset and length         
	 *	@param value
	 */
   public void setErrorTable590(Field source, int sourceIndex,int sourceLen, int targetIndex,int targetLen) {
       replace(source,sourceIndex,sourceLen,beginErrorTable590+targetIndex,targetLen);
    
   }
	/**
	 *	Returns the value of errorTable590Redefined
	 *	@return errorTable590Redefined
	 */   
	 public ErrorTable590Redefined getErrorTable590Redefined() {
   	return errorTable590Redefined;
   }
   /**
	* 	Update ErrorTable590Redefined with the passed value
	*   Corresponding COBOL Variable is 590-ERROR-TABLE-REDEFINED
	*	@param value
	*/
   public void setErrorTable590Redefined(char[] value) {
      errorTable590Redefined.setString(value); 
   }   
    
     /**
	 * 	Update ErrorTable590Redefined 
	 *     with a String from an offset and length             
	 *	@param value
	 */
   public void setErrorTable590Redefined(char[] source, int sourceIndex,int sourceLen) {
   	replace(source,sourceIndex,sourceLen,errorTable590Redefined.begin,errorTable590Redefined.length());
   }
   
     /**
	 * 	Update ErrorTable590Redefined 
	 *     with a String from an offset and length  
	 *                     to  an offset and length         
	 *	@param value
	 */
   public void setErrorTable590Redefined(char[] source, int sourceIndex,int sourceLen, int targetIndex,int targetLen) {
   	replace(source,sourceIndex,sourceLen,errorTable590Redefined.begin+targetIndex,targetLen);
   }
   
    /**
	 * 	Update ErrorTable590Redefined with another Field
	 *	@param value
	 */
   public void setErrorTable590Redefined(Field source) {
   	replace(source,0,source.length(),errorTable590Redefined.begin,errorTable590Redefined.length());
   }  
   
     /**
	 * 	Update ErrorTable590Redefined 
	 *     with another Field from an offset and length             
	 *	@param value
	 */
   public void setErrorTable590Redefined(Field source, int sourceIndex,int sourceLen) {
   	replace(source,sourceIndex,sourceLen,errorTable590Redefined.begin,errorTable590Redefined.length());
   }
   
     /**
	 * 	Update ErrorTable590Redefined 
	 *     with another Field from an offset and length  
	 *                         to  an offset and length         
	 *	@param value
	 */
   public void setErrorTable590Redefined(Field source, int sourceIndex,int sourceLen, int targetIndex,int targetLen) {
   	replace(source,sourceIndex,sourceLen,errorTable590Redefined.begin+targetIndex,targetLen);
   }

	
	
	

		public static int getErrorTableGroup590FieldLength() {
			return ERROR_TABLE_GROUP_590_LENGTH;
		}

}
  
