#STEP:MRGZPMTS_SORT| PGM:SORT| DD:SORTIN
Sortzdcomp1Mrgzpmts_sortSortIn[0]=CLOUDFRM.SLCO.VAST6397.ZBBPMTS(+0)
Sortzdcomp1Mrgzpmts_sortSortIn[0].DISP=OLD,PASS,KEEP
Sortzdcomp1Mrgzpmts_sortSortIn0RecordType=FB
Sortzdcomp1Mrgzpmts_sortSortIn0RecordLen=113
#STEP:MRGZPMTS_SORT| PGM:SORT| DD:SORTIN
Sortzdcomp1Mrgzpmts_sortSortIn[1]=CLOUDFRM.SLCO.VAST6397.VB595.ZBBPMTS
Sortzdcomp1Mrgzpmts_sortSortIn[1].DISP=SHR,KEEP,KEEP
Sortzdcomp1Mrgzpmts_sortSortIn1RecordType=FB
Sortzdcomp1Mrgzpmts_sortSortIn1RecordLen=113
#STEP:MRGZPMTS_SORT| PGM:SORT| DD:SORTOUT
Sortzdcomp1Mrgzpmts_sortSortOut=CLOUDFRM.SLCO.VAST6397.ZBBPMTS(+1)
Sortzdcomp1Mrgzpmts_sortSortOut.DISP=NEW,CATLG,UNCATLG
Sortzdcomp1Mrgzpmts_sortSortOutRecordType=FB
Sortzdcomp1Mrgzpmts_sortSortOutRecordLen=113
