GP004760.dbQualifier=
# Program GP004760 | DD : SYS201 | RecordFormat : FixedLength | RecordLength : 256
GP004760.ddname.SYS201=Sys201CabTccExt
GP004760.Sys201CabTccExt=Sys201CabTccExt
GP004760.Sys201CabTccExtCharSet=cp1047
GP004760.Sys201CabTccExtCRLFflag=no
# Program GP004760 | DD : SYS202 | RecordFormat : FixedLength | RecordLength : 10
GP004760.ddname.SYS202=Sys202NspkCabTccExt
GP004760.Sys202NspkCabTccExt=Sys202NspkCabTccExt
GP004760.Sys202NspkCabTccExtCharSet=cp1047
GP004760.Sys202NspkCabTccExtCRLFflag=no
# 
# End of GP004760
