# Program  : VSAMMON4 | DD : SYSIN | RecordFormat : FixedLength | RecordLength : 80
VSAMMON4.Scanner=SYSIN.bin
VSAMMON4.ScannerCharSet=cp1047
VSAMMON4.ScannerCRLFflag=no
# Program VSAMMON4 | DD : VSVKSDSB | VSAM KSDS
VSAMMON4.ddname.VSVKSDSB=VsvksdsIo
# Program VSAMMON4 | DD : VSVKSDSI | VSAM KSDS
VSAMMON4.ddname.VSVKSDSI=VsvksdsSeq
# Program VSAMMON4 | DD : REPOUT | RecordFormat : FixedLength | RecordLength : 300
VSAMMON4.ddname.REPOUT=Repout
VSAMMON4.Repout=Repout
VSAMMON4.RepoutCharSet=cp1047
VSAMMON4.RepoutCRLFflag=no
# Program VSAMMON4 | DD : VSVKSDSO | VSAM KSDS
VSAMMON4.ddname.VSVKSDSO=VsvksdsOutput
# 
# End of VSAMMON4
