# Program GLOBAL | DD : XMLDATA | RecordFormat : VariableLength | MaxRecordLength : 80
GLOBAL.ddname.XMLDATA=XmlIn
GLOBAL.XmlIn=XmlIn
GLOBAL.XmlInCharSet=cp1047
GLOBAL.XmlInCRLFflag=no
# 
# End of READVB01
# End of READVB02
