# Program  : MCSORT02 | DD : SYSIN | RecordFormat : FixedLength | RecordLength : 80
MCSORT02.Scanner=SYSIN.bin
MCSORT02.ScannerCharSet=cp1047
MCSORT02.ScannerCRLFflag=no
# Program MCSORT02 | DD : SYS002 | RecordFormat : VariableLength | MaxRecordLength : 32752
MCSORT02.ddname.SYS002=Sys002IpmParmMaster
MCSORT02.Sys002IpmParmMaster=Sys002IpmParmMaster
MCSORT02.Sys002IpmParmMasterCharSet=cp1047
MCSORT02.Sys002IpmParmMasterCRLFflag=no
# Program MCSORT02 | DD : SYS004 | RecordFormat : VariableLength | MaxRecordLength : 32752
MCSORT02.ddname.SYS004=Sys004IpmParmMaster
MCSORT02.Sys004IpmParmMaster=Sys004IpmParmMaster
MCSORT02.Sys004IpmParmMasterCharSet=cp1047
MCSORT02.Sys004IpmParmMasterCRLFflag=no
# Program MCSORT02 | DD : SYS005 | RecordFormat : VariableLength | MaxRecordLength : 32752
MCSORT02.ddname.SYS005=Sys005IpmParmMaster
MCSORT02.Sys005IpmParmMaster=Sys005IpmParmMaster
MCSORT02.Sys005IpmParmMasterCharSet=cp1047
MCSORT02.Sys005IpmParmMasterCRLFflag=no
# Program MCSORT02 | DD : SORTOUT | RecordFormat : VariableLength | MaxRecordLength : 32752
MCSORT02.ddname.SORTOUT=SortOut
MCSORT02.SortOut=SortOut
MCSORT02.SortOutCharSet=cp1047
MCSORT02.SortOutCRLFflag=no
# 
# End of MCSORT02
