timeZoneId=Etc/GMT
# Program SF328010 | DD : SYS001 | RecordFormat : FixedLength | RecordLength : 75
SF328010.ddname.SYS001=Sys001ZLogFile
SF328010.Sys001ZLogFile=Sys001ZLogFile
SF328010.Sys001ZLogFileCharSet=cp1047
SF328010.Sys001ZLogFileCRLFflag=no
# Program SF328010 | DD : SYS201 | RecordFormat : FixedLength | RecordLength : 132
SF328010.ddname.SYS201=Sys201ServiceReport
SF328010.Sys201ServiceReport=Sys201ServiceReport
SF328010.Sys201ServiceReportCharSet=cp1047
SF328010.Sys201ServiceReportCRLFflag=no
# 
# End of SF328010
