#common-test-properties
spring.main.log-startup-info=OFF
# logging.pattern.file=%msg%n
# logging.file.name=QA.QA000173.CLF.BLKDBLK.SYSOUT.CF
logging.logback.rollingpolicy.clean-history-on-start=true
logging.level.com.zaxxer=OFF
logging.level.com.cloudframe.app.dao.CFDataSourceConfiguration=OFF
logging.level.com.cloudframe.app.vsam.VSAMClusterUtil=OFF
logging.level.com.cloudframe.app.utility.CFConfiguration=OFF
spring.main.web-application-type=none

BLKDBLK.Scanner=SYSIN.bin
BLKDBLK.ScannerCharSet=cp1047
BLKDBLK.ScannerCRLFflag=no
BLKDBLK.ddname.VBSEBC=VbsFile
BLKDBLK.VbsFile=QA.QA000173.VBSEBC.FILE
BLKDBLK.VbsFileCharSet=cp1047
BLKDBLK.VbsFileCRLFflag=no
BLKDBLK.ddname.UMODEASC=UmodeFile
BLKDBLK.UmodeFile=QA.QA000173.CLF.UMODEASC.FILE.CF
BLKDBLK.UmodeFileCharSet=cp1047
BLKDBLK.UmodeFileCRLFflag=no
#test-specific-properties
# compare.files[0]=QA.QA000173.CLF.BLKDBLK.SYSOUT.MF,QA.QA000173.CLF.BLKDBLK.SYSOUT.CF
# compare.files[1]=QA.QA000173.CLF.UMODEASC.FILE.MF,QA.QA000173.CLF.UMODEASC.FILE.CF
#compare.files[1]=ExpectedOutPutFile,GeneratedOutputFile
#project-specific-properties
#
#for running as a server, please comment or delete line below 
# spring.main.lazy-initialization=true
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
# #logging.level.com.cloudframe=DEBUG
# logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
# HIGH_VALUE=Z
# 
# End of BLKDBLK
