<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="ApplExitWork810" cobol:name="810-APPL-EXIT-WORK" cobol:offset="275" cobol:length="102" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="ApplExitDsnLen810" type="xs:short" maxOccurs="1"  cobol:name="810-APPL-EXIT-DSN-LEN" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="ApplExitMbrLen810" type="xs:short" maxOccurs="1"  cobol:name="810-APPL-EXIT-MBR-LEN" cobol:offset="2" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="ApplExitDsnDlm810" maxOccurs="1"  cobol:name="810-APPL-EXIT-DSN-DLM" cobol:offset="4" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ApplExitMbrDlm810" maxOccurs="1"  cobol:name="810-APPL-EXIT-MBR-DLM" cobol:offset="5" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ApplExitDsn810" maxOccurs="1"  cobol:name="810-APPL-EXIT-DSN" cobol:offset="6" cobol:length="44" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ApplExitMbr810" maxOccurs="1"  cobol:name="810-APPL-EXIT-MBR" cobol:offset="50" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ApplExitWrk810" maxOccurs="1"  cobol:name="810-APPL-EXIT-WRK" cobol:offset="58" cobol:length="44" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="Long.MAX_VALUE" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 applExitOverflow88810 VALUE [["** OVERFLOW **                              "]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="44" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
