<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="ConnectErrorMsg630" cobol:name="630-CONNECT-ERROR-MSG" cobol:offset="0" cobol:length="56" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="ConnectErrorMsg630Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="0" cobol:length="35" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="35" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ConnectErrorMsg630Filler2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="35" cobol:length="17" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="17" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ConnectResponse630" maxOccurs="1"  cobol:name="630-CONNECT-RESPONSE" cobol:offset="52" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
