<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="DynamReturnMsg650" cobol:name="650-DYNAM-RETURN-MSG" cobol:offset="0" cobol:length="88" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="DynamReturnMsg650Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="0" cobol:length="34" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="34" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DynamSvc99Rc650" maxOccurs="1"  cobol:name="650-DYNAM-SVC99-RC" cobol:offset="34" cobol:length="9" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DynamReturnMsg650Filler2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="43" cobol:length="14" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="14" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DynamSvc99Err650" maxOccurs="1"  cobol:name="650-DYNAM-SVC99-ERR" cobol:offset="57" cobol:length="9" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DynamReturnMsg650Filler3" maxOccurs="1"  cobol:name="FILLER" cobol:offset="66" cobol:length="13" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="13" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DynamSvc99Inf650" maxOccurs="1"  cobol:name="650-DYNAM-SVC99-INF" cobol:offset="79" cobol:length="9" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
