<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="DynamWorkAreas850" cobol:name="850-DYNAM-WORK-AREAS" cobol:offset="0" cobol:length="318" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="DynamPointer850" type="xs:int" maxOccurs="1"  cobol:name="850-DYNAM-POINTER" cobol:offset="0" cobol:length="4" cobol:datatype="Pointer" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
<xs:element name="DynamFunctionGroup850" maxOccurs="1" cobol:name="850-DYNAM-FUNCTION-GROUP" cobol:offset="4" cobol:length="8" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="DynamAllocParms850" maxOccurs="1" cobol:name="850-DYNAM-ALLOC-PARMS" cobol:offset="12" cobol:length="224" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="DynamInfoIdent850" maxOccurs="1" cobol:name="850-DYNAM-INFO-IDENT" cobol:offset="236" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="DynamInfoParms850" maxOccurs="1" cobol:name="850-DYNAM-INFO-PARMS" cobol:offset="248" cobol:length="70" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
