<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="DynamErrorMsg650" cobol:name="650-DYNAM-ERROR-MSG" cobol:offset="0" cobol:length="78" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="DynamErrorMsg650Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="0" cobol:length="34" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="34" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DynamErrorRc650" maxOccurs="1"  cobol:name="650-DYNAM-ERROR-RC" cobol:offset="34" cobol:length="9" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DynamErrorMsg650Filler2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="43" cobol:length="12" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="12" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DynamFunction650" maxOccurs="1"  cobol:name="650-DYNAM-FUNCTION" cobol:offset="55" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DynamErrorMsg650Filler3" maxOccurs="1"  cobol:name="FILLER" cobol:offset="63" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DynamErrorMsg650ConditionGroup4" maxOccurs="1"  cobol:name="FILLER" cobol:offset="66" cobol:length="12" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_1T" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 dynamInitialize88650 VALUE [["INITIALIZE  "]].
                        88 dynamInformation88650 VALUE [["INFO        "]].
                        88 dynamAllocate88650 VALUE [["ALLOCATE    "]].
                        88 dynamDeleteAlloc88650 VALUE [["DELETE-ALLOC"]].
                        88 dynamUnallocate88650 VALUE [["UNALLOCATE  "]].
                        88 dynamEnd88650 VALUE [["END         "]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="12" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
