<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="GftdsnWorkAreas820" cobol:name="820-GFTDSN-WORK-AREAS" cobol:offset="0" cobol:length="45" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="GftdsnHlqid820" maxOccurs="1"  cobol:name="820-GFTDSN-HLQID" cobol:offset="0" cobol:length="4" cobol:datatype="Group" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10K" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 gftdsnHlqidTest88820 VALUE [["TEST"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
    </xs:element>  
<xs:element name="GftdsnBuild820" maxOccurs="1" cobol:name="820-GFTDSN-BUILD" cobol:offset="4" cobol:length="41" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="GftdsnBuild820Redefined" maxOccurs="1" cobol:name="820-GFTDSN-BUILD-REDEFINED" cobol:offset="4" cobol:length="41" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
