<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Itarafxa" cobol:name="ITARAFXA" cobol:offset="0" cobol:length="98" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="TarafxaArchLocTxtN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-ARCH-LOC-TXT-N" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaLstStatTsN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-LST-STAT-TS-N" cobol:offset="2" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaXferRqstTsN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-XFER-RQST-TS-N" cobol:offset="4" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaXferStrtTsN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-XFER-STRT-TS-N" cobol:offset="6" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaXferStopTsN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-XFER-STOP-TS-N" cobol:offset="8" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaXferRdyTsN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-XFER-RDY-TS-N" cobol:offset="10" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaXferCondCdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-XFER-COND-CD-N" cobol:offset="12" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaXferStatTxtN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-XFER-STAT-TXT-N" cobol:offset="14" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaXferPrcssIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-XFER-PRCSS-ID-N" cobol:offset="16" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaOrgXferPrcsIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-ORG-XFER-PRCS-ID-N" cobol:offset="18" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaTrgrCondCdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-TRGR-COND-CD-N" cobol:offset="20" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaTrgrStatTxtN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-TRGR-STAT-TXT-N" cobol:offset="22" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaOrgLocNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-ORG-LOC-NAM-N" cobol:offset="24" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaTrgrActNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-TRGR-ACT-NAM-N" cobol:offset="26" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaPrvMnfrmFileNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-PRV-MNFRM-FILE-NAM-N" cobol:offset="28" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaPrvCyclNumN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-PRV-CYCL-NUM-N" cobol:offset="30" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaPrvBusPrtnrIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-PRV-BUS-PRTNR-ID-N" cobol:offset="32" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaPrvEndptIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-PRV-ENDPT-ID-N" cobol:offset="34" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaPrvAvailTsN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-PRV-AVAIL-TS-N" cobol:offset="36" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaNxtMnfrmFileNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-NXT-MNFRM-FILE-NAM-N" cobol:offset="38" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaNxtCyclNumN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-NXT-CYCL-NUM-N" cobol:offset="40" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaNxtBusPrtnrIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-NXT-BUS-PRTNR-ID-N" cobol:offset="42" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaNxtEndptIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-NXT-ENDPT-ID-N" cobol:offset="44" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaNxtAvailTsN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-NXT-AVAIL-TS-N" cobol:offset="46" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaApplExitJobNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-APPL-EXIT-JOB-NAM-N" cobol:offset="48" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaApplExitTsN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-APPL-EXIT-TS-N" cobol:offset="50" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaCsMipIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-CS-MIP-ID-N" cobol:offset="52" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaRmMipIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-RM-MIP-ID-N" cobol:offset="54" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaApplExitNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-APPL-EXIT-NAM-N" cobol:offset="56" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaTapeCmpltdSwN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-TAPE-CMPLTD-SW-N" cobol:offset="58" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaTapeMultVolSwN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-TAPE-MULT-VOL-SW-N" cobol:offset="60" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaApplPrcssngDtN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-APPL-PRCSSNG-DT-N" cobol:offset="62" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaTransitionalDsnN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-TRANSITIONAL-DSN-N" cobol:offset="64" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaSourceHubIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-SOURCE-HUB-ID-N" cobol:offset="66" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaOwningHubIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-OWNING-HUB-ID-N" cobol:offset="68" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaStatRefIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-STAT-REF-ID-N" cobol:offset="70" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaSrcLocEntNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-SRC-LOC-ENT-NAM-N" cobol:offset="72" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaSrcTaskNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-SRC-TASK-NAM-N" cobol:offset="74" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaSrcTaskIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-SRC-TASK-ID-N" cobol:offset="76" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaSrcTaskUsrN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-SRC-TASK-USR-N" cobol:offset="78" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaSrcTaskStrtTsN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-SRC-TASK-STRT-TS-N" cobol:offset="80" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaSrcTaskStopTsN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-SRC-TASK-STOP-TS-N" cobol:offset="82" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaTrgtLocEntNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-TRGT-LOC-ENT-NAM-N" cobol:offset="84" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaTrgtTaskNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-TRGT-TASK-NAM-N" cobol:offset="86" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaTrgtTaskIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-TRGT-TASK-ID-N" cobol:offset="88" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaTrgtTaskUsrN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-TRGT-TASK-USR-N" cobol:offset="90" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaTrgtTaskStrtTsN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-TRGT-TASK-STRT-TS-N" cobol:offset="92" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaTrgtTaskStopTsN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-TRGT-TASK-STOP-TS-N" cobol:offset="94" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TarafxaApplTknNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-APPL-TKN-NAM-N" cobol:offset="96" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
