<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Itaraxtk" cobol:name="ITARAXTK" cobol:offset="0" cobol:length="50" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="TaraxtkDlyIntvlNumN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-DLY-INTVL-NUM-N" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkHighLvlQlfrCdN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-HIGH-LVL-QLFR-CD-N" cobol:offset="2" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkDirNodeNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-DIR-NODE-NAM-N" cobol:offset="4" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkLstRunTsN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-LST-RUN-TS-N" cobol:offset="6" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkStatsFileNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-STATS-FILE-NAM-N" cobol:offset="8" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkRunLmtNumN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-RUN-LMT-NUM-N" cobol:offset="10" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkLclRawStatsNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-LCL-RAW-STATS-NAM-N" cobol:offset="12" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkLclSrvrFileNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-LCL-SRVR-FILE-NAM-N" cobol:offset="14" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkLclFmtdStatsNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-LCL-FMTD-STATS-NAM-N" cobol:offset="16" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkGftSrvr2NamN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-GFT-SRVR2-NAM-N" cobol:offset="18" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkGftSrvr2DsnNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-GFT-SRVR2-DSN-NAM-N" cobol:offset="20" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkGftSrvr2TsN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-GFT-SRVR2-TS-N" cobol:offset="22" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkMfeSrvrNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-MFE-SRVR-NAM-N" cobol:offset="24" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkMfeBusPrtnrIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-MFE-BUS-PRTNR-ID-N" cobol:offset="26" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkMfeEndptIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-MFE-ENDPT-ID-N" cobol:offset="28" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkMfeBulkIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-MFE-BULK-ID-N" cobol:offset="30" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkInbndSwN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-INBND-SW-N" cobol:offset="32" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkOutbndSwN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-OUTBND-SW-N" cobol:offset="34" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkBrdcstSwN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-BRDCST-SW-N" cobol:offset="36" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkLastRunKyvlTxtN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-LAST-RUN-KYVL-TXT-N" cobol:offset="38" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkSshBulkIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-SSH-BULK-ID-N" cobol:offset="40" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkSshEndptIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-SSH-ENDPT-ID-N" cobol:offset="42" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkSshBusPrtnrIdN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-SSH-BUS-PRTNR-ID-N" cobol:offset="44" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkSshSrvrNamN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-SSH-SRVR-NAM-N" cobol:offset="46" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TaraxtkTaskWorkParmTxtN" type="xs:short" maxOccurs="1"  cobol:name="TARAXTK-TASK-WORK-PARM-TXT-N" cobol:offset="48" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
