<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Messages600" cobol:name="600-MESSAGES" cobol:offset="0" cobol:length="405" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="MsgPrefix600" maxOccurs="1" cobol:name="600-MSG-PREFIX" cobol:offset="0" cobol:length="9" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="XtkDefaultMsg600" maxOccurs="1" cobol:name="600-XTK-DEFAULT-MSG" cobol:offset="9" cobol:length="57" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="XtkAssignMsg600" maxOccurs="1" cobol:name="600-XTK-ASSIGN-MSG" cobol:offset="66" cobol:length="57" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="XtkMsg1600" maxOccurs="1" cobol:name="600-XTK-MSG1" cobol:offset="123" cobol:length="61" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="XtkMsg2600" maxOccurs="1" cobol:name="600-XTK-MSG2" cobol:offset="184" cobol:length="57" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="ProgramMsg600" maxOccurs="1" cobol:name="600-PROGRAM-MSG" cobol:offset="241" cobol:length="36" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="CompileMsg600" maxOccurs="1" cobol:name="600-COMPILE-MSG" cobol:offset="277" cobol:length="45" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="CurrentMsg600" maxOccurs="1" cobol:name="600-CURRENT-MSG" cobol:offset="322" cobol:length="45" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="TsSuffix600" maxOccurs="1" cobol:name="600-TS-SUFFIX" cobol:offset="367" cobol:length="38" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
