<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="MsgFormatParms240" cobol:name="240-MSG-FORMAT-PARMS" cobol:offset="0" cobol:length="669" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="GftSubsystemId240" maxOccurs="1"  cobol:name="240-GFT-SUBSYSTEM-ID" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10K" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 gftClassic88240 VALUE [["GFTC"]].
                        88 gftHub88240 VALUE [["GFTH"]].
                        88 gftMainframe88240 VALUE [["GFTM"]].
                        88 gftMfts88240 VALUE [["MFTS"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="4" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="MsgNum240" maxOccurs="1"  cobol:name="240-MSG-NUM" cobol:offset="4" cobol:length="3" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_1000" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 cdOutbMgr88240 VALUE [["101"]].
                        88 cdActvtyMgr88240 VALUE [["102"]].
                        88 cdAcvtyPrcTrmUpd88240 VALUE [["112"]].
                        88 cdAcvtyPrcTrmNoupd88240 VALUE [["122"]].
                        88 cdActvtyMissSite88240 VALUE [["132"]].
                        88 cdAcvtyMissEfp88240 VALUE [["142"]].
                        88 applExitMgr88240 VALUE [["103"]].
                        88 ipelOutbMgr88240 VALUE [["104"]].
                        88 ipelActvtyMgr88240 VALUE [["105"]].
                        88 mfeOutbMgr88240 VALUE [["106"]].
                        88 sdpushOutbMgr88240 VALUE [["107"]].
                        88 gftFtApi88240 VALUE [["108"]].
                        88 gftFtApiMissEpt88240 VALUE [["118"]].
                        88 gftFtApiMissEfp88240 VALUE [["128"]].
                        88 gftFtApiApplTkn88240 VALUE [["109"]].
                        88 gftStatUpdateUtlt88240 VALUE [["201"]].
                        88 gftStatUpdtUtltDb288240 VALUE [["202"]].
                        88 gftJobNameNumReset88240 VALUE [["203"]].
                        88 gftKeyFilterReset88240 VALUE [["204"]].
                        88 netwrkMonMenu88240 VALUE [["205"]].
                        88 fxsTrsholdViolation88240 VALUE [["301"]].
                        88 scdTrsholdViolation88240 VALUE [["302"]].
                        88 gf1TrsholdViolation88240 VALUE [["303"]].
                        88 procTrsholdViolation88240 VALUE [["304"]].
                        88 flWaitTshldViolatn88240 VALUE [["305"]].
                        88 ipsTrsholdViolation88240 VALUE [["306"]].
                        88 gftHostInterface88240 VALUE [["401"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="3" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="MsgSeverityInd240" maxOccurs="1"  cobol:name="240-MSG-SEVERITY-IND" cobol:offset="7" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 msgSeverityClr88240 VALUE [["C"]].
                        88 msgSeverityInf88240 VALUE [["I"]].
                        88 msgSeverityMinor88240 VALUE [["M"]].
                        88 msgSeverityWrn88240 VALUE [["W"]].
                        88 msgSeverityErr88240 VALUE [["E"]].
                        88 msgSeverityFatal88240 VALUE [["F"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="MsgTypeInd240" maxOccurs="1"  cobol:name="240-MSG-TYPE-IND" cobol:offset="8" cobol:length="4" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10K" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 errWithClrng88240 VALUE [["0100"]].
                        88 errClred88240 VALUE [["0110"]].
                        88 errWoutClrng88240 VALUE [["0200"]].
                        88 tsholdViolate88240 VALUE [["0300"]].
                        88 ftTsholdViolate88240 VALUE [["0310"]].
                        88 faTsholdViolate88240 VALUE [["0320"]].
                        88 peTsholdViolate88240 VALUE [["0330"]].
                        88 msgControl88240 VALUE [["0900"]].
                        88 msgDonotSend88240 VALUE [["0910"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="4" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="MsgBulkid240" maxOccurs="1"  cobol:name="240-MSG-BULKID" cobol:offset="12" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MsgEndpt240" maxOccurs="1"  cobol:name="240-MSG-ENDPT" cobol:offset="16" cobol:length="7" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="MsgCyclNum240" type="xs:short" maxOccurs="1"  cobol:name="240-MSG-CYCL-NUM" cobol:offset="23" cobol:length="2" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
    <xs:element name="MsgFilename240" maxOccurs="1"  cobol:name="240-MSG-FILENAME" cobol:offset="25" cobol:length="44" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="XferMthd240" maxOccurs="1"  cobol:name="240-XFER-MTHD" cobol:offset="69" cobol:length="3" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_1000" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 connectDirect88240 VALUE [["C  "]].
                        88 mfts88240 VALUE [["F  "]].
                        88 mfe88240 VALUE [["M  "]].
                        88 interpelPel88240 VALUE [["P  "]].
                        88 sdpush88240 VALUE [["S  "]].
                        88 xcom88240 VALUE [["X  "]].
                        88 interpelPesit88240 VALUE [["Y  "]].
                        88 tmcNotApplicable88240 VALUE [["N/A"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="3" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="XferMthdNode240" maxOccurs="1"  cobol:name="240-XFER-MTHD-NODE" cobol:offset="72" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="XferProcId240" maxOccurs="1"  cobol:name="240-XFER-PROC-ID" cobol:offset="92" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="XferMthdMsgId240" maxOccurs="1"  cobol:name="240-XFER-MTHD-MSG-ID" cobol:offset="112" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MsgErrCd240" maxOccurs="1"  cobol:name="240-MSG-ERR-CD" cobol:offset="132" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MsgStatRefId240" maxOccurs="1"  cobol:name="240-MSG-STAT-REF-ID" cobol:offset="136" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MsgStatRefDesc240" maxOccurs="1"  cobol:name="240-MSG-STAT-REF-DESC" cobol:offset="140" cobol:length="80" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="80" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MsgErrorDescription240" maxOccurs="1"  cobol:name="240-MSG-ERROR-DESCRIPTION" cobol:offset="220" cobol:length="400" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="400" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="MsgErr240" maxOccurs="5" cobol:name="240-MSG-ERR" cobol:offset="220" cobol:length="80" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="MsgProgName240" maxOccurs="1"  cobol:name="240-MSG-PROG-NAME" cobol:offset="620" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MsgParaName240" maxOccurs="1"  cobol:name="240-MSG-PARA-NAME" cobol:offset="628" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MsgBusPrtnrId240" maxOccurs="1"  cobol:name="240-MSG-BUS-PRTNR-ID" cobol:offset="658" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MsgAbendCd240" maxOccurs="1"  cobol:name="240-MSG-ABEND-CD" cobol:offset="664" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
