<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Tarafxa" cobol:name="TARAFXA" cobol:offset="0" cobol:length="1163" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="TarafxaMcMnfrmFileNam" maxOccurs="1"  cobol:name="TARAFXA-MC-MNFRM-FILE-NAM" cobol:offset="0" cobol:length="44" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="TarafxaCyclNum" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-CYCL-NUM" cobol:offset="44" cobol:length="2" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
    <xs:element name="TarafxaBusPrtnrId" maxOccurs="1"  cobol:name="TARAFXA-BUS-PRTNR-ID" cobol:offset="46" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaEndptId" maxOccurs="1"  cobol:name="TARAFXA-ENDPT-ID" cobol:offset="52" cobol:length="7" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaXferMthdCd" maxOccurs="1"  cobol:name="TARAFXA-XFER-MTHD-CD" cobol:offset="59" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaAvailTs" maxOccurs="1"  cobol:name="TARAFXA-AVAIL-TS" cobol:offset="60" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaBulkId" maxOccurs="1"  cobol:name="TARAFXA-BULK-ID" cobol:offset="86" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaStatCd" maxOccurs="1"  cobol:name="TARAFXA-STAT-CD" cobol:offset="90" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaSndRcvPrmsnCd" maxOccurs="1"  cobol:name="TARAFXA-SND-RCV-PRMSN-CD" cobol:offset="91" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaMcibdioParmTxt" maxOccurs="1"  cobol:name="TARAFXA-MCIBDIO-PARM-TXT" cobol:offset="92" cobol:length="50" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="50" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="TarafxaPrtyNum" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-PRTY-NUM" cobol:offset="142" cobol:length="2" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
    <xs:element name="TarafxaArchLocTxt" maxOccurs="1"  cobol:name="TARAFXA-ARCH-LOC-TXT" cobol:offset="144" cobol:length="44" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaSvrFileStatCd" maxOccurs="1"  cobol:name="TARAFXA-SVR-FILE-STAT-CD" cobol:offset="188" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaLstStatTs" maxOccurs="1"  cobol:name="TARAFXA-LST-STAT-TS" cobol:offset="189" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="TarafxaXferFileSzNum" type="xs:long" maxOccurs="1"  cobol:name="TARAFXA-XFER-FILE-SZ-NUM" cobol:offset="215" cobol:length="7" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10T"/>
         <xs:element name="TarafxaTmsXferdCnt" type="xs:int" maxOccurs="1"  cobol:name="TARAFXA-TMS-XFERD-CNT" cobol:offset="222" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
         <xs:element name="TarafxaXferRecCnt" type="xs:long" maxOccurs="1"  cobol:name="TARAFXA-XFER-REC-CNT" cobol:offset="225" cobol:length="7" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10T"/>
    <xs:element name="TarafxaXferRqstTs" maxOccurs="1"  cobol:name="TARAFXA-XFER-RQST-TS" cobol:offset="232" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaXferStrtTs" maxOccurs="1"  cobol:name="TARAFXA-XFER-STRT-TS" cobol:offset="258" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaXferStopTs" maxOccurs="1"  cobol:name="TARAFXA-XFER-STOP-TS" cobol:offset="284" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaXferRdyTs" maxOccurs="1"  cobol:name="TARAFXA-XFER-RDY-TS" cobol:offset="310" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaXferCondCd" maxOccurs="1"  cobol:name="TARAFXA-XFER-COND-CD" cobol:offset="336" cobol:length="9" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaXferStatTxt" maxOccurs="1"  cobol:name="TARAFXA-XFER-STAT-TXT" cobol:offset="345" cobol:length="9" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="TarafxaXferPrcssId" type="xs:long" maxOccurs="1"  cobol:name="TARAFXA-XFER-PRCSS-ID" cobol:offset="354" cobol:length="7" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10T"/>
         <xs:element name="TarafxaOrgXferPrcsId" type="xs:long" maxOccurs="1"  cobol:name="TARAFXA-ORG-XFER-PRCS-ID" cobol:offset="361" cobol:length="7" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10T"/>
    <xs:element name="TarafxaTrgrCondCd" maxOccurs="1"  cobol:name="TARAFXA-TRGR-COND-CD" cobol:offset="368" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaTrgrStatTxt" maxOccurs="1"  cobol:name="TARAFXA-TRGR-STAT-TXT" cobol:offset="369" cobol:length="9" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaOrgLocNam" maxOccurs="1"  cobol:name="TARAFXA-ORG-LOC-NAM" cobol:offset="378" cobol:length="16" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="16" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaLstUpdtUserId" maxOccurs="1"  cobol:name="TARAFXA-LST-UPDT-USER-ID" cobol:offset="394" cobol:length="9" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaLstUpdtTs" maxOccurs="1"  cobol:name="TARAFXA-LST-UPDT-TS" cobol:offset="403" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaTrgrActNam" maxOccurs="1"  cobol:name="TARAFXA-TRGR-ACT-NAM" cobol:offset="429" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaPrvMnfrmFileNam" maxOccurs="1"  cobol:name="TARAFXA-PRV-MNFRM-FILE-NAM" cobol:offset="437" cobol:length="44" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="TarafxaPrvCyclNum" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-PRV-CYCL-NUM" cobol:offset="481" cobol:length="2" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
    <xs:element name="TarafxaPrvBusPrtnrId" maxOccurs="1"  cobol:name="TARAFXA-PRV-BUS-PRTNR-ID" cobol:offset="483" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaPrvEndptId" maxOccurs="1"  cobol:name="TARAFXA-PRV-ENDPT-ID" cobol:offset="489" cobol:length="7" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaPrvAvailTs" maxOccurs="1"  cobol:name="TARAFXA-PRV-AVAIL-TS" cobol:offset="496" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaNxtMnfrmFileNam" maxOccurs="1"  cobol:name="TARAFXA-NXT-MNFRM-FILE-NAM" cobol:offset="522" cobol:length="44" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="TarafxaNxtCyclNum" type="xs:short" maxOccurs="1"  cobol:name="TARAFXA-NXT-CYCL-NUM" cobol:offset="566" cobol:length="2" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
    <xs:element name="TarafxaNxtBusPrtnrId" maxOccurs="1"  cobol:name="TARAFXA-NXT-BUS-PRTNR-ID" cobol:offset="568" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaNxtEndptId" maxOccurs="1"  cobol:name="TARAFXA-NXT-ENDPT-ID" cobol:offset="574" cobol:length="7" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaNxtAvailTs" maxOccurs="1"  cobol:name="TARAFXA-NXT-AVAIL-TS" cobol:offset="581" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaApplExitJobNam" maxOccurs="1"  cobol:name="TARAFXA-APPL-EXIT-JOB-NAM" cobol:offset="607" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaApplExitTs" maxOccurs="1"  cobol:name="TARAFXA-APPL-EXIT-TS" cobol:offset="615" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaCsMipId" maxOccurs="1"  cobol:name="TARAFXA-CS-MIP-ID" cobol:offset="641" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaRmMipId" maxOccurs="1"  cobol:name="TARAFXA-RM-MIP-ID" cobol:offset="644" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaApplExitNam" maxOccurs="1"  cobol:name="TARAFXA-APPL-EXIT-NAM" cobol:offset="647" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaTapeCmpltdSw" maxOccurs="1"  cobol:name="TARAFXA-TAPE-CMPLTD-SW" cobol:offset="655" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaTapeMultVolSw" maxOccurs="1"  cobol:name="TARAFXA-TAPE-MULT-VOL-SW" cobol:offset="656" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaApplPrcssngDt" maxOccurs="1"  cobol:name="TARAFXA-APPL-PRCSSNG-DT" cobol:offset="657" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaTransitionalDsn" maxOccurs="1"  cobol:name="TARAFXA-TRANSITIONAL-DSN" cobol:offset="667" cobol:length="44" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaSourceHubId" maxOccurs="1"  cobol:name="TARAFXA-SOURCE-HUB-ID" cobol:offset="711" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaOwningHubId" maxOccurs="1"  cobol:name="TARAFXA-OWNING-HUB-ID" cobol:offset="719" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaStatRefId" maxOccurs="1"  cobol:name="TARAFXA-STAT-REF-ID" cobol:offset="727" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaSrcLocEntNam" maxOccurs="1"  cobol:name="TARAFXA-SRC-LOC-ENT-NAM" cobol:offset="731" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaSrcTaskNam" maxOccurs="1"  cobol:name="TARAFXA-SRC-TASK-NAM" cobol:offset="741" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaSrcTaskId" maxOccurs="1"  cobol:name="TARAFXA-SRC-TASK-ID" cobol:offset="751" cobol:length="13" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="13" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="TarafxaSrcTaskUsr" maxOccurs="1" cobol:name="TARAFXA-SRC-TASK-USR" cobol:offset="764" cobol:length="66" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="TarafxaSrcTaskStrtTs" maxOccurs="1"  cobol:name="TARAFXA-SRC-TASK-STRT-TS" cobol:offset="830" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaSrcTaskStopTs" maxOccurs="1"  cobol:name="TARAFXA-SRC-TASK-STOP-TS" cobol:offset="856" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaTrgtLocEntNam" maxOccurs="1"  cobol:name="TARAFXA-TRGT-LOC-ENT-NAM" cobol:offset="882" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaTrgtTaskNam" maxOccurs="1"  cobol:name="TARAFXA-TRGT-TASK-NAM" cobol:offset="892" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaTrgtTaskId" maxOccurs="1"  cobol:name="TARAFXA-TRGT-TASK-ID" cobol:offset="902" cobol:length="13" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="13" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="TarafxaTrgtTaskUsr" maxOccurs="1" cobol:name="TARAFXA-TRGT-TASK-USR" cobol:offset="915" cobol:length="66" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="TarafxaTrgtTaskStrtTs" maxOccurs="1"  cobol:name="TARAFXA-TRGT-TASK-STRT-TS" cobol:offset="981" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaTrgtTaskStopTs" maxOccurs="1"  cobol:name="TARAFXA-TRGT-TASK-STOP-TS" cobol:offset="1007" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="TarafxaApplTknNam" maxOccurs="1" cobol:name="TARAFXA-APPL-TKN-NAM" cobol:offset="1033" cobol:length="130" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
