<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="TsSuffix600" cobol:name="600-TS-SUFFIX" cobol:offset="367" cobol:length="38" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Messages600Filler18" maxOccurs="1"  cobol:name="FILLER" cobol:offset="0" cobol:length="9" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="TsDate600" maxOccurs="1" cobol:name="600-TS-DATE" cobol:offset="9" cobol:length="10" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Messages600Filler21" maxOccurs="1"  cobol:name="FILLER" cobol:offset="19" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="TsTime600" maxOccurs="1" cobol:name="600-TS-TIME" cobol:offset="27" cobol:length="8" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Messages600Filler24" maxOccurs="1"  cobol:name="FILLER" cobol:offset="35" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TsHundredth600" maxOccurs="1"  cobol:name="600-TS-HUNDREDTH" cobol:offset="36" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
