<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Work" cobol:name="work" cobol:offset="0" cobol:length="97" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="TaraxtkFetchStatus100" maxOccurs="1"  cobol:name="100-TARAXTK-FETCH-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 taraxtkSuccess88100 VALUE [["Y"]].
                        88 taraxtkFailure88100 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="TaraxtkConfigValues100" maxOccurs="1"  cobol:name="100-TARAXTK-CONFIG-VALUES" cobol:offset="0" cobol:length="15" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_1P" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 configVals88100 VALUE [["CTRLBLKSZ      "], ["SYSOUTBLKSZ    "], ["LISTDDBLKSZ    "], ["MAXCYL         "], ["MAXTRK         "], ["MAXBLK         "], ["CPYATTMPTS     "], ["CPYINTRVL      "], ["DLTATTMPTS     "], ["DLTINTRVL      "], ["SQLATTMPTS     "], ["SQLINTRVL      "], ["SYSOUTLRECL    "]].
                        88 configCtrlblksz88100 VALUE [["CTRLBLKSZ      "]].
                        88 configSysoutblksz88100 VALUE [["SYSOUTBLKSZ    "]].
                        88 configListddblksz88100 VALUE [["LISTDDBLKSZ    "]].
                        88 configMaxcyl88100 VALUE [["MAXCYL         "]].
                        88 configMaxtrk88100 VALUE [["MAXTRK         "]].
                        88 configMaxblk88100 VALUE [["MAXBLK         "]].
                        88 configCpyattmpts88100 VALUE [["CPYATTMPTS     "]].
                        88 configCpyintrvl88100 VALUE [["CPYINTRVL      "]].
                        88 configDltattmpts88100 VALUE [["DLTATTMPTS     "]].
                        88 configDltintrvl88100 VALUE [["DLTINTRVL      "]].
                        88 configSqlattmpts88100 VALUE [["SQLATTMPTS     "]].
                        88 configSqlintrvl88100 VALUE [["SQLINTRVL      "]].
                        88 configSysoutlrecl88100 VALUE [["SYSOUTLRECL    "]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="15" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="FirstCall100" maxOccurs="1"  cobol:name="100-FIRST-CALL" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 firstCallToModule88100 VALUE [["Y"]].
                        88 firstCallCompleted88100 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="CallAttachLoad100" maxOccurs="1"  cobol:name="100-CALL-ATTACH-LOAD" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 callAttachNotLoaded88100 VALUE [["N"]].
                        88 callAttachLoaded88100 VALUE [["Y"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="RequestStatus110" maxOccurs="1"  cobol:name="110-REQUEST-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 requestSuccessful88110 VALUE [["+"]].
                        88 requestFailed88110 VALUE [["-"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="DeleteApplOption110" maxOccurs="1"  cobol:name="110-DELETE-APPL-OPTION" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 deleteApplRequested88110 VALUE [["R"]].
                        88 deleteApplBypassed88110 VALUE [["B"]].
                        88 deleteApplNotApplic88110 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="BroadcastStatus110" maxOccurs="1"  cobol:name="110-BROADCAST-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 broadcastInactive88110 VALUE [["I"]].
                        88 broadcastNoData88110 VALUE [["N"]].
                        88 broadcastEndptAvail88110 VALUE [["E"]].
                        88 broadcastComplete88110 VALUE [["C"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="InstallStatus110" maxOccurs="1"  cobol:name="110-INSTALL-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 installInactive88110 VALUE [["I"]].
                        88 installStandard88110 VALUE [["S"]].
                        88 installBroadcast88110 VALUE [["B"]].
                        88 installNotOpen88110 VALUE [["N"]].
                        88 installIsOpen88110 VALUE [["O"]].
                        88 installComplete88110 VALUE [["C"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="RetrieveStatus110" maxOccurs="1"  cobol:name="110-RETRIEVE-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 retrieveReady88110 VALUE [["R"]].
                        88 retrieveNotReady88110 VALUE [["N"]].
                        88 retrieveQuiesced88110 VALUE [["Q"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="ResendStatus110" maxOccurs="1"  cobol:name="110-RESEND-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 resendEnabled88110 VALUE [["Y"]].
                        88 resendDisabled88110 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="SetupStatus110" maxOccurs="1"  cobol:name="110-SETUP-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 setupValid88110 VALUE [["0"]].
                        88 setupProblem88110 VALUE [[["1"],["9"]]].
                        88 setupEptProblem88110 VALUE [[["1"],["5"]]].
                        88 setupEptMissing88110 VALUE [["1"]].
                        88 setupEptBackup88110 VALUE [["2"]].
                        88 setupEptBroken88110 VALUE [["3"]].
                        88 setupEptLoops88110 VALUE [["4"]].
                        88 setupEptNonFtss88110 VALUE [["5"]].
                        88 setupEfpProblem88110 VALUE [[["6"],["7"]]].
                        88 setupEfpMissing88110 VALUE [["6"]].
                        88 setupEfpBackup88110 VALUE [["7"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="SetupReported110" maxOccurs="1"  cobol:name="110-SETUP-REPORTED" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 setupReportedYes88110 VALUE [["Y"]].
                        88 setupReportedNo88110 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="TransferPostStatus110" maxOccurs="1"  cobol:name="110-TRANSFER-POST-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 transferInactive88110 VALUE [[" "]].
                        88 transferAccepted88110 VALUE [[["0"],["9"]]].
                        88 transferReady88110 VALUE [["0"]].
                        88 transferPosted88110 VALUE [["1"]].
                        88 transferQuiesce88110 VALUE [["2"]].
                        88 transferWaited88110 VALUE [["3"]].
                        88 transferInstalled88110 VALUE [["4"]].
                        88 transferRerouted88110 VALUE [["5"]].
                        88 transferRepeat88110 VALUE [["6"]].
                        88 transferFxsDupeWarn88110 VALUE [["7"]].
                        88 transferSetup88110 VALUE [["9"]].
                        88 transferRejected88110 VALUE [[["A"],["Z"]]].
                        88 transferEptSelect88110 VALUE [["E"]].
                        88 transferEfpSelect88110 VALUE [["F"]].
                        88 transferFxsSelect88110 VALUE [["X"]].
                        88 transferFxsInsert88110 VALUE [["I"]].
                        88 transferFxsDupeErr88110 VALUE [["D"]].
                        88 transferFxsUpdate88110 VALUE [["U"]].
                        88 transferResultWrite88110 VALUE [["W"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="CopyStatus110" maxOccurs="1"  cobol:name="110-COPY-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 copySuccessful88110 VALUE [["+"]].
                        88 copyFailed88110 VALUE [[["A"],["Z"]]].
                        88 copyFileAlloc88110 VALUE [["A"]].
                        88 copyFileInUse88110 VALUE [["I"]].
                        88 copyFileDupe88110 VALUE [["D"]].
                        88 copyFileNone88110 VALUE [["N"]].
                        88 copyFileOpen88110 VALUE [["O"]].
                        88 copyFileRead88110 VALUE [["R"]].
                        88 copyFileWrite88110 VALUE [["W"]].
                        88 copyFileClose88110 VALUE [["C"]].
                        88 copyFileUnall88110 VALUE [["U"]].
                        88 copyFileDltalc88110 VALUE [["L"]].
                        88 copyFileDltopn88110 VALUE [["P"]].
                        88 copyFileDltcls88110 VALUE [["S"]].
                        88 copyFileCounts88110 VALUE [["T"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="DynamEndStatus110" maxOccurs="1"  cobol:name="110-DYNAM-END-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 dynamEndNotNeeded88110 VALUE [["N"]].
                        88 dynamEndRequired88110 VALUE [["R"]].
                        88 dynamEndComplete88110 VALUE [["C"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="GftConnectStatus110" maxOccurs="1"  cobol:name="110-GFT-CONNECT-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 gftConnectInactive88110 VALUE [["I"]].
                        88 gftConnectActive88110 VALUE [["A"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="JclDdStatus110" maxOccurs="1"  cobol:name="110-JCL-DD-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 jclDdMissing88110 VALUE [["M"]].
                        88 jclDdPresent88110 VALUE [["P"]].
                        88 jclDdError88110 VALUE [["E"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="ResultDisp110" maxOccurs="1"  cobol:name="110-RESULT-DISP" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 resultDispSysout88110 VALUE [["O"]].
                        88 resultDispSyslst88110 VALUE [["L"]].
                        88 resultDispSysnnn88110 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="ResultFile110" maxOccurs="1"  cobol:name="110-RESULT-FILE" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 resultFileInactive88110 VALUE [["I"]].
                        88 resultFileActive88110 VALUE [["A"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="SqlExecStatus110" maxOccurs="1"  cobol:name="110-SQL-EXEC-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 sqlExecStart88110 VALUE [["S"]].
                        88 sqlExecActive88110 VALUE [["A"]].
                        88 sqlExecEnd88110 VALUE [["E"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="SqlRetryOption110" maxOccurs="1"  cobol:name="110-SQL-RETRY-OPTION" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 sqlRetryEnabled88110 VALUE [["E"]].
                        88 sqlRetryDisabled88110 VALUE [["D"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="RenameApplStatus110" maxOccurs="1"  cobol:name="110-RENAME-APPL-STATUS" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 renameApplInactive88110 VALUE [["I"]].
                        88 renameApplActive88110 VALUE [["A"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="SourceDsnSpaceInd110" maxOccurs="1"  cobol:name="110-SOURCE-DSN-SPACE-IND" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 sourceDsnPsInfo88110 VALUE [["Y"]].
                        88 sourceDsnAllcInfo88110 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="StatusAssignmentOption110" maxOccurs="1"  cobol:name="110-STATUS-ASSIGNMENT-OPTION" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 statusAssign88110 VALUE [["A"]].
                        88 statusPreSet88110 VALUE [["P"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="LogQueIndicator110" maxOccurs="1"  cobol:name="110-LOG-QUE-INDICATOR" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 logQueEmpty88110 VALUE [["E"]].
                        88 logQuePopulated88110 VALUE [["P"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="SkipByteCountInd110" maxOccurs="1"  cobol:name="110-SKIP-BYTE-COUNT-IND" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 skipByteCount88110 VALUE [["Y"]].
                        88 performByteCount88110 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="PgmMcdynam300" maxOccurs="1"  cobol:name="300-PGM-MCDYNAM" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmMcwait300" maxOccurs="1"  cobol:name="300-PGM-MCWAIT" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmAr648010300" maxOccurs="1"  cobol:name="300-PGM-AR648010" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="SpaceCount310" type="xs:int" maxOccurs="1"  cobol:name="310-SPACE-COUNT" cobol:offset="0" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="TildeCount310" type="xs:int" maxOccurs="1"  cobol:name="310-TILDE-COUNT" cobol:offset="3" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="TildeCount1310" type="xs:int" maxOccurs="1"  cobol:name="310-TILDE-COUNT1" cobol:offset="6" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="PipeCount310" type="xs:int" maxOccurs="1"  cobol:name="310-PIPE-COUNT" cobol:offset="9" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="ScolCount310" type="xs:int" maxOccurs="1"  cobol:name="310-SCOL-COUNT" cobol:offset="12" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="BinaryOne310" type="xs:short" maxOccurs="1"  cobol:name="310-BINARY-ONE" cobol:offset="15" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BinaryFour310" type="xs:short" maxOccurs="1"  cobol:name="310-BINARY-FOUR" cobol:offset="15" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BinaryFive310" type="xs:short" maxOccurs="1"  cobol:name="310-BINARY-FIVE" cobol:offset="15" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BinaryThirteen310" type="xs:short" maxOccurs="1"  cobol:name="310-BINARY-THIRTEEN" cobol:offset="15" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BinaryEighty310" type="xs:short" maxOccurs="1"  cobol:name="310-BINARY-EIGHTY" cobol:offset="15" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BinaryLrecl133310" type="xs:short" maxOccurs="1"  cobol:name="310-BINARY-LRECL-133" cobol:offset="15" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="MinusOne310" type="xs:short" maxOccurs="1"  cobol:name="310-MINUS-ONE" cobol:offset="15" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BinaryControlBlksz310" type="xs:int" maxOccurs="1"  cobol:name="310-BINARY-CONTROL-BLKSZ" cobol:offset="15" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BinarySysoutBlksz310" type="xs:int" maxOccurs="1"  cobol:name="310-BINARY-SYSOUT-BLKSZ" cobol:offset="15" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BinaryListddpoBlksz310" type="xs:int" maxOccurs="1"  cobol:name="310-BINARY-LISTDDPO-BLKSZ" cobol:offset="15" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BinControlBlksz310" type="xs:int" maxOccurs="1"  cobol:name="310-BIN-CONTROL-BLKSZ" cobol:offset="15" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BinSysoutBlksz310" type="xs:int" maxOccurs="1"  cobol:name="310-BIN-SYSOUT-BLKSZ" cobol:offset="15" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BinListddpoBlksz310" type="xs:int" maxOccurs="1"  cobol:name="310-BIN-LISTDDPO-BLKSZ" cobol:offset="15" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="BinLrecl133310" type="xs:short" maxOccurs="1"  cobol:name="310-BIN-LRECL-133" cobol:offset="15" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="PackedOne310" type="xs:short" maxOccurs="1"  cobol:name="310-PACKED-ONE" cobol:offset="15" cobol:length="1" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="ZonedTwentyeight310" type="xs:int" maxOccurs="1"  cobol:name="310-ZONED-TWENTYEIGHT" cobol:offset="16" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="ZonedTwentynine310" type="xs:int" maxOccurs="1"  cobol:name="310-ZONED-TWENTYNINE" cobol:offset="18" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="Zoned0080310" type="xs:int" maxOccurs="1"  cobol:name="310-ZONED-0080" cobol:offset="20" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
         <xs:element name="SqlSuccess330" type="xs:short" maxOccurs="1"  cobol:name="330-SQL-SUCCESS" cobol:offset="24" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SqlRowNotFound330" type="xs:short" maxOccurs="1"  cobol:name="330-SQL-ROW-NOT-FOUND" cobol:offset="24" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SqlCursorNotOpen330" type="xs:short" maxOccurs="1"  cobol:name="330-SQL-CURSOR-NOT-OPEN" cobol:offset="24" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SqlRowDuplicate330" type="xs:short" maxOccurs="1"  cobol:name="330-SQL-ROW-DUPLICATE" cobol:offset="24" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SqlResourceUnavail330" type="xs:short" maxOccurs="1"  cobol:name="330-SQL-RESOURCE-UNAVAIL" cobol:offset="24" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SqlResourceLimit330" type="xs:short" maxOccurs="1"  cobol:name="330-SQL-RESOURCE-LIMIT" cobol:offset="24" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SqlWorkunitRollback330" type="xs:short" maxOccurs="1"  cobol:name="330-SQL-WORKUNIT-ROLLBACK" cobol:offset="24" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SqlExecUnsuccessful330" type="xs:short" maxOccurs="1"  cobol:name="330-SQL-EXEC-UNSUCCESSFUL" cobol:offset="24" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SqlColUsed330" type="xs:short" maxOccurs="1"  cobol:name="330-SQL-COL-USED" cobol:offset="24" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SqlColNull330" type="xs:short" maxOccurs="1"  cobol:name="330-SQL-COL-NULL" cobol:offset="24" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SqlSqlerrd3Deadlock330" type="xs:int" maxOccurs="1"  cobol:name="330-SQL-SQLERRD3-DEADLOCK" cobol:offset="24" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SqlSqlerrd3Timeout330" type="xs:int" maxOccurs="1"  cobol:name="330-SQL-SQLERRD3-TIMEOUT" cobol:offset="24" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="MaximumCyl360" type="xs:long" maxOccurs="1"  cobol:name="360-MAXIMUM-CYL" cobol:offset="24" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="MaximumTrk360" type="xs:long" maxOccurs="1"  cobol:name="360-MAXIMUM-TRK" cobol:offset="35" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="MaximumBlk360" type="xs:long" maxOccurs="1"  cobol:name="360-MAXIMUM-BLK" cobol:offset="46" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="MaximumCylDeflt360" type="xs:long" maxOccurs="1"  cobol:name="360-MAXIMUM-CYL-DEFLT" cobol:offset="57" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="MaximumTrkDeflt360" type="xs:long" maxOccurs="1"  cobol:name="360-MAXIMUM-TRK-DEFLT" cobol:offset="68" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="MaximumBlkDeflt360" type="xs:long" maxOccurs="1"  cobol:name="360-MAXIMUM-BLK-DEFLT" cobol:offset="79" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="SourceRecords400" type="xs:int" maxOccurs="1"  cobol:name="400-SOURCE-RECORDS" cobol:offset="90" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SourceBytes400" type="xs:long" maxOccurs="1"  cobol:name="400-SOURCE-BYTES" cobol:offset="90" cobol:length="8" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="HeaderRecords400" type="xs:int" maxOccurs="1"  cobol:name="400-HEADER-RECORDS" cobol:offset="90" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="HeaderBytes400" type="xs:int" maxOccurs="1"  cobol:name="400-HEADER-BYTES" cobol:offset="90" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TargetRecords400" type="xs:int" maxOccurs="1"  cobol:name="400-TARGET-RECORDS" cobol:offset="90" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TargetBytes400" type="xs:long" maxOccurs="1"  cobol:name="400-TARGET-BYTES" cobol:offset="90" cobol:length="8" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="EndpointsValid400" type="xs:int" maxOccurs="1"  cobol:name="400-ENDPOINTS-VALID" cobol:offset="90" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="EndpointsError400" type="xs:int" maxOccurs="1"  cobol:name="400-ENDPOINTS-ERROR" cobol:offset="90" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="EndpointsListed400" type="xs:int" maxOccurs="1"  cobol:name="400-ENDPOINTS-LISTED" cobol:offset="90" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="AllocateAttempts400" type="xs:int" maxOccurs="1"  cobol:name="400-ALLOCATE-ATTEMPTS" cobol:offset="90" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="SqlRetryAttempts400" type="xs:short" maxOccurs="1"  cobol:name="400-SQL-RETRY-ATTEMPTS" cobol:offset="90" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Request410" type="xs:int" maxOccurs="1"  cobol:name="410-REQUEST" cobol:offset="90" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Error410" type="xs:short" maxOccurs="1"  cobol:name="410-ERROR" cobol:offset="95" cobol:length="2" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
    <xs:element name="ResultStartMsg603" maxOccurs="1"  cobol:name="603-RESULT-START-MSG" cobol:offset="97" cobol:length="36" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="36" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ResultEndMsg603" maxOccurs="1"  cobol:name="603-RESULT-END-MSG" cobol:offset="97" cobol:length="34" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="34" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PendedMsg605" maxOccurs="1"  cobol:name="605-PENDED-MSG" cobol:offset="97" cobol:length="18" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SetupProblemCurrMsg606" maxOccurs="1"  cobol:name="606-SETUP-PROBLEM-CURR-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SetupProblemOrigMsg606" maxOccurs="1"  cobol:name="606-SETUP-PROBLEM-ORIG-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SetupProblemBkupMsg606" maxOccurs="1"  cobol:name="606-SETUP-PROBLEM-BKUP-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SetupProblemSwMsg606" maxOccurs="1"  cobol:name="606-SETUP-PROBLEM-SW-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SetupProblemBulkMsg606" maxOccurs="1"  cobol:name="606-SETUP-PROBLEM-BULK-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SetupProblemXferMsg606" maxOccurs="1"  cobol:name="606-SETUP-PROBLEM-XFER-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SetupProblemCyclMsg606" maxOccurs="1"  cobol:name="606-SETUP-PROBLEM-CYCL-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SetupProblemSeqMsg606" maxOccurs="1"  cobol:name="606-SETUP-PROBLEM-SEQ-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FtssFileNameMsg607" maxOccurs="1"  cobol:name="607-FTSS-FILE-NAME-MSG" cobol:offset="97" cobol:length="18" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CopySuccessGft608" maxOccurs="1"  cobol:name="608-COPY-SUCCESS-GFT" cobol:offset="97" cobol:length="39" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="39" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CopySuccessAppl608" maxOccurs="1"  cobol:name="608-COPY-SUCCESS-APPL" cobol:offset="97" cobol:length="47" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="47" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RenameSuccess608" maxOccurs="1"  cobol:name="608-RENAME-SUCCESS" cobol:offset="97" cobol:length="68" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="68" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RenameOldMsg608" maxOccurs="1"  cobol:name="608-RENAME-OLD-MSG" cobol:offset="97" cobol:length="29" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="29" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RenameNewMsg608" maxOccurs="1"  cobol:name="608-RENAME-NEW-MSG" cobol:offset="97" cobol:length="29" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="29" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WarningText609" maxOccurs="1"  cobol:name="609-WARNING-TEXT" cobol:offset="97" cobol:length="54" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="54" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CopybookErrorMsg610" maxOccurs="1"  cobol:name="610-COPYBOOK-ERROR-MSG" cobol:offset="97" cobol:length="53" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="53" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CopybookProgramIdMsg610" maxOccurs="1"  cobol:name="610-COPYBOOK-PROGRAM-ID-MSG" cobol:offset="97" cobol:length="17" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="17" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CopybookVersionIdMsg610" maxOccurs="1"  cobol:name="610-COPYBOOK-VERSION-ID-MSG" cobol:offset="97" cobol:length="17" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="17" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ParameterErrorMsg611" maxOccurs="1"  cobol:name="611-PARAMETER-ERROR-MSG" cobol:offset="97" cobol:length="54" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="54" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FunctionRequestMsg611" maxOccurs="1"  cobol:name="611-FUNCTION-REQUEST-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="BulkIdMsg611" maxOccurs="1"  cobol:name="611-BULK-ID-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="EndptIdMsg611" maxOccurs="1"  cobol:name="611-ENDPT-ID-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DeleteIndMsg611" maxOccurs="1"  cobol:name="611-DELETE-IND-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CyclNumMsg611" maxOccurs="1"  cobol:name="611-CYCL-NUM-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ListBroadcastDdMsg611" maxOccurs="1"  cobol:name="611-LIST-BROADCAST-DD-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ApplicationDsnMsg611" maxOccurs="1"  cobol:name="611-APPLICATION-DSN-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="GftRetrieveDsnMsg611" maxOccurs="1"  cobol:name="611-GFT-RETRIEVE-DSN-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="BroadcastResultMsg611" maxOccurs="1"  cobol:name="611-BROADCAST-RESULT-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ProcDateMsg611" maxOccurs="1"  cobol:name="611-PROC-DATE-MSG" cobol:offset="97" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AssignLogicError619" maxOccurs="1"  cobol:name="619-ASSIGN-LOGIC-ERROR" cobol:offset="97" cobol:length="39" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="39" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ControlParmMsg620" maxOccurs="1"  cobol:name="620-CONTROL-PARM-MSG" cobol:offset="97" cobol:length="24" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="24" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ControlColsMsg620" maxOccurs="1"  cobol:name="620-CONTROL-COLS-MSG" cobol:offset="97" cobol:length="104" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="104" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ControlInfoMsg620" maxOccurs="1"  cobol:name="620-CONTROL-INFO-MSG" cobol:offset="97" cobol:length="24" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="24" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ControlDbid620" maxOccurs="1"  cobol:name="620-CONTROL-DBID" cobol:offset="97" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ControlDbpkg620" maxOccurs="1"  cobol:name="620-CONTROL-DBPKG" cobol:offset="97" cobol:length="16" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="16" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ControlHlqid620" maxOccurs="1"  cobol:name="620-CONTROL-HLQID" cobol:offset="97" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlErrorMsg640" maxOccurs="1"  cobol:name="640-SQL-ERROR-MSG" cobol:offset="97" cobol:length="48" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="48" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlMnfrmFileNamMsg640" maxOccurs="1"  cobol:name="640-SQL-MNFRM-FILE-NAM-MSG" cobol:offset="97" cobol:length="19" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="19" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlBulkIdMsg640" maxOccurs="1"  cobol:name="640-SQL-BULK-ID-MSG" cobol:offset="97" cobol:length="9" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlEndptIdMsg640" maxOccurs="1"  cobol:name="640-SQL-ENDPT-ID-MSG" cobol:offset="97" cobol:length="10" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlStatCdMsg640" maxOccurs="1"  cobol:name="640-SQL-STAT-CD-MSG" cobol:offset="97" cobol:length="9" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlApplExitNamMsg640" maxOccurs="1"  cobol:name="640-SQL-APPL-EXIT-NAM-MSG" cobol:offset="97" cobol:length="15" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="15" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlCyclNumMsg640" maxOccurs="1"  cobol:name="640-SQL-CYCL-NUM-MSG" cobol:offset="97" cobol:length="10" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlCyclNumLoMsg640" maxOccurs="1"  cobol:name="640-SQL-CYCL-NUM-LO-MSG" cobol:offset="97" cobol:length="15" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="15" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlCyclNumHiMsg640" maxOccurs="1"  cobol:name="640-SQL-CYCL-NUM-HI-MSG" cobol:offset="97" cobol:length="17" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="17" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlLstUpdtUserIdMsg640" maxOccurs="1"  cobol:name="640-SQL-LST-UPDT-USER-ID-MSG" cobol:offset="97" cobol:length="18" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlLstUpdtTsMsg640" maxOccurs="1"  cobol:name="640-SQL-LST-UPDT-TS-MSG" cobol:offset="97" cobol:length="13" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="13" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlBdioTxtMsg640" maxOccurs="1"  cobol:name="640-SQL-BDIO-TXT-MSG" cobol:offset="97" cobol:length="18" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafplNotfndMsg641" maxOccurs="1"  cobol:name="641-TARAFPL-NOTFND-MSG" cobol:offset="97" cobol:length="46" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="46" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafplSelectMsg641" maxOccurs="1"  cobol:name="641-TARAFPL-SELECT-MSG" cobol:offset="97" cobol:length="42" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="42" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxsNotfndMsg642" maxOccurs="1"  cobol:name="642-TARAFXS-NOTFND-MSG" cobol:offset="97" cobol:length="46" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="46" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxsSelectMsg642" maxOccurs="1"  cobol:name="642-TARAFXS-SELECT-MSG" cobol:offset="97" cobol:length="42" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="42" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxsUpdateMsg642" maxOccurs="1"  cobol:name="642-TARAFXS-UPDATE-MSG" cobol:offset="97" cobol:length="36" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="36" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxsInsertMsg642" maxOccurs="1"  cobol:name="642-TARAFXS-INSERT-MSG" cobol:offset="97" cobol:length="36" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="36" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxsNostatMsg642" maxOccurs="1"  cobol:name="642-TARAFXS-NOSTAT-MSG" cobol:offset="97" cobol:length="53" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="53" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxsCountMsg642" maxOccurs="1"  cobol:name="642-TARAFXS-COUNT-MSG" cobol:offset="97" cobol:length="42" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="42" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxsExitMsg642" maxOccurs="1"  cobol:name="642-TARAFXS-EXIT-MSG" cobol:offset="97" cobol:length="54" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="54" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxsOpenMsg642" maxOccurs="1"  cobol:name="642-TARAFXS-OPEN-MSG" cobol:offset="97" cobol:length="41" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="41" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxsFetchMsg642" maxOccurs="1"  cobol:name="642-TARAFXS-FETCH-MSG" cobol:offset="97" cobol:length="42" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="42" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxsCloseMsg642" maxOccurs="1"  cobol:name="642-TARAFXS-CLOSE-MSG" cobol:offset="97" cobol:length="42" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="42" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaNotfndMsg643" maxOccurs="1"  cobol:name="643-TARAFXA-NOTFND-MSG" cobol:offset="97" cobol:length="46" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="46" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaOpenMsg643" maxOccurs="1"  cobol:name="643-TARAFXA-OPEN-MSG" cobol:offset="97" cobol:length="41" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="41" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaFetchMsg643" maxOccurs="1"  cobol:name="643-TARAFXA-FETCH-MSG" cobol:offset="97" cobol:length="42" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="42" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarafxaCloseMsg643" maxOccurs="1"  cobol:name="643-TARAFXA-CLOSE-MSG" cobol:offset="97" cobol:length="42" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="42" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TaraefpNotfndMsg644" maxOccurs="1"  cobol:name="644-TARAEFP-NOTFND-MSG" cobol:offset="97" cobol:length="46" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="46" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TaraefpOpenMsg644" maxOccurs="1"  cobol:name="644-TARAEFP-OPEN-MSG" cobol:offset="97" cobol:length="41" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="41" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TaraefpFetchMsg644" maxOccurs="1"  cobol:name="644-TARAEFP-FETCH-MSG" cobol:offset="97" cobol:length="42" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="42" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TaraefpCloseMsg644" maxOccurs="1"  cobol:name="644-TARAEFP-CLOSE-MSG" cobol:offset="97" cobol:length="42" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="42" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TaraefpSelectMsg644" maxOccurs="1"  cobol:name="644-TARAEFP-SELECT-MSG" cobol:offset="97" cobol:length="42" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="42" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TaraefpBackupMsg644" maxOccurs="1"  cobol:name="644-TARAEFP-BACKUP-MSG" cobol:offset="97" cobol:length="53" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="53" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TaraeptNotfnd645" maxOccurs="1"  cobol:name="645-TARAEPT-NOTFND" cobol:offset="97" cobol:length="46" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="46" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TaraeptSelectMsg645" maxOccurs="1"  cobol:name="645-TARAEPT-SELECT-MSG" cobol:offset="97" cobol:length="42" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="42" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TaraeptBackupMsg645" maxOccurs="1"  cobol:name="645-TARAEPT-BACKUP-MSG" cobol:offset="97" cobol:length="53" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="53" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TaraeptRouteMsg645" maxOccurs="1"  cobol:name="645-TARAEPT-ROUTE-MSG" cobol:offset="97" cobol:length="54" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="54" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TarastsSelectMsg646" maxOccurs="1"  cobol:name="646-TARASTS-SELECT-MSG" cobol:offset="97" cobol:length="42" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="42" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlcodeMsg647" maxOccurs="1"  cobol:name="647-SQLCODE-MSG" cobol:offset="97" cobol:length="9" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DynamParmsMsg650" maxOccurs="1"  cobol:name="650-DYNAM-PARMS-MSG" cobol:offset="97" cobol:length="22" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="22" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ar647OldDsnMsg661" maxOccurs="1"  cobol:name="661-AR647-OLD-DSN-MSG" cobol:offset="97" cobol:length="14" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="14" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ar647NewDsnMsg661" maxOccurs="1"  cobol:name="661-AR647-NEW-DSN-MSG" cobol:offset="97" cobol:length="14" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="14" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ar648ErrorMsg662" maxOccurs="1"  cobol:name="662-AR648-ERROR-MSG" cobol:offset="97" cobol:length="53" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="53" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ar649ErrorMsg663" maxOccurs="1"  cobol:name="663-AR649-ERROR-MSG" cobol:offset="97" cobol:length="71" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="71" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SeqioErrorMsg670" maxOccurs="1"  cobol:name="670-SEQIO-ERROR-MSG" cobol:offset="97" cobol:length="52" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="52" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SeqioDdnameMsg670" maxOccurs="1"  cobol:name="670-SEQIO-DDNAME-MSG" cobol:offset="97" cobol:length="28" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="28" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SeqioRequestMsg670" maxOccurs="1"  cobol:name="670-SEQIO-REQUEST-MSG" cobol:offset="97" cobol:length="28" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="28" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SeqioSysidMsg670" maxOccurs="1"  cobol:name="670-SEQIO-SYSID-MSG" cobol:offset="97" cobol:length="28" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="28" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SeqioApplidMsg670" maxOccurs="1"  cobol:name="670-SEQIO-APPLID-MSG" cobol:offset="97" cobol:length="28" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="28" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SeqioDsnMsg670" maxOccurs="1"  cobol:name="670-SEQIO-DSN-MSG" cobol:offset="97" cobol:length="28" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="28" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SeqioTapserMsg670" maxOccurs="1"  cobol:name="670-SEQIO-TAPSER-MSG" cobol:offset="97" cobol:length="28" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="28" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SeqioVolserMsg670" maxOccurs="1"  cobol:name="670-SEQIO-VOLSER-MSG" cobol:offset="97" cobol:length="28" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="28" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SeqioLabelMsg670" maxOccurs="1"  cobol:name="670-SEQIO-LABEL-MSG" cobol:offset="97" cobol:length="28" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="28" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SeqioRecfmMsg670" maxOccurs="1"  cobol:name="670-SEQIO-RECFM-MSG" cobol:offset="97" cobol:length="28" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="28" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CopyFailureGft680" maxOccurs="1"  cobol:name="680-COPY-FAILURE-GFT" cobol:offset="97" cobol:length="39" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="39" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CopyFailureAppl680" maxOccurs="1"  cobol:name="680-COPY-FAILURE-APPL" cobol:offset="97" cobol:length="47" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="47" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RenameFailure680" maxOccurs="1"  cobol:name="680-RENAME-FAILURE" cobol:offset="97" cobol:length="54" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="54" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CopyCountsMsg680" maxOccurs="1"  cobol:name="680-COPY-COUNTS-MSG" cobol:offset="97" cobol:length="50" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="50" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="InstallPostExitInfo680" maxOccurs="1"  cobol:name="680-INSTALL-POST-EXIT-INFO" cobol:offset="97" cobol:length="44" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ErrorInfoMsg690" maxOccurs="1"  cobol:name="690-ERROR-INFO-MSG" cobol:offset="97" cobol:length="100" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SeeSystsprtMsg690" maxOccurs="1"  cobol:name="690-SEE-SYSTSPRT-MSG" cobol:offset="97" cobol:length="54" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="54" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ErrorConsMsg692" maxOccurs="1"  cobol:name="692-ERROR-CONS-MSG" cobol:offset="97" cobol:length="80" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="80" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ErrorConsMsgHdr692" maxOccurs="1"  cobol:name="692-ERROR-CONS-MSG-HDR" cobol:offset="97" cobol:length="55" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="Long.MAX_VALUE" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 setupEptMissing88692 VALUE [["ORIGINAL ENDPOINT NOT FOUND ON TARAEPT FOR #           "]].
                        88 setupEptBackup88692 VALUE [["BACKUP ENDPOINT NOT FOUND ON TARAEPT FOR #             "]].
                        88 setupEptBroken88692 VALUE [["BACKUP CHAIN BROKEN FOR #                              "]].
                        88 setupEptLoops88692 VALUE [["BACKUP ENDPOINT LOOPS BACK FOR #                       "]].
                        88 setupEptNonFtss88692 VALUE [["ENDPOINT IS NOT AN FTSS ENDPOINT #                     "]].
                        88 setupEfpMissing88692 VALUE [["ORIGINAL PROFILE NOT FOUND FOR #                       "]].
                        88 setupEfpBackup88692 VALUE [["BACKUP PROFILE NOT FOUND FOR #                         "]].
                        88 setupBulkNtFnd88692 VALUE [["BULK ID NOT FOUND ON TARAFPL FOR #                     "]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="55" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="OmnibusAlertFlag820" maxOccurs="1"  cobol:name="820-OMNIBUS-ALERT-FLAG" cobol:offset="97" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 alertSent88820 VALUE [["Y"]].
                        88 alertNotSent88820 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="StatRefId810" maxOccurs="1"  cobol:name="810-STAT-REF-ID" cobol:offset="97" cobol:length="4" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10K" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 srNoStatIdAssgnd88810 VALUE [[0x00ALL]].
                        88 srRecdAtDlvryEpt88810 VALUE [["0100"]].
                        88 srErrAtDlvryEpt88810 VALUE [["0110"]].
                        88 srXferIToDEpt88810 VALUE [["0120"]].
                        88 srDlvrdToDlvryEpt88810 VALUE [["0130"]].
                        88 srDlvryEptErr88810 VALUE [["0140"]].
                        88 srRecdAtIntEpt88810 VALUE [["0200"]].
                        88 srErrAtIntEpt88810 VALUE [["0210"]].
                        88 srXferHubToIe88810 VALUE [["0220"]].
                        88 srDelvrdToIe88810 VALUE [["0230"]].
                        88 srIntermdEptError88810 VALUE [["0240"]].
                        88 srInProgress88810 VALUE [["0400"]].
                        88 srAllocError88810 VALUE [["0410"]].
                        88 srIOError88810 VALUE [["0415"]].
                        88 srConfigError88810 VALUE [["0420"]].
                        88 srDuplicateFile88810 VALUE [["0430"]].
                        88 srCommError88810 VALUE [["0440"]].
                        88 srSubmitError88810 VALUE [["0450"]].
                        88 srTriggerError88810 VALUE [["0460"]].
                        88 srPrcssTermErr88810 VALUE [["0465"]].
                        88 srExitJobFailed88810 VALUE [["0470"]].
                        88 srExitSubmitErr88810 VALUE [["0475"]].
                        88 srXferMethodError88810 VALUE [["0480"]].
                        88 srEncryptionError88810 VALUE [["0481"]].
                        88 srDecryptionError88810 VALUE [["0482"]].
                        88 srDirectionError88810 VALUE [["0483"]].
                        88 srUnknownError88810 VALUE [["0490"]].
                        88 srMxrtryReached88810 VALUE [["0499"]].
                        88 srAvailable88810 VALUE [["0500"]].
                        88 srHeldByOps88810 VALUE [["0510"]].
                        88 srEndpointHold88810 VALUE [["0520"]].
                        88 srHoldFplConfig88810 VALUE [["0530"]].
                        88 srQuiesced88810 VALUE [["0540"]].
                        88 srSftCntlAdded88810 VALUE [["0550"]].
                        88 srProcessingToTape88810 VALUE [["0560"]].
                        88 srContingencyHold88810 VALUE [["0570"]].
                        88 srDownloading88810 VALUE [["0600"]].
                        88 srUploading88810 VALUE [["0605"]].
                        88 srWaitingExit88810 VALUE [["0610"]].
                        88 srWaitingPull88810 VALUE [["0620"]].
                        88 srWaitingRouting88810 VALUE [["0630"]].
                        88 srWaitingIntDlvry88810 VALUE [["0640"]].
                        88 srFileBeingPulled88810 VALUE [["0650"]].
                        88 srPushingToAppl88810 VALUE [["0660"]].
                        88 srApplPulling88810 VALUE [["0670"]].
                        88 srExitJobActive88810 VALUE [["0690"]].
                        88 srReadyForAppl88810 VALUE [["0700"]].
                        88 srXferTerminated88810 VALUE [["0710"]].
                        88 srValidating88810 VALUE [["0720"]].
                        88 srFileCreated88810 VALUE [["0730"]].
                        88 srPostXferError88810 VALUE [["0740"]].
                        88 srTerminatedByOps88810 VALUE [["0750"]].
                        88 srResetByAr0388810 VALUE [["0760"]].
                        88 srXferSuccessful88810 VALUE [["0800"]].
                        88 srCompletedByOps88810 VALUE [["0810"]].
                        88 srRetrievedByApp88810 VALUE [["0820"]].
                        88 srExitCompleted88810 VALUE [["0830"]].
                        88 srEmptyFile88810 VALUE [["0840"]].
                        88 srCompltdByJob88810 VALUE [["0850"]].
                        88 srCompltdByTape88810 VALUE [["0860"]].
                        88 srBypassedByExit88810 VALUE [["0870"]].
                        88 srGftComplete88810 VALUE [["0900"]].
                        88 srFileMigrated88810 VALUE [["0910"]].
                        88 srFileDeleted88810 VALUE [["0920"]].
                        88 srDoNotDeliver88810 VALUE [["0930"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="4" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="ErrorResponse900" maxOccurs="1"  cobol:name="900-ERROR-RESPONSE" cobol:offset="97" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ErrorMessage900" maxOccurs="1"  cobol:name="900-ERROR-MESSAGE" cobol:offset="97" cobol:length="50" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="50" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="McinfoProgramId" maxOccurs="1"  cobol:name="MCINFO-PROGRAM-ID" cobol:offset="97" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="McinfoReturnCode" maxOccurs="1"  cobol:name="MCINFO-RETURN-CODE" cobol:offset="97" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="Long.MAX_VALUE" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 mcinfoValidReturn88 VALUE [[0ALL]].
                        88 mcinfoLastDdnReturned88 VALUE [[4]].
                        88 mcinfoCopybookError88 VALUE [[8]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:short">
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Db85102cDb2CafLoadDsnali" maxOccurs="1"  cobol:name="DB85102C-DB2-CAF-LOAD-DSNALI" cobol:offset="97" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Db85102cDb2BatchErrorRtn" maxOccurs="1"  cobol:name="DB85102C-DB2-BATCH-ERROR-RTN" cobol:offset="97" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SqlTemp" maxOccurs="1"  cobol:name="SQL-TEMP" cobol:offset="97" cobol:length="128" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="128" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
