<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="XtkMsg1600" cobol:name="600-XTK-MSG1" cobol:offset="123" cobol:length="61" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Messages600Filler6" maxOccurs="1"  cobol:name="FILLER" cobol:offset="0" cobol:length="17" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="17" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Messages600Filler7" maxOccurs="1"  cobol:name="FILLER" cobol:offset="17" cobol:length="40" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="40" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="XtkStartPosition600" type="xs:int" maxOccurs="1"  cobol:name="600-XTK-START-POSITION" cobol:offset="57" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
