<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="CurrentRunMsg600" cobol:name="600-CURRENT-RUN-MSG" cobol:offset="0" cobol:length="64" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="CurrentRunMsg600Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="0" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="CurrentDate600" maxOccurs="1" cobol:name="600-CURRENT-DATE" cobol:offset="30" cobol:length="10" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="CurrentRunMsg600Filler4" maxOccurs="1"  cobol:name="FILLER" cobol:offset="40" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="CurrentTime600" maxOccurs="1" cobol:name="600-CURRENT-TIME" cobol:offset="48" cobol:length="8" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="CurrentRunMsg600Filler7" maxOccurs="1"  cobol:name="FILLER" cobol:offset="56" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
