<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Work" cobol:name="work" cobol:offset="0" cobol:length="162" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="ZLogEofSw100" maxOccurs="1"  cobol:name="100-Z-LOG-EOF-SW" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 zLogEof88100 VALUE [["Y"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="ZLogFirstRead100" maxOccurs="1"  cobol:name="100-Z-LOG-FIRST-READ" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 notFirstRead88100 VALUE [["N"]].
                        88 firstRead88100 VALUE [["Y"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="MnthMmNum100" maxOccurs="1"  cobol:name="100-MNTH-MM-NUM" cobol:offset="0" cobol:length="2" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_100" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 mnthMmNumJan88100 VALUE [["01"]].
                        88 mnthMmNumFeb88100 VALUE [["02"]].
                        88 mnthMmNumMar88100 VALUE [["03"]].
                        88 mnthMmNumApr88100 VALUE [["04"]].
                        88 mnthMmNumMay88100 VALUE [["05"]].
                        88 mnthMmNumJun88100 VALUE [["06"]].
                        88 mnthMmNumJul88100 VALUE [["07"]].
                        88 mnthMmNumAug88100 VALUE [["08"]].
                        88 mnthMmNumSep88100 VALUE [["09"]].
                        88 mnthMmNumOct88100 VALUE [["10"]].
                        88 mnthMmNumNov88100 VALUE [["11"]].
                        88 mnthMmNumDec88100 VALUE [["12"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="2" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
         <xs:element name="MaxLinesPerPage300" type="xs:short" maxOccurs="1"  cobol:name="300-MAX-LINES-PER-PAGE" cobol:offset="0" cobol:length="2" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="Plus1300" type="xs:int" maxOccurs="1"  cobol:name="300-PLUS-1" cobol:offset="2" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="Plus4300" type="xs:int" maxOccurs="1"  cobol:name="300-PLUS-4" cobol:offset="3" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="Plus7300" type="xs:int" maxOccurs="1"  cobol:name="300-PLUS-7" cobol:offset="4" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="Num1300" type="xs:int" maxOccurs="1"  cobol:name="300-NUM-1" cobol:offset="5" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="Num2300" type="xs:int" maxOccurs="1"  cobol:name="300-NUM-2" cobol:offset="6" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="Num4300" type="xs:int" maxOccurs="1"  cobol:name="300-NUM-4" cobol:offset="7" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
    <xs:element name="LitC300" maxOccurs="1"  cobol:name="300-LIT-C" cobol:offset="8" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="LitUnknwn300" maxOccurs="1"  cobol:name="300-LIT-UNKNWN" cobol:offset="8" cobol:length="20" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Num100300" type="xs:short" maxOccurs="1"  cobol:name="300-NUM-100" cobol:offset="8" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="MonthJan300" maxOccurs="1"  cobol:name="300-MONTH-JAN" cobol:offset="8" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MonthFeb300" maxOccurs="1"  cobol:name="300-MONTH-FEB" cobol:offset="8" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MonthMar300" maxOccurs="1"  cobol:name="300-MONTH-MAR" cobol:offset="8" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MonthApr300" maxOccurs="1"  cobol:name="300-MONTH-APR" cobol:offset="8" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MonthMay300" maxOccurs="1"  cobol:name="300-MONTH-MAY" cobol:offset="8" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MonthJun300" maxOccurs="1"  cobol:name="300-MONTH-JUN" cobol:offset="8" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MonthJul300" maxOccurs="1"  cobol:name="300-MONTH-JUL" cobol:offset="8" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MonthAug300" maxOccurs="1"  cobol:name="300-MONTH-AUG" cobol:offset="8" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MonthSep300" maxOccurs="1"  cobol:name="300-MONTH-SEP" cobol:offset="8" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MonthOct300" maxOccurs="1"  cobol:name="300-MONTH-OCT" cobol:offset="8" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MonthNov300" maxOccurs="1"  cobol:name="300-MONTH-NOV" cobol:offset="8" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MonthDec300" maxOccurs="1"  cobol:name="300-MONTH-DEC" cobol:offset="8" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="ZLogCnt400" type="xs:long" maxOccurs="1"  cobol:name="400-Z-LOG-CNT" cobol:offset="8" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="Rpt1LineCount400" type="xs:long" maxOccurs="1"  cobol:name="400-RPT1-LINE-COUNT" cobol:offset="14" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="PageCount400" type="xs:long" maxOccurs="1"  cobol:name="400-PAGE-COUNT" cobol:offset="20" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="TotServiceCnt400" type="xs:long" maxOccurs="1"  cobol:name="400-TOT-SERVICE-CNT" cobol:offset="26" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="TotRecWritten400" type="xs:long" maxOccurs="1"  cobol:name="400-TOT-REC-WRITTEN" cobol:offset="32" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="SuccessCnt400" type="xs:long" maxOccurs="1"  cobol:name="400-SUCCESS-CNT" cobol:offset="38" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="ErrorCnt400" type="xs:long" maxOccurs="1"  cobol:name="400-ERROR-CNT" cobol:offset="44" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="HighElapseTime400" type="xs:int" maxOccurs="1"  cobol:name="400-HIGH-ELAPSE-TIME" cobol:offset="50" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
         <xs:element name="LowElapseTime400" type="xs:int" maxOccurs="1"  cobol:name="400-LOW-ELAPSE-TIME" cobol:offset="55" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
         <xs:element name="SumElapsedTime400" type="xs:long" maxOccurs="1"  cobol:name="400-SUM-ELAPSED-TIME" cobol:offset="60" cobol:length="7" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T"/>
    <xs:element name="SuccessPercent400" maxOccurs="1"  cobol:name="400-SUCCESS-PERCENT" cobol:offset="67" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="5" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ErrPercent400" maxOccurs="1"  cobol:name="400-ERR-PERCENT" cobol:offset="70" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="5" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AvgElapsed400" maxOccurs="1"  cobol:name="400-AVG-ELAPSED" cobol:offset="73" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="14" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ExecStartMsg600" maxOccurs="1"  cobol:name="600-EXEC-START-MSG" cobol:offset="81" cobol:length="64" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="64" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Message6008000" maxOccurs="1"  cobol:name="600-8000-MESSAGE" cobol:offset="81" cobol:length="62" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="62" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Message6008999" maxOccurs="1"  cobol:name="600-8999-MESSAGE" cobol:offset="81" cobol:length="62" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="62" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="NoInputData6000001" maxOccurs="1"  cobol:name="600-0001-NO-INPUT-DATA" cobol:offset="81" cobol:length="55" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="55" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="EojMessage6009500" maxOccurs="1"  cobol:name="600-9500-EOJ-MESSAGE" cobol:offset="81" cobol:length="44" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HeaderLine3703" maxOccurs="1"  cobol:name="703-HEADER-LINE-3" cobol:offset="81" cobol:length="137" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="137" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HeaderLine4704" maxOccurs="1"  cobol:name="704-HEADER-LINE-4" cobol:offset="81" cobol:length="149" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="149" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="EmptyReport706" maxOccurs="1"  cobol:name="706-EMPTY-REPORT" cobol:offset="81" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HoldServiceId800" maxOccurs="1"  cobol:name="800-HOLD-SERVICE-ID" cobol:offset="81" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RunMonth800" maxOccurs="1"  cobol:name="800-RUN-MONTH" cobol:offset="81" cobol:length="3" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SuccessCnt800" maxOccurs="1"  cobol:name="800-SUCCESS-CNT" cobol:offset="81" cobol:length="11" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SuccessPercent800" maxOccurs="1"  cobol:name="800-SUCCESS-PERCENT" cobol:offset="92" cobol:length="6" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ErrorCnt800" maxOccurs="1"  cobol:name="800-ERROR-CNT" cobol:offset="98" cobol:length="11" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="UnsuccessPercent800" maxOccurs="1"  cobol:name="800-UNSUCCESS-PERCENT" cobol:offset="109" cobol:length="6" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AvgElapsed800" maxOccurs="1"  cobol:name="800-AVG-ELAPSED" cobol:offset="115" cobol:length="14" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="14" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HighElapseTime800" maxOccurs="1"  cobol:name="800-HIGH-ELAPSE-TIME" cobol:offset="129" cobol:length="11" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="LowElapseTime800" maxOccurs="1"  cobol:name="800-LOW-ELAPSE-TIME" cobol:offset="140" cobol:length="11" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TotServiceCnt800" maxOccurs="1"  cobol:name="800-TOT-SERVICE-CNT" cobol:offset="151" cobol:length="11" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
