<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Work" cobol:name="work" cobol:offset="0" cobol:length="0" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="SLen2" type="xs:short" maxOccurs="1"  cobol:name="WS-2-S-LEN" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TLen2" type="xs:short" maxOccurs="1"  cobol:name="WS-2-T-LEN" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="AS22" maxOccurs="1"  cobol:name="WS-2-2A-S" cobol:offset="0" cobol:length="70" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="70" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="BS22" maxOccurs="1"  cobol:name="WS-2-2B-S" cobol:offset="0" cobol:length="70" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="70" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AS24" maxOccurs="1"  cobol:name="WS-2-4A-S" cobol:offset="0" cobol:length="70" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="70" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="BS24" maxOccurs="1"  cobol:name="WS-2-4B-S" cobol:offset="0" cobol:length="70" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="70" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AS28" maxOccurs="1"  cobol:name="WS-2-8A-S" cobol:offset="0" cobol:length="70" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="70" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="BS28" maxOccurs="1"  cobol:name="WS-2-8B-S" cobol:offset="0" cobol:length="70" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="70" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AS212" maxOccurs="1"  cobol:name="WS-2-12A-S" cobol:offset="0" cobol:length="70" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="70" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="BS212" maxOccurs="1"  cobol:name="WS-2-12B-S" cobol:offset="0" cobol:length="70" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="70" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AS218" maxOccurs="1"  cobol:name="WS-2-18A-S" cobol:offset="0" cobol:length="70" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="70" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="BS218" maxOccurs="1"  cobol:name="WS-2-18B-S" cobol:offset="0" cobol:length="70" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="70" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AS220" maxOccurs="1"  cobol:name="WS-2-20A-S" cobol:offset="0" cobol:length="70" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="70" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="BS220" maxOccurs="1"  cobol:name="WS-2-20B-S" cobol:offset="0" cobol:length="70" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="70" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Wse22aS" maxOccurs="1"  cobol:name="WSE-2-2A-S" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Wse22bS" maxOccurs="1"  cobol:name="WSE-2-2B-S" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Wse24aS" maxOccurs="1"  cobol:name="WSE-2-4A-S" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Wse24bS" maxOccurs="1"  cobol:name="WSE-2-4B-S" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Wse28aS" maxOccurs="1"  cobol:name="WSE-2-8A-S" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Wse28bS" maxOccurs="1"  cobol:name="WSE-2-8B-S" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Wse212aS" maxOccurs="1"  cobol:name="WSE-2-12A-S" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Wse212bS" maxOccurs="1"  cobol:name="WSE-2-12B-S" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Wse218aS" maxOccurs="1"  cobol:name="WSE-2-18A-S" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Wse218bS" maxOccurs="1"  cobol:name="WSE-2-18B-S" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Wse220aS" maxOccurs="1"  cobol:name="WSE-2-20A-S" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Wse220bS" maxOccurs="1"  cobol:name="WSE-2-20B-S" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Wse220cT" maxOccurs="1"  cobol:name="WSE-2-20C-T" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
