<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Work" cobol:name="work" cobol:offset="0" cobol:length="42" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Data0Len" type="xs:short" maxOccurs="1"  cobol:name="WS-DATA0-LEN" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="Data0" maxOccurs="1"  cobol:name="WS-DATA0" cobol:offset="0" cobol:length="98" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="98" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Data" maxOccurs="1"  cobol:name="WS-DATA" cobol:offset="0" cobol:length="150" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="150" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Delim1" maxOccurs="1"  cobol:name="WS-DELIM1" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Delim3" maxOccurs="1"  cobol:name="WS-DELIM3" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Delim4" maxOccurs="1"  cobol:name="WS-DELIM4" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Count" type="xs:int" maxOccurs="1"  cobol:name="WS-COUNT" cobol:offset="0" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Count1" type="xs:int" maxOccurs="1"  cobol:name="WS-COUNT1" cobol:offset="0" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Count2" type="xs:long" maxOccurs="1"  cobol:name="WS-COUNT2" cobol:offset="0" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Count3" type="xs:int" maxOccurs="1"  cobol:name="WS-COUNT3" cobol:offset="9" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
         <xs:element name="Count4" type="xs:long" maxOccurs="1"  cobol:name="WS-COUNT4" cobol:offset="12" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Count5" type="xs:int" maxOccurs="1"  cobol:name="WS-COUNT5" cobol:offset="21" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
         <xs:element name="Tally" type="xs:long" maxOccurs="1"  cobol:name="WS-TALLY" cobol:offset="24" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Pointer" type="xs:long" maxOccurs="1"  cobol:name="WS-POINTER" cobol:offset="33" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
    <xs:element name="Field1" maxOccurs="1"  cobol:name="WS-FIELD1" cobol:offset="42" cobol:length="35" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="35" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Field2" maxOccurs="1"  cobol:name="WS-FIELD2" cobol:offset="42" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Field3" maxOccurs="1"  cobol:name="WS-FIELD3" cobol:offset="42" cobol:length="35" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="35" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Field4" maxOccurs="1"  cobol:name="WS-FIELD4" cobol:offset="42" cobol:length="35" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="35" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Field5" maxOccurs="1"  cobol:name="WS-FIELD5" cobol:offset="42" cobol:length="60" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="InputRec" maxOccurs="1"  cobol:name="INPUT-REC" cobol:offset="42" cobol:length="100" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="InputRecOverflw1" maxOccurs="1"  cobol:name="INPUT-REC-OVERFLW1" cobol:offset="42" cobol:length="100" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="InputRecOverflw2" maxOccurs="1"  cobol:name="INPUT-REC-OVERFLW2" cobol:offset="42" cobol:length="100" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="InputRecOverflw3" maxOccurs="1"  cobol:name="INPUT-REC-OVERFLW3" cobol:offset="42" cobol:length="100" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Val1" maxOccurs="1"  cobol:name="WS-VAL1" cobol:offset="42" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Val2" maxOccurs="1"  cobol:name="WS-VAL2" cobol:offset="42" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Val3" maxOccurs="1"  cobol:name="WS-VAL3" cobol:offset="42" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Val4" maxOccurs="1"  cobol:name="WS-VAL4" cobol:offset="42" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Val5" maxOccurs="1"  cobol:name="WS-VAL5" cobol:offset="42" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Val6" maxOccurs="1"  cobol:name="WS-VAL6" cobol:offset="42" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Val7" maxOccurs="1"  cobol:name="WS-VAL7" cobol:offset="42" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Val8" maxOccurs="1"  cobol:name="WS-VAL8" cobol:offset="42" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Val9" maxOccurs="1"  cobol:name="WS-VAL9" cobol:offset="42" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Vala" maxOccurs="1"  cobol:name="WS-VALA" cobol:offset="42" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Valb" maxOccurs="1"  cobol:name="WS-VALB" cobol:offset="42" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Valc" maxOccurs="1"  cobol:name="WS-VALC" cobol:offset="42" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Retain" maxOccurs="1"  cobol:name="WS-RETAIN" cobol:offset="42" cobol:length="100" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
