<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="IchgCalcVars800" cobol:name="800-ICHG-CALC-VARS" cobol:offset="0" cobol:length="183" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="ViaAmt800" maxOccurs="1"  cobol:name="800-VIA-AMT" cobol:offset="0" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FiaAmt800" maxOccurs="1"  cobol:name="800-FIA-AMT" cobol:offset="12" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="NetAmt800" maxOccurs="1"  cobol:name="800-NET-AMT" cobol:offset="24" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ClrTxnAmt6800" maxOccurs="1"  cobol:name="800-CLR-TXN-AMT-6" cobol:offset="36" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="18" />
                  <xs:fractionDigits value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ViaRate800" maxOccurs="1"  cobol:name="800-VIA-RATE" cobol:offset="54" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="11" />
                  <xs:fractionDigits value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MinAmt800" maxOccurs="1"  cobol:name="800-MIN-AMT" cobol:offset="65" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MaxAmt800" maxOccurs="1"  cobol:name="800-MAX-AMT" cobol:offset="77" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ViaRate801" maxOccurs="1"  cobol:name="801-VIA-RATE" cobol:offset="89" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="11" />
                  <xs:fractionDigits value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FiaAmt801" maxOccurs="1"  cobol:name="801-FIA-AMT" cobol:offset="100" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MinAmt801" maxOccurs="1"  cobol:name="801-MIN-AMT" cobol:offset="112" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MaxAmt801" maxOccurs="1"  cobol:name="801-MAX-AMT" cobol:offset="124" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ViaRate802" maxOccurs="1"  cobol:name="802-VIA-RATE" cobol:offset="136" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="11" />
                  <xs:fractionDigits value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FiaAmt802" maxOccurs="1"  cobol:name="802-FIA-AMT" cobol:offset="147" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MinAmt802" maxOccurs="1"  cobol:name="802-MIN-AMT" cobol:offset="159" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MaxAmt802" maxOccurs="1"  cobol:name="802-MAX-AMT" cobol:offset="171" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
