  package com.cloudframe.app.process;
  /* Java code generated by CloudFrame on 2025-04-21 at 12:15. */
  
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import org.springframework.web.bind.annotation.RequestParam;
  import java.math.BigDecimal;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.data.Field;
  import com.cloudframe.app.callprm2.dto.*;
  import com.cloudframe.app.callprm2.dto.LsParm1Group;
  import com.cloudframe.app.callprm2.dto.LsParm4Group;
  import com.cloudframe.app.callprm2.dto.LsParm5Group;
  import com.cloudframe.app.callprm2.dto.LsParm2Group;
  import com.cloudframe.app.callprm2.dto.LsParm3Group;
  import com.cloudframe.app.callprm2.dto.LsParm6Group;
  import com.cloudframe.app.callprm2.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("callprm2")
  
  public class Callprm2 extends CommonProcess {
  
  Logger logger = LoggerFactory.getLogger(Callprm2.class);
  
  private LsParm1Group lsParm1Group = new LsParm1Group() ;
  private LsParm4Group lsParm4Group = new LsParm4Group() ;
  private LsParm5Group lsParm5Group = new LsParm5Group() ;
  private LsParm2Group lsParm2Group = new LsParm2Group() ;
  private LsParm3Group lsParm3Group = new LsParm3Group() ;
  private LsParm6Group lsParm6Group = new LsParm6Group() ;
  private Work work = new Work() ;
  
  
  
  
  
  
  
  
  
      public int setParameter(String lsParm1Group,String lsParm2Group,String lsParm3Group,String lsParm4Group,String lsParm5Group,String lsParm6Group) throws Exception {
      		if(lsParm1Group != null)
      		    this.lsParm1Group.setString(com.cloudframe.app.data.Field.getParm(lsParm1Group),new String(CONSTANTS.EBCDIC_ENCODING));
      		if(lsParm2Group != null)
      		    this.lsParm2Group.setString(com.cloudframe.app.data.Field.getParm(lsParm2Group),new String(CONSTANTS.EBCDIC_ENCODING));
      		if(lsParm3Group != null)
      		    this.lsParm3Group.setString(com.cloudframe.app.data.Field.getParm(lsParm3Group),new String(CONSTANTS.EBCDIC_ENCODING));
      		if(lsParm4Group != null)
      		    this.lsParm4Group.setString(com.cloudframe.app.data.Field.getParm(lsParm4Group),new String(CONSTANTS.EBCDIC_ENCODING));
      		if(lsParm5Group != null)
      		    this.lsParm5Group.setString(com.cloudframe.app.data.Field.getParm(lsParm5Group),new String(CONSTANTS.EBCDIC_ENCODING));
      		if(lsParm6Group != null)
      		    this.lsParm6Group.setString(com.cloudframe.app.data.Field.getParm(lsParm6Group),new String(CONSTANTS.EBCDIC_ENCODING));
      		setInitDone(false);
      		process();
      		return getRc();
      }
      /**
      * process 
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      @Override
      public int process() throws Exception {
       initVars();
       try {
       setCodePage("1047");
          ;
//  PERFORM MAINLINE
          mainline();/*MAINLINE*/
          if (this.isProgramEnded()) {
              return getRc();
          }
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
       return getRc(); // Exit with return code
      // end of process method
      }
      /**
      * mainline 
      *   This method is derived from 
  *   COBOL Paragraph - MAINLINE COBOL Cyclomatic complexity - 2
      * Input  :  

      * - lsParm1                        COBOL Name: LS-PARM1
      * - lsParm2                        COBOL Name: LS-PARM2
      * - lsParm3                        COBOL Name: LS-PARM3
      * - lsParm4                        COBOL Name: LS-PARM4
      * - lsParm5                        COBOL Name: LS-PARM5
      * - lsParm6                        COBOL Name: LS-PARM6
      *
      * Output :  

      * - lsParm1                        COBOL Name: LS-PARM1
      * - lsParm2                        COBOL Name: LS-PARM2
      * - lsParm3                        COBOL Name: LS-PARM3
      * - lsParm4                        COBOL Name: LS-PARM4
      * - lsParm5                        COBOL Name: LS-PARM5
      * - lsParm6                        COBOL Name: LS-PARM6
      *
      * @throws CFException
      */
      private void mainline() throws Exception {
      
// *
//  DISPLAY '>>> IN CALLPRM2 '
          logger.info(">>> IN CALLPRM2 "); 
//  DISPLAY '    LS-PARM1 = ' LS-PARM1
          logger.info("    LS-PARM1 = {}", new String(lsParm1Group.getLsParm1())); 
//  DISPLAY '    LS-PARM2 = ' LS-PARM2
          logger.info("    LS-PARM2 = {}", String.valueOf(lsParm2Group.getLsParm2())); 
//  DISPLAY '    LS-PARM3 = ' LS-PARM3
          logger.info("    LS-PARM3 = {}", String.valueOf(lsParm3Group.getLsParm3().movePointRight(2))); 
//  DISPLAY '    LS-PARM4 = ' LS-PARM4
          logger.info("    LS-PARM4 = {}", new String(lsParm4Group.getLsParm4())); 
//  DISPLAY '    LS-PARM5 = ' LS-PARM5
          logger.info("    LS-PARM5 = {}", String.valueOf(lsParm5Group.getLsParm5())); 
//  DISPLAY '    LS-PARM6 = ' LS-PARM6
          logger.info("    LS-PARM6 = {}", String.valueOf(lsParm6Group.getLsParm6().movePointRight(2))); 
//  MOVE 'ETACOLER' TO LS-PARM1
//  LITERAL_ETACOLER = 'ETACOLER'
          lsParm1Group.setLsParm1(CONSTANTS.LITERAL_ETACOLER);
//  MOVE 9876 TO LS-PARM2
          lsParm2Group.setLsParm2((short)9876);
//  MOVE 98.76 TO LS-PARM3
          lsParm3Group.setLsParm3(BigDecimal.valueOf(98.76).setScale(2));
//  MOVE 'ETAVONER' TO LS-PARM4
//  LITERAL_ETAVONER = 'ETAVONER'
          lsParm4Group.setLsParm4(CONSTANTS.LITERAL_ETAVONER);
//  MOVE 0987 TO LS-PARM5
          lsParm5Group.setLsParm5((short)987);
//  MOVE 09.87 TO LS-PARM6
          lsParm6Group.setLsParm6(BigDecimal.valueOf(09.87).setScale(2));

// *
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          this.setProgramEnded(true);
          return ;
      
      }
  
  
      /**
* This method pre-initializes variables consistent with
* what a mainframe program would have done at the start of a program
*/
      @Override
      public void initVars() throws CFException {
      setProgramEnded(false);
          if(!isInitDone()) {
          	this.setRc(0);
          	setInitDone(true);
          }
        CFUtil.resetDecimalAsComma();
       }
  
      public int call(Object[] params) throws Exception {
      
      int len = params.length;
         if (len > 0 && params[0] != null )
            lsParm1Group.set((Field)params[0]);
         if (len > 1 && params[1] != null )
            lsParm2Group.set((Field)params[1]);
         if (len > 2 && params[2] != null )
            lsParm3Group.set((Field)params[2]);
         if (len > 3 && params[3] != null )
            lsParm4Group.set((Field)params[3]);
         if (len > 4 && params[4] != null )
            lsParm5Group.set((Field)params[4]);
         if (len > 5 && params[5] != null )
            lsParm6Group.set((Field)params[5]);
         // invoke the process and return rc
         return process();
         
      }
      
      public int call(Field... parameters) throws Exception {
         for (int index = 0; index < parameters.length;index++) {
             switch(index) {
              case 0:
                      if(parameters[index] != null ) {
              		if (parameters[index] instanceof LsParm1Group) {
                       	this.lsParm1Group = ((LsParm1Group) parameters[index]);
                  	} else {
                       	this.lsParm1Group.set(parameters[index]);
                  	}
                  }
                
                  break;
              case 1:
                      if(parameters[index] != null ) {
              		if (parameters[index] instanceof LsParm2Group) {
                       	this.lsParm2Group = ((LsParm2Group) parameters[index]);
                  	} else {
                       	this.lsParm2Group.set(parameters[index]);
                  	}
                  }
                
                  break;
              case 2:
                      if(parameters[index] != null ) {
              		if (parameters[index] instanceof LsParm3Group) {
                       	this.lsParm3Group = ((LsParm3Group) parameters[index]);
                  	} else {
                       	this.lsParm3Group.set(parameters[index]);
                  	}
                  }
                
                  break;
              case 3:
                      if(parameters[index] != null ) {
              		if (parameters[index] instanceof LsParm4Group) {
                       	this.lsParm4Group = ((LsParm4Group) parameters[index]);
                  	} else {
                       	this.lsParm4Group.set(parameters[index]);
                  	}
                  }
                
                  break;
              case 4:
                      if(parameters[index] != null ) {
              		if (parameters[index] instanceof LsParm5Group) {
                       	this.lsParm5Group = ((LsParm5Group) parameters[index]);
                  	} else {
                       	this.lsParm5Group.set(parameters[index]);
                  	}
                  }
                
                  break;
              case 5:
                      if(parameters[index] != null ) {
              		if (parameters[index] instanceof LsParm6Group) {
                       	this.lsParm6Group = ((LsParm6Group) parameters[index]);
                  	} else {
                       	this.lsParm6Group.set(parameters[index]);
                  	}
                  }
                
                  break;
            }
         }
          return process();
      }
      
      
  
  
  
  
  
  }
