package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] FORMAT_1395802937 = "+9999".toCharArray();
public static final char[] FORMAT_1453061239 = "-9999".toCharArray();
 
}
