#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
#logging.level.com.cloudframe=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
#
SortalljclSort1SortIn=CLOUDFRM.JPM.SORT.INPUT1
SortalljclSort1SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort1SortInRecordType=FB
SortalljclSort1SortInRecordLen=200
#
SortalljclSort1SortOut=CLOUDFRM.JPM.SORT.OUTPUT1
SortalljclSort1SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort1SortOutRecordType=FB
SortalljclSort1SortOutRecordLen=200
#
SortalljclSort2SortIn=CLOUDFRM.JPM.SORT.INPUT2
SortalljclSort2SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort2SortInRecordType=FB
SortalljclSort2SortInRecordLen=200
#
SortalljclSort2SortOut=CLOUDFRM.JPM.SORT.OUTPUT2
SortalljclSort2SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort2SortOutRecordType=FB
SortalljclSort2SortOutRecordLen=200
#
SortalljclSort3SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort3SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort3SortInRecordType=FB
SortalljclSort3SortInRecordLen=200
#
SortalljclSort3SortOut=CLOUDFRM.JPM.SORT.OUTPUT3
SortalljclSort3SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort3SortOutRecordType=FB
SortalljclSort3SortOutRecordLen=200
#
SortalljclSort4SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort4SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort4SortInRecordType=FB
SortalljclSort4SortInRecordLen=200
#
SortalljclSort4SortOut=CLOUDFRM.JPM.SORT.OUTPUT4
SortalljclSort4SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort4SortOutRecordType=FB
SortalljclSort4SortOutRecordLen=200
#
SortalljclSort5SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort5SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort5SortInRecordType=FB
SortalljclSort5SortInRecordLen=200
#
SortalljclSort5SortOut=CLOUDFRM.JPM.SORT.OUTPUT5
SortalljclSort5SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort5SortOutRecordType=FB
SortalljclSort5SortOutRecordLen=200
#
SortalljclSort6SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort6SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort6SortInRecordType=FB
SortalljclSort6SortInRecordLen=200
#
SortalljclSort6SortOut=CLOUDFRM.JPM.SORT.OUTPUT6
SortalljclSort6SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort6SortOutRecordType=FB
SortalljclSort6SortOutRecordLen=9
#
SortalljclSort7SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort7SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort7SortInRecordType=FB
SortalljclSort7SortInRecordLen=200
#
SortalljclSort7SortOut=CLOUDFRM.JPM.SORT.OUTPUT7
SortalljclSort7SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort7SortOutRecordType=FB
SortalljclSort7SortOutRecordLen=200
#
SortalljclSort8SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort8SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort8SortInRecordType=FB
SortalljclSort8SortInRecordLen=200
#
SortalljclSort8SortOut=CLOUDFRM.JPM.SORT.OUTPUT8
SortalljclSort8SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort8SortOutRecordType=FB
SortalljclSort8SortOutRecordLen=12
#
SortalljclSort9SortIn=CLOUDFRM.JPM.SORT.INPUT9
SortalljclSort9SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort9SortInRecordType=FB
SortalljclSort9SortInRecordLen=52
#
SortalljclSort9SortOut=CLOUDFRM.JPM.SORT.OUTPUT9
SortalljclSort9SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort9SortOutRecordType=FB
SortalljclSort9SortOutRecordLen=8
#
SortalljclSort10SortIn=CLOUDFRM.JPM.SORT.INPUT10
SortalljclSort10SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort10SortInRecordType=FB
SortalljclSort10SortInRecordLen=52
#
SortalljclSort10SortOut=CLOUDFRM.JPM.SORT.OUTPUT10
SortalljclSort10SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort10SortOutRecordType=FB
SortalljclSort10SortOutRecordLen=52
#
SortalljclSort11SortIn=CLOUDFRM.JPM.SORT.INPUT11
SortalljclSort11SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort11SortInRecordType=FB
SortalljclSort11SortInRecordLen=52
#
SortalljclSort11SortOut=CLOUDFRM.JPM.SORT.OUTPUT11
SortalljclSort11SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort11SortOutRecordType=FB
SortalljclSort11SortOutRecordLen=11
#
SortalljclSort12SortIn=CLOUDFRM.JPM.SORT.INPUT12
SortalljclSort12SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort12SortInRecordType=FB
SortalljclSort12SortInRecordLen=52
#
SortalljclSort12SortOut=CLOUDFRM.JPM.SORT.OUTPUT12
SortalljclSort12SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort12SortOutRecordType=FB
SortalljclSort12SortOutRecordLen=52
#
SortalljclSort13SortIn=CLOUDFRM.JPM.SORT.INPUT13
SortalljclSort13SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort13SortInRecordType=FB
SortalljclSort13SortInRecordLen=52
#
SortalljclSort13SortOut=CLOUDFRM.JPM.SORT.OUTPUT13
SortalljclSort13SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort13SortOutRecordType=FB
SortalljclSort13SortOutRecordLen=52
#
SortalljclSort14SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort14SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort14SortInRecordType=FB
SortalljclSort14SortInRecordLen=200
#
SortalljclSort14SortOut=CLOUDFRM.JPM.SORT.OUTPUT14
SortalljclSort14SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort14SortOutRecordType=FB
SortalljclSort14SortOutRecordLen=200
#
SortalljclSort15SortIn[0]=CLOUDFRM.JPM.SORT.INPUT151
SortalljclSort15SortIn[0].DISP=SHR,KEEP,KEEP
SortalljclSort15SortIn[1]=CLOUDFRM.JPM.SORT.INPUT152
SortalljclSort15SortIn[1].DISP=SHR,KEEP,KEEP
SortalljclSort15SortInRecordType=FB
SortalljclSort15SortInRecordLen=200
#
SortalljclSort15SortOut=CLOUDFRM.JPM.SORT.OUTPUT15
SortalljclSort15SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort15SortOutRecordType=FB
SortalljclSort15SortOutRecordLen=200
#
SortalljclSort16SortIn[0]=CLOUDFRM.JPM.SORT.INPUT161
SortalljclSort16SortIn[0].DISP=SHR,KEEP,KEEP
SortalljclSort16SortIn[1]=CLOUDFRM.JPM.SORT.INPUT162
SortalljclSort16SortIn[1].DISP=SHR,KEEP,KEEP
SortalljclSort16SortIn[2]=CLOUDFRM.JPM.SORT.INPUT163
SortalljclSort16SortIn[2].DISP=SHR,KEEP,KEEP
SortalljclSort16SortInRecordType=FB
SortalljclSort16SortInRecordLen=200
#
SortalljclSort16SortOut=CLOUDFRM.JPM.SORT.OUTPUT16
SortalljclSort16SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort16SortOutRecordType=FB
SortalljclSort16SortOutRecordLen=200
#
SortalljclSort18SortIn=CLOUDFRM.JPM.SORT.INPUT18
SortalljclSort18SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort18SortInRecordType=FB
SortalljclSort18SortInRecordLen=52
#
SortalljclSort18SortOut=CLOUDFRM.JPM.SORT.OUTPUT18
SortalljclSort18SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort18SortOutRecordType=FB
SortalljclSort18SortOutRecordLen=40
#
SortalljclSort19SortIn=CLOUDFRM.JPM.SORT.INPUT19
SortalljclSort19SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort19SortInRecordType=FB
SortalljclSort19SortInRecordLen=200
#
SortalljclSort19SortOut=CLOUDFRM.JPM.SORT.OUTPUT19
SortalljclSort19SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort19SortOutRecordType=FB
SortalljclSort19SortOutRecordLen=300
#
SortalljclSort20SortIn=CLOUDFRM.JPM.SORT.INPUT20
SortalljclSort20SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort20SortInRecordType=FB
SortalljclSort20SortInRecordLen=52
#
SortalljclSort20SortOut=CLOUDFRM.JPM.SORT.OUTPUT20
SortalljclSort20SortOut.DISP=NEW,KEEP,KEEP
SortalljclSort20SortOutRecordType=FB
SortalljclSort20SortOutRecordLen=9
#
cf.sort.useTempFile=no
#
#VSAM specific db properties (h2)
spring.cf.db.enabled=true
spring.cf.db.jdbc-url=jdbc:h2:file:./cf-vsam-db;DEFRAG_ALWAYS=true;
spring.cf.db.driverClassName=org.h2.Driver
spring.cf.db.username=sa
spring.cf.db.password=
#spring.cf.fetch-size=500
#uncomment below property to disable in-memory load of VSAM
#cf.vsam.load.inmemory=false
#end of h2
#
