#STEP:SORT1| PGM:SORT| DD:SORTIN
SortalljclSort1SortIn=CLOUDFRM.JPM.SORT.INPUT1
SortalljclSort1SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort1SortInRecordType=FB
SortalljclSort1SortInRecordLen=<recordLen>
#STEP:SORT1| PGM:SORT| DD:SORTOUT
SortalljclSort1SortOut=CLOUDFRM.JPM.SORT.OUTPUT1
SortalljclSort1SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort1SortOutRecordType=FB
SortalljclSort1SortOutRecordLen=<recordLen>
#STEP:SORT2| PGM:SORT| DD:SORTIN
SortalljclSort2SortIn=CLOUDFRM.JPM.SORT.INPUT2
SortalljclSort2SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort2SortInRecordType=FB
SortalljclSort2SortInRecordLen=<recordLen>
#STEP:SORT2| PGM:SORT| DD:SORTOUT
SortalljclSort2SortOut=CLOUDFRM.JPM.SORT.OUTPUT2
SortalljclSort2SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort2SortOutRecordType=FB
SortalljclSort2SortOutRecordLen=<recordLen>
#STEP:SORT3| PGM:SORT| DD:SORTIN
SortalljclSort3SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort3SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort3SortInRecordType=FB
SortalljclSort3SortInRecordLen=<recordLen>
#STEP:SORT3| PGM:SORT| DD:SORTOUT
SortalljclSort3SortOut=CLOUDFRM.JPM.SORT.OUTPUT3
SortalljclSort3SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort3SortOutRecordType=FB
SortalljclSort3SortOutRecordLen=<recordLen>
#STEP:SORT4| PGM:SORT| DD:SORTIN
SortalljclSort4SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort4SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort4SortInRecordType=FB
SortalljclSort4SortInRecordLen=<recordLen>
#STEP:SORT4| PGM:SORT| DD:SORTOUT
SortalljclSort4SortOut=CLOUDFRM.JPM.SORT.OUTPUT4
SortalljclSort4SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort4SortOutRecordType=FB
SortalljclSort4SortOutRecordLen=<recordLen>
#STEP:SORT5| PGM:SORT| DD:SORTIN
SortalljclSort5SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort5SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort5SortInRecordType=FB
SortalljclSort5SortInRecordLen=<recordLen>
#STEP:SORT5| PGM:SORT| DD:SORTOUT
SortalljclSort5SortOut=CLOUDFRM.JPM.SORT.OUTPUT5
SortalljclSort5SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort5SortOutRecordType=FB
SortalljclSort5SortOutRecordLen=<recordLen>
#STEP:SORT6| PGM:SORT| DD:SORTIN
SortalljclSort6SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort6SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort6SortInRecordType=FB
SortalljclSort6SortInRecordLen=<recordLen>
#STEP:SORT6| PGM:SORT| DD:SORTOUT
SortalljclSort6SortOut=CLOUDFRM.JPM.SORT.OUTPUT6
SortalljclSort6SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort6SortOutRecordType=FB
SortalljclSort6SortOutRecordLen=<recordLen>
#STEP:SORT7| PGM:SORT| DD:SORTIN
SortalljclSort7SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort7SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort7SortInRecordType=FB
SortalljclSort7SortInRecordLen=<recordLen>
#STEP:SORT7| PGM:SORT| DD:SORTOUT
SortalljclSort7SortOut=CLOUDFRM.JPM.SORT.OUTPUT7
SortalljclSort7SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort7SortOutRecordType=FB
SortalljclSort7SortOutRecordLen=<recordLen>
#STEP:SORT8| PGM:SORT| DD:SORTIN
SortalljclSort8SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort8SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort8SortInRecordType=FB
SortalljclSort8SortInRecordLen=<recordLen>
#STEP:SORT8| PGM:SORT| DD:SORTOUT
SortalljclSort8SortOut=CLOUDFRM.JPM.SORT.OUTPUT8
SortalljclSort8SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort8SortOutRecordType=FB
SortalljclSort8SortOutRecordLen=<recordLen>
#STEP:SORT9| PGM:SORT| DD:SORTIN
SortalljclSort9SortIn=CLOUDFRM.JPM.SORT.INPUT9
SortalljclSort9SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort9SortInRecordType=FB
SortalljclSort9SortInRecordLen=<recordLen>
#STEP:SORT9| PGM:SORT| DD:SORTOUT
SortalljclSort9SortOut=CLOUDFRM.JPM.SORT.OUTPUT9
SortalljclSort9SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort9SortOutRecordType=FB
SortalljclSort9SortOutRecordLen=<recordLen>
#STEP:SORT10| PGM:SORT| DD:SORTIN
SortalljclSort10SortIn=CLOUDFRM.JPM.SORT.INPUT10
SortalljclSort10SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort10SortInRecordType=FB
SortalljclSort10SortInRecordLen=<recordLen>
#STEP:SORT10| PGM:SORT| DD:SORTOUT
SortalljclSort10SortOut=CLOUDFRM.JPM.SORT.OUTPUT10
SortalljclSort10SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort10SortOutRecordType=FB
SortalljclSort10SortOutRecordLen=<recordLen>
#STEP:SORT11| PGM:SORT| DD:SORTIN
SortalljclSort11SortIn=CLOUDFRM.JPM.SORT.INPUT11
SortalljclSort11SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort11SortInRecordType=FB
SortalljclSort11SortInRecordLen=<recordLen>
#STEP:SORT11| PGM:SORT| DD:SORTOUT
SortalljclSort11SortOut=CLOUDFRM.JPM.SORT.OUTPUT11
SortalljclSort11SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort11SortOutRecordType=FB
SortalljclSort11SortOutRecordLen=<recordLen>
#STEP:SORT12| PGM:SORT| DD:SORTIN
SortalljclSort12SortIn=CLOUDFRM.JPM.SORT.INPUT12
SortalljclSort12SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort12SortInRecordType=FB
SortalljclSort12SortInRecordLen=<recordLen>
#STEP:SORT12| PGM:SORT| DD:SORTOUT
SortalljclSort12SortOut=CLOUDFRM.JPM.SORT.OUTPUT12
SortalljclSort12SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort12SortOutRecordType=FB
SortalljclSort12SortOutRecordLen=<recordLen>
#STEP:SORT13| PGM:SORT| DD:SORTIN
SortalljclSort13SortIn=CLOUDFRM.JPM.SORT.INPUT13
SortalljclSort13SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort13SortInRecordType=FB
SortalljclSort13SortInRecordLen=<recordLen>
#STEP:SORT13| PGM:SORT| DD:SORTOUT
SortalljclSort13SortOut=CLOUDFRM.JPM.SORT.OUTPUT13
SortalljclSort13SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort13SortOutRecordType=FB
SortalljclSort13SortOutRecordLen=<recordLen>
#STEP:SORT14| PGM:SORT| DD:SORTIN
SortalljclSort14SortIn=CLOUDFRM.JPM.SORT.INPUT
SortalljclSort14SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort14SortInRecordType=FB
SortalljclSort14SortInRecordLen=<recordLen>
#STEP:SORT14| PGM:SORT| DD:SORTOUT
SortalljclSort14SortOut=CLOUDFRM.JPM.SORT.OUTPUT14
SortalljclSort14SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort14SortOutRecordType=FB
SortalljclSort14SortOutRecordLen=<recordLen>
#STEP:SORT15| PGM:SORT| DD:SORTIN
SortalljclSort15SortIn[0]=CLOUDFRM.JPM.SORT.INPUT151
SortalljclSort15SortIn[0].DISP=SHR,KEEP,KEEP
SortalljclSort15SortIn0RecordType=FB
SortalljclSort15SortIn0RecordLen=<recordLen>
#STEP:SORT15| PGM:SORT| DD:SORTIN
SortalljclSort15SortIn[1]=CLOUDFRM.JPM.SORT.INPUT152
SortalljclSort15SortIn[1].DISP=SHR,KEEP,KEEP
SortalljclSort15SortIn1RecordType=FB
SortalljclSort15SortIn1RecordLen=<recordLen>
#STEP:SORT15| PGM:SORT| DD:SORTOUT
SortalljclSort15SortOut=CLOUDFRM.JPM.SORT.OUTPUT15
SortalljclSort15SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort15SortOutRecordType=FB
SortalljclSort15SortOutRecordLen=<recordLen>
#STEP:SORT16| PGM:SORT| DD:SORTIN
SortalljclSort16SortIn[0]=CLOUDFRM.JPM.SORT.INPUT161
SortalljclSort16SortIn[0].DISP=SHR,KEEP,KEEP
SortalljclSort16SortIn0RecordType=FB
SortalljclSort16SortIn0RecordLen=<recordLen>
#STEP:SORT16| PGM:SORT| DD:SORTIN
SortalljclSort16SortIn[1]=CLOUDFRM.JPM.SORT.INPUT162
SortalljclSort16SortIn[1].DISP=SHR,KEEP,KEEP
SortalljclSort16SortIn1RecordType=FB
SortalljclSort16SortIn1RecordLen=<recordLen>
#STEP:SORT16| PGM:SORT| DD:SORTIN
SortalljclSort16SortIn[2]=CLOUDFRM.JPM.SORT.INPUT163
SortalljclSort16SortIn[2].DISP=SHR,KEEP,KEEP
SortalljclSort16SortIn2RecordType=FB
SortalljclSort16SortIn2RecordLen=<recordLen>
#STEP:SORT16| PGM:SORT| DD:SORTOUT
SortalljclSort16SortOut=CLOUDFRM.JPM.SORT.OUTPUT16
SortalljclSort16SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort16SortOutRecordType=FB
SortalljclSort16SortOutRecordLen=<recordLen>
#STEP:SORT18| PGM:SORT| DD:SORTIN
SortalljclSort18SortIn=CLOUDFRM.JPM.SORT.INPUT18
SortalljclSort18SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort18SortInRecordType=FB
SortalljclSort18SortInRecordLen=<recordLen>
#STEP:SORT18| PGM:SORT| DD:SORTOUT
SortalljclSort18SortOut=CLOUDFRM.JPM.SORT.OUTPUT18
SortalljclSort18SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort18SortOutRecordType=FB
SortalljclSort18SortOutRecordLen=<recordLen>
#STEP:SORT19| PGM:SORT| DD:SORTIN
SortalljclSort19SortIn=CLOUDFRM.JPM.SORT.INPUT19
SortalljclSort19SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort19SortInRecordType=FB
SortalljclSort19SortInRecordLen=<recordLen>
#STEP:SORT19| PGM:SORT| DD:SORTOUT
SortalljclSort19SortOut=CLOUDFRM.JPM.SORT.OUTPUT19
SortalljclSort19SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort19SortOutRecordType=FB
SortalljclSort19SortOutRecordLen=<recordLen>
#STEP:SORT20| PGM:SORT| DD:SORTIN
SortalljclSort20SortIn=CLOUDFRM.JPM.SORT.INPUT20
SortalljclSort20SortIn.DISP=SHR,KEEP,KEEP
SortalljclSort20SortInRecordType=FB
SortalljclSort20SortInRecordLen=<recordLen>
#STEP:SORT20| PGM:SORT| DD:SORTOUT
SortalljclSort20SortOut=CLOUDFRM.JPM.SORT.OUTPUT20
SortalljclSort20SortOut.DISP=SHR,KEEP,KEEP
SortalljclSort20SortOutRecordType=FB
SortalljclSort20SortOutRecordLen=<recordLen>
