package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.data.Field;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] EBCDIC_ENCODING = "cp1047".toCharArray();
public static final char[] LITERAL_CLOUDFRM = "CLOUDFRM".toCharArray();
public static final char[] LITERAL_OT = "OT".toCharArray();
public static final char[] LOW_VALUE_1901531989 = Field.fillLowValue(1001);
public static final char[] MODE_READ_ONLY_36242 = "r".toCharArray();
public static final char[] MODE_WRITE_ONLY_36397 = "w".toCharArray();
 
}
