  package com.cloudframe.app.process;
  /* Java code generated by CloudFrame on 2025-04-29 at 08:33. */
  
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.varlen.dto.*;
  import com.cloudframe.app.varlen.dto.RevoExtractRecord;
  import com.cloudframe.app.varlen.dto.Revo3ExtractRecord;
  import com.cloudframe.app.varlen.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("varlen")
  
  public class Varlen extends CommonProcess {
  
  Logger logger = LoggerFactory.getLogger(Varlen.class);
  
  private RevoExtractRecord revoExtractRecord = new RevoExtractRecord() ;
  private Revo3ExtractRecord revo3ExtractRecord = new Revo3ExtractRecord() ;
  private Work work = new Work() ;
  
  
  
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output :  

      * - activeSvcProdCnt               COBOL Name: WS-ACTIVE-SVC-PROD-CNT
      * - displayLen                     COBOL Name: WS-DISPLAY-LEN
      * - activeFeatCnt                  COBOL Name: WS-ACTIVE-FEAT-CNT
      *
      * @throws CFException
      */
      @Override
      public int process() throws Exception {
       initVars();
       try {
       setCodePage("1047");

// *    ----
          // MOVE 0 TO WS-ACTIVE-SVC-PROD-CNT
          work.setActiveSvcProdCnt((short)0);
//  MOVE LENGTH OF REVO3-EXTRACT-RECORD TO WS-DISPLAY-LEN
          work.setDisplayLen(118/* fixed offset*/ + work.getActiveSvcProdCnt()/* depending on*/  * 57/* field Length */ );
//  DISPLAY ' 0  REVO3 REC LEN ' WS-DISPLAY-LEN
          logger.info(" 0  REVO3 REC LEN {}", String.valueOf(work.getDisplayLen())); 
          // MOVE 1 TO WS-ACTIVE-SVC-PROD-CNT
          work.setActiveSvcProdCnt((short)1);
//  MOVE LENGTH OF REVO3-EXTRACT-RECORD TO WS-DISPLAY-LEN
          work.setDisplayLen(118/* fixed offset*/ + work.getActiveSvcProdCnt()/* depending on*/  * 57/* field Length */ );
//  DISPLAY ' 1  REVO3 REC LEN ' WS-DISPLAY-LEN
          logger.info(" 1  REVO3 REC LEN {}", String.valueOf(work.getDisplayLen())); 
          // MOVE 2 TO WS-ACTIVE-SVC-PROD-CNT
          work.setActiveSvcProdCnt((short)2);
//  MOVE LENGTH OF REVO3-EXTRACT-RECORD TO WS-DISPLAY-LEN
          work.setDisplayLen(118/* fixed offset*/ + work.getActiveSvcProdCnt()/* depending on*/  * 57/* field Length */ );
//  DISPLAY ' 2  REVO3 REC LEN ' WS-DISPLAY-LEN
          logger.info(" 2  REVO3 REC LEN {}", String.valueOf(work.getDisplayLen())); 
          // MOVE 10 TO WS-ACTIVE-SVC-PROD-CNT
          work.setActiveSvcProdCnt((short)10);
//  MOVE LENGTH OF REVO3-EXTRACT-RECORD TO WS-DISPLAY-LEN
          work.setDisplayLen(118/* fixed offset*/ + work.getActiveSvcProdCnt()/* depending on*/  * 57/* field Length */ );
//  DISPLAY ' 10 REVO3 REC LEN ' WS-DISPLAY-LEN
          logger.info(" 10 REVO3 REC LEN {}", String.valueOf(work.getDisplayLen())); 
          // MOVE 20 TO WS-ACTIVE-SVC-PROD-CNT
          work.setActiveSvcProdCnt((short)20);
//  MOVE LENGTH OF REVO3-EXTRACT-RECORD TO WS-DISPLAY-LEN
          work.setDisplayLen(118/* fixed offset*/ + work.getActiveSvcProdCnt()/* depending on*/  * 57/* field Length */ );
//  DISPLAY ' 20 REVO3 REC LEN ' WS-DISPLAY-LEN
          logger.info(" 20 REVO3 REC LEN {}", String.valueOf(work.getDisplayLen())); 
          // MOVE 0 TO WS-ACTIVE-FEAT-CNT
          work.setActiveFeatCnt((short)0);
//  MOVE LENGTH OF REVO-EXTRACT-RECORD TO WS-DISPLAY-LEN
          work.setDisplayLen(676/* fixed offset*/ + work.getActiveFeatCnt()/* depending on*/  * 20/* field Length */ );
//  DISPLAY '  0 REVO  REC LEN ' WS-DISPLAY-LEN
          logger.info("  0 REVO  REC LEN {}", String.valueOf(work.getDisplayLen())); 
          // MOVE 10 TO WS-ACTIVE-FEAT-CNT
          work.setActiveFeatCnt((short)10);
//  MOVE LENGTH OF REVO-EXTRACT-RECORD TO WS-DISPLAY-LEN
          work.setDisplayLen(676/* fixed offset*/ + work.getActiveFeatCnt()/* depending on*/  * 20/* field Length */ );
//  DISPLAY ' 10 REVO  REC LEN ' WS-DISPLAY-LEN
          logger.info(" 10 REVO  REC LEN {}", String.valueOf(work.getDisplayLen())); 
          // MOVE 20 TO WS-ACTIVE-FEAT-CNT
          work.setActiveFeatCnt((short)20);
//  MOVE LENGTH OF REVO-EXTRACT-RECORD TO WS-DISPLAY-LEN
          work.setDisplayLen(676/* fixed offset*/ + work.getActiveFeatCnt()/* depending on*/  * 20/* field Length */ );
//  DISPLAY ' 20 REVO  REC LEN ' WS-DISPLAY-LEN
          logger.info(" 20 REVO  REC LEN {}", String.valueOf(work.getDisplayLen())); 

// *    ----
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          this.setProgramEnded(true);
          return getRc();
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
      // end of process method
      }
  
  
      /**
* This method pre-initializes variables consistent with
* what a mainframe program would have done at the start of a program
*/
      @Override
      public void initVars() throws CFException {
      setProgramEnded(false);
          if(!isInitDone()) {
          	this.setRc(0);
          	setInitDone(true);
          }
        CFUtil.resetDecimalAsComma();
       }
  
  
  
  
  
  
  }
