package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] EBCDIC_ENCODING = "cp1047".toCharArray();
public static final char[] LITERAL_ABCDEFGH = "ABCDEFGH".toCharArray();
public static final char[] LITERAL_CLOUDFRM = "CLOUDFRM".toCharArray();
public static final char[] LITERAL_ETACOLER = "ETACOLER".toCharArray();
public static final char[] LITERAL_ETAVONER = "ETAVONER".toCharArray();
public static final char[] LITERAL_HGFEDCBA = "HGFEDCBA".toCharArray();
public static final char[] LITERAL_MRFDUOLC = "MRFDUOLC".toCharArray();
public static final char[] LITERAL_RELOCATE = "RELOCATE".toCharArray();
public static final char[] LITERAL_RENOVATE = "RENOVATE".toCharArray();
 
}
