# Program  : BLKDBLK | DD : SYSIN | RecordFormat : FixedLength | RecordLength : 80
BLKDBLK.Scanner=SYSIN.bin
BLKDBLK.ScannerCharSet=cp1047
BLKDBLK.ScannerCRLFflag=no
# Program BLKDBLK | DD : UMODEASC | RecordFormat : Undefined | RecordLength : 1014
BLKDBLK.ddname.UMODEASC=UmodeFile
BLKDBLK.UmodeFile=UmodeFile
BLKDBLK.UmodeFileCharSet=cp1047
BLKDBLK.UmodeFileCRLFflag=no
# Program BLKDBLK | DD : VBSEBC | RecordFormat : VariableLength | MaxRecordLength : 32752
BLKDBLK.ddname.VBSEBC=VbsFile
BLKDBLK.VbsFile=VbsFile
BLKDBLK.VbsFileCharSet=cp1047
BLKDBLK.VbsFileCRLFflag=no
# 
# End of BLKDBLK
