<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Work" cobol:name="work" cobol:offset="0" cobol:length="7" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="String1" maxOccurs="1"  cobol:name="WS-STRING-1" cobol:offset="0" cobol:length="55" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="55" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="String2" maxOccurs="1"  cobol:name="WS-STRING-2" cobol:offset="0" cobol:length="55" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="55" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HoldString" maxOccurs="1"  cobol:name="WS-HOLD-STRING" cobol:offset="0" cobol:length="55" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="55" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Cnt1" type="xs:int" maxOccurs="1"  cobol:name="WS-CNT1" cobol:offset="0" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="Edit" maxOccurs="1"  cobol:name="WS-EDIT" cobol:offset="2" cobol:length="5" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Parm1" maxOccurs="1"  cobol:name="WS-PARM-1" cobol:offset="7" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Parm2" maxOccurs="1"  cobol:name="WS-PARM-2" cobol:offset="7" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Parm3" maxOccurs="1"  cobol:name="WS-PARM-3" cobol:offset="7" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Parm4" maxOccurs="1"  cobol:name="WS-PARM-4" cobol:offset="7" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Parm5" maxOccurs="1"  cobol:name="WS-PARM-5" cobol:offset="7" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Parm6" maxOccurs="1"  cobol:name="WS-PARM-6" cobol:offset="7" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="P1Cnt" type="xs:int" maxOccurs="1"  cobol:name="WS-P1-CNT" cobol:offset="7" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="P2Cnt" type="xs:int" maxOccurs="1"  cobol:name="WS-P2-CNT" cobol:offset="7" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="P3Cnt" type="xs:int" maxOccurs="1"  cobol:name="WS-P3-CNT" cobol:offset="7" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="P4Cnt" type="xs:int" maxOccurs="1"  cobol:name="WS-P4-CNT" cobol:offset="7" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="P5Cnt" type="xs:int" maxOccurs="1"  cobol:name="WS-P5-CNT" cobol:offset="7" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="P6Cnt" type="xs:int" maxOccurs="1"  cobol:name="WS-P6-CNT" cobol:offset="7" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="DelimRec" maxOccurs="1"  cobol:name="WS-DELIM-REC" cobol:offset="7" cobol:length="1761" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1761" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Len" type="xs:short" maxOccurs="1"  cobol:name="WS-LEN" cobol:offset="7" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="SvcIdNoP1" maxOccurs="1"  cobol:name="WS-SVC-ID-NO-P1" cobol:offset="7" cobol:length="7" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SvcIdNoP2" maxOccurs="1"  cobol:name="WS-SVC-ID-NO-P2" cobol:offset="7" cobol:length="18" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
