<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="DtPage2Ln5b" cobol:name="DT-PAGE2-LN5B" cobol:offset="0" cobol:length="136" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Dt25bCc" maxOccurs="1"  cobol:name="DT2-5B-CC" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln5bFiller1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="1" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln5bFiller2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="4" cobol:length="24" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="24" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln5bFiller3" maxOccurs="1"  cobol:name="FILLER" cobol:offset="28" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt25bRevDbAmt" maxOccurs="1"  cobol:name="DT2-5B-REV-DB-AMT" cobol:offset="48" cobol:length="18" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln5bFiller4" maxOccurs="1"  cobol:name="FILLER" cobol:offset="66" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln5bFiller5" maxOccurs="1"  cobol:name="FILLER" cobol:offset="70" cobol:length="17" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="17" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt25bRevCrAmt" maxOccurs="1"  cobol:name="DT2-5B-REV-CR-AMT" cobol:offset="87" cobol:length="18" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln5bFiller6" maxOccurs="1"  cobol:name="FILLER" cobol:offset="105" cobol:length="31" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="31" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
