<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="DtPage3Ln13" cobol:name="DT-PAGE3-LN13" cobol:offset="0" cobol:length="133" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Dt313Cc" maxOccurs="1"  cobol:name="DT3-13-CC" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatFicnt" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-FICNT" cobol:offset="1" cobol:length="11" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage3Ln13Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="12" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatFiamt" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-FIAMT" cobol:offset="13" cobol:length="16" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="16" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatFiind" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-FIIND" cobol:offset="29" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatFvamt" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-FVAMT" cobol:offset="31" cobol:length="11" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatFvind" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-FVIND" cobol:offset="42" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage3Ln13Filler2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="44" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatNicnt" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-NICNT" cobol:offset="46" cobol:length="11" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatNiamt" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-NIAMT" cobol:offset="57" cobol:length="16" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="16" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatNiind" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-NIIND" cobol:offset="73" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatNvamt" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-NVAMT" cobol:offset="75" cobol:length="11" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatNvind" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-NVIND" cobol:offset="86" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage3Ln13Filler3" maxOccurs="1"  cobol:name="FILLER" cobol:offset="88" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatTicnt" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-TICNT" cobol:offset="90" cobol:length="11" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatTiamt" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-TIAMT" cobol:offset="101" cobol:length="16" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="16" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatTiind" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-TIIND" cobol:offset="117" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatTvamt" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-TVAMT" cobol:offset="119" cobol:length="11" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt313IssvatTvind" maxOccurs="1"  cobol:name="DT3-13-ISSVAT-TVIND" cobol:offset="130" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage3Ln13Filler4" maxOccurs="1"  cobol:name="FILLER" cobol:offset="132" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
