<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="DtPage2Ln9" cobol:name="DT-PAGE2-LN9" cobol:offset="0" cobol:length="133" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Dt29Cc" maxOccurs="1"  cobol:name="DT2-9-CC" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln9Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="1" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln9Filler2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="2" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt29SurchgNbr" maxOccurs="1"  cobol:name="DT2-9-SURCHG-NBR" cobol:offset="28" cobol:length="15" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="15" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln9Filler3" maxOccurs="1"  cobol:name="FILLER" cobol:offset="43" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln9Filler4" maxOccurs="1"  cobol:name="FILLER" cobol:offset="48" cobol:length="15" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="15" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln9Filler5" maxOccurs="1"  cobol:name="FILLER" cobol:offset="63" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln9Filler6" maxOccurs="1"  cobol:name="FILLER" cobol:offset="67" cobol:length="15" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="15" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln9Filler7" maxOccurs="1"  cobol:name="FILLER" cobol:offset="82" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln9Filler8" maxOccurs="1"  cobol:name="FILLER" cobol:offset="87" cobol:length="15" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="15" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DtPage2Ln9Filler9" maxOccurs="1"  cobol:name="FILLER" cobol:offset="102" cobol:length="31" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="31" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
