<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="HdPage1Ln4" cobol:name="HD-PAGE1-LN4" cobol:offset="0" cobol:length="104" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Hd14Cc" maxOccurs="1"  cobol:name="HD1-4-CC" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln4Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="1" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln4Filler2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="2" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln4Filler3" maxOccurs="1"  cobol:name="FILLER" cobol:offset="22" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Hd14InstId" maxOccurs="1"  cobol:name="HD1-4-INST-ID" cobol:offset="23" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln4Filler4" maxOccurs="1"  cobol:name="FILLER" cobol:offset="33" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Hd14InstDesc" maxOccurs="1"  cobol:name="HD1-4-INST-DESC" cobol:offset="34" cobol:length="25" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln4Filler5" maxOccurs="1"  cobol:name="FILLER" cobol:offset="59" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Hd14BinNumber" maxOccurs="1"  cobol:name="HD1-4-BIN-NUMBER" cobol:offset="62" cobol:length="12" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="12" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln4Filler6" maxOccurs="1"  cobol:name="FILLER" cobol:offset="74" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Hd14BinId" maxOccurs="1"  cobol:name="HD1-4-BIN-ID" cobol:offset="75" cobol:length="11" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln4Filler7" maxOccurs="1"  cobol:name="FILLER" cobol:offset="86" cobol:length="18" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
