<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="HdPage1Ln2" cobol:name="HD-PAGE1-LN2" cobol:offset="0" cobol:length="133" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Hd12Cc" maxOccurs="1"  cobol:name="HD1-2-CC" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln2Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="1" cobol:length="49" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="49" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Hd12MceMsg" maxOccurs="1"  cobol:name="HD1-2-MCE-MSG" cobol:offset="50" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Hd12DailyMon" maxOccurs="1"  cobol:name="HD1-2-DAILY-MON" cobol:offset="53" cobol:length="11" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln2Filler2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="64" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln2Filler3" maxOccurs="1"  cobol:name="FILLER" cobol:offset="65" cobol:length="14" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="14" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln2Filler4" maxOccurs="1"  cobol:name="FILLER" cobol:offset="79" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Hd13CntryName" maxOccurs="1"  cobol:name="HD1-3-CNTRY-NAME" cobol:offset="85" cobol:length="9" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Hd13Country" maxOccurs="1"  cobol:name="HD1-3-COUNTRY" cobol:offset="94" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln2Filler5" maxOccurs="1"  cobol:name="FILLER" cobol:offset="97" cobol:length="17" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="17" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Hd1DateMsg" maxOccurs="1"  cobol:name="HD1-DATE-MSG" cobol:offset="114" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Hd12Mm" type="xs:int" maxOccurs="1"  cobol:name="HD1-2-MM" cobol:offset="124" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="HdPage1Ln2Filler6" maxOccurs="1"  cobol:name="FILLER" cobol:offset="126" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Hd12Dd" type="xs:int" maxOccurs="1"  cobol:name="HD1-2-DD" cobol:offset="127" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="HdPage1Ln2Filler7" maxOccurs="1"  cobol:name="FILLER" cobol:offset="129" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Hd12Yy" type="xs:int" maxOccurs="1"  cobol:name="HD1-2-YY" cobol:offset="130" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="HdPage1Ln2Filler8" maxOccurs="1"  cobol:name="FILLER" cobol:offset="132" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
