<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="RedExpon0Group" cobol:name="RED-EXPON-0-GROUP" cobol:offset="0" cobol:length="15" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="RedExpon0" type="xs:long" maxOccurs="1"  cobol:name="RED-EXPON-0" cobol:offset="0" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
    <xs:element name="RedExpon1" maxOccurs="1"  cobol:name="RED-EXPON-1" cobol:offset="0" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RedExpon2" maxOccurs="1"  cobol:name="RED-EXPON-2" cobol:offset="0" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RedExpon3" maxOccurs="1"  cobol:name="RED-EXPON-3" cobol:offset="0" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RedExpon4" maxOccurs="1"  cobol:name="RED-EXPON-4" cobol:offset="0" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RedExpon5" maxOccurs="1"  cobol:name="RED-EXPON-5" cobol:offset="0" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RedExpon6" maxOccurs="1"  cobol:name="RED-EXPON-6" cobol:offset="0" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RedExpon7" maxOccurs="1"  cobol:name="RED-EXPON-7" cobol:offset="0" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RedExpon8" maxOccurs="1"  cobol:name="RED-EXPON-8" cobol:offset="0" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RedExpon9" maxOccurs="1"  cobol:name="RED-EXPON-9" cobol:offset="0" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
