<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Work" cobol:name="work" cobol:offset="0" cobol:length="2430" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="WsaProgramName" maxOccurs="1"  cobol:name="WSA-PROGRAM-NAME" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsaReleaseNbr" maxOccurs="1"  cobol:name="WSA-RELEASE-NBR" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="MciabendAbendCode" type="xs:int" maxOccurs="1"  cobol:name="MCIABEND-ABEND-CODE" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="BlkLine" maxOccurs="1"  cobol:name="BLK-LINE" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ProductionTitle" maxOccurs="1"  cobol:name="PRODUCTION-TITLE" cobol:offset="0" cobol:length="27" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="27" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CertificationTitle" maxOccurs="1"  cobol:name="CERTIFICATION-TITLE" cobol:offset="0" cobol:length="27" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="27" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FastTrckTitle" maxOccurs="1"  cobol:name="FAST-TRCK-TITLE" cobol:offset="0" cobol:length="27" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="27" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CrEnvId" maxOccurs="1"  cobol:name="CR-ENV-ID" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_100M" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 prParameterIdValue VALUE [["        "], ["SWCHPROD"]].
                        88 crParameterIdValue VALUE [["SWCHCERT"]].
                        88 qaParameterIdValue VALUE [["SWCHQUAL"]].
                        88 dvParameterIdValue VALUE [["SWCHDEVL"]].
                        88 reParameterIdValue VALUE [["SWCHREGR"]].
                        88 ftParameterIdValue VALUE [["SWCHFTF "]].
                        88 lcParameterIdValue VALUE [["SWCHLOCL"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="8" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="HdPage1Ln3b" maxOccurs="1"  cobol:name="HD-PAGE1-LN3B" cobol:offset="0" cobol:length="132" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="132" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln7" maxOccurs="1"  cobol:name="HD-PAGE1-LN7" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln8" maxOccurs="1"  cobol:name="HD-PAGE1-LN8" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage1Ln9" maxOccurs="1"  cobol:name="HD-PAGE1-LN9" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DashPage1Ln" maxOccurs="1"  cobol:name="DASH-PAGE1-LN" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage2Ln1" maxOccurs="1"  cobol:name="HD-PAGE2-LN1" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage2Ln2" maxOccurs="1"  cobol:name="HD-PAGE2-LN2" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage2Ln3" maxOccurs="1"  cobol:name="HD-PAGE2-LN3" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage2Ln4" maxOccurs="1"  cobol:name="HD-PAGE2-LN4" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage2Ln5" maxOccurs="1"  cobol:name="HD-PAGE2-LN5" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage2Ln6" maxOccurs="1"  cobol:name="HD-PAGE2-LN6" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage3Ln1" maxOccurs="1"  cobol:name="HD-PAGE3-LN1" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage3Ln1a" maxOccurs="1"  cobol:name="HD-PAGE3-LN1A" cobol:offset="0" cobol:length="132" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="132" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage3Ln2" maxOccurs="1"  cobol:name="HD-PAGE3-LN2" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage3Ln6" maxOccurs="1"  cobol:name="HD-PAGE3-LN6" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage3Ln7" maxOccurs="1"  cobol:name="HD-PAGE3-LN7" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage3Ln8" maxOccurs="1"  cobol:name="HD-PAGE3-LN8" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage3Ln9" maxOccurs="1"  cobol:name="HD-PAGE3-LN9" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage3Ln10" maxOccurs="1"  cobol:name="HD-PAGE3-LN10" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="HdPage3Ln11" maxOccurs="1"  cobol:name="HD-PAGE3-LN11" cobol:offset="0" cobol:length="133" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="133" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt311SamacqNetAmt" maxOccurs="1"  cobol:name="DT3-11-SAMACQ-NET-AMT" cobol:offset="0" cobol:length="18" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt311SamacqInd" maxOccurs="1"  cobol:name="DT3-11-SAMACQ-IND" cobol:offset="0" cobol:length="2" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt311SamacqFeeAmt" maxOccurs="1"  cobol:name="DT3-11-SAMACQ-FEE-AMT" cobol:offset="0" cobol:length="16" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="16" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt311SamacqFeeInd" maxOccurs="1"  cobol:name="DT3-11-SAMACQ-FEE-IND" cobol:offset="0" cobol:length="2" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt311SamissNetAmt" maxOccurs="1"  cobol:name="DT3-11-SAMISS-NET-AMT" cobol:offset="0" cobol:length="18" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt311SamissInd" maxOccurs="1"  cobol:name="DT3-11-SAMISS-IND" cobol:offset="0" cobol:length="2" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt311SamissFeeAmt" maxOccurs="1"  cobol:name="DT3-11-SAMISS-FEE-AMT" cobol:offset="0" cobol:length="16" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="16" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Dt311SamissFeeInd" maxOccurs="1"  cobol:name="DT3-11-SAMISS-FEE-IND" cobol:offset="0" cobol:length="2" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="P2AcqPrint" maxOccurs="1"  cobol:name="P2-ACQ-PRINT" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="P2IssPrint" maxOccurs="1"  cobol:name="P2-ISS-PRINT" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SwRptqEof" maxOccurs="1"  cobol:name="SW-RPTQ-EOF" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 swRptqEofValue VALUE [["Y"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="SwCurrEof" maxOccurs="1"  cobol:name="SW-CURR-EOF" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 swCurrEofValue VALUE [["Y"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="SwApcEof" maxOccurs="1"  cobol:name="SW-APC-EOF" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 swApcEofValue VALUE [["Y"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="ErlyFlagSw" maxOccurs="1"  cobol:name="WS-ERLY-FLAG-SW" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 erlyFlag VALUE [["Y"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
         <xs:element name="Page2AcqFinDbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-FIN-DB-CNT" cobol:offset="0" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqFinDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-FIN-DB-AMT" cobol:offset="9" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqTmpCrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-TMP-CR-CNT" cobol:offset="27" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqTmpDbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-TMP-DB-CNT" cobol:offset="36" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqFinCrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-FIN-CR-CNT" cobol:offset="45" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqFinCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-FIN-CR-AMT" cobol:offset="54" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqAdjDbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-ADJ-DB-CNT" cobol:offset="72" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqAdjDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-ADJ-DB-AMT" cobol:offset="81" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqAdjCrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-ADJ-CR-CNT" cobol:offset="99" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqAdjCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-ADJ-CR-AMT" cobol:offset="108" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqAdj09DbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-ADJ09-DB-CNT" cobol:offset="126" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqAdj09DbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-ADJ09-DB-AMT" cobol:offset="135" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqAdj09CrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-ADJ09-CR-CNT" cobol:offset="153" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqAdj09CrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-ADJ09-CR-AMT" cobol:offset="162" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqA15ApdDbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-A15-APD-DB-CNT" cobol:offset="180" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
         <xs:element name="Page2AcqA15ApdCrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-A15-APD-CR-CNT" cobol:offset="185" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
         <xs:element name="Page2AcqFeeDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-FEE-DB-AMT" cobol:offset="190" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqNsdFeeDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-NSD-FEE-DB-AMT" cobol:offset="208" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page2AcqSdFeeDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-SD-FEE-DB-AMT" cobol:offset="223" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page2AcqFeeCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-FEE-CR-AMT" cobol:offset="238" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqNsdFeeCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-NSD-FEE-CR-AMT" cobol:offset="256" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page2AcqSdFeeCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-SD-FEE-CR-AMT" cobol:offset="271" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page2AcqAtmDbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-ATM-DB-CNT" cobol:offset="286" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqAtmDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-ATM-DB-AMT" cobol:offset="295" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqAtmCrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-ATM-CR-CNT" cobol:offset="313" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqAtmCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-ATM-CR-AMT" cobol:offset="322" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqPosDbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-POS-DB-CNT" cobol:offset="340" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqPosDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-POS-DB-AMT" cobol:offset="349" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqPosCrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-POS-CR-CNT" cobol:offset="367" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqPosCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-POS-CR-AMT" cobol:offset="376" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqAtmDbRevCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-ATM-DB-REV-CNT" cobol:offset="394" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqAtmDbRevAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-ATM-DB-REV-AMT" cobol:offset="403" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqAtmCrRevCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-ATM-CR-REV-CNT" cobol:offset="421" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqAtmCrRevAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-ATM-CR-REV-AMT" cobol:offset="430" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqPosDbRevCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-POS-DB-REV-CNT" cobol:offset="448" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqPosDbRevAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-POS-DB-REV-AMT" cobol:offset="457" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqPosCrRevCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-POS-CR-REV-CNT" cobol:offset="475" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2AcqPosCrRevAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ACQ-POS-CR-REV-AMT" cobol:offset="484" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2AcqSurchgFree" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ACQ-SURCHG-FREE" cobol:offset="502" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssFinDbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-FIN-DB-CNT" cobol:offset="511" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssFinDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-FIN-DB-AMT" cobol:offset="520" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssTmpDbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-TMP-DB-CNT" cobol:offset="538" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssTmpCrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-TMP-CR-CNT" cobol:offset="547" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssFinCrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-FIN-CR-CNT" cobol:offset="556" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssFinCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-FIN-CR-AMT" cobol:offset="565" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssAdjDbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-ADJ-DB-CNT" cobol:offset="583" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssAdjDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-ADJ-DB-AMT" cobol:offset="592" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssAdjCrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-ADJ-CR-CNT" cobol:offset="610" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssAdjCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-ADJ-CR-AMT" cobol:offset="619" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssA15ApdDbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-A15-APD-DB-CNT" cobol:offset="637" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
         <xs:element name="Page2IssA15ApdCrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-A15-APD-CR-CNT" cobol:offset="642" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
         <xs:element name="Page2IssAdj09DbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-ADJ09-DB-CNT" cobol:offset="647" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssAdj09DbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-ADJ09-DB-AMT" cobol:offset="656" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssAdj09CrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-ADJ09-CR-CNT" cobol:offset="674" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssAdj09CrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-ADJ09-CR-AMT" cobol:offset="683" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssFeeDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-FEE-DB-AMT" cobol:offset="701" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page2IssFeeCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-FEE-CR-AMT" cobol:offset="716" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssAtmDbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-ATM-DB-CNT" cobol:offset="734" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssAtmDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-ATM-DB-AMT" cobol:offset="743" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssAtmCrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-ATM-CR-CNT" cobol:offset="761" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssAtmCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-ATM-CR-AMT" cobol:offset="770" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssPosDbCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-POS-DB-CNT" cobol:offset="788" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssPosDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-POS-DB-AMT" cobol:offset="797" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssPosCrCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-POS-CR-CNT" cobol:offset="815" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssPosCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-POS-CR-AMT" cobol:offset="824" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssAtmDbRevCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-ATM-DB-REV-CNT" cobol:offset="842" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssAtmDbRevAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-ATM-DB-REV-AMT" cobol:offset="851" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssAtmCrRevCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-ATM-CR-REV-CNT" cobol:offset="869" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssAtmCrRevAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-ATM-CR-REV-AMT" cobol:offset="878" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssPosDbRevCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-POS-DB-REV-CNT" cobol:offset="896" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssPosDbRevAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-POS-DB-REV-AMT" cobol:offset="905" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssPosCrRevCnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-POS-CR-REV-CNT" cobol:offset="923" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page2IssPosCrRevAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-POS-CR-REV-AMT" cobol:offset="932" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssCcaDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-CCA-DB-AMT" cobol:offset="950" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssCcaCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-CCA-CR-AMT" cobol:offset="968" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssIccrDbAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-ICCR-DB-AMT" cobol:offset="986" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssIccrCrAmt" type="xs:long" maxOccurs="1"  cobol:name="PAGE2-ISS-ICCR-CR-AMT" cobol:offset="1004" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Page2IssSurchgFree" type="xs:int" maxOccurs="1"  cobol:name="PAGE2-ISS-SURCHG-FREE" cobol:offset="1022" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page3AcqVatTotal" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ACQ-VAT-TOTAL" cobol:offset="1031" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="Page3IssVatTotal" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ISS-VAT-TOTAL" cobol:offset="1042" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="Page3AcqVatFicnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE3-ACQ-VAT-FICNT" cobol:offset="1053" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page3AcqVatFiamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ACQ-VAT-FIAMT" cobol:offset="1062" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page3AcqVatFvamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ACQ-VAT-FVAMT" cobol:offset="1077" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="Page3AcqVatNicnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE3-ACQ-VAT-NICNT" cobol:offset="1088" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page3AcqVatNiamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ACQ-VAT-NIAMT" cobol:offset="1097" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page3AcqVatNvamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ACQ-VAT-NVAMT" cobol:offset="1112" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="Page3AcqVatTicnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE3-ACQ-VAT-TICNT" cobol:offset="1123" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page3AcqVatTiamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ACQ-VAT-TIAMT" cobol:offset="1132" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page3AcqVatTvamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ACQ-VAT-TVAMT" cobol:offset="1147" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="Page3IssVatFicnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE3-ISS-VAT-FICNT" cobol:offset="1158" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page3IssVatFiamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ISS-VAT-FIAMT" cobol:offset="1167" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page3IssVatFvamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ISS-VAT-FVAMT" cobol:offset="1182" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="Page3IssVatNicnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE3-ISS-VAT-NICNT" cobol:offset="1193" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page3IssVatNiamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ISS-VAT-NIAMT" cobol:offset="1202" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page3IssVatNvamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ISS-VAT-NVAMT" cobol:offset="1217" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="Page3IssVatTicnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE3-ISS-VAT-TICNT" cobol:offset="1228" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page3IssVatTiamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ISS-VAT-TIAMT" cobol:offset="1237" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page3IssVatTvamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-ISS-VAT-TVAMT" cobol:offset="1252" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="Page3NetVatFicnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE3-NET-VAT-FICNT" cobol:offset="1263" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page3NetVatFiamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-NET-VAT-FIAMT" cobol:offset="1272" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page3NetVatFvamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-NET-VAT-FVAMT" cobol:offset="1287" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="Page3NetVatNicnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE3-NET-VAT-NICNT" cobol:offset="1298" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page3NetVatNiamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-NET-VAT-NIAMT" cobol:offset="1307" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page3NetVatNvamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-NET-VAT-NVAMT" cobol:offset="1322" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="Page3NetVatTicnt" type="xs:int" maxOccurs="1"  cobol:name="PAGE3-NET-VAT-TICNT" cobol:offset="1333" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Page3NetVatTiamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-NET-VAT-TIAMT" cobol:offset="1342" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Page3NetVatTvamt" type="xs:long" maxOccurs="1"  cobol:name="PAGE3-NET-VAT-TVAMT" cobol:offset="1357" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="GrandTotSw" type="xs:int" maxOccurs="1"  cobol:name="WS-GRAND-TOT-SW" cobol:offset="1368" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="Amt" type="xs:long" maxOccurs="1"  cobol:name="WS-AMT" cobol:offset="1369" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="AmtT4" type="xs:long" maxOccurs="1"  cobol:name="WS-AMT-T4" cobol:offset="1387" cobol:length="24" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="AmtT5" type="xs:long" maxOccurs="1"  cobol:name="WS-AMT-T5" cobol:offset="1411" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="AmtCca" type="xs:long" maxOccurs="1"  cobol:name="WS-AMT-CCA" cobol:offset="1429" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="AmtIccr" type="xs:long" maxOccurs="1"  cobol:name="WS-AMT-ICCR" cobol:offset="1447" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="AmtCr" type="xs:long" maxOccurs="1"  cobol:name="WS-AMT-CR" cobol:offset="1465" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="AmtDb" type="xs:long" maxOccurs="1"  cobol:name="WS-AMT-DB" cobol:offset="1483" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="AmtCrFee" type="xs:long" maxOccurs="1"  cobol:name="WS-AMT-CR-FEE" cobol:offset="1501" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="AmtDbFee" type="xs:long" maxOccurs="1"  cobol:name="WS-AMT-DB-FEE" cobol:offset="1519" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="NetAcqDb" type="xs:long" maxOccurs="1"  cobol:name="WS-NET-ACQ-DB" cobol:offset="1537" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="NetAcqCr" type="xs:long" maxOccurs="1"  cobol:name="WS-NET-ACQ-CR" cobol:offset="1555" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="NetIssDb" type="xs:long" maxOccurs="1"  cobol:name="WS-NET-ISS-DB" cobol:offset="1573" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="NetIssCr" type="xs:long" maxOccurs="1"  cobol:name="WS-NET-ISS-CR" cobol:offset="1591" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="NetAchTot" type="xs:long" maxOccurs="1"  cobol:name="WS-NET-ACH-TOT" cobol:offset="1609" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Netp4AcqDb" type="xs:long" maxOccurs="1"  cobol:name="WS-NETP4-ACQ-DB" cobol:offset="1627" cobol:length="22" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Netp4AcqCr" type="xs:long" maxOccurs="1"  cobol:name="WS-NETP4-ACQ-CR" cobol:offset="1649" cobol:length="22" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Netp4AcqTot" type="xs:long" maxOccurs="1"  cobol:name="WS-NETP4-ACQ-TOT" cobol:offset="1671" cobol:length="22" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Netp4IssDb" type="xs:long" maxOccurs="1"  cobol:name="WS-NETP4-ISS-DB" cobol:offset="1693" cobol:length="22" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Netp4IssCr" type="xs:long" maxOccurs="1"  cobol:name="WS-NETP4-ISS-CR" cobol:offset="1715" cobol:length="22" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Netp4IssTot" type="xs:long" maxOccurs="1"  cobol:name="WS-NETP4-ISS-TOT" cobol:offset="1737" cobol:length="22" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Netp4AchTot" type="xs:long" maxOccurs="1"  cobol:name="WS-NETP4-ACH-TOT" cobol:offset="1759" cobol:length="22" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="SavSetlTyp" maxOccurs="1"  cobol:name="WS-SAV-SETL-TYP" cobol:offset="1781" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SavProcDesc" maxOccurs="1"  cobol:name="WS-SAV-PROC-DESC" cobol:offset="1781" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CurProcDesc" maxOccurs="1"  cobol:name="WS-CUR-PROC-DESC" cobol:offset="1781" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SavInstDesc" maxOccurs="1"  cobol:name="WS-SAV-INST-DESC" cobol:offset="1781" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CurInstDesc" maxOccurs="1"  cobol:name="WS-CUR-INST-DESC" cobol:offset="1781" cobol:length="25" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="HldAcqIssId" type="xs:int" maxOccurs="1"  cobol:name="WS-HLD-ACQ-ISS-ID" cobol:offset="1781" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="SavAcqIssId" type="xs:int" maxOccurs="1"  cobol:name="WS-SAV-ACQ-ISS-ID" cobol:offset="1782" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="CurAcqIssId" type="xs:int" maxOccurs="1"  cobol:name="WS-CUR-ACQ-ISS-ID" cobol:offset="1783" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
    <xs:element name="CurrSetlTyp" maxOccurs="1"  cobol:name="WS-CURR-SETL-TYP" cobol:offset="1784" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="SavMbrEndpoint" type="xs:long" maxOccurs="1"  cobol:name="WS-SAV-MBR-ENDPOINT" cobol:offset="1784" cobol:length="7" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
         <xs:element name="CurMbrEndpoint" type="xs:long" maxOccurs="1"  cobol:name="WS-CUR-MBR-ENDPOINT" cobol:offset="1791" cobol:length="7" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
         <xs:element name="SavMbrEntIca" type="xs:long" maxOccurs="1"  cobol:name="WS-SAV-MBR-ENT-ICA" cobol:offset="1798" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M"/>
         <xs:element name="CurMbrEntIca" type="xs:long" maxOccurs="1"  cobol:name="WS-CUR-MBR-ENT-ICA" cobol:offset="1804" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M"/>
         <xs:element name="SavMbrMbrIca" type="xs:long" maxOccurs="1"  cobol:name="WS-SAV-MBR-MBR-ICA" cobol:offset="1810" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M"/>
         <xs:element name="CurMbrMbrIca" type="xs:long" maxOccurs="1"  cobol:name="WS-CUR-MBR-MBR-ICA" cobol:offset="1816" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M"/>
    <xs:element name="SavApcIca" maxOccurs="1"  cobol:name="WS-SAV-APC-ICA" cobol:offset="1822" cobol:length="6" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ApcTotAmount" maxOccurs="1"  cobol:name="WS-APC-TOT-AMOUNT" cobol:offset="1822" cobol:length="17" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="17" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ApcTotCrAmount" maxOccurs="1"  cobol:name="WS-APC-TOT-CR-AMOUNT" cobol:offset="1839" cobol:length="20" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="20" />
                  <xs:fractionDigits value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ApcTotDrAmount" maxOccurs="1"  cobol:name="WS-APC-TOT-DR-AMOUNT" cobol:offset="1859" cobol:length="20" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="20" />
                  <xs:fractionDigits value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FirstRecord" maxOccurs="1"  cobol:name="FIRST-RECORD" cobol:offset="1879" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="NoActLine" maxOccurs="1"  cobol:name="NO-ACT-LINE" cobol:offset="1879" cobol:length="132" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="132" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="NoActivitySw" maxOccurs="1"  cobol:name="NO-ACTIVITY-SW" cobol:offset="1879" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MissingActivitySw" maxOccurs="1"  cobol:name="MISSING-ACTIVITY-SW" cobol:offset="1879" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="ProdNdx" type="xs:int" maxOccurs="1"  cobol:name="PROD-NDX" cobol:offset="1879" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="NdxMax" type="xs:int" maxOccurs="1"  cobol:name="NDX-MAX" cobol:offset="1881" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="Ndx" type="xs:int" maxOccurs="1"  cobol:name="NDX" cobol:offset="1884" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="CurNdx" type="xs:int" maxOccurs="1"  cobol:name="CUR-NDX" cobol:offset="1887" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="ApcInx" type="xs:long" maxOccurs="1"  cobol:name="APC-INX" cobol:offset="1890" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
         <xs:element name="Inx" type="xs:long" maxOccurs="1"  cobol:name="WS-INX" cobol:offset="1895" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
         <xs:element name="WS2" type="xs:long" maxOccurs="1"  cobol:name="WS-2" cobol:offset="1900" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
    <xs:element name="RptType" maxOccurs="1"  cobol:name="WS-RPT-TYPE" cobol:offset="1905" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 rptTypeDaily VALUE [["D"]].
                        88 rptTypeMonthly VALUE [["M"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="SystemTime" maxOccurs="1"  cobol:name="SYSTEM-TIME" cobol:offset="1905" cobol:length="6" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WaPageCtr" type="xs:int" maxOccurs="1"  cobol:name="WA-PAGE-CTR" cobol:offset="1905" cobol:length="4" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
         <xs:element name="WaLineCtr" type="xs:int" maxOccurs="1"  cobol:name="WA-LINE-CTR" cobol:offset="1909" cobol:length="4" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
    <xs:element name="EofTranSw" maxOccurs="1"  cobol:name="EOF-TRAN-SW" cobol:offset="1913" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 eofTran VALUE [["Y"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
         <xs:element name="ImpDec" type="xs:int" maxOccurs="1"  cobol:name="WS-IMP-DEC" cobol:offset="1913" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="ImpDecEp" type="xs:int" maxOccurs="1"  cobol:name="WS-IMP-DEC-EP" cobol:offset="1914" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="ImpAmtf" type="xs:long" maxOccurs="1"  cobol:name="WS-IMP-AMTF" cobol:offset="1915" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="ImpAmte" type="xs:long" maxOccurs="1"  cobol:name="WS-IMP-AMTE" cobol:offset="1926" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="ImpAmtep" type="xs:long" maxOccurs="1"  cobol:name="WS-IMP-AMTEP" cobol:offset="1944" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="ImpAmt" type="xs:long" maxOccurs="1"  cobol:name="WS-IMP-AMT" cobol:offset="1962" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="ImpAmtT4" type="xs:long" maxOccurs="1"  cobol:name="WS-IMP-AMT-T4" cobol:offset="1980" cobol:length="24" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="ImpCnt" type="xs:long" maxOccurs="1"  cobol:name="WS-IMP-CNT" cobol:offset="2004" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="FeeAmtNet" type="xs:long" maxOccurs="1"  cobol:name="WS-FEE-AMT-NET" cobol:offset="2013" cobol:length="17" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P"/>
         <xs:element name="Tot1FeeAmtCr" type="xs:long" maxOccurs="1"  cobol:name="WS-TOT1-FEE-AMT-CR" cobol:offset="2030" cobol:length="17" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P"/>
         <xs:element name="Tot1FeeAmtDb" type="xs:long" maxOccurs="1"  cobol:name="WS-TOT1-FEE-AMT-DB" cobol:offset="2047" cobol:length="17" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P"/>
         <xs:element name="Tot1FeeAmtNet01" type="xs:long" maxOccurs="1"  cobol:name="WS-TOT1-FEE-AMT-NET" cobol:offset="2064" cobol:length="17" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P"/>
         <xs:element name="Tot1FinAmt01" type="xs:long" maxOccurs="1"  cobol:name="WS-TOT1-FIN-AMT" cobol:offset="2081" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Tot1FinNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-TOT1-FIN-NBR" cobol:offset="2099" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Tot1FinNbrDen01" type="xs:long" maxOccurs="1"  cobol:name="WS-TOT1-FIN-NBR-DEN" cobol:offset="2108" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Tot1FinFeeNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-TOT1-FIN-FEE-NBR" cobol:offset="2117" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Tot1PctFeeNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-TOT1-PCT-FEE-NBR" cobol:offset="2126" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Tot1NfinFeeNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-TOT1-NFIN-FEE-NBR" cobol:offset="2135" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Tot1NbilFeeNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-TOT1-NBIL-FEE-NBR" cobol:offset="2144" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Exp1FeeAmtCr" type="xs:long" maxOccurs="1"  cobol:name="WS-EXP1-FEE-AMT-CR" cobol:offset="2153" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Exp1FeeAmtDb" type="xs:long" maxOccurs="1"  cobol:name="WS-EXP1-FEE-AMT-DB" cobol:offset="2168" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Exp1FeeAmtNet01" type="xs:long" maxOccurs="1"  cobol:name="WS-EXP1-FEE-AMT-NET" cobol:offset="2183" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="Exp1FinAmt01" type="xs:long" maxOccurs="1"  cobol:name="WS-EXP1-FIN-AMT" cobol:offset="2198" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Exp1FinNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-EXP1-FIN-NBR" cobol:offset="2216" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Exp1FinNbrDen01" type="xs:long" maxOccurs="1"  cobol:name="WS-EXP1-FIN-NBR-DEN" cobol:offset="2225" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Exp1FinFeeNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-EXP1-FIN-FEE-NBR" cobol:offset="2234" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Exp1PctFeeNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-EXP1-PCT-FEE-NBR" cobol:offset="2243" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Exp1NfinFeeNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-EXP1-NFIN-FEE-NBR" cobol:offset="2252" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Exp1NbilFeeNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-EXP1-NBIL-FEE-NBR" cobol:offset="2261" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Sub1FeeAmtCr" type="xs:long" maxOccurs="1"  cobol:name="WS-SUB1-FEE-AMT-CR" cobol:offset="2270" cobol:length="17" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P"/>
         <xs:element name="Sub1FeeAmtDb" type="xs:long" maxOccurs="1"  cobol:name="WS-SUB1-FEE-AMT-DB" cobol:offset="2287" cobol:length="17" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P"/>
         <xs:element name="Sub1FeeAmtNet01" type="xs:long" maxOccurs="1"  cobol:name="WS-SUB1-FEE-AMT-NET" cobol:offset="2304" cobol:length="17" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P"/>
         <xs:element name="Sub1FinAmt01" type="xs:long" maxOccurs="1"  cobol:name="WS-SUB1-FIN-AMT" cobol:offset="2321" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E"/>
         <xs:element name="Sub1FinNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-SUB1-FIN-NBR" cobol:offset="2339" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Sub1FinNbrDen01" type="xs:long" maxOccurs="1"  cobol:name="WS-SUB1-FIN-NBR-DEN" cobol:offset="2348" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Sub1FinFeeNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-SUB1-FIN-FEE-NBR" cobol:offset="2357" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Sub1PctFeeNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-SUB1-PCT-FEE-NBR" cobol:offset="2366" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Sub1NfinFeeNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-SUB1-NFIN-FEE-NBR" cobol:offset="2375" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="Sub1NbilFeeNbr01" type="xs:long" maxOccurs="1"  cobol:name="WS-SUB1-NBIL-FEE-NBR" cobol:offset="2384" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
    <xs:element name="SaveWsAmtep" maxOccurs="1"  cobol:name="SAVE-WS-AMTEP" cobol:offset="2393" cobol:length="20" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SaveWsAmtdt4" maxOccurs="1"  cobol:name="SAVE-WS-AMTDT4" cobol:offset="2393" cobol:length="24" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="24" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SaveWsAmte" maxOccurs="1"  cobol:name="SAVE-WS-AMTE" cobol:offset="2393" cobol:length="16" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="16" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="SwTranEof" maxOccurs="1"  cobol:name="SW-TRAN-EOF" cobol:offset="2393" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 swTranEofValue VALUE [["Y"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="TranApc" maxOccurs="1"  cobol:name="WS-TRAN-APC" cobol:offset="2393" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 swTranApc VALUE [["Y"]].
                        88 swTranNoApc VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="TranIca" maxOccurs="1"  cobol:name="WS-TRAN-ICA" cobol:offset="2393" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 icaFound VALUE [["Y"]].
                        88 icaNotFound VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
         <xs:element name="MaxDays" type="xs:int" maxOccurs="1"  cobol:name="MAX-DAYS" cobol:offset="2393" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="Message1" maxOccurs="1"  cobol:name="MESSAGE1" cobol:offset="2395" cobol:length="100" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Message2" maxOccurs="1"  cobol:name="MESSAGE2" cobol:offset="2395" cobol:length="100" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Message3" maxOccurs="1"  cobol:name="MESSAGE3" cobol:offset="2395" cobol:length="100" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Msg002NoParmInType" maxOccurs="1"  cobol:name="MSG002-NO-PARM-IN-TYPE" cobol:offset="2395" cobol:length="100" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="McrInCnt" type="xs:long" maxOccurs="1"  cobol:name="MCR-IN-CNT" cobol:offset="2395" cobol:length="7" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
         <xs:element name="McrSkippedCnt" type="xs:long" maxOccurs="1"  cobol:name="MCR-SKIPPED-CNT" cobol:offset="2402" cobol:length="7" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
         <xs:element name="MonthSub" type="xs:int" maxOccurs="1"  cobol:name="MONTH-SUB" cobol:offset="2409" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="X360HeaderCuttime01" type="xs:int" maxOccurs="1"  cobol:name="WS-X360-HEADER-CUTTIME" cobol:offset="2411" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
    <xs:element name="X360SrtAcqIssId01" maxOccurs="1"  cobol:name="WS-X360-SRT-ACQ-ISS-ID" cobol:offset="2415" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="InhProcFlag" maxOccurs="1"  cobol:name="WS-INH-PROC-FLAG" cobol:offset="2415" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MceSw1" maxOccurs="1"  cobol:name="MCE-SW1" cobol:offset="2415" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MceSw2" maxOccurs="1"  cobol:name="MCE-SW2" cobol:offset="2415" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="NetmceTot" type="xs:long" maxOccurs="1"  cobol:name="WS-NETMCE-TOT" cobol:offset="2415" cobol:length="15" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
