<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="X360FIssSurchrgRvPos" cobol:name="X360-F-ISS-SURCHRG-RV-POS" cobol:offset="1180" cobol:length="26" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="X360FIssSurchrgRvCntCrP" type="xs:int" maxOccurs="1"  cobol:name="X360-F-ISS-SURCHRG-RV-CNT-CR-P" cobol:offset="0" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360FIssSurchrgRvCntDbP" type="xs:int" maxOccurs="1"  cobol:name="X360-F-ISS-SURCHRG-RV-CNT-DB-P" cobol:offset="5" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
    <xs:element name="X360FIssSurchrgRvAmtCrP" maxOccurs="1"  cobol:name="X360-F-ISS-SURCHRG-RV-AMT-CR-P" cobol:offset="10" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="X360FIssSurchrgRvAmtDbP" maxOccurs="1"  cobol:name="X360-F-ISS-SURCHRG-RV-AMT-DB-P" cobol:offset="18" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
