<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="X360FMcsAcqSetl" cobol:name="X360-F-MCS-ACQ-SETL" cobol:offset="343" cobol:length="240" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="X360FMcsAcqApprovedCntCr" type="xs:int" maxOccurs="1"  cobol:name="X360-F-MCS-ACQ-APPROVED-CNT-CR" cobol:offset="0" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360FMcsAcqApprovedCntDb" type="xs:int" maxOccurs="1"  cobol:name="X360-F-MCS-ACQ-APPROVED-CNT-DB" cobol:offset="5" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360FMcsAcqDeniedCntCr" type="xs:int" maxOccurs="1"  cobol:name="X360-F-MCS-ACQ-DENIED-CNT-CR" cobol:offset="10" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360FMcsAcqDeniedCntDb" type="xs:int" maxOccurs="1"  cobol:name="X360-F-MCS-ACQ-DENIED-CNT-DB" cobol:offset="15" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360FMcsAcqAmtCr" type="xs:long" maxOccurs="1"  cobol:name="X360-F-MCS-ACQ-AMT-CR" cobol:offset="20" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FMcsAcqAmtDb" type="xs:long" maxOccurs="1"  cobol:name="X360-F-MCS-ACQ-AMT-DB" cobol:offset="28" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FMcsAcqCnvRteBse" type="xs:long" maxOccurs="1"  cobol:name="X360-F-MCS-ACQ-CNV-RTE-BSE" cobol:offset="36" cobol:length="8" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
         <xs:element name="X360FMcsAcqCurrCde" type="xs:int" maxOccurs="1"  cobol:name="X360-F-MCS-ACQ-CURR-CDE" cobol:offset="44" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="X360FMcsAcqCnvRteLoc" type="xs:long" maxOccurs="1"  cobol:name="X360-F-MCS-ACQ-CNV-RTE-LOC" cobol:offset="47" cobol:length="8" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
    <xs:element name="CirrusX360RecordFiller9" maxOccurs="1"  cobol:name="FILLER" cobol:offset="55" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="X360FMcsAcqSetlIca" type="xs:long" maxOccurs="1"  cobol:name="X360-F-MCS-ACQ-SETL-ICA" cobol:offset="56" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M"/>
         <xs:element name="X360FAcqFinIfeeCnt" type="xs:int" maxOccurs="1"  cobol:name="X360-F-ACQ-FIN-IFEE-CNT" cobol:offset="62" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360FAcqNfIfeeCnt" type="xs:int" maxOccurs="1"  cobol:name="X360-F-ACQ-NF-IFEE-CNT" cobol:offset="67" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360FAcqPctIfeeCnt" type="xs:int" maxOccurs="1"  cobol:name="X360-F-ACQ-PCT-IFEE-CNT" cobol:offset="72" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360FAcqNobillIfeeCnt" type="xs:int" maxOccurs="1"  cobol:name="X360-F-ACQ-NOBILL-IFEE-CNT" cobol:offset="77" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360FAcqIfeeAmtCr" type="xs:long" maxOccurs="1"  cobol:name="X360-F-ACQ-IFEE-AMT-CR" cobol:offset="82" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FAcqIfeeAmtDb" type="xs:long" maxOccurs="1"  cobol:name="X360-F-ACQ-IFEE-AMT-DB" cobol:offset="90" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FAcqCmpAmtCr" type="xs:long" maxOccurs="1"  cobol:name="X360-F-ACQ-CMP-AMT-CR" cobol:offset="98" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FAcqCmpAmtDb" type="xs:long" maxOccurs="1"  cobol:name="X360-F-ACQ-CMP-AMT-DB" cobol:offset="106" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FAcqMccrAmtCrNotused" type="xs:long" maxOccurs="1"  cobol:name="X360-F-ACQ-MCCR-AMT-CR-NOTUSED" cobol:offset="114" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FAcqMccrAmtDbNotused" type="xs:long" maxOccurs="1"  cobol:name="X360-F-ACQ-MCCR-AMT-DB-NOTUSED" cobol:offset="122" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FAcqIccrAmtCrNotused" type="xs:long" maxOccurs="1"  cobol:name="X360-F-ACQ-ICCR-AMT-CR-NOTUSED" cobol:offset="130" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FAcqIccrAmtDbNotused" type="xs:long" maxOccurs="1"  cobol:name="X360-F-ACQ-ICCR-AMT-DB-NOTUSED" cobol:offset="138" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FAcqSurchrgCntCr" type="xs:int" maxOccurs="1"  cobol:name="X360-F-ACQ-SURCHRG-CNT-CR" cobol:offset="146" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360FAcqSurchrgCntDb" type="xs:int" maxOccurs="1"  cobol:name="X360-F-ACQ-SURCHRG-CNT-DB" cobol:offset="151" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
    <xs:element name="X360FAcqSurchrgAmtCr" maxOccurs="1"  cobol:name="X360-F-ACQ-SURCHRG-AMT-CR" cobol:offset="156" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="X360FAcqSurchrgAmtDb" maxOccurs="1"  cobol:name="X360-F-ACQ-SURCHRG-AMT-DB" cobol:offset="164" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="X360FBseAcqStlAmtCr" type="xs:long" maxOccurs="1"  cobol:name="X360-F-BSE-ACQ-STL-AMT-CR" cobol:offset="172" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FBseAcqStlAmtDb" type="xs:long" maxOccurs="1"  cobol:name="X360-F-BSE-ACQ-STL-AMT-DB" cobol:offset="180" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
<xs:element name="X360FWorkOfDateFil" maxOccurs="1" cobol:name="X360-F-WORK-OF-DATE-FIL" cobol:offset="188" cobol:length="6" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="X360FCurrentDateFil" maxOccurs="1" cobol:name="X360-F-CURRENT-DATE-FIL" cobol:offset="194" cobol:length="6" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="X360FEccfCntDbFil" type="xs:int" maxOccurs="1"  cobol:name="X360-F-ECCF-CNT-DB-FIL" cobol:offset="200" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M"/>
         <xs:element name="X360FEccfAmtDbFil" type="xs:long" maxOccurs="1"  cobol:name="X360-F-ECCF-AMT-DB-FIL" cobol:offset="206" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="X360FEccfCntCrFil" type="xs:int" maxOccurs="1"  cobol:name="X360-F-ECCF-CNT-CR-FIL" cobol:offset="217" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M"/>
         <xs:element name="X360FEccfAmtCrFil" type="xs:long" maxOccurs="1"  cobol:name="X360-F-ECCF-AMT-CR-FIL" cobol:offset="223" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="X360FaVatAcqFinCnt" type="xs:int" maxOccurs="1"  cobol:name="X360-FA-VAT-ACQ-FIN-CNT" cobol:offset="234" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
    <xs:element name="CirrusX360RecordFiller10" maxOccurs="1"  cobol:name="FILLER" cobol:offset="239" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
