<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="X360ExtPrecisionInfo" cobol:name="X360-EXT-PRECISION-INFO" cobol:offset="1082" cobol:length="62" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="X360FaAiEpImpDec" type="xs:int" maxOccurs="1"  cobol:name="X360-FA-AI-EP-IMP-DEC" cobol:offset="0" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="X360FaAiEpBaseImpDec" type="xs:int" maxOccurs="1"  cobol:name="X360-FA-AI-EP-BASE-IMP-DEC" cobol:offset="1" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="X360FPurchInterEp" type="xs:long" maxOccurs="1"  cobol:name="X360-F-PURCH-INTER-EP" cobol:offset="2" cobol:length="14" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100T"/>
    <xs:element name="X360FPurchInterIndEp" maxOccurs="1"  cobol:name="X360-F-PURCH-INTER-IND-EP" cobol:offset="16" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="X360FCashbkInterEp" type="xs:long" maxOccurs="1"  cobol:name="X360-F-CASHBK-INTER-EP" cobol:offset="17" cobol:length="14" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100T"/>
    <xs:element name="X360FCashbkInterIndEp" maxOccurs="1"  cobol:name="X360-F-CASHBK-INTER-IND-EP" cobol:offset="31" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="X360APurchInterEp" type="xs:long" maxOccurs="1"  cobol:name="X360-A-PURCH-INTER-EP" cobol:offset="32" cobol:length="14" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100T"/>
    <xs:element name="X360APurchInterIndEp" maxOccurs="1"  cobol:name="X360-A-PURCH-INTER-IND-EP" cobol:offset="46" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="X360ACashbkInterEp" type="xs:long" maxOccurs="1"  cobol:name="X360-A-CASHBK-INTER-EP" cobol:offset="47" cobol:length="14" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100T"/>
    <xs:element name="X360ACashbkInterIndEp" maxOccurs="1"  cobol:name="X360-A-CASHBK-INTER-IND-EP" cobol:offset="61" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
