<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="X360AMcsIssSetl" cobol:name="X360-A-MCS-ISS-SETL" cobol:offset="731" cobol:length="269" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="X360AMcsIssApprovedCntCr" type="xs:int" maxOccurs="1"  cobol:name="X360-A-MCS-ISS-APPROVED-CNT-CR" cobol:offset="0" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360AMcsIssApprovedCntDb" type="xs:int" maxOccurs="1"  cobol:name="X360-A-MCS-ISS-APPROVED-CNT-DB" cobol:offset="5" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360AMcsIssDeniedCntCr" type="xs:int" maxOccurs="1"  cobol:name="X360-A-MCS-ISS-DENIED-CNT-CR" cobol:offset="10" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360AMcsIssDeniedCntDb" type="xs:int" maxOccurs="1"  cobol:name="X360-A-MCS-ISS-DENIED-CNT-DB" cobol:offset="15" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360AMcsIssAmtCr" type="xs:long" maxOccurs="1"  cobol:name="X360-A-MCS-ISS-AMT-CR" cobol:offset="20" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AMcsIssAmtDb" type="xs:long" maxOccurs="1"  cobol:name="X360-A-MCS-ISS-AMT-DB" cobol:offset="28" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AMcsIssCnvRteBse" type="xs:long" maxOccurs="1"  cobol:name="X360-A-MCS-ISS-CNV-RTE-BSE" cobol:offset="36" cobol:length="8" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
         <xs:element name="X360AMcsIssCurrCde" type="xs:int" maxOccurs="1"  cobol:name="X360-A-MCS-ISS-CURR-CDE" cobol:offset="44" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="X360AMcsIssCnvRteLoc" type="xs:long" maxOccurs="1"  cobol:name="X360-A-MCS-ISS-CNV-RTE-LOC" cobol:offset="47" cobol:length="8" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
    <xs:element name="CirrusX360RecordFiller14" maxOccurs="1"  cobol:name="FILLER" cobol:offset="55" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="X360AMcsIssSetlIca" type="xs:long" maxOccurs="1"  cobol:name="X360-A-MCS-ISS-SETL-ICA" cobol:offset="56" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M"/>
         <xs:element name="X360AIssFinIfeeCnt" type="xs:int" maxOccurs="1"  cobol:name="X360-A-ISS-FIN-IFEE-CNT" cobol:offset="62" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360AIssNfIfeeCnt" type="xs:int" maxOccurs="1"  cobol:name="X360-A-ISS-NF-IFEE-CNT" cobol:offset="67" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360AIssPctIfeeCnt" type="xs:int" maxOccurs="1"  cobol:name="X360-A-ISS-PCT-IFEE-CNT" cobol:offset="72" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360AIssNobillIfeeCnt" type="xs:int" maxOccurs="1"  cobol:name="X360-A-ISS-NOBILL-IFEE-CNT" cobol:offset="77" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360AIssIfeeAmtCr" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISS-IFEE-AMT-CR" cobol:offset="82" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssIfeeAmtDb" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISS-IFEE-AMT-DB" cobol:offset="90" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssOrigAmtCr" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISS-ORIG-AMT-CR" cobol:offset="98" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssOrigAmtDb" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISS-ORIG-AMT-DB" cobol:offset="106" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssNewAmtCr" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISS-NEW-AMT-CR" cobol:offset="114" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssNewAmtDb" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISS-NEW-AMT-DB" cobol:offset="122" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssAdjAmtCr" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISS-ADJ-AMT-CR" cobol:offset="130" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssAdjAmtDb" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISS-ADJ-AMT-DB" cobol:offset="138" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssbMccrAmtCr" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISSB-MCCR-AMT-CR" cobol:offset="146" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssbMccrAmtDb" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISSB-MCCR-AMT-DB" cobol:offset="154" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssbIccrAmtCr" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISSB-ICCR-AMT-CR" cobol:offset="162" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssbIccrAmtDb" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISSB-ICCR-AMT-DB" cobol:offset="170" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssA09ApprovedCntCr" type="xs:int" maxOccurs="1"  cobol:name="X360-A-ISS-A09-APPROVED-CNT-CR" cobol:offset="178" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360AIssA09ApprovedCntDb" type="xs:int" maxOccurs="1"  cobol:name="X360-A-ISS-A09-APPROVED-CNT-DB" cobol:offset="183" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360AIssA09ApprovedAmtCr" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISS-A09-APPROVED-AMT-CR" cobol:offset="188" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssA09ApprovedAmtDb" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISS-A09-APPROVED-AMT-DB" cobol:offset="196" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssBaseSetlAmtCr" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISS-BASE-SETL-AMT-CR" cobol:offset="204" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssBaseSetlAmtDb" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISS-BASE-SETL-AMT-DB" cobol:offset="212" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssbMccrA09Cr" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISSB-MCCR-A09-CR" cobol:offset="220" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360AIssbMccrA09Db" type="xs:long" maxOccurs="1"  cobol:name="X360-A-ISSB-MCCR-A09-DB" cobol:offset="228" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FaVatIssNfCnt" type="xs:int" maxOccurs="1"  cobol:name="X360-FA-VAT-ISS-NF-CNT" cobol:offset="236" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="X360FaVatIssFinAmt" type="xs:long" maxOccurs="1"  cobol:name="X360-FA-VAT-ISS-FIN-AMT" cobol:offset="241" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FaVatIssNfAmt" type="xs:long" maxOccurs="1"  cobol:name="X360-FA-VAT-ISS-NF-AMT" cobol:offset="249" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="X360FaVatIssFinVat" type="xs:long" maxOccurs="1"  cobol:name="X360-FA-VAT-ISS-FIN-VAT" cobol:offset="257" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="X360FaVatIssNfVat" type="xs:long" maxOccurs="1"  cobol:name="X360-FA-VAT-ISS-NF-VAT" cobol:offset="263" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
