<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="X360Financials" cobol:name="X360-FINANCIALS" cobol:offset="219" cobol:length="364" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="X360FSurchrgFields" maxOccurs="1" cobol:name="X360-F-SURCHRG-FIELDS" cobol:offset="0" cobol:length="5" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="X360FMcsMdsBase" maxOccurs="1" cobol:name="X360-F-MCS-MDS-BASE" cobol:offset="5" cobol:length="119" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="X360FMcsAcqSetl" maxOccurs="1" cobol:name="X360-F-MCS-ACQ-SETL" cobol:offset="124" cobol:length="240" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="X360FMcsIssSetl" maxOccurs="1" cobol:name="X360-F-MCS-ISS-SETL" cobol:offset="124" cobol:length="240" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
