#
#STEP:STEP01| PGM:IDCAMS| DD:INDD1
STEP01.IDCAMS.Indd1=CLOUDFRM.IDCAMS.USB6QSAM.F1
STEP01.IDCAMS.Indd1.DISP=OLD,KEEP,KEEP
STEP01.IDCAMS.Indd1.RecordType=FB
STEP01.IDCAMS.Indd1.RecordLen=80
#
#
#STEP:STEP01| PGM:IDCAMS| DD:OUTDD1
STEP01.IDCAMS.Outdd1=CLOUDFRM.IDCAMS.USB6QSAM.OUTPUT.F1
STEP01.IDCAMS.Outdd1.DISP=OLD,KEEP,KEEP
STEP01.IDCAMS.Outdd1.RecordType=FB
STEP01.IDCAMS.Outdd1.RecordLen=80
#
#
#STEP:STEP01| PGM:IDCAMS| DD:INDD2
STEP01.IDCAMS.Indd2=CLOUDFRM.IDCAMS.USB6QSAM.F2
STEP01.IDCAMS.Indd2.DISP=OLD,KEEP,KEEP
STEP01.IDCAMS.Indd2.RecordType=FB
STEP01.IDCAMS.Indd2.RecordLen=80
#
#
#STEP:STEP01| PGM:IDCAMS| DD:OUTDD2
STEP01.IDCAMS.Outdd2=CLOUDFRM.IDCAMS.USB6QSAM.OUTPUT.F2
STEP01.IDCAMS.Outdd2.DISP=OLD,KEEP,KEEP
STEP01.IDCAMS.Outdd2.RecordType=FB
STEP01.IDCAMS.Outdd2.RecordLen=80
#
#
#STEP:STEP01| PGM:IDCAMS| DD:INDD3
STEP01.IDCAMS.Indd3=CLOUDFRM.IDCAMS.USB6QSAM.F3
STEP01.IDCAMS.Indd3.DISP=OLD,KEEP,KEEP
STEP01.IDCAMS.Indd3.RecordType=FB
STEP01.IDCAMS.Indd3.RecordLen=80
#
#
#STEP:STEP01| PGM:IDCAMS| DD:OUTDD3
STEP01.IDCAMS.Outdd3=CLOUDFRM.IDCAMS.USB6QSAM.OUTPUT.F3
STEP01.IDCAMS.Outdd3.DISP=OLD,KEEP,KEEP
STEP01.IDCAMS.Outdd3.RecordType=FB
STEP01.IDCAMS.Outdd3.RecordLen=80
#
