#STEP:STEP0500| PGM:SORT| DD:SORTJNF1
Step500Step0500SortIn[0]=FILE1.DTLFILE.MOCK
Step500Step0500SortIn[0].DISP=SHR,KEEP,KEEP
Step500Step0500SortIn0RecordType=FB
Step500Step0500SortIn0RecordLen=300
#STEP:STEP0500| PGM:SORT| DD:SORTJNF2
Step500Step0500SortIn[1]=FILE2.SECFILE.MOCK
Step500Step0500SortIn[1].DISP=SHR,KEEP,KEEP
Step500Step0500SortIn1RecordType=FB
Step500Step0500SortIn1RecordLen=300
#STEP:STEP0500| PGM:SORT| DD:BOTH
Step500Step0500SortOut[0]=FILE1.DTLFILE.MOCK.OUTPUT
Step500Step0500SortOut[0].DISP=NEW,CATLG,DELETE
Step500Step0500SortOut0RecordType=FB
Step500Step0500SortOut0RecordLen=80
#STEP:STEP0500| PGM:SORT| DD:F1ONLY
Step500Step0500SortOut[1]=FILE2.SECFILE.MOCK.OUTPUT
Step500Step0500SortOut[1].DISP=NEW,CATLG,DELETE
Step500Step0500SortOut1RecordType=FB
Step500Step0500SortOut1RecordLen=80
