#STEP:PRINT01| PGM:IDCAMS| DD:INPUT
PRINT01.IDCAMS.Input=CLOUDFRM.IDCAMS.PRINT.FB.FILE1
PRINT01.IDCAMS.Input.DISP=SHR,KEEP,KEEP
PRINT01.IDCAMS.Input.RecordType=FB
PRINT01.IDCAMS.Input.RecordLen=80
#
#STEP:PRINT01| PGM:IDCAMS| DD:SYSPRINT
PRINT01.IDCAMS.Sysprint=PRINT01.IDCAMS.SYSPRINT.SYSOUT
#
