#STEP:PRINT01| PGM:IDCAMS| DD:INPUT
PRINT01.IDCAMS.Input=CLOUDFRM.IDCAMS.PRINT.VB.FILE2
PRINT01.IDCAMS.Input.DISP=SHR,KEEP,KEEP
PRINT01.IDCAMS.Input.RecordType=VBS
PRINT01.IDCAMS.Input.RecordLen=32760
#
#STEP:PRINT01| PGM:IDCAMS| DD:SYSPRINT
PRINT01.IDCAMS.Sysprint=PRINT01.IDCAMS.SYSPRINT.SYSOUT
#
