<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="GeneralWorkArea" cobol:name="GENERAL-WORK-AREA" cobol:offset="0" cobol:length="8192" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="GeneralWorkId" maxOccurs="1"  cobol:name="GENERAL-WORK-ID" cobol:offset="0" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="GeneralWorkDate" maxOccurs="1"  cobol:name="GENERAL-WORK-DATE" cobol:offset="3" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="GeneralWorkTime" maxOccurs="1"  cobol:name="GENERAL-WORK-TIME" cobol:offset="9" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="GeneralWorkClass" maxOccurs="1"  cobol:name="GENERAL-WORK-CLASS" cobol:offset="15" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="GeneralWorkRest" maxOccurs="1"  cobol:name="GENERAL-WORK-REST" cobol:offset="16" cobol:length="8176" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8176" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
