<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="RpC7Heading4" cobol:name="RP-C7-HEADING-4" cobol:offset="0" cobol:length="60" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="RpC7Heading4Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RpC7Heading4Filler2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="1" cobol:length="24" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="24" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RpC7H4MipId" maxOccurs="1"  cobol:name="RP-C7-H4-MIP-ID" cobol:offset="25" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RpC7Heading4Filler3" maxOccurs="1"  cobol:name="FILLER" cobol:offset="28" cobol:length="24" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="24" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RpC7H4DtStamp" maxOccurs="1"  cobol:name="RP-C7-H4-DT-STAMP" cobol:offset="52" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
