<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Sf503BdBulkDataTranLog" cobol:name="SF503-BD-BULK-DATA-TRAN-LOG" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Sf503BdBulkId" maxOccurs="1"  cobol:name="SF503-BD-BULK-ID" cobol:offset="1" cobol:length="14" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="14" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sf503BdMipId" maxOccurs="1"  cobol:name="SF503-BD-MIP-ID" cobol:offset="15" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sf503BdPathId" maxOccurs="1"  cobol:name="SF503-BD-PATH-ID" cobol:offset="18" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sf503BdStatus" maxOccurs="1"  cobol:name="SF503-BD-STATUS" cobol:offset="19" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sf503BdErrorCode" maxOccurs="1"  cobol:name="SF503-BD-ERROR-CODE" cobol:offset="20" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sf503BdJulianDay" maxOccurs="1"  cobol:name="SF503-BD-JULIAN-DAY" cobol:offset="21" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sf503BdTime" maxOccurs="1"  cobol:name="SF503-BD-TIME" cobol:offset="24" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Sf503BdNbr1kSpoolRcds" type="xs:long" maxOccurs="1"  cobol:name="SF503-BD-NBR-1K-SPOOL-RCDS" cobol:offset="30" cobol:length="4" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Sf503BdNbrBytesTrans" type="xs:long" maxOccurs="1"  cobol:name="SF503-BD-NBR-BYTES-TRANS" cobol:offset="34" cobol:length="4" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Sf503BdNbrBlocksTrans" type="xs:long" maxOccurs="1"  cobol:name="SF503-BD-NBR-BLOCKS-TRANS" cobol:offset="38" cobol:length="4" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
