<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Sf503MpMipProfileLog" cobol:name="SF503-MP-MIP-PROFILE-LOG" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Sf503MpLogTime" maxOccurs="1"  cobol:name="SF503-MP-LOG-TIME" cobol:offset="2" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sf503MpLogDate" maxOccurs="1"  cobol:name="SF503-MP-LOG-DATE" cobol:offset="8" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="Sf503MpMipId" maxOccurs="1" cobol:name="SF503-MP-MIP-ID" cobol:offset="14" cobol:length="3" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="Sf503MpIssFloorLim2Retail" type="xs:int" maxOccurs="1"  cobol:name="SF503-MP-ISS-FLOOR-LIM2-RETAIL" cobol:offset="17" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Sf503MpIssFloorLim2Travel" type="xs:int" maxOccurs="1"  cobol:name="SF503-MP-ISS-FLOOR-LIM2-TRAVEL" cobol:offset="19" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Sf503MpIssFloorLim2Cash" type="xs:int" maxOccurs="1"  cobol:name="SF503-MP-ISS-FLOOR-LIM2-CASH" cobol:offset="21" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Sf503MpPosRetailLimit" type="xs:int" maxOccurs="1"  cobol:name="SF503-MP-POS-RETAIL-LIMIT" cobol:offset="23" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Sf503MpPosTravelLimit" type="xs:int" maxOccurs="1"  cobol:name="SF503-MP-POS-TRAVEL-LIMIT" cobol:offset="25" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Sf503MpPosCashLimit" type="xs:int" maxOccurs="1"  cobol:name="SF503-MP-POS-CASH-LIMIT" cobol:offset="27" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Sf503MpXCodeLimit" type="xs:int" maxOccurs="1"  cobol:name="SF503-MP-X-CODE-LIMIT" cobol:offset="29" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="Sf503MpRclFileInd" maxOccurs="1"  cobol:name="SF503-MP-RCL-FILE-IND" cobol:offset="31" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sf503MpNegFileAvailInd" maxOccurs="1"  cobol:name="SF503-MP-NEG-FILE-AVAIL-IND" cobol:offset="32" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sf503MpMbrDelayFileInd" maxOccurs="1"  cobol:name="SF503-MP-MBR-DELAY-FILE-IND" cobol:offset="33" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sf503MpLocalNegFileInd" maxOccurs="1"  cobol:name="SF503-MP-LOCAL-NEG-FILE-IND" cobol:offset="34" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Sf503MpIpqTimes" type="xs:int" maxOccurs="20"  cobol:name="SF503-MP-IPQ-TIMES" cobol:offset="35" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
