<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Sf503IsoJDataRedefined" cobol:name="SF503-ISO-J-DATA-REDEFINED" cobol:offset="75" cobol:length="32677" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Sf503J3JData" maxOccurs="1"  cobol:name="SF503-J3-J-DATA" cobol:offset="27" cobol:length="32650" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="32650" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
