<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Sf50301" cobol:name="SF50301" cobol:offset="0" cobol:length="32752" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="Sf503SortFields" maxOccurs="1" cobol:name="SF503-SORT-FIELDS" cobol:offset="0" cobol:length="15" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Sf503LogRecord" maxOccurs="1"  cobol:name="SF503-LOG-RECORD" cobol:offset="15" cobol:length="32737" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="32737" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="Sf503SeStatAndErrorLog" maxOccurs="1" cobol:name="SF503-SE-STAT-AND-ERROR-LOG" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503BdBulkDataTranLog" maxOccurs="1" cobol:name="SF503-BD-BULK-DATA-TRAN-LOG" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503Bd32BulkDataTranLog" maxOccurs="1" cobol:name="SF503-BD32-BULK-DATA-TRAN-LOG" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503ImImageLogRecord" maxOccurs="1" cobol:name="SF503-IM-IMAGE-LOG-RECORD" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503OpOperatorTranLog" maxOccurs="1" cobol:name="SF503-OP-OPERATOR-TRAN-LOG" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503BanknetReconTranLog" maxOccurs="1" cobol:name="SF503-BANKNET-RECON-TRAN-LOG" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503MpMipProfileLog" maxOccurs="1" cobol:name="SF503-MP-MIP-PROFILE-LOG" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503PsPosTranLog" maxOccurs="1" cobol:name="SF503-PS-POS-TRAN-LOG" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503TypeIiTranLog" maxOccurs="1" cobol:name="SF503-TYPE-II-TRAN-LOG" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503RemoteConsoleLog" maxOccurs="1" cobol:name="SF503-REMOTE-CONSOLE-LOG" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503X92ActivityLog" maxOccurs="1" cobol:name="SF503-X92-ACTIVITY-LOG" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503EdcLogArea" maxOccurs="1" cobol:name="SF503-EDC-LOG-AREA" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503ChkLogArea" maxOccurs="1" cobol:name="SF503-CHK-LOG-AREA" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503AvsLogArea" maxOccurs="1" cobol:name="SF503-AVS-LOG-AREA" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503IsoRecord" maxOccurs="1" cobol:name="SF503-ISO-RECORD" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sf503IsoJRecord" maxOccurs="1" cobol:name="SF503-ISO-J-RECORD" cobol:offset="15" cobol:length="32737" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
