<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Head3354" cobol:name="354-HEAD-3" cobol:offset="0" cobol:length="130" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Head3ReportId354" maxOccurs="1"  cobol:name="354-HEAD3-REPORT-ID" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Head3CarCon354" maxOccurs="1"  cobol:name="354-HEAD3-CAR-CON" cobol:offset="1" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Head3354Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="2" cobol:length="11" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Head3354Filler2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="13" cobol:length="99" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="99" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Head3354Filler3" maxOccurs="1"  cobol:name="FILLER" cobol:offset="112" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Head3Page354" maxOccurs="1"  cobol:name="354-HEAD3-PAGE" cobol:offset="118" cobol:length="3" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Head3354Filler4" maxOccurs="1"  cobol:name="FILLER" cobol:offset="121" cobol:length="9" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
