<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="WorkCompTwoGroup808" cobol:name="808-WORK-COMP-TWO-GROUP" cobol:offset="0" cobol:length="2" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="WorkCompTwo808" type="xs:int" maxOccurs="1"  cobol:name="808-WORK-COMP-TWO" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
<xs:element name="WorkCompTwo808Redefined" maxOccurs="1" cobol:name="808-WORK-COMP-TWO-REDEFINED" cobol:offset="0" cobol:length="2" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
