<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Misc" cobol:name="WS-MISC" cobol:offset="0" cobol:length="40" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Timestamp" maxOccurs="1"  cobol:name="WS-TIMESTAMP" cobol:offset="0" cobol:length="32" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="32" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="MaxRows" type="xs:int" maxOccurs="1"  cobol:name="WS-MAX-ROWS" cobol:offset="36" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
