<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip98152RecordPart2" cobol:name="IP98152-RECORD-PART-2" cobol:offset="255" cobol:length="495" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip98152ClrFxDate" type="xs:long" maxOccurs="1"  cobol:name="IP98152-CLR-FX-DATE" cobol:offset="38" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
         <xs:element name="Ip98152ClrTxnAmt" type="xs:long" maxOccurs="1"  cobol:name="IP98152-CLR-TXN-AMT" cobol:offset="123" cobol:length="7" cobol:datatype="Packed-Dec" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T"/>
    <xs:element name="Ip98152ClrTxnCurrCd" maxOccurs="1"  cobol:name="IP98152-CLR-TXN-CURR-CD" cobol:offset="130" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="Ip98152ClrSetlInfo" maxOccurs="2" cobol:name="IP98152-CLR-SETL-INFO" cobol:offset="320" cobol:length="51" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Ip98152FundProdId" maxOccurs="1"  cobol:name="IP98152-FUND-PROD-ID" cobol:offset="462" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip98152FundAcctNum" maxOccurs="1"  cobol:name="IP98152-FUND-ACCT-NUM" cobol:offset="465" cobol:length="19" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="19" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip98152ActualMcc" maxOccurs="1"  cobol:name="IP98152-ACTUAL-MCC" cobol:offset="484" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip98152FundProdType" maxOccurs="1"  cobol:name="IP98152-FUND-PROD-TYPE" cobol:offset="488" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
