#STEP:STEP001| PGM:ICEGENER| DD:SYSUT1
STEP001.ICEGENER.Sysut1=DUMMY
#
#STEP:STEP001| PGM:ICEGENER| DD:SYSUT2
STEP001.ICEGENER.Sysut2=CLOUDFRM.SF.CSMIP1.A.BKUP.FCOPY(+1)
STEP001.ICEGENER.Sysut2.DISP=NEW,CATLG,DELETE
STEP001.ICEGENER.Sysut2.RecordType=VB
STEP001.ICEGENER.Sysut2.RecordLen=8004
#
#STEP:STEP001| PGM:ICEGENER| DD:SYSUT3
STEP001.ICEGENER.Sysut3=CLOUDFRM.SF.CSMIP2.A.BKUP.FCOPY(+1)
STEP001.ICEGENER.Sysut3.DISP=NEW,CATLG,DELETE
STEP001.ICEGENER.Sysut3.RecordType=VB
STEP001.ICEGENER.Sysut3.RecordLen=8004
#
#STEP:STEP001| PGM:ICEGENER| DD:SYSUT4
STEP001.ICEGENER.Sysut4=CLOUDFRM.SF.CSMIP3.A.BKUP.FCOPY(+1)
STEP001.ICEGENER.Sysut4.DISP=NEW,CATLG,DELETE
STEP001.ICEGENER.Sysut4.RecordType=VB
STEP001.ICEGENER.Sysut4.RecordLen=8004
#
#STEP:STEP001| PGM:ICEGENER| DD:SYSUT5
STEP001.ICEGENER.Sysut5=CLOUDFRM.SF.CSMIP4.A.BKUP.FCOPY(+1)
STEP001.ICEGENER.Sysut5.DISP=NEW,CATLG,DELETE
STEP001.ICEGENER.Sysut5.RecordType=VB
STEP001.ICEGENER.Sysut5.RecordLen=8004
#
