  package com.cloudframe.app.process;
  /* Java code generated by CloudFrame on 2025-04-29 at 08:35. */
  
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import org.springframework.web.bind.annotation.RequestParam;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.data.Field;
  import com.cloudframe.app.search0.dto.*;
  import com.cloudframe.app.search0.dto.FirstNumberGroup;
  import com.cloudframe.app.search0.dto.SecondNumberGroup;
  import com.cloudframe.app.search0.dto.ResultNumberGroup;
  import com.cloudframe.app.search0.dto.WtFields;
  import com.cloudframe.app.search0.dto.Summary;
  import com.cloudframe.app.search0.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("search0")
  
  public class Search0 extends CommonProcess {
  
  Logger logger = LoggerFactory.getLogger(Search0.class);
  
  private FirstNumberGroup firstNumberGroup = new FirstNumberGroup() ;
  private SecondNumberGroup secondNumberGroup = new SecondNumberGroup() ;
  private ResultNumberGroup resultNumberGroup = new ResultNumberGroup() ;
  private WtFields wtFields = new WtFields() ;
  private Summary summary = new Summary() ;
  private Work work = new Work() ;
  
  
  
  
  
  
  int summarySubldgIndex;
  int wtCodeCtrlIndex;
  
  
  
      public int setParameter(String firstNumberGroup,String secondNumberGroup,String resultNumberGroup) throws Exception {
      		if(firstNumberGroup != null)
      		    this.firstNumberGroup.setString(com.cloudframe.app.data.Field.getParm(firstNumberGroup),new String(CONSTANTS.EBCDIC_ENCODING));
      		if(secondNumberGroup != null)
      		    this.secondNumberGroup.setString(com.cloudframe.app.data.Field.getParm(secondNumberGroup),new String(CONSTANTS.EBCDIC_ENCODING));
      		if(resultNumberGroup != null)
      		    this.resultNumberGroup.setString(com.cloudframe.app.data.Field.getParm(resultNumberGroup),new String(CONSTANTS.EBCDIC_ENCODING));
      		setInitDone(false);
      		process();
      		return getRc();
      }
      /**
      * process 
      * Input  : None 

      * Output :  

      * - summaryFinEvntNo               COBOL Name: WS-SUMMARY-FIN-EVNT-NO
      * - summaryFinMktId                COBOL Name: WS-SUMMARY-FIN-MKT-ID
      * - summaryFinCat                  COBOL Name: WS-SUMMARY-FIN-CAT
      * - tb05323FinEvntNo               COBOL Name: TB05323-FIN-EVNT-NO
      * - tb05323FinMktId                COBOL Name: TB05323-FIN-MKT-ID
      * - financialCategory              COBOL Name: WS-FINANCIAL-CATEGORY
      * - finShortCategory               COBOL Name: WS-FIN-SHORT-CATEGORY
      * - codeValue                      COBOL Name: WS-CODE-VALUE
      * - codeDesc                       COBOL Name: WS-CODE-DESC
      * - search                         COBOL Name: WS-SEARCH
      *
      * @throws CFException
      */
      @Override
      public int process() throws Exception {
       initVars();
       try {
       setCodePage("1047");

// *
//  MOVE 676 TO WS-SUMMARY-FIN-EVNT-NO (1)
          summary.getSummarySubldgEntries(0).setSummaryFinEvntNo(676);
//  MOVE 676 TO WS-SUMMARY-FIN-EVNT-NO (2)
          summary.getSummarySubldgEntries(1).setSummaryFinEvntNo(676);
//  MOVE 676 TO WS-SUMMARY-FIN-EVNT-NO (3)
          summary.getSummarySubldgEntries(2).setSummaryFinEvntNo(676);
//  MOVE 676 TO WS-SUMMARY-FIN-EVNT-NO (4)
          summary.getSummarySubldgEntries(3).setSummaryFinEvntNo(676);
//  MOVE 676 TO WS-SUMMARY-FIN-EVNT-NO (5)
          summary.getSummarySubldgEntries(4).setSummaryFinEvntNo(676);

// *
//  MOVE 'T00' TO WS-SUMMARY-FIN-MKT-ID (1)
//  LITERAL_T00 = 'T00'
          summary.getSummarySubldgEntries(0).setSummaryFinMktId(CONSTANTS.LITERAL_T00);
//  MOVE 'T02' TO WS-SUMMARY-FIN-MKT-ID (2)
//  LITERAL_T02 = 'T02'
          summary.getSummarySubldgEntries(1).setSummaryFinMktId(CONSTANTS.LITERAL_T02);
//  MOVE 'T02' TO WS-SUMMARY-FIN-MKT-ID (3)
//  LITERAL_T02 = 'T02'
          summary.getSummarySubldgEntries(2).setSummaryFinMktId(CONSTANTS.LITERAL_T02);

// *       Move 't99' to ws-summary-fin-mkt-id(4)
//  MOVE 'T02' TO WS-SUMMARY-FIN-MKT-ID (4)
//  LITERAL_T02 = 'T02'
          summary.getSummarySubldgEntries(3).setSummaryFinMktId(CONSTANTS.LITERAL_T02);
//  MOVE 'T02' TO WS-SUMMARY-FIN-MKT-ID (5)
//  LITERAL_T02 = 'T02'
          summary.getSummarySubldgEntries(4).setSummaryFinMktId(CONSTANTS.LITERAL_T02);

// *
//  MOVE 28736 TO WS-SUMMARY-FIN-CAT (1)
          summary.getSummarySubldgEntries(0).setSummaryFinCat(28736);
//  MOVE 28896 TO WS-SUMMARY-FIN-CAT (2)
          summary.getSummarySubldgEntries(1).setSummaryFinCat(28896);
//  MOVE 28902 TO WS-SUMMARY-FIN-CAT (3)
          summary.getSummarySubldgEntries(2).setSummaryFinCat(28902);
//  MOVE 28904 TO WS-SUMMARY-FIN-CAT (4)
          summary.getSummarySubldgEntries(3).setSummaryFinCat(28904);
//  MOVE 29126 TO WS-SUMMARY-FIN-CAT (5)
          summary.getSummarySubldgEntries(4).setSummaryFinCat(29126);

// *
          // MOVE 676 TO TB05323-FIN-EVNT-NO
          work.setTb05323FinEvntNo((long)676);
          // MOVE 'T02' TO TB05323-FIN-MKT-ID
          //  LITERAL_T02 = 'T02'
          work.setTb05323FinMktId(CONSTANTS.LITERAL_T02);
//  MOVE 29126 TO WS-FINANCIAL-CATEGORY
          work.setFinancialCategory(29126);
          // MOVE 29126 TO WS-FIN-SHORT-CATEGORY
          work.setFinShortCategory((short)29126);

// *

// *
//  PERFORM 0100-SEARCH THRU 0100-EXIT
          search();/*0100-SEARCH*/
          if (this.isProgramEnded()) {
              return getRc();
          }
//  PERFORM 0110-SEARCH THRU 0110-EXIT
          search0110();/*0110-SEARCH*/
          if (this.isProgramEnded()) {
              return getRc();
          }
//  DISPLAY '-------------------------------------------'
          logger.info("-------------------------------------------"); 
//  MOVE "120" TO WS-CODE-VALUE (1)
//  LITERAL_120 = "120"
          wtFields.getWtCodeCtrl(0).setCodeValue(CONSTANTS.LITERAL_120);
//  MOVE "121" TO WS-CODE-VALUE (2)
//  LITERAL_121 = "121"
          wtFields.getWtCodeCtrl(1).setCodeValue(CONSTANTS.LITERAL_121);
//  MOVE "122" TO WS-CODE-VALUE (3)
//  LITERAL_122 = "122"
          wtFields.getWtCodeCtrl(2).setCodeValue(CONSTANTS.LITERAL_122);
//  MOVE "125" TO WS-CODE-VALUE (4)
//  LITERAL_125 = "125"
          wtFields.getWtCodeCtrl(3).setCodeValue(CONSTANTS.LITERAL_125);
//  MOVE "127" TO WS-CODE-VALUE (5)
//  LITERAL_127 = "127"
          wtFields.getWtCodeCtrl(4).setCodeValue(CONSTANTS.LITERAL_127);
//  MOVE "129" TO WS-CODE-VALUE (6)
//  LITERAL_129 = "129"
          wtFields.getWtCodeCtrl(5).setCodeValue(CONSTANTS.LITERAL_129);
//  MOVE "AAA" TO WS-CODE-DESC (1)
//  LITERAL_AAA = "AAA"
          wtFields.getWtCodeCtrl(0).setCodeDesc(CONSTANTS.LITERAL_AAA);
//  MOVE "BBB" TO WS-CODE-DESC (2)
//  LITERAL_BBB = "BBB"
          wtFields.getWtCodeCtrl(1).setCodeDesc(CONSTANTS.LITERAL_BBB);
//  MOVE "CCC" TO WS-CODE-DESC (3)
//  LITERAL_CCC = "CCC"
          wtFields.getWtCodeCtrl(2).setCodeDesc(CONSTANTS.LITERAL_CCC);
//  MOVE "EEE" TO WS-CODE-DESC (4)
//  LITERAL_EEE = "EEE"
          wtFields.getWtCodeCtrl(3).setCodeDesc(CONSTANTS.LITERAL_EEE);
//  MOVE "GGG" TO WS-CODE-DESC (5)
//  LITERAL_GGG = "GGG"
          wtFields.getWtCodeCtrl(4).setCodeDesc(CONSTANTS.LITERAL_GGG);
//  MOVE "HHH" TO WS-CODE-DESC (6)
//  LITERAL_HHH = "HHH"
          wtFields.getWtCodeCtrl(5).setCodeDesc(CONSTANTS.LITERAL_HHH);

// *
//  DISPLAY '-------------------------------------------'
          logger.info("-------------------------------------------"); 
//  DISPLAY ' ABOUT TO SEARCH 122 '
          logger.info(" ABOUT TO SEARCH 122 "); 
          // MOVE "122" TO WS-SEARCH
          //  LITERAL_122 = "122"
          work.setSearch(CONSTANTS.LITERAL_122);
//  PERFORM 0200-SEARCH THRU 0200-EXIT
          search0200();/*0200-SEARCH*/
          if (this.isProgramEnded()) {
              return getRc();
          }

// *
//  DISPLAY '-------------------------------------------'
          logger.info("-------------------------------------------"); 
//  DISPLAY ' ABOUT TO SEARCH 123 '
          logger.info(" ABOUT TO SEARCH 123 "); 
          // MOVE "123" TO WS-SEARCH
          //  LITERAL_123 = "123"
          work.setSearch(CONSTANTS.LITERAL_123);
//  PERFORM 0200-SEARCH THRU 0200-EXIT
          search0200();/*0200-SEARCH*/
          if (this.isProgramEnded()) {
              return getRc();
          }

// *
//  DISPLAY '-------------------------------------------'
          logger.info("-------------------------------------------"); 
//  DISPLAY ' ABOUT TO SEARCH 127 '
          logger.info(" ABOUT TO SEARCH 127 "); 
          // MOVE "127" TO WS-SEARCH
          //  LITERAL_127 = "127"
          work.setSearch(CONSTANTS.LITERAL_127);
//  PERFORM 0200-SEARCH THRU 0200-EXIT
          search0200();/*0200-SEARCH*/
          if (this.isProgramEnded()) {
              return getRc();
          }

// *
//  DISPLAY '-------------------------------------------'
          logger.info("-------------------------------------------"); 
//  DISPLAY ' ABOUT TO SEARCH 129 '
          logger.info(" ABOUT TO SEARCH 129 "); 
          // MOVE "129" TO WS-SEARCH
          //  LITERAL_129 = "129"
          work.setSearch(CONSTANTS.LITERAL_129);
//  PERFORM 0200-SEARCH THRU 0200-EXIT
          search0200();/*0200-SEARCH*/
          if (this.isProgramEnded()) {
              return getRc();
          }
          ;
//  PERFORM PROCESS-1
          process1();/*PROCESS-1*/
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
       return getRc(); // Exit with return code
      // end of process method
      }
      /**
      * programDone 
      *   This method is derived from 
  *   COBOL Paragraph - PROGRAM-DONE COBOL Cyclomatic complexity - 2
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      private void programDone() throws Exception {
//  STOP RUN
          throw Terminate.TERMINATE;
      
      }
      /**
      * search 
      *   This method is derived from 
  *   COBOL Paragraph - 0100-SEARCH COBOL Cyclomatic complexity - 4
      * Input  :  

      * - summarySubldgEntries           COBOL Name: WS-SUMMARY-SUBLDG-ENTRIES
      * - summaryFinEvntNo               COBOL Name: WS-SUMMARY-FIN-EVNT-NO
      * - summarySubldgIndex             COBOL Name: WS-SUMMARY-SUBLDG-INDEX
      * - tb05323FinEvntNo               COBOL Name: TB05323-FIN-EVNT-NO
      * - summaryFinMktId                COBOL Name: WS-SUMMARY-FIN-MKT-ID
      * - tb05323FinMktId                COBOL Name: TB05323-FIN-MKT-ID
      * - summaryFinCat                  COBOL Name: WS-SUMMARY-FIN-CAT
      * - financialCategory              COBOL Name: WS-FINANCIAL-CATEGORY
      *
      * Output : None 

      * @throws CFException
      */
      private void search() throws Exception {
			// Declare local variables used in the method
			boolean keepSearching = true;
			int[] searchIndexes = null;
			int searchLowPoint = 0;
			int searchMidPoint = 0;
			int searchHighPoint = 0;
			int searchCompare = 0;
			int financialCategory = 0;
			long tb05323FinEvntNo = 0;
			char[] tb05323FinMktId = null;
			// End of variable declaration

          tb05323FinEvntNo = work.getTb05323FinEvntNo();
          financialCategory = work.getFinancialCategory();
          tb05323FinMktId = work.getTb05323FinMktId();
//  SEARCH ALL WS-SUMMARY-SUBLDG-ENTRIES
          // Binary Search through summary.summarySubldgEntries
          searchLowPoint = 0; //prevLowValue
          searchHighPoint = summary.getSummarySubldgMaxCntr(); //prevHighValue
          searchMidPoint = searchHighPoint / 2; //starting at mid point
          searchIndexes = new int[]{searchLowPoint,searchMidPoint,searchHighPoint};
          keepSearching = true;
          while (keepSearching) {
          // compare logic below
             searchCompare = compareAscending(summary.getSummarySubldgEntries(searchMidPoint).getSummaryFinEvntNo() , tb05323FinEvntNo);
             if (searchCompare == 0) 
             searchCompare = compareAscending(summary.getSummarySubldgEntries(searchMidPoint).getSummaryFinCat() , financialCategory);
             if (searchCompare == 0) 
             searchCompare = compareAscending(summary.getSummarySubldgEntries(searchMidPoint).getSummaryFinMktId(),tb05323FinMktId);
          // end of compare logic
          	if (searchCompare == 0 ) { // if search found
          	      keepSearching = false;
          	     summarySubldgIndex = searchMidPoint	 + 1;
//  DISPLAY 'JO FOUND '
              logger.info("JO FOUND "); 
          	} else  {
          		adjustSearchIndex(searchCompare,searchIndexes);
          		searchLowPoint  = searchIndexes[0];
           		searchMidPoint  = searchIndexes[1];
           		searchHighPoint = searchIndexes[2];
           		if (searchMidPoint == -1) { // search exhausted
           		    keepSearching = false; 
//  DISPLAY ' NOT FOUND DURING SEARCH ALL '
              logger.info(" NOT FOUND DURING SEARCH ALL "); 
           		}
          	}
          }
  
          ;
      
      }
      /**
      * search0110 
      *   This method is derived from 
  *   COBOL Paragraph - 0110-SEARCH COBOL Cyclomatic complexity - 4
      * Input  :  

      * - summarySubldgEntries           COBOL Name: WS-SUMMARY-SUBLDG-ENTRIES
      * - summaryFinEvntNo               COBOL Name: WS-SUMMARY-FIN-EVNT-NO
      * - summarySubldgIndex             COBOL Name: WS-SUMMARY-SUBLDG-INDEX
      * - tb05323FinEvntNo               COBOL Name: TB05323-FIN-EVNT-NO
      * - summaryFinMktId                COBOL Name: WS-SUMMARY-FIN-MKT-ID
      * - tb05323FinMktId                COBOL Name: TB05323-FIN-MKT-ID
      * - summaryFinCat                  COBOL Name: WS-SUMMARY-FIN-CAT
      * - finShortCategory               COBOL Name: WS-FIN-SHORT-CATEGORY
      *
      * Output : None 

      * @throws CFException
      */
      private void search0110() throws Exception {
			// Declare local variables used in the method
			boolean keepSearching = true;
			int[] searchIndexes = null;
			int searchLowPoint = 0;
			int searchMidPoint = 0;
			int searchHighPoint = 0;
			int searchCompare = 0;
			long tb05323FinEvntNo = 0;
			char[] tb05323FinMktId = null;
			short finShortCategory = 0;
			// End of variable declaration

          finShortCategory = work.getFinShortCategory();
          tb05323FinEvntNo = work.getTb05323FinEvntNo();
          tb05323FinMktId = work.getTb05323FinMktId();
//  SEARCH ALL WS-SUMMARY-SUBLDG-ENTRIES
          // Binary Search through summary.summarySubldgEntries
          searchLowPoint = 0; //prevLowValue
          searchHighPoint = summary.getSummarySubldgMaxCntr(); //prevHighValue
          searchMidPoint = searchHighPoint / 2; //starting at mid point
          searchIndexes = new int[]{searchLowPoint,searchMidPoint,searchHighPoint};
          keepSearching = true;
          while (keepSearching) {
          // compare logic below
             searchCompare = compareAscending(summary.getSummarySubldgEntries(searchMidPoint).getSummaryFinEvntNo() , tb05323FinEvntNo);
             if (searchCompare == 0) 
             searchCompare = compareAscending(summary.getSummarySubldgEntries(searchMidPoint).getSummaryFinCat() , finShortCategory);
             if (searchCompare == 0) 
             searchCompare = compareAscending(summary.getSummarySubldgEntries(searchMidPoint).getSummaryFinMktId(),tb05323FinMktId);
          // end of compare logic
          	if (searchCompare == 0 ) { // if search found
          	      keepSearching = false;
          	     summarySubldgIndex = searchMidPoint	 + 1;
//  DISPLAY 'JO FOUND '
              logger.info("JO FOUND "); 
          	} else  {
          		adjustSearchIndex(searchCompare,searchIndexes);
          		searchLowPoint  = searchIndexes[0];
           		searchMidPoint  = searchIndexes[1];
           		searchHighPoint = searchIndexes[2];
           		if (searchMidPoint == -1) { // search exhausted
           		    keepSearching = false; 
//  DISPLAY ' NOT FOUND DURING SEARCH ALL '
              logger.info(" NOT FOUND DURING SEARCH ALL "); 
           		}
          	}
          }
  
          ;
      
      }
      /**
      * search0200 
      *   This method is derived from 
  *   COBOL Paragraph - 0200-SEARCH COBOL Cyclomatic complexity - 10
      * Input  :  

      * - wtCodeCtrl                     COBOL Name: WT-CODE-CTRL
      * - codeValue                      COBOL Name: WS-CODE-VALUE
      * - search                         COBOL Name: WS-SEARCH
      * - codeDesc                       COBOL Name: WS-CODE-DESC
      *
      * Output :  

      * - wtCodeCtrlIndex                COBOL Name: WT-CODE-CTRL-INDEX
      *
      * @throws CFException
      */
      private void search0200() throws Exception {
			// Declare local variables used in the method
			boolean keepSearching = true;
			char[] search = null;
			int[] searchIndexes = null;
			int searchLowPoint = 0;
			int searchMidPoint = 0;
			int searchHighPoint = 0;
			int searchCompare = 0;
			// End of variable declaration


// *
//  DISPLAY ' REGULAR SEARCH      '
          logger.info(" REGULAR SEARCH      "); 
//  SET WT-CODE-CTRL-INDEX TO 1
          wtCodeCtrlIndex = 1; 
          
          search = work.getSearch();
//  SEARCH WT-CODE-CTRL
          keepSearching = true;
          while(keepSearching) {
          	if  (		compareChars(wtFields.getWtCodeCtrl(wtCodeCtrlIndex - 1).getCodeValue(),search) == 0 ) { 
//  DISPLAY 'WS-CODE-DESC(WT-CODE-CTRL-INDEX) = '
              logger.info("WS-CODE-DESC(WT-CODE-CTRL-INDEX) = "); 
//  DISPLAY WS-CODE-DESC ( WT-CODE-CTRL-INDEX )
              logger.info(new String(wtFields.getWtCodeCtrl(wtCodeCtrlIndex - 1).getCodeDesc())); 
          	break;
          	}
          	wtCodeCtrlIndex++;
          	if (wtCodeCtrlIndex > 6) { 
          	 keepSearching = false;
          	}
          }
          	if(!keepSearching) { 
//  DISPLAY " SEARCH ELEMENT NOT FOUND "
              logger.info(" SEARCH ELEMENT NOT FOUND "); 
          	}
  

// *
//  DISPLAY ' BINARY SEARCH       '
          logger.info(" BINARY SEARCH       "); 
//  SET WT-CODE-CTRL-INDEX TO 1
          wtCodeCtrlIndex = 1; 
          
          search = work.getSearch();
//  SEARCH ALL WT-CODE-CTRL
          // Binary Search through wtFields.wtCodeCtrl
          searchLowPoint = 0; //prevLowValue
          searchHighPoint = wtFields.wtCodeCtrlSize(); //prevHighValue
          searchMidPoint = searchHighPoint / 2; //starting at mid point
          searchIndexes = new int[]{searchLowPoint,searchMidPoint,searchHighPoint};
          keepSearching = true;
          while (keepSearching) {
          // compare logic below
             searchCompare = compareAscending(wtFields.getWtCodeCtrl(searchMidPoint).getCodeValue(),search);
          // end of compare logic
          	if (searchCompare == 0 ) { // if search found
          	      keepSearching = false;
          	     wtCodeCtrlIndex = searchMidPoint	 + 1;
//  DISPLAY WS-CODE-DESC ( WT-CODE-CTRL-INDEX )
              logger.info(new String(wtFields.getWtCodeCtrl(wtCodeCtrlIndex - 1).getCodeDesc())); 
          	} else  {
          		adjustSearchIndex(searchCompare,searchIndexes);
          		searchLowPoint  = searchIndexes[0];
           		searchMidPoint  = searchIndexes[1];
           		searchHighPoint = searchIndexes[2];
           		if (searchMidPoint == -1) { // search exhausted
           		    keepSearching = false; 
//  DISPLAY " SEARCH ALL ELEMENT NOT FOUND "
              logger.info(" SEARCH ALL ELEMENT NOT FOUND "); 
           		}
          	}
          }
  

// *
//  DISPLAY ' EVALUATE            '
          logger.info(" EVALUATE            "); 
          search = work.getSearch();
//  EVALUATE TRUE
          if  (		compareChars(search,CONSTANTS.LITERAL_129) == 0 ) { 
//  DISPLAY 'SEARCH MUST HAVE FOUND ' WS-SEARCH
              logger.info("SEARCH MUST HAVE FOUND {}", new String(work.getSearch())); 
          }
          else if  (		compareChars(search,CONSTANTS.LITERAL_127) == 0 ) { 
//  DISPLAY 'SEARCH MUST HAVE FOUND ' WS-SEARCH
              logger.info("SEARCH MUST HAVE FOUND {}", new String(work.getSearch())); 
          }
          else if  (		compareChars(search,CONSTANTS.LITERAL_125) == 0 ) { 
//  DISPLAY 'SEARCH MUST HAVE FOUND ' WS-SEARCH
              logger.info("SEARCH MUST HAVE FOUND {}", new String(work.getSearch())); 
          }
          else if  (		compareChars(search,CONSTANTS.LITERAL_122) == 0 ) { 
//  DISPLAY 'SEARCH MUST HAVE FOUND ' WS-SEARCH
              logger.info("SEARCH MUST HAVE FOUND {}", new String(work.getSearch())); 
          }
          else if  (		compareChars(search,CONSTANTS.LITERAL_121) == 0 ) { 
//  DISPLAY 'SEARCH MUST HAVE FOUND ' WS-SEARCH
              logger.info("SEARCH MUST HAVE FOUND {}", new String(work.getSearch())); 
          }
          else if  (		compareChars(search,CONSTANTS.LITERAL_120) == 0 ) { 
//  DISPLAY 'SEARCH MUST HAVE FOUND ' WS-SEARCH
              logger.info("SEARCH MUST HAVE FOUND {}", new String(work.getSearch())); 
          }
          else   { 
//  DISPLAY 'NO SUCH VALUE EXIST  '
              logger.info("NO SUCH VALUE EXIST  "); 
          }
  
          ;
      
      }
      /**
      * process1 
      *   This method is derived from 
  *   COBOL Paragraph - PROCESS-1 COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      private void process1() throws Exception {
//  PERFORM PROGRAM-DONE
          programDone();/*PROGRAM-DONE*/
          if (this.isProgramEnded()) {
              return ;
          }
      
      }
  
  
      /**
* This method pre-initializes variables consistent with
* what a mainframe program would have done at the start of a program
*/
      @Override
      public void initVars() throws CFException {
      setProgramEnded(false);
          if(!isInitDone()) {
          	this.setRc(0);
          	setInitDone(true);
          }
        CFUtil.resetDecimalAsComma();
       }
  
      public int call(Object[] params) throws Exception {
      
      int len = params.length;
         if (len > 0 && params[0] != null )
            firstNumberGroup.set((Field)params[0]);
         if (len > 1 && params[1] != null )
            secondNumberGroup.set((Field)params[1]);
         if (len > 2 && params[2] != null )
            resultNumberGroup.set((Field)params[2]);
         // invoke the process and return rc
         return process();
         
      }
      
      public int call(Field... parameters) throws Exception {
         for (int index = 0; index < parameters.length;index++) {
             switch(index) {
              case 0:
                      if(parameters[index] != null ) {
              		if (parameters[index] instanceof FirstNumberGroup) {
                       	this.firstNumberGroup = ((FirstNumberGroup) parameters[index]);
                  	} else {
                       	this.firstNumberGroup.set(parameters[index]);
                  	}
                  }
                
                  break;
              case 1:
                      if(parameters[index] != null ) {
              		if (parameters[index] instanceof SecondNumberGroup) {
                       	this.secondNumberGroup = ((SecondNumberGroup) parameters[index]);
                  	} else {
                       	this.secondNumberGroup.set(parameters[index]);
                  	}
                  }
                
                  break;
              case 2:
                      if(parameters[index] != null ) {
              		if (parameters[index] instanceof ResultNumberGroup) {
                       	this.resultNumberGroup = ((ResultNumberGroup) parameters[index]);
                  	} else {
                       	this.resultNumberGroup.set(parameters[index]);
                  	}
                  }
                
                  break;
            }
         }
          return process();
      }
      
      
  
  
  
  
  
  }
