# Program SUP01780 | DD : PANACCT1 | VSAM KSDS
SUP01780.ddname.PANACCT1=UDEV47.PLAPP.SACCT1
# Program SUP01780 | DD : PANACCTA | VSAM KSDS
SUP01780.ddname.PANACCTA=UDEV47.PLAPP.SACCT10
SUP01780.TmPanFile1.DISP=SHR,KEEP,KEEP
# 
# End of SUP01780
