package com.cloudframe.app.mcsort05.file.records;
import com.cloudframe.app.sort.model.SortKeyObject;
/* Java Code Generated by CloudFrame */


public class Ip40005GrpFileSeqNbrKeys extends SortKeyObject{

	private  long sortRecPos = 0;
	private  int sortRecLen = 0;
	private  int fileIndx = 0;
    private int ip40005GrpFileSeqNbr;  
    private long ip40005GroupSeqNum;  
	
	public long getSortRecPos() {
		return sortRecPos;
	}

	public void setSortRecPos(long sortRecPos) {
		this.sortRecPos = sortRecPos;
	}

	public int getSortRecLen() {
		return sortRecLen;
	}

	public void setSortRecLen(int sortRecLen) {
		this.sortRecLen = sortRecLen;
	}
	
	public int getFileIndx() {
		return fileIndx;
	}

	public void setFileIndx(int indx) {
		this.fileIndx = indx;
	}
	
    /* Disp-Num - int - ip40005GrpFileSeqNbr */
	public int getIp40005GrpFileSeqNbr() {
		return ip40005GrpFileSeqNbr;
	}

	public void setIp40005GrpFileSeqNbr(int val) {
		this.ip40005GrpFileSeqNbr = val; 
	}
    /* Binary - long - ip40005GroupSeqNum */
	public long getIp40005GroupSeqNum() {
		return ip40005GroupSeqNum;
	}

	public void setIp40005GroupSeqNum(long val) {
		this.ip40005GroupSeqNum = val; 
	}

}
