#common-test-properties
spring.main.log-startup-info=OFF
logging.pattern.file=%msg%n
logging.file.name=QA274.log
logging.logback.rollingpolicy.clean-history-on-start=true
logging.level.com.zaxxer=OFF
logging.level.com.cloudframe.app.dao.CFDataSourceConfiguration=OFF
logging.level.com.cloudframe.app.vsam.VSAMClusterUtil=OFF
logging.level.com.cloudframe.app.utility.CFConfiguration=OFF
#test-specific-properties
# compare.files[0]=ExpSys201AsaServerReport,Sys201AsaServerReport
#compare.files[1]=Exp_QA274_log,QA274.log
#project-specific-properties
#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
# spring.main.lazy-initialization=true
timeZoneId=Etc/GMT
SF327010.ddname.SYS001=SYS001
SF327010.Sys001ExtractZLogFile=SYS001
SF327010.Sys001ExtractZLogFileCharSet=cp1047
SF327010.Sys001ExtractZLogFileCRLFflag=no
SF327010.ddname.SYS201=Sys201AsaServerReport
SF327010.Sys201AsaServerReport=Sys201AsaServerReport
SF327010.Sys201AsaServerReportCharSet=utf-8
SF327010.Sys201AsaServerReportCRLFflag=yes
#logging.level.com.cloudframe=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
# 
# End of SF327010
