# Program ECHOQSAM | DD : INFILE | RecordFormat : FixedLength | RecordLength : 1001
ECHOQSAM.ddname.INFILE=InputFile
ECHOQSAM.InputFile=InputFile
ECHOQSAM.InputFileCharSet=cp1047
ECHOQSAM.InputFileCRLFflag=no
# Program ECHOQSAM | DD : OUTFILE | RecordFormat : FixedLength | RecordLength : 1001
ECHOQSAM.ddname.OUTFILE=OutputFile
ECHOQSAM.OutputFile=OutputFile
ECHOQSAM.OutputFileCharSet=utf-8
ECHOQSAM.OutputFileCRLFflag=yes
# 
# End of ECHOQSAM
