#STEP:SORT001| PGM:SORT| DD:SORTIN
McsfsortSort001SortIn=CLOUDFRM.MC.SORT.IN001
McsfsortSort001SortIn.DISP=SHR,KEEP,KEEP
McsfsortSort001SortInRecordType=VB
McsfsortSort001SortInRecordLen=32752
#STEP:SORT001| PGM:SORT| DD:SORTOUT
McsfsortSort001SortOut=CLOUDFRM.MC.SORT.OUT001
McsfsortSort001SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort001SortOutRecordType=FB
McsfsortSort001SortOutRecordLen=32748
#STEP:SORT002| PGM:SORT| DD:SORTIN
McsfsortSort002SortIn=CLOUDFRM.MC.SORT.IN002
McsfsortSort002SortIn.DISP=SHR,KEEP,KEEP
McsfsortSort002SortInRecordType=VB
McsfsortSort002SortInRecordLen=30004
#STEP:SORT002| PGM:SORT| DD:SORTOUT
McsfsortSort002SortOut=CLOUDFRM.MC.SORT.OUT002
McsfsortSort002SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort002SortOutRecordType=FB
McsfsortSort002SortOutRecordLen=30000
#STEP:SORT003| PGM:SORT| DD:SORTIN
McsfsortSort003SortIn=CLOUDFRM.MC.SORT.IN003
McsfsortSort003SortIn.DISP=SHR,KEEP,KEEP
McsfsortSort003SortInRecordType=FB
McsfsortSort003SortInRecordLen=2000
#STEP:SORT003| PGM:SORT| DD:SORTOUT
McsfsortSort003SortOut=CLOUDFRM.MC.SORT.OUT003
McsfsortSort003SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort003SortOutRecordType=FB
McsfsortSort003SortOutRecordLen=2000
#STEP:SORT004| PGM:SORT| DD:SORTIN
McsfsortSort004SortIn=CLOUDFRM.MC.SORT.IN004
McsfsortSort004SortIn.DISP=SHR,KEEP,KEEP
McsfsortSort004SortInRecordType=VB
McsfsortSort004SortInRecordLen=8004
#STEP:SORT004| PGM:SORT| DD:SORTOF1
McsfsortSort004SortOut[0]=CLOUDFRM.MC.SORT.OUT0041
McsfsortSort004SortOut[0].DISP=NEW,KEEP,KEEP
McsfsortSort004SortOut0RecordType=VB
McsfsortSort004SortOut0RecordLen=8004
#STEP:SORT004| PGM:SORT| DD:SORTOF2
McsfsortSort004SortOut[1]=CLOUDFRM.MC.SORT.OUT0042
McsfsortSort004SortOut[1].DISP=NEW,KEEP,KEEP
McsfsortSort004SortOut1RecordType=VB
McsfsortSort004SortOut1RecordLen=8004
#STEP:SORT004| PGM:SORT| DD:SORTOF3
McsfsortSort004SortOut[2]=CLOUDFRM.MC.SORT.OUT0043
McsfsortSort004SortOut[2].DISP=NEW,KEEP,KEEP
McsfsortSort004SortOut2RecordType=VB
McsfsortSort004SortOut2RecordLen=8004
#STEP:SORT004| PGM:SORT| DD:SORTOF4
McsfsortSort004SortOut[3]=CLOUDFRM.MC.SORT.OUT0044
McsfsortSort004SortOut[3].DISP=NEW,KEEP,KEEP
McsfsortSort004SortOut3RecordType=VB
McsfsortSort004SortOut3RecordLen=8004
#STEP:SORT004| PGM:SORT| DD:SORTOF5
McsfsortSort004SortOut[4]=CLOUDFRM.MC.SORT.OUT0045
McsfsortSort004SortOut[4].DISP=NEW,KEEP,KEEP
McsfsortSort004SortOut4RecordType=VB
McsfsortSort004SortOut4RecordLen=8004
#STEP:SORT005| PGM:SORT| DD:SORTIN
McsfsortSort005SortIn=CLOUDFRM.MC.SORT.IN005
McsfsortSort005SortIn.DISP=SHR,KEEP,KEEP
McsfsortSort005SortInRecordType=VB
McsfsortSort005SortInRecordLen=32756
#STEP:SORT005| PGM:SORT| DD:SORTOUT
McsfsortSort005SortOut=CLOUDFRM.MC.SORT.OUT005
McsfsortSort005SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort005SortOutRecordType=VB
McsfsortSort005SortOutRecordLen=32756
#STEP:SORT006| PGM:SORT| DD:SORTIN
McsfsortSort006SortIn=CLOUDFRM.MC.SORT.IN006
McsfsortSort006SortIn.DISP=SHR,KEEP,KEEP
McsfsortSort006SortInRecordType=FB
McsfsortSort006SortInRecordLen=913
#STEP:SORT006| PGM:SORT| DD:SORTOUT
McsfsortSort006SortOut=CLOUDFRM.MC.SORT.OUT006
McsfsortSort006SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort006SortOutRecordType=FB
McsfsortSort006SortOutRecordLen=900
#STEP:SORT007| PGM:SORT| DD:SORTIN
McsfsortSort007SortIn=CLOUDFRM.MC.SORT.IN007
McsfsortSort007SortIn.DISP=SHR,KEEP,KEEP
McsfsortSort007SortInRecordType=FB
McsfsortSort007SortInRecordLen=397
#STEP:SORT007| PGM:SORT| DD:SORTOUT
McsfsortSort007SortOut=CLOUDFRM.MC.SORT.OUT007
McsfsortSort007SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort007SortOutRecordType=FB
McsfsortSort007SortOutRecordLen=397
#STEP:SORT008| PGM:SORT| DD:SORTJNF1
McsfsortSort008SortIn[0]=CLOUDFRM.MC.SORT.SORTJNF1
McsfsortSort008SortIn[0].DISP=SHR,KEEP,KEEP
McsfsortSort008SortIn0RecordType=FB
McsfsortSort008SortIn0RecordLen=26
#STEP:SORT008| PGM:SORT| DD:SORTJNF2
McsfsortSort008SortIn[1]=CLOUDFRM.MC.SORT.SORTJNF2
McsfsortSort008SortIn[1].DISP=SHR,KEEP,KEEP
McsfsortSort008SortIn1RecordType=FB
McsfsortSort008SortIn1RecordLen=180
#STEP:SORT008| PGM:SORT| DD:SORTOUT
McsfsortSort008SortOut=CLOUDFRM.MC.SORT.OUT008
McsfsortSort008SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort008SortOutRecordType=FB
McsfsortSort008SortOutRecordLen=180
#STEP:SORT009| PGM:SORT| DD:SORTIN
McsfsortSort009SortIn=CLOUDFRM.MC.SORT.IN009
McsfsortSort009SortIn.DISP=SHR,KEEP,KEEP
McsfsortSort009SortInRecordType=VB
McsfsortSort009SortInRecordLen=32756
#STEP:SORT009| PGM:SORT| DD:SORTOUT
McsfsortSort009SortOut=CLOUDFRM.MC.SORT.OUT009
McsfsortSort009SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort009SortOutRecordType=VB
McsfsortSort009SortOutRecordLen=32756
#STEP:SORT010| PGM:SORT| DD:SORTIN
McsfsortSort010SortIn=CLOUDFRM.MC.SORT.IN010
McsfsortSort010SortIn.DISP=SHR,KEEP,KEEP
McsfsortSort010SortInRecordType=VB
McsfsortSort010SortInRecordLen=32756
#STEP:SORT010| PGM:SORT| DD:SORTOF1
McsfsortSort010SortOut=CLOUDFRM.MC.SORT.OUT0101
McsfsortSort010SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort010SortOutRecordType=VB
McsfsortSort010SortOutRecordLen=32756
#STEP:SORT011| PGM:SORT| DD:SORTIN
McsfsortSort011SortIn=CLOUDFRM.MC.SORT.IN011
McsfsortSort011SortIn.DISP=SHR,KEEP,KEEP
McsfsortSort011SortInRecordType=FB
McsfsortSort011SortInRecordLen=2053
#STEP:SORT011| PGM:SORT| DD:SORTOUT
McsfsortSort011SortOut=CLOUDFRM.MC.SORT.OUT011
McsfsortSort011SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort011SortOutRecordType=FB
McsfsortSort011SortOutRecordLen=2000
#STEP:SORT012| PGM:SORT| DD:SORTIN
McsfsortSort012SortIn=CLOUDFRM.MC.SORT.IN012
McsfsortSort012SortIn.DISP=SHR,KEEP,KEEP
McsfsortSort012SortInRecordType=VB
McsfsortSort012SortInRecordLen=32756
#STEP:SORT012| PGM:SORT| DD:SORTOF1
McsfsortSort012SortOut[0]=CLOUDFRM.MC.SORT.OUT0121
McsfsortSort012SortOut[0].DISP=NEW,KEEP,KEEP
McsfsortSort012SortOut0RecordType=VB
McsfsortSort012SortOut0RecordLen=32756
#STEP:SORT012| PGM:SORT| DD:SORTOF2
McsfsortSort012SortOut[1]=CLOUDFRM.MC.SORT.OUT0122
McsfsortSort012SortOut[1].DISP=NEW,KEEP,KEEP
McsfsortSort012SortOut1RecordType=VB
McsfsortSort012SortOut1RecordLen=32756
#STEP:SORT012| PGM:SORT| DD:SORTOF3
McsfsortSort012SortOut[2]=CLOUDFRM.MC.SORT.OUT0123
McsfsortSort012SortOut[2].DISP=NEW,KEEP,KEEP
McsfsortSort012SortOut2RecordType=VB
McsfsortSort012SortOut2RecordLen=32756
#STEP:SORT013| PGM:SORT| DD:SORTIN
McsfsortSort013SortIn=CLOUDFRM.MC.SORT.IN013
McsfsortSort013SortIn.DISP=SHR,KEEP,KEEP
McsfsortSort013SortInRecordType=F
McsfsortSort013SortInRecordLen=120
#STEP:SORT013| PGM:SORT| DD:SORTOUT
McsfsortSort013SortOut=CLOUDFRM.MC.SORT.OUT013
McsfsortSort013SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort013SortOutRecordType=FB
McsfsortSort013SortOutRecordLen=120
#STEP:SORT014| PGM:SORT| DD:SORTIN
McsfsortSort014SortIn=CLOUDFRM.MC.SORT.IN014
McsfsortSort014SortIn.DISP=SHR,KEEP,KEEP
McsfsortSort014SortInRecordType=FB
McsfsortSort014SortInRecordLen=397
#STEP:SORT014| PGM:SORT| DD:SORTOUT
McsfsortSort014SortOut=CLOUDFRM.MC.SORT.OUT014
McsfsortSort014SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort014SortOutRecordType=FB
McsfsortSort014SortOutRecordLen=397
#STEP:SORT015| PGM:SORT| DD:SORTJNF1
McsfsortSort015SortIn[0]=CLOUDFRM.MC.SORT.S015JNF1
McsfsortSort015SortIn[0].DISP=SHR,KEEP,KEEP
McsfsortSort015SortIn0RecordType=FB
McsfsortSort015SortIn0RecordLen=100
#STEP:SORT015| PGM:SORT| DD:SORTJNF2
McsfsortSort015SortIn[1]=CLOUDFRM.MC.SORT.S015JNF2
McsfsortSort015SortIn[1].DISP=SHR,KEEP,KEEP
McsfsortSort015SortIn1RecordType=FB
McsfsortSort015SortIn1RecordLen=100
#STEP:SORT015| PGM:SORT| DD:SORTOUT
McsfsortSort015SortOut=CLOUDFRM.MC.SORT.OUT015
McsfsortSort015SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort015SortOutRecordType=FB
McsfsortSort015SortOutRecordLen=200
#STEP:SORT016| PGM:SORT| DD:FILE01
McsfsortSort016SortIn[0]=CLOUDFRM.MC.SORT.S016JNF1
McsfsortSort016SortIn[0].DISP=SHR,KEEP,KEEP
McsfsortSort016SortIn0RecordType=FB
McsfsortSort016SortIn0RecordLen=50
#STEP:SORT016| PGM:SORT| DD:FILE02
McsfsortSort016SortIn[1]=CLOUDFRM.MC.SORT.S016JNF2
McsfsortSort016SortIn[1].DISP=SHR,KEEP,KEEP
McsfsortSort016SortIn1RecordType=FB
McsfsortSort016SortIn1RecordLen=50
#STEP:SORT016| PGM:SORT| DD:SORTMTCH
McsfsortSort016SortOut[0]=CLOUDFRM.MC.SORT.OUT016.SORTMTCH
McsfsortSort016SortOut[0].DISP=NEW,KEEP,KEEP
McsfsortSort016SortOut0RecordType=FB
McsfsortSort016SortOut0RecordLen=50
#STEP:SORT016| PGM:SORT| DD:SORTUN01
McsfsortSort016SortOut[1]=CLOUDFRM.MC.SORT.OUT016.SORTUN01
McsfsortSort016SortOut[1].DISP=NEW,KEEP,KEEP
McsfsortSort016SortOut1RecordType=FB
McsfsortSort016SortOut1RecordLen=50
#STEP:SORT016| PGM:SORT| DD:SORTUN02
McsfsortSort016SortOut[2]=CLOUDFRM.MC.SORT.OUT016.SORTUN02
McsfsortSort016SortOut[2].DISP=NEW,KEEP,KEEP
McsfsortSort016SortOut2RecordType=FB
McsfsortSort016SortOut2RecordLen=50
#STEP:SORT017| PGM:SORT| DD:SORTJNF1
McsfsortSort017SortIn[0]=CLOUDFRM.MC.SORT.S017JNF1
McsfsortSort017SortIn[0].DISP=SHR,KEEP,KEEP
McsfsortSort017SortIn0RecordType=FB
McsfsortSort017SortIn0RecordLen=100
#STEP:SORT017| PGM:SORT| DD:SORTJNF2
McsfsortSort017SortIn[1]=CLOUDFRM.MC.SORT.S017JNF2
McsfsortSort017SortIn[1].DISP=SHR,KEEP,KEEP
McsfsortSort017SortIn1RecordType=FB
McsfsortSort017SortIn1RecordLen=100
#STEP:SORT017| PGM:SORT| DD:SORTOUT
McsfsortSort017SortOut=CLOUDFRM.MC.SORT.OUT017
McsfsortSort017SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort017SortOutRecordType=FB
McsfsortSort017SortOutRecordLen=200
#STEP:SORT018| PGM:SORT| DD:SORTJNF1
McsfsortSort018SortIn[0]=CLOUDFRM.MC.SORT.S018JNF1
McsfsortSort018SortIn[0].DISP=SHR,KEEP,KEEP
McsfsortSort018SortIn0RecordType=FB
McsfsortSort018SortIn0RecordLen=100
#STEP:SORT018| PGM:SORT| DD:SORTJNF2
McsfsortSort018SortIn[1]=CLOUDFRM.MC.SORT.S018JNF2
McsfsortSort018SortIn[1].DISP=SHR,KEEP,KEEP
McsfsortSort018SortIn1RecordType=FB
McsfsortSort018SortIn1RecordLen=100
#STEP:SORT018| PGM:SORT| DD:SORTOUT
McsfsortSort018SortOut=CLOUDFRM.MC.SORT.OUT018
McsfsortSort018SortOut.DISP=NEW,KEEP,KEEP
McsfsortSort018SortOutRecordType=FB
McsfsortSort018SortOutRecordLen=200
