#project-specific-properties
#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
DB2FUNC.Scanner=SYSIN.bin
DB2FUNC.ScannerCharSet=cp1047
DB2FUNC.ScannerCRLFflag=no
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=Y                    *
#logging.level.com.cloudframe=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
#Common db properties
spring.datasource.initialization-mode=embedded
spring.jpa.hibernate.ddl-auto=update
spring.jdbc.template.fetch-size=1000
#spring.datasource.autocommit=false
#db2 specific properties
spring.db2.enabled=true
spring.datasource.jdbc-url=jdbc:db2://sysh.cloudframe.com:5040/DALLASC:currentSchema=CLOUDFRM;currentFunctionPath=CLOUDFRM;dateFormat=1;timeFormat=1;timestampFormat=1;timestampPrecisionReporting=2;
spring.datasource.driverClassName=com.ibm.db2.jcc.DB2Driver
spring.datasource.username=QAUSER
spring.datasource.password=cloud04
#end of db2
HIGH_VALUE=Z
# 
# End of DB2FUNC
