#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
#logging.level.com.cloudframe=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
#
SyncsortSort1SortIn=CLOUDFRM.JPM.SORT.INPUT1
SyncsortSort1SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort1SortInRecordType=FB
SyncsortSort1SortInRecordLen=200
#
SyncsortSort1SortOut=CLOUDFRM.JPM.SORT.OUTPUT1
SyncsortSort1SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort1SortOutRecordType=FB
SyncsortSort1SortOutRecordLen=200
#End of SORT1 step for SORT
#
SyncsortSort2SortIn=CLOUDFRM.JPM.SORT.INPUT2
SyncsortSort2SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort2SortInRecordType=FB
SyncsortSort2SortInRecordLen=200
#
SyncsortSort2SortOut=CLOUDFRM.JPM.SORT.OUTPUT2
SyncsortSort2SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort2SortOutRecordType=FB
SyncsortSort2SortOutRecordLen=200
#End of SORT2 step for SORT
#
SyncsortSort3SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort3SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort3SortInRecordType=FB
SyncsortSort3SortInRecordLen=200
#
SyncsortSort3SortOut=CLOUDFRM.JPM.SORT.OUTPUT3
SyncsortSort3SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort3SortOutRecordType=FB
SyncsortSort3SortOutRecordLen=200
#End of SORT3 step for SORT
#
SyncsortSort4SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort4SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort4SortInRecordType=FB
SyncsortSort4SortInRecordLen=200
#
SyncsortSort4SortOut=CLOUDFRM.JPM.SORT.OUTPUT4
SyncsortSort4SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort4SortOutRecordType=FB
SyncsortSort4SortOutRecordLen=200
#End of SORT4 step for SORT
#
SyncsortSort5SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort5SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort5SortInRecordType=FB
SyncsortSort5SortInRecordLen=200
#
SyncsortSort5SortOut=CLOUDFRM.JPM.SORT.OUTPUT5
SyncsortSort5SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort5SortOutRecordType=FB
SyncsortSort5SortOutRecordLen=200
#End of SORT5 step for SORT
#
SyncsortSort6SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort6SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort6SortInRecordType=FB
SyncsortSort6SortInRecordLen=200
#
SyncsortSort6SortOut=CLOUDFRM.JPM.SORT.OUTPUT6
SyncsortSort6SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort6SortOutRecordType=FB
SyncsortSort6SortOutRecordLen=9
#End of SORT6 step for SORT
#
SyncsortSort7SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort7SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort7SortInRecordType=FB
SyncsortSort7SortInRecordLen=200
#
SyncsortSort7SortOut=CLOUDFRM.JPM.SORT.OUTPUT7
SyncsortSort7SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort7SortOutRecordType=FB
SyncsortSort7SortOutRecordLen=200
#End of SORT7 step for SORT
#
SyncsortSort8SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort8SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort8SortInRecordType=FB
SyncsortSort8SortInRecordLen=200
#
SyncsortSort8SortOut=CLOUDFRM.JPM.SORT.OUTPUT8
SyncsortSort8SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort8SortOutRecordType=FB
SyncsortSort8SortOutRecordLen=12
#End of SORT8 step for SORT
#
SyncsortSort9SortIn=CLOUDFRM.JPM.SORT.INPUT9
SyncsortSort9SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort9SortInRecordType=FB
SyncsortSort9SortInRecordLen=52
#
SyncsortSort9SortOut=CLOUDFRM.JPM.SORT.OUTPUT9
SyncsortSort9SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort9SortOutRecordType=FB
SyncsortSort9SortOutRecordLen=8
#End of SORT9 step for SORT
#
SyncsortSort10SortIn=CLOUDFRM.JPM.SORT.INPUT10
SyncsortSort10SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort10SortInRecordType=FB
SyncsortSort10SortInRecordLen=52
#
SyncsortSort10SortOut=CLOUDFRM.JPM.SORT.OUTPUT10
SyncsortSort10SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort10SortOutRecordType=FB
SyncsortSort10SortOutRecordLen=52
#End of SORT10 step for SORT
#
SyncsortSort11SortIn=CLOUDFRM.JPM.SORT.INPUT11
SyncsortSort11SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort11SortInRecordType=FB
SyncsortSort11SortInRecordLen=52
#
SyncsortSort11SortOut=CLOUDFRM.JPM.SORT.OUTPUT11
SyncsortSort11SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort11SortOutRecordType=FB
SyncsortSort11SortOutRecordLen=11
#End of SORT11 step for SORT
#
SyncsortSort12SortIn=CLOUDFRM.JPM.SORT.INPUT12
SyncsortSort12SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort12SortInRecordType=FB
SyncsortSort12SortInRecordLen=52
#
SyncsortSort12SortOut=CLOUDFRM.JPM.SORT.OUTPUT12
SyncsortSort12SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort12SortOutRecordType=FB
SyncsortSort12SortOutRecordLen=52
#End of SORT12 step for SORT
#
SyncsortSort13SortIn=CLOUDFRM.JPM.SORT.INPUT13
SyncsortSort13SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort13SortInRecordType=FB
SyncsortSort13SortInRecordLen=52
#
SyncsortSort13SortOut=CLOUDFRM.JPM.SORT.OUTPUT13
SyncsortSort13SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort13SortOutRecordType=FB
SyncsortSort13SortOutRecordLen=52
#End of SORT13 step for SORT
#
SyncsortSort14SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort14SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort14SortInRecordType=FB
SyncsortSort14SortInRecordLen=200
#
SyncsortSort14SortOut=CLOUDFRM.JPM.SORT.OUTPUT14
SyncsortSort14SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort14SortOutRecordType=FB
SyncsortSort14SortOutRecordLen=200
#End of SORT14 step for SORT
#
SyncsortSort15SortIn[0]=CLOUDFRM.JPM.SORT.INPUT151
SyncsortSort15SortIn[0].DISP=SHR,KEEP,KEEP
SyncsortSort15SortIn[1]=CLOUDFRM.JPM.SORT.INPUT152
SyncsortSort15SortIn[1].DISP=SHR,KEEP,KEEP
SyncsortSort15SortInRecordType=FB
SyncsortSort15SortInRecordLen=200
#
SyncsortSort15SortOut=CLOUDFRM.JPM.SORT.OUTPUT15
SyncsortSort15SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort15SortOutRecordType=FB
SyncsortSort15SortOutRecordLen=200
#End of SORT15 step for SORT
#
SyncsortSort16SortIn[0]=CLOUDFRM.JPM.SORT.INPUT161
SyncsortSort16SortIn[0].DISP=SHR,KEEP,KEEP
SyncsortSort16SortIn[1]=CLOUDFRM.JPM.SORT.INPUT162
SyncsortSort16SortIn[1].DISP=SHR,KEEP,KEEP
SyncsortSort16SortIn[2]=CLOUDFRM.JPM.SORT.INPUT163
SyncsortSort16SortIn[2].DISP=SHR,KEEP,KEEP
SyncsortSort16SortInRecordType=FB
SyncsortSort16SortInRecordLen=200
#
SyncsortSort16SortOut=CLOUDFRM.JPM.SORT.OUTPUT16
SyncsortSort16SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort16SortOutRecordType=FB
SyncsortSort16SortOutRecordLen=200
#End of SORT16 step for SORT
#
SyncsortSort18SortIn=CLOUDFRM.JPM.SORT.INPUT18
SyncsortSort18SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort18SortInRecordType=FB
SyncsortSort18SortInRecordLen=52
#
SyncsortSort18SortOut=CLOUDFRM.JPM.SORT.OUTPUT18
SyncsortSort18SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort18SortOutRecordType=FB
SyncsortSort18SortOutRecordLen=40
#End of SORT18 step for SORT
#
SyncsortSort19SortIn=CLOUDFRM.JPM.SORT.INPUT19
SyncsortSort19SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort19SortInRecordType=FB
SyncsortSort19SortInRecordLen=200
#
SyncsortSort19SortOut=CLOUDFRM.JPM.SORT.OUTPUT19
SyncsortSort19SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort19SortOutRecordType=FB
SyncsortSort19SortOutRecordLen=300
#End of SORT19 step for SORT
#
SyncsortSort20SortIn=CLOUDFRM.JPM.SORT.INPUT20
SyncsortSort20SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort20SortInRecordType=FB
SyncsortSort20SortInRecordLen=52
#
SyncsortSort20SortOut=CLOUDFRM.JPM.SORT.OUTPUT20
SyncsortSort20SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort20SortOutRecordType=FB
SyncsortSort20SortOutRecordLen=9
#End of SORT20 step for SORT
#
cf.sort.useTempFile=no
