#STEP:SORT1| PGM:SYNCSORT| DD:SORTIN
SyncsortSort1SortIn=CLOUDFRM.JPM.SORT.INPUT1
SyncsortSort1SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort1SortInRecordType=FB
SyncsortSort1SortInRecordLen=<recordLen>
#STEP:SORT1| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort1SortOut=CLOUDFRM.JPM.SORT.OUTPUT1
SyncsortSort1SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort1SortOutRecordType=FB
SyncsortSort1SortOutRecordLen=<recordLen>
#STEP:SORT2| PGM:SYNCSORT| DD:SORTIN
SyncsortSort2SortIn=CLOUDFRM.JPM.SORT.INPUT2
SyncsortSort2SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort2SortInRecordType=FB
SyncsortSort2SortInRecordLen=<recordLen>
#STEP:SORT2| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort2SortOut=CLOUDFRM.JPM.SORT.OUTPUT2
SyncsortSort2SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort2SortOutRecordType=FB
SyncsortSort2SortOutRecordLen=<recordLen>
#STEP:SORT3| PGM:SYNCSORT| DD:SORTIN
SyncsortSort3SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort3SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort3SortInRecordType=FB
SyncsortSort3SortInRecordLen=<recordLen>
#STEP:SORT3| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort3SortOut=CLOUDFRM.JPM.SORT.OUTPUT3
SyncsortSort3SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort3SortOutRecordType=FB
SyncsortSort3SortOutRecordLen=<recordLen>
#STEP:SORT4| PGM:SYNCSORT| DD:SORTIN
SyncsortSort4SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort4SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort4SortInRecordType=FB
SyncsortSort4SortInRecordLen=<recordLen>
#STEP:SORT4| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort4SortOut=CLOUDFRM.JPM.SORT.OUTPUT4
SyncsortSort4SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort4SortOutRecordType=FB
SyncsortSort4SortOutRecordLen=<recordLen>
#STEP:SORT5| PGM:SYNCSORT| DD:SORTIN
SyncsortSort5SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort5SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort5SortInRecordType=FB
SyncsortSort5SortInRecordLen=<recordLen>
#STEP:SORT5| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort5SortOut=CLOUDFRM.JPM.SORT.OUTPUT5
SyncsortSort5SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort5SortOutRecordType=FB
SyncsortSort5SortOutRecordLen=<recordLen>
#STEP:SORT6| PGM:SYNCSORT| DD:SORTIN
SyncsortSort6SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort6SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort6SortInRecordType=FB
SyncsortSort6SortInRecordLen=<recordLen>
#STEP:SORT6| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort6SortOut=CLOUDFRM.JPM.SORT.OUTPUT6
SyncsortSort6SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort6SortOutRecordType=FB
SyncsortSort6SortOutRecordLen=<recordLen>
#STEP:SORT7| PGM:SYNCSORT| DD:SORTIN
SyncsortSort7SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort7SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort7SortInRecordType=FB
SyncsortSort7SortInRecordLen=<recordLen>
#STEP:SORT7| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort7SortOut=CLOUDFRM.JPM.SORT.OUTPUT7
SyncsortSort7SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort7SortOutRecordType=FB
SyncsortSort7SortOutRecordLen=<recordLen>
#STEP:SORT8| PGM:SYNCSORT| DD:SORTIN
SyncsortSort8SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort8SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort8SortInRecordType=FB
SyncsortSort8SortInRecordLen=<recordLen>
#STEP:SORT8| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort8SortOut=CLOUDFRM.JPM.SORT.OUTPUT8
SyncsortSort8SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort8SortOutRecordType=FB
SyncsortSort8SortOutRecordLen=<recordLen>
#STEP:SORT9| PGM:SYNCSORT| DD:SORTIN
SyncsortSort9SortIn=CLOUDFRM.JPM.SORT.INPUT9
SyncsortSort9SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort9SortInRecordType=FB
SyncsortSort9SortInRecordLen=<recordLen>
#STEP:SORT9| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort9SortOut=CLOUDFRM.JPM.SORT.OUTPUT9
SyncsortSort9SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort9SortOutRecordType=FB
SyncsortSort9SortOutRecordLen=<recordLen>
#STEP:SORT10| PGM:SYNCSORT| DD:SORTIN
SyncsortSort10SortIn=CLOUDFRM.JPM.SORT.INPUT10
SyncsortSort10SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort10SortInRecordType=FB
SyncsortSort10SortInRecordLen=<recordLen>
#STEP:SORT10| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort10SortOut=CLOUDFRM.JPM.SORT.OUTPUT10
SyncsortSort10SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort10SortOutRecordType=FB
SyncsortSort10SortOutRecordLen=<recordLen>
#STEP:SORT11| PGM:SYNCSORT| DD:SORTIN
SyncsortSort11SortIn=CLOUDFRM.JPM.SORT.INPUT11
SyncsortSort11SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort11SortInRecordType=FB
SyncsortSort11SortInRecordLen=<recordLen>
#STEP:SORT11| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort11SortOut=CLOUDFRM.JPM.SORT.OUTPUT11
SyncsortSort11SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort11SortOutRecordType=FB
SyncsortSort11SortOutRecordLen=<recordLen>
#STEP:SORT12| PGM:SYNCSORT| DD:SORTIN
SyncsortSort12SortIn=CLOUDFRM.JPM.SORT.INPUT12
SyncsortSort12SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort12SortInRecordType=FB
SyncsortSort12SortInRecordLen=<recordLen>
#STEP:SORT12| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort12SortOut=CLOUDFRM.JPM.SORT.OUTPUT12
SyncsortSort12SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort12SortOutRecordType=FB
SyncsortSort12SortOutRecordLen=<recordLen>
#STEP:SORT13| PGM:SYNCSORT| DD:SORTIN
SyncsortSort13SortIn=CLOUDFRM.JPM.SORT.INPUT13
SyncsortSort13SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort13SortInRecordType=FB
SyncsortSort13SortInRecordLen=<recordLen>
#STEP:SORT13| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort13SortOut=CLOUDFRM.JPM.SORT.OUTPUT13
SyncsortSort13SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort13SortOutRecordType=FB
SyncsortSort13SortOutRecordLen=<recordLen>
#STEP:SORT14| PGM:SYNCSORT| DD:SORTIN
SyncsortSort14SortIn=CLOUDFRM.JPM.SORT.INPUT
SyncsortSort14SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort14SortInRecordType=FB
SyncsortSort14SortInRecordLen=<recordLen>
#STEP:SORT14| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort14SortOut=CLOUDFRM.JPM.SORT.OUTPUT14
SyncsortSort14SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort14SortOutRecordType=FB
SyncsortSort14SortOutRecordLen=<recordLen>
#STEP:SORT15| PGM:SYNCSORT| DD:SORTIN
SyncsortSort15SortIn[0]=CLOUDFRM.JPM.SORT.INPUT151
SyncsortSort15SortIn[0].DISP=SHR,KEEP,KEEP
SyncsortSort15SortIn0RecordType=FB
SyncsortSort15SortIn0RecordLen=<recordLen>
#STEP:SORT15| PGM:SYNCSORT| DD:SORTIN
SyncsortSort15SortIn[1]=CLOUDFRM.JPM.SORT.INPUT152
SyncsortSort15SortIn[1].DISP=SHR,KEEP,KEEP
SyncsortSort15SortIn1RecordType=FB
SyncsortSort15SortIn1RecordLen=<recordLen>
#STEP:SORT15| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort15SortOut=CLOUDFRM.JPM.SORT.OUTPUT15
SyncsortSort15SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort15SortOutRecordType=FB
SyncsortSort15SortOutRecordLen=<recordLen>
#STEP:SORT16| PGM:SYNCSORT| DD:SORTIN
SyncsortSort16SortIn[0]=CLOUDFRM.JPM.SORT.INPUT161
SyncsortSort16SortIn[0].DISP=SHR,KEEP,KEEP
SyncsortSort16SortIn0RecordType=FB
SyncsortSort16SortIn0RecordLen=<recordLen>
#STEP:SORT16| PGM:SYNCSORT| DD:SORTIN
SyncsortSort16SortIn[1]=CLOUDFRM.JPM.SORT.INPUT162
SyncsortSort16SortIn[1].DISP=SHR,KEEP,KEEP
SyncsortSort16SortIn1RecordType=FB
SyncsortSort16SortIn1RecordLen=<recordLen>
#STEP:SORT16| PGM:SYNCSORT| DD:SORTIN
SyncsortSort16SortIn[2]=CLOUDFRM.JPM.SORT.INPUT163
SyncsortSort16SortIn[2].DISP=SHR,KEEP,KEEP
SyncsortSort16SortIn2RecordType=FB
SyncsortSort16SortIn2RecordLen=<recordLen>
#STEP:SORT16| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort16SortOut=CLOUDFRM.JPM.SORT.OUTPUT16
SyncsortSort16SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort16SortOutRecordType=FB
SyncsortSort16SortOutRecordLen=<recordLen>
#STEP:SORT18| PGM:SYNCSORT| DD:SORTIN
SyncsortSort18SortIn=CLOUDFRM.JPM.SORT.INPUT18
SyncsortSort18SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort18SortInRecordType=FB
SyncsortSort18SortInRecordLen=<recordLen>
#STEP:SORT18| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort18SortOut=CLOUDFRM.JPM.SORT.OUTPUT18
SyncsortSort18SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort18SortOutRecordType=FB
SyncsortSort18SortOutRecordLen=<recordLen>
#STEP:SORT19| PGM:SYNCSORT| DD:SORTIN
SyncsortSort19SortIn=CLOUDFRM.JPM.SORT.INPUT19
SyncsortSort19SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort19SortInRecordType=FB
SyncsortSort19SortInRecordLen=<recordLen>
#STEP:SORT19| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort19SortOut=CLOUDFRM.JPM.SORT.OUTPUT19
SyncsortSort19SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort19SortOutRecordType=FB
SyncsortSort19SortOutRecordLen=<recordLen>
#STEP:SORT20| PGM:SYNCSORT| DD:SORTIN
SyncsortSort20SortIn=CLOUDFRM.JPM.SORT.INPUT20
SyncsortSort20SortIn.DISP=SHR,KEEP,KEEP
SyncsortSort20SortInRecordType=FB
SyncsortSort20SortInRecordLen=<recordLen>
#STEP:SORT20| PGM:SYNCSORT| DD:SORTOUT
SyncsortSort20SortOut=CLOUDFRM.JPM.SORT.OUTPUT20
SyncsortSort20SortOut.DISP=NEW,KEEP,KEEP
SyncsortSort20SortOutRecordType=FB
SyncsortSort20SortOutRecordLen=<recordLen>
