package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.utility.CFUtil;
import com.cloudframe.app.data.Field;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] SPACE_4 = CFUtil.fillSpaces(4);
public static final char[] SPACE_2 = CFUtil.fillSpaces(2);
public static final char[] SPACE_27973 = CFUtil.fillSpaces(27973);
public static final char[] SPACE_32730 = CFUtil.fillSpaces(32730);
public static final char[] SPACE_8 = CFUtil.fillSpaces(8);
public static final char[] SPACE_7 = CFUtil.fillSpaces(7);
public static final char[] SPACE_9 = CFUtil.fillSpaces(9);
public static final char[] SPACE_17 = CFUtil.fillSpaces(17);
public static final char[] SPACE_10 = CFUtil.fillSpaces(10);
public static final char[] FORMAT1311677340 = "X(08)BX(08)".toCharArray();
public static final char[] FORMAT_1027795424 = "99BB".toCharArray();
public static final char[] FORMAT_33154069 = "99/".toCharArray();
public static final char[] FORMAT_33154658 = "99B".toCharArray();
public static final char[] HIGH_VALUE_1464863615 = Field.fillHighValue(10504);
public static final char[] HIGH_VALUE_STRING = Field.fillHighValue(1);
public static final char[] LITERAL_1807325697 = "10/30/2100.01.21".toCharArray();
 
}
