# Program  : UHDYNSQL | DD : SYSIN | RecordFormat : FixedLength | RecordLength : 80
UHDYNSQL.Scanner=SYSIN.bin
UHDYNSQL.ScannerCharSet=cp1047
UHDYNSQL.ScannerCRLFflag=no
UHDYNSQL.dbQualifier=
# 
# End of UHDYNSQL
