#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
#logging.level.com.cloudframe=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
# 
# End of MCVSAM1
CFBOOKS.Scanner=SYSIN.bin
CFBOOKS.ScannerCharSet=cp1047
CFBOOKS.ScannerCRLFflag=no
timeZoneId=Etc/GMT
CFBOOKS.ddname.REPOP=SYSOUT.txt
CFBOOKS.RepOp=SYSOUT.txt
CFBOOKS.RepOpCharSet=utf-8
CFBOOKS.RepOpCRLFflag=yes
#Common db properties
spring.datasource.initialization-mode=embedded
spring.jpa.hibernate.ddl-auto=update
spring.jdbc.template.fetch-size=1000
spring.datasource.maximum-pool-size=1
#spring.datasource.autocommit=false
#db2 specific properties
spring.db2.enabled=true
spring.datasource.jdbc-url=jdbc:db2://sysh.cloudframe.com:5040/DALLASC:currentSchema=CLOUDFRM;
spring.datasource.driverClassName=com.ibm.db2.jcc.DB2Driver
spring.datasource.username=QAUSER
spring.datasource.password=CLOUD04
#end of db2
# End of CFBOOKS
MCVSAM2.ddname.SYS001=IRDEXTR
TEST.MCVSAM2.ddname.SYS001=IRDEXTR
#Vsam specific db properties (h2)
spring.cf.db.enabled=true
spring.cf.db.jdbc-url=jdbc:h2:file:./cf-vsam-db;DEFRAG_ALWAYS=true;
spring.cf.db.driverClassName=org.h2.Driver
spring.cf.db.username=sa
spring.cf.db.password=
#spring.cf.fetch-size=500
#uncomment below property to disable in-memory load of VSAM
#cf.vsam.load.inmemory=false
#end of h2
# End of MCVSAM2
Mcvsam1Step01SortIn=CLOUDFRM.DEMO.CFCARD.INPUT.FILE.UNSORTED
Mcvsam1Step01SortInRecordType=FB
Mcvsam1Step01SortInRecordLen=44
#
Mcvsam1Step01SortOut=CLOUDFRM.DEMO.CFCARD.INPUT.FILE.SORTED
Mcvsam1Step01SortOutRecordType=FB
Mcvsam1Step01SortOutRecordLen=44
#
cf.sort.useTempFile=no
#
## batch
#sprint.batch.datasource.enabled=true
#sprint.batch.datasource.jdbcUrl=jdbc:h2:file:./cf-db;DEFRAG_ALWAYS=true;
#sprint.batch.datasource.driverClassName=org.h2.Driver
#sprint.batch.datasource.username=sa
#sprint.batch.datasource.password=
