#STEP:STEP01| PGM:SORT| DD:SORTIN
Jclsortcobolvsamdb2Step01SortIn=CLOUDFRM.DEMO.CFCARD.INPUT.FILE.UNSORTED
Jclsortcobolvsamdb2Step01SortIn.DISP=SHR,KEEP,KEEP
Jclsortcobolvsamdb2Step01SortInRecordType=FB
Jclsortcobolvsamdb2Step01SortInRecordLen=<recordLen>
#STEP:STEP01| PGM:SORT| DD:SORTOUT
Jclsortcobolvsamdb2Step01SortOut=CLOUDFRM.DEMO.CFCARD.INPUT.FILE.SORTED
Jclsortcobolvsamdb2Step01SortOut.DISP=SHR,KEEP,KEEP
Jclsortcobolvsamdb2Step01SortOutRecordType=FB
Jclsortcobolvsamdb2Step01SortOutRecordLen=<recordLen>
