#STEP:STEP003| PGM:IEBGENER| DD:SYSUT1
STEP003.IEBGENER.Sysut1=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(0)
STEP003.IEBGENER.Sysut1.DISP=SHR,KEEP,KEEP
STEP003.IEBGENER.Sysut1.RecordType=FB
STEP003.IEBGENER.Sysut1.RecordLen=80
#
#STEP:STEP003| PGM:IEBGENER| DD:SYSUT2
STEP003.IEBGENER.Sysut2=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(+1)
STEP003.IEBGENER.Sysut2.DISP=NEW,CATLG,DELETE
STEP003.IEBGENER.Sysut2.RecordType=FB
STEP003.IEBGENER.Sysut2.RecordLen=80
#
