#STEP:STEP015| PGM:SORT| DD:SORTIN
Sup1447Step015SortIn[0]=DTF.SI.P2BX.BULK.TYPES.TRNSPRT.MATCH
Sup1447Step015SortIn[0].DISP=SHR,KEEP,KEEP
Sup1447Step015SortIn0RecordType=FB
Sup1447Step015SortIn0RecordLen=58
#STEP:STEP015| PGM:SORT| DD:SORTIN
Sup1447Step015SortIn[1]=DTF.SI.P2BX.BULK.TYPES.TRNSPRT.UNMATCH
Sup1447Step015SortIn[1].DISP=SHR,KEEP,KEEP
Sup1447Step015SortIn1RecordType=FB
Sup1447Step015SortIn1RecordLen=58
#STEP:STEP015| PGM:SORT| DD:SORTOUT
Sup1447Step015SortOut=STEP015.SUP1447.SYSOUT
Sup1447Step015SortOutRecordType=FB
Sup1447Step015SortOutRecordLen=133
