# Program IP650010 | DD : SYS007 | VSAM KSDS
IP650010.ddname.SYS007=Sys007OptimizedParmFile
# 
# End of IP650010
# Program IP661020 | DD : SYS003 | RecordFormat : VariableLength | MaxRecordLength : 32756
IP661020.ddname.SYS003=IpmFile
IP661020.IpmFile=IpmFile
IP661020.IpmFileCharSet=cp1047
IP661020.IpmFileCRLFflag=no
# End of IP661020
timeZoneId=Etc/GMT
# End of IP662010
# End of IP739010
# End of IP741010
