#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
spring.main.allow-circular-references=true
#update the inputValue below, that has to be passed to the application, if running as a stand alone
IOVB32K.ddname.INDD=DUMMY
IOVB32K.InFile=DUMMY
WRITEVB.IOVB32K.InFile=DUMMY
READVB.IOVB32K.InFile=QA.QA000120.CLF.OUT.CF
READVB.IOVB32K.InFile.DISP=SHR,KEEP,KEEP
IOVB32K.InFileCharSet=utf-8
IOVB32K.InFileCRLFflag=yes
IOVB32K.ddname.OUTDD=QA.QA000120.CLF.OUT.CF
IOVB32K.OutFile=QA.QA000120.CLF.OUT.CF
WRITEVB.IOVB32K.OutFile=QA.QA000120.CLF.OUT.CF
WRITEVB.IOVB32K.OutFile.DISP=NEW,CATLG,CATLG
READVB.IOVB32K.OutFile=DUMMY
IOVB32K.OutFileCharSet=utf-8
IOVB32K.OutFileCRLFflag=yes
#logging.level.com.cloudframe=DEBUG
logging.file.name=console-IOVB32K.log
logging.pattern.file=%msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
# 
# End of IOVB32K
   
DELETE.IEFBR14.Sysout=QA.QA000120.CLF.SYSOUT.CF
DELETE.IEFBR14.Sysout.DISP=MOD,DELETE,DELETE
#End of DELETE step for IEFBR14
   
DELETE.IEFBR14.Outdd=QA.QA000120.CLF.OUT.CF
DELETE.IEFBR14.Outdd.DISP=MOD,DELETE,DELETE
#End of DELETE step for IEFBR14
