WRITEVB.IOVB32K.inputValue='W,32700,32750'
READVB.IOVB32K.inputValue='R,32700,32750'
#update the inputValue below, that has to be passed to the application, if running as a stand alone
# Program IOVB32K | DD : INDD | RecordFormat : VariableLength | MaxRecordLength : 32752
IOVB32K.ddname.INDD=DUMMY
IOVB32K.InFile=DUMMY
WRITEVB.IOVB32K.InFile=DUMMY
READVB.IOVB32K.InFile=QA.QA000120.CLF.OUT.MF
READVB.IOVB32K.InFile.DISP=SHR,KEEP,KEEP
IOVB32K.InFileCharSet=cp1047
IOVB32K.InFileCRLFflag=no
# Program IOVB32K | DD : OUTDD | RecordFormat : VariableLength | MaxRecordLength : 32752
IOVB32K.ddname.OUTDD=QA.QA000120.CLF.OUT.MF
IOVB32K.OutFile=QA.QA000120.CLF.OUT.MF
WRITEVB.IOVB32K.OutFile=QA.QA000120.CLF.OUT.MF
WRITEVB.IOVB32K.OutFile.DISP=NEW,CATLG,CATLG
READVB.IOVB32K.OutFile=DUMMY
IOVB32K.OutFileCharSet=cp1047
IOVB32K.OutFileCRLFflag=no
# 
# End of IOVB32K
