#STEP:DELETE| PGM:IEFBR14| DD:SYSOUT
DELETE.IEFBR14.Sysout=QA.QA000120.CLF.SYSOUT.MF
DELETE.IEFBR14.Sysout.DISP=MOD,DELETE,DELETE
#
#STEP:DELETE| PGM:IEFBR14| DD:OUTDD
DELETE.IEFBR14.Outdd=QA.QA000120.CLF.OUT.MF
DELETE.IEFBR14.Outdd.DISP=MOD,DELETE,DELETE
#
