#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
inputValue1=
inputValue2=
inputValue3=
inputValue4=
inputValue5=
# 
# End of CALLPRM1
# End of CALLPRM2
