  package com.cloudframe.app.process.impl;
  /* Java code generated by CloudFrame on 2025-04-28 at 08:00. */
  
  import com.cloudframe.app.mc081.Mc081Ctx.*;
  import com.cloudframe.app.mc081.Mc081Ctx;
  import com.cloudframe.app.process.Mc081;
  import com.cloudframe.app.process.BaseProcess;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.dto.GlobalExecutorCtx;
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.beans.factory.annotation.Qualifier;
  import com.cloudframe.app.mc081.file.*;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.data.Field;
  import com.cloudframe.app.mc081.dto.*;
  import com.cloudframe.app.mc081.file.records.FbRecordOut;
  import com.cloudframe.app.mc081.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("mc081")
  
  public class Mc081Impl extends CommonProcess implements Mc081 {
  
  Logger logger = LoggerFactory.getLogger(Mc081Impl.class);
  
  
  
  
  @Autowired 
  @Qualifier("mc081_fbFile")
  FbFile fbFile;
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output :  

      * - fbFileStatus                   COBOL Name: WS-FB-FILE-STATUS
      * - fbRecordOut                    COBOL Name: FB-RECORD-OUT
      * - fbBigRec                       COBOL Name: FB-BIG-REC
      *
      * @throws CFException
      */
      public int process(Mc081Ctx programCtx) throws Exception {
       try {
       setCodePage("1047");
            // Reset program ended flag
           programCtx.setProgramEnded(false);
ProcessOutCtx methodOut = programCtx.getProcessOutCtx();

// *
//  OPEN OUTPUT FB-FILE
          fbFile.open(new String(CONSTANTS.MODE_WRITE_ONLY_36397),fbFile.getFileName(),fbFile.getFbFileCharSet(),fbFile.getFbFileCrlfFlag());
          methodOut.setFbFileStatus(fbFile.getStatusString() );
//  IF NOT ( WS-FB-FILE-STATUS = ZERO)
          if ((!( allZeros(methodOut.getFbFileStatus()) ) /*  !=  zeros*/)) { 
//  DISPLAY 'FB-FILE OPEN FAILED' WS-FB-FILE-STATUS
              logger.info("FB-FILE OPEN FAILED{}", new String(methodOut.getFbFileStatus())); 
//  GOBACK
              setNotLogged(false); // no need to log, it is a normal termination
              programCtx.setProgramEnded(true);
              return programCtx.getRc();
          }
//  MOVE ALL 'A' TO FB-RECORD-OUT
          methodOut.getFbRecordOut().setString(CONSTANTS.LITERAL_551705848);
//  WRITE FB-RECORD-OUT
          fbFile.write(methodOut.getFbRecordOut().toCharArray()); 
          methodOut.getFbRecordOut().setString(CONSTANTS.LOW_VALUE_215751987);
          methodOut.setFbFileStatus(fbFile.getStatusString() );
//  MOVE ALL 'B' TO FB-RECORD-OUT
          methodOut.getFbRecordOut().setString(CONSTANTS.LITERAL_1257227880);
//  WRITE FB-RECORD-OUT
          fbFile.write(methodOut.getFbRecordOut().toCharArray()); 
          methodOut.getFbRecordOut().setString(CONSTANTS.LOW_VALUE_215751987);
          methodOut.setFbFileStatus(fbFile.getStatusString() );
          // MOVE ALL 'C' TO FB-BIG-REC
          methodOut.setFbBigRec(CONSTANTS.LITERAL_157397706);
//  WRITE FB-RECORD-OUT FROM FB-BIG-REC
          fbFile.write(methodOut.getFbBigRec()); 
          methodOut.getFbRecordOut().setString(CONSTANTS.LOW_VALUE_215751987);
          methodOut.setFbFileStatus(fbFile.getStatusString() );
//  CLOSE FB-FILE
          fbFile.close(); 
          methodOut.setFbFileStatus(fbFile.getStatusString() );
//  IF NOT ( WS-FB-FILE-STATUS = ZERO)
          if ((!( allZeros(methodOut.getFbFileStatus()) ) /*  !=  zeros*/)) { 
//  DISPLAY 'FB-FILE CLOSE FAILED' WS-FB-FILE-STATUS
              logger.info("FB-FILE CLOSE FAILED{}", new String(methodOut.getFbFileStatus())); 
//  GOBACK
              setNotLogged(false); // no need to log, it is a normal termination
              programCtx.setProgramEnded(true);
              return programCtx.getRc();
          }
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          programCtx.setProgramEnded(true);
          return programCtx.getRc();
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
        finally {
      		if(fbFile.hasOpened() && !fbFile.isReadOnly()) { 
      			fbFile.flush(); 
      		}
      }
      
      // end of process method
      }
  
  
  
  
  
  
  
  
  }
