#
#STEP:REPVSAM| PGM:IDCAMS| DD:FILEIN1
REPVSAM.IDCAMS.Filein1=CLOUDFRM.IDCAMS.PRINT.VSAMKSDS.INPUT
REPVSAM.IDCAMS.Filein1.DISP=SHR,KEEP,KEEP
REPVSAM.IDCAMS.Filein1.RecordType=FB
REPVSAM.IDCAMS.Filein1.RecordLen=281
#
#
#STEP:REPVSAM| PGM:IDCAMS| DD:FILEOUT1
REPVSAM.IDCAMS.Fileout1=CLOUDFRM_IDCAMS_PRINT_VSAMKSDS
#
#
#STEP:VSAMOUT| PGM:IDCAMS| DD:FILEIN1
VSAMOUT.IDCAMS.Filein1=CLOUDFRM_IDCAMS_PRINT_VSAMKSDS
#
#
#STEP:VSAMOUT| PGM:IDCAMS| DD:FILEOUT1
VSAMOUT.IDCAMS.Fileout1=CLOUDFRM.IDCAMS.PRINT.VSAMKSDS.OUTPUT
VSAMOUT.IDCAMS.Fileout1.DISP=NEW,DELETE,DELETE
VSAMOUT.IDCAMS.Fileout1.RecordType=FB
VSAMOUT.IDCAMS.Fileout1.RecordLen=<recordLen>
#
