package com.cloudframe.app.vsammon4.file;
/* Java Code Generated by CloudFrame */

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;
import com.cloudframe.app.utility.CFFileVsam;
import com.cloudframe.app.exception.CFException;
import com.cloudframe.app.vsammon4.file.keys.VsvksdsOutputKey;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import com.cloudframe.app.utility.CFConstants;
import com.cloudframe.app.vsammon4.file.records.*;

@Component("vsammon4_vsvksdsOutput")
public class VsvksdsOutput extends CFFileVsam {

	private Logger logger = LoggerFactory.getLogger(VsvksdsOutput.class);
	

	@Autowired 
	@Qualifier("vsammon4_vsvksdsOutputKey")
	VsvksdsOutputKey keyInfo;

	public VsvksdsOutput()
	{	
		setVariableBlockFile(true);
		setRecord(new byte[221]);	
		setAccessMode("DYNAMIC");
	}
	
	public void setVsamCluster(String pgmName)
	{
		setVsamCluster(pgmName,"VSVKSDSO",CFConstants.ACCESS_MODE_SEQUENTIAL.equals(getAccessMode()));
		setKeyInfo(keyInfo.getFileKeyInfoList());
	}

	

	public char[] getStatusString() {
		if (status == 0) return new char[]{'0','0'};
		else if (status == 23) return new char[]{'2','3'};
		else if (status == 10) return new char[]{'1','0'};
		return String.format("%1$2s", status+"").replace(' ', '0').toCharArray();
	}

	@Override
	public byte[] readNext() {
		try {
			record = super.readNext();
		} catch (CFException e) {
			printErrorLog(CFConstants.TEXT_READ, e.getMessage());  
		}
		return record;
	}
	

	

	@Override
	public void delete(int rrn) {
		try{
			super.delete(rrn);
		} catch (Exception e) {
			logger.error("Error during VsvksdsOutput delete: {}",e.getMessage() ); 		}
	}
	
	@Override
	public int getStatus() {
		if (status == CFConstants.END_OF_FILE)
			ended = true;
		return status;
	}
	
	public boolean hasEnded() {
		return ended;
	}
	
	public int getRecLen() {
		return recLen;
	}
	
	public VsvksdsOutputKey getKeyInfo() {
		return keyInfo;
	}
	
	@Override
	public String toString() {
		String recStr = "";
		if (record != null) {
			try {recStr = new String(record,CFConstants.EBCDIC_CHARSET);}
			catch(Exception e) {
				logger.error(e.getMessage());
			}
		}
		return recStr;
	}
	
	private void printErrorLog(String modeStr, String errMsg){
		logger.error("Error during VsvksdsOutput {}:{}",modeStr,errMsg); 
	}
}
