#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
spring.main.allow-circular-references=true
VSAMMON4.Scanner=SYSIN.bin
VSAMMON4.ScannerCharSet=cp1047
VSAMMON4.ScannerCRLFflag=no
VSAMMON4.ddname.VSVKSDSB=VSVKSDS_VSAMMON4
VSAMMON4.ddname.VSVKSDSI=VSVKSDS_VSAMMON4
VSAMMON4.ddname.REPOUT=Repout
VSAMMON4.Repout=REPOUT.CF
VSAMMON4.RepoutCharSet=cp1047
VSAMMON4.RepoutCRLFflag=no
VSAMMON4.ddname.VSVKSDSO=VSVKSDS_VSAMMON4
#logging.level.com.cloudframe=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
#Common db properties
spring.datasource.initialization-mode=embedded
spring.jpa.hibernate.ddl-auto=update
spring.jdbc.template.fetch-size=1000
spring.datasource.maximum-pool-size=1
#spring.datasource.autocommit=false
#Vsam specific db properties (h2)
spring.cf.db.enabled=true
spring.cf.db.jdbc-url=jdbc:h2:file:./cf-vsam-db;DEFRAG_ALWAYS=true;
spring.cf.db.driverClassName=org.h2.Driver
spring.cf.db.username=sa
spring.cf.db.password=
#spring.cf.fetch-size=500
#uncomment below property to disable in-memory load of VSAM
#cf.vsam.load.inmemory=false
#end of h2
HIGH_VALUE=Z
# 
# End of VSAMMON4
