package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.data.Field;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] LOW_VALUE_1253885741 = Field.fillLowValue(13);
public static final char[] LOW_VALUE_STRING = new String(new byte[]{0}).toCharArray();
 
}
