#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
spring.main.allow-circular-references=true
ASAPRNT4.ddname.REPOUT=Repout
ASAPRNT4.Repout=REPOUT.CF
ASAPRNT4.RepoutCharSet=utf-8
ASAPRNT4.RepoutCRLFflag=yes
#logging.level.com.cloudframe=DEBUG
logging.file.name=console-ASAPRNT4.log
logging.pattern.file=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
# 
# End of ASAPRNT4
