<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Work" cobol:name="work" cobol:offset="0" cobol:length="25" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Div" type="xs:long" maxOccurs="1"  cobol:name="WS-DIV" cobol:offset="0" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
    <xs:element name="Allow" maxOccurs="1"  cobol:name="WS-ALLOW" cobol:offset="6" cobol:length="7" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="OosuSharedAllow" maxOccurs="1"  cobol:name="WS-OOSU-SHARED-ALLOW" cobol:offset="13" cobol:length="7" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Rlu3aTotDataPromoAllow" maxOccurs="1"  cobol:name="LK-RLU3A-TOT-DATA-PROMO-ALLOW" cobol:offset="20" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="8" />
                  <xs:fractionDigits value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="CKilobyteNum" type="xs:int" maxOccurs="1"  cobol:name="C-KILOBYTE-NUM" cobol:offset="25" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
