package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.utility.CFUtil;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] SPACE_200 = CFUtil.fillSpaces(200);
public static final char[] SPACE_50 = CFUtil.fillSpaces(50);
public static final char[] SPACE_7000 = CFUtil.fillSpaces(7000);
public static final char[] FORMAT1016704244 = "-999".toCharArray();
public static final char[] LITERAL_1571420044 = ", WIDGET_MANU_PLANT, WIDGET_MANU_COST".toCharArray();
public static final char[] LITERAL_1832445661 = "SELECT WIDGET_NUM, WIDGET_COLOR, WIDGET_SIZE".toCharArray();
public static final char[] LITERAL_1894985001 = ", WIDGET_LEAD_TIME".toCharArray();
public static final char[] LITERAL_225636967 = ", WIDGET_PRICE, WIDGET_SUPPLIER, WIDGET_DESC".toCharArray();
public static final char[] LITERAL_B_HS_ = " #".toCharArray();
public static final char[] LITERAL_FROM_B_TBWIDGET = "FROM TBWIDGET".toCharArray();
public static final char[] LITERAL_HS_ = "#".toCharArray();
public static final char[] LITERAL_SIZE = "SIZE".toCharArray();
public static final char[] LITERAL_SQLDA_B3_ = "SQLDA   ".toCharArray();
public static final char[] LITERAL_UHDYNSQL = "UHDYNSQL".toCharArray();
 
}
