#STEP:SORT001| PGM:SORT| DD:SORTIN
McgcmsSort001SortIn=CLOUDFRM.MC.GCMS.SORT.IN001
McgcmsSort001SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort001SortInRecordType=FB
McgcmsSort001SortInRecordLen=7
#STEP:SORT001| PGM:SORT| DD:SORTOUT
McgcmsSort001SortOut=CLOUDFRM.MC.GCMS.SORT.OUT001
McgcmsSort001SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort001SortOutRecordType=FB
McgcmsSort001SortOutRecordLen=23
#STEP:SORT002| PGM:SORT| DD:SORTIN
McgcmsSort002SortIn=CLOUDFRM.MC.GCMS.SORT.IN002
McgcmsSort002SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort002SortInRecordType=FB
McgcmsSort002SortInRecordLen=130
#STEP:SORT002| PGM:SORT| DD:SORTOF1
McgcmsSort002SortOut[0]=CLOUDFRM.MC.GCMS.SORT.OUT0021
McgcmsSort002SortOut[0].DISP=NEW,KEEP,KEEP
McgcmsSort002SortOut0RecordType=FB
McgcmsSort002SortOut0RecordLen=80
#STEP:SORT002| PGM:SORT| DD:SORTOF2
McgcmsSort002SortOut[1]=CLOUDFRM.MC.GCMS.SORT.OUT0022
McgcmsSort002SortOut[1].DISP=NEW,KEEP,KEEP
McgcmsSort002SortOut1RecordType=FB
McgcmsSort002SortOut1RecordLen=164
#STEP:SORT002| PGM:SORT| DD:SORTOF3
McgcmsSort002SortOut[2]=CLOUDFRM.MC.GCMS.SORT.OUT0023
McgcmsSort002SortOut[2].DISP=NEW,KEEP,KEEP
McgcmsSort002SortOut2RecordType=FB
McgcmsSort002SortOut2RecordLen=164
#STEP:SORT003| PGM:SORT| DD:SORTIN
McgcmsSort003SortIn=CLOUDFRM.MC.GCMS.SORT.IN003
McgcmsSort003SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort003SortInRecordType=FB
McgcmsSort003SortInRecordLen=80
#STEP:SORT003| PGM:SORT| DD:SORTOUT
McgcmsSort003SortOut=CLOUDFRM.MC.GCMS.SORT.OUT003
McgcmsSort003SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort003SortOutRecordType=FB
McgcmsSort003SortOutRecordLen=24
#STEP:SORT004| PGM:SORT| DD:SORTIN
McgcmsSort004SortIn=CLOUDFRM.MC.GCMS.SORT.IN004
McgcmsSort004SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort004SortInRecordType=FB
McgcmsSort004SortInRecordLen=264
#STEP:SORT004| PGM:SORT| DD:SORTOF01
McgcmsSort004SortOut=CLOUDFRM.MC.GCMS.SORT.OUT004
McgcmsSort004SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort004SortOutRecordType=FB
McgcmsSort004SortOutRecordLen=264
#STEP:SORT005| PGM:SORT| DD:SORTIN
McgcmsSort005SortIn=CLOUDFRM.MC.GCMS.SORT.IN005
McgcmsSort005SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort005SortInRecordType=FB
McgcmsSort005SortInRecordLen=80
#STEP:SORT005| PGM:SORT| DD:SORTOUT
McgcmsSort005SortOut=CLOUDFRM.MC.GCMS.SORT.OUT005
McgcmsSort005SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort005SortOutRecordType=FB
McgcmsSort005SortOutRecordLen=80
#STEP:SORT006| PGM:SORT| DD:SORTIN
McgcmsSort006SortIn=CLOUDFRM.MC.GCMS.SORT.IN006
McgcmsSort006SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort006SortInRecordType=FB
McgcmsSort006SortInRecordLen=98
#STEP:SORT006| PGM:SORT| DD:SORTOF1
McgcmsSort006SortOut[0]=CLOUDFRM.MC.GCMS.SORT.OUT0061
McgcmsSort006SortOut[0].DISP=NEW,KEEP,KEEP
McgcmsSort006SortOut0RecordType=FB
McgcmsSort006SortOut0RecordLen=98
#STEP:SORT006| PGM:SORT| DD:SORTOF2
McgcmsSort006SortOut[1]=CLOUDFRM.MC.GCMS.SORT.OUT0062
McgcmsSort006SortOut[1].DISP=NEW,KEEP,KEEP
McgcmsSort006SortOut1RecordType=FB
McgcmsSort006SortOut1RecordLen=98
#STEP:SORT007| PGM:SORT| DD:SORTIN
McgcmsSort007SortIn=CLOUDFRM.MC.GCMS.SORT.IN007
McgcmsSort007SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort007SortInRecordType=FB
McgcmsSort007SortInRecordLen=126
#STEP:SORT007| PGM:SORT| DD:SORTOUT
McgcmsSort007SortOut=CLOUDFRM.MC.GCMS.SORT.OUT007
McgcmsSort007SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort007SortOutRecordType=FBA
McgcmsSort007SortOutRecordLen=150
#STEP:SORT008| PGM:SORT| DD:SORTJNF1
McgcmsSort008SortIn[0]=CLOUDFRM.MC.GCMS.SORT.IN0081
McgcmsSort008SortIn[0].DISP=SHR,KEEP,KEEP
McgcmsSort008SortIn0RecordType=FB
McgcmsSort008SortIn0RecordLen=102
#STEP:SORT008| PGM:SORT| DD:SORTJNF2
McgcmsSort008SortIn[1]=CLOUDFRM.MC.GCMS.SORT.IN0082
McgcmsSort008SortIn[1].DISP=SHR,KEEP,KEEP
McgcmsSort008SortIn1RecordType=FB
McgcmsSort008SortIn1RecordLen=95
#STEP:SORT008| PGM:SORT| DD:SORTOUT
McgcmsSort008SortOut=CLOUDFRM.MC.GCMS.SORT.OUT008
McgcmsSort008SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort008SortOutRecordType=FB
McgcmsSort008SortOutRecordLen=136
#STEP:SORT009| PGM:SORT| DD:SORTJNF1
McgcmsSort009SortIn[0]=CLOUDFRM.MC.GCMS.SORT.IN0091
McgcmsSort009SortIn[0].DISP=SHR,KEEP,KEEP
McgcmsSort009SortIn0RecordType=FB
McgcmsSort009SortIn0RecordLen=102
#STEP:SORT009| PGM:SORT| DD:SORTJNF2
McgcmsSort009SortIn[1]=CLOUDFRM.MC.GCMS.SORT.IN0092
McgcmsSort009SortIn[1].DISP=SHR,KEEP,KEEP
McgcmsSort009SortIn1RecordType=FB
McgcmsSort009SortIn1RecordLen=95
#STEP:SORT009| PGM:SORT| DD:SORTOUT
McgcmsSort009SortOut=CLOUDFRM.MC.GCMS.SORT.OUT009
McgcmsSort009SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort009SortOutRecordType=FB
McgcmsSort009SortOutRecordLen=136
#STEP:SORT010| PGM:SORT| DD:SORTIN
McgcmsSort010SortIn=CLOUDFRM.MC.GCMS.SORT.IN010
McgcmsSort010SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort010SortInRecordType=VB
McgcmsSort010SortInRecordLen=61
#STEP:SORT010| PGM:SORT| DD:SORTOF1
McgcmsSort010SortOut[0]=CLOUDFRM.MC.GCMS.SORT.OUT0101
McgcmsSort010SortOut[0].DISP=NEW,KEEP,KEEP
McgcmsSort010SortOut0RecordType=FBA
McgcmsSort010SortOut0RecordLen=56
#STEP:SORT010| PGM:SORT| DD:SORTOF2
McgcmsSort010SortOut[1]=CLOUDFRM.MC.GCMS.SORT.OUT0102
McgcmsSort010SortOut[1].DISP=NEW,KEEP,KEEP
McgcmsSort010SortOut1RecordType=FBA
McgcmsSort010SortOut1RecordLen=56
#STEP:SORT011| PGM:SORT| DD:SORTIN
McgcmsSort011SortIn=CLOUDFRM.MC.GCMS.SORT.IN011
McgcmsSort011SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort011SortInRecordType=FB
McgcmsSort011SortInRecordLen=38
#STEP:SORT011| PGM:SORT| DD:SORTOF1
McgcmsSort011SortOut[0]=CLOUDFRM.MC.GCMS.SORT.OUT0111
McgcmsSort011SortOut[0].DISP=NEW,KEEP,KEEP
McgcmsSort011SortOut0RecordType=FBA
McgcmsSort011SortOut0RecordLen=41
#STEP:SORT011| PGM:SORT| DD:SORTOF2
McgcmsSort011SortOut[1]=CLOUDFRM.MC.GCMS.SORT.OUT0112
McgcmsSort011SortOut[1].DISP=NEW,KEEP,KEEP
McgcmsSort011SortOut1RecordType=FBA
McgcmsSort011SortOut1RecordLen=41
#STEP:SORT011| PGM:SORT| DD:SORTOF3
McgcmsSort011SortOut[2]=CLOUDFRM.MC.GCMS.SORT.OUT0113
McgcmsSort011SortOut[2].DISP=NEW,KEEP,KEEP
McgcmsSort011SortOut2RecordType=FBA
McgcmsSort011SortOut2RecordLen=41
#STEP:SORT011| PGM:SORT| DD:SORTOF4
McgcmsSort011SortOut[3]=CLOUDFRM.MC.GCMS.SORT.OUT0114
McgcmsSort011SortOut[3].DISP=NEW,KEEP,KEEP
McgcmsSort011SortOut3RecordType=FBA
McgcmsSort011SortOut3RecordLen=41
#STEP:SORT011| PGM:SORT| DD:SORTOF5
McgcmsSort011SortOut[4]=CLOUDFRM.MC.GCMS.SORT.OUT0115
McgcmsSort011SortOut[4].DISP=NEW,KEEP,KEEP
McgcmsSort011SortOut4RecordType=FBA
McgcmsSort011SortOut4RecordLen=41
#STEP:SORT011| PGM:SORT| DD:SORTOF6
McgcmsSort011SortOut[5]=CLOUDFRM.MC.GCMS.SORT.OUT0116
McgcmsSort011SortOut[5].DISP=NEW,KEEP,KEEP
McgcmsSort011SortOut5RecordType=FBA
McgcmsSort011SortOut5RecordLen=41
#STEP:SORT011| PGM:SORT| DD:SORTOF7
McgcmsSort011SortOut[6]=CLOUDFRM.MC.GCMS.SORT.OUT0117
McgcmsSort011SortOut[6].DISP=NEW,KEEP,KEEP
McgcmsSort011SortOut6RecordType=FBA
McgcmsSort011SortOut6RecordLen=41
#STEP:SORT012| PGM:SORT| DD:SORTJNF1
McgcmsSort012SortIn[0]=CLOUDFRM.MC.GCMS.SORT.IN0121
McgcmsSort012SortIn[0].DISP=SHR,KEEP,KEEP
McgcmsSort012SortIn0RecordType=FB
McgcmsSort012SortIn0RecordLen=180
#STEP:SORT012| PGM:SORT| DD:SORTJNF2
McgcmsSort012SortIn[1]=CLOUDFRM.MC.GCMS.SORT.IN0122
McgcmsSort012SortIn[1].DISP=SHR,KEEP,KEEP
McgcmsSort012SortIn1RecordType=FB
McgcmsSort012SortIn1RecordLen=180
#STEP:SORT012| PGM:SORT| DD:SORTOF1
McgcmsSort012SortOut[0]=CLOUDFRM.MC.GCMS.SORT.OUT0121
McgcmsSort012SortOut[0].DISP=NEW,KEEP,KEEP
McgcmsSort012SortOut0RecordType=FB
McgcmsSort012SortOut0RecordLen=180
#STEP:SORT012| PGM:SORT| DD:SORTOF2
McgcmsSort012SortOut[1]=CLOUDFRM.MC.GCMS.SORT.OUT0122
McgcmsSort012SortOut[1].DISP=NEW,KEEP,KEEP
McgcmsSort012SortOut1RecordType=FB
McgcmsSort012SortOut1RecordLen=180
#STEP:SORT013| PGM:SORT| DD:SORTJNF1
McgcmsSort013SortIn[0]=CLOUDFRM.MC.GCMS.SORT.IN0131
McgcmsSort013SortIn[0].DISP=SHR,KEEP,KEEP
McgcmsSort013SortIn0RecordType=FB
McgcmsSort013SortIn0RecordLen=180
#STEP:SORT013| PGM:SORT| DD:SORTJNF2
McgcmsSort013SortIn[1]=CLOUDFRM.MC.GCMS.SORT.IN0132
McgcmsSort013SortIn[1].DISP=SHR,KEEP,KEEP
McgcmsSort013SortIn1RecordType=FB
McgcmsSort013SortIn1RecordLen=180
#STEP:SORT013| PGM:SORT| DD:SORTOF1
McgcmsSort013SortOut[0]=CLOUDFRM.MC.GCMS.SORT.OUT0131
McgcmsSort013SortOut[0].DISP=NEW,KEEP,KEEP
McgcmsSort013SortOut0RecordType=FB
McgcmsSort013SortOut0RecordLen=180
#STEP:SORT013| PGM:SORT| DD:SORTOF2
McgcmsSort013SortOut[1]=CLOUDFRM.MC.GCMS.SORT.OUT0132
McgcmsSort013SortOut[1].DISP=NEW,KEEP,KEEP
McgcmsSort013SortOut1RecordType=FB
McgcmsSort013SortOut1RecordLen=180
#STEP:SORT014| PGM:SORT| DD:SORTJNF1
McgcmsSort014SortIn[0]=CLOUDFRM.MC.GCMS.SORT.IN0141
McgcmsSort014SortIn[0].DISP=SHR,KEEP,KEEP
McgcmsSort014SortIn0RecordType=FB
McgcmsSort014SortIn0RecordLen=43
#STEP:SORT014| PGM:SORT| DD:SORTJNF2
McgcmsSort014SortIn[1]=CLOUDFRM.MC.GCMS.SORT.IN0142
McgcmsSort014SortIn[1].DISP=SHR,KEEP,KEEP
McgcmsSort014SortIn1RecordType=FB
McgcmsSort014SortIn1RecordLen=43
#STEP:SORT014| PGM:SORT| DD:F1ONLY
McgcmsSort014SortOut[0]=CLOUDFRM.MC.GCMS.SORT.OUT0141
McgcmsSort014SortOut[0].DISP=NEW,KEEP,KEEP
McgcmsSort014SortOut0RecordType=FB
McgcmsSort014SortOut0RecordLen=43
#STEP:SORT014| PGM:SORT| DD:F2ONLY
McgcmsSort014SortOut[1]=CLOUDFRM.MC.GCMS.SORT.OUT0142
McgcmsSort014SortOut[1].DISP=NEW,KEEP,KEEP
McgcmsSort014SortOut1RecordType=FB
McgcmsSort014SortOut1RecordLen=43
#STEP:SORT014| PGM:SORT| DD:BOTH
McgcmsSort014SortOut[2]=CLOUDFRM.MC.GCMS.SORT.OUT0143
McgcmsSort014SortOut[2].DISP=NEW,KEEP,KEEP
McgcmsSort014SortOut2RecordType=FB
McgcmsSort014SortOut2RecordLen=43
#STEP:SORT015| PGM:SORT| DD:SORTIN
McgcmsSort015SortIn=CLOUDFRM.MC.GCMS.SORT.IN015
McgcmsSort015SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort015SortInRecordType=VBS
McgcmsSort015SortInRecordLen=32760
#STEP:SORT015| PGM:SORT| DD:SORTOF1
McgcmsSort015SortOut[0]=CLOUDFRM.MC.GCMS.SORT.OUT0151
McgcmsSort015SortOut[0].DISP=NEW,KEEP,KEEP
McgcmsSort015SortOut0RecordType=FB
McgcmsSort015SortOut0RecordLen=23
#STEP:SORT015| PGM:SORT| DD:SORTOF2
McgcmsSort015SortOut[1]=CLOUDFRM.MC.GCMS.SORT.OUT0152
McgcmsSort015SortOut[1].DISP=NEW,KEEP,KEEP
McgcmsSort015SortOut1RecordType=FB
McgcmsSort015SortOut1RecordLen=23
#STEP:SORT016| PGM:SORT| DD:SORTJNF1
McgcmsSort016SortIn[0]=CLOUDFRM.MC.GCMS.SORT.IN0161
McgcmsSort016SortIn[0].DISP=SHR,KEEP,KEEP
McgcmsSort016SortIn0RecordType=FB
McgcmsSort016SortIn0RecordLen=136
#STEP:SORT016| PGM:SORT| DD:SORTJNF2
McgcmsSort016SortIn[1]=CLOUDFRM.MC.GCMS.SORT.IN0162
McgcmsSort016SortIn[1].DISP=SHR,KEEP,KEEP
McgcmsSort016SortIn1RecordType=FB
McgcmsSort016SortIn1RecordLen=80
#STEP:SORT016| PGM:SORT| DD:SORTOF1
McgcmsSort016SortOut[0]=CLOUDFRM.MC.GCMS.SORT.OUT0161
McgcmsSort016SortOut[0].DISP=NEW,KEEP,KEEP
McgcmsSort016SortOut0RecordType=FB
McgcmsSort016SortOut0RecordLen=2500
#STEP:SORT016| PGM:SORT| DD:SORTOF2
McgcmsSort016SortOut[1]=CLOUDFRM.MC.GCMS.SORT.OUT0162
McgcmsSort016SortOut[1].DISP=NEW,KEEP,KEEP
McgcmsSort016SortOut1RecordType=FBA
McgcmsSort016SortOut1RecordLen=248
#STEP:SORT017| PGM:SORT| DD:SORTIN
McgcmsSort017SortIn=CLOUDFRM.MC.GCMS.SORT.IN017
McgcmsSort017SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort017SortInRecordType=VB
McgcmsSort017SortInRecordLen=32760
#STEP:SORT017| PGM:SORT| DD:SORTOUT
McgcmsSort017SortOut=CLOUDFRM.MC.GCMS.SORT.OUT017
McgcmsSort017SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort017SortOutRecordType=FB
McgcmsSort017SortOutRecordLen=10
#STEP:SORT018| PGM:SORT| DD:SORTIN
McgcmsSort018SortIn=CLOUDFRM.MC.GCMS.SORT.IN018
McgcmsSort018SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort018SortInRecordType=FB
McgcmsSort018SortInRecordLen=135
#STEP:SORT018| PGM:SORT| DD:SORTOUT
McgcmsSort018SortOut=CLOUDFRM.MC.GCMS.SORT.OUT018
McgcmsSort018SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort018SortOutRecordType=FB
McgcmsSort018SortOutRecordLen=135
#STEP:SORT019| PGM:SORT| DD:SORTIN
McgcmsSort019SortIn[0]=CLOUDFRM.MC.GCMS.SORT.IN0191
McgcmsSort019SortIn[0].DISP=SHR,KEEP,KEEP
McgcmsSort019SortIn0RecordType=FB
McgcmsSort019SortIn0RecordLen=132
#STEP:SORT019| PGM:SORT| DD:SORTIN
McgcmsSort019SortIn[1]=CLOUDFRM.MC.GCMS.SORT.IN0192
McgcmsSort019SortIn[1].DISP=SHR,KEEP,KEEP
McgcmsSort019SortIn1RecordType=FB
McgcmsSort019SortIn1RecordLen=132
#STEP:SORT019| PGM:SORT| DD:SORTIN
McgcmsSort019SortIn[2]=CLOUDFRM.MC.GCMS.SORT.IN0193
McgcmsSort019SortIn[2].DISP=SHR,KEEP,KEEP
McgcmsSort019SortIn2RecordType=FB
McgcmsSort019SortIn2RecordLen=132
#STEP:SORT019| PGM:SORT| DD:SORTOUT
McgcmsSort019SortOut=CLOUDFRM.MC.GCMS.SORT.OUT019
McgcmsSort019SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort019SortOutRecordType=FB
McgcmsSort019SortOutRecordLen=132
#STEP:SORT020| PGM:SORT| DD:SORTIN
McgcmsSort020SortIn=CLOUDFRM.MC.GCMS.SORT.IN020
McgcmsSort020SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort020SortInRecordType=FB
McgcmsSort020SortInRecordLen=508
#STEP:SORT020| PGM:SORT| DD:SORTOUT
McgcmsSort020SortOut=CLOUDFRM.MC.GCMS.SORT.OUT020
McgcmsSort020SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort020SortOutRecordType=FB
McgcmsSort020SortOutRecordLen=508
#STEP:SORT021| PGM:SORT| DD:SORTIN
McgcmsSort021SortIn[0]=CLOUDFRM.MC.GCMS.SORT.IN0211
McgcmsSort021SortIn[0].DISP=SHR,KEEP,KEEP
McgcmsSort021SortIn0RecordType=FB
McgcmsSort021SortIn0RecordLen=237
#STEP:SORT021| PGM:SORT| DD:SORTIN
McgcmsSort021SortIn[1]=CLOUDFRM.MC.GCMS.SORT.IN0211
McgcmsSort021SortIn[1].DISP=SHR,KEEP,KEEP
McgcmsSort021SortIn1RecordType=FB
McgcmsSort021SortIn1RecordLen=237
#STEP:SORT021| PGM:SORT| DD:SORTOUT
McgcmsSort021SortOut=CLOUDFRM.MC.GCMS.SORT.OUT021
McgcmsSort021SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort021SortOutRecordType=FB
McgcmsSort021SortOutRecordLen=34
#STEP:SORT021_2| PGM:SORT| DD:SORTIN
McgcmsSort021_2SortIn[0]=CLOUDFRM.MC.GCMS.SORT.IN0211
McgcmsSort021_2SortIn[0].DISP=SHR,KEEP,KEEP
McgcmsSort021_2SortIn0RecordType=FB
McgcmsSort021_2SortIn0RecordLen=237
#STEP:SORT021_2| PGM:SORT| DD:SORTIN
McgcmsSort021_2SortIn[1]=CLOUDFRM.MC.GCMS.SORT.IN0212
McgcmsSort021_2SortIn[1].DISP=SHR,KEEP,KEEP
McgcmsSort021_2SortIn1RecordType=FB
McgcmsSort021_2SortIn1RecordLen=237
#STEP:SORT021_2| PGM:SORT| DD:SORTOUT
McgcmsSort021_2SortOut=CLOUDFRM.MC.GCMS.SORT.OUT021A
McgcmsSort021_2SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort021_2SortOutRecordType=FB
McgcmsSort021_2SortOutRecordLen=34
#STEP:SORT022| PGM:SORT| DD:SORTIN
McgcmsSort022SortIn=CLOUDFRM.MC.GCMS.SORT.IN022
McgcmsSort022SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort022SortInRecordType=VB
McgcmsSort022SortInRecordLen=27994
#STEP:SORT022| PGM:SORT| DD:SORTOF1
McgcmsSort022SortOut[0]=CLOUDFRM.MC.GCMS.SORT.OUT0221
McgcmsSort022SortOut[0].DISP=NEW,KEEP,KEEP
McgcmsSort022SortOut0RecordType=FB
McgcmsSort022SortOut0RecordLen=260
#STEP:SORT022| PGM:SORT| DD:SORTOF2
McgcmsSort022SortOut[1]=CLOUDFRM.MC.GCMS.SORT.OUT0222
McgcmsSort022SortOut[1].DISP=NEW,KEEP,KEEP
McgcmsSort022SortOut1RecordType=FB
McgcmsSort022SortOut1RecordLen=394
#STEP:SORT023| PGM:SORT| DD:SORTIN
McgcmsSort023SortIn=CLOUDFRM.MC.GCMS.SORT.IN023
McgcmsSort023SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort023SortInRecordType=FB
McgcmsSort023SortInRecordLen=260
#STEP:SORT023| PGM:SORT| DD:SORTOUT
McgcmsSort023SortOut=CLOUDFRM.MC.GCMS.SORT.OUT023
McgcmsSort023SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort023SortOutRecordType=FB
McgcmsSort023SortOutRecordLen=27
#STEP:SORT024| PGM:SORT| DD:SORTIN
McgcmsSort024SortIn=CLOUDFRM.MC.GCMS.SORT.IN024
McgcmsSort024SortIn.DISP=SHR,KEEP,KEEP
McgcmsSort024SortInRecordType=FB
McgcmsSort024SortInRecordLen=237
#STEP:SORT024| PGM:SORT| DD:SORTOUT
McgcmsSort024SortOut=CLOUDFRM.MC.GCMS.SORT.OUT024
McgcmsSort024SortOut.DISP=NEW,KEEP,KEEP
McgcmsSort024SortOutRecordType=FB
McgcmsSort024SortOutRecordLen=58
#STEP:STEPSUM| PGM:SORT| DD:SORTIN
McgcmsStepsumSortIn=CLOUDFRM.MC.GCMS.SORT.INSUM
McgcmsStepsumSortIn.DISP=SHR,KEEP,KEEP
McgcmsStepsumSortInRecordType=FB
McgcmsStepsumSortInRecordLen=60
#STEP:STEPSUM| PGM:SORT| DD:SORTOUT
McgcmsStepsumSortOut=CLOUDFRM.MC.GCMS.SORT.OUTSUM
McgcmsStepsumSortOut.DISP=NEW,KEEP,KEEP
McgcmsStepsumSortOutRecordType=FB
McgcmsStepsumSortOutRecordLen=60
#STEP:STEP010| PGM:SORT| DD:SORTIN
McgcmsStep010SortIn=CLOUDFRM.MC.GCMS.SORT.IN025
McgcmsStep010SortIn.DISP=SHR,KEEP,KEEP
McgcmsStep010SortInRecordType=VB
McgcmsStep010SortInRecordLen=201
#STEP:STEP010| PGM:SORT| DD:SORTOUT
McgcmsStep010SortOut=CLOUDFRM.MC.GCMS.SORT.OUT025
McgcmsStep010SortOut.DISP=NEW,KEEP,KEEP
McgcmsStep010SortOutRecordType=VB
McgcmsStep010SortOutRecordLen=201
#STEP:STEP020| PGM:SORT| DD:SORTJNF1
McgcmsStep020SortIn[0]=CLOUDFRM.MC.GCMS.SORT.IN0261
McgcmsStep020SortIn[0].DISP=SHR,KEEP,KEEP
McgcmsStep020SortIn0RecordType=VB
McgcmsStep020SortIn0RecordLen=45
#STEP:STEP020| PGM:SORT| DD:SORTJNF2
McgcmsStep020SortIn[1]=CLOUDFRM.MC.GCMS.SORT.IN0262
McgcmsStep020SortIn[1].DISP=SHR,KEEP,KEEP
McgcmsStep020SortIn1RecordType=VB
McgcmsStep020SortIn1RecordLen=201
#STEP:STEP020| PGM:SORT| DD:SORTOUT
McgcmsStep020SortOut=CLOUDFRM.MC.GCMS.SORT.OUT026
McgcmsStep020SortOut.DISP=NEW,KEEP,KEEP
McgcmsStep020SortOutRecordType=VB
McgcmsStep020SortOutRecordLen=201
