<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="FnsPayloadFacData" cobol:name="FNS-PAYLOAD-FAC-DATA" cobol:offset="93" cobol:length="129" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="FnsPayloadInsertTimestamp" maxOccurs="1"  cobol:name="FNS-PAYLOAD-INSERT-TIMESTAMP" cobol:offset="0" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="FnsPayloadCycleIndicator" type="xs:int" maxOccurs="1"  cobol:name="FNS-PAYLOAD-CYCLE-INDICATOR" cobol:offset="26" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="FnsPayloadMsgRsnCd" type="xs:long" maxOccurs="1"  cobol:name="FNS-PAYLOAD-MSG-RSN-CD" cobol:offset="29" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
         <xs:element name="FnsPayloadChargebackAmt" type="xs:long" maxOccurs="1"  cobol:name="FNS-PAYLOAD-CHARGEBACK-AMT" cobol:offset="34" cobol:length="13" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10T"/>
         <xs:element name="FnsPayloadChargebackCurrCd" type="xs:int" maxOccurs="1"  cobol:name="FNS-PAYLOAD-CHARGEBACK-CURR-CD" cobol:offset="47" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
    <xs:element name="FnsPayloadChargebackExpCd" maxOccurs="1"  cobol:name="FNS-PAYLOAD-CHARGEBACK-EXP-CD" cobol:offset="50" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FnsPayloadReversalIndicator" maxOccurs="1"  cobol:name="FNS-PAYLOAD-REVERSAL-INDICATOR" cobol:offset="51" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FnsPayloadChargebackRefNo" maxOccurs="1"  cobol:name="FNS-PAYLOAD-CHARGEBACK-REF-NO" cobol:offset="52" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="FnsPayloadFuncCd" type="xs:int" maxOccurs="1"  cobol:name="FNS-PAYLOAD-FUNC-CD" cobol:offset="62" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
    <xs:element name="FnsPayloadSwitchSerialNum" maxOccurs="1"  cobol:name="FNS-PAYLOAD-SWITCH-SERIAL-NUM" cobol:offset="65" cobol:length="9" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FnsPayloadSourceCd" maxOccurs="1"  cobol:name="FNS-PAYLOAD-SOURCE-CD" cobol:offset="74" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="FnsPayloadCntCd" type="xs:short" maxOccurs="1"  cobol:name="FNS-PAYLOAD-CNT-CD" cobol:offset="78" cobol:length="2" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
    <xs:element name="FnsPayloadOrigSwSerNum" maxOccurs="1"  cobol:name="FNS-PAYLOAD-ORIG-SW-SER-NUM" cobol:offset="80" cobol:length="9" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="FnsPayloadCloseDt" maxOccurs="1" cobol:name="FNS-PAYLOAD-CLOSE-DT" cobol:offset="89" cobol:length="10" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="FnsPayloadChgbkCnt" type="xs:int" maxOccurs="1"  cobol:name="FNS-PAYLOAD-CHGBK-CNT" cobol:offset="99" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
    <xs:element name="FnsPayloadRejRsn1Cd" maxOccurs="1"  cobol:name="FNS-PAYLOAD-REJ-RSN-1-CD" cobol:offset="102" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FnsPayloadRejRsn2Cd" maxOccurs="1"  cobol:name="FNS-PAYLOAD-REJ-RSN-2-CD" cobol:offset="106" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FnsPayloadVrtlAcctNum" maxOccurs="1"  cobol:name="FNS-PAYLOAD-VRTL-ACCT-NUM" cobol:offset="110" cobol:length="19" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="19" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
