<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="FnsPayloadFacDataKey" cobol:name="FNS-PAYLOAD-FAC-DATA-KEY" cobol:offset="68" cobol:length="25" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="FnsPayloadPrimaryAcctNbr" maxOccurs="1"  cobol:name="FNS-PAYLOAD-PRIMARY-ACCT-NBR" cobol:offset="0" cobol:length="19" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="19" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="FnsPayloadExpirationDate" maxOccurs="1" cobol:name="FNS-PAYLOAD-EXPIRATION-DATE" cobol:offset="19" cobol:length="6" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
