<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="FraudMqDebugDisp600" cobol:name="600-FRAUD-MQ-DEBUG-DISP" cobol:offset="0" cobol:length="126" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="PrimaryAcctNo600" maxOccurs="1"  cobol:name="600-PRIMARY-ACCT-NO" cobol:offset="0" cobol:length="19" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="19" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ExpirDate600" maxOccurs="1"  cobol:name="600-EXPIR-DATE" cobol:offset="19" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="VirtualAcctNo600" maxOccurs="1"  cobol:name="600-VIRTUAL-ACCT-NO" cobol:offset="25" cobol:length="19" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="19" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="QueryNum600" type="xs:int" maxOccurs="1"  cobol:name="600-QUERY-NUM" cobol:offset="44" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
    <xs:element name="GftDsn600" maxOccurs="1"  cobol:name="600-GFT-DSN" cobol:offset="48" cobol:length="44" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="LogicalSeq600" type="xs:long" maxOccurs="1"  cobol:name="600-LOGICAL-SEQ" cobol:offset="92" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="TxnNo600" type="xs:long" maxOccurs="1"  cobol:name="600-TXN-NO" cobol:offset="101" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="FacCount600" type="xs:long" maxOccurs="1"  cobol:name="600-FAC-COUNT" cobol:offset="110" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
    <xs:element name="FaaPanStatCd600" maxOccurs="1"  cobol:name="600-FAA-PAN-STAT-CD" cobol:offset="115" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FaaClsDt600" maxOccurs="1"  cobol:name="600-FAA-CLS-DT" cobol:offset="116" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
