<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip82921ErrMsgOut" cobol:name="IP82921-ERR-MSG-OUT" cobol:offset="0" cobol:length="280" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="Ip82921ErrPayloadMsg" maxOccurs="1" cobol:name="IP82921-ERR-PAYLOAD-MSG" cobol:offset="0" cobol:length="222" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Ip82921ErrRequestCd" maxOccurs="1"  cobol:name="IP82921-ERR-REQUEST-CD" cobol:offset="222" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip82921ErrTargetQmgrName" maxOccurs="1"  cobol:name="IP82921-ERR-TARGET-QMGR-NAME" cobol:offset="225" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Ip82921ErrTargetQName" maxOccurs="1"  cobol:name="IP82921-ERR-TARGET-Q-NAME" cobol:offset="229" cobol:length="11" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Ip82921ErrCompCd" type="xs:long" maxOccurs="1"  cobol:name="IP82921-ERR-COMP-CD" cobol:offset="240" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
         <xs:element name="Ip82921ErrResnCd" type="xs:long" maxOccurs="1"  cobol:name="IP82921-ERR-RESN-CD" cobol:offset="245" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
    <xs:element name="Ip82921ErrMsg" maxOccurs="1"  cobol:name="IP82921-ERR-MSG" cobol:offset="250" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
