<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Work" cobol:name="work" cobol:offset="0" cobol:length="8" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="MqRespStatusSw100" maxOccurs="1"  cobol:name="100-MQ-RESP-STATUS-SW" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 mqRespY88100 VALUE [["Y"]].
                        88 mqRespN88100 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="IsItTheFirstTime100" maxOccurs="1"  cobol:name="100-IS-IT-THE-FIRST-TIME" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 itIsFirstTime88100 VALUE [["Y"]].
                        88 itIsNotFirstTime88100 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
         <xs:element name="QueryNoSeven300" type="xs:short" maxOccurs="1"  cobol:name="300-QUERY-NO-SEVEN" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="JobnameErrorAbendCode300" maxOccurs="1"  cobol:name="300-JOBNAME-ERROR-ABEND-CODE" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="JobnumErrorAbendCode300" maxOccurs="1"  cobol:name="300-JOBNUM-ERROR-ABEND-CODE" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RetryErrorAbendCode300" maxOccurs="1"  cobol:name="300-RETRY-ERROR-ABEND-CODE" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="GetMqRspCdAbendCode300" maxOccurs="1"  cobol:name="300-GET-MQ-RSP-CD-ABEND-CODE" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="GetQAbendCode300" maxOccurs="1"  cobol:name="300-GET-Q-ABEND-CODE" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="InsertMrsAbendCode300" maxOccurs="1"  cobol:name="300-INSERT-MRS-ABEND-CODE" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PutQAbendCode300" maxOccurs="1"  cobol:name="300-PUT-Q-ABEND-CODE" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="InvalidRcLrm300" maxOccurs="1"  cobol:name="300-INVALID-RC-LRM" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendCode3003010" maxOccurs="1"  cobol:name="300-3010-ABEND-CODE" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendCode3003011" maxOccurs="1"  cobol:name="300-3011-ABEND-CODE" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendCode3003012" maxOccurs="1"  cobol:name="300-3012-ABEND-CODE" cobol:offset="0" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp081110300" maxOccurs="1"  cobol:name="300-PGM-IP081110" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp282210300" maxOccurs="1"  cobol:name="300-PGM-IP282210" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp521010300" maxOccurs="1"  cobol:name="300-PGM-IP521010" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp586010300" maxOccurs="1"  cobol:name="300-PGM-IP586010" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp599810300" maxOccurs="1"  cobol:name="300-PGM-IP599810" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp595210300" maxOccurs="1"  cobol:name="300-PGM-IP595210" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendPgm300" maxOccurs="1"  cobol:name="300-ABEND-PGM" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp648010300" maxOccurs="1"  cobol:name="300-PGM-IP648010" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp703020300" maxOccurs="1"  cobol:name="300-PGM-IP703020" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp829010300" maxOccurs="1"  cobol:name="300-PGM-IP829010" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmVersion300" maxOccurs="1"  cobol:name="300-PGM-VERSION" cobol:offset="0" cobol:length="7" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp708020300" maxOccurs="1"  cobol:name="300-PGM-IP708020" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp890110300" maxOccurs="1"  cobol:name="300-PGM-IP890110" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp996010300" maxOccurs="1"  cobol:name="300-PGM-IP996010" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp996020300" maxOccurs="1"  cobol:name="300-PGM-IP996020" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PgmIp708010300" maxOccurs="1"  cobol:name="300-PGM-IP708010" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Value1300" type="xs:short" maxOccurs="1"  cobol:name="300-VALUE-1" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Value7300" type="xs:int" maxOccurs="1"  cobol:name="300-VALUE-7" cobol:offset="0" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="Value99300" type="xs:int" maxOccurs="1"  cobol:name="300-VALUE-99" cobol:offset="2" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="ValueFacreq300" maxOccurs="1"  cobol:name="300-VALUE-FACREQ" cobol:offset="4" cobol:length="6" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="MqFailCode300" type="xs:int" maxOccurs="1"  cobol:name="300-MQ-FAIL-CODE" cobol:offset="4" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="MqFailCodeOne300" type="xs:int" maxOccurs="1"  cobol:name="300-MQ-FAIL-CODE-ONE" cobol:offset="4" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="ValuePipe300" maxOccurs="1"  cobol:name="300-VALUE-PIPE" cobol:offset="4" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ValueClosed300" maxOccurs="1"  cobol:name="300-VALUE-CLOSED" cobol:offset="4" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ValueTest300" maxOccurs="1"  cobol:name="300-VALUE-TEST" cobol:offset="4" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ValueN300" maxOccurs="1"  cobol:name="300-VALUE-N" cobol:offset="4" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ValueC300" maxOccurs="1"  cobol:name="300-VALUE-C" cobol:offset="4" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sys201300" maxOccurs="1"  cobol:name="300-SYS201" cobol:offset="4" cobol:length="6" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PanInvalidMsg300" maxOccurs="1"  cobol:name="300-PAN-INVALID-MSG" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ExpInvalidMsg300" maxOccurs="1"  cobol:name="300-EXP-INVALID-MSG" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="VanInvalidMsg300" maxOccurs="1"  cobol:name="300-VAN-INVALID-MSG" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="GftInvalidMsg300" maxOccurs="1"  cobol:name="300-GFT-INVALID-MSG" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TxnInvalidMsg300" maxOccurs="1"  cobol:name="300-TXN-INVALID-MSG" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FacNotFoundMsg300" maxOccurs="1"  cobol:name="300-FAC-NOT-FOUND-MSG" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TipmrsFailMsg300" maxOccurs="1"  cobol:name="300-TIPMRS-FAIL-MSG" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TipmrsDuplMsg300" maxOccurs="1"  cobol:name="300-TIPMRS-DUPL-MSG" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MqputFailMsg300" maxOccurs="1"  cobol:name="300-MQPUT-FAIL-MSG" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MqgetFailMsg300" maxOccurs="1"  cobol:name="300-MQGET-FAIL-MSG" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Asterisks300" maxOccurs="1"  cobol:name="300-ASTERISKS" cobol:offset="4" cobol:length="34" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="34" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendTxt300" maxOccurs="1"  cobol:name="300-ABEND-TXT" cobol:offset="4" cobol:length="31" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="31" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendPgmTxt300" maxOccurs="1"  cobol:name="300-ABEND-PGM-TXT" cobol:offset="4" cobol:length="26" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ParaName1400300" maxOccurs="1"  cobol:name="300-PARA-NAME-1400" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ParaName2426300" maxOccurs="1"  cobol:name="300-PARA-NAME-2426" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ParaName2410300" maxOccurs="1"  cobol:name="300-PARA-NAME-2410" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ParaName2610300" maxOccurs="1"  cobol:name="300-PARA-NAME-2610" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ParaName24301300" maxOccurs="1"  cobol:name="300-PARA-NAME-2430-1" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ParaName8500300" maxOccurs="1"  cobol:name="300-PARA-NAME-8500" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ParaName1900300" maxOccurs="1"  cobol:name="300-PARA-NAME-1900" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ParaName2800300" maxOccurs="1"  cobol:name="300-PARA-NAME-2800" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ParaName3100300" maxOccurs="1"  cobol:name="300-PARA-NAME-3100" cobol:offset="4" cobol:length="30" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FraudMqDebugDispStr600" maxOccurs="1"  cobol:name="600-FRAUD-MQ-DEBUG-DISP-STR" cobol:offset="4" cobol:length="400" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="400" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="JobNameError600" maxOccurs="1"  cobol:name="600-JOB-NAME-ERROR" cobol:offset="4" cobol:length="45" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="45" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="JobNumError601" maxOccurs="1"  cobol:name="601-JOB-NUM-ERROR" cobol:offset="4" cobol:length="45" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="45" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RetryCountError602" maxOccurs="1"  cobol:name="602-RETRY-COUNT-ERROR" cobol:offset="4" cobol:length="45" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="45" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="RowsNotFoundErrMsgTxt604" maxOccurs="1"  cobol:name="604-ROWS-NOT-FOUND-ERR-MSG-TXT" cobol:offset="4" cobol:length="35" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="35" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TipamrsInsertFailure605" maxOccurs="1"  cobol:name="605-TIPAMRS-INSERT-FAILURE" cobol:offset="4" cobol:length="35" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="35" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="LrmIoAbendMsg609" maxOccurs="1"  cobol:name="609-LRM-IO-ABEND-MSG" cobol:offset="4" cobol:length="50" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="50" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="AbendPtr800" maxOccurs="1"  cobol:name="800-ABEND-PTR" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PtrIp081110800" maxOccurs="1"  cobol:name="800-PTR-IP081110" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PtrIp282210800" maxOccurs="1"  cobol:name="800-PTR-IP282210" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PtrIp586010800" maxOccurs="1"  cobol:name="800-PTR-IP586010" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PtrIp599810800" maxOccurs="1"  cobol:name="800-PTR-IP599810" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PtrIp595210800" maxOccurs="1"  cobol:name="800-PTR-IP595210" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PtrIp648010800" maxOccurs="1"  cobol:name="800-PTR-IP648010" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PtrIp708020800" maxOccurs="1"  cobol:name="800-PTR-IP708020" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PtrIp703020800" maxOccurs="1"  cobol:name="800-PTR-IP703020" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PtrIp890110800" maxOccurs="1"  cobol:name="800-PTR-IP890110" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PtrIp996010800" maxOccurs="1"  cobol:name="800-PTR-IP996010" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PtrIp996020800" maxOccurs="1"  cobol:name="800-PTR-IP996020" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PtrIp521010800" maxOccurs="1"  cobol:name="800-PTR-IP521010" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PtrIp708010800" maxOccurs="1"  cobol:name="800-PTR-IP708010" cobol:offset="4" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Start800" type="xs:int" maxOccurs="1"  cobol:name="800-START" cobol:offset="4" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="End800" type="xs:int" maxOccurs="1"  cobol:name="800-END" cobol:offset="4" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="ClrCyclId800" type="xs:int" maxOccurs="1"  cobol:name="800-CLR-CYCL-ID" cobol:offset="4" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="PrevClrCyclId800" type="xs:int" maxOccurs="1"  cobol:name="800-PREV-CLR-CYCL-ID" cobol:offset="6" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="MqRespCd800" maxOccurs="1"  cobol:name="800-MQ-RESP-CD" cobol:offset="8" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="FacreqJobgrpName800" maxOccurs="1"  cobol:name="800-FACREQ-JOBGRP-NAME" cobol:offset="8" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Jobname800" maxOccurs="1"  cobol:name="800-JOBNAME" cobol:offset="8" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="MrsIsrtCount800" type="xs:int" maxOccurs="1"  cobol:name="800-MRS-ISRT-COUNT" cobol:offset="8" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="MqputSkipCount800" type="xs:int" maxOccurs="1"  cobol:name="800-MQPUT-SKIP-COUNT" cobol:offset="8" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="TipamrsSkipCount800" type="xs:int" maxOccurs="1"  cobol:name="800-TIPAMRS-SKIP-COUNT" cobol:offset="8" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="MqgetFailCount800" type="xs:int" maxOccurs="1"  cobol:name="800-MQGET-FAIL-COUNT" cobol:offset="8" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="MqputFailCount800" type="xs:int" maxOccurs="1"  cobol:name="800-MQPUT-FAIL-COUNT" cobol:offset="8" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="FaaFacNotFndCnt800" type="xs:int" maxOccurs="1"  cobol:name="800-FAA-FAC-NOT-FND-CNT" cobol:offset="8" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="LnRespDebugInd800" maxOccurs="1"  cobol:name="800-LN-RESP-DEBUG-IND" cobol:offset="8" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 respDebugIndY88800 VALUE [["Y"]].
                        88 respDebugIndN88800 VALUE [["N"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Sys201Status800" maxOccurs="1"  cobol:name="800-SYS201-STATUS" cobol:offset="8" cobol:length="2" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_100" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 sys201IoGood80088 VALUE [["00"]].
                        88 sys201Eof80088 VALUE [["10"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="2" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="SkipFlag800" maxOccurs="1"  cobol:name="800-SKIP-FLAG" cobol:offset="8" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 skipFlagN88800 VALUE [["N"]].
                        88 skipFlagY88800 VALUE [["Y"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
