  package com.cloudframe.app.vsammon7.file.keys;
  /* Java Code Generated by CloudFrame */
  
  
  import org.springframework.stereotype.Component;
  
  import java.util.ArrayList;
  import java.util.List;
  
  import com.cloudframe.app.vsam.KeyInfo;
  
  
  @Component("vsammon7_monitorKey")
  public class MonitorKey {
  
  	private FileKeyInfo monPriKey;
  	private FileKeyInfo monXcdtProgNm;
  
  	public MonitorKey() {
  											// Offset, length, key sequence , isPrimaryKey
  		this.monPriKey = new FileKeyInfo(0,65,0,true);
  											// Offset, length, key sequence , isPrimaryKey
  		this.monXcdtProgNm = new FileKeyInfo(18,8,1,false);
  	}
  	
  	public List<KeyInfo> getFileKeyInfoList() {
    		ArrayList<KeyInfo> fileKeyInfoList = new ArrayList<>();
    		fileKeyInfoList.add(this.monPriKey);
    		fileKeyInfoList.add(this.monXcdtProgNm);
  		return fileKeyInfoList;
      }
    	
  	public FileKeyInfo getMonPriKey() {
  		return monPriKey;
  	}
  	public FileKeyInfo getMonXcdtProgNm() {
  		return monXcdtProgNm;
  	}
  
  	
  }
