package com.cloudframe.app.sort.file.records;
/* Java Code Generated by CloudFrame */

import java.io.Serializable;
import java.util.Comparator;
import com.cloudframe.app.data.Field;
import java.util.Arrays;

public class SortzdcompPrip7001_step030Keys implements Serializable {

	/**
	 * External SORT Statement is converted to keys
	 */
	private static final long serialVersionUID = 1L; 
	private  long sortRecPos = 0;
	private  int sortRecLen = 0;
	private  int fileIndx = 0;
	private byte[] keyCharacter1;
	private byte[] keyCharacter2;
	private byte[] keyBinary3;
	private byte[] keyCharacter4;
	
	public int getFileIndx() {
		return fileIndx;
	}

	public void setFileIndx(int indx) {
		this.fileIndx = indx;
	}
	public long getSortRecPos() {
		return sortRecPos;
	}

	public void setSortRecPos(long sortRecPos) {
		this.sortRecPos = sortRecPos;
	}

	public int getSortRecLen() {
		return sortRecLen;
	}

	public void setSortRecLen(int sortRecLen) {
		this.sortRecLen = sortRecLen;
	}
	
    /* String - Display - keyCharacter1 */
	public byte[] getKeyCharacter1() {
		return keyCharacter1;
   }

   public void setKeyCharacter1(byte[] val) {
		this.keyCharacter1 = val; 
   }
    /* String - Display - keyCharacter2 */
	public byte[] getKeyCharacter2() {
		return keyCharacter2;
   }

   public void setKeyCharacter2(byte[] val) {
		this.keyCharacter2 = val; 
   }
    /* int - Binary - keyBinary3 */
	public byte[] getKeyBinary3() {
		return keyBinary3;
   }

   public void setKeyBinary3(byte[] val) {
		this.keyBinary3 = val; 
   }
    /* String - Display - keyCharacter4 */
	public byte[] getKeyCharacter4() {
		return keyCharacter4;
   }

   public void setKeyCharacter4(byte[] val) {
		this.keyCharacter4 = val; 
   }

	public static Comparator<SortzdcompPrip7001_step030Keys> getKeyCharacter1Comparator(boolean isAsc) {
		return isAsc ? (o1, o2) -> Field.compareBytes(o1.getKeyCharacter1(), o2.getKeyCharacter1())
				: (o1, o2) -> Field.compareBytes(o2.getKeyCharacter1(), o1.getKeyCharacter1());
	}
	
	public static Comparator<SortzdcompPrip7001_step030Keys> getKeyCharacter2Comparator(boolean isAsc) {
		return isAsc ? (o1, o2) -> Field.compareBytes(o1.getKeyCharacter2(), o2.getKeyCharacter2())
				: (o1, o2) -> Field.compareBytes(o2.getKeyCharacter2(), o1.getKeyCharacter2());
	}
	
	public static Comparator<SortzdcompPrip7001_step030Keys> getKeyBinary3Comparator(boolean isAsc) {
		return isAsc ? (o1, o2) -> Field.compareBytes(o1.getKeyBinary3(), o2.getKeyBinary3())
				: (o1, o2) -> Field.compareBytes(o2.getKeyBinary3(), o1.getKeyBinary3());
	}
	
	public static Comparator<SortzdcompPrip7001_step030Keys> getKeyCharacter4Comparator(boolean isAsc) {
		return isAsc ? (o1, o2) -> Field.compareBytes(o1.getKeyCharacter4(), o2.getKeyCharacter4())
				: (o1, o2) -> Field.compareBytes(o2.getKeyCharacter4(), o1.getKeyCharacter4());
	}
	

	@Override
    public boolean equals(Object obj) {
        if(obj instanceof SortzdcompPrip7001_step030Keys) {
        	SortzdcompPrip7001_step030Keys temp = (SortzdcompPrip7001_step030Keys) obj;
            if(Field.getString(this.keyCharacter1).equals(Field.getString(temp.keyCharacter1)) && Field.getString(this.keyCharacter2).equals(Field.getString(temp.keyCharacter2)) && Field.getString(this.keyBinary3).equals(Field.getString(temp.keyBinary3)) && Field.getString(this.keyCharacter4).equals(Field.getString(temp.keyCharacter4)))
                return true;
        }
        return false;
    }
	
	@Override
    public int hashCode() {
        return (Arrays.hashCode(this.keyCharacter1) + Arrays.hashCode(this.keyCharacter2) + Arrays.hashCode(this.keyBinary3) + Arrays.hashCode(this.keyCharacter4));        
    }
}
