# Program IP606130 | DD : SYS105 | RecordFormat : VariableLength | MaxRecordLength : 32752
IP606130.ddname.SYS105=Sys105TempTable90
IP606130.Sys105TempTable90=Sys105TempTable90
IP606130.Sys105TempTable90CharSet=cp1047
IP606130.Sys105TempTable90CRLFflag=no
# Program IP606130 | DD : SYS106 | RecordFormat : VariableLength | MaxRecordLength : 32752
IP606130.ddname.SYS106=Sys106TempTable91
IP606130.Sys106TempTable91=Sys106TempTable91
IP606130.Sys106TempTable91CharSet=cp1047
IP606130.Sys106TempTable91CRLFflag=no
# Program IP606130 | DD : SYS001 | RecordFormat : VariableLength | MaxRecordLength : 32752
IP606130.ddname.SYS001=Sys001ReducedParmMaster
IP606130.Sys001ReducedParmMaster=Sys001ReducedParmMaster
IP606130.Sys001ReducedParmMasterCharSet=cp1047
IP606130.Sys001ReducedParmMasterCRLFflag=no
# Program IP606130 | DD : SYS200 | RecordFormat : VariableLength | MaxRecordLength : 32752
IP606130.ddname.SYS200=Sys200ExpandedParmMaster
IP606130.Sys200ExpandedParmMaster=Sys200ExpandedParmMaster
IP606130.Sys200ExpandedParmMasterCharSet=cp1047
IP606130.Sys200ExpandedParmMasterCRLFflag=no
# 
# End of IP606130
