# Program DBISSUES | DD : FIZ018I | RecordFormat : VariableLength | MaxRecordLength : 1600
DBISSUES.ddname.FIZ018I=Fiz018i
DBISSUES.Fiz018i=Fiz018i
DBISSUES.Fiz018iCharSet=cp1047
DBISSUES.Fiz018iCRLFflag=no
# Program DBISSUES | DD : FIZ018O | RecordFormat : VariableLength | MaxRecordLength : 1600
DBISSUES.ddname.FIZ018O=Fiz018o
DBISSUES.Fiz018o=Fiz018o
DBISSUES.Fiz018oCharSet=cp1047
DBISSUES.Fiz018oCRLFflag=no
# 
# End of DBISSUES
