  package com.cloudframe.app.process.impl;
  /* Java code generated by CloudFrame on 2025-04-24 at 16:31. */
  
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.beans.factory.annotation.Qualifier;
  import com.cloudframe.app.mc083.file.*;
  import com.cloudframe.app.mc083.Mc083Ctx.*;
  import com.cloudframe.app.mc083.Mc083Ctx;
  import com.cloudframe.app.process.Mc083;
  import com.cloudframe.app.process.BaseProcess;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import org.springframework.web.bind.annotation.RequestParam;
  import com.cloudframe.app.dto.GlobalExecutorCtx;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.dto.ProgramContext;
  import com.cloudframe.app.data.Field;
  import com.cloudframe.app.mc083.dto.*;
  import com.cloudframe.app.mc083.dto.Mc083ReadFileParm;
  import com.cloudframe.app.mc083.file.records.FbRecordOut;
  import com.cloudframe.app.global.sharedvar.FirstTimeCallGroup;
  import com.cloudframe.app.mc083.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("mc083")
  
  public class Mc083Impl extends CommonProcess implements Mc083 {
  
  Logger logger = LoggerFactory.getLogger(Mc083Impl.class);
  
  
  
  
  @Autowired 
  @Qualifier("mc083_fbFile")
  FbFile fbFile;
  
  
  
  
  
  
      @Override
      public int setParameter(Mc083Ctx programCtx, String mc083ReadFileParm) throws Exception {
      		if(mc083ReadFileParm != null)
      		    programCtx.getMc083ReadFileParm().setString(com.cloudframe.app.data.Field.getParm(mc083ReadFileParm),new String(CONSTANTS.EBCDIC_ENCODING));
      		setInitDone(false);
      		process(programCtx);
      		return programCtx.getRc();
      }
      /**
      * process 
      * Input  :  

      * - firstTimeCall                  COBOL Name: FIRST-TIME-CALL
      *
      * Output :  

      * - fbFileStatus                   COBOL Name: WS-FB-FILE-STATUS
      * - mc083FileStatus                COBOL Name: MC083-FILE-STATUS
      * - firstTimeCall                  COBOL Name: FIRST-TIME-CALL
      * - mc083Data                      COBOL Name: MC083-DATA
      * - fbRecordOut                    COBOL Name: FB-RECORD-OUT
      *
      * @throws CFException
      */
      public int process(Mc083Ctx programCtx) throws Exception {
       try {
       setCodePage("1047");
            // Reset program ended flag
           programCtx.setProgramEnded(false);
ProcessInCtx methodIn = programCtx.getProcessInCtx();
ProcessOutCtx methodOut = methodIn.getProcessOutCtx();

// *
//  IF FIRST-TIME-CALL = 'Y'
//  LITERAL_Y = 'Y'
          if (compareChars(methodOut.getFirstTimeCall(), CONSTANTS.LITERAL_Y) == 0) { 
//  OPEN INPUT FB-FILE
              fbFile.open(new String(CONSTANTS.MODE_READ_ONLY_36242),fbFile.getFileName(),fbFile.getFbFileCharSet(),fbFile.getFbFileCrlfFlag());
              methodOut.setFbFileStatus(fbFile.getStatusString() );
//  MOVE WS-FB-FILE-STATUS TO MC083-FILE-STATUS
              methodOut.setMc083FileStatus(methodOut.getFbFileStatus());
//  IF NOT ( WS-FB-FILE-STATUS = ZERO)
              if ((!( allZeros(methodOut.getFbFileStatus()) ) /*  !=  zeros*/)) { 
//  DISPLAY 'FB-FILE OPEN FAILED' WS-FB-FILE-STATUS
                  logger.info("FB-FILE OPEN FAILED{}", new String(methodOut.getFbFileStatus())); 
//  GOBACK
                  setNotLogged(false); // no need to log, it is a normal termination
                  programCtx.setProgramEnded(true);
                  return programCtx.getRc();
              }
//  MOVE 'N' TO FIRST-TIME-CALL
//  LITERAL_N = 'N'
              methodOut.setFirstTimeCall(CONSTANTS.LITERAL_N);
          }
//  MOVE ALL '?' TO MC083-DATA
          methodOut.setMc083Data(CONSTANTS.LITERAL_1837816148);
          // READ FB-FILE
          fbFile.read();
          methodOut.setFbFileStatus(fbFile.getStatusString());
          if (!fbFile.hasEnded()) {
              methodOut.getFbRecordOut().setString(fbFile.getRecord());
          }
//  MOVE WS-FB-FILE-STATUS TO MC083-FILE-STATUS
          methodOut.setMc083FileStatus(methodOut.getFbFileStatus());
//  IF WS-FB-FILE-STATUS = '00'
//  LITERAL_00 = '00'
          if (		compareChars(methodOut.getFbFileStatus(),CONSTANTS.LITERAL_00) == 0 ) { 
              // MOVE FB-RECORD-OUT TO MC083-DATA
              methodOut.setMc083Data(methodOut.getFbRecordOut().toCharArray());
          }
//  ELSE
          else { 
//  IF WS-FB-FILE-STATUS = '10'
//  LITERAL_10 = '10'
              if (		compareChars(methodOut.getFbFileStatus(),CONSTANTS.LITERAL_10) == 0 ) { 
//  MOVE SPACES TO MC083-DATA
                  methodOut.setMc083Data(CONSTANTS.SPACE_80);
              }
          }
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          programCtx.setProgramEnded(true);
          return programCtx.getRc();
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
        finally {
      		if(fbFile.hasOpened() && !fbFile.isReadOnly()) { 
      			fbFile.flush(); 
      		}
      }
      
      // end of process method
      }
  
  
  
      public int call(ProgramContext ctx, Object[] params) throws Exception {
      Mc083Ctx programCtx = (Mc083Ctx) ctx;
      
      int len = params.length;
         if (len > 0 && params[0] != null )
            programCtx.getMc083ReadFileParm().set((Field)params[0]);
         // invoke the process and return rc
         return process(programCtx);
         
      }
      
      public int call(ProgramContext ctx, Field... parameters) throws Exception {
      Mc083Ctx programCtx = (Mc083Ctx) ctx;
         for (int index = 0; index < parameters.length;index++) {
             switch(index) {
              case 0:
                      if(parameters[index] != null ) {
              		if (parameters[index] instanceof Mc083ReadFileParm) {
                       	programCtx.setMc083ReadFileParm((Mc083ReadFileParm) parameters[index]);
                  	} else {
                       	programCtx.getMc083ReadFileParm().set(parameters[index]);
                  	}
                  }
                
                  break;
            }
         }
      	return process(programCtx);
      }
      
      
  
  
  
  
  
  }
