#STEP:PRINT01| PGM:IDCAMS| DD:INPUT
PRINT01.IDCAMS.Input=CLOUDFRM.IDCAMS.PRINT.FB.FILE2
PRINT01.IDCAMS.Input.DISP=SHR,KEEP,KEEP
PRINT01.IDCAMS.Input.RecordType=FB
PRINT01.IDCAMS.Input.RecordLen=<recordLen>
#
#STEP:PRINT01| PGM:IDCAMS| DD:SYSPRINT
PRINT01.IDCAMS.Sysprint=DUMMY
PRINT01.IDCAMS.Sysprint.DISP=SHR,KEEP,KEEP
PRINT01.IDCAMS.Sysprint.RecordType=FB
PRINT01.IDCAMS.Sysprint.RecordLen=<recordLen>
#
