# Program MCSORT05 | DD : SYS001 | RecordFormat : FixedLength | RecordLength : 2000
MCSORT05.ddname.SYS001=Sys001GroupStatFile
MCSORT05.Sys001GroupStatFile=Sys001GroupStatFile
MCSORT05.Sys001GroupStatFileCharSet=cp1047
MCSORT05.Sys001GroupStatFileCRLFflag=no
# Program MCSORT05 | DD : SYS201 | RecordFormat : FixedLength | RecordLength : 2000
MCSORT05.ddname.SYS201=Sys201SortedGroupStatFile
MCSORT05.Sys201SortedGroupStatFile=Sys201SortedGroupStatFile
MCSORT05.Sys201SortedGroupStatFileCharSet=cp1047
MCSORT05.Sys201SortedGroupStatFileCRLFflag=no
# 
# End of MCSORT05
