package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.data.Field;
import com.cloudframe.app.utility.CFUtil;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] SPACE_2 = CFUtil.fillSpaces(2);
public static final char[] SPACE_80 = CFUtil.fillSpaces(80);
public static final char[] SPACE_7 = CFUtil.fillSpaces(7);
public static final char[] EBCDIC_ENCODING = "cp1047".toCharArray();
public static final char[] FORMAT_2062691925 = "ZZZZZZZZ9".toCharArray();
public static final char[] HEX_00010203 = Field.getString(new byte[] {(byte)0x00,(byte)0x01,(byte)0x02,(byte)0x03}).toCharArray();
public static final char[] HIGH_VALUE_1455163297 = Field.fillHighValue(80);
public static final char[] HIGH_VALUE_STRING = Field.fillHighValue(1);
public static final char[] LITERAL_0000000000_B4_NATCAVER = "0000000000 NAT CA VER ".toCharArray();
public static final char[] LITERAL_1 = "1".toCharArray();
public static final char[] LITERAL_1030274401 = "</HT".toCharArray();
public static final char[] LITERAL_1030306145 = "</ht".toCharArray();
public static final char[] LITERAL_1033574940 = "@#$%".toCharArray();
public static final char[] LITERAL_1170718772 = CFUtil.pad(80, "*", "*",CFUtil.RIGHT_PAD);
public static final char[] LITERAL_1346 = "1346".toCharArray();
public static final char[] LITERAL_33824 = "$".toCharArray();
public static final char[] LITERAL_34134 = ".".toCharArray();
public static final char[] LITERAL_34568 = "<".toCharArray();
public static final char[] LITERAL_34630 = ">".toCharArray();
public static final char[] LITERAL_534421107 = CFUtil.pad(80, "&<\'\"\">123&<\'\"\">&<&<\'\"\">\'>\'>\"\"", " ",CFUtil.RIGHT_PAD);
public static final char[] LITERAL_8 = "8".toCharArray();
public static final char[] LITERAL_9 = "9".toCharArray();
public static final char[] LITERAL_954407368 = CFUtil.pad(80, "<htag>Header</htag>", " ",CFUtil.RIGHT_PAD);
public static final char[] LITERAL_959977949 = CFUtil.pad(80, "$+9-9$+-123+$$", " ",CFUtil.RIGHT_PAD);
public static final char[] LITERAL_ABCD = "ABCD".toCharArray();
public static final char[] LITERAL_ABCD1234 = "ABCD1234".toCharArray();
public static final char[] LITERAL_AT_ = "@".toCharArray();
public static final char[] LITERAL_BS_ = "\"".toCharArray();
public static final char[] LITERAL_BS_QT_ = "\'".toCharArray();
public static final char[] LITERAL_CHARACTERS = "CHARACTERS".toCharArray();
public static final char[] LITERAL_MN_ = "-".toCharArray();
public static final char[] LITERAL_NP_ = "&".toCharArray();
public static final char[] LITERAL_PL_ = "+".toCharArray();
public static final char[] LITERAL_PR_ = "%".toCharArray();
public static final char[] LITERAL_SIZE = "SIZE".toCharArray();
public static final char[] LITERAL_STR_ = "*".toCharArray();
public static final char[] LOW_VALUE_1253879107 = Field.fillLowValue(80);
public static final char[] LOW_VALUE_1253883912 = Field.fillLowValue(30);
public static final char[] LOW_VALUE_STRING = new String(new byte[]{0}).toCharArray();
 
}
