<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Group" cobol:name="WS-GROUP" cobol:offset="0" cobol:length="948" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="GroupWithoutValue" maxOccurs="1" cobol:name="WS-GROUP-WITHOUT-VALUE" cobol:offset="0" cobol:length="209" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="AGroupWithArray" maxOccurs="1" cobol:name="WS-A-GROUP-WITH-ARRAY" cobol:offset="209" cobol:length="418" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="GroupWithValue" maxOccurs="1" cobol:name="WS-GROUP-WITH-VALUE" cobol:offset="627" cobol:length="209" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="GroupWith88" maxOccurs="1" cobol:name="WS-GROUP-WITH-88" cobol:offset="836" cobol:length="112" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
