# Program OLDNEW | DD : SYS001 | RecordFormat : FixedLength | RecordLength : 80
OLDNEW.ddname.SYS001=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(+0)
OLDNEW.Sys001MipSpecrtOld=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(+0)
OLDNEW.Sys001MipSpecrtOld.DISP=SHR,KEEP,KEEP
OLDNEW.Sys001MipSpecrtOldCharSet=cp1047
OLDNEW.Sys001MipSpecrtOldCRLFflag=no
# Program OLDNEW | DD : SYS002 | RecordFormat : FixedLength | RecordLength : 80
OLDNEW.ddname.SYS002=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(+1)
OLDNEW.Sys002MipSpecrtNew=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(+1)
OLDNEW.Sys002MipSpecrtNew.DISP=SHR,KEEP,KEEP
OLDNEW.Sys002MipSpecrtNewCharSet=cp1047
OLDNEW.Sys002MipSpecrtNewCRLFflag=no
# 
# End of OLDNEW
# Program GDGPGM2 | DD : SYS001 | RecordFormat : FixedLength | RecordLength : 80
GDGPGM2.ddname.SYS001=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(+0)
GDGPGM2.Sys001MipSpecrtOld=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(+0)
GDGPGM2.Sys001MipSpecrtOld.DISP=SHR,KEEP,KEEP
GDGPGM2.Sys001MipSpecrtOldCharSet=cp1047
GDGPGM2.Sys001MipSpecrtOldCRLFflag=no
# Program GDGPGM2 | DD : SYS002 | RecordFormat : FixedLength | RecordLength : 80
GDGPGM2.ddname.SYS002=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(+1)
GDGPGM2.Sys002MipSpecrtNew=CLOUDFRM.SF.P3GX.PRSF2130.REBATE(+1)
GDGPGM2.Sys002MipSpecrtNew.DISP=SHR,KEEP,KEEP
GDGPGM2.Sys002MipSpecrtNewCharSet=cp1047
GDGPGM2.Sys002MipSpecrtNewCRLFflag=no
# Program GDGPGM2 | DD : SYS201 | RecordFormat : FixedLength | RecordLength : 80
GDGPGM2.ddname.SYS201=Sys201DownloadFile
GDGPGM2.Sys201DownloadFile=Sys201DownloadFile
GDGPGM2.Sys201DownloadFileCharSet=cp1047
GDGPGM2.Sys201DownloadFileCRLFflag=no
# Program GDGPGM2 | DD : SYS202 | RecordFormat : FixedLength | RecordLength : 80
GDGPGM2.ddname.SYS202=Sys202T0027aFileOut
GDGPGM2.Sys202T0027aFileOut=Sys202T0027aFileOut
GDGPGM2.Sys202T0027aFileOutCharSet=cp1047
GDGPGM2.Sys202T0027aFileOutCRLFflag=no
# End of GDGPGM2
