# Program CFSORT04 | DD : FILEIN | RecordFormat : FixedLength | RecordLength : 30
CFSORT04.ddname.FILEIN=FileIn
CFSORT04.FileIn=FileIn
CFSORT04.FileInCharSet=cp1047
CFSORT04.FileInCRLFflag=no
# Program CFSORT04 | DD : FILEOUT | RecordFormat : FixedLength | RecordLength : 30
CFSORT04.ddname.FILEOUT=FileOut
CFSORT04.FileOut=FileOut
CFSORT04.FileOutCharSet=cp1047
CFSORT04.FileOutCRLFflag=no
# 
# End of CFSORT04
