#
#STEP:STEP01| PGM:IDCAMS| DD:INDD
STEP01.IDCAMS.Indd=CLOUDFRM.IDCAMS.USB3QSAM(0)
STEP01.IDCAMS.Indd.DISP=OLD,KEEP,KEEP
STEP01.IDCAMS.Indd.RecordType=FB
STEP01.IDCAMS.Indd.RecordLen=80
#
#
#STEP:STEP01| PGM:IDCAMS| DD:OUTDD
STEP01.IDCAMS.Outdd=CLOUDFRM.IDCAMS.USB3QSAM.OUTPUT
STEP01.IDCAMS.Outdd.DISP=SHR,KEEP,KEEP
STEP01.IDCAMS.Outdd.RecordType=FB
STEP01.IDCAMS.Outdd.RecordLen=80
#
