<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip90354L1Ctlmtifunc" cobol:name="IP90354-L1-CTLMTIFUNC" cobol:offset="1" cobol:length="7" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip90354L1Ctlmti" type="xs:int" maxOccurs="1"  cobol:name="IP90354-L1-CTLMTI" cobol:offset="0" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
         <xs:element name="Ip90354L1Ctlfunc" type="xs:int" maxOccurs="1"  cobol:name="IP90354-L1-CTLFUNC" cobol:offset="4" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
