<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="PreEditVersionGroup300" cobol:name="300-PRE-EDIT-VERSION-GROUP" cobol:offset="0" cobol:length="7" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="PreEditVersion300" maxOccurs="1"  cobol:name="300-PRE-EDIT-VERSION" cobol:offset="0" cobol:length="7" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="PreEditVersion300Redefined" maxOccurs="1" cobol:name="300-PRE-EDIT-VERSION-REDEFINED" cobol:offset="0" cobol:length="7" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
