package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] FORMAT_1059277505 = "ZZZ9".toCharArray();
public static final char[] LITERAL_1 = "1".toCharArray();
public static final char[] LITERAL_B_TESTTESTTST = " TESTTESTTST".toCharArray();
public static final char[] LITERAL_HELLO_B_WORLD = "HELLO WORLD".toCharArray();
public static final char[] LITERAL_RS_B24_TEST = "RS TEST                       ".toCharArray();
public static final char[] LITERAL_TESTTESTTST_B_ = "TESTTESTTST ".toCharArray();
public static final char[] LITERAL_TEST_B2_DATAC = "TEST DATA C".toCharArray();
 
}
