<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="WcDay" cobol:name="WC-DAY" cobol:offset="1188" cobol:length="108" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="WcDayBbl" maxOccurs="1"  cobol:name="WC-DAY-BBL" cobol:offset="0" cobol:length="9" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="17" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WcDayKb" maxOccurs="1"  cobol:name="WC-DAY-KB" cobol:offset="9" cobol:length="9" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="17" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WcDayLit" maxOccurs="1"  cobol:name="WC-DAY-LIT" cobol:offset="18" cobol:length="9" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="17" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WcDayM3" maxOccurs="1"  cobol:name="WC-DAY-M3" cobol:offset="27" cobol:length="9" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="17" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WcDayUsg" maxOccurs="1"  cobol:name="WC-DAY-USG" cobol:offset="36" cobol:length="9" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="17" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WcDayUkg" maxOccurs="1"  cobol:name="WC-DAY-UKG" cobol:offset="45" cobol:length="9" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="17" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WcDayMmb" maxOccurs="1"  cobol:name="WC-DAY-MMB" cobol:offset="54" cobol:length="9" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="17" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WcDayGbt" maxOccurs="1"  cobol:name="WC-DAY-GBT" cobol:offset="63" cobol:length="9" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="17" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WcDayThm" maxOccurs="1"  cobol:name="WC-DAY-THM" cobol:offset="72" cobol:length="9" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="17" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WcDayMwh" maxOccurs="1"  cobol:name="WC-DAY-MWH" cobol:offset="81" cobol:length="9" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="17" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WcDayGj" maxOccurs="1"  cobol:name="WC-DAY-GJ" cobol:offset="90" cobol:length="9" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="17" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WcDayDay" maxOccurs="1"  cobol:name="WC-DAY-DAY" cobol:offset="99" cobol:length="9" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="17" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
