timeZoneId=Etc/GMT
# Program SF327010 | DD : SYS001 | RecordFormat : FixedLength | RecordLength : 75
SF327010.ddname.SYS001=Sys001ExtractZLogFile
SF327010.Sys001ExtractZLogFile=Sys001ExtractZLogFile
SF327010.Sys001ExtractZLogFileCharSet=cp1047
SF327010.Sys001ExtractZLogFileCRLFflag=no
# Program SF327010 | DD : SYS201 | RecordFormat : FixedLength | RecordLength : 132
SF327010.ddname.SYS201=Sys201AsaServerReport
SF327010.Sys201AsaServerReport=Sys201AsaServerReport
SF327010.Sys201AsaServerReportCharSet=cp1047
SF327010.Sys201AsaServerReportCRLFflag=no
# 
# End of SF327010
