<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Revo3TrailerRecord" cobol:name="REVO3-TRAILER-RECORD" cobol:offset="2" cobol:length="32" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Revo3TrlrRecordCount" type="xs:long" maxOccurs="1"  cobol:name="REVO3-TRLR-RECORD-COUNT" cobol:offset="20" cobol:length="12" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
