#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
#logging.level.com.cloudframe=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
#
WipromedicareSort001SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN001
WipromedicareSort001SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort001SortInRecordType=FB
WipromedicareSort001SortInRecordLen=80
#
WipromedicareSort001SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT001
WipromedicareSort001SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort001SortOutRecordType=FB
WipromedicareSort001SortOutRecordLen=80
#End of SORT001 step for SORT
#
WipromedicareSort002SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN002
WipromedicareSort002SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort002SortInRecordType=FB
WipromedicareSort002SortInRecordLen=80
#
WipromedicareSort002SortOut[0]=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0021
WipromedicareSort002SortOut[0].DISP=NEW,KEEP,KEEP
WipromedicareSort002SortOut[1]=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0022
WipromedicareSort002SortOut[1].DISP=NEW,KEEP,KEEP
WipromedicareSort002SortOutRecordType=FB
WipromedicareSort002SortOutRecordLen=80
#End of SORT002 step for SORT
#
WipromedicareSort003SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN003
WipromedicareSort003SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort003SortInRecordType=FB
WipromedicareSort003SortInRecordLen=300
#
WipromedicareSort003SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT003
WipromedicareSort003SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort003SortOutRecordType=FB
WipromedicareSort003SortOutRecordLen=300
#End of SORT003 step for SORT
#
WipromedicareSort004SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN004
WipromedicareSort004SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort004SortInRecordType=FB
WipromedicareSort004SortInRecordLen=300
#
WipromedicareSort004SortOut[0]=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0041
WipromedicareSort004SortOut[0].DISP=NEW,KEEP,KEEP
WipromedicareSort004SortOut[1]=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0042
WipromedicareSort004SortOut[1].DISP=NEW,KEEP,KEEP
WipromedicareSort004SortOutRecordType=FB
WipromedicareSort004SortOutRecordLen=300
#End of SORT004 step for SORT
#
WipromedicareSort005SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN005
WipromedicareSort005SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort005SortInRecordType=FB
WipromedicareSort005SortInRecordLen=470
#
WipromedicareSort005SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT005
WipromedicareSort005SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort005SortOutRecordType=FB
WipromedicareSort005SortOutRecordLen=470
#End of SORT005 step for SORT
#
WipromedicareSort006SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN006
WipromedicareSort006SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort006SortInRecordType=FBA
WipromedicareSort006SortInRecordLen=171
#
WipromedicareSort006SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT006
WipromedicareSort006SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort006SortOutRecordType=FB
WipromedicareSort006SortOutRecordLen=171
#End of SORT006 step for SORT
#
WipromedicareSort007SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN007
WipromedicareSort007SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort007SortInRecordType=FB
WipromedicareSort007SortInRecordLen=470
#
WipromedicareSort007SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT007
WipromedicareSort007SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort007SortOutRecordType=FB
WipromedicareSort007SortOutRecordLen=470
#End of SORT007 step for SORT
#
WipromedicareSort008SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN008
WipromedicareSort008SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort008SortInRecordType=FB
WipromedicareSort008SortInRecordLen=470
#
WipromedicareSort008SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT008
WipromedicareSort008SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort008SortOutRecordType=FB
WipromedicareSort008SortOutRecordLen=80
#End of SORT008 step for SORT
#
WipromedicareSort009SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN009
WipromedicareSort009SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort009SortInRecordType=FB
WipromedicareSort009SortInRecordLen=470
#
WipromedicareSort009SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT009
WipromedicareSort009SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort009SortOutRecordType=FB
WipromedicareSort009SortOutRecordLen=470
#End of SORT009 step for SORT
#
WipromedicareSort010SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT009
WipromedicareSort010SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort010SortInRecordType=FB
WipromedicareSort010SortInRecordLen=470
#
WipromedicareSort010SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT010
WipromedicareSort010SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort010SortOutRecordType=FB
WipromedicareSort010SortOutRecordLen=470
#End of SORT010 step for SORT
#
WipromedicareSort011SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN011
WipromedicareSort011SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort011SortInRecordType=FB
WipromedicareSort011SortInRecordLen=470
#
WipromedicareSort011SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT011
WipromedicareSort011SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort011SortOutRecordType=FB
WipromedicareSort011SortOutRecordLen=470
#End of SORT011 step for SORT
#
cf.sort.useTempFile=no
