#STEP:SORT001| PGM:SORT| DD:SORTIN
WipromedicareSort001SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN001
WipromedicareSort001SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort001SortInRecordType=FB
WipromedicareSort001SortInRecordLen=80
#STEP:SORT001| PGM:SORT| DD:SORTOUT
WipromedicareSort001SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0
WipromedicareSort001SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort001SortOutRecordType=FB
WipromedicareSort001SortOutRecordLen=<recordLen>
#STEP:SORT002| PGM:SORT| DD:SORTIN
WipromedicareSort002SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN002
WipromedicareSort002SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort002SortInRecordType=FB
WipromedicareSort002SortInRecordLen=80
#STEP:SORT002| PGM:SORT| DD:HDR
WipromedicareSort002SortOut[0]=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0
WipromedicareSort002SortOut[0].DISP=NEW,KEEP,KEEP
WipromedicareSort002SortOut0RecordType=FB
WipromedicareSort002SortOut0RecordLen=<recordLen>
#STEP:SORT002| PGM:SORT| DD:HDR
WipromedicareSort002SortOut[1]=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0
WipromedicareSort002SortOut[1].DISP=NEW,KEEP,KEEP
WipromedicareSort002SortOut1RecordType=FB
WipromedicareSort002SortOut1RecordLen=<recordLen>
#STEP:SORT003| PGM:SORT| DD:SORTIN
WipromedicareSort003SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN003
WipromedicareSort003SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort003SortInRecordType=FB
WipromedicareSort003SortInRecordLen=300
#STEP:SORT003| PGM:SORT| DD:SORTOUT
WipromedicareSort003SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0
WipromedicareSort003SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort003SortOutRecordType=FB
WipromedicareSort003SortOutRecordLen=<recordLen>
#STEP:SORT004| PGM:SORT| DD:SORTIN
WipromedicareSort004SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN004
WipromedicareSort004SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort004SortInRecordType=FB
WipromedicareSort004SortInRecordLen=300
#STEP:SORT004| PGM:SORT| DD:HDR
WipromedicareSort004SortOut[0]=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0
WipromedicareSort004SortOut[0].DISP=NEW,KEEP,KEEP
WipromedicareSort004SortOut0RecordType=FB
WipromedicareSort004SortOut0RecordLen=<recordLen>
#STEP:SORT004| PGM:SORT| DD:HDR
WipromedicareSort004SortOut[1]=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0
WipromedicareSort004SortOut[1].DISP=NEW,KEEP,KEEP
WipromedicareSort004SortOut1RecordType=FB
WipromedicareSort004SortOut1RecordLen=<recordLen>
#STEP:SORT005| PGM:SORT| DD:SORTIN
WipromedicareSort005SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN005
WipromedicareSort005SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort005SortInRecordType=FB
WipromedicareSort005SortInRecordLen=470
#STEP:SORT005| PGM:SORT| DD:SORTOUT
WipromedicareSort005SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0
WipromedicareSort005SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort005SortOutRecordType=FB
WipromedicareSort005SortOutRecordLen=<recordLen>
#STEP:SORT006| PGM:SORT| DD:SORTIN
WipromedicareSort006SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN006
WipromedicareSort006SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort006SortInRecordType=FBA
WipromedicareSort006SortInRecordLen=171
#STEP:SORT006| PGM:SORT| DD:SORTOUT
WipromedicareSort006SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0
WipromedicareSort006SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort006SortOutRecordType=FB
WipromedicareSort006SortOutRecordLen=<recordLen>
#STEP:SORT007| PGM:SORT| DD:SORTIN
WipromedicareSort007SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN007
WipromedicareSort007SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort007SortInRecordType=FB
WipromedicareSort007SortInRecordLen=470
#STEP:SORT007| PGM:SORT| DD:SORTOUT
WipromedicareSort007SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0
WipromedicareSort007SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort007SortOutRecordType=FB
WipromedicareSort007SortOutRecordLen=<recordLen>
#STEP:SORT008| PGM:SORT| DD:SORTIN
WipromedicareSort008SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN008
WipromedicareSort008SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort008SortInRecordType=FB
WipromedicareSort008SortInRecordLen=470
#STEP:SORT008| PGM:SORT| DD:SORTOUT
WipromedicareSort008SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0
WipromedicareSort008SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort008SortOutRecordType=FB
WipromedicareSort008SortOutRecordLen=<recordLen>
#STEP:SORT009| PGM:SORT| DD:SORTIN
WipromedicareSort009SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN009
WipromedicareSort009SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort009SortInRecordType=FB
WipromedicareSort009SortInRecordLen=470
#STEP:SORT009| PGM:SORT| DD:SORTOUT
WipromedicareSort009SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0
WipromedicareSort009SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort009SortOutRecordType=FB
WipromedicareSort009SortOutRecordLen=<recordLen>
#STEP:SORT010| PGM:SORT| DD:SORTIN
WipromedicareSort010SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT009
WipromedicareSort010SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort010SortInRecordType=FB
WipromedicareSort010SortInRecordLen=470
#STEP:SORT010| PGM:SORT| DD:SORTOUT
WipromedicareSort010SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0
WipromedicareSort010SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort010SortOutRecordType=FB
WipromedicareSort010SortOutRecordLen=<recordLen>
#STEP:SORT011| PGM:SORT| DD:SORTIN
WipromedicareSort011SortIn=CLOUDFRM.WIPRO.MEDICARE.SORT.IN011
WipromedicareSort011SortIn.DISP=SHR,KEEP,KEEP
WipromedicareSort011SortInRecordType=FB
WipromedicareSort011SortInRecordLen=470
#STEP:SORT011| PGM:SORT| DD:SORTOUT
WipromedicareSort011SortOut=CLOUDFRM.WIPRO.MEDICARE.SORT.OUT0
WipromedicareSort011SortOut.DISP=NEW,KEEP,KEEP
WipromedicareSort011SortOutRecordType=FB
WipromedicareSort011SortOutRecordLen=<recordLen>
