<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip570004TableEntry" cobol:name="IP570004-TABLE-ENTRY" cobol:offset="18" cobol:length="18" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip570004Tbl57PcCabGrpPtr" type="xs:long" maxOccurs="1"  cobol:name="IP570004-TBL57-PC-CAB-GRP-PTR" cobol:offset="0" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
<xs:element name="Ip570004Tbl57PointerData" maxOccurs="1" cobol:name="IP570004-TBL57-POINTER-DATA" cobol:offset="6" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
