GLOBAL.ddname.UREQPT00=UREQPT00
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
GLOBAL.ddname.PLNVAR00=PLNVAR00
GLOBAL.ddname.SPIRUL00=SPIRUL00
# 
# End of O529351U
inputValue1=
D529351U.dbQualifier=
# End of D529351U
