# Program CFSORT03 | DD : FILEIN | RecordFormat : FixedLength | RecordLength : 80
CFSORT03.ddname.FILEIN=FileIn
CFSORT03.FileIn=FileIn
CFSORT03.FileInCharSet=cp1047
CFSORT03.FileInCRLFflag=no
# Program CFSORT03 | DD : FILEOUT | RecordFormat : FixedLength | RecordLength : 80
CFSORT03.ddname.FILEOUT=FileOut
CFSORT03.FileOut=FileOut
CFSORT03.FileOutCharSet=cp1047
CFSORT03.FileOutCRLFflag=no
# 
# End of CFSORT03
