<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Ip40005GroupStatusRec" cobol:name="IP40005-GROUP-STATUS-REC" cobol:offset="0" cobol:length="2000" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Ip40005GrpFileSeqNbr" type="xs:int" maxOccurs="1"  cobol:name="IP40005-GRP-FILE-SEQ-NBR" cobol:offset="1" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="Ip40005GroupSeqNum" type="xs:long" maxOccurs="1"  cobol:name="IP40005-GROUP-SEQ-NUM" cobol:offset="29" cobol:length="4" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
