#STEP:PRGP4511_STEP11A| PGM:SORT| DD:SORTJNF1
Sgp7344dPrgp4511_step11aSortIn[0]=DTF.GP.P2BX.TGPAUKD.AKF.EXT
Sgp7344dPrgp4511_step11aSortIn[0].DISP=SHR,KEEP,KEEP
Sgp7344dPrgp4511_step11aSortIn0RecordType=FB
Sgp7344dPrgp4511_step11aSortIn0RecordLen=300
#STEP:PRGP4511_STEP11A| PGM:SORT| DD:SORTJNF2
Sgp7344dPrgp4511_step11aSortIn[1]=DTF.GP.P2BX.TGPAUKD.AKF.LOAD
Sgp7344dPrgp4511_step11aSortIn[1].DISP=SHR,KEEP,KEEP
Sgp7344dPrgp4511_step11aSortIn1RecordType=FB
Sgp7344dPrgp4511_step11aSortIn1RecordLen=300
#STEP:PRGP4511_STEP11A| PGM:SORT| DD:SORTOUT
Sgp7344dPrgp4511_step11aSortOut=DTF.GP.P2BX.TGPAUKD.AKF.UNPAIRED
Sgp7344dPrgp4511_step11aSortOut.DISP=NEW,CATLG,DELETE
Sgp7344dPrgp4511_step11aSortOutRecordType=FB
Sgp7344dPrgp4511_step11aSortOutRecordLen=128
#STEP:PRGP4511_STEP11B| PGM:SORT| DD:SORTIN
Sgp7344dPrgp4511_step11bSortIn[0]=DTF.GP.P2BX.TGPAUKD.AKF.UNPAIRED
Sgp7344dPrgp4511_step11bSortIn[0].DISP=SHR,KEEP,KEEP
Sgp7344dPrgp4511_step11bSortIn0RecordType=FB
Sgp7344dPrgp4511_step11bSortIn0RecordLen=128
#STEP:PRGP4511_STEP11B| PGM:SORT| DD:SORTIN
Sgp7344dPrgp4511_step11bSortIn[1]=DTF.GP.P2BX.TNR0.EXTRACT.INTERM
Sgp7344dPrgp4511_step11bSortIn[1].DISP=SHR,KEEP,KEEP
Sgp7344dPrgp4511_step11bSortIn1RecordType=FB
Sgp7344dPrgp4511_step11bSortIn1RecordLen=128
#STEP:PRGP4511_STEP11B| PGM:SORT| DD:SORTOUT
Sgp7344dPrgp4511_step11bSortOut=DTF.GP.P3GX.TNR0.EXTRACT(+1)
Sgp7344dPrgp4511_step11bSortOut.DISP=NEW,CATLG,DELETE
Sgp7344dPrgp4511_step11bSortOutRecordType=FB
Sgp7344dPrgp4511_step11bSortOutRecordLen=128
