<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Pe8090p" cobol:name="PE8090P" cobol:offset="0" cobol:length="11870" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="Pe8090r" maxOccurs="50" cobol:name="PE8090R" cobol:offset="0" cobol:length="233" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Pe00tc00" maxOccurs="1"  cobol:name="PE00TC00" cobol:offset="11650" cobol:length="100" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Pe00tc01" maxOccurs="1"  cobol:name="PE00TC01" cobol:offset="11750" cobol:length="60" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Pe00tc02" maxOccurs="1"  cobol:name="PE00TC02" cobol:offset="11810" cobol:length="60" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
