<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Section" cobol:name="WS-SECTION" cobol:offset="0" cobol:length="3168" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="WIndxTitular" type="xs:int" maxOccurs="1"  cobol:name="W-INDX-TITULAR" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="WTotTit" type="xs:int" maxOccurs="1"  cobol:name="W-TOT-TIT" cobol:offset="2" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WPriTitu" maxOccurs="1"  cobol:name="W-PRI-TITU" cobol:offset="4" cobol:length="60" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WLonPriTitu" type="xs:int" maxOccurs="1"  cobol:name="W-LON-PRI-TITU" cobol:offset="64" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WSegTitu" maxOccurs="1"  cobol:name="W-SEG-TITU" cobol:offset="66" cobol:length="60" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WLonSegTitu" type="xs:int" maxOccurs="1"  cobol:name="W-LON-SEG-TITU" cobol:offset="126" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WTitCtaPe8090m" maxOccurs="1"  cobol:name="W-TIT-CTA-PE8090M" cobol:offset="128" cobol:length="100" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WPriTroPe8090m" maxOccurs="1"  cobol:name="W-PRI-TRO-PE8090M" cobol:offset="228" cobol:length="50" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="50" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WSegTroPe8090m" maxOccurs="1"  cobol:name="W-SEG-TRO-PE8090M" cobol:offset="278" cobol:length="50" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="50" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WTitCtaAux" maxOccurs="1"  cobol:name="W-TIT-CTA-AUX" cobol:offset="328" cobol:length="100" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WPriTroAux" maxOccurs="1"  cobol:name="W-PRI-TRO-AUX" cobol:offset="428" cobol:length="50" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="50" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WSegTroAux" maxOccurs="1"  cobol:name="W-SEG-TRO-AUX" cobol:offset="478" cobol:length="50" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="50" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WTpePe8090m" maxOccurs="1" cobol:name="W-TPE-PE8090M" cobol:offset="528" cobol:length="1824" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WTobPe8090m" maxOccurs="1" cobol:name="W-TOB-PE8090M" cobol:offset="2352" cobol:length="32" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WDatVarPe8090m" maxOccurs="1" cobol:name="W-DAT-VAR-PE8090M" cobol:offset="2384" cobol:length="24" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WZonAlmPe8090m" maxOccurs="1" cobol:name="W-ZON-ALM-PE8090M" cobol:offset="2408" cobol:length="196" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WIniNomaPe8090m" maxOccurs="1" cobol:name="W-INI-NOMA-PE8090M" cobol:offset="2604" cobol:length="60" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WIniNomrPe8090m" maxOccurs="1" cobol:name="W-INI-NOMR-PE8090M" cobol:offset="2604" cobol:length="60" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WZonFpfPe8090m" maxOccurs="1" cobol:name="W-ZON-FPF-PE8090M" cobol:offset="2664" cobol:length="26" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WAstPapPe8090m" maxOccurs="1" cobol:name="W-AST-PAP-PE8090M" cobol:offset="2690" cobol:length="20" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WAstJurPe8090m" maxOccurs="1" cobol:name="W-AST-JUR-PE8090M" cobol:offset="2710" cobol:length="60" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="WImpPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-IMP-PE8090M" cobol:offset="2770" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WTitulPe8090m" maxOccurs="1"  cobol:name="W-TITUL-PE8090M" cobol:offset="2772" cobol:length="140" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="140" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WIniNomPe8090m" maxOccurs="1" cobol:name="W-INI-NOM-PE8090M" cobol:offset="2912" cobol:length="20" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="WNumPerFisPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-NUM-PER-FIS-PE8090M" cobol:offset="2932" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
<xs:element name="WMcas3Pe8090m" maxOccurs="1" cobol:name="W-MCAS3-PE8090M" cobol:offset="2934" cobol:length="9" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcas3aPe8090m" maxOccurs="1" cobol:name="W-MCAS3A-PE8090M" cobol:offset="2943" cobol:length="10" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcas3bPe8090m" maxOccurs="1" cobol:name="W-MCAS3B-PE8090M" cobol:offset="2953" cobol:length="11" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcat3Pe8090m" maxOccurs="1" cobol:name="W-MCAT3-PE8090M" cobol:offset="2964" cobol:length="9" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcat3aPe8090m" maxOccurs="1" cobol:name="W-MCAT3A-PE8090M" cobol:offset="2973" cobol:length="10" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcat3bPe8090m" maxOccurs="1" cobol:name="W-MCAT3B-PE8090M" cobol:offset="2983" cobol:length="11" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcas6Pe8090m" maxOccurs="1" cobol:name="W-MCAS6-PE8090M" cobol:offset="2994" cobol:length="15" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcas6aPe8090m" maxOccurs="1" cobol:name="W-MCAS6A-PE8090M" cobol:offset="3009" cobol:length="16" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcas6bPe8090m" maxOccurs="1" cobol:name="W-MCAS6B-PE8090M" cobol:offset="3025" cobol:length="17" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcat6Pe8090m" maxOccurs="1" cobol:name="W-MCAT6-PE8090M" cobol:offset="3042" cobol:length="15" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcat6aPe8090m" maxOccurs="1" cobol:name="W-MCAT6A-PE8090M" cobol:offset="3057" cobol:length="16" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcat6bPe8090m" maxOccurs="1" cobol:name="W-MCAT6B-PE8090M" cobol:offset="3073" cobol:length="17" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcas7Pe8090m" maxOccurs="1" cobol:name="W-MCAS7-PE8090M" cobol:offset="3090" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcas7aPe8090m" maxOccurs="1" cobol:name="W-MCAS7A-PE8090M" cobol:offset="3102" cobol:length="13" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcas7bPe8090m" maxOccurs="1" cobol:name="W-MCAS7B-PE8090M" cobol:offset="3115" cobol:length="14" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcat7Pe8090m" maxOccurs="1" cobol:name="W-MCAT7-PE8090M" cobol:offset="3129" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcat7aPe8090m" maxOccurs="1" cobol:name="W-MCAT7A-PE8090M" cobol:offset="3141" cobol:length="13" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="WMcat7bPe8090m" maxOccurs="1" cobol:name="W-MCAT7B-PE8090M" cobol:offset="3154" cobol:length="14" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
