<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="WElpPe8090m" cobol:name="W-ELP-PE8090M" cobol:offset="528" cobol:length="228" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="WTipPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-TIP-PE8090M" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="WIeqPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-IEQ-PE8090M" cobol:offset="2" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WNomPe8090m" maxOccurs="1"  cobol:name="W-NOM-PE8090M" cobol:offset="4" cobol:length="62" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="62" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WNcaNomPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-NCA-NOM-PE8090M" cobol:offset="66" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WNo1Pe8090m" maxOccurs="1"  cobol:name="W-NO1-PE8090M" cobol:offset="68" cobol:length="40" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="40" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WNcaNo1Pe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-NCA-NO1-PE8090M" cobol:offset="108" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WNo2Pe8090m" maxOccurs="1"  cobol:name="W-NO2-PE8090M" cobol:offset="110" cobol:length="24" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="24" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WNcaNo2Pe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-NCA-NO2-PE8090M" cobol:offset="134" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="WNsePerPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-NSE-PER-PE8090M" cobol:offset="136" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="WIsePe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-ISE-PE8090M" cobol:offset="138" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WMasSepPe8090m" maxOccurs="1"  cobol:name="W-MAS-SEP-PE8090M" cobol:offset="140" cobol:length="18" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WTmaSepPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-TMA-SEP-PE8090M" cobol:offset="158" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="WNmaSepPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-NMA-SEP-PE8090M" cobol:offset="160" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="WPerGruPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-PER-GRU-PE8090M" cobol:offset="162" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="WTpeNrePe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-TPE-NRE-PE8090M" cobol:offset="164" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WNomNrePe8090m" maxOccurs="1"  cobol:name="W-NOM-NRE-PE8090M" cobol:offset="166" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WPraNrePe8090m" maxOccurs="1"  cobol:name="W-PRA-NRE-PE8090M" cobol:offset="186" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WSeaNrePe8090m" maxOccurs="1"  cobol:name="W-SEA-NRE-PE8090M" cobol:offset="206" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WCpeNomPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-CPE-NOM-PE8090M" cobol:offset="226" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
