<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="WZonAlmPe8090m" cobol:name="W-ZON-ALM-PE8090M" cobol:offset="2408" cobol:length="196" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="WTipAlmPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-TIP-ALM-PE8090M" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="WIeqAlmPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-IEQ-ALM-PE8090M" cobol:offset="2" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WNomAlmPe8090m" maxOccurs="1"  cobol:name="W-NOM-ALM-PE8090M" cobol:offset="4" cobol:length="60" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WNcnAlmPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-NCN-ALM-PE8090M" cobol:offset="64" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WNo1AlmPe8090m" maxOccurs="1"  cobol:name="W-NO1-ALM-PE8090M" cobol:offset="66" cobol:length="40" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="40" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WNc1AlmPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-NC1-ALM-PE8090M" cobol:offset="106" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WNo2AlmPe8090m" maxOccurs="1"  cobol:name="W-NO2-ALM-PE8090M" cobol:offset="108" cobol:length="24" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="24" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WNc2AlmPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-NC2-ALM-PE8090M" cobol:offset="132" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WNreAlmPe8090m" maxOccurs="1"  cobol:name="W-NRE-ALM-PE8090M" cobol:offset="134" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WPraAlmPe8090m" maxOccurs="1"  cobol:name="W-PRA-ALM-PE8090M" cobol:offset="154" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WSeaAlmPe8090m" maxOccurs="1"  cobol:name="W-SEA-ALM-PE8090M" cobol:offset="174" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WCpeAlmPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-CPE-ALM-PE8090M" cobol:offset="194" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
