<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="WZonFpfPe8090m" cobol:name="W-ZON-FPF-PE8090M" cobol:offset="2664" cobol:length="26" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="WNupFpfPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-NUP-FPF-PE8090M" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="WTipFpfPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-TIP-FPF-PE8090M" cobol:offset="2" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="WMasFpfPe8090m" maxOccurs="1"  cobol:name="W-MAS-FPF-PE8090M" cobol:offset="4" cobol:length="18" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WTmaFpfPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-TMA-FPF-PE8090M" cobol:offset="22" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="WNcmFpfPe8090m" type="xs:int" maxOccurs="1"  cobol:name="W-NCM-FPF-PE8090M" cobol:offset="24" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
