#STEP:SORT241A_S0011| PGM:SORT| DD:SORTIN
Sort241Sort241a_s0011SortIn[0]=CLOUDFRM.MS.SORT.IN241.PART1
Sort241Sort241a_s0011SortIn[0].DISP=SHR,KEEP,KEEP
Sort241Sort241a_s0011SortIn0RecordType=FB
Sort241Sort241a_s0011SortIn0RecordLen=255
#STEP:SORT241A_S0011| PGM:SORT| DD:SORTIN
Sort241Sort241a_s0011SortIn[1]=CLOUDFRM.MS.SORT.IN241.PART2
Sort241Sort241a_s0011SortIn[1].DISP=SHR,KEEP,KEEP
Sort241Sort241a_s0011SortIn1RecordType=FB
Sort241Sort241a_s0011SortIn1RecordLen=255
#STEP:SORT241A_S0011| PGM:SORT| DD:SORTOUT
Sort241Sort241a_s0011SortOut=<Please enter SORTOUT file name>
Sort241Sort241a_s0011SortOutRecordType=FB
Sort241Sort241a_s0011SortOutRecordLen=255
#STEP:SORT241B_S0011| PGM:SORT| DD:SORTIN
Sort241Sort241b_s0011SortIn[0]=CLOUDFRM.MS.SORT.IN241.PART1OVR
Sort241Sort241b_s0011SortIn[0].DISP=SHR,KEEP,KEEP
Sort241Sort241b_s0011SortIn0RecordType=FB
Sort241Sort241b_s0011SortIn0RecordLen=255
#STEP:SORT241B_S0011| PGM:SORT| DD:SORTIN
Sort241Sort241b_s0011SortIn[1]=CLOUDFRM.MS.SORT.IN241.PART2
Sort241Sort241b_s0011SortIn[1].DISP=SHR,KEEP,KEEP
Sort241Sort241b_s0011SortIn1RecordType=FB
Sort241Sort241b_s0011SortIn1RecordLen=255
#STEP:SORT241B_S0011| PGM:SORT| DD:SORTOUT
Sort241Sort241b_s0011SortOut=<Please enter SORTOUT file name>
Sort241Sort241b_s0011SortOutRecordType=FB
Sort241Sort241b_s0011SortOutRecordLen=255
#STEP:SORT241C_S0011| PGM:SORT| DD:SORTIN
Sort241Sort241c_s0011SortIn[0]=CLOUDFRM.MS.SORT.IN241.PART1
Sort241Sort241c_s0011SortIn[0].DISP=SHR,KEEP,KEEP
Sort241Sort241c_s0011SortIn0RecordType=FB
Sort241Sort241c_s0011SortIn0RecordLen=255
#STEP:SORT241C_S0011| PGM:SORT| DD:SORTIN
Sort241Sort241c_s0011SortIn[1]=CLOUDFRM.MS.SORT.IN241.PART2OVR
Sort241Sort241c_s0011SortIn[1].DISP=SHR,KEEP,KEEP
Sort241Sort241c_s0011SortIn1RecordType=FB
Sort241Sort241c_s0011SortIn1RecordLen=255
#STEP:SORT241C_S0011| PGM:SORT| DD:SORTOUT
Sort241Sort241c_s0011SortOut=<Please enter SORTOUT file name>
Sort241Sort241c_s0011SortOutRecordType=FB
Sort241Sort241c_s0011SortOutRecordLen=255
#STEP:SORT241D_S0011| PGM:SORT| DD:SORTIN
Sort241Sort241d_s0011SortIn[0]=CLOUDFRM.MS.SORT.IN241.PART1OVR
Sort241Sort241d_s0011SortIn[0].DISP=SHR,KEEP,KEEP
Sort241Sort241d_s0011SortIn0RecordType=FB
Sort241Sort241d_s0011SortIn0RecordLen=255
#STEP:SORT241D_S0011| PGM:SORT| DD:SORTIN
Sort241Sort241d_s0011SortIn[1]=CLOUDFRM.MS.SORT.IN241.PART2OVR
Sort241Sort241d_s0011SortIn[1].DISP=SHR,KEEP,KEEP
Sort241Sort241d_s0011SortIn1RecordType=FB
Sort241Sort241d_s0011SortIn1RecordLen=255
#STEP:SORT241D_S0011| PGM:SORT| DD:SORTOUT
Sort241Sort241d_s0011SortOut=<Please enter SORTOUT file name>
Sort241Sort241d_s0011SortOutRecordType=FB
Sort241Sort241d_s0011SortOutRecordLen=255
#STEP:SORT241E_S0011| PGM:SORT| DD:SORTIN
Sort241Sort241e_s0011SortIn[0]=CLOUDFRM.MS.SORT.IN241.PART1OVR
Sort241Sort241e_s0011SortIn[0].DISP=SHR,KEEP,KEEP
Sort241Sort241e_s0011SortIn0RecordType=FB
Sort241Sort241e_s0011SortIn0RecordLen=255
#STEP:SORT241E_S0011| PGM:SORT| DD:SORTIN
Sort241Sort241e_s0011SortIn[1]=CLOUDFRM.MS.SORT.IN241.PART2
Sort241Sort241e_s0011SortIn[1].DISP=SHR,KEEP,KEEP
Sort241Sort241e_s0011SortIn1RecordType=FB
Sort241Sort241e_s0011SortIn1RecordLen=255
#STEP:SORT241E_S0011| PGM:SORT| DD:SORTOUT
Sort241Sort241e_s0011SortOut=<Please enter SORTOUT file name>
Sort241Sort241e_s0011SortOutRecordType=FB
Sort241Sort241e_s0011SortOutRecordLen=255
