<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Work" cobol:name="work" cobol:offset="0" cobol:length="249" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="W03a1DiComp3" type="xs:long" maxOccurs="1"  cobol:name="W03A-1-DI-COMP3" cobol:offset="0" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="W03a1DiComp" type="xs:int" maxOccurs="1"  cobol:name="W03A-1-DI-COMP" cobol:offset="8" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="W03a1DiDecimal" maxOccurs="1"  cobol:name="W03A-1-DI-DECIMAL" cobol:offset="8" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="9" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="W03a1DiSmallint" type="xs:short" maxOccurs="1"  cobol:name="W03A-1-DI-SMALLINT" cobol:offset="13" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="W03a1DiInt" type="xs:int" maxOccurs="1"  cobol:name="W03A-1-DI-INT" cobol:offset="13" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="W03a1DiBigint" type="xs:long" maxOccurs="1"  cobol:name="W03A-1-DI-BIGINT" cobol:offset="13" cobol:length="8" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="W03a1DiReal" maxOccurs="1"  cobol:name="W03A-1-DI-REAL" cobol:offset="13" cobol:length="4" cobol:datatype="Comp-1" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="0" />
                  <xs:fractionDigits value="0" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="W03a1DiDouble" maxOccurs="1"  cobol:name="W03A-1-DI-DOUBLE" cobol:offset="17" cobol:length="8" cobol:datatype="Comp-2" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="0" />
                  <xs:fractionDigits value="0" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="W03a1DoComp3" type="xs:long" maxOccurs="1"  cobol:name="W03A-1-DO-COMP3" cobol:offset="25" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P"/>
         <xs:element name="W03a1DoComp" type="xs:int" maxOccurs="1"  cobol:name="W03A-1-DO-COMP" cobol:offset="33" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="W03a1DoDecimal" maxOccurs="1"  cobol:name="W03A-1-DO-DECIMAL" cobol:offset="33" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="9" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="W03a1DoSmallint" type="xs:short" maxOccurs="1"  cobol:name="W03A-1-DO-SMALLINT" cobol:offset="38" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="W03a1DoInt" type="xs:int" maxOccurs="1"  cobol:name="W03A-1-DO-INT" cobol:offset="38" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="W03a1DoBigint" type="xs:long" maxOccurs="1"  cobol:name="W03A-1-DO-BIGINT" cobol:offset="38" cobol:length="8" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="W03a1DoReal" maxOccurs="1"  cobol:name="W03A-1-DO-REAL" cobol:offset="38" cobol:length="4" cobol:datatype="Comp-1" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="0" />
                  <xs:fractionDigits value="0" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="W03a1DoDouble" maxOccurs="1"  cobol:name="W03A-1-DO-DOUBLE" cobol:offset="42" cobol:length="8" cobol:datatype="Comp-2" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="0" />
                  <xs:fractionDigits value="0" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="HvStartDt81d" type="xs:long" maxOccurs="1"  cobol:name="HV-START-DT8-1D" cobol:offset="50" cobol:length="8" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
         <xs:element name="IntOfDt1" type="xs:int" maxOccurs="1"  cobol:name="WS-INT-OF-DT-1" cobol:offset="58" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
    <xs:element name="Tb11148AdminAmt" maxOccurs="1"  cobol:name="TB11148-ADMIN-AMT" cobol:offset="63" cobol:length="5" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="9" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="TotAmt" maxOccurs="1"  cobol:name="WS-TOT-AMT" cobol:offset="68" cobol:length="8" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="11" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Rlu3aMtnAcAcctChgsCredits" maxOccurs="1"  cobol:name="RLU3A-MTN-AC-ACCT-CHGS-CREDITS" cobol:offset="68" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="11" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ChrgCreditTotNotax" maxOccurs="1"  cobol:name="WS-CHRG-CREDIT-TOT-NOTAX" cobol:offset="74" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="11" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="W5v5A" maxOccurs="1"  cobol:name="W-5V5-A" cobol:offset="80" cobol:length="10" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="10" />
                  <xs:fractionDigits value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="W5v5" maxOccurs="1"  cobol:name="W-5V5" cobol:offset="90" cobol:length="10" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="10" />
                  <xs:fractionDigits value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="W3v2A" maxOccurs="1"  cobol:name="W-3V2-A" cobol:offset="100" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="5" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="W3v2" maxOccurs="1"  cobol:name="W-3V2" cobol:offset="105" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="5" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="W3v2Result" maxOccurs="1"  cobol:name="W-3V2-RESULT" cobol:offset="110" cobol:length="5" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="5" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Pmslk402ListPrice" maxOccurs="1"  cobol:name="PMSLK402-LIST-PRICE" cobol:offset="115" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="11" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WFeePromoxAmt" maxOccurs="1"  cobol:name="W-FEE-PROMOX-AMT" cobol:offset="121" cobol:length="4" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="7" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WChgAmtDec5" maxOccurs="1"  cobol:name="W-CHG-AMT-DEC5" cobol:offset="125" cobol:length="7" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1T">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WcdloLeapYear" maxOccurs="1"  cobol:name="WCDLO-LEAP-YEAR" cobol:offset="132" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1M">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="6" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WcdliCurYyyy" type="xs:int" maxOccurs="1"  cobol:name="WCDLI-CUR-YYYY" cobol:offset="138" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
    <xs:element name="W1" maxOccurs="1"  cobol:name="W1" cobol:offset="142" cobol:length="8" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="11" />
                  <xs:fractionDigits value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="W2" maxOccurs="1"  cobol:name="W2" cobol:offset="142" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="7" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="W3" maxOccurs="1"  cobol:name="W3" cobol:offset="142" cobol:length="8" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="12" />
                  <xs:fractionDigits value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="W4" maxOccurs="1"  cobol:name="W4" cobol:offset="142" cobol:length="4" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="6" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="W5" type="xs:int" maxOccurs="1"  cobol:name="W5" cobol:offset="142" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="CcatTitleSize" type="xs:int" maxOccurs="1"  cobol:name="CCAT-TITLE-SIZE" cobol:offset="142" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="CcatCombinedSize" type="xs:int" maxOccurs="1"  cobol:name="CCAT-COMBINED-SIZE" cobol:offset="142" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="PctWoPrice" maxOccurs="1"  cobol:name="WS-PCT-WO-PRICE" cobol:offset="142" cobol:length="11" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="11" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="PctWithNoPrice" maxOccurs="1"  cobol:name="WS-PCT-WITH-NO-PRICE" cobol:offset="153" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="5" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="RecsWithoutPrice" type="xs:long" maxOccurs="1"  cobol:name="WS-RECS-WITHOUT-PRICE" cobol:offset="156" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
         <xs:element name="DetailRecs" type="xs:long" maxOccurs="1"  cobol:name="WS-DETAIL-RECS" cobol:offset="162" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
    <xs:element name="F" maxOccurs="1"  cobol:name="F" cobol:offset="168" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="11" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="A" maxOccurs="1"  cobol:name="A" cobol:offset="179" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="9" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="B" maxOccurs="1"  cobol:name="B" cobol:offset="188" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="11" />
                  <xs:fractionDigits value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="C" maxOccurs="1"  cobol:name="C" cobol:offset="194" cobol:length="6" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="11" />
                  <xs:fractionDigits value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="D" maxOccurs="1"  cobol:name="D" cobol:offset="200" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="9" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="E" maxOccurs="1"  cobol:name="E" cobol:offset="209" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="11" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="CoordinatedGeneration" type="xs:int" maxOccurs="1"  cobol:name="WS-COORDINATED-GENERATION" cobol:offset="220" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="ReportGen" type="xs:int" maxOccurs="1"  cobol:name="WS-REPORT-GEN" cobol:offset="223" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="CbsumGen" type="xs:int" maxOccurs="1"  cobol:name="WS-CBSUM-GEN" cobol:offset="226" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="OmsumpvGen" type="xs:int" maxOccurs="1"  cobol:name="WS-OMSUMPV-GEN" cobol:offset="229" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="OmauditGen" type="xs:int" maxOccurs="1"  cobol:name="WS-OMAUDIT-GEN" cobol:offset="232" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="OmencfGen" type="xs:int" maxOccurs="1"  cobol:name="WS-OMENCF-GEN" cobol:offset="235" cobol:length="3" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1000"/>
         <xs:element name="DecimalNo300" type="xs:long" maxOccurs="1"  cobol:name="300-DECIMAL-NO" cobol:offset="238" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
