#
#STEP:MERGE| PGM:ICETOOL| DD:IN1, IN2, IN3
Icet020MergeSortIn[0]=CLOUDFRM.MC.SORT.IN0201
Icet020MergeSortIn[0].DISP=SHR,KEEP,KEEP
Icet020MergeSortIn[1]=CLOUDFRM.MC.SORT.IN0202
Icet020MergeSortIn[1].DISP=SHR,KEEP,KEEP
Icet020MergeSortIn[2]=CLOUDFRM.MC.SORT.IN0203
Icet020MergeSortIn[2].DISP=SHR,KEEP,KEEP
Icet020MergeSortInRecordType=FB
Icet020MergeSortInRecordLen=<recordLen>
#
#
#STEP:MERGE| PGM:ICETOOL| DD:OUT
Icet020MergeSortOut=CLOUDFRM.MC.SORT.OUT020
Icet020MergeSortOut.DISP=NEW,KEEP,KEEP
Icet020MergeSortOutRecordType=FB
Icet020MergeSortOutRecordLen=<recordLen>
#
