<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="SyntaxPgmTableGroup500" cobol:name="500-SYNTAX-PGM-TABLE-GROUP" cobol:offset="0" cobol:length="144" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="SyntaxPgmTable500" maxOccurs="1" cobol:name="500-SYNTAX-PGM-TABLE" cobol:offset="0" cobol:length="144" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="SyntaxPgmRedTable500" maxOccurs="1" cobol:name="500-SYNTAX-PGM-RED-TABLE" cobol:offset="0" cobol:length="144" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
