#common-test-properties
spring.main.log-startup-info=OFF
logging.pattern.file=%msg%n
logging.file.name=QA275.log
logging.logback.rollingpolicy.clean-history-on-start=true
logging.level.com.zaxxer=OFF
logging.level.com.cloudframe.app.dao.CFDataSourceConfiguration=OFF
logging.level.com.cloudframe.app.vsam.VSAMClusterUtil=OFF
logging.level.com.cloudframe.app.utility.CFConfiguration=OFF
#test-specific-properties
# compare.files[0]=ExpSys201ServiceReport,Sys201ServiceReport
#compare.files[1]=Exp_QA275_log,QA275.log
#project-specific-properties
#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
# spring.main.lazy-initialization=true
timeZoneId=Etc/GMT
SF328010.ddname.SYS001=SYS001
SF328010.Sys001ZLogFile=SYS001
SF328010.Sys001ZLogFileCharSet=cp1047
SF328010.Sys001ZLogFileCRLFflag=no
SF328010.ddname.SYS201=Sys201ServiceReport
SF328010.Sys201ServiceReport=Sys201ServiceReport
SF328010.Sys201ServiceReportCharSet=utf-8
SF328010.Sys201ServiceReportCRLFflag=yes
#logging.level.com.cloudframe=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
# 
# End of SF328010
