<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Sys209RecordCount600" cobol:name="600-SYS209-RECORD-COUNT" cobol:offset="0" cobol:length="73" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Sys209RecordCount600Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="0" cobol:length="60" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="60" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sys209Count1600" maxOccurs="1"  cobol:name="600-SYS209-COUNT1" cobol:offset="60" cobol:length="13" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="13" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
