  package com.cloudframe.app.process.impl;
  /* Java code generated by CloudFrame on 2025-04-24 at 16:28. */
  
  import com.cloudframe.app.ip224620.Ip224620Ctx.*;
  import com.cloudframe.app.ip224620.Ip224620Ctx;
  import com.cloudframe.app.process.Ip224620;
  import com.cloudframe.app.process.BaseProcess;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.dto.GlobalExecutorCtx;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.ip224620.dto.*;
  import com.cloudframe.app.ip224620.dto.AbendParaName900;
  import com.cloudframe.app.ip224620.dto.AbendMessage900;
  import com.cloudframe.app.ip224620.dto.Pds501Value800;
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.beans.factory.annotation.Qualifier;
  import com.cloudframe.app.global.sharedvar.Ip30331FinAddndmEntries;
  import com.cloudframe.app.global.sharedvar.McIpmMsg;
  import com.cloudframe.app.ip224620.dto.Pds501S1s2s3Entries500;
  import com.cloudframe.app.ip224620.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("ip224620")
  
  public class Ip224620Impl extends CommonProcess implements Ip224620 {
  
  Logger logger = LoggerFactory.getLogger(Ip224620Impl.class);
  
  
  
  
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      public int process(Ip224620Ctx programCtx) throws Exception {
       try {
       setCodePage("1047");
            // Reset program ended flag
           programCtx.setProgramEnded(false);
          ;
//  PERFORM 0000-MAINLINE
          mainline(programCtx);/*0000-MAINLINE*/
          if (programCtx.isProgramEnded()) {
              return programCtx.getRc();
          }
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
       return programCtx.getRc(); // Exit with return code
      // end of process method
      }
      /**
      * mainline 
      *   This method is derived from 
  *   COBOL Paragraph - 0000-MAINLINE COBOL Cyclomatic complexity - 2
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      @Override
      public void mainline(Ip224620Ctx programCtx) throws Exception {
//  PERFORM 1000-PERFORM-INITIALIZATION
          performInitialization(programCtx.getPerformInitializationInCtx());/*1000-PERFORM-INITIALIZATION*/
          if (programCtx.isProgramEnded()) {
              return ;
          }
//  PERFORM 2000-PERFORM-EDIT
          performEdit(programCtx.getPerformEditInCtx());/*2000-PERFORM-EDIT*/
          if (programCtx.isProgramEnded()) {
              return ;
          }
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          programCtx.setProgramEnded(true);
          return ;
      
      }
      /**
      * performInitialization 
      *   This method is derived from 
  *   COBOL Paragraph - 1000-PERFORM-INITIALIZATION COBOL Cyclomatic complexity - 3
      * Input  :  

      * - isItTheFirstTime100            COBOL Name: 100-IS-IT-THE-FIRST-TIME
      * - ip30331Subscript               COBOL Name: IP30331-SUBSCRIPT
      * - valueOne300                    COBOL Name: 300-VALUE-ONE
      *
      * Output :  

      * - pds501S1s2s3Tcnt500            COBOL Name: 500-PDS501-S1S2S3-TCNT
      * - isItTheFirstTime100            COBOL Name: 100-IS-IT-THE-FIRST-TIME
      * - isOccurrenceValid100           COBOL Name: 100-IS-OCCURRENCE-VALID
      * - isCombinationFound100          COBOL Name: 100-IS-COMBINATION-FOUND
      *
      * @throws CFException
      */
      @Override
      public PerformInitializationOutCtx performInitialization(PerformInitializationInCtx methodIn) throws Exception {
Ip224620Ctx programCtx = methodIn.getIp224620Ctx();
PerformInitializationOutCtx methodOut = methodIn.getPerformInitializationOutCtx();
//  IF 88-100-IT-IS-THE-FIRST-TIME
          if ( methodIn.isItIsTheFirstTime88100()  ) { 
//  MOVE ZEROES TO 500-PDS501-S1S2S3-TCNT
              methodOut.setPds501S1s2s3Tcnt500((short) 0);
//  SET 88-100-IT-IS-NOT-FIRST-TIME TO TRUE
              methodOut.setItIsNotFirstTime88100True(); 
              
          }
//  IF IP30331-SUBSCRIPT IS EQUAL 300-VALUE-ONE
          if (	( methodIn.getIp30331Subscript() == methodIn.getValueOne300() )) { 
//  MOVE ZEROES TO 500-PDS501-S1S2S3-TCNT
              methodOut.setPds501S1s2s3Tcnt500((short) 0);
          }
//  SET 88-100-OCCURRENCE-IS-VALID TO TRUE
          methodOut.setOccurrenceIsValid88100True(); 
          
//  SET 88-100-COMBINATION-FOUND TO TRUE
          methodOut.setCombinationFound88100True(); 
          
      
      return methodOut;
      }
      /**
      * performEdit 
      *   This method is derived from 
  *   COBOL Paragraph - 2000-PERFORM-EDIT COBOL Cyclomatic complexity - 2
      * Input  :  

      * - mcIpmMsgTxt                    COBOL Name: MC-IPM-MSG-TXT
      * - isOccurrenceValid100           COBOL Name: 100-IS-OCCURRENCE-VALID
      *
      * Output :  

      * - pds501Value800                 COBOL Name: 800-PDS501-VALUE
      * - mcIpmMsgTxt                    COBOL Name: MC-IPM-MSG-TXT
      * - rc                             COBOL Name: RETURN-CODE
      *
      * @throws CFException
      */
      @Override
      public PerformEditOutCtx performEdit(PerformEditInCtx methodIn) throws Exception {
Ip224620Ctx programCtx = methodIn.getIp224620Ctx();
PerformEditOutCtx methodOut = methodIn.getPerformEditOutCtx();
//  MOVE MC-IPM-MSG-TXT TO 800-PDS501-VALUE
          methodOut.getPds501Value800().setString(methodOut.getMcIpmMsgTxt());
//  PERFORM 2100-SEARCH-COMBINATION
          searchCombination(programCtx.getSearchCombinationInCtx());/*2100-SEARCH-COMBINATION*/
//  IF 88-100-OCCURRENCE-IS-INVALID
          if ( methodIn.isOccurrenceIsInvalid88100()  ) { 
              // MOVE 1 TO RETURN-CODE
              programCtx.setRc( 1);
          }
      
      return methodOut;
      }
      /**
      * searchCombination 
      *   This method is derived from 
  *   COBOL Paragraph - 2100-SEARCH-COMBINATION COBOL Cyclomatic complexity - 5
      * Input  :  

      * - valueOne300                    COBOL Name: 300-VALUE-ONE
      * - pds501S1s2s3Table500           COBOL Name: 500-PDS501-S1S2S3-TABLE
      * - subfld1Value500                COBOL Name: 500-SUBFLD-1-VALUE
      * - pds501s1Value800               COBOL Name: 800-PDS501S1-VALUE
      * - subfld2Value500                COBOL Name: 500-SUBFLD-2-VALUE
      * - pds501s2Value800               COBOL Name: 800-PDS501S2-VALUE
      * - subfld3Value500                COBOL Name: 500-SUBFLD-3-VALUE
      * - pds501s3Value800               COBOL Name: 800-PDS501S3-VALUE
      *
      * Output :  

      * - pds501TblIdx500                COBOL Name: 500-PDS501-TBL-IDX
      * - subfld3Value500                COBOL Name: 500-SUBFLD-3-VALUE
      * - pds501s3Value800               COBOL Name: 800-PDS501S3-VALUE
      * - isOccurrenceValid100           COBOL Name: 100-IS-OCCURRENCE-VALID
      *
      * @throws CFException
      */
      @Override
      public SearchCombinationOutCtx searchCombination(SearchCombinationInCtx methodIn) throws Exception {
			// Declare local variables used in the method
			boolean keepSearching = true;
			// End of variable declaration

Ip224620Ctx programCtx = methodIn.getIp224620Ctx();
SearchCombinationOutCtx methodOut = methodIn.getSearchCombinationOutCtx();
//  SET 500-PDS501-TBL-IDX TO 300-VALUE-ONE
          methodOut.setPds501TblIdx500(methodIn.getValueOne300()); 
          
//  SEARCH 500-PDS501-S1S2S3-TABLE
          keepSearching = true;
          if(methodIn.getPds501S1s2s3Tcnt500() == 0){ 
          keepSearching = false; 
          }
          while(keepSearching) {
          	if  (		compareChars(methodIn.getSubfld1Value500(methodOut.getPds501TblIdx500() - 1),methodIn.getPds501s1Value800()) == 0  && 		compareChars(methodIn.getSubfld2Value500(methodOut.getPds501TblIdx500() - 1),methodIn.getPds501s2Value800()) == 0 ) { 
//  IF 500-SUBFLD-3-VALUE ( 500-PDS501-TBL-IDX ) IS LESS THAN 800-PDS501S3-VALUE
              if (		compareChars(methodOut.getSubfld3Value500(methodOut.getPds501TblIdx500() - 1),methodOut.getPds501s3Value800()) < 0 ) { 
//  MOVE 800-PDS501S3-VALUE TO 500-SUBFLD-3-VALUE ( 500-PDS501-TBL-IDX )
                  methodOut.setSubfld3Value500(methodOut.getPds501TblIdx500() - 1,methodOut.getPds501s3Value800());
              }
//  ELSE
              else { 
//  DISPLAY '** EXCEPTION ** SHOULDNT REACH THIS'
                  logger.info("** EXCEPTION ** SHOULDNT REACH THIS"); 
//  SET 88-100-OCCURRENCE-IS-INVALID TO TRUE
                  methodOut.setOccurrenceIsInvalid88100True(); 
                  
              }
          	break;
          	}
          	methodOut.setPds501TblIdx500(methodOut.getPds501TblIdx500() + 1);
          	if (methodOut.getPds501TblIdx500() > methodIn.getPds501S1s2s3Tcnt500()) { 
          	 keepSearching = false;
          	}
          }
          	if(!keepSearching) { 
//  PERFORM 2110-ENTER-NEW-COMBINATION
              enterNewCombination(programCtx.getEnterNewCombinationInCtx());/*2110-ENTER-NEW-COMBINATION*/
          	}
      
      return methodOut;
      }
      /**
      * enterNewCombination 
      *   This method is derived from 
  *   COBOL Paragraph - 2110-ENTER-NEW-COMBINATION COBOL Cyclomatic complexity - 3
      * Input  :  

      * - pds501S1s2s3Tcnt500            COBOL Name: 500-PDS501-S1S2S3-TCNT
      * - valueFifty300                  COBOL Name: 300-VALUE-FIFTY
      * - valueOne300                    COBOL Name: 300-VALUE-ONE
      * - pds501Value800                 COBOL Name: 800-PDS501-VALUE
      * - pds501s1Value800               COBOL Name: 800-PDS501S1-VALUE
      * - pds501s2Value800               COBOL Name: 800-PDS501S2-VALUE
      * - pds501s3Value800               COBOL Name: 800-PDS501S3-VALUE
      *
      * Output :  

      * - pds501S1s2s3Tcnt500            COBOL Name: 500-PDS501-S1S2S3-TCNT
      * - pds501TblIdx500                COBOL Name: 500-PDS501-TBL-IDX
      * - subfld1Value500                COBOL Name: 500-SUBFLD-1-VALUE
      * - pds501s1Value800               COBOL Name: 800-PDS501S1-VALUE
      * - subfld2Value500                COBOL Name: 500-SUBFLD-2-VALUE
      * - pds501s2Value800               COBOL Name: 800-PDS501S2-VALUE
      * - subfld3Value500                COBOL Name: 500-SUBFLD-3-VALUE
      * - pds501s3Value800               COBOL Name: 800-PDS501S3-VALUE
      *
      * @throws CFException
      */
      @Override
      public EnterNewCombinationOutCtx enterNewCombination(EnterNewCombinationInCtx methodIn) throws Exception {
Ip224620Ctx programCtx = methodIn.getIp224620Ctx();
EnterNewCombinationOutCtx methodOut = methodIn.getEnterNewCombinationOutCtx();
//  IF 500-PDS501-S1S2S3-TCNT LESS THAN OR EQUAL 300-VALUE-FIFTY
          if (	( methodOut.getPds501S1s2s3Tcnt500() <= methodIn.getValueFifty300() ) ) { 
//  ADD 300-VALUE-ONE TO 500-PDS501-S1S2S3-TCNT
              methodOut.setPds501S1s2s3Tcnt500( (short) (methodOut.getPds501S1s2s3Tcnt500()+(short) methodIn.getValueOne300()));
//  DISPLAY 800-PDS501-VALUE ' NOT FOUND IN TABLE ** ' ' ADDED AT POSITION ' 500-PDS501-S1S2S3-TCNT
              logger.info("{} NOT FOUND IN TABLE **  ADDED AT POSITION {}", methodIn.getPds501Value800().toString(), String.valueOf(methodOut.getPds501S1s2s3Tcnt500())); 
//  SET 500-PDS501-TBL-IDX TO 500-PDS501-S1S2S3-TCNT
              methodOut.setPds501TblIdx500(methodOut.getPds501S1s2s3Tcnt500()); 
              
//  MOVE 800-PDS501S1-VALUE TO 500-SUBFLD-1-VALUE ( 500-PDS501-TBL-IDX )
              methodOut.setSubfld1Value500(methodOut.getPds501TblIdx500() - 1,methodOut.getPds501s1Value800());
//  MOVE 800-PDS501S2-VALUE TO 500-SUBFLD-2-VALUE ( 500-PDS501-TBL-IDX )
              methodOut.setSubfld2Value500(methodOut.getPds501TblIdx500() - 1,methodOut.getPds501s2Value800());
//  MOVE 800-PDS501S3-VALUE TO 500-SUBFLD-3-VALUE ( 500-PDS501-TBL-IDX )
              methodOut.setSubfld3Value500(methodOut.getPds501TblIdx500() - 1,methodOut.getPds501s3Value800());
          }
//  ELSE
          else { 
//  PERFORM 2111-ABEND-ON-TBL-OVERFLOW
              abendOnTblOverflow(programCtx.getAbendOnTblOverflowInCtx());/*2111-ABEND-ON-TBL-OVERFLOW*/
          }
      
      return methodOut;
      }
      /**
      * abendOnTblOverflow 
      *   This method is derived from 
  *   COBOL Paragraph - 2111-ABEND-ON-TBL-OVERFLOW COBOL Cyclomatic complexity - 1
      * Input  :  

      * - tableOverflowError600          COBOL Name: 600-TABLE-OVERFLOW-ERROR
      * - para2111300                    COBOL Name: 300-PARA-2111
      * - tblOverflowAbendCode300        COBOL Name: 300-TBL-OVERFLOW-ABEND-CODE
      *
      * Output :  

      * - abendText900                   COBOL Name: 900-ABEND-TEXT
      * - tableOverflowError600          COBOL Name: 600-TABLE-OVERFLOW-ERROR
      * - abendPara900                   COBOL Name: 900-ABEND-PARA
      * - para2111300                    COBOL Name: 300-PARA-2111
      * - abendCode900                   COBOL Name: 900-ABEND-CODE
      * - tblOverflowAbendCode300        COBOL Name: 300-TBL-OVERFLOW-ABEND-CODE
      *
      * @throws CFException
      */
      @Override
      public AbendOnTblOverflowOutCtx abendOnTblOverflow(AbendOnTblOverflowInCtx methodIn) throws Exception {
Ip224620Ctx programCtx = methodIn.getIp224620Ctx();
AbendOnTblOverflowOutCtx methodOut = methodIn.getAbendOnTblOverflowOutCtx();
//  MOVE 600-TABLE-OVERFLOW-ERROR TO 900-ABEND-TEXT
          methodOut.setAbendText900(pad(66,methodOut.getTableOverflowError600(),SPACE_CHAR,RIGHT_PAD));
//  MOVE 300-PARA-2111 TO 900-ABEND-PARA
          methodOut.setAbendPara900(pad(30,methodOut.getPara2111300(),SPACE_CHAR,RIGHT_PAD));
//  MOVE 300-TBL-OVERFLOW-ABEND-CODE TO 900-ABEND-CODE
          methodOut.setAbendCode900(methodOut.getTblOverflowAbendCode300());
//  PERFORM 9000-TERMINATE-ON-ERROR
          terminateOnError(programCtx.getTerminateOnErrorInCtx());/*9000-TERMINATE-ON-ERROR*/
          ;
      
      return methodOut;
      }
      /**
      * terminateOnError 
      *   This method is derived from 
  *   COBOL Paragraph - 9000-TERMINATE-ON-ERROR COBOL Cyclomatic complexity - 1
      * Input  :  

      * - abendParaName900               COBOL Name: 900-ABEND-PARA-NAME
      * - abendMessage900                COBOL Name: 900-ABEND-MESSAGE
      *
      * Output : None 

      * @throws CFException
      */
      @Override
      public void terminateOnError(TerminateOnErrorInCtx methodIn) throws Exception {
Ip224620Ctx programCtx = methodIn.getIp224620Ctx();
//  DISPLAY '***********************************'
          logger.info("***********************************"); 
//  DISPLAY 'A B E N D   A B E N D   A B E N D  '
          logger.info("A B E N D   A B E N D   A B E N D  "); 
//  DISPLAY 'A B E N D   I P 2 2 4 6 2 0        '
          logger.info("A B E N D   I P 2 2 4 6 2 0        "); 
//  DISPLAY '***********************************'
          logger.info("***********************************"); 
//  DISPLAY 900-ABEND-PARA-NAME
          logger.info(methodIn.getAbendParaName900().toString()); 
//  DISPLAY 900-ABEND-MESSAGE
          logger.info(methodIn.getAbendMessage900().toString()); 
      
      }
  
  
  
  
  
  
  
  
  }
