#STEP:SORT010| PGM:SORT| DD:SORTIN
HeadertrailerSort010SortIn=CLOUDFRM.MC.GCMS.SORT.IN
HeadertrailerSort010SortIn.DISP=SHR,KEEP,KEEP
HeadertrailerSort010SortInRecordType=FB
HeadertrailerSort010SortInRecordLen=256
#STEP:SORT010| PGM:SORT| DD:SORTOUT
HeadertrailerSort010SortOut=CLOUDFRM.MC.GCMS.SORT.OUT
HeadertrailerSort010SortOut.DISP=NEW,KEEP,KEEP
HeadertrailerSort010SortOutRecordType=FB
HeadertrailerSort010SortOutRecordLen=5000
