  package com.cloudframe.app.process.impl;
  /* Java code generated by CloudFrame on 2025-04-28 at 08:03. */
  
  import com.cloudframe.app.mcvsam1.Mcvsam1Ctx.*;
  import com.cloudframe.app.mcvsam1.Mcvsam1Ctx;
  import com.cloudframe.app.process.Mcvsam1;
  import com.cloudframe.app.process.BaseProcess;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.dto.GlobalExecutorCtx;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.process.Mcvsam2;
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.beans.factory.annotation.Qualifier;
  import com.cloudframe.app.process.*;
  import com.cloudframe.app.global.sharedvar.HoldIrdTable500;
  import com.cloudframe.app.global.sharedvar.IrdExtrFileRec800;
  import com.cloudframe.app.mcvsam1.dto.*;
  import com.cloudframe.app.mcvsam1.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("mcvsam1")
  
  public class Mcvsam1Impl extends CommonProcess implements Mcvsam1 {
  
  Logger logger = LoggerFactory.getLogger(Mcvsam1Impl.class);
  
  
  
  
  @Autowired 
  @Qualifier("mcvsam2")
  Mcvsam2 mcvsam2;
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      public int process(Mcvsam1Ctx programCtx) throws Exception {
       try {
       setCodePage("1047");
            // Reset program ended flag
           programCtx.setProgramEnded(false);
          ;
//  PERFORM 0000-MAINLINE
          mainline(programCtx);/*0000-MAINLINE*/
          if (programCtx.isProgramEnded()) {
              return programCtx.getRc();
          }
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
       return programCtx.getRc(); // Exit with return code
      // end of process method
      }
      /**
      * mainline 
      *   This method is derived from 
  *   COBOL Paragraph - 0000-MAINLINE COBOL Cyclomatic complexity - 2
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      @Override
      public void mainline(Mcvsam1Ctx programCtx) throws Exception {
//  PERFORM 1000-DO-INITIALIZATION
          doInitialization(programCtx);/*1000-DO-INITIALIZATION*/
          if (programCtx.isProgramEnded()) {
              return ;
          }
//  PERFORM 2000-PROCESS-IRD-EXTR
          processIrdExtr(programCtx);/*2000-PROCESS-IRD-EXTR*/
          if (programCtx.isProgramEnded()) {
              return ;
          }
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          programCtx.setProgramEnded(true);
          return ;
      
      }
      /**
      * doInitialization 
      *   This method is derived from 
  *   COBOL Paragraph - 1000-DO-INITIALIZATION COBOL Cyclomatic complexity - 1
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      @Override
      public void doInitialization(Mcvsam1Ctx programCtx) throws Exception {
//  DISPLAY 'IN MCVSAM1'
          logger.info("IN MCVSAM1"); 
      
      }
      /**
      * processIrdExtr 
      *   This method is derived from 
  *   COBOL Paragraph - 2000-PROCESS-IRD-EXTR COBOL Cyclomatic complexity - 11
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      @Override
      public void processIrdExtr(Mcvsam1Ctx programCtx) throws Exception {
//  PERFORM 2000-PROCESS-IRD-EXTR-SPLIT0
          processIrdExtrSplit0(programCtx.getProcessIrdExtrSplit0InCtx());/*2000-PROCESS-IRD-EXTR-SPLIT0*/
//  PERFORM 2000-PROCESS-IRD-EXTR-SPLIT1
          processIrdExtrSplit1(programCtx.getProcessIrdExtrSplit1InCtx());/*2000-PROCESS-IRD-EXTR-SPLIT1*/
      
      }
      /**
      * processIrdExtrSplit0 
      *   This method is derived from 
  *   COBOL Paragraph - 2000-PROCESS-IRD-EXTR-SPLIT0 COBOL Cyclomatic complexity - 1
      * Input  :  

      * - irdLdCnt500                    COBOL Name: 500-IRD-LD-CNT
      * - irdIdx500                      COBOL Name: 500-IRD-IDX
      * - ird500                         COBOL Name: 500-IRD
      *
      * Output :  

      * - cpi800                         COBOL Name: 800-CPI
      * - bsl800                         COBOL Name: 800-BSL
      * - bsid800                        COBOL Name: 800-BSID
      * - msgType800                     COBOL Name: 800-MSG-TYPE
      * - funcCd800                      COBOL Name: 800-FUNC-CD
      * - prcsCd800                      COBOL Name: 800-PRCS-CD
      * - de26800                        COBOL Name: 800-DE26
      * - prodId800                      COBOL Name: 800-PROD-ID
      * - rc                             COBOL Name: RETURN-CODE
      * - irdIdx500                      COBOL Name: 500-IRD-IDX
      *
      * @throws CFException
      */
      @Override
      public ProcessIrdExtrSplit0OutCtx processIrdExtrSplit0(ProcessIrdExtrSplit0InCtx methodIn) throws Exception {
Mcvsam1Ctx programCtx = methodIn.getMcvsam1Ctx();
ProcessIrdExtrSplit0OutCtx methodOut = methodIn.getProcessIrdExtrSplit0OutCtx();

// * Cir1040301124020501000006011cir
//  DISPLAY ' '
          logger.info(" "); 
//  DISPLAY 'SEARCH KEY = CIR1040301124020501000006011CIR'
          logger.info("SEARCH KEY = CIR1040301124020501000006011CIR"); 
//  DISPLAY ' '
          logger.info(" "); 
//  MOVE 'CIR' TO 800-CPI
//  LITERAL_CIR = 'CIR'
          methodOut.setCpi800(CONSTANTS.LITERAL_CIR);
          // MOVE 1 TO 800-BSL
          //  LITERAL_1 = 1
          methodOut.setBsl800(CONSTANTS.LITERAL_1);
          // MOVE '040301' TO 800-BSID
          //  LITERAL_040301 = '040301'
          methodOut.setBsid800(CONSTANTS.LITERAL_040301);
          // MOVE '1240' TO 800-MSG-TYPE
          //  LITERAL_1240 = '1240'
          methodOut.setMsgType800(CONSTANTS.LITERAL_1240);
          // MOVE '205' TO 800-FUNC-CD
          //  LITERAL_205 = '205'
          methodOut.setFuncCd800(CONSTANTS.LITERAL_205);
          // MOVE '010000' TO 800-PRCS-CD
          //  LITERAL_010000 = '010000'
          methodOut.setPrcsCd800(CONSTANTS.LITERAL_010000);
          // MOVE 06011 TO 800-DE26
          methodOut.setDe26800((long)6011);
//  MOVE 'CIR' TO 800-PROD-ID
//  LITERAL_CIR = 'CIR'
          methodOut.setProdId800(CONSTANTS.LITERAL_CIR);
//  CALL 300-PGM-NAME
          // CALL 300-PGM-NAME
          	programCtx.setRc( mcvsam2.process(programCtx.getGlobalCtx().getContext("MCVSAM2")));
//  DISPLAY 'NUMBER OF MATCHING RECORDS = ' 500-IRD-LD-CNT
          logger.info("NUMBER OF MATCHING RECORDS = {}", String.valueOf(methodIn.getIrdLdCnt500())); 
//  PERFORM VARYING 500-IRD-IDX FROM 1 BY 1 UNTIL 500-IRD-IDX > 500-IRD-LD-CNT
          for (methodOut.setIrdIdx500(1); (	( methodOut.getIrdIdx500() <= methodIn.getIrdLdCnt500() ) ) ; methodOut.setIrdIdx500(methodOut.getIrdIdx500() + 1) ) {
//  DISPLAY '|--> 500-IRD  = ' 500-IRD ( 500-IRD-IDX )
              logger.info("|--> 500-IRD  = {}", new String(methodIn.getIrd500(methodOut.getIrdIdx500() - 1))); 
          }

// * Cir1050301124020501000006011cir
//  DISPLAY ' '
          logger.info(" "); 
//  DISPLAY 'SEARCH KEY = CIR1050301124020501000006011CIR'
          logger.info("SEARCH KEY = CIR1050301124020501000006011CIR"); 
//  DISPLAY ' '
          logger.info(" "); 
//  MOVE 'CIR' TO 800-CPI
//  LITERAL_CIR = 'CIR'
          methodOut.setCpi800(CONSTANTS.LITERAL_CIR);
          // MOVE 1 TO 800-BSL
          //  LITERAL_1 = 1
          methodOut.setBsl800(CONSTANTS.LITERAL_1);
          // MOVE '050301' TO 800-BSID
          //  LITERAL_050301 = '050301'
          methodOut.setBsid800(CONSTANTS.LITERAL_050301);
          // MOVE '1240' TO 800-MSG-TYPE
          //  LITERAL_1240 = '1240'
          methodOut.setMsgType800(CONSTANTS.LITERAL_1240);
          // MOVE '205' TO 800-FUNC-CD
          //  LITERAL_205 = '205'
          methodOut.setFuncCd800(CONSTANTS.LITERAL_205);
          // MOVE '010000' TO 800-PRCS-CD
          //  LITERAL_010000 = '010000'
          methodOut.setPrcsCd800(CONSTANTS.LITERAL_010000);
          // MOVE 06011 TO 800-DE26
          methodOut.setDe26800((long)6011);
//  MOVE 'CIR' TO 800-PROD-ID
//  LITERAL_CIR = 'CIR'
          methodOut.setProdId800(CONSTANTS.LITERAL_CIR);
//  CALL 300-PGM-NAME
          // CALL 300-PGM-NAME
          	programCtx.setRc( mcvsam2.process(programCtx.getGlobalCtx().getContext("MCVSAM2")));
//  DISPLAY 'NUMBER OF MATCHING RECORDS = ' 500-IRD-LD-CNT
          logger.info("NUMBER OF MATCHING RECORDS = {}", String.valueOf(methodIn.getIrdLdCnt500())); 
//  PERFORM VARYING 500-IRD-IDX FROM 1 BY 1 UNTIL 500-IRD-IDX > 500-IRD-LD-CNT
          for (methodOut.setIrdIdx500(1); (	( methodOut.getIrdIdx500() <= methodIn.getIrdLdCnt500() ) ) ; methodOut.setIrdIdx500(methodOut.getIrdIdx500() + 1) ) {
//  DISPLAY '|--> 500-IRD  = ' 500-IRD ( 500-IRD-IDX )
              logger.info("|--> 500-IRD  = {}", new String(methodIn.getIrd500(methodOut.getIrdIdx500() - 1))); 
          }

// * Pvl3040031124028228000009950pvj
//  DISPLAY ' '
          logger.info(" "); 
//  DISPLAY 'SEARCH KEY = PVL3040031124028228000009950PVJ'
          logger.info("SEARCH KEY = PVL3040031124028228000009950PVJ"); 
//  DISPLAY ' '
          logger.info(" "); 
//  MOVE 'PVL' TO 800-CPI
//  LITERAL_PVL = 'PVL'
          methodOut.setCpi800(CONSTANTS.LITERAL_PVL);
          // MOVE 3 TO 800-BSL
          //  LITERAL_3 = 3
          methodOut.setBsl800(CONSTANTS.LITERAL_3);
          // MOVE '040031' TO 800-BSID
          //  LITERAL_040031 = '040031'
          methodOut.setBsid800(CONSTANTS.LITERAL_040031);
          // MOVE '1240' TO 800-MSG-TYPE
          //  LITERAL_1240 = '1240'
          methodOut.setMsgType800(CONSTANTS.LITERAL_1240);
          // MOVE '282' TO 800-FUNC-CD
          //  LITERAL_282 = '282'
          methodOut.setFuncCd800(CONSTANTS.LITERAL_282);
          // MOVE '280000' TO 800-PRCS-CD
          //  LITERAL_280000 = '280000'
          methodOut.setPrcsCd800(CONSTANTS.LITERAL_280000);
          // MOVE 09950 TO 800-DE26
          methodOut.setDe26800((long)9950);
//  MOVE 'PVJ' TO 800-PROD-ID
//  LITERAL_PVJ = 'PVJ'
          methodOut.setProdId800(CONSTANTS.LITERAL_PVJ);
//  CALL 300-PGM-NAME
          // CALL 300-PGM-NAME
          	programCtx.setRc( mcvsam2.process(programCtx.getGlobalCtx().getContext("MCVSAM2")));
//  DISPLAY 'NUMBER OF MATCHING RECORDS = ' 500-IRD-LD-CNT
          logger.info("NUMBER OF MATCHING RECORDS = {}", String.valueOf(methodIn.getIrdLdCnt500())); 
//  PERFORM VARYING 500-IRD-IDX FROM 1 BY 1 UNTIL 500-IRD-IDX > 500-IRD-LD-CNT
          for (methodOut.setIrdIdx500(1); (	( methodOut.getIrdIdx500() <= methodIn.getIrdLdCnt500() ) ) ; methodOut.setIrdIdx500(methodOut.getIrdIdx500() + 1) ) {
//  DISPLAY '|--> 500-IRD  = ' 500-IRD ( 500-IRD-IDX )
              logger.info("|--> 500-IRD  = {}", new String(methodIn.getIrd500(methodOut.getIrdIdx500() - 1))); 
          }

// * Pvl3040031124028228000009950pvl
//  DISPLAY ' '
          logger.info(" "); 
//  DISPLAY 'SEARCH KEY = PVL3040031124028228000009950PVL'
          logger.info("SEARCH KEY = PVL3040031124028228000009950PVL"); 
//  DISPLAY ' '
          logger.info(" "); 
//  MOVE 'PVL' TO 800-CPI
//  LITERAL_PVL = 'PVL'
          methodOut.setCpi800(CONSTANTS.LITERAL_PVL);
          // MOVE 3 TO 800-BSL
          //  LITERAL_3 = 3
          methodOut.setBsl800(CONSTANTS.LITERAL_3);
          // MOVE '040031' TO 800-BSID
          //  LITERAL_040031 = '040031'
          methodOut.setBsid800(CONSTANTS.LITERAL_040031);
          // MOVE '1240' TO 800-MSG-TYPE
          //  LITERAL_1240 = '1240'
          methodOut.setMsgType800(CONSTANTS.LITERAL_1240);
          // MOVE '282' TO 800-FUNC-CD
          //  LITERAL_282 = '282'
          methodOut.setFuncCd800(CONSTANTS.LITERAL_282);
          // MOVE '280000' TO 800-PRCS-CD
          //  LITERAL_280000 = '280000'
          methodOut.setPrcsCd800(CONSTANTS.LITERAL_280000);
      
      return methodOut;
      }
      /**
      * processIrdExtrSplit1 
      *   This method is derived from 
  *   COBOL Paragraph - 2000-PROCESS-IRD-EXTR-SPLIT1 COBOL Cyclomatic complexity - 1
      * Input  :  

      * - irdLdCnt500                    COBOL Name: 500-IRD-LD-CNT
      * - irdIdx500                      COBOL Name: 500-IRD-IDX
      * - ird500                         COBOL Name: 500-IRD
      *
      * Output :  

      * - de26800                        COBOL Name: 800-DE26
      * - prodId800                      COBOL Name: 800-PROD-ID
      * - rc                             COBOL Name: RETURN-CODE
      * - irdIdx500                      COBOL Name: 500-IRD-IDX
      * - cpi800                         COBOL Name: 800-CPI
      * - bsl800                         COBOL Name: 800-BSL
      * - bsid800                        COBOL Name: 800-BSID
      * - msgType800                     COBOL Name: 800-MSG-TYPE
      * - funcCd800                      COBOL Name: 800-FUNC-CD
      * - prcsCd800                      COBOL Name: 800-PRCS-CD
      *
      * @throws CFException
      */
      @Override
      public ProcessIrdExtrSplit1OutCtx processIrdExtrSplit1(ProcessIrdExtrSplit1InCtx methodIn) throws Exception {
Mcvsam1Ctx programCtx = methodIn.getMcvsam1Ctx();
ProcessIrdExtrSplit1OutCtx methodOut = methodIn.getProcessIrdExtrSplit1OutCtx();
          // MOVE 09950 TO 800-DE26
          methodOut.setDe26800((long)9950);
//  MOVE 'PVL' TO 800-PROD-ID
//  LITERAL_PVL = 'PVL'
          methodOut.setProdId800(CONSTANTS.LITERAL_PVL);
//  CALL 300-PGM-NAME
          // CALL 300-PGM-NAME
          	programCtx.setRc( mcvsam2.process(programCtx.getGlobalCtx().getContext("MCVSAM2")));
//  DISPLAY 'NUMBER OF MATCHING RECORDS = ' 500-IRD-LD-CNT
          logger.info("NUMBER OF MATCHING RECORDS = {}", String.valueOf(methodIn.getIrdLdCnt500())); 
//  PERFORM VARYING 500-IRD-IDX FROM 1 BY 1 UNTIL 500-IRD-IDX > 500-IRD-LD-CNT
          for (methodOut.setIrdIdx500(1); (	( methodOut.getIrdIdx500() <= methodIn.getIrdLdCnt500() ) ) ; methodOut.setIrdIdx500(methodOut.getIrdIdx500() + 1) ) {
//  DISPLAY '|--> 500-IRD  = ' 500-IRD ( 500-IRD-IDX )
              logger.info("|--> 500-IRD  = {}", new String(methodIn.getIrd500(methodOut.getIrdIdx500() - 1))); 
          }

// * Zzz3040031124028228000000001zzz
//  DISPLAY ' '
          logger.info(" "); 
//  DISPLAY 'SEARCH KEY = ZZZ3040031124028228000000001ZZZ'
          logger.info("SEARCH KEY = ZZZ3040031124028228000000001ZZZ"); 
//  DISPLAY ' '
          logger.info(" "); 
//  MOVE 'ZZZ' TO 800-CPI
//  LITERAL_ZZZ = 'ZZZ'
          methodOut.setCpi800(CONSTANTS.LITERAL_ZZZ);
          // MOVE 3 TO 800-BSL
          //  LITERAL_3 = 3
          methodOut.setBsl800(CONSTANTS.LITERAL_3);
          // MOVE '040031' TO 800-BSID
          //  LITERAL_040031 = '040031'
          methodOut.setBsid800(CONSTANTS.LITERAL_040031);
          // MOVE '1240' TO 800-MSG-TYPE
          //  LITERAL_1240 = '1240'
          methodOut.setMsgType800(CONSTANTS.LITERAL_1240);
          // MOVE '282' TO 800-FUNC-CD
          //  LITERAL_282 = '282'
          methodOut.setFuncCd800(CONSTANTS.LITERAL_282);
          // MOVE '280000' TO 800-PRCS-CD
          //  LITERAL_280000 = '280000'
          methodOut.setPrcsCd800(CONSTANTS.LITERAL_280000);
          // MOVE 00001 TO 800-DE26
          methodOut.setDe26800((long)1);
//  MOVE 'ZZZ' TO 800-PROD-ID
//  LITERAL_ZZZ = 'ZZZ'
          methodOut.setProdId800(CONSTANTS.LITERAL_ZZZ);
//  CALL 300-PGM-NAME
          // CALL 300-PGM-NAME
          	programCtx.setRc( mcvsam2.process(programCtx.getGlobalCtx().getContext("MCVSAM2")));
//  DISPLAY 'NUMBER OF MATCHING RECORDS = ' 500-IRD-LD-CNT
          logger.info("NUMBER OF MATCHING RECORDS = {}", String.valueOf(methodIn.getIrdLdCnt500())); 
//  PERFORM VARYING 500-IRD-IDX FROM 1 BY 1 UNTIL 500-IRD-IDX > 500-IRD-LD-CNT
          for (methodOut.setIrdIdx500(1); (	( methodOut.getIrdIdx500() <= methodIn.getIrdLdCnt500() ) ) ; methodOut.setIrdIdx500(methodOut.getIrdIdx500() + 1) ) {
//  DISPLAY '|--> 500-IRD  = ' 500-IRD ( 500-IRD-IDX )
              logger.info("|--> 500-IRD  = {}", new String(methodIn.getIrd500(methodOut.getIrdIdx500() - 1))); 
          }
          ;
      
      return methodOut;
      }
  
  
  
  
  
  
  
  
  }
