  package com.cloudframe.app.process.impl;
  /* Java code generated by CloudFrame on 2025-04-24 at 16:37. */
  
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.beans.factory.annotation.Qualifier;
  import com.cloudframe.app.mcvsam2.file.*;
  import com.cloudframe.app.mcvsam2.Mcvsam2Ctx.*;
  import com.cloudframe.app.mcvsam2.Mcvsam2Ctx;
  import com.cloudframe.app.process.Mcvsam2;
  import com.cloudframe.app.process.BaseProcess;
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.dto.GlobalExecutorCtx;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.utility.CFConstants;
  import com.cloudframe.app.mcvsam2.dto.*;
  import com.cloudframe.app.mcvsam2.file.records.Sys001IrdExtrFileRec;
  import com.cloudframe.app.mcvsam2.dto.AbendMessage600;
  import com.cloudframe.app.mcvsam2.dto.AbendMessage900;
  import com.cloudframe.app.global.sharedvar.Ip60001EventLogWorkArea;
  import com.cloudframe.app.global.sharedvar.HoldIrdTable500;
  import com.cloudframe.app.global.sharedvar.IrdExtrFileRec800;
  import com.cloudframe.app.mcvsam2.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("mcvsam2")
  
  public class Mcvsam2Impl extends CommonProcess implements Mcvsam2 {
  
  Logger logger = LoggerFactory.getLogger(Mcvsam2Impl.class);
  
  
  
  
  @Autowired 
  @Qualifier("mcvsam2_sys001IrdExtrFile")
  Sys001IrdExtrFile sys001IrdExtrFile;
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      public int process(Mcvsam2Ctx programCtx) throws Exception {
       try {
       setCodePage("1047");
            // Reset program ended flag
           programCtx.setProgramEnded(false);
          ;
//  PERFORM 0000-MAINLINE
          mainline(programCtx);/*0000-MAINLINE*/
          if (programCtx.isProgramEnded()) {
              return programCtx.getRc();
          }
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
        finally {
      		if(sys001IrdExtrFile.hasOpened() && !sys001IrdExtrFile.isReadOnly()) { 
      			sys001IrdExtrFile.flush(); 
      		}
      }
      
       return programCtx.getRc(); // Exit with return code
      // end of process method
      }
      /**
      * mainline 
      *   This method is derived from 
  *   COBOL Paragraph - 0000-MAINLINE COBOL Cyclomatic complexity - 2
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      @Override
      public void mainline(Mcvsam2Ctx programCtx) throws Exception {
//  PERFORM 1000-DO-INITIALIZATION
          doInitialization(programCtx.getDoInitializationInCtx());/*1000-DO-INITIALIZATION*/
          if (programCtx.isProgramEnded()) {
              return ;
          }
//  PERFORM 2000-PROCESS-IRD-EXTR
          processIrdExtr(programCtx.getProcessIrdExtrInCtx());/*2000-PROCESS-IRD-EXTR*/
          if (programCtx.isProgramEnded()) {
              return ;
          }
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          programCtx.setProgramEnded(true);
          return ;
      
      }
      /**
      * doInitialization 
      *   This method is derived from 
  *   COBOL Paragraph - 1000-DO-INITIALIZATION COBOL Cyclomatic complexity - 2
      * Input  :  

      * - isItFirstTime100               COBOL Name: 100-IS-IT-FIRST-TIME
      *
      * Output :  

      * - isItFirstTime100               COBOL Name: 100-IS-IT-FIRST-TIME
      *
      * @throws CFException
      */
      @Override
      public DoInitializationOutCtx doInitialization(DoInitializationInCtx methodIn) throws Exception {
Mcvsam2Ctx programCtx = methodIn.getMcvsam2Ctx();
DoInitializationOutCtx methodOut = methodIn.getDoInitializationOutCtx();
//  IF 88-100-IT-IS-FIRST-TIME
          if ( methodIn.isItIsFirstTime88100()  ) { 
//  SET 88-100-IT-IS-NOT-FIRST-TIME TO TRUE
              methodOut.setItIsNotFirstTime88100True(); 
              
//  PERFORM 1200-OPEN-INPUT-SYS001
              openInputSys001(programCtx.getOpenInputSys001InCtx());/*1200-OPEN-INPUT-SYS001*/
          }
      
      return methodOut;
      }
      /**
      * openInputSys001 
      *   This method is derived from 
  *   COBOL Paragraph - 1200-OPEN-INPUT-SYS001 COBOL Cyclomatic complexity - 2
      * Input  : None 

      * Output :  

      * - sys001FileStatus200            COBOL Name: 200-SYS001-FILE-STATUS
      * - fileStatus600                  COBOL Name: 600-FILE-STATUS
      * - abendDescription600            COBOL Name: 600-ABEND-DESCRIPTION
      * - abendCode300                   COBOL Name: 300-ABEND-CODE
      * - abendParaName300               COBOL Name: 300-ABEND-PARA-NAME
      *
      * @throws CFException
      */
      @Override
      public OpenInputSys001OutCtx openInputSys001(OpenInputSys001InCtx methodIn) throws Exception {
Mcvsam2Ctx programCtx = methodIn.getMcvsam2Ctx();
OpenInputSys001OutCtx methodOut = methodIn.getOpenInputSys001OutCtx();
//  OPEN INPUT SYS001-IRD-EXTR-FILE
          	sys001IrdExtrFile.setVsamCluster("MCVSAM2" /*program name*/);
          sys001IrdExtrFile.open("r"); 
          methodOut.setSys001FileStatus200(sys001IrdExtrFile.getStatusString() );
//  IF 88-200-SYS001-IO-GOOD
//  ELSE
          if (!(methodOut.isSys001IoGood88200()) ) { 
//  MOVE 200-SYS001-FILE-STATUS TO 600-FILE-STATUS
              methodOut.setFileStatus600(methodOut.getSys001FileStatus200());
//  SET 88-600-ABEND-OPEN-SYS001 TO TRUE
              methodOut.setAbendOpenSys00188600True(); 
              
//  SET 88-300-OPEN-ABEND-CODE TO TRUE
              methodOut.setOpenAbendCode88300True(); 
              
//  SET 88-300-ABEND-PARA-1200 TO TRUE
              methodOut.setAbendPara120088300True(); 
              
//  PERFORM 9500-ABEND-PROGRAM
              abendProgram(programCtx.getAbendProgramInCtx());/*9500-ABEND-PROGRAM*/
          }
      
      return methodOut;
      }
      /**
      * processIrdExtr 
      *   This method is derived from 
  *   COBOL Paragraph - 2000-PROCESS-IRD-EXTR COBOL Cyclomatic complexity - 6
      * Input  :  

      * - prevKey800                     COBOL Name: 800-PREV-KEY
      * - key800                         COBOL Name: 800-KEY
      * - sys001FileStatus200            COBOL Name: 200-SYS001-FILE-STATUS
      *
      * Output :  

      * - irdLdCnt500                    COBOL Name: 500-IRD-LD-CNT
      * - sys001Key                      COBOL Name: SYS001-KEY
      * - prevKey800                     COBOL Name: 800-PREV-KEY
      * - key800                         COBOL Name: 800-KEY
      * - isItEndOfData100               COBOL Name: 100-IS-IT-END-OF-DATA
      * - abendDescription600            COBOL Name: 600-ABEND-DESCRIPTION
      * - abendCode300                   COBOL Name: 300-ABEND-CODE
      * - abendParaName300               COBOL Name: 300-ABEND-PARA-NAME
      * - fileStatus600                  COBOL Name: 600-FILE-STATUS
      * - sys001FileStatus200            COBOL Name: 200-SYS001-FILE-STATUS
      *
      * @throws CFException
      */
      @Override
      public ProcessIrdExtrOutCtx processIrdExtr(ProcessIrdExtrInCtx methodIn) throws Exception {
Mcvsam2Ctx programCtx = methodIn.getMcvsam2Ctx();
ProcessIrdExtrOutCtx methodOut = methodIn.getProcessIrdExtrOutCtx();
//  IF 800-PREV-KEY EQUAL 800-KEY
//  ELSE
          if (compareChars(methodOut.getPrevKey800(),methodOut.getKey800()) != 0) { 
//  MOVE ZEROES TO 500-IRD-LD-CNT
              methodOut.setIrdLdCnt500((short) 0);
              // MOVE 800-KEY TO SYS001-KEY 800-PREV-KEY
              methodOut.setSys001Key(methodOut.getKey800().toCharArray());
              methodOut.setPrevKey800(methodOut.getKey800().toCharArray());
//  START SYS001-IRD-EXTR-FILE KEY EQUAL SYS001-KEY
              sys001IrdExtrFile.seekPartial(methodOut.getSys001IrdExtrFileRec().toCharArray(),CFConstants.CONDITION_EQUAL,0,31);
              methodOut.setSys001FileStatus200(sys001IrdExtrFile.getStatusString() );
//  EVALUATE TRUE
              if  ( methodIn.isSys001IoGood88200()  ) { 
//  SET 88-100-END-OF-DATA-N TO TRUE
                  methodOut.setEndOfDataN88100True(); 
                  
//  PERFORM 8000-READ-SYS001-FILE UNTIL 88-100-END-OF-DATA-Y
                  while (!(methodOut.isEndOfDataY88100()) ) {
                     readSys001File(programCtx.getReadSys001FileInCtx());/*8000-READ-SYS001-FILE*/
                  }
              }
              else if  ( methodIn.isSys001NoRecs88200()  ) { 
                  ;
              }
              else   { 
//  SET 88-600-ABEND-START-SYS001 TO TRUE
                  methodOut.setAbendStartSys00188600True(); 
                  
//  SET 88-300-STRT-ABEND-CODE TO TRUE
                  methodOut.setStrtAbendCode88300True(); 
                  
//  SET 88-300-ABEND-PARA-2000 TO TRUE
                  methodOut.setAbendPara200088300True(); 
                  
//  MOVE 200-SYS001-FILE-STATUS TO 600-FILE-STATUS
                  methodOut.setFileStatus600(methodOut.getSys001FileStatus200());
//  PERFORM 9500-ABEND-PROGRAM
                  abendProgram(programCtx.getAbendProgramInCtx());/*9500-ABEND-PROGRAM*/
              }
          }
      
      return methodOut;
      }
      /**
      * readSys001File 
      *   This method is derived from 
  *   COBOL Paragraph - 8000-READ-SYS001-FILE COBOL Cyclomatic complexity - 5
      * Input  :  

      * - key800                         COBOL Name: 800-KEY
      * - irdLdCnt500                    COBOL Name: 500-IRD-LD-CNT
      *
      * Output :  

      * - sys001IrdExtrFileRec           COBOL Name: SYS001-IRD-EXTR-FILE-REC
      * - sys001FileStatus200            COBOL Name: 200-SYS001-FILE-STATUS
      * - sys001KeyAll                   COBOL Name: SYS001-KEY-ALL
      * - sys001Key                      COBOL Name: SYS001-KEY
      * - irdLdCnt500                    COBOL Name: 500-IRD-LD-CNT
      * - irdIdx500                      COBOL Name: 500-IRD-IDX
      * - sys001Ird                      COBOL Name: SYS001-IRD
      * - ird500                         COBOL Name: 500-IRD
      * - isItEndOfData100               COBOL Name: 100-IS-IT-END-OF-DATA
      * - fileStatus600                  COBOL Name: 600-FILE-STATUS
      * - abendDescription600            COBOL Name: 600-ABEND-DESCRIPTION
      * - abendCode300                   COBOL Name: 300-ABEND-CODE
      * - abendParaName300               COBOL Name: 300-ABEND-PARA-NAME
      *
      * @throws CFException
      */
      @Override
      public ReadSys001FileOutCtx readSys001File(ReadSys001FileInCtx methodIn) throws Exception {
Mcvsam2Ctx programCtx = methodIn.getMcvsam2Ctx();
ReadSys001FileOutCtx methodOut = methodIn.getReadSys001FileOutCtx();
//  READ SYS001-IRD-EXTR-FILE NEXT END-READ
          sys001IrdExtrFile.readNext();
          methodOut.setSys001FileStatus200(sys001IrdExtrFile.getStatusString() );
          if (!sys001IrdExtrFile.hasEnded()) {
          	methodOut.getSys001IrdExtrFileRec().setString(sys001IrdExtrFile.getRecord());
          }
//  EVALUATE TRUE
          if  ( methodOut.isSys001IoGood88200()  ) { 
//  IF SYS001-KEY EQUAL 800-KEY
              if (		compareChars(methodOut.getSys001Key(),methodIn.getKey800()) == 0 ) { 
//  ADD 1 TO 500-IRD-LD-CNT
                  methodOut.setIrdLdCnt500( (short) (methodOut.getIrdLdCnt500()+(short)1));
//  SET 500-IRD-IDX TO 500-IRD-LD-CNT
                  methodOut.setIrdIdx500(methodOut.getIrdLdCnt500()); 
                  
//  MOVE SYS001-IRD TO 500-IRD ( 500-IRD-IDX )
                  methodOut.setIrd500(methodOut.getIrdIdx500() - 1,methodOut.getSys001Ird());
              }
//  ELSE
              else { 
//  SET 88-100-END-OF-DATA-Y TO TRUE
                  methodOut.setEndOfDataY88100True(); 
                  
              }
          }
          else if  ( methodOut.isSys001Eof88200()  ) { 
//  SET 88-100-END-OF-DATA-Y TO TRUE
              methodOut.setEndOfDataY88100True(); 
              
          }
          else   { 
//  MOVE 200-SYS001-FILE-STATUS TO 600-FILE-STATUS
              methodOut.setFileStatus600(methodOut.getSys001FileStatus200());
//  SET 88-600-ABEND-READ-SYS001 TO TRUE
              methodOut.setAbendReadSys00188600True(); 
              
//  SET 88-300-READ-ABEND-CODE TO TRUE
              methodOut.setReadAbendCode88300True(); 
              
//  SET 88-300-ABEND-PARA-8000 TO TRUE
              methodOut.setAbendPara800088300True(); 
              
//  PERFORM 9500-ABEND-PROGRAM
              abendProgram(programCtx.getAbendProgramInCtx());/*9500-ABEND-PROGRAM*/
          }
      
      return methodOut;
      }
      /**
      * abendProgram 
      *   This method is derived from 
  *   COBOL Paragraph - 9500-ABEND-PROGRAM COBOL Cyclomatic complexity - 1
      * Input  :  

      * - abendMessage600                COBOL Name: 600-ABEND-MESSAGE
      * - abendCode300                   COBOL Name: 300-ABEND-CODE
      * - abendPara900                   COBOL Name: 900-ABEND-PARA
      * - abendMessage900                COBOL Name: 900-ABEND-MESSAGE
      *
      * Output :  

      * - errorText900                   COBOL Name: 900-ERROR-TEXT
      * - ip60001EventErrorMsg           COBOL Name: IP60001-EVENT-ERROR-MSG
      * - abendMessage600                COBOL Name: 600-ABEND-MESSAGE
      * - abendCode900                   COBOL Name: 900-ABEND-CODE
      * - ip60001EventErrorCode          COBOL Name: IP60001-EVENT-ERROR-CODE
      * - abendCode300                   COBOL Name: 300-ABEND-CODE
      *
      * @throws CFException
      */
      @Override
      public AbendProgramOutCtx abendProgram(AbendProgramInCtx methodIn) throws Exception {
Mcvsam2Ctx programCtx = methodIn.getMcvsam2Ctx();
AbendProgramOutCtx methodOut = methodIn.getAbendProgramOutCtx();
          // MOVE 600-ABEND-MESSAGE TO 900-ERROR-TEXT IP60001-EVENT-ERROR-MSG
          methodOut.setErrorText900(methodOut.getAbendMessage600().toCharArray());
          methodOut.setIp60001EventErrorMsg(methodOut.getAbendMessage600().toCharArray());
//  MOVE 300-ABEND-CODE TO 900-ABEND-CODE IP60001-EVENT-ERROR-CODE
          methodOut.setAbendCode900(String.valueOf(methodOut.getAbendCode300String()).toCharArray());
          methodOut.setIp60001EventErrorCode(String.valueOf(methodOut.getAbendCode300String()).toCharArray());
//  DISPLAY '***********************************'
          logger.info("***********************************"); 
//  DISPLAY 'A B E N D   A B E N D   A B E N D  '
          logger.info("A B E N D   A B E N D   A B E N D  "); 
//  DISPLAY 'A B E N D   I P 3 2 2 3 1 0        '
          logger.info("A B E N D   I P 3 2 2 3 1 0        "); 
//  DISPLAY '***********************************'
          logger.info("***********************************"); 
//  DISPLAY 900-ABEND-PARA
          logger.info(new String(methodIn.getAbendPara900())); 
//  DISPLAY 900-ABEND-MESSAGE
          logger.info(methodIn.getAbendMessage900().toString()); 
      
      return methodOut;
      }
  
  
  
  
  
  
  
  
  }
