#
#STEP:S030_P070| PGM:IDCAMS| DD:DUP1IN
S030_P070.IDCAMS.Dup1in=Y910.P.ATM.TLFDUP1.FILE
S030_P070.IDCAMS.Dup1in.DISP=SHR,KEEP,KEEP
S030_P070.IDCAMS.Dup1in.RecordType=FB
S030_P070.IDCAMS.Dup1in.RecordLen=<recordLen>
#
#
#STEP:S030_P070| PGM:IDCAMS| DD:DUP1OT
S030_P070.IDCAMS.Dup1ot=Y910.P.ATM.BACKUP.TLFDUP1(+1)
S030_P070.IDCAMS.Dup1ot.DISP=NEW,CATLG,DELETE
S030_P070.IDCAMS.Dup1ot.RecordType=FB
S030_P070.IDCAMS.Dup1ot.RecordLen=123
#
#
#STEP:S030_P070| PGM:IDCAMS| DD:DUP2IN
S030_P070.IDCAMS.Dup2in=Y910.P.ATM.TLFDUP2.FILE
S030_P070.IDCAMS.Dup2in.DISP=SHR,KEEP,KEEP
S030_P070.IDCAMS.Dup2in.RecordType=FB
S030_P070.IDCAMS.Dup2in.RecordLen=<recordLen>
#
#
#STEP:S030_P070| PGM:IDCAMS| DD:DUP2OT
S030_P070.IDCAMS.Dup2ot=Y910.P.ATM.BACKUP.TLFDUP2(+1)
S030_P070.IDCAMS.Dup2ot.DISP=NEW,CATLG,DELETE
S030_P070.IDCAMS.Dup2ot.RecordType=FB
S030_P070.IDCAMS.Dup2ot.RecordLen=123
#
#
#STEP:S030_P070| PGM:IDCAMS| DD:DUP3IN
S030_P070.IDCAMS.Dup3in=Y910.P.ATM.TLFDUP3.FILE
S030_P070.IDCAMS.Dup3in.DISP=SHR,KEEP,KEEP
S030_P070.IDCAMS.Dup3in.RecordType=FB
S030_P070.IDCAMS.Dup3in.RecordLen=<recordLen>
#
#
#STEP:S030_P070| PGM:IDCAMS| DD:DUP3OT
S030_P070.IDCAMS.Dup3ot=Y910.P.ATM.BACKUP.TLFDUP3(+1)
S030_P070.IDCAMS.Dup3ot.DISP=NEW,CATLG,DELETE
S030_P070.IDCAMS.Dup3ot.RecordType=FB
S030_P070.IDCAMS.Dup3ot.RecordLen=123
#
#
#STEP:S030_P070| PGM:IDCAMS| DD:DUP4IN
S030_P070.IDCAMS.Dup4in=Y910.P.ATM.TLFDUP4.FILE
S030_P070.IDCAMS.Dup4in.DISP=SHR,KEEP,KEEP
S030_P070.IDCAMS.Dup4in.RecordType=FB
S030_P070.IDCAMS.Dup4in.RecordLen=<recordLen>
#
#
#STEP:S030_P070| PGM:IDCAMS| DD:DUP4OT
S030_P070.IDCAMS.Dup4ot=Y910.P.ATM.BACKUP.TLFDUP4(+1)
S030_P070.IDCAMS.Dup4ot.DISP=NEW,CATLG,DELETE
S030_P070.IDCAMS.Dup4ot.RecordType=FB
S030_P070.IDCAMS.Dup4ot.RecordLen=123
#
#
#STEP:S030_P070| PGM:IDCAMS| DD:HOLDIN
S030_P070.IDCAMS.Holdin[1]=Y910.P.ATM.ID.HOLDFILE
S030_P070.IDCAMS.Holdin[2]=Y910.P.ATM.ID.HOLDFIL1
S030_P070.IDCAMS.Holdin[3]=Y910.P.ATM.ID.HOLDFIL2
S030_P070.IDCAMS.Holdin[4]=Y910.P.ATM.ID.HOLDFIL3
S030_P070.IDCAMS.Holdin[5]=Y910.P.ATM.ID.HOLDFIL4
S030_P070.IDCAMS.Holdin.DISP=SHR,KEEP,KEEP
S030_P070.IDCAMS.Holdin.RecordType=FB
S030_P070.IDCAMS.Holdin.RecordLen=<recordLen>
#
#
#STEP:S030_P070| PGM:IDCAMS| DD:HOLDOT
S030_P070.IDCAMS.Holdot=Y910.P.ATM.BACKUP.HOLDFILE(+1)
S030_P070.IDCAMS.Holdot.DISP=NEW,CATLG,DELETE
S030_P070.IDCAMS.Holdot.RecordType=FB
S030_P070.IDCAMS.Holdot.RecordLen=80
#
