#STEP:STEP001| PGM:IEBGENER| DD:SYSUT1
STEP001.IEBGENER.Sysut1=DUMMY
#
#STEP:STEP001| PGM:IEBGENER| DD:SYSUT2
STEP001.IEBGENER.Sysut2=CLOUDFRM.SF.CSMIP1.A.BKUP.FCOPY(+1)
STEP001.IEBGENER.Sysut2.DISP=NEW,CATLG,DELETE
STEP001.IEBGENER.Sysut2.RecordType=VB
STEP001.IEBGENER.Sysut2.RecordLen=8004
#
#STEP:STEP001| PGM:IEBGENER| DD:SYSUT3
STEP001.IEBGENER.Sysut3=CLOUDFRM.SF.CSMIP2.A.BKUP.FCOPY(+1)
STEP001.IEBGENER.Sysut3.DISP=NEW,CATLG,DELETE
STEP001.IEBGENER.Sysut3.RecordType=VB
STEP001.IEBGENER.Sysut3.RecordLen=8004
#
#STEP:STEP001| PGM:IEBGENER| DD:SYSUT4
STEP001.IEBGENER.Sysut4=CLOUDFRM.SF.CSMIP3.A.BKUP.FCOPY(+1)
STEP001.IEBGENER.Sysut4.DISP=NEW,CATLG,DELETE
STEP001.IEBGENER.Sysut4.RecordType=VB
STEP001.IEBGENER.Sysut4.RecordLen=8004
#
#STEP:STEP001| PGM:IEBGENER| DD:SYSUT5
STEP001.IEBGENER.Sysut5=CLOUDFRM.SF.CSMIP4.A.BKUP.FCOPY(+1)
STEP001.IEBGENER.Sysut5.DISP=NEW,CATLG,DELETE
STEP001.IEBGENER.Sysut5.RecordType=VB
STEP001.IEBGENER.Sysut5.RecordLen=8004
#
