# Program CALLFD01 | DD : INFILE | RecordFormat : FixedLength | RecordLength : 1001
CALLFD01.ddname.INFILE=InputFile
CALLFD01.InputFile=InputFile
CALLFD01.InputFileCharSet=cp1047
CALLFD01.InputFileCRLFflag=no
# Program CALLFD01 | DD : OUTFILE | RecordFormat : FixedLength | RecordLength : 1001
CALLFD01.ddname.OUTFILE=OutputFile
CALLFD01.OutputFile=OutputFile
CALLFD01.OutputFileCharSet=cp1047
CALLFD01.OutputFileCRLFflag=no
# 
# End of CALLFD01
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
inputValue1=
# End of CALLFD02
