<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="IoErrorType600" cobol:name="600-IO-ERROR-TYPE" cobol:offset="0" cobol:length="109" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="IoErrTxt600" maxOccurs="1"  cobol:name="600-IO-ERR-TXT" cobol:offset="0" cobol:length="40" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="Long.MAX_VALUE" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 openError88600 VALUE [["ERROR OPENING SYS001 FILE.              "]].
                        88 readError88600 VALUE [["ERROR READING SYS001 FILE.              "]].
                        88 closeError88600 VALUE [["ERROR CLOSING SYS001 FILE.              "]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="40" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="IoErrorType600Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="40" cobol:length="12" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="12" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Sys001FileStat600" type="xs:int" maxOccurs="1"  cobol:name="600-SYS001-FILE-STAT" cobol:offset="52" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="NoOfRecords600" maxOccurs="1"  cobol:name="600-NO-OF-RECORDS" cobol:offset="54" cobol:length="55" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="55" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
