#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
# Program MC083 | DD : FBFILE | RecordFormat : FixedLength | RecordLength : 80
MC083.ddname.FBFILE=FbFile
MC083.FbFile=FbFile
MC083.FbFileCharSet=cp1047
MC083.FbFileCRLFflag=no
# 
# End of MC083
