<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="BpDates" cobol:name="WS-BP-DATES" cobol:offset="18" cobol:length="36" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="StartDt" maxOccurs="1" cobol:name="WS-START-DT" cobol:offset="0" cobol:length="10" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="EndDt" maxOccurs="1" cobol:name="WS-END-DT" cobol:offset="10" cobol:length="10" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="StartDtIso" type="xs:long" maxOccurs="1"  cobol:name="WS-START-DT-ISO" cobol:offset="20" cobol:length="8" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
         <xs:element name="EndDtIso" type="xs:long" maxOccurs="1"  cobol:name="WS-END-DT-ISO" cobol:offset="28" cobol:length="8" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
