<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="ChgEndDtIso2Redefined" cobol:name="WS-CHG-END-DT-ISO-2-REDEFINED" cobol:offset="108" cobol:length="8" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="ChgEndYy2" type="xs:int" maxOccurs="1"  cobol:name="WS-CHG-END-YY-2" cobol:offset="0" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
         <xs:element name="ChgEndMm2" type="xs:int" maxOccurs="1"  cobol:name="WS-CHG-END-MM-2" cobol:offset="4" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="ChgEndDd2" type="xs:int" maxOccurs="1"  cobol:name="WS-CHG-END-DD-2" cobol:offset="6" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
