<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="CmnDateCalcNewDateCalcR" cobol:name="CMN-DATE-CALC-NEW-DATE-CALC-R" cobol:offset="1058" cobol:length="10" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="CmnDateCalcNewDateMm" type="xs:int" maxOccurs="1"  cobol:name="CMN-DATE-CALC-NEW-DATE-MM" cobol:offset="0" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="CmnDateCalcNewDateSep1" maxOccurs="1"  cobol:name="CMN-DATE-CALC-NEW-DATE-SEP1" cobol:offset="2" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="CmnDateCalcNewDateDd" type="xs:int" maxOccurs="1"  cobol:name="CMN-DATE-CALC-NEW-DATE-DD" cobol:offset="3" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="CmnDateCalcNewDateSep2" maxOccurs="1"  cobol:name="CMN-DATE-CALC-NEW-DATE-SEP2" cobol:offset="5" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="CmnDateCalcNewDateYyyy" maxOccurs="1" cobol:name="CMN-DATE-CALC-NEW-DATE-YYYY" cobol:offset="6" cobol:length="4" cobol:datatype="Group" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
