<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="CmnDateCalcTypeOpt56" cobol:name="CMN-DATE-CALC-TYPE-OPT-5-6" cobol:offset="1028" cobol:length="1" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="CmnDateCalcDowIndicator" maxOccurs="1"  cobol:name="CMN-DATE-CALC-DOW-INDICATOR" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 mondaysDate12 VALUE [["1"]].
                        88 tuesdaysDate12 VALUE [["2"]].
                        88 wednesdaysDate12 VALUE [["3"]].
                        88 thursdaysDate12 VALUE [["4"]].
                        88 fridaysDate12 VALUE [["5"]].
                        88 saturdaysDate12 VALUE [["6"]].
                        88 sundaysDate12 VALUE [["7"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
