<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="CmnErrMsg2" cobol:name="CMN-ERR-MSG-2" cobol:offset="80" cobol:length="80" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="CmnErrorMessagesFiller2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="0" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CmnErrorMessagesFiller3" maxOccurs="1"  cobol:name="FILLER" cobol:offset="3" cobol:length="18" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CmnErrorMessagesFiller4" maxOccurs="1"  cobol:name="FILLER" cobol:offset="30" cobol:length="12" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="12" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CmnErrorMessagesFiller5" maxOccurs="1"  cobol:name="FILLER" cobol:offset="46" cobol:length="19" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="19" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CmnErrorMessagesFiller6" maxOccurs="1"  cobol:name="FILLER" cobol:offset="79" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
