<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="CmnPeriodInput" cobol:name="CMN-PERIOD-INPUT" cobol:offset="1024" cobol:length="4" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="CmnPeriodInputMm" type="xs:int" maxOccurs="1"  cobol:name="CMN-PERIOD-INPUT-MM" cobol:offset="0" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="CmnPeriodInputYy" type="xs:int" maxOccurs="1"  cobol:name="CMN-PERIOD-INPUT-YY" cobol:offset="2" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
