<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="DclWipBlCycPhaseAudit" cobol:name="DCL-WIP-BL-CYC-PHASE-AUDIT" cobol:offset="0" cobol:length="73" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Tb33006BlSegregateNo" type="xs:short" maxOccurs="1"  cobol:name="TB33006-BL-SEGREGATE-NO" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="Tb33006BlCycNo" maxOccurs="1"  cobol:name="TB33006-BL-CYC-NO" cobol:offset="2" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Tb33006BlStreamCd" maxOccurs="1"  cobol:name="TB33006-BL-STREAM-CD" cobol:offset="4" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Tb33006JobIterationNo" type="xs:short" maxOccurs="1"  cobol:name="TB33006-JOB-ITERATION-NO" cobol:offset="5" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="Tb33006PhaseTyp" maxOccurs="1"  cobol:name="TB33006-PHASE-TYP" cobol:offset="7" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Tb33006CycMthYr" maxOccurs="1"  cobol:name="TB33006-CYC-MTH-YR" cobol:offset="9" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Tb33006RptTypCd" maxOccurs="1"  cobol:name="TB33006-RPT-TYP-CD" cobol:offset="15" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Tb33006RptAttrCd" maxOccurs="1"  cobol:name="TB33006-RPT-ATTR-CD" cobol:offset="20" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Tb33006RptAttrIdNo" type="xs:int" maxOccurs="1"  cobol:name="TB33006-RPT-ATTR-ID-NO" cobol:offset="23" cobol:length="4" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
    <xs:element name="Tb33006RptColNameCd" maxOccurs="1"  cobol:name="TB33006-RPT-COL-NAME-CD" cobol:offset="27" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Tb33006RptColTypCd" maxOccurs="1"  cobol:name="TB33006-RPT-COL-TYP-CD" cobol:offset="30" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Tb33006RptColValue" maxOccurs="1"  cobol:name="TB33006-RPT-COL-VALUE" cobol:offset="31" cobol:length="8" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1P">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="15" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Tb33006DbUserid" maxOccurs="1"  cobol:name="TB33006-DB-USERID" cobol:offset="39" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Tb33006DbTmstamp" maxOccurs="1"  cobol:name="TB33006-DB-TMSTAMP" cobol:offset="47" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
