<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="FillerBeginEnd1" cobol:name="FILLER-BEGIN-END1" cobol:offset="0" cobol:length="91" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
<xs:element name="IypInit9" maxOccurs="1" cobol:name="WS-9IYP-INIT" cobol:offset="0" cobol:length="56" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="IypCurr9" maxOccurs="1" cobol:name="WS-9IYP-CURR" cobol:offset="56" cobol:length="24" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Ws9iypAddedSw" maxOccurs="1"  cobol:name="WS-WS9IYP-ADDED-SW" cobol:offset="80" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="IypPriorCnt9" type="xs:int" maxOccurs="1"  cobol:name="WS-9IYP-PRIOR-CNT" cobol:offset="81" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="Filler6" type="xs:int" maxOccurs="1"  cobol:name="FILLER6" cobol:offset="83" cobol:length="4" cobol:datatype="Pointer" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
         <xs:element name="Filler7" type="xs:int" maxOccurs="1"  cobol:name="FILLER7" cobol:offset="87" cobol:length="4" cobol:datatype="Pointer" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10M"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
