<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="WsrevRevoStatRecord" cobol:name="WSREV-REVO-STAT-RECORD" cobol:offset="0" cobol:length="300" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="WsrevVisionInstanceCd" maxOccurs="1"  cobol:name="WSREV-VISION-INSTANCE-CD" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsrevUbOrigInstance" maxOccurs="1"  cobol:name="WSREV-UB-ORIG-INSTANCE" cobol:offset="1" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsrevUbOrigFileName" maxOccurs="1"  cobol:name="WSREV-UB-ORIG-FILE-NAME" cobol:offset="21" cobol:length="40" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="40" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsrevBillCycleDt" maxOccurs="1"  cobol:name="WSREV-BILL-CYCLE-DT" cobol:offset="61" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsrevSwitchId" maxOccurs="1"  cobol:name="WSREV-SWITCH-ID" cobol:offset="71" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsrevDataType" maxOccurs="1"  cobol:name="WSREV-DATA-TYPE" cobol:offset="74" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsrevReceivedTmstamp" maxOccurs="1"  cobol:name="WSREV-RECEIVED-TMSTAMP" cobol:offset="78" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsrevCreateTmstamp" maxOccurs="1"  cobol:name="WSREV-CREATE-TMSTAMP" cobol:offset="104" cobol:length="26" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="26" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsrevFileStatus" maxOccurs="1"  cobol:name="WSREV-FILE-STATUS" cobol:offset="130" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsrevReason" maxOccurs="1"  cobol:name="WSREV-REASON" cobol:offset="140" cobol:length="40" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="40" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WsrevInputCount" type="xs:long" maxOccurs="1"  cobol:name="WSREV-INPUT-COUNT" cobol:offset="180" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="WsrevFilteredCount" type="xs:long" maxOccurs="1"  cobol:name="WSREV-FILTERED-COUNT" cobol:offset="189" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="WsrevRejectedCount" type="xs:long" maxOccurs="1"  cobol:name="WSREV-REJECTED-COUNT" cobol:offset="198" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="WsrevBilledCount" type="xs:long" maxOccurs="1"  cobol:name="WSREV-BILLED-COUNT" cobol:offset="207" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
    <xs:element name="WsrevStreamCd" maxOccurs="1"  cobol:name="WSREV-STREAM-CD" cobol:offset="216" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="WsrevIterNo" type="xs:int" maxOccurs="1"  cobol:name="WSREV-ITER-NO" cobol:offset="217" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
         <xs:element name="WsrevCycleNo" type="xs:int" maxOccurs="1"  cobol:name="WSREV-CYCLE-NO" cobol:offset="221" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="WsrevDataChgAmt" maxOccurs="1"  cobol:name="WSREV-DATA-CHG-AMT" cobol:offset="223" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="9" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsrevRejDataChgAmt" maxOccurs="1"  cobol:name="WSREV-REJ-DATA-CHG-AMT" cobol:offset="232" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="9" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsrevBilledDataChgAmt" maxOccurs="1"  cobol:name="WSREV-BILLED-DATA-CHG-AMT" cobol:offset="241" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="9" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsrevVersionNum" maxOccurs="1"  cobol:name="WSREV-VERSION-NUM" cobol:offset="250" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WsrevRevoStatRecordFiller1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="254" cobol:length="46" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="46" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
