<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="WvExtrDetails" cobol:name="WV-EXTR-DETAILS" cobol:offset="0" cobol:length="624" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="WvExtrParcel" maxOccurs="1"  cobol:name="WV-EXTR-PARCEL" cobol:offset="0" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="8" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrCounterparty" maxOccurs="1"  cobol:name="WV-EXTR-COUNTERPARTY" cobol:offset="9" cobol:length="9" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="18" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrOwner" maxOccurs="1"  cobol:name="WV-EXTR-OWNER" cobol:offset="19" cobol:length="9" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller3" maxOccurs="1"  cobol:name="FILLER" cobol:offset="28" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrLoadDateFrom" maxOccurs="1"  cobol:name="WV-EXTR-LOAD-DATE-FROM" cobol:offset="29" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller4" maxOccurs="1"  cobol:name="FILLER" cobol:offset="39" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrLoadDateTo" maxOccurs="1"  cobol:name="WV-EXTR-LOAD-DATE-TO" cobol:offset="40" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller5" maxOccurs="1"  cobol:name="FILLER" cobol:offset="50" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrDiscDateFrom" maxOccurs="1"  cobol:name="WV-EXTR-DISC-DATE-FROM" cobol:offset="51" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller6" maxOccurs="1"  cobol:name="FILLER" cobol:offset="61" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrDiscDateTo" maxOccurs="1"  cobol:name="WV-EXTR-DISC-DATE-TO" cobol:offset="62" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller7" maxOccurs="1"  cobol:name="FILLER" cobol:offset="72" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrSettlementDate" maxOccurs="1"  cobol:name="WV-EXTR-SETTLEMENT-DATE" cobol:offset="73" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller8" maxOccurs="1"  cobol:name="FILLER" cobol:offset="83" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrSettlementOride" maxOccurs="1"  cobol:name="WV-EXTR-SETTLEMENT-ORIDE" cobol:offset="84" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller9" maxOccurs="1"  cobol:name="FILLER" cobol:offset="85" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrValueX" maxOccurs="1" cobol:name="WV-EXTR-VALUE-X" cobol:offset="86" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller10" maxOccurs="1"  cobol:name="FILLER" cobol:offset="98" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrBlDate" maxOccurs="1"  cobol:name="WV-EXTR-BL-DATE" cobol:offset="99" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller11" maxOccurs="1"  cobol:name="FILLER" cobol:offset="109" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrDcDate" maxOccurs="1"  cobol:name="WV-EXTR-DC-DATE" cobol:offset="110" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller12" maxOccurs="1"  cobol:name="FILLER" cobol:offset="120" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrLatestPriceDate" maxOccurs="1"  cobol:name="WV-EXTR-LATEST-PRICE-DATE" cobol:offset="121" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller13" maxOccurs="1"  cobol:name="FILLER" cobol:offset="131" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrOperator" maxOccurs="1"  cobol:name="WV-EXTR-OPERATOR" cobol:offset="132" cobol:length="9" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="9" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller14" maxOccurs="1"  cobol:name="FILLER" cobol:offset="141" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrQuantityX" maxOccurs="1" cobol:name="WV-EXTR-QUANTITY-X" cobol:offset="142" cobol:length="9" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller15" maxOccurs="1"  cobol:name="FILLER" cobol:offset="151" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrUnitCode" maxOccurs="1"  cobol:name="WV-EXTR-UNIT-CODE" cobol:offset="152" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller16" maxOccurs="1"  cobol:name="FILLER" cobol:offset="155" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrLdgBblX" maxOccurs="1" cobol:name="WV-EXTR-LDG-BBL-X" cobol:offset="156" cobol:length="13" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller17" maxOccurs="1"  cobol:name="FILLER" cobol:offset="169" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrLdgMtX" maxOccurs="1" cobol:name="WV-EXTR-LDG-MT-X" cobol:offset="170" cobol:length="13" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller18" maxOccurs="1"  cobol:name="FILLER" cobol:offset="183" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrDchBblX" maxOccurs="1" cobol:name="WV-EXTR-DCH-BBL-X" cobol:offset="184" cobol:length="13" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller19" maxOccurs="1"  cobol:name="FILLER" cobol:offset="197" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrDchMtX" maxOccurs="1" cobol:name="WV-EXTR-DCH-MT-X" cobol:offset="198" cobol:length="13" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller20" maxOccurs="1"  cobol:name="FILLER" cobol:offset="211" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrSettleTerms1" maxOccurs="1"  cobol:name="WV-EXTR-SETTLE-TERMS-1" cobol:offset="212" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller21" maxOccurs="1"  cobol:name="FILLER" cobol:offset="218" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrSettleTerms2" maxOccurs="1"  cobol:name="WV-EXTR-SETTLE-TERMS-2" cobol:offset="219" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller22" maxOccurs="1"  cobol:name="FILLER" cobol:offset="225" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrEarlyLate" maxOccurs="1"  cobol:name="WV-EXTR-EARLY-LATE" cobol:offset="226" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller23" maxOccurs="1"  cobol:name="FILLER" cobol:offset="227" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrInvoiced" maxOccurs="1"  cobol:name="WV-EXTR-INVOICED" cobol:offset="228" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller24" maxOccurs="1"  cobol:name="FILLER" cobol:offset="229" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrBuySell" maxOccurs="1"  cobol:name="WV-EXTR-BUY-SELL" cobol:offset="230" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller25" maxOccurs="1"  cobol:name="FILLER" cobol:offset="231" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrGrade" maxOccurs="1"  cobol:name="WV-EXTR-GRADE" cobol:offset="232" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller26" maxOccurs="1"  cobol:name="FILLER" cobol:offset="237" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrTerms" maxOccurs="1"  cobol:name="WV-EXTR-TERMS" cobol:offset="238" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller27" maxOccurs="1"  cobol:name="FILLER" cobol:offset="243" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrVessel" maxOccurs="1"  cobol:name="WV-EXTR-VESSEL" cobol:offset="244" cobol:length="75" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="75" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller28" maxOccurs="1"  cobol:name="FILLER" cobol:offset="319" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrLdgNorDate" maxOccurs="1"  cobol:name="WV-EXTR-LDG-NOR-DATE" cobol:offset="320" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller29" maxOccurs="1"  cobol:name="FILLER" cobol:offset="330" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrLdgNorTime" maxOccurs="1"  cobol:name="WV-EXTR-LDG-NOR-TIME" cobol:offset="331" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller30" maxOccurs="1"  cobol:name="FILLER" cobol:offset="336" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrDchNorDate" maxOccurs="1"  cobol:name="WV-EXTR-DCH-NOR-DATE" cobol:offset="337" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller31" maxOccurs="1"  cobol:name="FILLER" cobol:offset="347" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrDchNorTime" maxOccurs="1"  cobol:name="WV-EXTR-DCH-NOR-TIME" cobol:offset="348" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller32" maxOccurs="1"  cobol:name="FILLER" cobol:offset="353" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrSapDocCode" maxOccurs="1"  cobol:name="WV-EXTR-SAP-DOC-CODE" cobol:offset="354" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller33" maxOccurs="1"  cobol:name="FILLER" cobol:offset="364" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrSetlCurr" maxOccurs="1"  cobol:name="WV-EXTR-SETL-CURR" cobol:offset="365" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller34" maxOccurs="1"  cobol:name="FILLER" cobol:offset="368" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrLcStatus" maxOccurs="1"  cobol:name="WV-EXTR-LC-STATUS" cobol:offset="369" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller35" maxOccurs="1"  cobol:name="FILLER" cobol:offset="370" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrSancStatus" maxOccurs="1"  cobol:name="WV-EXTR-SANC-STATUS" cobol:offset="371" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller36" maxOccurs="1"  cobol:name="FILLER" cobol:offset="374" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrCalcWork" maxOccurs="1"  cobol:name="WV-EXTR-CALC-WORK" cobol:offset="375" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller37" maxOccurs="1"  cobol:name="FILLER" cobol:offset="376" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrRefDensityX" maxOccurs="1" cobol:name="WV-EXTR-REF-DENSITY-X" cobol:offset="377" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller38" maxOccurs="1"  cobol:name="FILLER" cobol:offset="389" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrActDensityX" maxOccurs="1" cobol:name="WV-EXTR-ACT-DENSITY-X" cobol:offset="390" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller39" maxOccurs="1"  cobol:name="FILLER" cobol:offset="402" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrStiFlag" maxOccurs="1"  cobol:name="WV-EXTR-STI-FLAG" cobol:offset="403" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller40" maxOccurs="1"  cobol:name="FILLER" cobol:offset="404" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrMethod" maxOccurs="1"  cobol:name="WV-EXTR-METHOD" cobol:offset="405" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller41" maxOccurs="1"  cobol:name="FILLER" cobol:offset="407" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrPrclNote" maxOccurs="1"  cobol:name="WV-EXTR-PRCL-NOTE" cobol:offset="408" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller42" maxOccurs="1"  cobol:name="FILLER" cobol:offset="409" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrSendToGsap" maxOccurs="1"  cobol:name="WV-EXTR-SEND-TO-GSAP" cobol:offset="410" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller43" maxOccurs="1"  cobol:name="FILLER" cobol:offset="411" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrLinkedFrom" maxOccurs="1"  cobol:name="WV-EXTR-LINKED-FROM" cobol:offset="412" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller44" maxOccurs="1"  cobol:name="FILLER" cobol:offset="422" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrSecToShell" maxOccurs="1"  cobol:name="WV-EXTR-SEC-TO-SHELL" cobol:offset="423" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller45" maxOccurs="1"  cobol:name="FILLER" cobol:offset="428" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrInvoiceQty" maxOccurs="1"  cobol:name="WV-EXTR-INVOICE-QTY" cobol:offset="429" cobol:length="12" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="12" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller46" maxOccurs="1"  cobol:name="FILLER" cobol:offset="441" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrInvoiceUnit" maxOccurs="1"  cobol:name="WV-EXTR-INVOICE-UNIT" cobol:offset="442" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller47" maxOccurs="1"  cobol:name="FILLER" cobol:offset="445" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrLloydsNum" maxOccurs="1"  cobol:name="WV-EXTR-LLOYDS-NUM" cobol:offset="446" cobol:length="7" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller48" maxOccurs="1"  cobol:name="FILLER" cobol:offset="453" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrLdgUsgX" maxOccurs="1" cobol:name="WV-EXTR-LDG-USG-X" cobol:offset="454" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller49" maxOccurs="1"  cobol:name="FILLER" cobol:offset="466" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrLdgM315X" maxOccurs="1" cobol:name="WV-EXTR-LDG-M3-15-X" cobol:offset="467" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller50" maxOccurs="1"  cobol:name="FILLER" cobol:offset="479" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrLdgM320X" maxOccurs="1" cobol:name="WV-EXTR-LDG-M3-20-X" cobol:offset="480" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller51" maxOccurs="1"  cobol:name="FILLER" cobol:offset="492" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrLdgM330X" maxOccurs="1" cobol:name="WV-EXTR-LDG-M3-30-X" cobol:offset="493" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller52" maxOccurs="1"  cobol:name="FILLER" cobol:offset="505" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrLdgM3AmbX" maxOccurs="1" cobol:name="WV-EXTR-LDG-M3-AMB-X" cobol:offset="506" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller53" maxOccurs="1"  cobol:name="FILLER" cobol:offset="518" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrDchUsgX" maxOccurs="1" cobol:name="WV-EXTR-DCH-USG-X" cobol:offset="519" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller54" maxOccurs="1"  cobol:name="FILLER" cobol:offset="531" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrDchM315X" maxOccurs="1" cobol:name="WV-EXTR-DCH-M3-15-X" cobol:offset="532" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller55" maxOccurs="1"  cobol:name="FILLER" cobol:offset="544" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrDchM320X" maxOccurs="1" cobol:name="WV-EXTR-DCH-M3-20-X" cobol:offset="545" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller56" maxOccurs="1"  cobol:name="FILLER" cobol:offset="557" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrDchM330X" maxOccurs="1" cobol:name="WV-EXTR-DCH-M3-30-X" cobol:offset="558" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller57" maxOccurs="1"  cobol:name="FILLER" cobol:offset="570" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="WvExtrDchM3AmbX" maxOccurs="1" cobol:name="WV-EXTR-DCH-M3-AMB-X" cobol:offset="571" cobol:length="12" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="WvExtrRecordFiller58" maxOccurs="1"  cobol:name="FILLER" cobol:offset="583" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrFrmlName" maxOccurs="1"  cobol:name="WV-EXTR-FRML-NAME" cobol:offset="584" cobol:length="15" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="15" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller59" maxOccurs="1"  cobol:name="FILLER" cobol:offset="599" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrFrmlVers" maxOccurs="1"  cobol:name="WV-EXTR-FRML-VERS" cobol:offset="600" cobol:length="2" cobol:datatype="Disp-Num-Edit" cobol:serialize="true" cobol:blankWhenZero="true" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller60" maxOccurs="1"  cobol:name="FILLER" cobol:offset="602" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrLoadPort" maxOccurs="1"  cobol:name="WV-EXTR-LOAD-PORT" cobol:offset="603" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrRecordFiller61" maxOccurs="1"  cobol:name="FILLER" cobol:offset="613" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="WvExtrDiscPort" maxOccurs="1"  cobol:name="WV-EXTR-DISC-PORT" cobol:offset="614" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
