package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] EBCDIC_ENCODING = "cp1047".toCharArray();
public static final char[] FORMAT_1223488108 = "-ZZZZ9".toCharArray();
public static final char[] MODE_READ_ONLY_36242 = "r".toCharArray();
public static final char[] MODE_WRITE_ONLY_36397 = "w".toCharArray();
 
}
