package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.utility.CFUtil;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] SPACE_255 = CFUtil.fillSpaces(255);
public static final char[] EBCDIC_ENCODING = "cp1047".toCharArray();
public static final char[] FORMAT1016334848 = "----".toCharArray();
public static final char[] FORMAT260474221 = "-ZZZZZZZZZ".toCharArray();
public static final char[] LITERAL_1872643415 = CFUtil.pad(255, "16th April 2022", " ",CFUtil.RIGHT_PAD);
public static final char[] LITERAL_1927616395 = CFUtil.pad(255, "Testing VARCHAR Length Issues", " ",CFUtil.RIGHT_PAD);
public static final char[] LITERAL_521471397 = CFUtil.pad(255, "Null", " ",CFUtil.RIGHT_PAD);
public static final char[] LITERAL_DB2VARCH = "DB2VARCH".toCharArray();
public static final char[] LITERAL_DB2VARCL = "DB2VARCL".toCharArray();
public static final char[] LITERAL_MN_1 = "-1".toCharArray();
public static final char[] LITERAL_Y = "Y".toCharArray();
 
}
