  package com.cloudframe.app.process;
  /* Java code generated by CloudFrame on 2025-04-28 at 07:09. */
  
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.crazy88.dto.*;
  import com.cloudframe.app.crazy88.dto.WCharG;
  import com.cloudframe.app.crazy88.dto.WI;
  import com.cloudframe.app.crazy88.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  import com.cloudframe.app.utility.CFUtil;
  
  @Component("crazy88")
  
  public class Crazy88 extends CommonProcess {
  
  Logger logger = LoggerFactory.getLogger(Crazy88.class);
  
  private WCharG wCharG = new WCharG() ;
  private WI wI = new WI() ;
  private Work work = new Work() ;
  
  
  
  
  
  
  
  
  
      /**
      * process 
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      @Override
      public int process() throws Exception {
       initVars();
       try {
       setCodePage("1047");
          ;
//  PERFORM 0000-MAIN
          main();/*0000-MAIN*/
          if (this.isProgramEnded()) {
              return getRc();
          }
//  PERFORM 9999-END
          end();/*9999-END*/
          if (this.isProgramEnded()) {
              return getRc();
          }
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
       return getRc(); // Exit with return code
      // end of process method
      }
      /**
      * main 
      *   This method is derived from 
  *   COBOL Paragraph - 0000-MAIN COBOL Cyclomatic complexity - 48
      * Input  :  

      * - i                              COBOL Name: I
      * - wI                             COBOL Name: W-I
      *
      * Output :  

      * - i                              COBOL Name: I
      * - wCharG                         COBOL Name: W-CHAR-G
      * - wI                             COBOL Name: W-I
      * - wCharTestData                  COBOL Name: W-CHAR-TEST-DATA
      * - w300EvalChar                   COBOL Name: W-300-EVAL-CHAR
      *
      * @throws CFException
      */
      private void main() throws Exception {
//  DISPLAY ' '
          logger.info(" "); 
//  DISPLAY 'BEGIN CRAZY88'
          logger.info("BEGIN CRAZY88"); 
//  DISPLAY ' '
          logger.info(" "); 
//  PERFORM VARYING I FROM ZERO BY +1 UNTIL I > 255
          for (wI.setI(0); (	( wI.getI() <= 255 ) ) ; wI.setI(wI.getI() + 1) ) {
              // MOVE W-I TO W-CHAR-G
              wCharG.setString(wI.getCharArray());
//  MOVE W-CHAR-TEST-DATA TO W-300-EVAL-CHAR
              work.setW300EvalChar(wCharG.getWCharTestData());
//  IF 300-EVAL-CHAR
              if ( work.isEvalChar300()  ) { 
//  DISPLAY '300-EVAL-CHAR IS TRUE FOR I VALUE: ' I ' AND W-300-EVAL-CHAR VALUE: ' W-300-EVAL-CHAR
                  logger.info("300-EVAL-CHAR IS TRUE FOR I VALUE: {} AND W-300-EVAL-CHAR VALUE: {}", String.valueOf(wI.getI()), new String(work.getW300EvalChar())); 
//  EVALUATE TRUE
                  if  ( work.isEvalCharLetter300()  ) { 
//  DISPLAY '300-EVAL-CHAR-LETTER IS TRUE'
                      logger.info("300-EVAL-CHAR-LETTER IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharA300()  ) { 
//  DISPLAY '300-EVAL-CHAR-A IS TRUE'
                      logger.info("300-EVAL-CHAR-A IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharB300()  ) { 
//  DISPLAY '300-EVAL-CHAR-B IS TRUE'
                      logger.info("300-EVAL-CHAR-B IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharC300()  ) { 
//  DISPLAY '300-EVAL-CHAR-C IS TRUE'
                      logger.info("300-EVAL-CHAR-C IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharD300()  ) { 
//  DISPLAY '300-EVAL-CHAR-D IS TRUE'
                      logger.info("300-EVAL-CHAR-D IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharE300()  ) { 
//  DISPLAY '300-EVAL-CHAR-E IS TRUE'
                      logger.info("300-EVAL-CHAR-E IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharF300()  ) { 
//  DISPLAY '300-EVAL-CHAR-F IS TRUE'
                      logger.info("300-EVAL-CHAR-F IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharG300()  ) { 
//  DISPLAY '300-EVAL-CHAR-G IS TRUE'
                      logger.info("300-EVAL-CHAR-G IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharH300()  ) { 
//  DISPLAY '300-EVAL-CHAR-H IS TRUE'
                      logger.info("300-EVAL-CHAR-H IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharI300()  ) { 
//  DISPLAY '300-EVAL-CHAR-I IS TRUE'
                      logger.info("300-EVAL-CHAR-I IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharJ300()  ) { 
//  DISPLAY '300-EVAL-CHAR-J IS TRUE'
                      logger.info("300-EVAL-CHAR-J IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharK300()  ) { 
//  DISPLAY '300-EVAL-CHAR-K IS TRUE'
                      logger.info("300-EVAL-CHAR-K IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharL300()  ) { 
//  DISPLAY '300-EVAL-CHAR-L IS TRUE'
                      logger.info("300-EVAL-CHAR-L IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharM300()  ) { 
//  DISPLAY '300-EVAL-CHAR-M IS TRUE'
                      logger.info("300-EVAL-CHAR-M IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharN300()  ) { 
//  DISPLAY '300-EVAL-CHAR-N IS TRUE'
                      logger.info("300-EVAL-CHAR-N IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharO300()  ) { 
//  DISPLAY '300-EVAL-CHAR-O IS TRUE'
                      logger.info("300-EVAL-CHAR-O IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharP300()  ) { 
//  DISPLAY '300-EVAL-CHAR-P IS TRUE'
                      logger.info("300-EVAL-CHAR-P IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharQ300()  ) { 
//  DISPLAY '300-EVAL-CHAR-Q IS TRUE'
                      logger.info("300-EVAL-CHAR-Q IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharR300()  ) { 
//  DISPLAY '300-EVAL-CHAR-R IS TRUE'
                      logger.info("300-EVAL-CHAR-R IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharS300()  ) { 
//  DISPLAY '300-EVAL-CHAR-S IS TRUE'
                      logger.info("300-EVAL-CHAR-S IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharT300()  ) { 
//  DISPLAY '300-EVAL-CHAR-T IS TRUE'
                      logger.info("300-EVAL-CHAR-T IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharU300()  ) { 
//  DISPLAY '300-EVAL-CHAR-U IS TRUE'
                      logger.info("300-EVAL-CHAR-U IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharV300()  ) { 
//  DISPLAY '300-EVAL-CHAR-V IS TRUE'
                      logger.info("300-EVAL-CHAR-V IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharW300()  ) { 
//  DISPLAY '300-EVAL-CHAR-W IS TRUE'
                      logger.info("300-EVAL-CHAR-W IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharX300()  ) { 
//  DISPLAY '300-EVAL-CHAR-X IS TRUE'
                      logger.info("300-EVAL-CHAR-X IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharY300()  ) { 
//  DISPLAY '300-EVAL-CHAR-Y IS TRUE'
                      logger.info("300-EVAL-CHAR-Y IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharZ300()  ) { 
//  DISPLAY '300-EVAL-CHAR-Z IS TRUE'
                      logger.info("300-EVAL-CHAR-Z IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalChar0300()  ) { 
//  DISPLAY '300-EVAL-CHAR-0 IS TRUE'
                      logger.info("300-EVAL-CHAR-0 IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalChar1300()  ) { 
//  DISPLAY '300-EVAL-CHAR-1 IS TRUE'
                      logger.info("300-EVAL-CHAR-1 IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalChar2300()  ) { 
//  DISPLAY '300-EVAL-CHAR-2 IS TRUE'
                      logger.info("300-EVAL-CHAR-2 IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalChar3300()  ) { 
//  DISPLAY '300-EVAL-CHAR-3 IS TRUE'
                      logger.info("300-EVAL-CHAR-3 IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalChar4300()  ) { 
//  DISPLAY '300-EVAL-CHAR-4 IS TRUE'
                      logger.info("300-EVAL-CHAR-4 IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalChar5300()  ) { 
//  DISPLAY '300-EVAL-CHAR-5 IS TRUE'
                      logger.info("300-EVAL-CHAR-5 IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalChar6300()  ) { 
//  DISPLAY '300-EVAL-CHAR-6 IS TRUE'
                      logger.info("300-EVAL-CHAR-6 IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalChar7300()  ) { 
//  DISPLAY '300-EVAL-CHAR-7 IS TRUE'
                      logger.info("300-EVAL-CHAR-7 IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalChar8300()  ) { 
//  DISPLAY '300-EVAL-CHAR-8 IS TRUE'
                      logger.info("300-EVAL-CHAR-8 IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalChar9300()  ) { 
//  DISPLAY '300-EVAL-CHAR-9 IS TRUE'
                      logger.info("300-EVAL-CHAR-9 IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharPeriod300()  ) { 
//  DISPLAY '300-EVAL-CHAR-PERIOD IS TRUE'
                      logger.info("300-EVAL-CHAR-PERIOD IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharComma300()  ) { 
//  DISPLAY '300-EVAL-CHAR-COMMA IS TRUE'
                      logger.info("300-EVAL-CHAR-COMMA IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharHyphen300()  ) { 
//  DISPLAY '300-EVAL-CHAR-HYPEN IS TRUE'
                      logger.info("300-EVAL-CHAR-HYPEN IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharSlashF300()  ) { 
//  DISPLAY '300-EVAL-CHAR-SLASH-F IS TRUE'
                      logger.info("300-EVAL-CHAR-SLASH-F IS TRUE"); 
                      ;
                  }
                  else if  ( work.isEvalCharSlashB300()  ) { 
//  DISPLAY '300-EVAL-CHAR-SLASH-B IS TRUE'
                      logger.info("300-EVAL-CHAR-SLASH-B IS TRUE"); 
                      ;
                  }
              }
//  ELSE
              else { 
//  DISPLAY '300-EVAL-CHAR IS FALSE FOR I VALUE: ' I ' AND W-300-EVAL-CHAR VALUE: ' W-300-EVAL-CHAR
                  logger.info("300-EVAL-CHAR IS FALSE FOR I VALUE: {} AND W-300-EVAL-CHAR VALUE: {}", String.valueOf(wI.getI()), new String(work.getW300EvalChar())); 
              }
          }
      
      }
      /**
      * end 
      *   This method is derived from 
  *   COBOL Paragraph - 9999-END COBOL Cyclomatic complexity - 2
      * Input  : None 

      * Output :  

      * - rc                             COBOL Name: RETURN-CODE
      *
      * @throws CFException
      */
      private void end() throws Exception {
      
// *
          // MOVE +0 TO RETURN-CODE
          this.setRc( 0);
//  DISPLAY ' '
          logger.info(" "); 
//  DISPLAY 'BEGIN CRAZY88'
          logger.info("BEGIN CRAZY88"); 
//  DISPLAY ' '
          logger.info(" "); 
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          this.setProgramEnded(true);
          return ;
      
      }
  
  
      /**
* This method pre-initializes variables consistent with
* what a mainframe program would have done at the start of a program
*/
      @Override
      public void initVars() throws CFException {
      setProgramEnded(false);
          if(!isInitDone()) {
          	this.setRc(0);
          	setInitDone(true);
          }
        CFUtil.resetDecimalAsComma();
       }
  
  
  
  
  
  
  }
