package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.utility.CFUtil;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] SPACE_100 = CFUtil.fillSpaces(100);
public static final char[] LITERAL_A = "A".toCharArray();
public static final char[] LITERAL_AB = "AB".toCharArray();
public static final char[] LITERAL_CR = "CR".toCharArray();
public static final char[] LITERAL_DR = "DR".toCharArray();
public static final char[] LITERAL_I = "I".toCharArray();
 
}
