#STEP:STEP003| PGM:IEBGENER| DD:SYSUT1
STEP003.IEBGENER.Sysut1[1]=CLOUDFRM.IEBGENER.DATA2
STEP003.IEBGENER.Sysut1[1].DISP=SHR,KEEP,KEEP
STEP003.IEBGENER.Sysut1[2]=CLOUDFRM.IEBGENER.DATA3
STEP003.IEBGENER.Sysut1[2].DISP=SHR,KEEP,KEEP
STEP003.IEBGENER.Sysut1[3]=CLOUDFRM.IEBGENER.DATA4
STEP003.IEBGENER.Sysut1[3].DISP=SHR,KEEP,KEEP
STEP003.IEBGENER.Sysut1[4]=CLOUDFRM.IEBGENER.DATA5
STEP003.IEBGENER.Sysut1[4].DISP=SHR,KEEP,KEEP
STEP003.IEBGENER.Sysut1.RecordType=FB
STEP003.IEBGENER.Sysut1.RecordLen=<recordLen>
#
#STEP:STEP003| PGM:IEBGENER| DD:SYSUT2
STEP003.IEBGENER.Sysut2=CLOUDFRM.IEBGENER.DATA.OUT(+1)
STEP003.IEBGENER.Sysut2.DISP=NEW,CATLG,DELETE
STEP003.IEBGENER.Sysut2.RecordType=FB
STEP003.IEBGENER.Sysut2.RecordLen=80
#
