<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Bdms01BondBasicExpData" cobol:name="BDMS01-BOND-BASIC-EXP-DATA" cobol:offset="3873" cobol:length="157" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Bdms01ScrtyAdpBaseNbr" maxOccurs="1"  cobol:name="BDMS01-SCRTY-ADP-BASE-NBR" cobol:offset="0" cobol:length="7" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01PuttableInd" maxOccurs="1"  cobol:name="BDMS01-PUTTABLE-IND" cobol:offset="7" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01AbsInd" maxOccurs="1"  cobol:name="BDMS01-ABS-IND" cobol:offset="8" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01TypeAbsCd" maxOccurs="1"  cobol:name="BDMS01-TYPE-ABS-CD" cobol:offset="9" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01CbndPassThruInd" maxOccurs="1"  cobol:name="BDMS01-CBND-PASS-THRU-IND" cobol:offset="11" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01UseOfPrcdCd" maxOccurs="1"  cobol:name="BDMS01-USE-OF-PRCD-CD" cobol:offset="12" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01OtrEnhcmtCmpyNm" maxOccurs="1"  cobol:name="BDMS01-OTR-ENHCMT-CMPY-NM" cobol:offset="14" cobol:length="50" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="50" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01OtrEnhcmtTypeCd" maxOccurs="1"  cobol:name="BDMS01-OTR-ENHCMT-TYPE-CD" cobol:offset="64" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01SttlmDt" maxOccurs="1"  cobol:name="BDMS01-STTLM-DT" cobol:offset="66" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01SttlmInd" maxOccurs="1"  cobol:name="BDMS01-STTLM-IND" cobol:offset="76" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01OtrTaxExmptCd" maxOccurs="1"  cobol:name="BDMS01-OTR-TAX-EXMPT-CD" cobol:offset="77" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01RmktTermInd" maxOccurs="1"  cobol:name="BDMS01-RMKT-TERM-IND" cobol:offset="78" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01FrgnSvrgnDbInd" maxOccurs="1"  cobol:name="BDMS01-FRGN-SVRGN-DB-IND" cobol:offset="79" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01ClMkWhlInd" maxOccurs="1"  cobol:name="BDMS01-CL-MK-WHL-IND" cobol:offset="80" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01InsCd" maxOccurs="1"  cobol:name="BDMS01-INS-CD" cobol:offset="81" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01InsFtidCd" maxOccurs="1"  cobol:name="BDMS01-INS-FTID-CD" cobol:offset="86" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01RrbInd" maxOccurs="1"  cobol:name="BDMS01-RRB-IND" cobol:offset="88" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01IssSttsCd" maxOccurs="1"  cobol:name="BDMS01-ISS-STTS-CD" cobol:offset="89" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01EomRuleCd" maxOccurs="1"  cobol:name="BDMS01-EOM-RULE-CD" cobol:offset="90" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01CouponTypeCd" maxOccurs="1"  cobol:name="BDMS01-COUPON-TYPE-CD" cobol:offset="91" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01OffrDocDlvryCd" maxOccurs="1"  cobol:name="BDMS01-OFFR-DOC-DLVRY-CD" cobol:offset="92" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01SidMudNbr" maxOccurs="1"  cobol:name="BDMS01-SID-MUD-NBR" cobol:offset="93" cobol:length="7" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="7" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01MuniSrsDescTxt" maxOccurs="1"  cobol:name="BDMS01-MUNI-SRS-DESC-TXT" cobol:offset="100" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01SupissTypeCd" maxOccurs="1"  cobol:name="BDMS01-SUPISS-TYPE-CD" cobol:offset="120" cobol:length="5" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="5" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01CallParametersFiller31" maxOccurs="1"  cobol:name="FILLER" cobol:offset="125" cobol:length="32" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="32" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
