<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Bdms01OsiSymbolCont" cobol:name="BDMS01-OSI-SYMBOL-CONT" cobol:offset="74" cobol:length="15" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Bdms01SearchOptSymbolType" maxOccurs="1"  cobol:name="BDMS01-SEARCH-OPT-SYMBOL-TYPE" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="true">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 bdms01SearchOptUndrSymbol VALUE [["U"]].
                        88 bdms01SearchOptRootSymbol VALUE [[" "]].
                        88 bdms01SearchOptBothSymbol VALUE [["B"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
    <xs:element name="Bdms01SearchOptSymbol" maxOccurs="1"  cobol:name="BDMS01-SEARCH-OPT-SYMBOL" cobol:offset="1" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01SearchOptStrike" maxOccurs="1"  cobol:name="BDMS01-SEARCH-OPT-STRIKE" cobol:offset="7" cobol:length="8" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="8" />
                  <xs:fractionDigits value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01SearchOptStrikex" maxOccurs="1"  cobol:name="BDMS01-SEARCH-OPT-STRIKEX" cobol:offset="7" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
