<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Bdms01ReturnData" cobol:name="BDMS01-RETURN-DATA" cobol:offset="100" cobol:length="6900" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Bdms01ReturnCode" maxOccurs="1"  cobol:name="BDMS01-RETURN-CODE" cobol:offset="0" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Bdms01ReturnSqlcode" type="xs:int" maxOccurs="1"  cobol:name="BDMS01-RETURN-SQLCODE" cobol:offset="2" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
<xs:element name="MsdRecordKey" maxOccurs="1" cobol:name="MSD-RECORD-KEY" cobol:offset="6" cobol:length="8" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Bdms01RegCode" maxOccurs="1"  cobol:name="BDMS01-REG-CODE" cobol:offset="14" cobol:length="2" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="Bdms01AdpMasterSegData" maxOccurs="1" cobol:name="BDMS01-ADP-MASTER-SEG-DATA" cobol:offset="16" cobol:length="206" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01BaseSecuritySegData" maxOccurs="1" cobol:name="BDMS01-BASE-SECURITY-SEG-DATA" cobol:offset="222" cobol:length="135" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01SecurityTypeSegData" maxOccurs="1" cobol:name="BDMS01-SECURITY-TYPE-SEG-DATA" cobol:offset="357" cobol:length="43" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01PriceSegData" maxOccurs="1" cobol:name="BDMS01-PRICE-SEG-DATA" cobol:offset="400" cobol:length="162" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01XrefSegData" maxOccurs="1" cobol:name="BDMS01-XREF-SEG-DATA" cobol:offset="562" cobol:length="320" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01DescSegData" maxOccurs="1" cobol:name="BDMS01-DESC-SEG-DATA" cobol:offset="882" cobol:length="299" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01SpecialistSegData" maxOccurs="1" cobol:name="BDMS01-SPECIALIST-SEG-DATA" cobol:offset="1181" cobol:length="58" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01FrozenChillSegData" maxOccurs="1" cobol:name="BDMS01-FROZEN-CHILL-SEG-DATA" cobol:offset="1239" cobol:length="162" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01IncomeSegData" maxOccurs="1" cobol:name="BDMS01-INCOME-SEG-DATA" cobol:offset="1401" cobol:length="439" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01RatingSegData" maxOccurs="1" cobol:name="BDMS01-RATING-SEG-DATA" cobol:offset="1840" cobol:length="47" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01ConvertibleSegData" maxOccurs="1" cobol:name="BDMS01-CONVERTIBLE-SEG-DATA" cobol:offset="1887" cobol:length="69" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01StockSegData" maxOccurs="1" cobol:name="BDMS01-STOCK-SEG-DATA" cobol:offset="1956" cobol:length="293" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01OptionSegData" maxOccurs="1" cobol:name="BDMS01-OPTION-SEG-DATA" cobol:offset="2249" cobol:length="189" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01BondBasicSegData" maxOccurs="1" cobol:name="BDMS01-BOND-BASIC-SEG-DATA" cobol:offset="2438" cobol:length="249" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01BondFeatureSegData" maxOccurs="1" cobol:name="BDMS01-BOND-FEATURE-SEG-DATA" cobol:offset="2687" cobol:length="394" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01BondFactorSegData" maxOccurs="1" cobol:name="BDMS01-BOND-FACTOR-SEG-DATA" cobol:offset="3081" cobol:length="164" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01BondCmoSegData" maxOccurs="1" cobol:name="BDMS01-BOND-CMO-SEG-DATA" cobol:offset="3245" cobol:length="84" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01OidSegData" maxOccurs="1" cobol:name="BDMS01-OID-SEG-DATA" cobol:offset="3329" cobol:length="88" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01UitSegData" maxOccurs="1" cobol:name="BDMS01-UIT-SEG-DATA" cobol:offset="3417" cobol:length="43" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01MortBackedSegData" maxOccurs="1" cobol:name="BDMS01-MORT-BACKED-SEG-DATA" cobol:offset="3460" cobol:length="89" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01GetpriceSegData" maxOccurs="1" cobol:name="BDMS01-GETPRICE-SEG-DATA" cobol:offset="3549" cobol:length="119" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01MultSecurityNoData" maxOccurs="1" cobol:name="BDMS01-MULT-SECURITY-NO-DATA" cobol:offset="3668" cobol:length="37" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01DivQualifyData" maxOccurs="1" cobol:name="BDMS01-DIV-QUALIFY-DATA" cobol:offset="3705" cobol:length="2" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01TaxSegData" maxOccurs="1" cobol:name="BDMS01-TAX-SEG-DATA" cobol:offset="3707" cobol:length="66" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01BondBasicExpData" maxOccurs="1" cobol:name="BDMS01-BOND-BASIC-EXP-DATA" cobol:offset="3773" cobol:length="157" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01BaseSecurityExpData" maxOccurs="1" cobol:name="BDMS01-BASE-SECURITY-EXP-DATA" cobol:offset="3930" cobol:length="216" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01MultAdpNoData" maxOccurs="1" cobol:name="BDMS01-MULT-ADP-NO-DATA" cobol:offset="4146" cobol:length="182" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01UnitsSegData" maxOccurs="1" cobol:name="BDMS01-UNITS-SEG-DATA" cobol:offset="4328" cobol:length="57" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01TcontrolSegData" maxOccurs="1" cobol:name="BDMS01-TCONTROL-SEG-DATA" cobol:offset="4385" cobol:length="145" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01SecurityPrivSegData" maxOccurs="1" cobol:name="BDMS01-SECURITY-PRIV-SEG-DATA" cobol:offset="4530" cobol:length="1" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01AdpMasterExpData" maxOccurs="1" cobol:name="BDMS01-ADP-MASTER-EXP-DATA" cobol:offset="4531" cobol:length="213" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01CvrsnSegData" maxOccurs="1" cobol:name="BDMS01-CVRSN-SEG-DATA" cobol:offset="4744" cobol:length="389" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01CanadaBondSegData" maxOccurs="1" cobol:name="BDMS01-CANADA-BOND-SEG-DATA" cobol:offset="5133" cobol:length="44" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Bdms01OptUnderlXrefData" maxOccurs="1" cobol:name="BDMS01-OPT-UNDERL-XREF-DATA" cobol:offset="5177" cobol:length="128" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Bdms01CallParametersFiller36" maxOccurs="1"  cobol:name="FILLER" cobol:offset="5305" cobol:length="1595" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1595" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
