package com.cloudframe.app.ip088030.file;
/* Java Code Generated by CloudFrame */

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;
import com.cloudframe.app.utility.CFFile;
import org.springframework.beans.factory.annotation.Value;
import com.cloudframe.app.utility.CFConstants;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import com.cloudframe.app.ip088030.file.records.*;

@Component("ip088030_sys002CntlIchgFile")
public class Sys002CntlIchgFile extends CFFile {

	private Logger logger = LoggerFactory.getLogger(Sys002CntlIchgFile.class);
	
	@Value("${IP088030.Sys002CntlIchgFile:SYS002}")
	private String fileName;

	/**
	 * This function is not required in this subclass for your program to work as intended. 
	 * CloudFrame generated this function to provide you hints for the code you must write 
	 * to change the implementation and remove runtime and license dependency on CloudFrame. 
	 * Consult CloudFrame's customer wiki for additional information. https://ask.cloudframe.com
	 **/
	@Override
	public String getFileName() {
		return fileName;
	}
	
	/**
	 * This function is not required in this subclass for your program to work as intended. 
	 * CloudFrame generated this function to provide you hints for the code you must write 
	 * to change the implementation and remove runtime and license dependency on CloudFrame. 
	 * Consult CloudFrame's customer wiki for additional information. https://ask.cloudframe.com
	 **/	
	@Override
	public  void setFileName(String fileName) {
		this.fileName = fileName;
	}	

   /**
    *  Default value for CharSet is cp1047 defined in application.properties
    *  For files that has mixed UTF-8 as well as binary characters keep this value as cp1047
    **/
	@Value("${IP088030.Sys002CntlIchgFileCharSet:cp1047}")
	private String charSet;
	
	@Value("${IP088030.Sys002CntlIchgFileCRLFflag:no}")
	private String crlfFlag;

	public String getSys002CntlIchgFileCharSet() {
		return charSet;
	}
	
	public String getSys002CntlIchgFileCrlfFlag() {
		return crlfFlag;
	}

	public Sys002CntlIchgFile()
	{
		setFixedBlockFile(true);	
		setRecord(new byte[85]);
		setOptionalFile(false);
	}
	
	public char[] getStatusString() {
		if (status == 0) return new char[]{'0','0'};
		else if (status == 10) return new char[]{'1','0'};
		return String.format("%1$2s", status+"").replace(' ', '0').toCharArray();
	}

	@Override
	public void read() throws Exception {
		try {
			super.readRecord();
		} catch (Exception e) {
			ended = true;
			status = CFConstants.END_OF_FILE; 
			logger.error("Error during Sys002CntlIchgFile Read: {}",e.getMessage() ); 
		    throw e;
		}
	}
  
	
}
