<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="FixedHeader801" cobol:name="801-FIXED-HEADER" cobol:offset="0" cobol:length="8232" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="Sys001MiplogClass801" maxOccurs="1"  cobol:name="801-SYS001-MIPLOG-CLASS" cobol:offset="15" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sys001MiplogTyp801" maxOccurs="1"  cobol:name="801-SYS001-MIPLOG-TYP" cobol:offset="16" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sys001MiplogRefNum801" maxOccurs="1"  cobol:name="801-SYS001-MIPLOG-REF-NUM" cobol:offset="17" cobol:length="6" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="6" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Sys001MiplogBoxId801" maxOccurs="1"  cobol:name="801-SYS001-MIPLOG-BOX-ID" cobol:offset="23" cobol:length="3" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="3" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="Sys001MiplogTime801" maxOccurs="1" cobol:name="801-SYS001-MIPLOG-TIME" cobol:offset="26" cobol:length="3" cobol:datatype="Group" cobol:serialize="true" />
<xs:element name="Sys001MiplogDate801" maxOccurs="1" cobol:name="801-SYS001-MIPLOG-DATE" cobol:offset="29" cobol:length="3" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="Sys001MiplogElaTimX801" maxOccurs="1"  cobol:name="801-SYS001-MIPLOG-ELA-TIM-X" cobol:offset="32" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
