<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Work" cobol:name="work" cobol:offset="0" cobol:length="53" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="MipLogEofSw100" maxOccurs="1"  cobol:name="100-MIP-LOG-EOF-SW" cobol:offset="0" cobol:length="1" cobol:datatype="Display" cobol:signed="false" cobol:signLeading="false"  cobol:signSeparate="false" cobol:max="MAX_10" cobol:serialize="false">
        <xs:annotation>
            <xs:documentation>
                <![CDATA[
                        88 mipLogEof88100 VALUE [["Y"]].
                ]]>
            </xs:documentation> 
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                  <xs:length value="1" />     
            </xs:restriction>
        </xs:simpleType>
    </xs:element>  
         <xs:element name="Halfword8300" type="xs:short" maxOccurs="1"  cobol:name="300-HALFWORD-8" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Halfword13300" type="xs:short" maxOccurs="1"  cobol:name="300-HALFWORD-13" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="One300" type="xs:short" maxOccurs="1"  cobol:name="300-ONE" cobol:offset="0" cobol:length="1" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10"/>
         <xs:element name="Twenty300" type="xs:short" maxOccurs="1"  cobol:name="300-TWENTY" cobol:offset="1" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="Sf305120300" maxOccurs="1"  cobol:name="300-SF305120" cobol:offset="3" cobol:length="8" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="ZLog300" maxOccurs="1"  cobol:name="300-Z-LOG" cobol:offset="3" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CharC300" maxOccurs="1"  cobol:name="300-CHAR-C" cobol:offset="3" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CharE300" maxOccurs="1"  cobol:name="300-CHAR-E" cobol:offset="3" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CharA300" maxOccurs="1"  cobol:name="300-CHAR-A" cobol:offset="3" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CharB300" maxOccurs="1"  cobol:name="300-CHAR-B" cobol:offset="3" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CharN300" maxOccurs="1"  cobol:name="300-CHAR-N" cobol:offset="3" cobol:length="1" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="Sys001Lrecl400" type="xs:long" maxOccurs="1"  cobol:name="400-SYS001-LRECL" cobol:offset="3" cobol:length="4" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Sub400" type="xs:short" maxOccurs="1"  cobol:name="400-SUB" cobol:offset="3" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="false" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="Assert1400" type="xs:int" maxOccurs="1"  cobol:name="400-ASSERT-1" cobol:offset="3" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="MipLogCnt400" type="xs:int" maxOccurs="1"  cobol:name="400-MIP-LOG-CNT" cobol:offset="12" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="ZLogCnt400" type="xs:int" maxOccurs="1"  cobol:name="400-Z-LOG-CNT" cobol:offset="21" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
         <xs:element name="ZLogBypass400" type="xs:int" maxOccurs="1"  cobol:name="400-Z-LOG-BYPASS" cobol:offset="30" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
    <xs:element name="ExecStartMsg600" maxOccurs="1"  cobol:name="600-EXEC-START-MSG" cobol:offset="39" cobol:length="64" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="64" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CurrDateYyyy600" maxOccurs="1"  cobol:name="600-CURR-DATE-YYYY" cobol:offset="39" cobol:length="4" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CurrDateMm600" maxOccurs="1"  cobol:name="600-CURR-DATE-MM" cobol:offset="39" cobol:length="2" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CurrDateDd600" maxOccurs="1"  cobol:name="600-CURR-DATE-DD" cobol:offset="39" cobol:length="2" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CurrTimeHh600" maxOccurs="1"  cobol:name="600-CURR-TIME-HH" cobol:offset="39" cobol:length="2" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CurrTimeMm600" maxOccurs="1"  cobol:name="600-CURR-TIME-MM" cobol:offset="39" cobol:length="2" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="CurrTimeSs600" maxOccurs="1"  cobol:name="600-CURR-TIME-SS" cobol:offset="39" cobol:length="2" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Message6008000" maxOccurs="1"  cobol:name="600-8000-MESSAGE" cobol:offset="39" cobol:length="62" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="62" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Message6008999" maxOccurs="1"  cobol:name="600-8999-MESSAGE" cobol:offset="39" cobol:length="62" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="62" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="EojMessage6009400" maxOccurs="1"  cobol:name="600-9400-EOJ-MESSAGE" cobol:offset="39" cobol:length="44" cobol:datatype="Display" cobol:serialize="false" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="44" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="TranlogTimeHh800" type="xs:int" maxOccurs="1"  cobol:name="800-TRANLOG-TIME-HH" cobol:offset="39" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="TranlogTimeMm800" type="xs:int" maxOccurs="1"  cobol:name="800-TRANLOG-TIME-MM" cobol:offset="41" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="TranlogTimeSs800" type="xs:int" maxOccurs="1"  cobol:name="800-TRANLOG-TIME-SS" cobol:offset="43" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="TranlogDateMm800" type="xs:int" maxOccurs="1"  cobol:name="800-TRANLOG-DATE-MM" cobol:offset="45" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="TranlogDateDd800" type="xs:int" maxOccurs="1"  cobol:name="800-TRANLOG-DATE-DD" cobol:offset="47" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="TranlogDateYy800" type="xs:int" maxOccurs="1"  cobol:name="800-TRANLOG-DATE-YY" cobol:offset="49" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
         <xs:element name="TranlogDateCc800" type="xs:int" maxOccurs="1"  cobol:name="800-TRANLOG-DATE-CC" cobol:offset="51" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
