SQLSTEP.DSNTEP2.Systsprt=SQLSTEP.DSNTEP2.SYSTSPRT.SYSOUT
SQLSTEP.DSNTEP2.Sysprint=SQLSTEP.DSNTEP2.SYSPRINT.SYSOUT
#start sqlutil report/raw format properties
unload.sqlutil.format=REPORT
#end sqlutil report/raw format properties

#database specific properties
spring.database.enabled=true
spring.datasource.jdbc-url=jdbc:db2://sysh.cloudframe.com:5040/DALLASC:currentSchema=CLOUDFRM;
spring.datasource.driverClassName=com.ibm.db2.jcc.DB2Driver
spring.datasource.username=QAUSER
spring.datasource.password=CLOUD04
spring.datasource.initialization-mode=embedded
spring.jpa.hibernate.ddl-auto=update
spring.jdbc.template.fetch-size=5000
#end of database properties
