#STEP:STEP020| PGM:SORT| DD:SORTJNF1
Sort037Step020SortIn[0]=CLOUDFRM.MC.GCMS.SORT.IN0371
Sort037Step020SortIn[0].DISP=SHR,KEEP,KEEP
Sort037Step020SortIn0RecordType=FB
Sort037Step020SortIn0RecordLen=58
#STEP:STEP020| PGM:SORT| DD:SORTJNF2
Sort037Step020SortIn[1]=CLOUDFRM.MC.GCMS.SORT.IN0372
Sort037Step020SortIn[1].DISP=SHR,KEEP,KEEP
Sort037Step020SortIn1RecordType=FB
Sort037Step020SortIn1RecordLen=58
#STEP:STEP020| PGM:SORT| DD:SORTJNF2
Sort037Step020SortIn[2]=CLOUDFRM.MC.GCMS.SORT.IN0373
Sort037Step020SortIn[2].DISP=SHR,KEEP,KEEP
Sort037Step020SortIn2RecordType=FB
Sort037Step020SortIn2RecordLen=58
#STEP:STEP020| PGM:SORT| DD:SORTJNF2
Sort037Step020SortIn[3]=CLOUDFRM.MC.GCMS.SORT.IN0374
Sort037Step020SortIn[3].DISP=SHR,KEEP,KEEP
Sort037Step020SortIn3RecordType=FB
Sort037Step020SortIn3RecordLen=58
#STEP:STEP020| PGM:SORT| DD:SORTJNF2
Sort037Step020SortIn[4]=CLOUDFRM.MC.GCMS.SORT.IN0375
Sort037Step020SortIn[4].DISP=SHR,KEEP,KEEP
Sort037Step020SortIn4RecordType=FB
Sort037Step020SortIn4RecordLen=58
#STEP:STEP020| PGM:SORT| DD:UNMATCH
Sort037Step020SortOut[0]=CLOUDFRM.MC.GCMS.SORT.OUT0371
Sort037Step020SortOut[0].DISP=NEW,KEEP,KEEP
Sort037Step020SortOut0RecordType=FB
Sort037Step020SortOut0RecordLen=50
#STEP:STEP020| PGM:SORT| DD:MATCH
Sort037Step020SortOut[1]=CLOUDFRM.MC.GCMS.SORT.OUT0372
Sort037Step020SortOut[1].DISP=NEW,KEEP,KEEP
Sort037Step020SortOut1RecordType=FB
Sort037Step020SortOut1RecordLen=50
