<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Bdms01OidSegData" cobol:name="BDMS01-OID-SEG-DATA" cobol:offset="3429" cobol:length="88" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Bdms01OidSegSqlcd" type="xs:int" maxOccurs="1"  cobol:name="BDMS01-OID-SEG-SQLCD" cobol:offset="0" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
<xs:element name="MsdOidDateCcyymmdd" maxOccurs="1" cobol:name="MSD-OID-DATE-CCYYMMDD" cobol:offset="4" cobol:length="8" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="MsdOidIssuePrc" maxOccurs="1"  cobol:name="MSD-OID-ISSUE-PRC" cobol:offset="12" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="18" />
                  <xs:fractionDigits value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MsdOidAccrtdValue" maxOccurs="1"  cobol:name="MSD-OID-ACCRTD-VALUE" cobol:offset="30" cobol:length="18" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1E">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="18" />
                  <xs:fractionDigits value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01OidDt" maxOccurs="1"  cobol:name="BDMS01-OID-DT" cobol:offset="48" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01CallParametersFiller26" maxOccurs="1"  cobol:name="FILLER" cobol:offset="58" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
