<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Bdms01SpecialistSegData" cobol:name="BDMS01-SPECIALIST-SEG-DATA" cobol:offset="1281" cobol:length="58" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="Bdms01SpecialistSegSqlcd" type="xs:int" maxOccurs="1"  cobol:name="BDMS01-SPECIALIST-SEG-SQLCD" cobol:offset="0" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
         <xs:element name="MsdSpecAcctBbbaaaaat" type="xs:long" maxOccurs="1"  cobol:name="MSD-SPEC-ACCT-BBBAAAAAT" cobol:offset="4" cobol:length="9" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_1G"/>
<xs:element name="MsdSpecialistAcctNo" maxOccurs="1" cobol:name="MSD-SPECIALIST-ACCT-NO" cobol:offset="4" cobol:length="9" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="MsdSpecAcctCkdg" maxOccurs="1"  cobol:name="MSD-SPEC-ACCT-CKDG" cobol:offset="13" cobol:length="1" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01SpecExchangeCd" maxOccurs="1"  cobol:name="BDMS01-SPEC-EXCHANGE-CD" cobol:offset="14" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01SpecClientNbr" maxOccurs="1"  cobol:name="BDMS01-SPEC-CLIENT-NBR" cobol:offset="24" cobol:length="4" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="Bdms01CallParametersFiller11" maxOccurs="1"  cobol:name="FILLER" cobol:offset="28" cobol:length="30" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
