# Program TMSMMCPY | DD : TMSMMIN | RecordFormat : VariableLength | MaxRecordLength : 3996
TMSMMCPY.ddname.TMSMMIN=SmmFileIn
TMSMMCPY.SmmFileIn=SmmFileIn
TMSMMCPY.SmmFileInCharSet=cp1047
TMSMMCPY.SmmFileInCRLFflag=no
# Program TMSMMCPY | DD : TMSMMOUT | RecordFormat : FixedLength | RecordLength : 822
TMSMMCPY.ddname.TMSMMOUT=SmmFileOut
TMSMMCPY.SmmFileOut=SmmFileOut
TMSMMCPY.SmmFileOutCharSet=cp1047
TMSMMCPY.SmmFileOutCRLFflag=no
# 
# End of TMSMMCPY
