#STEP:DATE1IN| PGM:SORT| DD:SORTIN
UsbrecdatDate1inSortIn=CLOUDFRM.DATE.INPUT
UsbrecdatDate1inSortIn.DISP=SHR,KEEP,KEEP
UsbrecdatDate1inSortInRecordType=FB
UsbrecdatDate1inSortInRecordLen=200
#STEP:DATE1IN| PGM:SORT| DD:SORTOUT
UsbrecdatDate1inSortOut=CLOUDFRM.DATE.OUT5
UsbrecdatDate1inSortOut.DISP=NEW,KEEP,KEEP
UsbrecdatDate1inSortOutRecordType=FB
UsbrecdatDate1inSortOutRecordLen=200
#STEP:DATE1OUT| PGM:SORT| DD:SORTIN
UsbrecdatDate1outSortIn=CLOUDFRM.DATE.INPUT
UsbrecdatDate1outSortIn.DISP=SHR,KEEP,KEEP
UsbrecdatDate1outSortInRecordType=FB
UsbrecdatDate1outSortInRecordLen=200
#STEP:DATE1OUT| PGM:SORT| DD:SORTOUT
UsbrecdatDate1outSortOut=CLOUDFRM.DATE.OUT2
UsbrecdatDate1outSortOut.DISP=NEW,KEEP,KEEP
UsbrecdatDate1outSortOutRecordType=FB
UsbrecdatDate1outSortOutRecordLen=200
