# Program  : DB2FUNCI | DD : SYSIN | RecordFormat : FixedLength | RecordLength : 80
DB2FUNCI.Scanner=SYSIN.bin
DB2FUNCI.ScannerCharSet=cp1047
DB2FUNCI.ScannerCRLFflag=no
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
DB2FUNCI.dbQualifier=
# 
# End of DB2FUNCI
