# Program CFSORT01 | DD : FILEIN | RecordFormat : FixedLength | RecordLength : 30
CFSORT01.ddname.FILEIN=FileIn
CFSORT01.FileIn=FileIn
CFSORT01.FileInCharSet=cp1047
CFSORT01.FileInCRLFflag=no
# Program CFSORT01 | DD : FILEOUT | RecordFormat : FixedLength | RecordLength : 30
CFSORT01.ddname.FILEOUT=FileOut
CFSORT01.FileOut=FileOut
CFSORT01.FileOutCharSet=cp1047
CFSORT01.FileOutCRLFflag=no
# 
# End of CFSORT01
