#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
# spring.main.lazy-initialization=true
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=X
timeZoneId=Etc/GMT
SF311010.ddname.SYS001=SYS001
SF311010.CentralSiteBdlogs=SYS001
SF311010.CentralSiteBdlogsCharSet=cp1047
SF311010.CentralSiteBdlogsCRLFflag=no
SF311010.ddname.SYS202=IssAcqVer2FileOut
SF311010.IssAcqVer2FileOut=IssAcqVer2FileOut
SF311010.IssAcqVer2FileOutCharSet=cp1047
SF311010.IssAcqVer2FileOutCRLFflag=no
SF311010.ddname.SYS201=LogStatisticsReport
SF311010.LogStatisticsReport=LogStatisticsReport
SF311010.LogStatisticsReportCharSet=cp1047
SF311010.LogStatisticsReportCRLFflag=no
#logging.level.com.cloudframe=DEBUG
# logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
# 
# End of SF311010
inputValue1=X
# End of MCWIN
# End of MCABEND
# End of SF910020
# End of SI994010
# End of SI994020
