#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
timeZoneId=Etc/GMT
# Program SF311010 | DD : SYS001 | RecordFormat : VariableLength | MaxRecordLength : 8000
SF311010.ddname.SYS001=CentralSiteBdlogs
SF311010.CentralSiteBdlogs=CentralSiteBdlogs
SF311010.CentralSiteBdlogsCharSet=cp1047
SF311010.CentralSiteBdlogsCRLFflag=no
# Program SF311010 | DD : SYS202 | RecordFormat : FixedLength | RecordLength : 900
SF311010.ddname.SYS202=IssAcqVer2FileOut
SF311010.IssAcqVer2FileOut=IssAcqVer2FileOut
SF311010.IssAcqVer2FileOutCharSet=cp1047
SF311010.IssAcqVer2FileOutCRLFflag=no
# Program SF311010 | DD : SYS201 | RecordFormat : FixedLength | RecordLength : 145
SF311010.ddname.SYS201=LogStatisticsReport
SF311010.LogStatisticsReport=LogStatisticsReport
SF311010.LogStatisticsReportCharSet=cp1047
SF311010.LogStatisticsReportCRLFflag=no
# 
# End of SF311010
inputValue1=
inputValue2=
# End of MCWIN
# End of SF910020
# End of SI994010
