#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
# Program IP343900 | DD : SYS067 | RecordFormat : FixedLength | RecordLength : 80
IP343900.ddname.SYS067=Sys067EnvrmentFile
IP343900.Sys067EnvrmentFile=Sys067EnvrmentFile
IP343900.Sys067EnvrmentFileCharSet=cp1047
IP343900.Sys067EnvrmentFileCRLFflag=no
# Program IP343900 | DD : SYS001 | RecordFormat : FixedLength | RecordLength : 94
IP343900.ddname.SYS001=Sys001PmmFixUnloadFile
IP343900.Sys001PmmFixUnloadFile=Sys001PmmFixUnloadFile
IP343900.Sys001PmmFixUnloadFileCharSet=cp1047
IP343900.Sys001PmmFixUnloadFileCRLFflag=no
# 
# End of IP343900
# Program IP798030 | DD : SYS001 | RecordFormat : FixedLength | RecordLength : 182
IP798030.ddname.SYS001=Sys001CutoffFile
IP798030.Sys001CutoffFile=Sys001CutoffFile
IP798030.Sys001CutoffFileCharSet=cp1047
IP798030.Sys001CutoffFileCRLFflag=no
# Program IP798030 | DD : SYS202 | RecordFormat : FixedLength | RecordLength : 94
IP798030.ddname.SYS202=Sys202PmaFile
IP798030.Sys202PmaFile=Sys202PmaFile
IP798030.Sys202PmaFileCharSet=cp1047
IP798030.Sys202PmaFileCRLFflag=no
# Program IP798030 | DD : SYS210 | RecordFormat : FixedLength | RecordLength : 500
IP798030.ddname.SYS210=Sys210MqDataFile
IP798030.Sys210MqDataFile=Sys210MqDataFile
IP798030.Sys210MqDataFileCharSet=cp1047
IP798030.Sys210MqDataFileCRLFflag=no
# End of IP798030
# Program IP809050 | DD : SYS012 | RecordFormat : FixedLength | RecordLength : 80
IP809050.ddname.SYS012=Sys012RunControlFile
IP809050.Sys012RunControlFile=Sys012RunControlFile
IP809050.Sys012RunControlFileCharSet=cp1047
IP809050.Sys012RunControlFileCRLFflag=no
# Program IP809050 | DD : SYS001 | RecordFormat : VariableLength | MaxRecordLength : 32756
IP809050.ddname.SYS001=Sys001InputIpmOutboundFile
IP809050.Sys001InputIpmOutboundFile=Sys001InputIpmOutboundFile
IP809050.Sys001InputIpmOutboundFileCharSet=cp1047
IP809050.Sys001InputIpmOutboundFileCRLFflag=no
# Program IP809050 | DD : SYS201 | RecordFormat : FixedLength | RecordLength : 600
IP809050.ddname.SYS201=Sys201OutputIpmOtbndFile
IP809050.Sys201OutputIpmOtbndFile=Sys201OutputIpmOtbndFile
IP809050.Sys201OutputIpmOtbndFileCharSet=cp1047
IP809050.Sys201OutputIpmOtbndFileCRLFflag=no
# Program IP809050 | DD : SYS202 | RecordFormat : FixedLength | RecordLength : 600
IP809050.ddname.SYS202=Sys202OutputIpmOtbndFile
IP809050.Sys202OutputIpmOtbndFile=Sys202OutputIpmOtbndFile
IP809050.Sys202OutputIpmOtbndFileCharSet=cp1047
IP809050.Sys202OutputIpmOtbndFileCRLFflag=no
# Program IP809050 | DD : SYS203 | RecordFormat : FixedLength | RecordLength : 600
IP809050.ddname.SYS203=Sys203OutputIpmOtbndFile
IP809050.Sys203OutputIpmOtbndFile=Sys203OutputIpmOtbndFile
IP809050.Sys203OutputIpmOtbndFileCharSet=cp1047
IP809050.Sys203OutputIpmOtbndFileCRLFflag=no
# Program IP809050 | DD : SYS204 | RecordFormat : FixedLength | RecordLength : 600
IP809050.ddname.SYS204=Sys204OutputIpmOtbndFile
IP809050.Sys204OutputIpmOtbndFile=Sys204OutputIpmOtbndFile
IP809050.Sys204OutputIpmOtbndFileCharSet=cp1047
IP809050.Sys204OutputIpmOtbndFileCRLFflag=no
# Program IP809050 | DD : SYS205 | RecordFormat : FixedLength | RecordLength : 600
IP809050.ddname.SYS205=Sys205OutputIpmOtbndFile
IP809050.Sys205OutputIpmOtbndFile=Sys205OutputIpmOtbndFile
IP809050.Sys205OutputIpmOtbndFileCharSet=cp1047
IP809050.Sys205OutputIpmOtbndFileCRLFflag=no
# Program IP809050 | DD : SYS206 | RecordFormat : FixedLength | RecordLength : 600
IP809050.ddname.SYS206=Sys206OutputIpmOtbndFile
IP809050.Sys206OutputIpmOtbndFile=Sys206OutputIpmOtbndFile
IP809050.Sys206OutputIpmOtbndFileCharSet=cp1047
IP809050.Sys206OutputIpmOtbndFileCRLFflag=no
# Program IP809050 | DD : SYS207 | RecordFormat : FixedLength | RecordLength : 600
IP809050.ddname.SYS207=Sys207OutputIpmOtbndFile
IP809050.Sys207OutputIpmOtbndFile=Sys207OutputIpmOtbndFile
IP809050.Sys207OutputIpmOtbndFileCharSet=cp1047
IP809050.Sys207OutputIpmOtbndFileCRLFflag=no
# End of IP809050
timeZoneId=Etc/GMT
# Program IP829010 | DD : SYS201 | RecordFormat : FixedLength | RecordLength : 280
IP829010.ddname.SYS201=Sys201FnsMqErrFile
IP829010.Sys201FnsMqErrFile=Sys201FnsMqErrFile
IP829010.Sys201FnsMqErrFileCharSet=cp1047
IP829010.Sys201FnsMqErrFileCRLFflag=no
# End of IP829010
