#STEP:STEP020| PGM:SORT| DD:SORTIN
Sort036Step020SortIn=CLOUDFRM.MC.GCMS.SORT.IN036
Sort036Step020SortIn.DISP=SHR,KEEP,KEEP
Sort036Step020SortInRecordType=FB
Sort036Step020SortInRecordLen=256
#STEP:STEP020| PGM:SORT| DD:SORTOUT
Sort036Step020SortOut=CLOUDFRM.MC.GCMS.SORT.OUT036
Sort036Step020SortOut.DISP=NEW,KEEP,KEEP
Sort036Step020SortOutRecordType=FB
Sort036Step020SortOutRecordLen=256
