#STEP:STEP0600| PGM:SORT| DD:SORTJNF1
Step600Step0600SortIn[0]=FILE1.DTLFILE.MOCK
Step600Step0600SortIn[0].DISP=SHR,KEEP,KEEP
Step600Step0600SortIn0RecordType=FB
Step600Step0600SortIn0RecordLen=300
#STEP:STEP0600| PGM:SORT| DD:SORTJNF2
Step600Step0600SortIn[1]=FILE2.SECFILE.MOCK
Step600Step0600SortIn[1].DISP=SHR,KEEP,KEEP
Step600Step0600SortIn1RecordType=FB
Step600Step0600SortIn1RecordLen=300
#STEP:STEP0600| PGM:SORT| DD:SORTOUT
Step600Step0600SortOut=FILE1.DTLFILE.MOCK.OUTPUT1
Step600Step0600SortOut.DISP=NEW,CATLG,DELETE
Step600Step0600SortOutRecordType=FB
Step600Step0600SortOutRecordLen=80
