
#
#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=03
CFCARD.ddname.INPDD=FlInputFile
CFCARD.FlInputFile=input.txt
CFCARD.FlInputFileCharSet=cp1047
CFCARD.FlInputFileCRLFflag=yes
CFCARD.ddname.OUTPDD=FlOutputFile
CFCARD.FlOutputFile=FlOutputFile
CFCARD.FlOutputFileCharSet=cp1047
CFCARD.FlOutputFileCRLFflag=yes
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
