STEP1_STEP10.RETCODE2.inputValue='00001'
STEP2_STEP10.RETCODE2.inputValue='00002'
STEP3_STEP10.RETCODE2.inputValue='00033'
STEP4.RETCODE2.inputValue='00004'
STEP5.RETCODE2.inputValue='00005'
STEP6.RETCODE2.inputValue='00006'
STEP7.RETCODE2.inputValue='00007'
#update the inputValue below, that has to be passed to the application, if running as a stand alone
# 
# End of RETCODE2
# End of RETCODE1
ABEND001.RETCODE.inputValue='00999'
ABEND002.RETCODE.inputValue='00999'
# End of RETCODE
