#STEP:SORT001| PGM:SORT| DD:SORTIN
IftestcSort001SortIn=CLOUDFRM.MC.SORT.IN001
IftestcSort001SortIn.DISP=SHR,KEEP,KEEP
IftestcSort001SortInRecordType=VB
IftestcSort001SortInRecordLen=32752
#STEP:SORT001| PGM:SORT| DD:SORTOUT
IftestcSort001SortOut=CLOUDFRM.MC.SORT.OUT001
IftestcSort001SortOut.DISP=SHR,KEEP,KEEP
IftestcSort001SortOutRecordType=FB
IftestcSort001SortOutRecordLen=32748
#STEP:SORT002| PGM:SORT| DD:SORTIN
IftestcSort002SortIn=CLOUDFRM.MC.SORT.IN002
IftestcSort002SortIn.DISP=SHR,KEEP,KEEP
IftestcSort002SortInRecordType=VB
IftestcSort002SortInRecordLen=30004
#STEP:SORT002| PGM:SORT| DD:SORTOUT
IftestcSort002SortOut=CLOUDFRM.MC.SORT.OUT002
IftestcSort002SortOut.DISP=SHR,KEEP,KEEP
IftestcSort002SortOutRecordType=FB
IftestcSort002SortOutRecordLen=30000
