#
#STEP:P030| PGM:ICETOOL| DD:FLE1
UsbiceP030SortIn=UDEV34.CLOUDFRM.USB.NCR.DSNAMES
UsbiceP030SortIn.DISP=SHR,KEEP,KEEP
UsbiceP030SortInRecordType=VBA
UsbiceP030SortInRecordLen=125
#
#
#STEP:P030| PGM:ICETOOL| DD:FLE2
UsbiceP030SortOut=UDEV34.CLOUDFRM.USB.NCR.NONVSAM
UsbiceP030SortOut.DISP=NEW,CATLG,KEEP
UsbiceP030SortOutRecordType=VBA
UsbiceP030SortOutRecordLen=125
#
#
#STEP:P0301| PGM:ICETOOL| DD:FLE1
UsbiceP0301SortIn=UDEV34.CLOUDFRM.USB.NCR.COPY
UsbiceP0301SortIn.DISP=SHR,KEEP,KEEP
UsbiceP0301SortInRecordType=FBA
UsbiceP0301SortInRecordLen=80
#
#
#STEP:P0301| PGM:ICETOOL| DD:FLE2
UsbiceP0301SortOut=UDEV34.CLOUDFRM.USB.NCR.COPYPARM
UsbiceP0301SortOut.DISP=NEW,CATLG,DELETE
UsbiceP0301SortOutRecordType=FBA
UsbiceP0301SortOutRecordLen=80
#
#
#STEP:P040| PGM:IDCAMS| DD:SYSIN
P040.IDCAMS.Sysin=UDEV34.CLOUDFRM.USB.NCR.COPYPARM
P040.IDCAMS.Sysin.DISP=SHR,KEEP,KEEP
P040.IDCAMS.Sysin.RecordType=FBA
P040.IDCAMS.Sysin.RecordLen=80
#
#STEP:P040| PGM:IDCAMS| DD:MODDD2
P040.IDCAMS.MODDD2=UDEV34.CLOUDFRM.MODD1
P040.IDCAMS.MODDD2.DISP=NEW,KEEP,KEEP
P040.IDCAMS.MODDD2.RecordType=VBA
P040.IDCAMS.MODDD2.RecordLen=125
#
#STEP:P050| PGM:IDCAMS| DD:SYSIN
P050.IDCAMS.Sysin=UDEV34.CLOUDFRM.USB.NCR.COPYPARM
P050.IDCAMS.Sysin.DISP=SHR,KEEP,KEEP
P050.IDCAMS.Sysin.RecordType=FBA
P050.IDCAMS.Sysin.RecordLen=80
#
#STEP:P050| PGM:IDCAMS| DD:MODDD2
P050.IDCAMS.MODDD2=UDEV34.CLOUDFRM.MODD2
P050.IDCAMS.MODDD2.DISP=MOD,KEEP,KEEP
P050.IDCAMS.MODDD2.RecordType=VBA
P050.IDCAMS.MODDD2.RecordLen=125
