package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] FORMAT_1223488108 = "-ZZZZ9".toCharArray();
public static final char[] FORMAT_1453061239 = "-9999".toCharArray();
public static final char[] FORMAT_1619390911 = "-ZZZZZZZZ.ZZZZZZ".toCharArray();
public static final char[] FORMAT_2095226196 = "-99999".toCharArray();
public static final char[] FORMAT_301109145 = "-ZZZZZ.ZZZ".toCharArray();
public static final char[] FORMAT_515235511 = "-ZZZZZZZZZZ".toCharArray();
public static final char[] FORMAT_726606776 = "-ZZZZZ9".toCharArray();
public static final char[] LITERAL_12345 = "12345".toCharArray();
public static final char[] LITERAL_2083144459 = "-9876543.21098".toCharArray();
public static final char[] LITERAL_789514350 = "21474836.12345".toCharArray();
public static final char[] LITERAL_9000000000 = "9000000000".toCharArray();
 
}
