<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="Parms1000" cobol:name="1000-PARMS" cobol:offset="0" cobol:length="10" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="ParmLngth1000" type="xs:short" maxOccurs="1"  cobol:name="1000-PARM-LNGTH" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
         <xs:element name="CommitFreq1000" type="xs:long" maxOccurs="1"  cobol:name="1000-COMMIT-FREQ" cobol:offset="2" cobol:length="8" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100M"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
