  package com.cloudframe.app.sort.file;
  /* Java Code Generated by CloudFrame */
  
  import org.springframework.stereotype.Component;
  import com.cloudframe.app.utility.CFFile;
  import org.springframework.beans.factory.annotation.Value;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.utility.CFConstants;
  import org.springframework.batch.core.configuration.annotation.JobScope;
  
  @Component("Sort038Step020SortIn")
  @JobScope
  public class Sort038Step020SortIn extends CFFile {
  	private Logger logger = LoggerFactory.getLogger(Sort038Step020SortIn.class);
  	@Value("${Sort038Step020SortIn:CLOUDFRM.MC.GCMS.SORT.IN0382}")
  	private String fileName;
  
  	/**
  	 * This function is not required in this subclass for your program to work as intended. 
  	 * CloudFrame generated this function to provide you hints for the code you must write 
  	 * to change the implementation and remove runtime and license dependency on CloudFrame. 
  	 * Consult CloudFrame's customer wiki for additional information. https://wiki.cloudframe.com
  	 **/
  	public String getFileName() {
  		return fileName;
  	}
  	
  	/**
  	 * This function is not required in this subclass for your program to work as intended. 
  	 * CloudFrame generated this function to provide you hints for the code you must write 
  	 * to change the implementation and remove runtime and license dependency on CloudFrame. 
  	 * Consult CloudFrame's customer wiki for additional information. https://wiki.cloudframe.com
  	 **/	
  	@Override
  	public  void setFileName(String fileName) {
  		this.fileName = fileName;
  	}	
  
  	@Value("#{'${Sort038Step020SortInRecordType:${Sort038Step020SortInRecordType:FB}}'}")
  	private String recordType;
  
  	@Value("#{'${Sort038Step020SortInRecordLen:${Sort038Step020SortInRecordLen:80}}'}")
  	private int recordLen;
  	
  	public boolean isFBRec() {
    		return (recordType.startsWith("F")); //F/FB/FBA
    	}
  
    
  	public int getRecordLen() {
  		return recordLen;
  	}
  	
  	@Override
  	public void read() {
  		try {
  			super.readRecord();
  		} catch (Exception e) {
  			status = CFConstants.END_OF_FILE;
  			logger.error("Error during Sort038Step020SortIn Read: {}",e.getMessage()); 
  		}
  	}
    
  	
  	public String getStatusString() {
  		if (status == 0) return "00";
  		else if (status == 10) return "10";
  		return String.format("%1$2s", status+"").replace(' ', '0');
  	}
  }
