# Program  : VSAMMON7 | DD : SYSIN | RecordFormat : FixedLength | RecordLength : 80
VSAMMON7.Scanner=SYSIN.bin
VSAMMON7.ScannerCharSet=cp1047
VSAMMON7.ScannerCRLFflag=no
# Program VSAMMON7 | DD : MONITOR | VSAM KSDS
VSAMMON7.ddname.MONITOR=Monitor
# Program VSAMMON7 | DD : REPOUT | RecordFormat : FixedLength | RecordLength : 300
VSAMMON7.ddname.REPOUT=Repout
VSAMMON7.Repout=Repout
VSAMMON7.RepoutCharSet=cp1047
VSAMMON7.RepoutCRLFflag=no
# 
# End of VSAMMON7
