  package com.cloudframe.app.process;
  /* Java code generated by CloudFrame on 2025-04-22 at 07:16. */
  
  import org.springframework.web.bind.annotation.GetMapping;
  import org.slf4j.Logger;
  import org.slf4j.LoggerFactory;
  import com.cloudframe.app.exception.CFException;
  import org.springframework.stereotype.Component;
  import org.springframework.web.bind.annotation.RestController;
  import com.cloudframe.app.utility.CFXmlParser;
  import com.cloudframe.app.exception.Terminate;
  import com.cloudframe.app.utility.CFUtil;
  import com.cloudframe.app.xmlpars2.dto.*;
  import com.cloudframe.app.xmlpars2.dto.Work;
  import com.cloudframe.app.common.CONSTANTS;
  
  @Component("xmlpars2")
  
  public class Xmlpars2 extends CommonProcess {
  
  Logger logger = LoggerFactory.getLogger(Xmlpars2.class);
  
  private Work work = new Work() ;
  
  
  
  
  
  
  char[] xmlEvent = 	CFUtil.pad(30,"SPACE"," ",CFUtil.RIGHT_PAD);
  char[] xmlText = fill(256,CONSTANTS.LOW_VALUE_STRING);
  long xmlCode = 0;
  
  
  
      /**
      * process 
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      @Override
      public int process() throws Exception {
       initVars();
       try {
       setCodePage("1047");
          ;
//  PERFORM 0000-MAINLINE
          mainline();/*0000-MAINLINE*/
          if (this.isProgramEnded()) {
              return getRc();
          }
       } catch(Exception e) {
            handleErrorCode(e);
            throw e;
       }
      
       return getRc(); // Exit with return code
      // end of process method
      }
      /**
      * mainline 
      *   This method is derived from 
  *   COBOL Paragraph - 0000-MAINLINE COBOL Cyclomatic complexity - 2
      * Input  :  

      * - vXml                           COBOL Name: WS-V-XML
      * - xmlCode                        COBOL Name: XML-CODE
      *
      * Output : None 

      * @throws CFException
      */
      private void mainline() throws Exception {
			// Declare local variables used in the method
			CFXmlParser cfXmlParser = null;
			// End of variable declaration

//  DISPLAY '*----------------------------------*'
          logger.info("*----------------------------------*"); 
//  XML PARSE WS-V-XML PROCESSING PROCEDURE IS 0200-PARSE-XML THRU 0200-EXIT
          cfXmlParser = new CFXmlParser(work.getVXml());
          while (cfXmlParser.hasMoreXMLEvent()) {
          	xmlEvent = cfXmlParser.getXmlEvent();
          	xmlText = cfXmlParser.getXmlText();	
          parseXml();
          }
          	if(cfXmlParser.hasException()) {
//  DISPLAY 'XML PROCESS ERROR    ' XML-CODE
              logger.info("XML PROCESS ERROR    {}", String.valueOf(xmlCode)); 
          	}
//  DISPLAY ' '
          logger.info(" "); 
//  DISPLAY 'XML Response:'
          logger.info("XML Response:"); 
//  DISPLAY ' '
          logger.info(" "); 
//cobolCode::GO TO 9999-RETURN
return9999();
 return ;
//cobolCodeEnds::GO TO 9999-RETURN
      
      }
      /**
      * parseXml 
      *   This method is derived from 
  *   COBOL Paragraph - 0200-PARSE-XML COBOL Cyclomatic complexity - 12
      * Input  :  

      * - xmlText                        COBOL Name: XML-TEXT
      *
      * Output :  

      * - elemNm                         COBOL Name: WS-ELEM-NM
      * - xmlText                        COBOL Name: XML-TEXT
      * - elemLen                        COBOL Name: WS-ELEM-LEN
      * - i                              COBOL Name: I
      * - attrLen                        COBOL Name: WS-ATTR-LEN
      * - attrNm                         COBOL Name: WS-ATTR-NM
      *
      * @throws CFException
      */
      private void parseXml() throws Exception {
      
// *---------------------------------------------------------------*

// *---------------------------------------------------------------*
//  EVALUATE XML-EVENT
          switch(new String(xmlEvent)){
          	case "START-OF-ELEMENT":
//  MOVE XML-TEXT TO WS-ELEM-NM
              work.setElemNm(xmlText);
//  MOVE LENGTH OF XML-TEXT TO WS-ELEM-LEN
              work.setElemLen((short) xmlText.length);
//  DISPLAY 'Element Name.....: ' WS-ELEM-NM (1 : WS-ELEM-LEN )
              logger.info("Element Name.....: {}", new String(substring(work.getElemNm(),0,work.getElemLen()))); 
          break;
          	case "CONTENT-CHARACTER":
          
          	case "CONTENT-CHARACTERS":
//  MOVE LENGTH OF XML-TEXT TO I
              work.setI(xmlText.length);
//  DISPLAY 'Element Content..: ' XML-TEXT (1 : I)
              logger.info("Element Content..: {}", new String(substring(xmlText,0,work.getI()))); 
          break;
          	case "END-OF-ELEMENT":
//  MOVE XML-TEXT TO WS-ELEM-NM
              work.setElemNm(xmlText);
//  MOVE LENGTH OF XML-TEXT TO WS-ELEM-LEN
              work.setElemLen((short) xmlText.length);
//  DISPLAY 'End of Element...: ' WS-ELEM-NM (1 : WS-ELEM-LEN )
              logger.info("End of Element...: {}", new String(substring(work.getElemNm(),0,work.getElemLen()))); 
//  DISPLAY '*----------------------------------*'
              logger.info("*----------------------------------*"); 
              // MOVE SPACES TO WS-ELEM-NM
              work.setElemNm(CONSTANTS.SPACE_20);
              // MOVE +0 TO WS-ELEM-LEN
              work.setElemLen((short)0);
          break;
          	case "ATTRIBUTE-NAME":
//  MOVE LENGTH OF XML-TEXT TO WS-ATTR-LEN
              work.setAttrLen((short) xmlText.length);
//  MOVE XML-TEXT TO WS-ATTR-NM
              work.setAttrNm(xmlText);
//  DISPLAY 'Attribute Name...: ' WS-ATTR-NM (1 : WS-ATTR-LEN )
              logger.info("Attribute Name...: {}", new String(substring(work.getAttrNm(),0,work.getAttrLen()))); 
          break;
          	case "ATTRIBUTE-CHARACTER":
          
          	case "ATTRIBUTE-CHARACTERS":
          
          	case "ATTRIBUTE-NATIONAL-CHARACTER":
//  MOVE LENGTH OF XML-TEXT TO I
              work.setI(xmlText.length);
//  DISPLAY 'Attribute Content: ' XML-TEXT (1 : I)
              logger.info("Attribute Content: {}", new String(substring(xmlText,0,work.getI()))); 
//  DISPLAY '*----------------------------------*'
              logger.info("*----------------------------------*"); 
          break;
          	case "NAMESPACE-DECLARATION":
//  MOVE LENGTH OF XML-TEXT TO I
              work.setI(xmlText.length);

// *          Move xml-namespace      to lk-xml-doc(d:i)
//  DISPLAY 'NameSpace Content: ' XML-TEXT (1 : I)
              logger.info("NameSpace Content: {}", new String(substring(xmlText,0,work.getI()))); 
//  DISPLAY '*----------------------------------*'
              logger.info("*----------------------------------*"); 
          break;
          	case "EXCEPTION":
//  MOVE LENGTH OF XML-TEXT TO I
              work.setI(xmlText.length);
//  DISPLAY 'Error: ' XML-TEXT (1 : I)
              logger.info("Error: {}", new String(substring(xmlText,0,work.getI()))); 
//cobolCode::GO TO 9999-RETURN
return9999();
 return ;
//cobolCodeEnds::GO TO 9999-RETURN
          
          }
          ;
      
      }
      /**
      * return9999 
      *   This method is derived from 
  *   COBOL Paragraph - 9999-RETURN COBOL Cyclomatic complexity - 2
      * Input  : None 

      * Output : None 

      * @throws CFException
      */
      private void return9999() throws Exception {
      
// *----------------------------------------------------------------*

// *----------------------------------------------------------------*
//  GOBACK
          setNotLogged(false); // no need to log, it is a normal termination
          this.setProgramEnded(true);
          return ;
      
      }
  
  
      /**
* This method pre-initializes variables consistent with
* what a mainframe program would have done at the start of a program
*/
      @Override
      public void initVars() throws CFException {
      setProgramEnded(false);
          if(!isInitDone()) {
          	this.setRc(0);
          	setInitDone(true);
          }
        CFUtil.resetDecimalAsComma();
       }
  
  
  
  
  
  
  }
