<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="DsmSqlErrorMsgArea" cobol:name="DSM-SQL-ERROR-MSG-AREA" cobol:offset="990" cobol:length="120" cobol:datatype="Group" cobol:hasParent="true" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="DsmErrTblName" maxOccurs="1"  cobol:name="DSM-ERR-TBL-NAME" cobol:offset="0" cobol:length="25" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="25" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DsmErrSectnName" maxOccurs="1"  cobol:name="DSM-ERR-SECTN-NAME" cobol:offset="25" cobol:length="34" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="34" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DsmErrPgmName" maxOccurs="1"  cobol:name="DSM-ERR-PGM-NAME" cobol:offset="59" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DsmErrClngPgmName" maxOccurs="1"  cobol:name="DSM-ERR-CLNG-PGM-NAME" cobol:offset="67" cobol:length="8" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DsmErrTblAction" maxOccurs="1"  cobol:name="DSM-ERR-TBL-ACTION" cobol:offset="75" cobol:length="10" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="DsmErrTxt" maxOccurs="1"  cobol:name="DSM-ERR-TXT" cobol:offset="85" cobol:length="35" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="35" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
