# Program GLOBAL | DD : SYS003 | RecordFormat : VariableLength | MaxRecordLength : 32756
GLOBAL.ddname.SYS003=IpmFile
GLOBAL.IpmFile=IpmFile
GLOBAL.IpmFileCharSet=cp1047
GLOBAL.IpmFileCRLFflag=no
# 
# End of READ0003
# End of READ0004
