<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="TableAreas" cobol:name="TABLE-AREAS" cobol:offset="0" cobol:length="4142" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="TaAdjIndexMax" type="xs:int" maxOccurs="1"  cobol:name="TA-ADJ-INDEX-MAX" cobol:offset="0" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
    <xs:element name="TaAdjTable" maxOccurs="1"  cobol:name="TA-ADJ-TABLE" cobol:offset="3" cobol:length="4100" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="4100" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="TaAdjTableRedefined" maxOccurs="100" cobol:name="TA-ADJ-TABLE-REDEFINED" cobol:offset="3" cobol:length="41" cobol:datatype="Group" cobol:serialize="true" />
    <xs:element name="TaMonthTable" maxOccurs="1"  cobol:name="TA-MONTH-TABLE" cobol:offset="4103" cobol:length="36" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="36" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
<xs:element name="TaMonthTableRedefined" maxOccurs="12" cobol:name="TA-MONTH-TABLE-REDEFINED" cobol:offset="4103" cobol:length="3" cobol:datatype="Group" cobol:serialize="true" />
         <xs:element name="TaMonthIndex" type="xs:int" maxOccurs="1"  cobol:name="TA-MONTH-INDEX" cobol:offset="4139" cobol:length="3" cobol:datatype="Packed-Dec" cobol:signed="true" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100K"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
