package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.data.Field;
import com.cloudframe.app.utility.CFUtil;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] ZERO_1 = CFUtil.fill(1,"0");
public static final char[] LITERAL_0000 = "0000".toCharArray();
public static final char[] LITERAL_0000000000 = "0000000000".toCharArray();
public static final char[] LITERAL_36552 = "|".toCharArray();
public static final char[] LITERAL_END = "END".toCharArray();
public static final char[] LOW_VALUE_1703015924 = Field.fillLowValue(1);
public static final char[] LOW_VALUE_215544411 = Field.fillLowValue(822);
public static final char[] LOW_VALUE_STRING = new String(new byte[]{0}).toCharArray();
public static final char[] MODE_READ_ONLY_36242 = "r".toCharArray();
public static final char[] MODE_READ_WRITE_1126171 = "rw".toCharArray();
public static final char[] MODE_WRITE_ONLY_36397 = "w".toCharArray();
 
}
