#STEP:MPS001| PGM:SORT| DD:SORTIN
MpsMps001SortIn=CLOUDFRM.MC.MPS.SORT.IN001
MpsMps001SortIn.DISP=SHR,KEEP,KEEP
MpsMps001SortInRecordType=FB
MpsMps001SortInRecordLen=256
#STEP:MPS001| PGM:SORT| DD:SORTOUT
MpsMps001SortOut=CLOUDFRM.MC.MPS.SORT.OUT001
MpsMps001SortOut.DISP=NEW,KEEP,KEEP
MpsMps001SortOutRecordType=FB
MpsMps001SortOutRecordLen=80
#STEP:STEP020| PGM:SORT| DD:SORTIN
MpsStep020SortIn=CLOUDFRM.MC.MPS.SORT.IN001
MpsStep020SortIn.DISP=SHR,KEEP,KEEP
MpsStep020SortInRecordType=FB
MpsStep020SortInRecordLen=256
#STEP:STEP020| PGM:SORT| DD:SORTOUT
MpsStep020SortOut=CLOUDFRM.MC.MPS.SORT.OUT001A
MpsStep020SortOut.DISP=NEW,KEEP,KEEP
MpsStep020SortOutRecordType=FB
MpsStep020SortOutRecordLen=256
#STEP:MPS002| PGM:SORT| DD:SORTIN
MpsMps002SortIn=CLOUDFRM.MC.MPS.SORT.IN002
MpsMps002SortIn.DISP=SHR,KEEP,KEEP
MpsMps002SortInRecordType=FB
MpsMps002SortInRecordLen=200
#STEP:MPS002| PGM:SORT| DD:SORTOUT
MpsMps002SortOut=CLOUDFRM.MC.MPS.SORT.OUT002
MpsMps002SortOut.DISP=NEW,KEEP,KEEP
MpsMps002SortOutRecordType=FB
MpsMps002SortOutRecordLen=40
#STEP:MPS003| PGM:SORT| DD:SORTIN
MpsMps003SortIn=CLOUDFRM.MC.MPS.SORT.IN003
MpsMps003SortIn.DISP=SHR,KEEP,KEEP
MpsMps003SortInRecordType=FB
MpsMps003SortInRecordLen=12288
#STEP:MPS003| PGM:SORT| DD:SORTOUT
MpsMps003SortOut=CLOUDFRM.MC.MPS.SORT.OUT003
MpsMps003SortOut.DISP=NEW,KEEP,KEEP
MpsMps003SortOutRecordType=FB
MpsMps003SortOutRecordLen=12288
#STEP:MPS004| PGM:SORT| DD:SORTIN
MpsMps004SortIn=CLOUDFRM.MC.MPS.SORT.IN004
MpsMps004SortIn.DISP=SHR,KEEP,KEEP
MpsMps004SortInRecordType=VB
MpsMps004SortInRecordLen=4096
#STEP:MPS004| PGM:SORT| DD:SORTOF1
MpsMps004SortOut[0]=CLOUDFRM.MC.MPS.SORT.OUT0041
MpsMps004SortOut[0].DISP=NEW,KEEP,KEEP
MpsMps004SortOut0RecordType=VB
MpsMps004SortOut0RecordLen=4096
#STEP:MPS004| PGM:SORT| DD:SORTOF2
MpsMps004SortOut[1]=CLOUDFRM.MC.MPS.SORT.OUT0042
MpsMps004SortOut[1].DISP=NEW,KEEP,KEEP
MpsMps004SortOut1RecordType=VB
MpsMps004SortOut1RecordLen=4096
#STEP:MPS004| PGM:SORT| DD:SORTOF3
MpsMps004SortOut[2]=CLOUDFRM.MC.MPS.SORT.OUT0043
MpsMps004SortOut[2].DISP=NEW,KEEP,KEEP
MpsMps004SortOut2RecordType=FB
MpsMps004SortOut2RecordLen=38
#STEP:MPS005| PGM:SORT| DD:SORTIN01
MpsMps005SortIn[0]=CLOUDFRM.MC.MPS.SORT.IN051
MpsMps005SortIn[0].DISP=SHR,KEEP,KEEP
MpsMps005SortIn0RecordType=FB
MpsMps005SortIn0RecordLen=12288
#STEP:MPS005| PGM:SORT| DD:SORTIN02
MpsMps005SortIn[1]=CLOUDFRM.MC.MPS.SORT.IN052
MpsMps005SortIn[1].DISP=SHR,KEEP,KEEP
MpsMps005SortIn1RecordType=FB
MpsMps005SortIn1RecordLen=12288
#STEP:MPS005| PGM:SORT| DD:SORTIN03
MpsMps005SortIn[2]=CLOUDFRM.MC.MPS.SORT.IN053
MpsMps005SortIn[2].DISP=SHR,KEEP,KEEP
MpsMps005SortIn2RecordType=FB
MpsMps005SortIn2RecordLen=12288
#STEP:MPS005| PGM:SORT| DD:SORTOF1
MpsMps005SortOut[0]=CLOUDFRM.MC.MPS.SORT.OUT051
MpsMps005SortOut[0].DISP=NEW,KEEP,KEEP
MpsMps005SortOut0RecordType=FB
MpsMps005SortOut0RecordLen=12288
#STEP:MPS005| PGM:SORT| DD:SORTOF2
MpsMps005SortOut[1]=CLOUDFRM.MC.MPS.SORT.OUT052
MpsMps005SortOut[1].DISP=NEW,KEEP,KEEP
MpsMps005SortOut1RecordType=FB
MpsMps005SortOut1RecordLen=12288
#STEP:MPS006| PGM:SORT| DD:SORTIN01
MpsMps006SortIn=CLOUDFRM.MC.MPS.SORT.IN061
MpsMps006SortIn.DISP=SHR,KEEP,KEEP
MpsMps006SortInRecordType=FB
MpsMps006SortInRecordLen=12288
#STEP:MPS006| PGM:SORT| DD:SORTOF1
MpsMps006SortOut[0]=CLOUDFRM.MC.MPS.SORT.OUT061
MpsMps006SortOut[0].DISP=NEW,KEEP,KEEP
MpsMps006SortOut0RecordType=FB
MpsMps006SortOut0RecordLen=12288
#STEP:MPS006| PGM:SORT| DD:SORTOF2
MpsMps006SortOut[1]=CLOUDFRM.MC.MPS.SORT.OUT062
MpsMps006SortOut[1].DISP=NEW,KEEP,KEEP
MpsMps006SortOut1RecordType=FB
MpsMps006SortOut1RecordLen=12288
#STEP:MPS006| PGM:SORT| DD:SORTOF3
MpsMps006SortOut[2]=CLOUDFRM.MC.MPS.SORT.OUT063
MpsMps006SortOut[2].DISP=NEW,KEEP,KEEP
MpsMps006SortOut2RecordType=FB
MpsMps006SortOut2RecordLen=12288
#STEP:STEP020_2| PGM:SORT| DD:SORTIN
MpsStep020_2SortIn=CLOUDFRM.MC.MPS.SORT.IN118220
MpsStep020_2SortIn.DISP=SHR,KEEP,KEEP
MpsStep020_2SortInRecordType=FB
MpsStep020_2SortInRecordLen=256
#STEP:STEP020_2| PGM:SORT| DD:SORTOUT
MpsStep020_2SortOut=&&HEADER
MpsStep020_2SortOut.DISP=NEW,PASS,KEEP
MpsStep020_2SortOutRecordType=FB
MpsStep020_2SortOutRecordLen=256
#STEP:STEP040| PGM:SORT| DD:SORTIN
MpsStep040SortIn[0]=&&HEADER
MpsStep040SortIn[0].DISP=SHR,KEEP,KEEP
MpsStep040SortIn0RecordType=FB
MpsStep040SortIn0RecordLen=256
#STEP:STEP040| PGM:SORT| DD:SORTIN
MpsStep040SortIn[1]=CLOUDFRM.MC.MPS.SORT.IN118220
MpsStep040SortIn[1].DISP=SHR,KEEP,KEEP
MpsStep040SortIn1RecordType=FB
MpsStep040SortIn1RecordLen=256
#STEP:STEP040| PGM:SORT| DD:SORTOUT
MpsStep040SortOut=CLOUDFRM.MC.MPS.SORT.OUT11824
MpsStep040SortOut.DISP=NEW,CATLG,DELETE
MpsStep040SortOutRecordType=FB
MpsStep040SortOutRecordLen=256
