STEP050.MS00D363.inputValue='DAILY  ,Y,0010,Y'
#update the inputValue below, that has to be passed to the application, if running as a stand alone
timeZoneId=Etc/GMT
# Program MS00D363 | DD : CERTTEST | RecordFormat : FixedLength | RecordLength : 80
MS00D363.ddname.CERTTEST=CERTTEST.IN
MS00D363.CertificationFile=CERTTEST.IN
MS00D363.CertificationFile.DISP=SHR,KEEP,KEEP
MS00D363.CertificationFileCharSet=cp1047
MS00D363.CertificationFileCRLFflag=no
# Program MS00D363 | DD : RPTKEYS | RecordFormat : FixedLength | RecordLength : 80
MS00D363.ddname.RPTKEYS=RPTKEYS.IN
MS00D363.RptkeyFile=RPTKEYS.IN
MS00D363.RptkeyFile.DISP=SHR,KEEP,KEEP
MS00D363.RptkeyFileCharSet=cp1047
MS00D363.RptkeyFileCRLFflag=no
# Program MS00D363 | DD : SWCHCUR | RecordFormat : FixedLength | RecordLength : 300
MS00D363.ddname.SWCHCUR=SWCHCUR.IN
MS00D363.CurcyFile=SWCHCUR.IN
MS00D363.CurcyFile.DISP=SHR,KEEP,KEEP
MS00D363.CurcyFileCharSet=cp1047
MS00D363.CurcyFileCRLFflag=no
# Program MS00D363 | DD : SWCHAPC | RecordFormat : FixedLength | RecordLength : 350
MS00D363.ddname.SWCHAPC=SWCHAPC.IN
MS00D363.SamapcFile=SWCHAPC.IN
MS00D363.SamapcFile.DISP=SHR,KEEP,KEEP
MS00D363.SamapcFileCharSet=cp1047
MS00D363.SamapcFileCRLFflag=no
# Program MS00D363 | DD : SWCHMCR | RecordFormat : FixedLength | RecordLength : 1400
MS00D363.ddname.SWCHMCR=SWCHMCR.IN
MS00D363.InputFile=SWCHMCR.IN
MS00D363.InputFile.DISP=SHR,KEEP,KEEP
MS00D363.InputFileCharSet=cp1047
MS00D363.InputFileCRLFflag=no
# Program MS00D363 | DD : REPORT | RecordFormat : FixedLength | RecordLength : 270
MS00D363.ddname.REPORT=REPORT.CF.OUT
MS00D363.ReportFile=REPORT.CF.OUT
MS00D363.ReportFile.DISP=NEW,CATLG,DELETE
MS00D363.ReportFileCharSet=cp1047
MS00D363.ReportFileCRLFflag=no
# Program MS00D363 | DD : EXCEL | RecordFormat : FixedLength | RecordLength : 500
MS00D363.ddname.EXCEL=EXCEL.CF.OUT
MS00D363.ExcelFile=EXCEL.CF.OUT
MS00D363.ExcelFile.DISP=NEW,CATLG,DELETE
MS00D363.ExcelFileCharSet=cp1047
MS00D363.ExcelFileCRLFflag=no
# Program MS00D363 | DD : BALFILE | RecordFormat : FixedLength | RecordLength : 200
MS00D363.ddname.BALFILE=BALFILE.IN
MS00D363.OFileBal=BALFILE.IN
MS00D363.OFileBal.DISP=SHR,KEEP,KEEP
MS00D363.OFileBalCharSet=cp1047
MS00D363.OFileBalCRLFflag=no
# 
# End of MS00D363
