STEP1.RETCODE2.inputValue='00001'
STEP2.RETCODE2.inputValue='00002'
STEP3.RETCODE2.inputValue='00003'
STEP4095.RETCODE2.inputValue='00001'
STEP4.RETCODE2.inputValue='00004'
STEP5.RETCODE2.inputValue='00005'
STEP6.RETCODE2.inputValue='00006'
STEP7.RETCODE2.inputValue='00007'
STEP8.RETCODE2.inputValue='00008'
#update the inputValue below, that has to be passed to the application, if running as a stand alone
# 
# End of RETCODE2
# End of RETCODE1
ABEND1.CFABCALL.inputValue='C0789'
# End of CFABCALL
