package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
public class SQLS {
 
public static final char[] SQL_77213668 = "SELECT BOOK_ID , RTRIM ( TITLE ) , TOTAL_PAGES , RATING , ISBN , PUBLISHED_DATE , PUBLISHER_ID FROM BOOKS WITH UR".toCharArray() ;
public static final char[] SQL_982711535 = "SELECT CURRENT_TIMESTAMP FROM SYSIBM.SYSDUMMY1".toCharArray() ;
 
}
