#for running as a server, please comment or delete line below 
spring.main.web-application-type=none
spring.main.lazy-initialization=true
GLOBAL.ddname.XMLDATA=XmlIn
GLOBAL.XmlIn=XmlIn
GLOBAL.XmlInCharSet=cp1047
GLOBAL.XmlInCRLFflag=no
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}.%M %L - %msg%n
HIGH_VALUE=Z
