#STEP:P010| PGM:IEFBR14| DD:FLE1
P010.IEFBR14.Fle1=CLOUDFRM.USB.NCR.DSNAMES
P010.IEFBR14.Fle1.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:FLE2
P010.IEFBR14.Fle2=CLOUDFRM.USB.NCR.NONVSAM
P010.IEFBR14.Fle2.DISP=MOD,DELETE,DELETE
#
#STEP:P010| PGM:IEFBR14| DD:FLE3
P010.IEFBR14.Fle3=CLOUDFRM.USB.NCR.COPYPARM
P010.IEFBR14.Fle3.DISP=MOD,DELETE,DELETE
#
#STEP: P020 | PGM:IDCAMS
P020.IDCAMS.Sysin=CLOUDFRM.USB.NCR.PARMLIB/Y9LSTXML
#STEP: P020 | PGM:IDCAMS
P020.IDCAMS.Sysprint=CLOUDFRM.USB.NCR.DSNAMES
#
#STEP:P030_01| PGM:ICETOOL| DD:FLE1
Usbice01P030_01SortIn=CLOUDFRM.USB.NCR.DSNAMES
Usbice01P030_01SortIn.DISP=SHR,KEEP,KEEP
Usbice01P030_01SortInRecordType=VBA
Usbice01P030_01SortInRecordLen=125
#
#
#STEP:P030_01| PGM:ICETOOL| DD:FLE2
Usbice01P030_01SortOut=CLOUDFRM.USB.NCR.NONVSAM
Usbice01P030_01SortOut.DISP=NEW,CATLG,KEEP
Usbice01P030_01SortOutRecordType=VBA
Usbice01P030_01SortOutRecordLen=125
#
#
#STEP:P030_02| PGM:ICETOOL| DD:FLE2
Usbice01P030_02SortIn=CLOUDFRM.USB.NCR.NONVSAM
Usbice01P030_02SortIn.DISP=SHR,CATLG,KEEP
Usbice01P030_02SortInRecordType=VBA
Usbice01P030_02SortInRecordLen=125
#
#
#STEP:P030_02| PGM:ICETOOL| DD:FLE3
Usbice01P030_02SortOut=CLOUDFRM.USB.NCR.COPYPARM
Usbice01P030_02SortOut.DISP=NEW,CATLG,DELETE
Usbice01P030_02SortOutRecordType=FBA
Usbice01P030_02SortOutRecordLen=80
#
