<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="MaxRrnLimitErr620" cobol:name="620-MAX-RRN-LIMIT-ERR" cobol:offset="0" cobol:length="79" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="MaxRrnLimitErr620Filler1" maxOccurs="1"  cobol:name="FILLER" cobol:offset="0" cobol:length="24" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="24" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="MaxRrnLimit620" type="xs:int" maxOccurs="1"  cobol:name="620-MAX-RRN-LIMIT" cobol:offset="24" cobol:length="2" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100"/>
    <xs:element name="MaxRrnLimitErr620Filler2" maxOccurs="1"  cobol:name="FILLER" cobol:offset="26" cobol:length="20" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="PcCapGrpPtr620" type="xs:long" maxOccurs="1"  cobol:name="620-PC-CAP-GRP-PTR" cobol:offset="46" cobol:length="11" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_100G"/>
    <xs:element name="MaxRrnLimitErr620Filler3" maxOccurs="1"  cobol:name="FILLER" cobol:offset="57" cobol:length="18" cobol:datatype="Display" cobol:serialize="true" cobol:blankWhenZero="false" >
        <xs:simpleType>
            <xs:restriction base="xs:string" cobol:justify="false" >
                  <xs:length value="18" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
         <xs:element name="ActualRrnLimit620" type="xs:int" maxOccurs="1"  cobol:name="620-ACTUAL-RRN-LIMIT" cobol:offset="75" cobol:length="4" cobol:datatype="Disp-Num" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="MAX_10K"/>
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
