<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="OutRec" cobol:name="WS-OUT-REC" cobol:offset="0" cobol:length="32752" cobol:datatype="Grp-VarLen" cobol:hasParent="false" cobol:dependingArrayLen="1" cobol:offsetToVariableArray="2"  >
 <xs:complexType>
   <xs:sequence>
         <xs:element name="OutRecDataLen" type="xs:int" maxOccurs="1"  cobol:name="WS-OUT-REC-DATA-LEN" cobol:offset="0" cobol:length="2" cobol:datatype="Binary" cobol:signed="false" cobol:signLeading="false" cobol:signTrailing="true"  cobol:signSeparate="false" cobol:serialize="true" cobol:max="Long.MAX_VALUE"/>
<xs:element name="OutRecData" maxOccurs="1" cobol:name="WS-OUT-REC-DATA" cobol:offset="2" cobol:length="32750" cobol:datatype="Grp-VarLen" cobol:serialize="true" />
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
