package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
public class SQLS {
 
public static final char[] SQL_221264722 = "UPDATE TIPAPMA SET PRIM_ACCT_SEQ_NUM = ? WHERE CURRENT OF PMA_CURSOR".toCharArray() ;
public static final char[] SQL_438331198 = "SELECT VRTL_ACCT_NUM , PRIM_ACCT_NUM , PRIM_ACCT_SEQ_NUM FROM TIPAPMA WHERE VRTL_ACCT_NUM = ? AND PRIM_ACCT_NUM = ? AND SUBSTR ( ? , LENGTH ( TRIM ( ? ) ) -2 , 3 ) = PARTN_ID FOR UPDATE OF PRIM_ACCT_SEQ_NUM".toCharArray() ;
 
}
