#STEP:SORT002| PGM:SORT| DD:SORTIN
UsbsortSort002SortIn=CLOUDFRM.EPAM.SORT.IN002
UsbsortSort002SortIn.DISP=SHR,KEEP,KEEP
UsbsortSort002SortInRecordType=FB
UsbsortSort002SortInRecordLen=80
#STEP:SORT002| PGM:SORT| DD:OUT1
UsbsortSort002SortOut=CLOUDFRM.EPAM.SORT.OUT002
UsbsortSort002SortOut.DISP=NEW,KEEP,KEEP
UsbsortSort002SortOutRecordType=FB
UsbsortSort002SortOutRecordLen=29
#STEP:SORT003| PGM:SORT| DD:SORTIN
UsbsortSort003SortIn=CLOUDFRM.USB.SORT.IN003
UsbsortSort003SortIn.DISP=SHR,KEEP,KEEP
UsbsortSort003SortInRecordType=FB
UsbsortSort003SortInRecordLen=80
#STEP:SORT003| PGM:SORT| DD:SORTOUT
UsbsortSort003SortOut=CLOUDFRM.USB.SORT.OUT003
UsbsortSort003SortOut.DISP=NEW,KEEP,KEEP
UsbsortSort003SortOutRecordType=FB
UsbsortSort003SortOutRecordLen=80
#STEP:SORT004| PGM:SORT| DD:SORTIN
UsbsortSort004SortIn=CLOUDFRM.VLSCMP.SORT.IN034
UsbsortSort004SortIn.DISP=SHR,KEEP,KEEP
UsbsortSort004SortInRecordType=VB
UsbsortSort004SortInRecordLen=256
#STEP:SORT004| PGM:SORT| DD:SORTOUT
UsbsortSort004SortOut=CLOUDFRM.VLSCMP.SORT.OUT34
UsbsortSort004SortOut.DISP=NEW,KEEP,KEEP
UsbsortSort004SortOutRecordType=VB
UsbsortSort004SortOutRecordLen=256
