<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cobol="http://www.cloudframe.com/COBOLSchema">
<xs:element name="MainHbEqupSurchageOcc06" cobol:name="MAIN-HB-EQUP-SURCHAGE-OCC-06" cobol:offset="0" cobol:length="28" cobol:datatype="Group" cobol:hasParent="false" cobol:dependingArrayLen="0" cobol:offsetToVariableArray="0"  >
 <xs:complexType>
   <xs:sequence>
    <xs:element name="MainHbTotVzwSurchgAmt" maxOccurs="1"  cobol:name="MAIN-HB-TOT-VZW-SURCHG-AMT" cobol:offset="0" cobol:length="10" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="true" cobol:signTrailing="false"  cobol:signSeparate="true" cobol:serialize="true" cobol:max="MAX_10G">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="9" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MainHbFusfRate" maxOccurs="1"  cobol:name="MAIN-HB-FUSF-RATE" cobol:offset="10" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="true" cobol:signTrailing="false"  cobol:signSeparate="true" cobol:serialize="true" cobol:max="MAX_1M">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="5" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MainHbRegulatoryCharg" maxOccurs="1"  cobol:name="MAIN-HB-REGULATORY-CHARG" cobol:offset="16" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="true" cobol:signTrailing="false"  cobol:signSeparate="true" cobol:serialize="true" cobol:max="MAX_1M">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="5" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
    <xs:element name="MainHbVzwAdminChgAmt" maxOccurs="1"  cobol:name="MAIN-HB-VZW-ADMIN-CHG-AMT" cobol:offset="22" cobol:length="6" cobol:datatype="Disp-Num" cobol:signed="true" cobol:signLeading="true" cobol:signTrailing="false"  cobol:signSeparate="true" cobol:serialize="true" cobol:max="MAX_1M">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                  <xs:totalDigits value="5" />
                  <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>        
   </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>
