# Program CFSORT06 | DD : FILEIN | RecordFormat : FixedLength | RecordLength : 30
CFSORT06.ddname.FILEIN=FileIn
CFSORT06.FileIn=FileIn
CFSORT06.FileInCharSet=cp1047
CFSORT06.FileInCRLFflag=no
# Program CFSORT06 | DD : FILEOUT | RecordFormat : FixedLength | RecordLength : 30
CFSORT06.ddname.FILEOUT=FileOut
CFSORT06.FileOut=FileOut
CFSORT06.FileOutCharSet=cp1047
CFSORT06.FileOutCRLFflag=no
# 
# End of CFSORT06
