cf.has.sort=true
cf.sort.useTempFile=no
cf.sort.using.file.strategy=yes
cf_sort_limit_memory_of_heap_percentage=60
cf_sort_inmemorykey_use_sync=true
cf_sort_force_inmemory_strategy=false
cf_sort_force_inmemory_key_strategy=false
cf_sort_force_tempfile_with_record_strategy=false
cf_sort_force_tempfile_strategy=false
cf.jcl.batch=true