#update the inputValue below, that has to be passed to the application, if running as a stand alone
inputValue=''
inputValue1=
inputValue2=
inputValue3=
timeZoneId=Etc/GMT
AR640010.dbQualifier=
# 
# End of AR640010
